### ISSUE TITLE
[Unity] ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by wbb21230** [Tencent/puerts#1001]
## detail | 详细描述
问题描述，websocket 有提示在lib.dom.d.ts但是运行不了
我是windows，npm i ws 有引用但websocket无法运行，编译到引用websocket的脚本就不编译了，想用ts的websocket，要怎么解决呢

**Comment by zombieyang** [comment]
1. d.ts只是代码提示，并不意味着你的js环境包含这个能力。Puer本身是不带有浏览器DOM API的。
2. 如果使用的是PuerTS的Node.js Plugins，那你执行`npm i ws`之后可以按照它的文档来调用（但不是按照lib.dom.d.ts的接口来调，是根据ws包自己的接口来调，这两个是不一样的）
3. 如果你用的不是Node.js Plugin，那JS环境里是没有websocket支持的。但你可以在C#引入WebSocket库并在JS端调用
