### ISSUE TITLE
[Unity] System.DateTime.UtcNow

### ISSUE THREAD

**Issue by wbb21230** [Tencent/puerts#1014]
TS 获取的System.DateTime.UtcNow 和CS的不一样

**Comment by zombieyang** [comment]
测试了一下，时间值是一样的。你是指打印出来的字符串值不一样么？
C#的DateTime传到JS这边会转化成JS的Date，功能是一样的

**Comment by wbb21230** [comment]
> 

打印处理的的不一样，都调用的是c#时间类，我在C#里打印System.DateTime.UtcNow.ToString()

**Comment by wbb21230** [comment]
打印处理的的不一样，都调用的是c#时间类，我在C#里打印System.DateTime.UtcNow.ToString("yyyy-MM-dd hh:mm")
在ts相同方法，两个相差四小时
![image](https://user-images.githubusercontent.com/49426786/194696155-3e1cc21b-ae9c-4cd1-9e12-06a605e0648f.png)

**Comment by wbb21230** [comment]
> 测试了一下，时间值是一样的。你是指打印出来的字符串值不一样么？ C#的DateTime传到JS这边会转化成JS的Date，功能是一样的

在ts里System.DateTime.UtcNow已经是经过处理了已经是js的utc了？js的utc是相差四个小时

**Comment by zombieyang** [comment]
utcNow到了JS侧应该是没有 `ToString` 方法的，因为这时候已经转换成JS的 Date对象了，JS的Date对象没有大写打头的ToString方法。
或者你把你代码贴一下看看

<img width="371" alt="image" src="https://user-images.githubusercontent.com/5595819/194734487-5a60d529-5d3f-4f9b-a5ce-78c74f6117f3.png">
这个是我试出来的结果，代码如下
```
            Debug.Log(System.DateTime.UtcNow.ToString("yyyy-MM-dd hh:mm"));
            jsEnv.Eval(@"
                console.log(CS.System.DateTime.UtcNow.toUTCString());
            ");
```

**Comment by wbb21230** [comment]
> 
ToString是我扩展Date的，用不用扩展的这个打印处理都是一样的（不用的时候已完全注释掉扩展），相差几个小时
![image](https://user-images.githubusercontent.com/49426786/194736065-f44e9e80-b646-4d09-9750-4a41f3af8fe0.png)
![image](https://user-images.githubusercontent.com/49426786/194735796-f9395534-1943-41cb-8029-c8929af7d622.png)
#           Debug.Log("c#的Utc:"+System.DateTime.UtcNow.ToString("yyyy-MM-dd hh:mm"));
            _jsEnv.Eval(@"
                const CS = require('csharp');
                CS.UnityEngine.Debug.Log('ts的Utc3:'+CS.System.DateTime.UtcNow);
            ");

**Comment by wbb21230** [comment]
> 

加个函数，toUTCString()是可以输出一样的，不理解的是System.DateTime.UtcNow获取的怎么就不一样

**Comment by zombieyang** [comment]
其实是一样的。
你可以看到JS打印的时间里有标注 `GMT+0800`。意思是该时间串是东八区的时间。C#打印的时间里则没有，代表它是格林尼治时间。
但这两个Date，所表达的时刻是一样的。
