### ISSUE TITLE
[UE] suggestion world.SpawnActor方法无法调用

### ISSUE THREAD

**Issue by ladyishenlong** [Tencent/puerts#1017]
## detail | 详细描述

let world = (argv.getByName("GameInstance") as UE.GameInstance).GetWorld();
let actor = world.SpawnActor(UE.MainActor.StaticClass(), undefined, UE.ESpawnActorCollisionHandlingMethod.Undefined, undefined, undefined) as UE.MainActor;

在ReceiveBeginPlay中无法调用world.SpawnActor方法，可以给一个例子吗？

**Comment by chexiongsheng** [comment]
怎么个“无法调用”法？

**Comment by ladyishenlong** [comment]
> 怎么个“无法调用”法？

Property 'SpawnActor' does not exist on type 'World'.

**Comment by ladyishenlong** [comment]
> 怎么个“无法调用”法？

https://github.com/Tencent/puerts/issues/1017#issuecomment-1272478291

**Comment by ladyishenlong** [comment]
Property 'SpawnActor' does not exist on type 'World'.

**Comment by ladyishenlong** [comment]
我记得生成actor是蓝图的方法，这个还要自己写c++代码去实现吗？我看其他的issue里面也有提到，不过我不会写c++所以不太懂具体该怎么做，是否有详细的教程

**Comment by ladyishenlong** [comment]
UE.GameplayTask_SpawnActor.SpawnActor("","","","")这个方法可以代替吗，如果可以的话taskowner该怎么传？

**Comment by chexiongsheng** [comment]
demo扩展了这方法，扩展方法在文档里头有：https://puerts.github.io/unreal/zhcn/extension_methods
不过这是过时的方式了，现在建议通过模板绑定：https://puerts.github.io/unreal/zhcn/template_binding

**Comment by chexiongsheng** [comment]
如果你想SpawnActor，也不用像demo那样自己扩展。用蓝图的方法就可以了。
