### ISSUE TITLE
[Feature Request] 生成引擎 API 时导出文档信息

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#102]
如果生成的 API 能够带 JSDoc 格式的文档将能很大程度上方便开发，减少很多查引擎API的时间。

**Comment by jihuayu** [comment]
引擎 API 的文档可以从哪里获取？这个东西反射拿不到吧？是不是只能解析源代码？

**Comment by Geequlim** [comment]
VSCode 之类的的IDE是如何取得到的？

**Comment by jihuayu** [comment]
ide 是会在后台下载源代码吧？
难道 C# 编译完还会保存注释吗？

**Comment by littlesome** [comment]
需要自己解析对应的xml，Unity的dll都自带了，自己的需要指定编译参数，可以参考这里https://github.com/ialex32x/unity-jsb/issues/12

**Comment by ialex32x** [comment]
搬过来了😄 https://github.com/Tencent/puerts/pull/104 不过排版有点麻烦

**Comment by chexiongsheng** [comment]
排版也ok了
