### ISSUE TITLE
[Unity] 歧义重载方法依然生成了dts。

### ISSUE THREAD

**Issue by Ninian4155** [Tencent/puerts#1020]
public void PlaySound(string uid, int tag = 0, Action onCompleted = default, bool cover = true)
        public void PlaySound(string uid,Action onCompleted = default)

类似这样定义的c#重载方法，存在调用歧义，但生成的dts里依然两者都存在。

**Comment by zombieyang** [comment]
typescript里像上述的情况，并不会有“歧义”的错误，因为javascript本无重载。
目前DTS生成逻辑里也无“重载“这个概念。

如果要修复，dts里就不能用一两个函数+默认参数的形式生成方法了，要变成为每个重载生成一个方法。
改动会比较大，这个case比较小，因此先记着，看后续有机会再修复吧。

**Comment by zombieyang** [comment]
fccf3f6419fe7b470ae921d42153105b0038a69f
a0306cf97f15af6e4ea33e5542a853c165885876
干脆支持了歧义方法的调用。选择逻辑为：选择第一个合适的overload，和反射时保持一致。
后续再看看有无必要优先选择无默认参数overload
