### ISSUE TITLE
[Unity] puerts_unity_demo 打ios包必闪退

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1022]
puerts版本：1.4.0-rc.2
unity版本：2021.3.9f
手机：iphone12pro ios16
## how to reproduce | 复现步骤
1. 生成绑定，用demo发布ios
2. 用xcode发到手机上，xcode连着demo进程时候不会闪退
3. xcode点击stop
4. 手机点demo icon启动（不要用xcode启动） 直接闪退。

通过打断点发现
![image](https://user-images.githubusercontent.com/3063621/196235461-e8d41071-60ae-4582-919a-4ab412a99b3f.png)
是在这一步直接闪退

附上奔溃日志

[log.txt](https://github.com/Tencent/puerts/files/9802810/log.txt)

**Comment by chexiongsheng** [comment]
ios 16 + nodejs ?

**Comment by dunadain** [comment]
v8，尝试了直接把v8版本放到assets中 也是闪退。奇怪的是，xcode连着进程就能正常跑。xcode断开，直接手机点开应用就闪退

**Comment by dunadain** [comment]
> ios 16 + nodejs ?

v8，尝试了直接把v8版本放到assets中 也是闪退。奇怪的是，xcode连着进程就能正常跑。xcode断开，直接手机点开应用就闪退

**Comment by dunadain** [comment]
> > ios 16 + nodejs ?
> 
> 尝试了直接把v8版本放到assets中 也是闪退。奇怪的是，xcode连着进程就能正常跑。xcode断开，直接手机点开应用就闪退

重新测试了下 确实是nodejs版本 闪退

**Comment by chexiongsheng** [comment]
> > > ios 16 + nodejs ?
> > 
> > 
> > 尝试了直接把v8版本放到assets中 也是闪退。奇怪的是，xcode连着进程就能正常跑。xcode断开，直接手机点开应用就闪退
> 
> 重新测试了下 确实是nodejs版本 闪退

v8版本没事？

**Comment by zombieyang** [comment]
测试ios13.3也会出现。v8是好的

**Comment by chexiongsheng** [comment]
崩溃在v8 api调用上，怀疑是nodejs16.16.0集成的v8不支持ios
可以试试这个版本的nodejs：https://github.com/puerts/backend-nodejs/releases/tag/NodeJS_220811

**Comment by zombieyang** [comment]
@dunadain 可以尝试一下`rc.6`版本，我这边能复现一样的现象的问题，已经修复。但我和你的crash栈并不同，不确定是否是同一个问题。

**Comment by dunadain** [comment]
> 

好的

**Comment by dunadain** [comment]
> @dunadain 可以尝试一下`rc.6`版本，我这边能复现一样的现象的问题，已经修复。但我和你的crash栈并不同，不确定是否是同一个问题。

可以了 不闪退了
