### ISSUE TITLE
[Unity] promise使用task作为参数报错

### ISSUE THREAD

**Issue by StarryGaming** [Tencent/puerts#1027]
## how to reproduce | 复现步骤
1.unity端生成代码
2.TS代码有报错，purets版本是1.3.7，之前用旧版本的没问题。
![webwxgetmsgimg1](https://user-images.githubusercontent.com/18264857/197324561-7ec45217-387d-4d5e-8f5e-77755383233b.jpg)
![webwxgetmsgimg](https://user-images.githubusercontent.com/18264857/197324567-42318515-8f9d-4315-8702-fefb5e3034cc.jpg)

![webwxgetmsgimg2](https://user-images.githubusercontent.com/18264857/197324570-5bbd4b3e-6dcd-4840-a5c0-41d16f65fad6.jpg)

**Comment by zombieyang** [comment]
已复现，async function生成出来有问题

**Comment by zombieyang** [comment]
1.3.x版本不怎么发版了，不升1.4的话自行魔改进去即可

**Comment by StarryGaming** [comment]
好吧 谢谢啦
