### ISSUE TITLE
[UE] 4.27 Linux nodejs backend windows交叉编译链接失败

### ISSUE THREAD

**Issue by haowang1013** [Tencent/puerts#1029]
## error log | 日志或报错信息

其中的一个连接错误，其他的类似就不重复了

`    ld.lld: error: undefined symbol: node::CreateEnvironment(node::IsolateData*, v8::Local<v8::Context>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, node::EnvironmentFlags::Flags, node::ThreadId, std::__1::unique_ptr<node::InspectorParentHandle, std::__1::default_delete<node::InspectorParentHandle> >)
    >>> referenced by JsEnvImpl.cpp:478 (D:/work/directivegames/ScriptingTest/Plugins/puerts/Puerts/Source/JsEnv/Private\JsEnvImpl.cpp:478)
    >>>               D:/work/directivegames/ScriptingTest/Intermediate/Build/Linux/B4D820EA/ScriptingTestServer/Development/JsEnv/Module.JsEnv.2_of_3.cpp.o:(puerts::FJsEnvImpl::FJsEnvImpl(std::__1::shared_ptr<puerts::IJSModuleLoader>, std::__1::shared_ptr<puerts::ILogger>, int, std::__1::function<void (FString const&)>, void*, void*))`

## context | 编译/运行环境

4.27源码，C++ template项目，选择nodejs然后交叉编译到Linux Server.
V8后端没问题但是项目原因只能用nodejs

**Comment by chexiongsheng** [comment]
node::CreateEnvironment是最基本的函数，看上去没链接到nodejs的linux库。
链接的是libnode.so，你看看有没有，有的话和你的系统是不是匹配的
https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/JsEnv.Build.cs#L473

**Comment by marospekarik** [comment]
@haowang1013 - did you figure out the issue?

**Comment by chexiongsheng** [comment]
我查了下libnode的符号，发现有node::CreateEnvironment，但有细微差别
~~~bash
nm -C libnode.so.93 |grep CreateEnvironment
0000000001778810 T v8::internal::Bootstrapper::CreateEnvironment(v8::internal::MaybeHandle<v8::internal::JSGlobalProxy>, v8::Local<v8::ObjectTemplate>, v8::ExtensionConfiguration*, unsigned long, v8::DeserializeInternalFieldsCallback, v8::MicrotaskQueue*)
0000000000aed360 T node::CreateEnvironment(node::IsolateData*, v8::Local<v8::Context>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::EnvironmentFlags::Flags, node::ThreadId, std::unique_ptr<node::InspectorParentHandle, std::default_delete<node::InspectorParentHandle> >)
~~~

stl类，在我编译的libnode.so是std::__cxx11，而UE交叉编译需要的std::__1，应该是编译链接的libc++版本不同所致。

**Comment by chexiongsheng** [comment]
这有相关的提问：https://forums.unrealengine.com/t/demangled-used-std-basic-string-but-i-need-std-basic-string/408345/6

**Comment by chexiongsheng** [comment]
原因是linux下编译默认用的是libstdc++。
而ue要求的是libc++。
已经解决，下载这个版本可以编译通过：https://github.com/puerts/backend-nodejs/releases/tag/NodeJS_16.16.0_230209
