### ISSUE TITLE
I want infomation about runtime speed compless native or xLua

### ISSUE THREAD

**Issue by kyubuns** [Tencent/puerts#103]
I'm worry about the speed at runtime.
I would like some information about xLua and how it compares to C# natives.

**Comment by kyubuns** [comment]
当我试用时，它比C#的简单计算快。
访问UnityEngine的速度比C#慢100倍左右，但可以接受。
如果有人将其与xLua等进行比较，我想听听结果。
https://gist.github.com/kyubuns/d8755b5bf8a68f28c70e7f8a82b47f4e

**Comment by chexiongsheng** [comment]
You can ask questions in English

**Comment by kyubuns** [comment]
It was auto-translated Chinese, so I rewrote it into English.

**Comment by chexiongsheng** [comment]
puerts using chrome v8 as script backend. compare to lua, v8 api is heavier，and have to wrap to c api for unity, so the interaction with C# is slower, but v8 itself is better than lua overall.
interaction with C#：slower than xLua, but it's acceptable I think, and we will continue to improve it.
script execution:  close to native expect ios.

**Comment by kyubuns** [comment]
Thanks
