### ISSUE TITLE
[Unity] hotreload 与debug并行时，有一方会不生效

### ISSUE THREAD

**Issue by kbl531476264** [Tencent/puerts#1033]
## context | 编译/运行环境
使用了最新api16的版本到最新，调试和hotreload同时运行时，debugerRuntime已经都能跑起来了，但是调试生效，hotreload不生效，查明是hotreload在于chome的ws交互时，ws的onMessage不会抛数据回来（ws处于连接状态）

**Comment by zombieyang** [comment]
这个问题在apilevel 18以上修的，即1.4.0-rc.0以上
