### ISSUE TITLE
[[UE5] 打包Windows, 蓝图BeginPlay时调用父类TS函数无效

### ISSUE THREAD

**Issue by MrBaoquan** [Tencent/puerts#1038]
## 问题描述:
蓝图类MainPlayer继承代理蓝图TS_Player,  在BeginPlay 时调用父类TS_Player下任何函数均无效(大部分情况下均不生效, 打包后第一次运行有效)，延迟一些时间后均有效。(Note: MainPlayer蓝图是直接拖拽到场景中的, AutoPossess  Player 0)

![image](https://user-images.githubusercontent.com/36908656/198924420-e59f8854-b166-45b1-92fb-9bb31b0f0cf3.png)

**Comment by MrBaoquan** [comment]
编辑器下是可以的，打包后出的问题

**Comment by MrBaoquan** [comment]
再次验证: 蓝图MainPlayer不拖拽到场景中， 通过GamePlay框架正常启动没有问题。 所以就是直接拖拽到场景中后出的问题

**Comment by chexiongsheng** [comment]
试试关闭AsyncLoadingThreadEnabled
