### ISSUE TITLE
[UE] suggestion 怎么使用UE.TSoftClassPtr类型的TArray或者TMap呢

### ISSUE THREAD

**Issue by justinlm** [Tencent/puerts#1043]
## detail | 详细描述
代码如下：
```ts
 Init(): void {
        let actorMap = UE.NewMap(UE.Blueprint, UE.TSoftClassPtr<UE.Actor>)

        let actorArray = UE.NewArray(UE.TSoftClassPtr<UE.Actor>)
    }
```

但是是会报错的

![puerts_Array](https://user-images.githubusercontent.com/764048/199689396-e63dcce5-ec18-4fd2-80ed-7ae000fa7323.png)

错误如下：
Property 'TSoftClassPtr' does not exist on type 'typeof import("ue")'. Did you mean 'SoftClassPath'?ts(2551)
ue.d.ts(5671, 11): 'SoftClassPath' is declared here.

所以想问问，是不能这么用吗，那不是就不能软引用不是就很蛋疼了呀 ><

**Comment by chexiongsheng** [comment]
不支持
