### ISSUE TITLE
[UE] suggestion ts 如何调用StaticLoadObject 

### ISSUE THREAD

**Issue by mimiky** [Tencent/puerts#1046]
## detail | 详细描述
用扩展类的话  参数里面像TCHAR UFUNCTION编译不了

**Comment by chexiongsheng** [comment]
每个类都有个Load函数，那个函数相当于以那个类为参数1调用StaticLoadObject。

非反射的c++ api现在不需要用扩展类，用模版绑定。

**Comment by mimiky** [comment]
好的 谢谢解惑
