### ISSUE TITLE
[Unity] suggestion 希望能改善Puerts.ILoader的接口设计，因为同样的搜寻文件逻辑要在FileExists和ReadFile中都实现一遍

### ISSUE THREAD

**Issue by ankisme** [Tencent/puerts#1061]
## detail | 详细描述
我去年刚开始接触puerts时就觉得这个接口实现起来很繁琐，现在因为一些原因又要被迫接触这个接口，有点难受

Puerts.ILoader接口有2个方法FileExists和ReadFile

这导致了同样的搜寻文件逻辑要在FileExists和ReadFile中都实现一遍，而且对性能也有损耗

FileExists已经搜了一遍文件夹，判断文件是否存在，如果存在，ReadFile又要去搜一遍，然后再去读取文件内容

我觉得对于这种新手一上来就必须实现的接口，要直观且便于实现，而现在Puerts.ILoader接口虽然直观，但不便于实现

所以希望能改善一下Puerts.ILoader的接口设计

我期望的接口是像下面这样的代码，或者官方设计一个更好的，只要便于实现就行

```c#
namespace Puerts
{
    // 当前的接口
    public interface ILoader
    {
        bool FileExists(string filepath);
        string ReadFile(string filepath, out string debugpath);
    }
}
```

```c#
public class PuertsFile
{
    public string debugpath; // debug路径
    public string fileText; // 文件内容
}

namespace Puerts
{
    // 我感觉比较好用的接口，不优雅，但是接口实现起来更方便
    public interface ILoader
    {
        // 参数filepath：文件路径
        // 参数isNeedReadFile：是否读取文件内容，为false时不需要填写debugpath和fileText
        // 返回值：文件内容，为null时表示文件不存在
        PuertsFile ReadFile(string filepath, bool isNeedReadFile);
    }
}
```

**Comment by zombieyang** [comment]
v2会改，计划会弄成类似dictionary的tryGetValue那种形式。由有无out参数决定取内容，同时out参数的类型决定是字节码（quickjs）还是文本

**Comment by ankisme** [comment]
了解了解

**Comment by zombieyang** [comment]
新增加了 `IResolvableLoader` 这个interface，内含`string Resolve(string specifier, string from)`函数。

实现了该接口的Loader，`ReadFile`的参数为`Resolve`函数的返回而不再是原始import符号。`Resolve`返回null或空串等同于以前`FileExists`返回false
