### ISSUE TITLE
[Unity][Question]  What is the best practices of implement interface of c# in JS?

### ISSUE THREAD

**Issue by NilanZxR** [Tencent/puerts#1062]
## detail | 详细描述 

If I have a method in c# like this:
```c#
// need a interface as argument
public void Attack(IDamageable target, int damageValue){}

// a interface can be hurt
public interface IDamageable{
    int HP {get; set;}
    void Hurt(int value);
}
```

What is the best way to use `Attack` in javasciprt?

The only way I can think of is create a JSDamageable.cs like this:
```c#
public class JsDamageable : IDamageable{
    public delegate int HPGetter();
    public delegate void HPSetter(int value);
    public delegate void HurtHandler(int value);
    public JSDamageable(HPGetter js_get_HP,HPSetter js_set_HP,HurtHandler js_Hurt ){
         this.js_get_HP = js_get_HP;
         this.js_set_HP = js_Set_HP;
         this.js_Hurt = js_Hurt;
    }
    // IDamageable
    public HP { get=>js_get_HP(); set=> js_set_HP(value); }
    public void Hurt(int value) => js_Hurt(value);
}
```
Is there any way better to do it?

In our current project, we use xlua as the logic script
A xlua capability is convert a lua table to interface of c#, and it almost like a real c# object
Does it possible in puer? or in the feature?

Hope to get an answer, thanks a lot.

**Comment by zombieyang** [comment]
not any commended good practice by us yet. It's a hard problem. I think it should use `JSObject` to do some object converting to implement this indirectly.

related issue: 
#548

**Comment by NilanZxR** [comment]
all right, anyway, thank you for answer. 
hope it improve in the future.

closing
