### ISSUE TITLE
[UE] 如何New一个元素是UE枚举的TArray

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1064]
函数SphereTraceSingleForObjects有个参数需要传递一个TAttray<UE.EObjectTypeQuery>类型的枚举数组，请问在TS里面如何构造出来？

**Comment by chexiongsheng** [comment]
跟Actor那些一样

**Comment by ljporljp** [comment]
ts提示报错，NewArray的SupprtedContainerKVType不支持ue的枚举

**Comment by ljporljp** [comment]
> 跟Actor那些一样
ts提示报错，NewArray的SupprtedContainerKVType不支持ue的枚举

**Comment by chexiongsheng** [comment]
> > 跟Actor那些一样
> 
> ts提示报错，NewArray的SupprtedContainerKVType不支持ue的枚举

亲测这样写没报错
let a0 = UE.NewArray(UE.EObjectTypeQuery);
