### ISSUE TITLE
[UE] question Mixin UE.Actor 之后ReceiveTick函数怎么才能有效

### ISSUE THREAD

**Issue by 9000miles** [Tencent/puerts#1066]
## detail | 详细描述

export interface MixinActor extends UE.Actor {
};

export class MixinActor {
    Constructor() {
        this.PrimaryActorTick.bCanEverTick = true;
    }
    ReceiveBeginPlay(): void {
        console.log("MixinActor->ReceiveBeginPlay")//OK，可以正常输出
    }
    ReceiveTick(DeltaSeconds: number): void {
        console.log("MixinActor->ReceiveTick")//不会输出
    }
}

blueprint.mixin(UE.Actor, MixinActor)

mixin 之后，ReceiveTick 函数没有反应，请问怎样做Tick函数才有效

**Comment by chexiongsheng** [comment]
mixin没有Constructor

**Comment by Xian-Yun-Jun** [comment]
> mixin没有Constructor

把这个this.PrimaryActorTick.bCanEverTick = true;移动到ReceiveBeginPlay()，Tick函数也没有被调用

**Comment by chexiongsheng** [comment]
这个标记该什么时候设置看ue文档

**Comment by vmtest888** [comment]
> > mixin没有Constructor
> 
> 把这个this.PrimaryActorTick.bCanEverTick = true;移动到ReceiveBeginPlay()，Tick函数也没有被调用

+1
