### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by qiujm1993** [Tencent/puerts#1076]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.2

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

编译错误：
1、GenHeaders.h中 #include "Matinee/MatineeActor.h" MatineeActor已经被移除
2、JSGeneratedClass.cppLine274中UJSGeneratedClass::Restore函数
    OrphanedClass->ClassAddReferencedObjects = Class->AddReferencedObjects;
现在已经改为struct FUObjectCppClassStaticFunctions其中包括一个AddReferencedObjectsType修改后编译通过

结果：
虽然编译通过并且脚本可以正常输出，但是在TypeScript创建继承于自定义UObject类的时候输出Log Puerts: Display: Bind module [ClassPath],紧接着就输出LogClass: Warning: Failed to bind native function ClassName.Function

### 问题重现 | Bug reproduce

编译即可重现
![image](https://user-images.githubusercontent.com/11519907/202837768-fe16fcda-df1b-463f-b6df-c920c8e23451.png)

**Comment by qiujm1993** [comment]
我有看到[#513](https://github.com/Tencent/puerts/issues/513)这个问题是说Failed是因为手动修改过自动创建的蓝图并保存的问题，发现重新生成后没有报这个警告了，但是不知道UE5.1是否还有其它兼容问题

**Comment by chexiongsheng** [comment]
5.1才正式发布没几天。
先修改到能编译通过吧。
那个Failed to bind native function按之前的经验是没影响的。

**Comment by mahao1997** [comment]
JSGeneratedClass.cppLine274:
OrphanedClass->ClassAddReferencedObjects = Class->AddReferencedObjects;
改成
OrphanedClass->CppClassStaticFunctions = Class->CppClassStaticFunctions;

**Comment by chexiongsheng** [comment]
> 遇到了同样的问题，请问提到的第二点怎么修改能编译通过呢？

好几个月前就改了，更新下就可以
