### ISSUE TITLE
[Unity-v2][Feature] source-map支持

### ISSUE THREAD

**Issue by zombieyang** [Tencent/puerts#1083]
## detail | 详细描述
如同现有FAQ里所说的那样，只需要添加 source-map-support 包即可。
source-map-support是MIT协议的，可以直接拿过来放进包里，并且将Node.js相关的调用删掉。
* fs和path改为自己实现或者调用unityAPI。
* source-map-support中对node uncaughtException的处理可以删掉

**Comment by chexiongsheng** [comment]
尽可能别把别的包直接搞进来，这和开源协作方式相违背。后续被搞进来的包的新修改要怎么同步呢？会不会影响到不需要用这个包的人呢？
即使是希望便利用户，也是用手脚架之类的方式比较好。

**Comment by zombieyang** [comment]
参见deno和ts-node，都是包含这个东西的，没有这个东西，打出来的栈依旧是js而不是ts的
可以说是100%人都会用到的功能。比如像hot-reload不是100%，就不合入了

**Comment by chexiongsheng** [comment]
游戏也不太一样。
公司内就有个项目想把js代码加载后，里头源码信息占的内存给优化掉。更别论让他们再加载个sourcemap了。
在移动端内存占用是关键指标，内存超了系统直接把你干掉了，deno和ts-node都没应用在移动平台上。
可以有这么个功能，但必须可选。

其次，v2.0.0 仅仅专注于il2cpp版本，其它的东西先放下。我觉得能把il2cpp版本的功能对齐现有功能就相当不错了。

**Comment by zombieyang** [comment]
source-map显然是一个Editor上更实用的功能，移动端当然不会默认开

**Comment by chexiongsheng** [comment]
如果仅Editor可以
