### ISSUE TITLE
[Unity-v2] 内置TS编译

### ISSUE THREAD

**Issue by zombieyang** [Tencent/puerts#1084]
## detail | 详细描述
类似deno的做法，既然是所有用户都会用到的功能，考虑加入。

另外的一些：
* 可以通过transformer实现的一些功能
  1. 针对泛型调用自动生成$generic语句（确认可做）
  2. out/ref 参数处理（待确认）

* 配套loader
  1. executemodule时直接执行ts文件。editor下实时编译
  2. 打包时，将ts编译成js再交还用户处理（比如走ab、addressable等）

**Comment by chexiongsheng** [comment]
优先级不高。先搞完其它的再看。

其次js也要支持，不能只支持ts。动态类型语言在原型开发有优势，而且某些场合也是js比较方便。

**Comment by chexiongsheng** [comment]
别安排在2.0.0

2.0.0仅专注于il2cpp。别各种述求相互影响，导致最重要的il2cpp优化迟迟出不了正式版。
