### ISSUE TITLE
[UE] Bug: UE5.1 点击UE.d.ts 报错 无法生成ts

### ISSUE THREAD

**Issue by mimiky** [Tencent/puerts#1098]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

latest

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

![16696331933972](https://user-images.githubusercontent.com/44563230/204265319-7fd5acbe-228c-45a4-b28c-9d540fde8699.png)

### 问题重现 | Bug reproduce

4.27.2更新到5.1 替换最新的puerts 点击生成报错

**Comment by mimiky** [comment]
`void FTypeScriptDeclarationGenerator::LoadAllWidgetBlueprint(FName SearchPath)
{
    FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(FName("AssetRegistry"));
    IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();

    FName PackagePath = (SearchPath == NAME_None) ? FName(TEXT("/Game")) : SearchPath;

    FARFilter BPFilter;
    BPFilter.PackagePaths.Add(PackagePath);
    BPFilter.bRecursivePaths = true;
    BPFilter.bRecursiveClasses = true;
    BPFilter.ClassPaths.Add	(FTopLevelAssetPath(TEXT("/Script/Engine"), TEXT("Blueprint")));
    BPFilter.ClassPaths.Add(FTopLevelAssetPath(UUserDefinedEnum::StaticClass()));
    BPFilter.ClassPaths.Add(FTopLevelAssetPath(UUserDefinedStruct::StaticClass()));

    AssetRegistry.GetAssets(BPFilter, AssetList);
    for (FAssetData const& AssetData : AssetList)
    {
        const FAssetPackageData* PackageData = AssetRegistry.GetAssetPackageData(AssetData.PackageName);
        auto BlueprintTypeDeclInfoPtr = BlueprintTypeDeclInfoCache.Find(AssetData.PackageName);

        if (PackageData && BlueprintTypeDeclInfoPtr)
        {
            auto FileVersion = PackageData->PackageGuid.ToString();
            BlueprintTypeDeclInfoPtr->IsExist = true;
            BlueprintTypeDeclInfoPtr->Changed = FileVersion != BlueprintTypeDeclInfoPtr->FileVersionString;
            BlueprintTypeDeclInfoPtr->FileVersionString = FileVersion;
        }
        else
        {
            BlueprintTypeDeclInfoCache.Add(AssetData.PackageName,
                {TEXT(""), PackageData ? PackageData->PackageGuid.ToString() : FString(TEXT("")), true, true});
        }
    }
}`
将DeclarationGenerator.cpp此处方法中ClassName 替换 ClassPaths替换 已解决问题

**Comment by chexiongsheng** [comment]
建议提个PR过来
