### ISSUE TITLE
是否有关于v8与lua垃圾回收性能的对比？

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/puerts#11]
因为我之前做过cocos2d-js开发，当时的js引擎是spridemonkey，游戏开发到后期遇到了GC过于频繁的问题，在lua里面比较常见的table(比如Vector2)在js里面都要使用池。
想知道v8的垃圾回收性能与lua对比如何？在网上我没有搜索到相关的文章。
如果没有的话能否提供相关的测试对比，或者讨论一下测试思路我来实现一下？

**Comment by chexiongsheng** [comment]
lua的gc不是极其简陋么？至少5.4之前都没分代gc，5.4据说有。
而v8在服务器上都有使用，应该gc做得可以的。
