### ISSUE TITLE
[Unity] Bug: 某些缺乏更新的win7机器报：DllNotFoundException: puerts

### ISSUE THREAD

**Issue by Halliwood** [Tencent/puerts#1104]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

PuerTS_V8_1.4.0-rc.6

### Unity的版本 | Unity Version

2019.4.18f1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

这个错误目前只在部分没有安装某项关键更新的**win7 PC**上发现：
![image](https://user-images.githubusercontent.com/860632/204470469-e4dedb61-6671-42b7-be60-ea54174ce66a.png)
已排除是plugin设置、打包等各种原因，在目标机器上加载dll失败，我自己写了个小程序在目标机器上load puerts.dll:
```c++
#include "stdafx.h"
#include "windows.h"
#include "WinBase.h"
#include <iostream>


int main()
{
	const TCHAR* szDllPath = _T("puerts.dll");
	HMODULE hModule = ::LoadLibrary(szDllPath);

	if (hModule)
	{
		std::cout << "Load library successed!";
	}
	else
	{
		DWORD error = GetLastError();
		std::cout << "Load library failed! error: " << error;
	}
	int x;
	std::cin >> x;
    return 0;
}
```
弹出如下错误：`无法定位程序输入点 EventSetInformation 于动态链接库ADVAPI32.dll 上。`
我用dumpbin分别查看我运行正常的PC上的advapi32.dll，确实可以看到export了EventSetInformation：
![image](https://user-images.githubusercontent.com/860632/204471724-2f8d9426-a1b2-4062-aec2-3b513bfd4979.png)
而出错的PC上的dll没有这个api。
网上有提到这个错误，但都是让安装windows更新：
https://github.com/tauri-apps/tauri/issues/5163
https://www.ghostarrow.com/age-of-empires-ii-definitive-edition-eventsetinformation-advapi32-dll-error

我安装了一些更新，要么安装失败，要么安装了也没效果~直接在根目录下放了正确版本的advapi32.dll也无济于事，似乎始终默认加载`C:\Windows\System32`中的版本~

### 问题重现 | Bug reproduce

在带有旧版本advapi32.dll的PC机器上，使用puerts就可重现。

**Comment by zombieyang** [comment]
所有backend都会么，还是只有node.js

**Comment by Halliwood** [comment]
> 所有backend都会么，还是只有node.js

这个我没测试，明天测试一下~我用的是`PuerTS_V8_1.4.0-rc.6`，为啥backend不是V8而是nodejs~~

**Comment by Halliwood** [comment]
补充一个Process Monitor日志，确实很多dll都不对劲~
![企业微信截图_16697265885968](https://user-images.githubusercontent.com/860632/204535068-a705f454-be40-4174-b2e5-03ddae4195d3.png)

**Comment by Halliwood** [comment]
下面这个是我在正常的win10机器上的Process Monitor
![image](https://user-images.githubusercontent.com/860632/204535354-d604371e-56f0-4d9f-af9d-5327a1dbdc51.png)
看到一个似乎类似的问题：
https://monorail-prod.appspot.com/p/chromium/issues/detail?id=1216311
![image](https://user-images.githubusercontent.com/860632/204535494-15557ae3-f291-447b-befd-3cb2b6263897.png)

**Comment by Halliwood** [comment]
> 

另外，问题应该不仅仅局限于上述提及的那个`advapi32.dll`，我从一台正常的win7上拷贝了正常的`advapi32.dll`，不会弹找不到EventSetInformation了，但是loadlibrary还是返回错误码126。从上述Process Monitor也可印证这一点。
附上Process Monitor的日志链接：[Logfile(1).PML](http://jd.res.4366game.com/testurl/ttt/Logfile(1).PML)

**Comment by chexiongsheng** [comment]
链接的机器环境和你的环境不一样导致的吧
你可以试试自己在win7同样的环境编译一份。

**Comment by Halliwood** [comment]
我在目标win7机器上编译了一份puerts.dll，但无法解决问题。（v8 backend的编译我没试，在win7上整太麻烦了）。最后通过安装以下补丁解决了这个问题：
Windows6.1-KB3080149-x64.msu
https://www.microsoft.com/zh-CN/download/confirmation.aspx?id=48636

**Comment by chexiongsheng** [comment]
一个内部项目也碰到这问题
实测这个和v8的版本有关，8.4没有ADVAPI32.dll的依赖，9.4有（nodejs 16是用v8 9.4）。基于最新代码，分别链接8.4和9.4，用dumpbin /dependents查依赖
9.4如下：
```bash
dumpbin /dependents build_win_x64_v8_9.4.146.24_debug\RelWithDebInfo\puerts.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30154.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file build_win_x64_v8_9.4.146.24_debug\RelWithDebInfo\puerts.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    ADVAPI32.dll
    WS2_32.dll
    MSWSOCK.dll
    WINMM.dll
    dbghelp.dll

```

8.4如下
```bash
dumpbin /dependents build_win_x64_v8_debug\RelWithDebInfo\puerts.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30154.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file build_win_x64_v8_debug\RelWithDebInfo\puerts.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    WS2_32.dll
    MSWSOCK.dll
    WINMM.dll
    dbghelp.dll

```
