### ISSUE TITLE
[UE] Bug: 继承引擎类BlueprintFunctionLibrary 生成的蓝图库供蓝图调用，PIE模式下正常，打包后无法调用到对应的js方法，也没有报错

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1107]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

没有错误信息，只是无法调用到js函数内部，调用本身没有报错

### 问题重现 | Bug reproduce

```
class TS_BlueprintFunctionLibrary extends BlueprintFunctionLibrary {
    /**
     * 显示警告提示
     */
    static ShowWarningTip(sn: number): void {
        WarningTipModule.ShowTip(sn);
    }
}
```

类似这种代码  生成了蓝图并且在蓝图中调用，PIE中正常 ，但是打了win64包后 就无法调用到js内部了。

**Comment by chexiongsheng** [comment]
报什么错么？

**Comment by lzj10** [comment]
没有报错信息，只是蓝图调用方法 没有进js的逻辑

**Comment by chexiongsheng** [comment]
1.0是不是有点老了？你试试更新到最新版本看看？
