### ISSUE TITLE
[Unity] Bug: Ts 内创建Dictionary，$generic(System.Collections.Generic.Dictionary$2, System.String, System.Object)，设置float类型会丢弃小数部分

### ISSUE THREAD

**Issue by Lychee2022** [Tencent/puerts#1115]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4.0

### Unity的版本 | Unity Version

2021.3.14f1c1

### 发生在哪个平台 | Platform

All

### 问题重现 | Bug reproduce

`let DictionaryAny = $generic(System.Collections.Generic.Dictionary$2, System.String, System.Object);`
 ` let customThinkparams = new DictionaryAny<string, any>();`
  ` customThinkparams.Add("test",0.99);`
   ` let a =customThinkparams.get_Item("test");`
   ` console.log(a);`
如上使用方式输出是0，老版本都可以正常输出0.99

**Comment by zombieyang** [comment]
修复 
44b0e28c10f46f2c09aa69ed0e351eabc52345b8
测试用例 720dfd83d6f9f73d25321d0ef611360673d605bf

可以直接魔改进你的代码。版本稍晚发布
