### ISSUE TITLE
[Unity] Bug: 

### ISSUE THREAD

**Issue by Icekettle** [Tencent/puerts#1118]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

PuerTS_V8_1.4.0

### Unity的版本 | Unity Version

2022.2.0b16.112.5806

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

打开Unity官方的DOTS的Demo后，加入PuerTS,并执行菜单Generate Code后，有如下的编译错误：

Assets\Gen\AutoStaticCodeRegister.cs(222,50): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(33,97): error CS0619: 'Camera.RenderRequestMode' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(38,25): error CS0619: 'Camera.RenderRequestMode' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(38,70): error CS0619: 'Camera.RenderRequestMode' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(42,42): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(47,76): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(72,97): error CS0619: 'Camera.RenderRequestMode' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(72,262): error CS0619: 'Camera.RenderRequestOutputSpace' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(77,25): error CS0619: 'Camera.RenderRequestMode' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(77,70): error CS0619: 'Camera.RenderRequestMode' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(79,25): error CS0619: 'Camera.RenderRequestOutputSpace' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(79,77): error CS0619: 'Camera.RenderRequestOutputSpace' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(83,42): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(88,76): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(104,42): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(109,76): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(117,91): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(137,28): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(152,28): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(167,28): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_Camera_RenderRequest_Wrap.cs(182,28): error CS0619: 'Camera.RenderRequest' is obsolete: 'The RenderRequest struct is obsolete, use the function overload with RequestData of supported types such as RenderPipeline.StandardRequest'

Assets\Gen\UnityEngine_ArticulationBody_Wrap.cs(3429,17): error CS0619: 'ArticulationBody.jointAcceleration.set' is obsolete: 'Setting joint accelerations is not supported in forward kinematics. To have inverse dynamics take acceleration into account, use GetJointForcesForAcceleration instead'

### 问题重现 | Bug reproduce

1.Windows10下安装Unity 2022.2.0b16.112.5806版本。
2.从https://github.com/Unity-Technologies/EntityComponentSystemSamples下载Unity官方的ECS示例工程。
3.将PuerTS_V8_1.4.0导入Unity。
4.从Unity执行菜单Generate Code。

**Comment by zombieyang** [comment]
https://puerts.github.io/unity/zhcn/wrapper/filter
这个应该可以解决

**Comment by Icekettle** [comment]
> https://puerts.github.io/unity/zhcn/wrapper/filter 这个应该可以解决

非常感谢，问题解决了；在Config.cs里排除掉编译出错的那几个类就行了：

//需要排除的类型
    static List<string> excludeTypes = new List<string>
    {
      ...
        "UnityEngine.Camera.RenderRequest",//Obsolete
        "UnityEngine.ArticulationBody",//Obsolete
        ...
 };
