### ISSUE TITLE
[UE] Bug: UE.Class.Load一个带有Widget的Actor的蓝图类，Actor生成正常，获取widget对象名称，异常

### ISSUE THREAD

**Issue by VegetableWithChicken** [Tencent/puerts#1122]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

latest

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

`Puerts: Error: (0x0000040FFD294470) call TSPawn_C::ReceiveBeginPlay of 0000040FE6207D00 fail: D:\UnrealProjects\SDK_Script\TS_learning\Content\JavaScript\TSGamePlay\TSPawn.js:39: TypeError: Cannot read property 'GetName' of undefined
TypeError: Cannot read property 'GetName' of undefined
    at Object.ReceiveBeginPlay (D:\UnrealProjects\SDK_Script\TS_learning\Content\JavaScript\TSGamePlay\TSPawn.js:39:31)
LogGameState: Match State Changed from WaitingToStart to InProgress
PIE: Server logged in`

### 问题重现 | Bug reproduce

1. 创建一个带有Widget组件的Actor蓝图类  
2. TS脚本里面，加载和生成  
3. 打印widget的名称，getname,返回上面异常

**Comment by chexiongsheng** [comment]
群里你自己找到原因了，没finishedspawaningactor
