### ISSUE TITLE
[Unity] Bug: 运行时，CreateInspector崩溃

### ISSUE THREAD

**Issue by WesleyWangFei** [Tencent/puerts#1124]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

14

### Unity的版本 | Unity Version

2021.3.15f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

Obtained 256 stack frames.
#0  0x00000180ca98be in asio::detail::kqueue_reactor::allocate_descriptor_state()
#1  0x00000180ca964f in asio::detail::reactive_socket_service_base::do_open(asio::detail::reactive_socket_service_base::base_implementation_type&, int, int, int, std::__1::error_code&)
#2  0x00000180ca92f0 in websocketpp::transport::asio::endpoint<websocketpp::config::asio::transport_config>::listen(asio::ip::basic_endpoint<asio::ip::tcp> const&, std::__1::error_code&)
#3  0x00000180ca0df9 in puerts::V8InspectorClientImpl::V8InspectorClientImpl(int, v8::Local<v8::Context>)
#4  0x00000180ca2c9b in puerts::CreateV8Inspector(int, void*)
#5  0x00000180c88a7c in puerts::JSEngine::CreateInspector(int)
#6  0x000001a09f52a2 in  (wrapper managed-to-native) Puerts.PuertsDLL:CreateInspector (intptr,int) [{0x7f81c46ce010} + 0xe2]  (0x1a09f51c0 0x1a09f538b) [0x1712bfa80 - Unity Child Domain]
#7  0x000001a09beb1b in  Kunpo.JsEngine:.ctor (Kunpo.JsRunner,Puerts.ILoader,int) [{0x7f81d41ec420} + 0x4db] [/Library/Project/KunpoGame/TravelString/TravelString/Assets/Kunpo/Source/Puerts/JsEngine.cs :: 113u] (0x1a09be640 0x1a09bec2b) [0x1712bfa80 - Unity Child Domain]
#8  0x00000000000000 in (Unknown)
#9  0x00000000000000 in (Unknown)
#10 0x007f81c1b9d788 in (Unknown)
#11 0x007f81c1b9d788 in (Unknown)
#12 0x007f81c1b9d788 in (Unknown)
#13 0x007f81c1b9d788 in (Unknown)
#14 0x007f81c1b9d788 in (Unknown)
#15 0x007f81c1b9d788 in (Unknown)
#16 0x007f81c1b9d788 in (Unknown)
#17 0x007f81c1b9d788 in (Unknown)
#18 0x007f81c1b9d788 in (Unknown)
#19 0x007f81c1b9d788 in (Unknown)
#20 0x007f81c1b9d788 in (Unknown)
#21 0x007f81c1b9d788 in (Unknown)
#22 0x007f81c1b9d788 in (Unknown)
#23 0x007f81c1b9d788 in (Unknown)
#24 0x007f81c1b9d788 in (Unknown)
#25 0x007f81c1b9d788 in (Unknown)
#26 0x007f81c1b9d788 in (Unknown)
#27 0x007f81c1b9d788 in (Unknown)
#28 0x007f81c1b9d788 in (Unknown)
#29 0x007f81c1b9d788 in (Unknown)
#30 0x007f81c1b9d788 in (Unknown)
#31 0x007f81c1b9d788 in (Unknown)
#32 0x007f81c1b9d788 in (Unknown)
#33 0x007f81c1b9d788 in (Unknown)
#34 0x007f81c1b9d788 in (Unknown)
#35 0x007f81c1b9d788 in (Unknown)
#36 0x007f81c1b9d788 in (Unknown)
#37 0x007f81c1b9d788 in (Unknown)
#38 0x007f81c1b9d788 in (Unknown)
#39 0x007f81c1b9d788 in (Unknown)
#40 0x007f81c1b9d788 in (Unknown)
#41 0x007f81c1b9d788 in (Unknown)
#42 0x007f81c1b9d788 in (Unknown)
#43 0x007f81c1b9d788 in (Unknown)
#44 0x007f81c1b9d788 in (Unknown)
#45 0x007f81c1b9d788 in (Unknown)
#46 0x007f81c1b9d788 in (Unknown)
#47 0x007f81c1b9d788 in (Unknown)
#48 0x007f81c1b9d788 in (Unknown)
#49 0x007f81c1b9d788 in (Unknown)
#50 0x007f81c1b9d788 in (Unknown)
#51 0x007f81c1b9d788 in (Unknown)
#52 0x007f81c1b9d788 in (Unknown)
#53 0x007f81c1b9d788 in (Unknown)
#54 0x007f81c1b9d788 in (Unknown)
#55 0x007f81c1b9d788 in (Unknown)
#56 0x007f81c1b9d788 in (Unknown)
#57 0x007f81c1b9d788 in (Unknown)
#58 0x007f81c1b9d788 in (Unknown)
#59 0x007f81c1b9d788 in (Unknown)
#60 0x007f81c1b9d788 in (Unknown)
#61 0x007f81c1b9d788 in (Unknown)
#62 0x007f81c1b9d788 in (Unknown)
#63 0x007f81c1b9d788 in (Unknown)
#64 0x007f81c1b9d788 in (Unknown)
#65 0x007f81c1b9d788 in (Unknown)
#66 0x007f81c1b9d788 in (Unknown)
#67 0x007f81c1b9d788 in (Unknown)
#68 0x007f81c1b9d788 in (Unknown)
#69 0x007f81c1b9d788 in (Unknown)
#70 0x007f81c1b9d788 in (Unknown)
#71 0x007f81c1b9d788 in (Unknown)
#72 0x007f81c1b9d788 in (Unknown)
#73 0x007f81c1b9d788 in (Unknown)
#74 0x007f81c1b9d788 in (Unknown)
#75 0x007f81c1b9d788 in (Unknown)
#76 0x007f81c1b9d788 in (Unknown)
#77 0x007f81c1b9d788 in (Unknown)
#78 0x007f81c1b9d788 in (Unknown)
#79 0x007f81c1b9d788 in (Unknown)
#80 0x007f81c1b9d788 in (Unknown)
#81 0x007f81c1b9d788 in (Unknown)
#82 0x007f81c1b9d788 in (Unknown)
#83 0x007f81c1b9d788 in (Unknown)
#84 0x007f81c1b9d788 in (Unknown)
#85 0x007f81c1b9d788 in (Unknown)
#86 0x007f81c1b9d788 in (Unknown)
#87 0x007f81c1b9d788 in (Unknown)
#88 0x007f81c1b9d788 in (Unknown)
#89 0x007f81c1b9d788 in (Unknown)
#90 0x007f81c1b9d788 in (Unknown)
#91 0x007f81c1b9d788 in (Unknown)
#92 0x007f81c1b9d788 in (Unknown)
#93 0x007f81c1b9d788 in (Unknown)
#94 0x007f81c1b9d788 in (Unknown)
#95 0x007f81c1b9d788 in (Unknown)
#96 0x007f81c1b9d788 in (Unknown)
#97 0x007f81c1b9d788 in (Unknown)
#98 0x007f81c1b9d788 in (Unknown)
#99 0x007f81c1b9d788 in (Unknown)
#1000x007f81c1b9d788 in (Unknown)
#1010x007f81c1b9d788 in (Unknown)
#1020x007f81c1b9d788 in (Unknown)
#1030x007f81c1b9d788 in (Unknown)
#1040x007f81c1b9d788 in (Unknown)
#1050x007f81c1b9d788 in (Unknown)
#1060x007f81c1b9d788 in (Unknown)
#1070x007f81c1b9d788 in (Unknown)
#1080x007f81c1b9d788 in (Unknown)
#1090x007f81c1b9d788 in (Unknown)
#1100x007f81c1b9d788 in (Unknown)
#1110x007f81c1b9d788 in (Unknown)
#1120x007f81c1b9d788 in (Unknown)
#1130x007f81c1b9d788 in (Unknown)
#1140x007f81c1b9d788 in (Unknown)
#1150x007f81c1b9d788 in (Unknown)
#1160x007f81c1b9d788 in (Unknown)
#1170x007f81c1b9d788 in (Unknown)
#1180x007f81c1b9d788 in (Unknown)
#1190x007f81c1b9d788 in (Unknown)
#1200x007f81c1b9d788 in (Unknown)
#1210x007f81c1b9d788 in (Unknown)
#1220x007f81c1b9d788 in (Unknown)
#1230x007f81c1b9d788 in (Unknown)
#1240x007f81c1b9d788 in (Unknown)
#1250x007f81c1b9d788 in (Unknown)
#1260x007f81c1b9d788 in (Unknown)
#1270x007f81c1b9d788 in (Unknown)
#1280x007f81c1b9d788 in (Unknown)
#1290x007f81c1b9d788 in (Unknown)
#1300x007f81c1b9d788 in (Unknown)
#1310x007f81c1b9d788 in (Unknown)
#1320x007f81c1b9d788 in (Unknown)
#1330x007f81c1b9d788 in (Unknown)
#1340x007f81c1b9d788 in (Unknown)
#1350x007f81c1b9d788 in (Unknown)
#1360x007f81c1b9d788 in (Unknown)
#1370x007f81c1b9d788 in (Unknown)
#1380x007f81c1b9d788 in (Unknown)
#1390x007f81c1b9d788 in (Unknown)
#1400x007f81c1b9d788 in (Unknown)
#1410x007f81c1b9d788 in (Unknown)
#1420x007f81c1b9d788 in (Unknown)
#1430x007f81c1b9d788 in (Unknown)
#1440x007f81c1b9d788 in (Unknown)
#1450x007f81c1b9d788 in (Unknown)
#1460x007f81c1b9d788 in (Unknown)
#1470x007f81c1b9d788 in (Unknown)
#1480x007f81c1b9d788 in (Unknown)
#1490x007f81c1b9d788 in (Unknown)
#1500x007f81c1b9d788 in (Unknown)
#1510x007f81c1b9d788 in (Unknown)
#1520x007f81c1b9d788 in (Unknown)
#1530x007f81c1b9d788 in (Unknown)
#1540x007f81c1b9d788 in (Unknown)
#1550x007f81c1b9d788 in (Unknown)
#1560x007f81c1b9d788 in (Unknown)
#1570x007f81c1b9d788 in (Unknown)
#1580x007f81c1b9d788 in (Unknown)
#1590x007f81c1b9d788 in (Unknown)
#1600x007f81c1b9d788 in (Unknown)
#1610x007f81c1b9d788 in (Unknown)
#1620x007f81c1b9d788 in (Unknown)
#1630x007f81c1b9d788 in (Unknown)
#1640x007f81c1b9d788 in (Unknown)
#1650x007f81c1b9d788 in (Unknown)
#1660x007f81c1b9d788 in (Unknown)
#1670x007f81c1b9d788 in (Unknown)
#1680x007f81c1b9d788 in (Unknown)
#1690x007f81c1b9d788 in (Unknown)
#1700x007f81c1b9d788 in (Unknown)
#1710x007f81c1b9d788 in (Unknown)
#1720x007f81c1b9d788 in (Unknown)
#1730x007f81c1b9d788 in (Unknown)
#1740x007f81c1b9d788 in (Unknown)
#1750x007f81c1b9d788 in (Unknown)
#1760x007f81c1b9d788 in (Unknown)
#1770x007f81c1b9d788 in (Unknown)
#1780x007f81c1b9d788 in (Unknown)
#1790x007f81c1b9d788 in (Unknown)
#1800x007f81c1b9d788 in (Unknown)
#1810x007f81c1b9d788 in (Unknown)
#1820x007f81c1b9d788 in (Unknown)
#1830x007f81c1b9d788 in (Unknown)
#1840x007f81c1b9d788 in (Unknown)
#1850x007f81c1b9d788 in (Unknown)
#1860x007f81c1b9d788 in (Unknown)
#1870x007f81c1b9d788 in (Unknown)
#1880x007f81c1b9d788 in (Unknown)
#1890x007f81c1b9d788 in (Unknown)
#1900x007f81c1b9d788 in (Unknown)
#1910x007f81c1b9d788 in (Unknown)
#1920x007f81c1b9d788 in (Unknown)
#1930x007f81c1b9d788 in (Unknown)
#1940x007f81c1b9d788 in (Unknown)
#1950x007f81c1b9d788 in (Unknown)
#1960x007f81c1b9d788 in (Unknown)
#1970x007f81c1b9d788 in (Unknown)
#1980x007f81c1b9d788 in (Unknown)
#1990x007f81c1b9d788 in (Unknown)
#2000x007f81c1b9d788 in (Unknown)
#2010x007f81c1b9d788 in (Unknown)
#2020x007f81c1b9d788 in (Unknown)
#2030x007f81c1b9d788 in (Unknown)
#2040x007f81c1b9d788 in (Unknown)
#2050x007f81c1b9d788 in (Unknown)
#2060x007f81c1b9d788 in (Unknown)
#2070x007f81c1b9d788 in (Unknown)
#2080x007f81c1b9d788 in (Unknown)
#2090x007f81c1b9d788 in (Unknown)
#2100x007f81c1b9d788 in (Unknown)
#2110x007f81c1b9d788 in (Unknown)
#2120x007f81c1b9d788 in (Unknown)
#2130x007f81c1b9d788 in (Unknown)
#2140x007f81c1b9d788 in (Unknown)
#2150x007f81c1b9d788 in (Unknown)
#2160x007f81c1b9d788 in (Unknown)
#2170x007f81c1b9d788 in (Unknown)
#2180x007f81c1b9d788 in (Unknown)
#2190x007f81c1b9d788 in (Unknown)
#2200x007f81c1b9d788 in (Unknown)
#2210x007f81c1b9d788 in (Unknown)
#2220x007f81c1b9d788 in (Unknown)
#2230x007f81c1b9d788 in (Unknown)
#2240x007f81c1b9d788 in (Unknown)
#2250x007f81c1b9d788 in (Unknown)
#2260x007f81c1b9d788 in (Unknown)
#2270x007f81c1b9d788 in (Unknown)
#2280x007f81c1b9d788 in (Unknown)
#2290x007f81c1b9d788 in (Unknown)
#2300x007f81c1b9d788 in (Unknown)
#2310x007f81c1b9d788 in (Unknown)
#2320x007f81c1b9d788 in (Unknown)
#2330x007f81c1b9d788 in (Unknown)
#2340x007f81c1b9d788 in (Unknown)
#2350x007f81c1b9d788 in (Unknown)
#2360x007f81c1b9d788 in (Unknown)
#2370x007f81c1b9d788 in (Unknown)
#2380x007f81c1b9d788 in (Unknown)
#2390x007f81c1b9d788 in (Unknown)
#2400x007f81c1b9d788 in (Unknown)
#2410x007f81c1b9d788 in (Unknown)
#2420x007f81c1b9d788 in (Unknown)
#2430x007f81c1b9d788 in (Unknown)
#2440x007f81c1b9d788 in (Unknown)
#2450x007f81c1b9d788 in (Unknown)
#2460x007f81c1b9d788 in (Unknown)
#2470x007f81c1b9d788 in (Unknown)
#2480x007f81c1b9d788 in (Unknown)
#2490x007f81c1b9d788 in (Unknown)
#2500x007f81c1b9d788 in (Unknown)
#2510x007f81c1b9d788 in (Unknown)
#2520x007f81c1b9d788 in (Unknown)
#2530x007f81c1b9d788 in (Unknown)
#2540x007f81c1b9d788 in (Unknown)
#2550x007f81c1b9d788 in (Unknown)

### 问题重现 | Bug reproduce

正常运行启动中就崩溃了

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/changelog.md#140-preview6---2022-07-25
这个版本修复了该问题
