### ISSUE TITLE
Unity子类重载基类方法时, index.d.ts声明文件报错, 无法正常执行tsc编译

### ISSUE THREAD

**Issue by layerpsr** [Tencent/puerts#113]
当子类重载基类的方法时, 生成的d.ts声明异常<类型XX中的属性“method1”不可分配给基类型XX中的同一属性>, tsc编译将会报错(如下图所示)
![image](https://user-images.githubusercontent.com/45587825/101876307-2cbc4a00-3bc7-11eb-8a92-5ee1e73dcbda.png)

解决方法: 在子类中将重载的方法重新声明一次(如下图所示)
![image](https://user-images.githubusercontent.com/45587825/101876334-35ad1b80-3bc7-11eb-8cc9-d6fbb1329e04.png)

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/commit/89fdc603fcbaf4eeaa5654a9637d7b15dfa451a9

**Comment by zgz682000** [comment]
貌似又出现这个问题了，麻烦车大神帮忙看一下
![image](https://user-images.githubusercontent.com/9474727/147645159-9f14c8fb-5bf2-4cf1-9f5b-7b2874cf8c9a.png)
![image](https://user-images.githubusercontent.com/9474727/147645173-1a1d3a25-5e3c-414f-98e2-83c5c0866a9b.png)
