### ISSUE TITLE
[Unity] Bug: ExecuteModule 如果返回的是个类不能用JSObject接 

### ISSUE THREAD

**Issue by shanxiaoda** [Tencent/puerts#1144]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4

### Unity的版本 | Unity Version

2021

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

InvalidCastException: Specified cast is not valid.

### 问题重现 | Bug reproduce

JSObject js = jsEnv.ExecuteModule<JSObject>(this.jsScript, "class name");

**Comment by shanxiaoda** [comment]
提重了

**Comment by zombieyang** [comment]
#1143
