### ISSUE TITLE
[UE] Bug: require("../../Script/Config/Config.json")导入json失败

### ISSUE THREAD

**Issue by Xian-Yun-Jun** [Tencent/puerts#1149]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Master最新版本

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

之前还好好地，插件更新到最新版之后，有如下错误
Error: can not find ../../Script/Config/Config.json in ../../../../../../UnrealProjects/TestPuerts/Content/JavaScript/System/Setting

### 问题重现 | Bug reproduce

require("../../Script/Config/Config.json")，使用这种方式导入json文件失败

**Comment by chexiongsheng** [comment]
你用的是nodejs版本？

**Comment by chexiongsheng** [comment]
你之前没问题的版本是哪个？

**Comment by Xian-Yun-Jun** [comment]
> 你用的是nodejs版本？

nodejs：18.10.0
之前的插件版本：[Unreal_v1.0.1](https://github.com/Tencent/puerts/releases/tag/Unreal_v1.0.1)
这次更新只更新了，Puerts插件，其他的都没有改变

**Comment by chexiongsheng** [comment]
我说的nodejs版本指的是你用的是nodejs版本的puerts。

v1.0.1和master差太远了。

或者你直接提供个能重新的简单例子

**Comment by Xian-Yun-Jun** [comment]
从UMyGameInstance::StartGameInstance()启动 Start.ts 脚本  require一个json文件，然后输出json的内容
Plugins/Puerts-OK.zip是Unreal_v1.0.1版本，导入json是没问题的
Plugins/Puerts_NotOK.zip是最近更新到Master最新，导入json失败
下面是我的测试工程：
https://ys-workspace.oss-cn-chengdu.aliyuncs.com/RequireJson.zip?Expires=1672917964&OSSAccessKeyId=TMP.3Kfi2PQ1kNi5aDCUCGREgrcXkF6S8Tu882fsa4uDUrB1defdcxBgt13CnHmwoYAuU26zi5gcTPXZamx7cgGHuUthLAm8Rg&Signature=8dKNAY1ewpleaP8JpSvJmbUrjxE%3D

**Comment by Xian-Yun-Jun** [comment]
> 我说的nodejs版本指的是你用的是nodejs版本的puerts。
> 
> v1.0.1和master差太远了。
> 
> 或者你直接提供个能重新的简单例子

下面链接我提供一个测试工程，只需要切换Plugins里面的Puerts插件就可以运行看到结果，麻烦看下，谢谢

从UMyGameInstance::StartGameInstance()启动 Start.ts 脚本 require一个json文件，然后输出json的内容
Plugins/Puerts-OK.zip是Unreal_v1.0.1版本，导入json是没问题的
Plugins/Puerts_NotOK.zip是最近更新到Master最新，导入json失败
下面是我的测试工程：
https://ys-workspace.oss-cn-chengdu.aliyuncs.com/RequireJson.zip

**Comment by chexiongsheng** [comment]
你那工程下载不了。
建议fork一份这个工程：https://github.com/chexiongsheng/puerts_unreal_demo ，在此基础上修改？

**Comment by Xian-Yun-Jun** [comment]
> 你那工程下载不了。 建议fork一份这个工程：https://github.com/chexiongsheng/puerts_unreal_demo ，在此基础上修改？

不好意思，那个下载链接失效了，我从这儿（https://github.com/chexiongsheng/puerts_unreal_demo）fork 了一个，然后把我的项目上传到Releases了，你可以从那儿下载
https://github.com/Xian-Yun-Jun/puerts_unreal_demo
![image](https://user-images.githubusercontent.com/37586630/211444385-adb0bf12-1c64-4000-a666-30f88bb73be5.png)

如果还是不行，麻烦从百度云盘下载一下
链接：https://pan.baidu.com/s/1-tr3jpsMk625NTpYarGoGQ 
提取码：0fb9

**Comment by chexiongsheng** [comment]
fork一份然后改其实是出于安全的考虑。
否则我得先看你写了啥才敢运行。

**Comment by Xian-Yun-Jun** [comment]
> fork一份然后改其实是出于安全的考虑。 否则我得先看你写了啥才敢运行。
已经同步到你最新的插件，添加了测试代码，麻烦看下
我也在这demo项目测试过，把插件Puerts换成Unreal_v1.0.1版本是OK的，其他任何东西都没修改
![image](https://user-images.githubusercontent.com/37586630/211719474-7c8872c7-3435-4f6f-87b0-6b8e3f710fc6.png)

https://github.com/Xian-Yun-Jun/puerts_unreal_demo

**Comment by Xian-Yun-Jun** [comment]
> fork一份然后改其实是出于安全的考虑。 否则我得先看你写了啥才敢运行。

已经同步到你最新的插件，添加了测试代码，麻烦看下
我也在这demo项目测试过，把插件Puerts换成Unreal_v1.0.1版本是OK的，其他任何东西都没修改
![image](https://user-images.githubusercontent.com/37586630/211719775-56dd6dfe-c0a4-4c58-b66e-4437c176d250.png)
https://github.com/Xian-Yun-Jun/puerts_unreal_demo

**Comment by chexiongsheng** [comment]
ok

**Comment by chexiongsheng** [comment]
这个PR导致的：https://github.com/Tencent/puerts/issues/1035
