### ISSUE TITLE
[UE] suggestion int32和Uint64类型引发的崩溃请教

### ISSUE THREAD

**Issue by scutDavid** [Tencent/puerts#1165]
## detail | 详细描述
首先 不是puerts设计造成的一个缺陷。
在C++定义一个参数类型为int32的接口，导出给TS使用后，
![image](https://user-images.githubusercontent.com/30872025/212124953-0fd9bd54-7aa0-4262-9b16-8b35adbfadad.png)
再将C++的参数类型设为uint64， 
![image](https://user-images.githubusercontent.com/30872025/212125941-90c4595d-4b28-475d-82fc-b112a8e97bf7.png)
不重新导出生成js(重新导出会编译不过的，参数类型不同)，直接运行上一次的js，就会因为这个断言崩溃。
目前是想在这里加上警告，并且在类型检验不过时默认为0. 想请教下有其他的处理方法么

**Comment by chexiongsheng** [comment]
v8本身的行为，number和bigint是两个东西，传错就assert。

我考虑下是不是加个检查，类型不对返回默认值。这样你收到的会是0。你要传1n才符合预期。

**Comment by chexiongsheng** [comment]
你用的是静态绑定吧？反射应该不会这样。

**Comment by scutDavid** [comment]
> 你用的是静态绑定吧？反射应该不会这样。

我用的是反射，早上在新版的插件上试了，发现不会assert了，返回默认值0. 
麻烦车神顺便看下我另一个关于UE Object 和JS Object有效性的问题，确实不大明白~~

**Comment by chexiongsheng** [comment]
静态绑定我也改下
