### ISSUE TITLE
[UE] discussion

### ISSUE THREAD

**Issue by scutDavid** [Tencent/puerts#1166]
## detail | 详细描述
![image](https://user-images.githubusercontent.com/30872025/212128785-8b45373f-7f84-4b32-9217-3a6a342a576a.png)
创建了Actor后又马上销毁，
这里有两个疑问，一个是自己一开始以为销毁后对应的JS object会被置undefind或者null, 从而导致if分支走不进去。但实际上，此时还没触发Actor的GC 也就不会触发回调UnBind, 所以是不是可以说在destroy到真的被GC这个时间段，JS object实际上是一直有效的？
第二个疑问，自己对V8确实不熟，这里GC回调后的UnBind
![image](https://user-images.githubusercontent.com/30872025/212129846-6c526eac-fa14-4940-93bb-5d41e60bcead.png)
以及下一层的SetPointer，
![image](https://user-images.githubusercontent.com/30872025/212130454-0488240d-5c77-4d89-a0e6-5efa6a6a2b85.png)
是有对Js object做操作，是置null吗？ 目前是GC后回调调用UnBind后， TS侧if分支还是走的进去的。这样判空是没用的。
那TS侧得怎样保证对应的UE Object是有效的呢。

**Comment by chexiongsheng** [comment]
不是设置空，是设置个puerts能识别的标记。
判空没用，直接用就可以了。使用无效对象会抛js异常中断流程

**Comment by scutDavid** [comment]
> 不是设置空，是设置个puerts能识别的标记。 判空没用，直接用就可以了。使用无效对象会抛js异常中断流程

中断流程，是指if 块 后面的代码还是可以继续跑吗。 如果判空没用，那对于TS这边，代码写着就很奇怪，比如我想在对象无效是做其他的处理，但这个无效的分支就一直走不进来了。

**Comment by chexiongsheng** [comment]
就是js异常啊，会有日志打印
碰到这种情况（日志），你应该解决释放后仍然被使用的逻辑问题。
如果你确认想忽略这种情况，就try catch。。这就普通的js异常。
