### ISSUE TITLE
[UE] question 打包后蓝图的mixin TS类失效了

### ISSUE THREAD

**Issue by Xian-Yun-Jun** [Tencent/puerts#1178]
## detail | 详细描述
我有一堆的蓝图UMG，在编辑器下拼好界面之后，然后有对应的TS类，通过mixin的方式和蓝图建立联系，在TS里面绑定事件和编写逻辑
在虚幻编辑器下Play运行是OK的，但是打包和-game运行时，运行一段时间之后，有部分mixin的类就失效了，无效的表现就像没有给该蓝图mixin一个TS类一样，没有任何报错和错误日志。请问我该从哪些方面去排查问题？
我创建了一个简单的示例项目，但是又没有出现上面的情况，我现在开发的项目已经很庞大了，不知道是哪一步出问题了，没办法弄一个示例项目复现这个问题。

**Comment by chexiongsheng** [comment]
感觉像是蓝图类被gc清理了，然后需要用到的时候重新加载，新加载的时候你们没执行mixin。

**Comment by ljporljp** [comment]
请问执行mixin的时机有什么要求呢?有什么建议么？

**Comment by chexiongsheng** [comment]
> 请问执行mixin的时机有什么要求呢?有什么建议么？

没啥要求。只有限制：执行了mixin才有效果。

不过考虑到gc后重新加载的情况，要程序员自己处理确实不太友好，我看看能不能自动处理这种情况。

**Comment by chexiongsheng** [comment]
你们有没在mixin后，持续持有uclass以及mixin后的js类呢？

**Comment by Xian-Yun-Jun** [comment]
> 感觉像是蓝图类被gc清理了，然后需要用到的时候重新加载，新加载的时候你们没执行mixin。

不知道你说的是不是这个意思，我现在把UClass给存下来了，跑了一晚上是OK的
![image](https://user-images.githubusercontent.com/37586630/215641447-e9972821-82dc-40d5-86e8-35e2268b9ec6.png)

**Comment by chexiongsheng** [comment]
mixin的例子那有标注的，可能你没注意到：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TsProj/UsingMixin.ts#L10

**Comment by Xian-Yun-Jun** [comment]
> mixin的例子那有标注的，可能你没注意到：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TsProj/UsingMixin.ts#L10

谢谢，看到了

**Comment by Xian-Yun-Jun** [comment]
> 请问执行mixin的时机有什么要求呢?有什么建议么？

我们是在WorldBeginPlay阶段去把所有需要mixin的类都执行一次，只要保证在创建蓝图实例之前mixin过就没问题，不能mixin 2次否则会报错

**Comment by chexiongsheng** [comment]
分享一个内部项目的做法
他们自己改造puerts，提供c++的mixin接口，然后写些子类覆盖AActor::PostActorCreated，Component的OnCreated这些回调中保证mixin了。
蓝图继承这些子类。这样就完全不用在js那执行mixin了，也不用担心gc的问题。

**Comment by ljporljp** [comment]
> > 请问执行mixin的时机有什么要求呢?有什么建议么？
> 
> 我们是在WorldBeginPlay阶段去把所有需要mixin的类都执行一次，只要保证在创建蓝图实例之前mixin过就没问题，不能mixin 2次否则会报错；在StartGameInstance()阶段执行的mixin打包之后会无效，可能是太早了

你们加载蓝图是直接路径加载么

**Comment by ljporljp** [comment]
> Component

我们最近在想怎么设计基于mixin的gameplay框架。看您给的例子，spawnactor传递的是mixin之后的uclass类型，所以在postactorcreated回调里面去做mixin是不是会有问题？

**Comment by SiCoYu** [comment]
您好，最近仿照Unlua做了个插件监听NotifyUObjectCreated通过事件将Class广播到TS侧调用mixin。有4个问题麻烦您有空帮忙看一下，谢谢！①插件在C++侧持有UClass，ts侧实例化。C++侧持有的UClass，通过测试发现，如果将UClass传给蓝图侧并保存成变量，会Load UObject实例化需要的资源（蒙皮，贴图，材质等）；如果仅仅在C++侧持有，就不会Load资源，如果是这样，是不是可以放心大胆的在C++侧持有UClass，等到切换场景再清理UClass？②清理UClass前需不需要主动UnMixin，目前C++侧不改源码的话暂时不能直接UnMixin，而TS侧unmixin时需要的参数又是一个在C++New出来的UObject，在我们插件中也拿到，导致无法unmixin。暂时想了个折中的方法，是在ts侧也持有mixin的Object，C++侧通过TS类名调用TS侧去unmixin，这样的话TS侧持有minin的Object，C++侧持有Object的GetClass，感觉不是很好，在C++侧何时Unmixin？如何Unmixin？③看到最近解决的#1415是切换场景导致的崩溃，建议是不过早mixin，如果使用NotifyUObjectCreated监听然后C++侧发起mixin会有这个问题么？④我们目前ts版本还不是最新，而且有一些改动，不确定新版本中有没有更直接的方法，不去ts侧绕一圈，而是直接C++->C++实现mixin？

**Comment by SiCoYu** [comment]
您好，最近仿照Unlua做了个插件监听NotifyUObjectCreated通过事件将Class广播到TS侧调用mixin。有4个问题麻烦您有空帮忙看一下，谢谢！

①插件在C++侧持有UClass，ts侧实例化。C++侧持有的UClass，通过测试发现，如果将UClass传给蓝图侧并保存成变量，会Load UObject实例化需要的资源（蒙皮，贴图，材质等）；如果仅仅在C++侧持有，就不会Load资源，如果是这样，是不是可以放心大胆的在C++侧持有UClass，等到切换场景再清理UClass？

②清理UClass前需不需要主动UnMixin，目前C++侧不改源码的话暂时不能直接UnMixin，而TS侧unmixin时需要的参数又是一个在C++New出来的UObject，在我们插件中也拿到，导致无法unmixin。暂时想了个折中的方法，是在ts侧也持有mixin的Object，C++侧通过TS类名调用TS侧去unmixin，这样的话TS侧持有minin的Object，C++侧持有Object的GetClass，感觉不是很好，在C++侧何时Unmixin？如何Unmixin？

③看到最近解决的#1415是切换场景导致的崩溃，建议是不过早mixin，如果使用NotifyUObjectCreated监听然后C++侧发起mixin会有这个问题么？

④我们目前ts版本还不是最新，而且有一些改动，不确定新版本中有没有更直接的方法，不去ts侧绕一圈，而是直接C++->C++实现mixin？

![TS问题1](https://github.com/Tencent/puerts/assets/20559909/ccaf2231-705b-44e4-b20b-ebcc02c55c0e)
![TS问题2](https://github.com/Tencent/puerts/assets/20559909/a9662077-cc0b-441e-9b86-c168f4a91ca0)
