### ISSUE TITLE
[unity] quickjs库调用System.Text.Encoding.UTF8.GetString异常(对照v8库)

### ISSUE THREAD

**Issue by layerpsr** [Tencent/puerts#118]
v8库和quickjs库版本号: v8

![image](https://user-images.githubusercontent.com/45587825/102427592-9c5d8980-404c-11eb-99c3-5e5b7e0d72bd.png)
![image](https://user-images.githubusercontent.com/45587825/102427514-7a640700-404c-11eb-8e5a-b2f9261b7075.png)

**Comment by chexiongsheng** [comment]
你的意思是v8没报错，quickjs报错？
还是quickjs报错的文件行号信息问题？

**Comment by layerpsr** [comment]
v8是正常的, quickjs库报错(仅仅替换了库文件)

**Comment by chexiongsheng** [comment]
这是因为quickjs采用引用计数做gc，变量回收比较实时导致的。
Object.setPrototypeOf(System.Text.Encoding.UTF8, System.Text.Encoding.prototype);
这里头的System.Text.Encoding.UTF8只是临时变量，设置后回收了。从新访问System.Text.Encoding.UTF8是个新变量。
这么改下就可以了：
~~~typescript
let utf8 = System.Text.Encoding.UTF8;
Object.setPrototypeOf(utf8, System.Text.Encoding.prototype);
utf8.GetString(buff);
~~~
理论上之前的写法在v8也是有风险，我们不能假定变量啥时候被gc

**Comment by layerpsr** [comment]
了解, 谢谢解答!
所以, 之前v8时用UTF8也偶发异常就是这个原因吗...

**Comment by Geequlim** [comment]
> 这里头的System.Text.Encoding.UTF8只是临时变量，设置后回收了。从新访问System.Text.Encoding.UTF8是个新变量。

这个机制从JS这一侧很难 get 得到，对脚本开发者来说也不容易理解，能否访问一次之后这个变量被缓存下来？
