### ISSUE TITLE
[UE] Bug: DeclarationGenerator 生成ue_bp.d.ts 错误

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1184]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master  5a3fec7c

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

- **生成ue_bp.d.ts时，如果目标蓝图类没有变动，则引用的UE内部蓝图描述丢失，原因是__TYPE_DECL_START没有变化，蓝图类生成被跳过，所以没有生成内部依赖的UE原生蓝图。**
- 可以通过FullGen解决问题，但是这代表着每次重新启动Editor第一次都需要进行FullGen，失去了增量编译头文件的意义

![image](https://user-images.githubusercontent.com/5946974/215720464-1767f156-35e0-4e03-a392-f871e97900df.png)

![image](https://user-images.githubusercontent.com/5946974/215720624-ccc18320-dc50-4085-8073-3547cc3cf0e0.png)

- BP Paint Clouds，在Engine路径下

![image](https://user-images.githubusercontent.com/5946974/215721296-69471bd7-8481-4f38-b417-d3dad4b2a2f8.png)

### 问题重现 | Bug reproduce

1. 创建一个蓝图DG_Test继承自Object，增加一个变量TestParam 类型是BP Paint Clouds

![image](https://user-images.githubusercontent.com/5946974/215718903-f1ad5eae-4744-4c56-8eaa-25022d273516.png)

![image](https://user-images.githubusercontent.com/5946974/215718712-8c784900-9843-435b-b443-2f558c3b4cc0.png)

2.GenDTS,生成头文件，生成成功，因为ue_bp.d.ts中没有DG_Test，所以依赖的类型BP_PaintClouds可以正常生成

**3.重新启动Editor(关键)**，原因是首次生成DG_Test时，BP_PaintClouds已经被加载进内存，所以再次生成也可以正常生成

4.再次GenDTS，由于DG_Test没有发生变化，生成跳过，依赖的BP_PaintClouds也没有被生成，触发编译错误
![image](https://user-images.githubusercontent.com/5946974/215720340-0bf6aba7-bfab-4d81-9e7e-b262dd5b32fd.png)

**Comment by chexiongsheng** [comment]
原因是依赖了蓝图，但被依赖的蓝图不在Content下吧？目前只扫描Content，不存在就认为被删了，第二次生成就删了。

**Comment by lzj10** [comment]
是的没错

**Comment by chexiongsheng** [comment]
有个比较简单的方式
就是增量生成只加、修改类。不删类。
缺点是会累积，但可以通过全量生成来清理。

**Comment by lzj10** [comment]
感觉可能不行，因为引用的蓝图是生成到ue.d.ts里面的不是ue_bp.d.ts,而ue.d.ts好像每次都会重新生成。可以把这种特殊的没有生成的被的依赖蓝图放在一个新的文件里，然后只加，不删，不改。如果有修改就全量生成，感觉这种蓝图一般都是在引擎目录下，改动不会很频繁。
![image](https://user-images.githubusercontent.com/5946974/216035079-7d58b088-022d-4818-a819-5aff27d85b4b.png)

**Comment by lzj10** [comment]
也可以给把这种依赖的类给一个特殊标记，放在ue_bp.d.ts里 ，只针对这种类型增量生成只加 ，不删改。我试试能不能弄
