### ISSUE TITLE
[UE] Bug:Xcode 编译UE报错

### ISSUE THREAD

**Issue by zhulove86** [Tencent/puerts#1189]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.2

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

mac

### 错误信息 | Error Message

**编译错误：**
![BuildError](https://user-images.githubusercontent.com/5286374/216284700-8a5df193-b2b6-4540-a974-277f439cd85b.jpeg)
这个是由于resolver_base.hpp中的局部变量v4_mapped屏蔽address_v6.hpp中已有v4_mapped变量产生的编译错误。

临时通过在resolver_base.hpp中增加如下的方式消除编译错误：
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"
#endif
.......
#ifdef __clang__
#pragma clang diagnostic pop
#endif

### 问题重现 | Bug reproduce

step 1：UE工程中导入puerts插件；
setp 2:   在mac上生成工程并进行工程编译；

**Comment by ljporljp** [comment]
v1.0.3也同样报错，UE5.1.0

**Comment by chexiongsheng** [comment]
xcode版本？
我的一直都没报错

**Comment by ljporljp** [comment]
> xcode版本？ 我的一直都没报错

13.4.1

**Comment by chexiongsheng** [comment]
> > xcode版本？ 我的一直都没报错
> 
> 13.4.1

我刚刚确认了下，xcode 13.4.1 + ue5.1 + puerts_unreal_demo没问题。
感觉是你们项目的特殊设置吧？

**Comment by chexiongsheng** [comment]
本来是warning，可能你们设置了warning as error之类吧。
按@zhulove86 的处理是ok的，asio库是官方的，挺多人用的，直接忽略问题不大，可以提交个PR给我。

**Comment by chexiongsheng** [comment]
或者不改resolver_base.hpp，在JsEnv.Build.cs那加个忽略选项也行。

**Comment by ljporljp** [comment]
不太熟悉xcode是不是有这块的设置，不过我这边按照 @zhulove86 的处理不行。我这边的解决方案是 改了 adress_v6.hpp 中 enum v4_mapped_t { v4_mapped } 的定义， 改为enum class 了，因为改resolver_base.hpp 那的定义，有不少地方直接是按照全局空间的方式来使用enum，要改的地方比较多。。。我这种改完是可以编译通过了。

**Comment by chexiongsheng** [comment]
你在JsEnv.Build.cs的构造函数里头
加如下代码试试：
ShadowVariableWarningLevel = WarningLevel.Warning;

**Comment by ljporljp** [comment]
> > 不太熟悉xcode，不过我这边按照 @zhulove86 的处理不行。我这边的解决方案是 改了 adress_v6.hpp 中 enum v4_mapped_t { v4_mapped } 的定义， 改为enum class 了，因为改resolver_base.hpp 那的定义，有不少地方直接是按照全局空间的方式来使用enum，要改的地方比较多。。。我这种改完是可以编译通过了。
> 
> 你在JsEnv.Build.cs的构造函数里头 加如下代码试试： ShadowVariableWarningLevel = WarningLevel.Warning;
> 
> 如果不行就 ShadowVariableWarningLevel = WarningLevel.Off;

可以的。

**Comment by chexiongsheng** [comment]
> > > 不太熟悉xcode，不过我这边按照 @zhulove86 的处理不行。我这边的解决方案是 改了 adress_v6.hpp 中 enum v4_mapped_t { v4_mapped } 的定义， 改为enum class 了，因为改resolver_base.hpp 那的定义，有不少地方直接是按照全局空间的方式来使用enum，要改的地方比较多。。。我这种改完是可以编译通过了。
> > 
> > 
> > 你在JsEnv.Build.cs的构造函数里头 加如下代码试试： ShadowVariableWarningLevel = WarningLevel.Warning;
> > 如果不行就 ShadowVariableWarningLevel = WarningLevel.Off;
> 
> 可以的。

是ShadowVariableWarningLevel = WarningLevel.Warning就可以了吧？

**Comment by ljporljp** [comment]
是的。
