### ISSUE TITLE
[UE] Bug: Unreal_v1.0.3 TypeError: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by Xian-Yun-Jun** [Tencent/puerts#1191]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.3

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

更新到最新发布版Unreal_v1.0.3，之后使用node_modules/typescript/lib/lib.es2022.object.d.ts这个库里面的Object.hasOwn这个函数报如下错误：TypeError: Object.hasOwn is not a function

之前的版本没出现过

### 问题重现 | Bug reproduce

        let a = {tt: 234}
        let b = Object.hasOwn(a, "tt")
        console.log(b)

**Comment by chexiongsheng** [comment]
试试回退这个：https://github.com/Tencent/puerts/commit/25ba7e29f24a26f5be2675e26fdab49d29297383

**Comment by chexiongsheng** [comment]
之前哪个版本有呢？

**Comment by Xian-Yun-Jun** [comment]
> 之前哪个版本有呢？

之前这个Unreal_v1.0.2版本没问题，这个Unreal_v1.0.3版本有问题

**Comment by chexiongsheng** [comment]
刚我换Unreal_v1.0.2也是没有这函数

**Comment by Xian-Yun-Jun** [comment]
> 刚我换Unreal_v1.0.2也是没有这函数

不好意思Unreal_v1.0.2这个确实也不对
我刚刚重新拉了你这个项目，https://github.com/chexiongsheng/puerts_unreal_demo，这个是对的

**Comment by chexiongsheng** [comment]
[puerts_unreal_demo](https://github.com/chexiongsheng/puerts_unreal_demo)是master版本么？好像我用master也不行

**Comment by chexiongsheng** [comment]
这个要高版本v8才支持，下载这个：https://github.com/puerts/backend-v8/releases/tag/V8_9.4.146.24_1115

默认用的是8.4

**Comment by Xian-Yun-Jun** [comment]
> 这个要高版本v8才支持，下载这个：https://github.com/puerts/backend-v8/releases/tag/V8_9.4.146.24_1115
> 
> 默认用的是8.4

谢谢，替换V8之后确实可以了
