### ISSUE TITLE
[UE] Bug: 升级ts插件，打包报错 Error: can not find lib/typescript.js

### ISSUE THREAD

**Issue by nathonNot** [Tencent/puerts#1197]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.3

### UE的版本 | UE Version

0

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

16:22:41   LogInit: Display: Puerts: Error: (0x0000022101FBAE50) C:\jenkins-work\workspace\ts-windwos-client\Content\JavaScript\puerts\modular.js:105: Error: can not find lib/typescript.js in ../../../../jenkins-work/workspace/ts-windwos-client/Content/JavaScript/PuertsEditor/node_modules/typescript
16:22:41   
16:22:41   Error: can not find lib/typescript.js in ../../../../jenkins-work/workspace/ts-windwos-client/Content/JavaScript/PuertsEditor/node_modules/typescript
16:22:41       at require (C:\jenkins-work\workspace\ts-windwos-client\Content\JavaScript\puerts\modular.js:105:23)
16:22:41       at require (C:\jenkins-work\workspace\ts-windwos-client\Content\JavaScript\puerts\modular.js:129:29)
16:22:41       at C:\jenkins-work\workspace\ts-windwos-client\Content\JavaScript\PuertsEditor\CodeAnalyze.js:5:12
16:22:41       at executeModule (C:\jenkins-work\workspace\ts-windwos-client\Content\JavaScript\puerts\modular.js:70:9)
16:22:41       at require (C:\jenkins-work\workspace\ts-windwos-client\Content\JavaScript\puerts\modular.js:137:17)

### 问题重现 | Bug reproduce

删除原来的Content/JavaScript 目录和 Plugins\Puerts目录。
删除项目下Saved目录和Binaries目录。
删除ts_file_versions_info.json 文件
清理jenkins工作空间。
重新编译c++，打开工程后重新生成d.ts。
运行项目js代码是挂载上并运行成功的。
打包机的自动化会报错

**Comment by chexiongsheng** [comment]
Content/JavaScript都删除了肯定跑不了

**Comment by nathonNot** [comment]
重新编译和生成了Content/JavaScript。
![`$G1DE_~AN73H3~SHWKSW1D](https://user-images.githubusercontent.com/31683427/216936281-3888d222-afef-477a-bb69-1a3f8764d5e7.png)
而且也有 Content/JavaScript/PuertsEditor/node_modules/typescript 目录

**Comment by nathonNot** [comment]
.js文件被忽略了，导致Content/JavaScript下的文件没有被git 提交上去
