### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by AlanWalk** [Tencent/puerts#1199]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

V1.0.3

### UE的版本 | UE Version

5.1.0

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

目前对一个js module的加载顺序是先读取package.json，再读index.js，会导致如果在package.json中没有声明main字段的模块加载出错，比如 https://www.npmjs.com/package/js-yaml 这个库，现在通过 `import * as yaml from "js-yaml"`导入进来是package.json的object。

想了解下这么改动的原因
![image](https://user-images.githubusercontent.com/4654826/217201999-0ebcfb44-26bd-496f-b4c5-adeb3bd630a5.png)

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/commit/a6853226fb763afc07b258da5e72d5b94f7da901#diff-7aafe8cf149a2491194d6b9b5b78db821832d1e36303d765109d506134cd023a

package.json里可能会指明这个module是cjs还是esm，这影响了*.js文件的加载方式。

**Comment by chexiongsheng** [comment]
要根治这问题，估计调整c++和js间的配合。c++只负责最基本的文件是否存在，读文件内容。然后所有逻辑都交给js，和nodejs类似。

**Comment by chexiongsheng** [comment]
放到这个issue跟进把，https://github.com/Tencent/puerts/issues/1248
