### ISSUE TITLE
puerts生成的index.d.ts里面的interface，其function前面有public，应该不能有public

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#12]
我在Unity C#的环境下，在[Binding]的类列表内加入一个自定义的interface，按了Generate Code之后，产生的index.d.ts里面的interface，其function前面有public，但这是语法错误，interface的function的前面应该不能有public。

**Comment by chexiongsheng** [comment]
更新到这个commit：https://github.com/Tencent/puerts/commit/2fb40c388573a1e395ebc33b086f9e16ceffa579

**Comment by h3902340** [comment]
謝謝。更新後，問題已解決。
