### ISSUE TITLE
[UE] Bug: Mixin相关，ue对象持有stub对象的时机问题

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1205]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master  5a3fec7c

### UE的版本 | UE Version

5.0

### 发生在哪个平台 | Platform

Editor(win)

## detail | 详细描述
- Mixin 的 UObject 持有stub对象（objectTakeByNative: true）的时机是在首次调用mixin的函数的时候
(在FJsEnvImpl::InvokeMixinMethod中)，而不是在UObject 创建的时候。所以Mixin没有函数的类，（比如ListView使用的数据类），或者创建后只调用了扩展函数和只访问了新增字段，没有调用到FJsEnvImpl::InvokeMixinMethod的话，js侧的stub对象生命周期依然不受UObject引用，可能会被v8 gc回收掉
- 目前的解决方法，实现一个mixin方法，创建对象后调用一下。虽然能解决 但是感觉有点奇怪

### 问题重现 | Bug reproduce

- 一个 c++类型，用来mixin后给ListView传递数据

```
UCLASS()
class UNListItemObject : public UObject
{
	GENERATED_BODY()
};

```
- 一个数据类，mixin到c++类型，用于存储ListView使用的数据　objectTakeByNative: true

```
import { blueprint } from "puerts";
import { NListItemObject } from "ue";
import { UE } from "../../../../Global/Common";

export interface TS_ListViewItem extends NListItemObject {}
export class TS_ListViewItem {
    data: any;
}

export const TS_ListViewItemMixinClass = blueprint.mixin(NListItemObject, TS_ListViewItem, { objectTakeByNative: true });

/**
 * 创建ItemObject
 * @param data
 * @returns
 */
export function CreateListViewItemObj(data: any, outer?: UE.Object): TS_ListViewItem {
    const listViewItem = new TS_ListViewItemMixinClass();
    listViewItem.data = data;
    return listViewItem;
}

```
- 一个mixin的UMG，用来放ListView，NListView_15是ListView,EntryWidgetClass是  TestEntry
![image](https://user-images.githubusercontent.com/5946974/218415637-95b363b3-3914-4afc-841e-faa7c1e39574.png)
```

import { blueprint } from "puerts";
import { UE } from "../../../../Global/Common";
import { LogInfo } from "../../../../Global/GlobalFunction";
import { CreateListViewItemObj } from "../Common/TS_ListViewItem";

export interface TestView extends UE.Game.UI.UMG.General.Test.TestView.TestView_C {}
export class TestView {
    Construct(): void {
        for (let i = 0; i < 50; i++) {
            this.NListView_15.AddItem(CreateListViewItemObj({ index: i }, this));
        }
    }
}

```
- 一个mixin的UMG Entry，用于显示存储的数据,实现UserObjectListEntry接口
![image](https://user-images.githubusercontent.com/5946974/218415971-44d2d046-c4b8-45ba-b13f-a034f1aa9398.png)
![image](https://user-images.githubusercontent.com/5946974/218416092-e8d3aff4-fdbd-4949-a9ae-58b0c56059e7.png)

```
import { $Nullable } from "puerts";
import { UE } from "../../../../Global/Common";
import { LogInfo } from "../../../../Global/GlobalFunction";
import { TS_ListViewItem } from "../Common/TS_ListViewItem";

/**
 *
 */
export interface TestEntry extends UE.Game.UI.UMG.General.Test.TestEntry.TestEntry_C {}
export class TestEntry {
    Construct(): void {
        LogInfo(`TestEntry.Construct`);
    }

    Destruct(): void {
        LogInfo(`TestEntry.Destruct`);
    }

    OnListItemObjectSet(ListItemObject: $Nullable<UE.Object>): void {
        if (!ListItemObject) return;
        LogInfo(`WBP_Example_ListEntry.OnListItemObjectSet`);

        const itemObject = ListItemObject as TS_ListViewItem;
        this.Text.SetText(`${itemObject.data.index}`);
    }
}
```

- 创建TestView界面后界面正常，调用v8 的 gc后连续滑动，TS_ListViewItem 的stub对象被回收报错
![image](https://user-images.githubusercontent.com/5946974/218417349-1e9c1693-9941-46db-9d5f-d799456eb667.png)
![image](https://user-images.githubusercontent.com/5946974/218417143-cdf94534-b1bc-4ef5-aed8-0377507656bd.png)

**Comment by chexiongsheng** [comment]
是有点不合理。
