### ISSUE TITLE
[UE] puerts 怎样配合 GameFeature 使用？

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1206]
## detail | 详细描述
GameFeature 和 ModularGameplay 允许把资源玩法放在插件里面，如果想结合 Puerts 使用，想请教下使用姿势？

**Comment by chexiongsheng** [comment]
之前有个项目，他们的情况是一个GameFeature就是一个游戏，项目本身是个游戏平台，我当时建议他们一个GameFeature一个虚拟机。

**Comment by ljporljp** [comment]
如果GameFeature本身只是一些dlc的东西，是不是可以共享一个虚拟机

**Comment by wangray86** [comment]
这个问题现在有没有进展呀？我们的项目也是想用gamefeature做一些dlc的东西，没办法用额外的虚拟机来做。

**Comment by chexiongsheng** [comment]
> 这个问题现在有没有进展呀？我们的项目也是想用gamefeature做一些dlc的东西，没办法用额外的虚拟机来做。

这不是问题啊，没什么进展可言。
这是个咨询。我只是给了个我知道的案例，这并不是puerts对这个场景的功能性支持，而是使用姿势。
这好比有人问怎么用c++网络程序，有人回答说调用系统的epoll，但不代表这是c++程序只能这么干，这也不是c++的职责。c++真正负责的是你按c++语法写代码，按照预期来工作。
放到puerts，puerts负责的是启动虚拟机，并实现c++/蓝图和js的交互。怎么编程，怎么设计，是具体项目的事情。
