### ISSUE TITLE
<UE4 bug>无法重载蓝图已经实现的Tick实现,结束游戏时崩溃

### ISSUE THREAD

**Issue by FishOrBear** [Tencent/puerts#121]
崩溃是概率性的,不会百分百

**Comment by eefan000** [comment]
重写蓝图实现得事件会导致运行时卡住，从日志看事件已经执行了，但是执行后就一直未响应了
![U`U%CU{Q3}VCRN 79%6J8N](https://user-images.githubusercontent.com/19683667/102704903-54dd3480-42bc-11eb-9bef-54931e90f0b2.png)
![R}LGVXR4 6DUUFE8OBL3}UH](https://user-images.githubusercontent.com/19683667/102704906-573f8e80-42bc-11eb-979c-66027501904e.png)

**Comment by chexiongsheng** [comment]
> 重写蓝图实现得事件会导致运行时卡住，从日志看事件已经执行了，但是执行后就一直未响应了
> ![U`U%CU{Q3}VCRN 79%6J8N](https://user-images.githubusercontent.com/19683667/102704903-54dd3480-42bc-11eb-9bef-54931e90f0b2.png)
> ![R}LGVXR4 6DUUFE8OBL3}UH](https://user-images.githubusercontent.com/19683667/102704906-573f8e80-42bc-11eb-979c-66027501904e.png)

你这个是Ttt调用了Ttt？这不是死循环么？

**Comment by chexiongsheng** [comment]
如果蓝图没有实现Tick，直接在Ts那实现的话，会有问题么？

**Comment by eefan000** [comment]
> > 重写蓝图实现得事件会导致运行时卡住，从日志看事件已经执行了，但是执行后就一直未响应了
> > ![U`U%CU{Q3}VCRN 79%6J8N](https://user-images.githubusercontent.com/19683667/102704903-54dd3480-42bc-11eb-9bef-54931e90f0b2.png)
> > ![R}LGVXR4 6DUUFE8OBL3}UH](https://user-images.githubusercontent.com/19683667/102704906-573f8e80-42bc-11eb-979c-66027501904e.png)
> 
> 你这个是Ttt调用了Ttt？这不是死循环么？

不是  我是在开始运行调用得Ttt

**Comment by eefan000** [comment]
> 如果蓝图没有实现Tick，直接在Ts那实现的话，会有问题么？

如果蓝图没实现Tick，只在Ts实现的话就没问题

**Comment by chexiongsheng** [comment]
我这里测试不会crash了
