### ISSUE TITLE
[UE] Bug: win下交叉编译linux报错

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1212]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

Compile PesapiFrameworkLoader.mm
error: Objective-C was disabled in PCH file but is currently enabled

### 问题重现 | Bug reproduce

demo项目在windows下利用交叉编译打linux包

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/pull/1154
按这个改个后缀名就行

**Comment by ljporljp** [comment]
ok了，确实可以。感谢。
