### ISSUE TITLE
[UE] Nodejs环境下遇到的一个小问题

### ISSUE THREAD

**Issue by stdnxd** [Tencent/puerts#1213]
Nodejs环境下 当js对象的被垃圾回收触发FClassWrapper::OnGarbageCollected函数
继而调用FJsEnvImpl::UnBind的时候 如果把UnBind的第三个参数ResetPointer改为true(puerts原来的代码这个参数是false)
然后在调用
DataTransfer::SetPointer(MainIsolate, PersistentValuePtr->Get(Isolate).As<v8::Object>(), RELEASED_UOBJECT, 0);
这一行代码的时候会崩溃
经过调试发现这个时候 通过PersistentValuePtr->Get(Isolate).As<v8::Object>()拿到的js对象已经在v8底层释放 在C++层对这个js对象进行任何操作都会导致程序崩溃

而在NewV8环境不会出现这个问题

**Comment by chexiongsheng** [comment]
本来就不应该改，这时候对象是是释放了。

NewV8不（立刻）崩的原因我猜是NewV8是静态链接，此时new和delete实际上是被ue拦截转到内存分配器了，一个对象被释放了只是放回内存池，对其修改没除非asset（ue内存池不做检查）。

nodejs是dll，可能用的还是c++默认的内存分配器。
