### ISSUE TITLE
[UE] Bug:  Unable to create new object: Object /Engine/Transient.None. Creating an instance of an abstract class is not allowed!

### ISSUE THREAD

**Issue by lightflow** [Tencent/puerts#1218]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.75

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

![20230224-124352](https://user-images.githubusercontent.com/14144022/221093752-0ba0f9f1-27cf-4fcb-a839-5421121f2599.jpg)

### 问题重现 | Bug reproduce

安卓包就会崩溃，直接报这个错误

**Comment by chexiongsheng** [comment]
你要描述清楚你干了啥。
或者更直接的提供个重现小demo
