### ISSUE TITLE
[Unity] ts中无法创建cs数组

### ISSUE THREAD

**Issue by wuchuanjue** [Tencent/puerts#1221]
## detail | 详细描述

cs中的数组导出后的类型是 System.Array$1。 只有一个ts的interface，没有继承的类。 请问下如何在ts端构建一个此类型？

类似cs中的List<T>，有一个ts的类 CS.System.Collections.Generic.List$1 可以通过$generic方法生成对应的泛型list，但是Array无法这么做。

**Comment by zombieyang** [comment]
`System.Array.CreateInstance`可以用
