### ISSUE TITLE
Implementation of coroutine of Unity Style in Typescript

### ISSUE THREAD

**Issue by KimChily1117** [Tencent/puerts#1222]
Is it possible to invoke c# style coroutine using StartCoroutine ({Method()}) within the type script?

Can you transfer the Generator function of TypeScript to c# Ienumerator to act as StartCoroutine?

please! help!

====================================================================
It doesn't work, but Google found an example code.

Is this code valid?

If it is valid, how should I call it?

**In TS_Source**

![image](https://user-images.githubusercontent.com/57296811/221873880-9878592f-53a5-4919-999c-b50cd41ac74c.png)

**In C#_Source**

![image](https://user-images.githubusercontent.com/57296811/221873948-2ba59feb-7594-422b-a598-739e8bc3d1f0.png)

**Comment by zombieyang** [comment]
There is an example that can start a coroutine: 
https://github.com/chexiongsheng/puerts_unity_demo/blob/master/projects/0_Basic_Demo/Assets/Examples/04_JsBehaviour/Resources/rotate.mjs#L8
https://github.com/chexiongsheng/puerts_unity_demo/blob/master/projects/0_Basic_Demo/Assets/Examples/04_JsBehaviour/JsBehaviour.cs#L56

---------

If you want to listen to the finish of coroutine, we recommend you to use `async/await` in C# and `puer.$promise` in JS:
https://github.com/chexiongsheng/puerts_unity_demo/blob/master/projects/0_Basic_Demo/Assets/Examples/05_Typescript/Resources/QuickStart.mjs#L77

you can wrap the coroutine as a async function for JS to call

---------
I can't understand the usage of the code you posted either...
