### ISSUE TITLE
[UE] Bug: Potentially invalid Assumptions in Javascript module search logic - bn.js module not found error

### ISSUE THREAD

**Issue by mangoplane** [Tencent/puerts#1223]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

```
Puerts: Error: (0x0x97422319538) /home/whale/UnrealEngine/Oasis/Content/JavaScript/puerts/modular.js:105: Error: can not find bn.js in ../../../Oasis/Content/JavaScript/node_modules/@walletconnect/utils/dist/cjs
```

### 问题重现 | Bug reproduce

Hey there!

I think there might be some invalid assumptions made about modules, folders, and JavaScript files in the implementation for searching for a JavaScript module. Specifically, it seems like the implementation assumes that folders, built-in modules, or modules installed in the node_modules directory don't end with a .js extension.

However, this isn't always the case for certain npm packages, like bn.js (https://www.npmjs.com/package/bn.js/v/4.5.2), which has a directory name 'bn.js' in node_modules that could be misclassified as a local JavaScript file instead of a node module in the node_modules directory.

The relevant C++ signature is below:
```C++
bool DefaultJSModuleLoader::Search(const FString& RequiredDir, const FString& RequiredModule, FString& Path, FString& AbsolutePath)
```
I could be mistaken, but it seems like this might be the reason for the error message above. Could you please take a look at the relevant code?

I'm currently working on a fix and would be happy to make a pull request if you don't mind.

Thanks!

**Comment by chexiongsheng** [comment]
how to reproduce?
