### ISSUE TITLE
[Unity] js普通log无法看到js堆栈

### ISSUE THREAD

**Issue by wuchuanjue** [Tencent/puerts#1227]
## detail | 详细描述

js文件内log看不到js端的堆栈，点击后只能跳转到 UnityEngine_Debug_Wrap 内方法。
js文件内的error输出可以看到js文件的堆栈。

官方demo “Start_Template” 里有一个例子是 “03_ConsoleRedirect”。 测试后发现无任何变化。log依然看不到堆栈，console edit 内点击后也跳转不到js/ts文件。
Unity版本:2021.3.15f
编辑器:VsCode。  已添加 ts;js后缀

**Comment by zombieyang** [comment]
或是使用[puerts-ts-loader](https://github.com/zombieyang/puerts-tsloader)，集成了@throw-out 写的ConsoleRedirect
