### ISSUE TITLE
[UE] Delegate

### ISSUE THREAD

**Issue by faseceroo** [Tencent/puerts#1233]
Hi, the **QuickStart.ts** file contains examples about delegates but still I can't solve this problem.

![timer](https://user-images.githubusercontent.com/93630866/222884959-c4405721-4776-4d37-9fd0-ab3dee6a0eb8.png)

The **K2_SetTimerDelegate**(...) function requires a delegate like this: **UE.$Delegate<() => void>**

I need to pass in there the address of **OnTimer**() function located below. I can't find how to build a delegate around **OnTimer**().

**Comment by faseceroo** [comment]
This compiles fine but OnTimer still not called:

`this.TimerHandle = System.K2_SetTimerDelegate(toManualReleaseDelegate(this.OnTimer), 1, true);`

**Comment by faseceroo** [comment]
I found a working alternative:

`this.TimerHandle = System.K2_SetTimer(this, "OnTimer", 1, true)`

I still wish to know why isn't working with the delegate. Hope someone can catch what's wrong.

**Comment by chexiongsheng** [comment]
call K2_SetTimerDelegate(toManualReleaseDelegate(xxx), 1, true) will print this warning.
~~~
LogScript: Warning: Script Msg: No world was found for object (/Engine/Transient.DynamicDelegateProxy_1) passed in to UEngine::GetWorldFromContextObject().
~~~
toManualReleaseDelegate generate a delegate, but the delegate bond object is not a actor, K2_SetTimerDelegate can not find world from this object.

Why not using setTimeout/setInterval? The setTimeout/setInterval API of Puerts is based on UE's FTicker, so does not conflict with UE's functionality/mechanism, and it easier to use.
