### ISSUE TITLE
[Unity]/[UE] suggestion

### ISSUE THREAD

**Issue by lightflow** [Tencent/puerts#1236]
## detail | 详细描述
Puerts平台是否支持在Linux上运行？因为我们的DS需要使用Puerts，并在Linux上运行。但是看官方文档，支持平台没有写Linux。这个对我们的项目还蛮关键的。

**Comment by chexiongsheng** [comment]
linux很多人在用

**Comment by chexiongsheng** [comment]
刚好最近有个老外问过：https://github.com/Tencent/puerts/issues/1220
