### ISSUE TITLE
[UE] Bug: 不使用 Namespace 时无法调用蓝图枚举

### ISSUE THREAD

**Issue by AlanWalk** [Tencent/puerts#1237]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

All

### 问题重现 | Bug reproduce

在目前的版本里，有 Namespace 的情况下，蓝图枚举可以正常调用，如：
`console.log(UE.Game.StarterContent.TestEnum.TestEnum.Blue);`

但是如果项目使用 WithoutNamespace 的宏关闭 Namespace 导出的话，蓝图枚举就没法正常读取了。
`console.log(UE.TestEnum.Blue)`
![image](https://user-images.githubusercontent.com/4654826/223011030-2dc6e6d7-6b5a-4a57-b0b2-52eace8895cc.png)

加载后调用，报错相同：
```
UE.UserDefinedEnum.Load("/Game/ENUM_Test.ENUM_Test");
console.log(UE.ENUM_Test.Blue);
```

**Comment by chexiongsheng** [comment]
设计如此。
没有名字空间（路径），没法区分重名蓝图。

这个提示不是加载后UE.XX就可用了。加载后还要转成js类才可用。

**Comment by AlanWalk** [comment]
> 

嗯，但是枚举本身是比较特殊的东西，tojs也是不行的，比如这么写：
```
let cls = UE.Class.Load("/Game/StarterContent/TestEnum.TestEnum");
let TestEnum = blueprint.tojs(cls) as unknown as typeof UE.TestEnum;
console.error(UE.TestEnum.Blue);
```

下面的写法是参考蓝图结构体的。
```
UE.UserDefinedEnum.Load("/Game/ENUM_Test.ENUM_Test");
console.log(UE.ENUM_Test.Blue);
```

没有命名空间确实无法区分重名蓝图，但是既然开放了运行去掉Namespace，那肯定还是有项目需求。比如项目内自行约束了不允许存在同名蓝图。
毕竟写代码的时候一长串Namespace在TS里写着太麻烦了。
是不是可以考虑一下加入上面类似于UserDefinedStruct的写法。

**Comment by chexiongsheng** [comment]
去掉Namespace那个宏是让项目过度用的

**Comment by chexiongsheng** [comment]
长串Namespace可以前面加个
const XX = UE.AA.BB.CC.XX

**Comment by AlanWalk** [comment]
`WITHOUT_BP_NAMESPACE` 这个宏在未来的某个版本会移除没，还是会维护？

**Comment by chexiongsheng** [comment]
应该会去除。
