### ISSUE TITLE
[UE] Bug: 5.1.1在Windows下打LinuxServer包时, PesapiFrameworkLoader.mm会导致编译失败

### ISSUE THREAD

**Issue by jasonyuan51** [Tencent/puerts#1239]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

1>Building 4 actions with 4 processes...
1>[1/4] Compile PesapiFrameworkLoader.mm
1>EXEC : error : Objective-C was disabled in PCH file but is currently enabled
1>1 error generated.

### 问题重现 | Bug reproduce

在Windows下, 使用UE5.1.1打LinuxServer包, 编译过程中就会出现

**Comment by chexiongsheng** [comment]
后缀名改为cpp
