### ISSUE TITLE
[UE]  通过Object.values读取不出蓝图结构体属性值

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#1240]
## detail | 详细描述
版本：Unreal_v1.0.3
问题截图：
![微信截图_20230308143117](https://user-images.githubusercontent.com/18215765/223637071-ae8e6b31-e329-424e-9e13-b38d1dee230d.png)

问题描述：
上面示例中，通过Object.values访问蓝图结构体是读取不到值的，实际断点看，testStruct是有属性的，而且通过testStruct.MemberVar_4.MemberVar_0访问数据也是有的

**Comment by chexiongsheng** [comment]
puerts通过getter/setter定义的属性，Object.values获取不了

**Comment by chexiongsheng** [comment]
Object.values访问的是当前对象上自有属性。puerts的对象属性是定义在prototype上的getter/setter，获取不了。
可以通过for来获取
~~~javascript
for (var k in testStruct) {
    console.log(k, c[k]);
}
~~~
