### ISSUE TITLE
[UE] Bug: ArrayBuffer 通过事件派发的时候，ts侧回调取到的数据是空的

### ISSUE THREAD

**Issue by nathonNot** [Tencent/puerts#1249]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.3

### UE的版本 | UE Version

4.27

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

我们项目之前用的json，感觉不安全，现在在做protobuf的改造
项目里使用的是ue4的websocket
我的想法是通过事件来把websocket收到的值派发出来，然后在ts里监听事件
C++里是这样的
`
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FEventOnMessageRaw, FArrayBuffer, bf);
UPROPERTY(BlueprintAssignable, Category = "Event")
		FEventOnMessageRaw onMessageRaw;
UPROPERTY()
		TArray<FArrayBuffer> bfArray;
void UEngineSubsystem_ServerClient::OnRawMessage(const void* data, SIZE_T len, SIZE_T bit)
{
	auto curBf = FArrayBuffer();
	auto p_void = const_cast<void*>(data);
	curBf.Data = p_void;
	curBf.Length = len;
	bfArray.Add(curBf);
	UE_LOG(ServerClient, Display, TEXT("OnRawMessage:len:%d,bit:%d,data:%p"), len, bit, data);
	onMessageRaw.Broadcast(curBf);
}
`
ts里是这样的
`
export function AddPbListen(msgType: number, func: receivePbFunc): number {
  if (ListenPbFuncMap.has(msgType)) {
    ListenPbFuncMap.get(msgType).push(func);
    return ListenPbFuncMap.get(msgType).length - 1;
  }
  ListenPbFuncMap.set(msgType, [func]);
  if (addMsgListen) {
    return;
  }
  client.onMessageRaw.Add((bf: Uint8Array) => {
    // const lenbf = bf.length;
    const curBf = client.GetCurArrayBuffer();
    const curBf2 = new Uint8Array(curBf);
    try {
      const msgBase = decodeMsgBase(curBf2);
      console.log("msgBase.MsgId", msgBase.MsgId);
      if (ListenPbFuncMap.has(msgBase.MsgId)) {
        let funcList = ListenPbFuncMap.get(msgBase.MsgId);
        console.log("func count", funcList.length);
        for (let index = 0; index < funcList.length; index++) {
          funcList[index](msgBase.MsgData);
        }
      }
    } catch (error) {
    }
  })
  addMsgListen = true
  return 0;
}
`
最开始想的是收到消息后封成结构体，然后事件派发出来，在ts里直接监听事件来处理。
遇到的情况是ts里收到的对象是空的，log长度也是undefined。
然后我绕了一下，c++里封到结构体后往bfArray里塞，ts再事件里来pop取，这样是能取的到对象的。

### 问题重现 | Bug reproduce

.

**Comment by chexiongsheng** [comment]
我试了传过来的是对象，不是空。
你声明的回调有问题，回传的对象是ArrayBuffer，并不是Uint8Array

**Comment by chexiongsheng** [comment]
我这段代码能打印数据
~~~typescript
actor.NotifyWithArrayBuffer.Add((A:ArrayBuffer) => {
    console.log('-------------------------------------------------');
    console.log(typeof A);
    var b = new Uint8Array(A);
    for(var i = 0; i < b.length; i++)
    {
        console.log(b[i]);
    }
});

~~~
