### ISSUE TITLE
[UE] 支持通过typescript decorator 为Actor添加Component

### ISSUE THREAD

**Issue by chexiongsheng** [Tencent/puerts#1250]
## detail | 详细描述
目前继承ue的Actor的ts类，要加在ts添加Component，需要Constructor里调用CreateDefaultSubobject，但CreateDefaultSubobject需要在ue类的构造函数中执行，ts的Constructor能在大多数情况下能在ue类的构造函数，但如果开启了AsyncLoadingThreadEnabled，在非GameThread加载蓝图时，会被延迟加载，CreateDefaultSubobject会调用失败（崩溃）

本功能在生成蓝图时，就分析decorator获取Component路径信息，往蓝图加入Component，和手动添加一样。

**Comment by ljporljp** [comment]
要是decorator种可以指定组件的名字，且能被this直接访问就更完美了（就完全和蓝图没有区别了）

**Comment by yyj2013-two** [comment]
现在能用了吗? 怎么使用?

**Comment by chexiongsheng** [comment]
> 要是decorator中可以指定组件的名字，且能被this直接访问就更完美了（就完全和蓝图没有区别了）

其实也不用decorator，之前想偏了，现在版本的蓝图类型已经包含路径信息了。不需要用decorator加。只要在处理变量那发现是UActorComponent类型就直接按加组件的方式加即可。

**Comment by chexiongsheng** [comment]
> 现在能用了吗? 怎么使用?

才刚开始开发。

**Comment by chexiongsheng** [comment]
> 现在能用了吗? 怎么使用?

添加了，改动不多，可以试试。

**Comment by ljporljp** [comment]
> 

这个方案更好一点，相当于替换了手动添加组件。跟原来手动蓝图里添加组件会生成一个对应名字的变量逻辑一致了。

**Comment by chexiongsheng** [comment]
进一步测试发现些问题，先别用，修改好了再通知

**Comment by chexiongsheng** [comment]
> 进一步测试发现些问题，先别用，修改好了再通知

其实不是问题：测试发现在构造函数访问不了组件（null），定位发现是正常的，蓝图添加的component在构造的最后阶段才赋值。

之前fps的例子根据新版本修改是这样：https://github.com/chexiongsheng/BlockBreakerStarter

**Comment by chexiongsheng** [comment]
> 几个建议： 1、删掉变量之后不会自动删除，可帮助自动删除，否则可能导致遗留冗余 2、可以通过decorator来标记层级关系，否则只能手动修改生成的代理蓝图，感觉不太好

你可以尝试加下然后PR给我

**Comment by ljporljp** [comment]
> > 几个建议： 1、删掉变量之后不会自动删除，可帮助自动删除，否则可能导致遗留冗余 2、可以通过decorator来标记层级关系，否则只能手动修改生成的代理蓝图，感觉不太好
> 
> 你可以尝试加下然后PR给我

好的 ，自动删除挂上去的component我这边写好了，我整理下给你

**Comment by chexiongsheng** [comment]
> 几个建议： 1、删掉变量之后不会自动删除，可帮助自动删除，否则可能导致遗留冗余 2、可以通过decorator来标记层级关系，否则只能手动修改生成的代理蓝图，感觉不太好

2已经实现，可以更新试试
