### ISSUE TITLE
[UE] Bug: Can not compatible with some JavaScript bundlers.

### ISSUE THREAD

**Issue by PrimaryFantasty** [Tencent/puerts#1252]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

All

### UE的版本 | UE Version

All

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

"ue"等ts模块中的类型无法找到.

### 问题重现 | Bug reproduce

使用一些常见的JS构建工具，例如Rollup.js，tsup等，bundle代码后运行，日志中即可看到报错信息。

**Comment by chexiongsheng** [comment]
webpack可以声明ue是外部模块，相信其它构建工具也会有类似的设置。

**Comment by PrimaryFantasty** [comment]
> webpack可以声明ue是外部模块，相信其它构建工具也会有类似的设置。

确实可以声明是外部模块的，但是它们一般会作类似这样的操作：
[dynamic import interop in rollup.js](https://github.com/rollup/rollup/pull/2954)
在tsup中，确实也声明了外部模块，转换后的代码是commonjs的。比如，我把"ue"设置为外部模块后，它会转成直接调用require函数的代码：
![image](https://user-images.githubusercontent.com/36122477/224889128-e5e03e32-67bd-4bce-a3e8-b89ccd14fb1b.png)
目前我的方式是遵循这些打包器的习惯，设置了__esModule为true。

**Comment by PrimaryFantasty** [comment]
解决方案可参考 #1253 
或者，当构建工具没有良好的配置选项时，参考本issue的思路也能避开这个问题，但做法并不符合ECMA规范。
