### ISSUE TITLE
[UE] Bug: 蓝图AnimNotify调用父类ts的函数失效（第二次PIE运行的情况下）

### ISSUE THREAD

**Issue by rogerhdh** [Tencent/puerts#1257]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

v1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

第二次PIE运行的情况下，蓝图AnimNotify调用父类ts的函数失效。初步检查问题在于RebindJS中的LazyLoadRedirect导致的问题。

### 问题重现 | Bug reproduce

- 添加TS父类

class TsDebugAnimNotify extends UE.AnimNotify

{
    public OutputLog() : void { console.log("Call in"); }
}

- 建立蓝图资产 BP_DebugAnimNotify 继承自TsDebugAnimNotify，BP_DebugAnimNotify中添加Received_Notify，调用父类OutputLog函数。

- 动作中添加BP_DebugAnimNotify，播放动作触发调用。

**Comment by chexiongsheng** [comment]
要不你试试最新的版本？最新这块有调整。

**Comment by rogerhdh** [comment]
好，我们先更新一下试试

**Comment by chexiongsheng** [comment]
方便提供个demo么？最好基于https://github.com/chexiongsheng/puerts_unreal_demo

**Comment by chexiongsheng** [comment]
还有是不是有某个版本是没问题的呢？

**Comment by rogerhdh** [comment]
> 方便提供个demo么？最好基于https://github.com/chexiongsheng/puerts_unreal_demo

bug重现工程地址：https://github.com/rogerhdh/puerts_unreal_demo.git
首次PIE运行会刷日志：anim notify debug log，二次PIE运行就没有了

**Comment by chexiongsheng** [comment]
我连首次都显示不了日志

**Comment by rogerhdh** [comment]
执行了node enable_puerts_module.js吗？
https://puerts.github.io/docs/puerts/unreal/uclass_extends

**Comment by chexiongsheng** [comment]
重现了
