### ISSUE TITLE
[UE] Bug: 静态绑定 UGameplayTagsManager的Get函数报错

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1258]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

模板编译报错

### 问题重现 | Bug reproduce

		puerts::DefineClass<UGameplayTagsManager>()
			.Function("Get", MakeFunction(&UGameplayTagsManager::Get))
			.Register();

按照文档来的，但这个编译过不了

**Comment by chexiongsheng** [comment]
至少贴个报错信息

**Comment by ljporljp** [comment]
Error	C2027	use of undefined type 'puerts::converter::Converter<UGameplayTagsManager,void>
Error	C3861	'toScript': identifier not found

**Comment by ljporljp** [comment]
补充：已有前置声明 UsingUClass(UGameplayTagsManager)

**Comment by chexiongsheng** [comment]
~~~c++
puerts::DefineClass<UGameplayTagsManager>()
                .Function("Get", SelectFunction_PtrRet(UGameplayTagsManager& (*)(), &UGameplayTagsManager::Get))
                .Register();
~~~

**Comment by chexiongsheng** [comment]
我改下，如果非const 引用直接按指针返回好了，不用特别指明

**Comment by chexiongsheng** [comment]
你更新下，直接用MakeFunction即可

**Comment by ljporljp** [comment]
好的。用SelectFunction_PtrRet没问题。顺带问下，很多返回值是const的好像都绑定不了？

**Comment by chexiongsheng** [comment]
具体问题具体分析

**Comment by ljporljp** [comment]
就比如还是这个UGameplayTagsManager类里面的GetSingleTagContainer函数，直接用MakeFunction好像就绑定不了

**Comment by chexiongsheng** [comment]
const UStruct是有问题，你更新下

**Comment by ljporljp** [comment]
好的，感谢
