### ISSUE TITLE
unreal git拉取的编译会报找不到NotificationManager.h在DeclarationGenerator.cpp中，用示例中的则不会

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#126]

**Comment by FishOrBear** [comment]
加一下QQ看看? 908666218

**Comment by FishOrBear** [comment]
在DeclarationGenerator.cpp中,把下面两条inculde改成下面这种全路径的试试
```
#include "Framework/Notifications/NotificationManager.h"
#include "Widgets/Notifications/SNotificationList.h"
```

**Comment by mingxxming** [comment]
> 在DeclarationGenerator.cpp中,把下面两条inculde改成下面这种全路径的试试
> 
> ```
> #include "Framework/Notifications/NotificationManager.h"
> #include "Widgets/Notifications/SNotificationList.h"
> ```

这个可以修复的
