### ISSUE TITLE
[UE] discussion blueprint.load 和 UE.Class.Load 有什么区别？

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1263]
## detail | 详细描述
比如两者是否都会加载蓝图？

**Comment by chexiongsheng** [comment]
Load方法不是UE.Class独有的，UE.Object及其子类都有Load方法，对应C++的StaticLoadObject，用于加载资源，蓝图类也是资源的一种。
blueprint.load是让对应的蓝图加载成js/ts类，文档有。

**Comment by ljporljp** [comment]
blueprint.load好像可以通过命名空间加载？目前Load只能通过路径么？

**Comment by chexiongsheng** [comment]
看文档。
不过我觉得两个就完全没啥关系的api，用来对比有点奇怪。

**Comment by ljporljp** [comment]
可能因为Load一般用来加载蓝图比较多，而blueprint.load名字可能让我会以为有类似功能。。。
