### ISSUE TITLE
[UE] Bug:  ts派生的actorcomonent使用rpc，不能被ts派生的actor调用。但是可以被蓝图派生的actor调用 代码https://github.com/yyj2013-two/puerts_unreal_demo.git

### ISSUE THREAD

**Issue by yyj2013-two** [Tencent/puerts#1265]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/54255051/226184980-a22e0e1c-0e04-4270-8962-3ee3b5d44bb1.png)
![image](https://user-images.githubusercontent.com/54255051/226185134-cf93fc6b-7d82-4a7a-a3f6-2ab835ea8c35.png)
![image](https://user-images.githubusercontent.com/54255051/226185189-dea81d82-fd21-4665-9096-328aa0756d14.png)
蓝图直接派生character后添加ts_equipmentCtrl后调用
![image](https://user-images.githubusercontent.com/54255051/226185260-662b17ac-97f6-4a81-a9b3-620f1a118c4d.png)

**Comment by yyj2013-two** [comment]
![image](https://user-images.githubusercontent.com/54255051/226185435-92c154b1-6277-4a7a-99b2-977c82212bae.png)

**Comment by yyj2013-two** [comment]
![image](https://user-images.githubusercontent.com/54255051/226185510-3d604b5d-3d52-4da5-a3f3-f556aeb20fa0.png)

**Comment by yyj2013-two** [comment]
使用的是node16

**Comment by chexiongsheng** [comment]
直接fork puerts_unreal_demo工程修改个重现的工程？
每个issue我还要搞个工程去重现就太废时间了，中间还可能因为一些细节重现不了

**Comment by yyj2013-two** [comment]
上传了一个工程https://github.com/yyj2013-two/puerts_unreal_demo.git

**Comment by chexiongsheng** [comment]
这工程要怎么重现问题呢？我Play后没什么反应，也没你说的打印

**Comment by chexiongsheng** [comment]
==，貌似我看到原因了，你用的是makeUClass？？
这API不支持RPC，而且已经废弃了。
直接用UE.Class.Load加载即可。
