### ISSUE TITLE
[Unity] Bug: import 不支持 node_modules 模块

### ISSUE THREAD

**Issue by sbfkcel** [Tencent/puerts#1266]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4.1

### Unity的版本 | Unity Version

2021

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

自定义模块可使用 `import` 导入。

而安装在 `node_modules` 目录中的 `npm` 模块不能通过 `import` 方法导入。

### 问题重现 | Bug reproduce

```bash
npm install source-map-support
```
```javascript
// 自定义模块可以
import sum from './sum';

// npm模块不行
import sms from 'source-map-support';
```

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts-ts-loader/blob/main/upm/Samples~/Sample4/Assets/Editor/Typescripts/main.mts

 相关功能已放在`ts-loader`包实现
