### ISSUE TITLE
[UE] Bug:打包后JS代码不执行

### ISSUE THREAD

**Issue by 313364973** [Tencent/puerts#1269]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.3

### UE的版本 | UE Version

UE5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

很简单的一个demo，打包测试js运行情况，发现js并没有运行，是打包的时候还需要其他设置吗，谢谢大佬们了

### 问题重现 | Bug reproduce

我的打包流程如下:
1.github下载Unreal_v1.0.3 release版本
2.拷贝到项目的plugins下
3.在项目的typescipte文件夹下新建TS_TestAct.ts 文件
4.文件内容如下：
import * as UE from "ue";
class TS_TestAct extends UE.Actor{
    ReceiveBeginPlay():void{
        UE.KismetSystemLibrary.PrintString(this.GetWorld(),"脚本执行了",true,true)
    }
}
export default TS_TestAct
5.编辑器运行，顺利输出了脚本执行了文本
6.项目打包设置里，在 addtional Non-Assets packages 目录添加项目下的javascript目录
7.打包windows，然后运行，发现没有输出脚本执行了关键词

**Comment by 313364973** [comment]
又测试了一个情况，在关卡蓝图中，直接生成这个蓝图，是会执行的，但是直接把这个蓝图放到关卡中就不会执行，这种情况怎么弄，大佬。。

**Comment by 313364973** [comment]
@chexiongsheng 大佬给看看，谢谢了，项目立项阶段，各个环节想跑通一下。非常感谢大佬了！

**Comment by chexiongsheng** [comment]
1.0.3需要关闭AsyncLoadingThreadEnabled。
master版本有可能不用，可以试试。

ps，如果新立项，建议自创建虚拟机方式来使用，这样脚本和引擎有清晰的界限。（unity项目的脚本都是这种方式）
而ts继承ue类型这个功能，主要是面向开发了一段时间的项目，容易切入现有系统。

**Comment by 313364973** [comment]
感谢大佬指点！
