### ISSUE TITLE
[UE] Bug: windows下使用nodejs16作为后端时，访问https服务会报错

### ISSUE THREAD

**Issue by laughxing** [Tencent/puerts#1271]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

> Puerts: Warning: (0x0000045A278C00B0) JS Execution Exception: node:internal/deps/undici/undici:2172: TypeError: Cannot destructure property 'socket' of 'parser' as it is undefined.
TypeError: Cannot destructure property 'socket' of 'parser' as it is undefined.
    at onParserTimeout (node:internal/deps/undici/undici:2172:15)

### 问题重现 | Bug reproduce

windows editor中使用nodejs做后端，使用langchain库进行https请求后必然出现

**Comment by chexiongsheng** [comment]
标题描述下简要信息？

**Comment by chexiongsheng** [comment]
你试试合入这个commit：https://github.com/Tencent/puerts/commit/d6007cc73e971c825a85c164ca4273a543b8dad8

**Comment by chexiongsheng** [comment]
要注意覆盖两个地方：Content\JavaScript\puerts，Plugins\Puerts\Content\JavaScript\puerts

**Comment by laughxing** [comment]
`Puerts: Warning: (0x0000045A33A4DD30) unhandledRejection,Error: Network Error,Error: Network Error
    at createError (C:\StackOBot_UGC\Content\JavaScript\langchain.gen.js:22567:19)
    at getResponse (C:\StackOBot_UGC\Content\JavaScript\langchain.gen.js:22464:16)
    at async fetchAdapter (C:\StackOBot_UGC\Content\JavaScript\langchain.gen.js:22441:18)
Puerts: Warning: (0x0000045A33A4DD30) unhandledRejection,Error: Network Error,Error: Network Error
    at createError (C:\StackOBot_UGC\Content\JavaScript\langchain.gen.js:22567:19)
    at getResponse (C:\StackOBot_UGC\Content\JavaScript\langchain.gen.js:22464:16)
    at async fetchAdapter (C:\StackOBot_UGC\Content\JavaScript\langchain.gen.js:22441:18)
Puerts: Warning: (0x0000045A33A4DD30) unhandledRejection,TypeError: Cannot read properties of undefined (reading 'unref'),TypeError: Cannot read properties of undefined (reading 'unref')
    at Parser.setTimeout (node:internal/deps/undici/undici:1823:30)
    at _resume (node:internal/deps/undici/undici:2388:31)
    at resume (node:internal/deps/undici/undici:2351:7)
    at connect (node:internal/deps/undici/undici:2340:7)`

运行报错

**Comment by chexiongsheng** [comment]
那你试试改为用nodejs原生的timer：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L535

这的宏打开

**Comment by chexiongsheng** [comment]
同样的代码在16.16版本nodejs官方版本能跑么？贴个简单重现代码

**Comment by laughxing** [comment]
> 

使用修改就就暂时没有错误了

**Comment by chexiongsheng** [comment]
> > 那你试试改为用nodejs原生的timer：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L535
> 
> 使用修改就暂时没有错误了

那还是和timer有关，但我新提交的那个timer的修改，应该和nodejs的timer一样的，我说的两个地方都覆盖了么？

**Comment by laughxing** [comment]
两个地方都覆盖了，我刚又重新试了一下：
master代码，只新增commit https://github.com/Tencent/puerts/commit/d6007cc73e971c825a85c164ca4273a543b8dad8 的内容，报错如下：
![image](https://user-images.githubusercontent.com/17986587/228462418-af847ae4-a787-494b-99a3-c362e6e03d29.png)
在打开了c++宏的情况下，再加入这个commit也会报错：
![image](https://user-images.githubusercontent.com/17986587/228463846-b1336d92-95c5-44e6-a4dc-e062250852f1.png)

**Comment by chexiongsheng** [comment]
简单的重现代码发来看看？

**Comment by chexiongsheng** [comment]
之前的修改是有点问题，你再合入这个看看：https://github.com/Tencent/puerts/commit/73c2ec0f70986a88bc6c7392ffdee0468844856f

**Comment by laughxing** [comment]
刚才试了一下，可以解决
