### ISSUE TITLE
[Unity] Issue about call timing of JsEnv.Eval and JsEnv.Tick when running async function of javascript

### ISSUE THREAD

**Issue by danij91** [Tencent/puerts#1278]
## detail | 详细描述
Running RunWs_default.cs does not produce results, but running RunWs_fixed.cs results in a web socket being connected. I don't know why, but if A function is called even once before B function is called, the script didn't run properly. Let me know if you guys know what the problem is.
Thank you for reading this issue and for your hard work. Puerts is really useful and interesting for me. 

**wsTest.js**
```javascript
const ws = require('ws');
const wsk  = new ws("ws://$IP_ADDRESS:8080");

wsk.onopen = (e)=> {
    console.log("$NAME connected to server");
}
``` 

RunWs_default.cs( not working)
```c#
    private JsEnv env;
    public void Start()
    {
        env = new JsEnv();
    }

    public void Update()
    {
        env?.Tick();
    }

    public void OnClickBtn()
    {
        env.Eval("CONTENTS OF wsTest.js");
    }
``` 

RunWs_fixed.cs( working)
```c#
      private JsEnv env;

      public void Update()
      {
          env?.Tick();
      }
  
      public void OnClickBtn()
      {
          env = new JsEnv();
          env.Eval("CONTENTS OF wsTest.js");
      }
```

**Comment by zombieyang** [comment]
Do you solve this?
