### ISSUE TITLE
[Unity] Bug: Issue about call timing of JsEnv.Eval and JsEnv.Tick when running async function of javascript

### ISSUE THREAD

**Issue by danij91** [Tencent/puerts#1279]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4.0

### Unity的版本 | Unity Version

2021.3.17f

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

no error message..

### 问题重现 | Bug reproduce

Running RunWs_default.cs does not produce results, but running RunWs_fixed.cs results in a web socket being connected. I don't know why, but if A function is called even once before B function is called, the script didn't run properly. Let me know if you guys know what the problem is.
Thank you for reading this issue and for your hard work. Puerts is really useful and interesting for me. 

**wsTest.js**
```javascript
const ws = require('ws');
const wsk  = new ws("ws://$IP_ADDRESS:8080");

wsk.onopen = (e)=> {
    console.log("$NAME connected to server");
}
``` 

RunWs_default.cs( not working)
```c#
    private JsEnv env;
    public void Start()
    {
        env = new JsEnv();
    }

    public void Update()
    {
        env?.Tick();
    }

    public void OnClickBtn()
    {
        env.Eval("CONTENTS OF wsTest.js");
    }
``` 

RunWs_fixed.cs( working)
```c#
      private JsEnv env;

      public void Update()
      {
          env?.Tick();
      }
  
      public void OnClickBtn()
      {
          env = new JsEnv();
          env.Eval("CONTENTS OF wsTest.js");
      }
```

**Comment by zombieyang** [comment]
You can get a quick fix by adding another async invokation, such as:
```
const wsk  = new ws("ws://127.0.0.1:8080");
wsk.onopen = (e)=> {
    console.log("$NAME connected to server");
}
wsk.onerror = (e)=> {
    console.trace("$NAME error");
}

const fs = require('fs');
fs.readFile('whatever', function() {

});
```
I'll review it after #1093 is done

**Comment by danij91** [comment]
@zombieyang It works! Thanks a lot!
