### ISSUE TITLE
[UE] Bug: 删除代理蓝图后重新生成后出现 触发断言和函数失效

### ISSUE THREAD

**Issue by xixixi3** [Tencent/puerts#1280]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

bug1:使用ts继承组件生成的代理蓝图的beginplay事件节点有几率为灰色，即没有setenable。
附上解决原因和解决方法：
原因：新创建的蓝图会创建默认节点，然后蓝图没有刷新导致uclass 的superfuncmap没有转移到funcmap，
解决方法：在创建完新蓝图后调用FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified;
或者关闭ue设置里的 spawndefaultblueprintnodes;

 bug2:  重新生成的ts代理蓝图反序列化pin触发断言
附上解决原因和解决方法：
原因：新创建的蓝图会创建默认节点，而部分默认节点不一定在ts文件上重写，然后导致removenotexistedfunction会删除这个节点导致部分pin失效
解决方法：
（1）关闭ue设置里的 spawndefaultblueprintnodes;
（2）建议作者能完善相关代码。

### 问题重现 | Bug reproduce

删除代理蓝图后重新生成

**Comment by chexiongsheng** [comment]
新建或修改都有调用FBlueprintEditorUtils::MarkBlueprintAsModified（不是MarkBlueprintAsStructurallyModified）：
https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/Plugins/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp#L1089
你试试再加个MarkBlueprintAsStructurallyModified？

bug2是必现的么？具体怎么重现呢？

**Comment by xixixi3** [comment]
在save的时候调用FBlueprintEditorUtils::MarkBlueprintAsModified已经来不及了。会在addfunction的时候错过默认蓝图事件节点的setenable。我本地在createblueprint后调用MarkBlueprintAsStructurallyModified表现就正常了。

bug2 我这边的表现是 一个继承了actor的ts类里面没有重新actoroverlap的函数时候会触发。关闭生成默认蓝图节点后表现正常，而且触发断言还得关闭editor后重新启动再打开才会触发。

**Comment by chexiongsheng** [comment]
我在5.1.1没触发你说的问题，也找不到spawndefaultblueprintnodes选项
