### ISSUE TITLE
[Unity]/[UE] suggestion 静态绑定 World SpawnActor方法 参数Transform 该使用UsingCppType(Transform )申明吗

### ISSUE THREAD

**Issue by 313364973** [Tencent/puerts#1282]
想绑定下World的SpawnActor方法，知道UClass 需要用UsingUClass来申明，但是FTransform怎么申明呢，尝试了UsingCppType(FTransform)后
到处的ts是 SpawnActor(p0: Class, p1: cpp.Transform, p2?: cpp.ActorSpawnParameters) : Actor;
里面的p1:cpp.Transform 应该是UE.Transform才对吧
获取使用的方法不对,这里应该是怎么样申明呢，谢谢啦

UsingUClass(UWorld);
UsingUClass(UObject)
UsingUClass(UClass)
UsingUClass(AActor)
AutoRegisterForCPP()
	{
		puerts::DefineClass<UWorld>()
		.Method("SpawnActor",
							SelectFunction(AActor*(UWorld::*)(UClass*,  FTransform const*  ,const FActorSpawnParameters&),
										   &UWorld::SpawnActor, FActorSpawnParameters()))
		.Register();
	}

**Comment by chexiongsheng** [comment]
UsingUStruct

**Comment by 313364973** [comment]
谢谢大佬！
