### ISSUE TITLE
[UE] Bug: 运行时热更失败，Puerts失去一半可用性

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1286]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

全部

### UE的版本 | UE Version

全部

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

打包运行后，APP运行中将升级热补丁拷贝到saved目录，重新打开地图，UE的各种更新正常工作，但是JS脚本无法重新加载，第一次热更有时候可以，第二次以后全部失败，调用Puerts自己的reloadmodule函数，可以解决这个问题，但是这个函数只支持Win/Mac。如果强退APP，重新打开APP，所有功能全部正常。

### 问题重现 | Bug reproduce

在以下这个仓库里，有讲到如何为移动平台添加inspector，实现移动端的reloadmodule函数功能

https://github.com/NativeScript/android/blob/main/docs/extending-inspector.md

**Comment by terst6** [comment]
如果将Puerts的v8项目共享出来，大家或许可以帮助完成该功能

**Comment by chexiongsheng** [comment]
为啥要搞得怎么复杂？移动端定义WITH_INSPECTOR宏即可。

其次，有什么puerts的v8项目？puerts用的是官方版本的v8，自动编译的工程在这里：https://github.com/puerts/backend-v8

**Comment by terst6** [comment]
> 为啥要搞得怎么复杂？移动端定义WITH_INSPECTOR宏即可。
> 
> 其次，有什么puerts的v8项目？puerts用的是官方版本的v8，自动编译的工程在这里：https://github.com/puerts/backend-v8

感谢提醒，之前看到 WITH_INSPECTOR那里，只看到了前面部分只对win/Mac有效，走了弯路。现在代码做了一些调整，可以正常工作了
