### ISSUE TITLE
[Unity] Bug: 生成 FunctionBridge.Gen.h 诺干问题汇总。

### ISSUE THREAD

**Issue by birnfly** [Tencent/puerts#1288]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0

### Unity的版本 | Unity Version

2021.3.8f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

生成 FunctionBridge.Gen.h 问题非常多。
1、静态属性、字段都不会生成，在js中赋值，在C#层都无法取到。暂时我用方法替换解决。
2、如果是Action类型的属性，在JS中赋值一个函数，在C#层调用，会直接crash，空指针错误。
3、new CS.UnityEngine.Color() 会报错 invalid arguments， new CS.UnityEngine.Color(0,0,0,0)  也一样，暂时无解。
4、puer.$generic 生成的类方法缺失，暂时无解。

    const ByteList = puer.$generic(CS.Collections.Generic.List$1, CS.System.Byte);
    let bytes=new ByteList();
    bytes.GetRange(0,100);
    然后报错 bytes.GetRange is not a function

    我 PuertsConfigs 中绑定配置了typeof(List<int>),  typeof(List<byte>),   typeof(List<Vector3>), 等，
    但是在FunctionBridge.Gen.h中只生成了 一个 
    System.Collections.Generic.List`1[System.Int32] GetRange(Int32, Int32)

### 问题重现 | Bug reproduce

以上问题直接可以重现

**Comment by birnfly** [comment]
以上都是v1.x下的工程升级上来并使用IL2CPP所遇到的问题。原本在v1.x下都是正常的。

**Comment by zombieyang** [comment]
问题1无复现，一切正常
问题2已复现
问题3在反射模式下复现了crash而非报错，生成模式正常
问题4已复现，本质上似乎是裁剪问题，在C#侧有调用过就正常。

**Comment by birnfly** [comment]
我怀疑除了问题2，其它都是裁剪的问题。
我如何避免某些函数被裁减？由于我做小游戏，几乎所有业务逻辑都写在JS端。
之前版本在PuertsConfigs添加相关类的绑定就没问题了。而现在貌似无效了。

**Comment by zombieyang** [comment]
> 我怀疑除了问题2，其它都是裁剪的问题。 我如何避免某些函数被裁减？由于我做小游戏，几乎所有业务逻辑都写在JS端。 之前版本在PuertsConfigs添加相关类的绑定就没问题了。而现在貌似无效了。

生成link.xml的功能就是解决这个问题的，你加进bindingList然后生成link.xml理论上就能解决

**Comment by birnfly** [comment]
> > 我怀疑除了问题2，其它都是裁剪的问题。 我如何避免某些函数被裁减？由于我做小游戏，几乎所有业务逻辑都写在JS端。 之前版本在PuertsConfigs添加相关类的绑定就没问题了。而现在貌似无效了。
> 
> 生成link.xml的功能就是解决这个问题的，你加进bindingList然后生成link.xml理论上就能解决

我每次都点了重新生成呀，all in one 难道不包括link.xml 吗？

**Comment by zombieyang** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/5595819/231159350-778606a1-a1e3-4a05-97d4-c1c54f0ab59d.png">
根据官方文档的说法，整个IL2CPP的过程如上。

也就是说，只有在从C#到IL这个步骤中就存在的代码，才会经过code strip的步骤，最终被编译为CPP。
而具体的泛型类（比如`List<Byte>`），如果在C#中没有被使用到，它从第1步开始就不会参与到IL2CPP的过程，最终也无法在编译后的IL2CPP代码中使用。`link.xml`只会改变第二步的行为，对这个情况束手无策

所以问题4的解法只有在C#中添加相关的使用代码。或者直接生成v1的wrapper，并解除wrapper中关于IL2CPP绑定的判定宏。

**Comment by birnfly** [comment]
好的谢谢
