### ISSUE TITLE
[Unity] Question: 是否支持限制 JsEnv 的访问能力？

### ISSUE THREAD

**Issue by sesky4** [Tencent/puerts#1289]
hi，谢谢你们开源 puerts ❤️
 
## 我的使用场景
用户传入一个string，然后程序内通过 JsEnv 去执行该 string

## 碰到的问题
因为输入是不受信任的，因此需要在运行环境中加以限制。

## 我期望的使用方式
默认不支持任何API（也就是说无法 require 任何内置库，尤其是 CS，通过 CS 可以访问任意 Unity API ），仅开放我手动指定的 module。

在官网文档中似乎没有找到相关的文档，因此在这里提问，希望得到你们的帮助，谢谢！ ❤️

**Comment by zombieyang** [comment]
CS对象 可以通过这个宏禁用反射能力，这样就只有你生成了wrapper的接口可被调用。
https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Runtime/Src/TypeRegister.cs#L656
这个宏会全局生效，所以我正在想一个可以让每个env有单独配置的办法。

------
require什么的就比较简单了，直接delete就可以了

**Comment by sesky4** [comment]
@zombieyang 明白了，谢谢！

**Comment by sesky4** [comment]
看到最新版本 2.0.0-pre.1 已经把 EXPERMENTIAL_PUERTS_DISABLE_SLOWBINDING 修改为了 PUERTS_DISABLE_SLOWBINDING

但是定义该宏后 codegen 会报错
<img width="901" alt="image" src="https://user-images.githubusercontent.com/13792533/232277994-be9137e8-5942-4a0b-bddc-965894cbea76.png">

错误是在 codegen 的时候 wrapper.tpl.mjs 脚本中无法拿到 StaticWrapperInfo 的字段（ 拿到了 undefined ），并且 console.log 也无法使用。

大概看了一下代码，似乎原因是开启 PUERTS_DISABLE_SLOWBINDING 后无法通过反射访问了，但是在 codegen 的时候因为也需要使用一些类，但是这些类没有 StaticWrapper，陷入了死循环。
https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Runtime/Src/TypeRegister.cs#L656

临时修改了下，不知道这种方案是否可行？
<img width="768" alt="image" src="https://user-images.githubusercontent.com/13792533/232278637-2e422c81-ae13-4b90-a86b-594ea18e8576.png">

**Comment by zombieyang** [comment]
这就是为什么我说需要一个让不同JsEnv使用不同设置的配置办法。
你的临时修改方案是可以的，不过从Puer的角度来说是直接一步到位实现最终方案更好。
