### ISSUE TITLE
[UE4] js原生数组如何转为ue4的TArray

### ISSUE THREAD

**Issue by jemoo** [Tencent/puerts#129]
ue.d.ts:
// 自动生成的蓝图类
class BP_TestActor_C extends Actor {
        TestVerts(Verts: $Ref<TArray<Vector>>): void;
}

test.ts
let verts = new Array<UE.Vector>();
...
//调用TestVerts时如何传参verts？

**Comment by FishOrBear** [comment]
在c++那边包装一下,在js这边调用.
