### ISSUE TITLE
[UE] Bug: 在执行委托回调JS某个函数时，出现了v8::base::OS::Abort() 崩溃

### ISSUE THREAD

**Issue by scutDavid** [Tencent/puerts#1291]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.2

### UE的版本 | UE Version

4.24

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

在执行委托回调JS某个函数时，出现了v8::base::OS::Abort()
![image](https://user-images.githubusercontent.com/30872025/231115901-ef761a91-c100-4341-a20e-e84158726a6a.png)
![image](https://user-images.githubusercontent.com/30872025/231115499-4ef128a2-39a0-4e25-8335-c63742218f1c.png)
委托带有一个FString 参数，委托是绑定在一个广播上：
![image](https://user-images.githubusercontent.com/30872025/231116857-68632bde-6cb6-4146-b97c-077bdb50ba55.png)
委托：
![image](https://user-images.githubusercontent.com/30872025/231117311-3ee89580-1e9a-4ab3-baee-cec3bcfbc640.png)
是FString的构建上不规范吗，

### 问题重现 | Bug reproduce

这是个偶现的，有和它类似的带单个FString 参数的委托回调JS时一直没问题。

**Comment by chexiongsheng** [comment]
可以把EscapableHandleScope的使用都去掉，目前看是多余的。

**Comment by chexiongsheng** [comment]
更新下，我直接不用这个api了

**Comment by scutDavid** [comment]
> 更新下，我直接不用这个api了

好的，感谢车神！
