### ISSUE TITLE
[Unity]支持new JsEnv时指定v8或者quickjs backend

### ISSUE THREAD

**Issue by chexiongsheng** [Tencent/puerts#1293]
## detail | 详细描述

业务有v8和quickjs backend同时并存的需求。

该需求的短期实现方案：
1、qjs模拟的v8 api的namespace改用宏定义，不定义宏默认是v8；
2、一个纯虚puerts::IJSEngine和不同实现puerts::v8::JSEngine和puerts::qjs::JSEngine
3、new JsEnv时，调用CreateJSEngine传入参数选择backend，JSEngine根据参数去new puerts::v8::JSEngine或者puerts::qjs::JSEngine；
4、对每一个plugin对C#接口，都在puerts::IJSEngine新增一个对应虚函数，实现挪动到puerts::v8::JSEngine和puerts::qjs::JSEngine
5、所有plugin对C#接口都改为接收puerts::IJSEngine参数，然后调用puerts::IJSEngine上对应的虚函数；

中长期的方案：
puerts::qjs::JSEngine直接调用qjs的接口实现即可，省掉一层封装性能更优；

**Comment by sesky4** [comment]
mark, 顺便问下什么场景下会需要共存两个backend ?

**Comment by chexiongsheng** [comment]
> mark, 顺便问下什么场景下会需要共存两个backend ?
有个sdk用了quickjs版本puerts。
有个游戏用了这个sdk，并且他们想用v8版本的puerts。

**Comment by chexiongsheng** [comment]
从 https://github.com/Tencent/puerts/commit/a8e5094ac89791a78a2a5daac3fc4e1ee7912031 到 https://github.com/Tencent/puerts/commit/c1723d4b6e5cd5262298425fc4336274a9fafb89 是对原版的一些调整，变化不大，主要是支持名字空间可定制。

https://github.com/Tencent/puerts/commit/148dbc42312490ab54ae3370719ae52780472a46 是支持运行时指定脚本后端的实现，思路如下：
* 把原先plugin对c#暴露的接口都作为IPuertsPlugin的一个待实现的函数
* 用v8和quickjs分别实现IPuertsPlugin，创建IPuertsPlugin实例根据参数去new v8的实现和quickjs的实现。
    - 这步骤取了个巧：两个实现的逻辑是共享的，区别是调用的是v8的api还是qjs模拟的api，后者名字空间通过宏修改为v8_qjs
    - 引用部分通过名字空间别名实现调用逻辑不修改
    ~~~c++
    #if defined(QJS_BACKEND)
    namespace v8 = v8_qjs;
   #endif
    ~~~_
    - 实现部分通过更改名字空间原版为puerts，通过宏变更为puerts_v8（对应v8实现），puerts_qjs（对应qjs实现）

**Comment by chexiongsheng** [comment]
有个小插曲：切换到quickjs时，ut用例不过。
一开始以为是我的动态切换版本有问题，花了很长时间，才发现我双backend plugin用的backend_quickjs是最新版本，而puerts的ut还是指向一个去年中的版本，如果指向最新版本，纯quickjs的ut用例也不过。
最终定位是这个提交引起的： https://github.com/puerts/backend-quickjs/commit/318933c4b0fcd38e7edfdc821360b6e76db87acd  ，这个提交修正了backend_quickjs的不合理的地方，但puerts之前的esm实现依赖了这个不合理的地方，而且通过小修改貌似改不了，稳妥起见就先在backend_quickjs回退改修改做一个临时版本（ https://github.com/puerts/backend-quickjs/tree/revert_for_unity_20240326 ）来使用，后续重做这部分（这部分quickjs和v8 api混用实现，不太合理）
