### ISSUE TITLE
[Unity] Bug: index.d.ts 生成时，BindingMode.DontBinding 方法的依赖依然会被生成。

### ISSUE THREAD

**Issue by birnfly** [Tencent/puerts#1295]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0

### Unity的版本 | Unity Version

2021.3.8f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

如题：index.d.ts 生成时，BindingMode.DontBinding 方法的依赖依然会被生成。

修复方案：
在DTS.cs 中的public static TypingGenInfo FromTypes(IEnumerable<Type> types)下，
找到：foreach (var method in type.GetMethods(Utils.Flags)
修改为：foreach (var method in type.GetMethods(Utils.Flags).Where(m => Utils.getBindingMode(m) != BindingMode.DontBinding))

![截屏2023-04-13 11 38 15](https://user-images.githubusercontent.com/7858384/231643425-90372fb0-ae2d-4e2d-b7e3-8d76e349f90f.png)

### 问题重现 | Bug reproduce

1、在[Binding]中，添加 System.Text.RegularExpressions.Regex 
2、在[Filter]中，对 CompileToAssembly方法 返回 BindingMode.DontBinding

此时生成的index.d.ts 中将会包含 CustomAttributeBuilder 类

实际上，CustomAttributeBuilder对象是CompileToAssembly方法的依赖，而该方法已经被忽略，没必要再生其依赖类。

**Comment by zombieyang** [comment]
是有问题。
不过你确认改发的话可以直接提PR过来。Field、Method、Constructor都要改。
