### ISSUE TITLE
第三方模块require时出错

### ISSUE THREAD

**Issue by huzhangyang** [Tencent/puerts#130]
查了一圈，目测原因是这次提交被后面的Commit不小心覆盖了：

https://github.com/Tencent/puerts/commit/8eb0494ad0a8b76f6ae7cc70909b0c0ef279a792

本地照着这个修复后正常了，麻烦主分支重新合并一下吧。

**Comment by chexiongsheng** [comment]
推个pr过来啊

**Comment by chexiongsheng** [comment]
我提交了
