### ISSUE TITLE
[Unity] Bug: ios 创建 JsEnv 报错

### ISSUE THREAD

**Issue by sesky4** [Tencent/puerts#1302]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0-pre.2

### Unity的版本 | Unity Version

2022.2.12f1c1

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

`Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.`

### 问题重现 | Bug reproduce

1. 创建空 unity 项目
2. openupm add com.tencent.puerts.core@2.0.0-pre.2 ( 从openupm下载的后端应该为 nodejs ? )
3. 创建 MonoBehaviour 附加到空 gameobject 上
```
public class NewBehaviourScript : MonoBehaviour
{
    void Start()
    {
        var env = new JsEnv();
        env.Eval("console.log('hello from js')");
    }
}
```
4. unity ios build, xcode 关闭 bitcode, xcode build
5. 真机 iPhone X 运行报错 `Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.`
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/13792533/232857942-ded7d277-9141-4efe-a378-51e48b0c34bb.png">

**Comment by watsonsong** [comment]
在编辑器上升级了puerts后也碰到了同样的问题，在创建JsEvn的时候崩溃：
 Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.

这个是要怎么解决？

**Comment by zombieyang** [comment]
> 在编辑器上升级了puerts后也碰到了同样的问题，在创建JsEvn的时候崩溃： Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
> 
> 拉了一个新工程，在执行node enable_puerts_module.js，打开了AutoModeEnable后就会出现这个崩溃。 这个是要怎么解决？

如果你是自己重编译的话，删除一下.backend文件夹。

enable_puerts_module.js是什么？
