### ISSUE TITLE
[Unity] 建议将assemble排除能力外移到EditorScript

### ISSUE THREAD

**Issue by yutongbus** [Tencent/puerts#1307]
## 现状
1. 目前在Puerts/Editor/Src/Generator/IL2Cpp/FileExporter.cs line:156 存在一处逻辑，生成wrapper时主动排除一些assemble，不遍历其中的类型。但如果需要加入其他排除assemble，则不得不修改源码。
因为遍历逻辑位于Filter之前，有些assemble遍历即报错，走不到Filter。所以并不能靠Filter来过滤。

2. 目前代码先遍历了所有assemble里的所有类型，再过滤assemble，效率偏低。

## 预期
1. 支持在EditorScript里配置排除assemble，提前过滤。
2. 先过滤asseble，再对剩下的assemble遍历类型。

**Comment by zombieyang** [comment]
#1317 

可在外面实现filter过滤此处的类，参考
https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/InstructionsFilter.cs
