### ISSUE TITLE
[UE] Bug: Puerts模块加载时机太晚导致 GameInstance 的ReceiveInit事件无法响应

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1318]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

这个提交 https://github.com/Tencent/puerts/pull/1284 把Puerts模块的加载时机直接滞后到PostEngineInit了，导致我用ts写的GameInstance类无法响应 ReceiveInit 事件

### 问题重现 | Bug reproduce

必现。

**Comment by ljporljp** [comment]
是因为把时机滞后到Default也会有其他问题么？

**Comment by Tangxinwei** [comment]
> 

放到default是因为，如果在其他模块进行了静态绑定，它可能比puerts更晚加载，导致静态绑定失效

**Comment by ljporljp** [comment]
> 会有其他问

现在是直接放到PostEngineInit了，导致ds服务器的GameInstance的ReceiveInit消息收不到。

**Comment by terst6** [comment]
4.27.2 在Win/IOS/android 下正常

**Comment by ljporljp** [comment]
我现在改为在Default，目前能解决我的问题，但是不知道会不会有其他问题，静态绑定我这也是好的，可能还没碰到需要放到PostEngineInit的问题。。。

**Comment by chexiongsheng** [comment]
@Tangxinwei 我想了下，应该静态绑定是不需要比JsEnv模块先加载的呀？只要执行js脚本时模块已经加载完毕即可，按理说不应该在模块加载完成前就执行js逻辑。

**Comment by chexiongsheng** [comment]
> @Tangxinwei 我想了下，静态绑定是不需要比JsEnv模块先加载的呀？只要执行js脚本时模块已经加载完毕即可，按理说不应该在模块加载完成前就执行js逻辑。

类似JsEnv->Start(TEXT("startup"))中启动的的startup脚本访问的静态模块。

**Comment by chexiongsheng** [comment]
现在GameInstance 的ReceiveInit不支持
更改模块加载时机可以支持，但评估下来，在“还有模块没加载完成”的时候，就执行脚本的行为比较危险。还是不支持比较好。

**Comment by terst6** [comment]
我的tsGameInstance类，有一个蓝图子类，用于定义修改ts类里的变量。在蓝图的 ReceiveInit事件后面添加parentinit，可以成功触发ts里的 ReceiveInit，现在是这么在用
