### ISSUE TITLE
[Unity] Bug: IL2CPP 闪退

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1320]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0-pre.0(master)

### Unity的版本 | Unity Version

2021.3.19f1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

闪退于GameInstance_ConsumeReceiveMsg_mBC5A93ED67D7AB6379B700F690602F9C72003D40

### 问题重现 | Bug reproduce

    public struct GIMsg {
        public int msgtp;
        public ArrayBuffer msg;
    }     

      public GIMsg? ConsumeReceiveMsg() {//闪退
            GIMsg? msg = null;
            if (ReceiveMsgQueue.Count > 0) {
                GIMsg m;
                if (ReceiveMsgQueue.TryDequeue(out m)) {
                    msg = m;
                }
            }
            return msg;
       }

      public GIMsg ConsumeReceiveMsg() {//正常
          GIMsg msg = new GIMsg();
          if (ReceiveMsgQueue.Count > 0) {
              GIMsg m;
              if (ReceiveMsgQueue.TryDequeue(out m)) {
                  msg = m;
              }
          }
          return msg;
      }

**Comment by mingxxming** [comment]
08 16:08:07.006  6877  6913 E CRASH   : Version '2021.3.19f1c1 (b8e3cea1e9d3)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
05-08 16:08:07.006  6877  6913 E CRASH   : Build fingerprint: 'HONOR/DUK-AL20/HWDUK:9/HUAWEIDUK-AL20/9.1.0.225C00:user/release-keys'
05-08 16:08:07.006  6877  6913 E CRASH   : Revision: '0'
05-08 16:08:07.006  6877  6913 E CRASH   : ABI: 'arm64'
05-08 16:08:07.006  6877  6913 E CRASH   : Timestamp: 2023-05-08 16:08:07+0800
05-08 16:08:07.006  6877  6913 E CRASH   : pid: 6877, tid: 6913, name: UnityMain  >>> com.developdream.rgd <<<
05-08 16:08:07.006  6877  6913 E CRASH   : uid: 10686
05-08 16:08:07.006  6877  6913 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
05-08 16:08:07.006  6877  6913 E CRASH   : Cause: null pointer dereference
05-08 16:08:07.006  6877  6913 E CRASH   :     x0  0000000000000000  x1  0000000000000000  x2  0000000000000000  x3  000000767359c378
05-08 16:08:07.006  6877  6913 E CRASH   :     x4  000000763fe5fc30  x5  0000007673281599  x6  00000077606bbef8  x7  0000000000000000
05-08 16:08:07.006  6877  6913 E CRASH   :     x8  0000000000000000  x9  0000000000000002  x10 0000000000000001  x11 0000000000000000
05-08 16:08:07.006  6877  6913 E CRASH   :     x12 0000000000000018  x13 0000000000000008  x14 000000763eff1791  x15 00000000bd8f63c6
05-08 16:08:07.006  6877  6913 E CRASH   :     x16 000000776540c020  x17 000000780ac86ac4  x18 0000000000000008  x19 0000000000000000
05-08 16:08:07.006  6877  6913 E CRASH   :     x20 000000767011ae40  x21 00000076735bd038  x22 00000077606bbcb8  x23 000000776225a308
05-08 16:08:07.006  6877  6913 E CRASH   :     x24 00000076735d6120  x25 00000077606bbd88  x26 000000764c1aed80  x27 00000076722b0f51
05-08 16:08:07.006  6877  6913 E CRASH   :     x28 0000007670125418  x29 00000077606bbc40
05-08 16:08:07.006  6877  6913 E CRASH   :     sp  00000077606bbb90  lr  000000776225a378  pc  000000776225a3c4
05-08 16:08:07.006  6877  6913 E CRASH   :
05-08 16:08:07.006  6877  6913 E CRASH   : backtrace:
05-08 16:08:07.006  6877  6913 E CRASH   :       #00 pc 0000000001a953c4(GameInstance_ConsumeReceiveMsg_mBC5A93ED67D7AB6379B700F690602F9C72003D40)  /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)
05-08 16:08:07.006  6877  6913 E CRASH   :       #01 pc 0000000000e8f704 (puerts::w_s_bi4o_t(void*, void (*)(), v8::FunctionCallbackInfo<v8::Value> const&, bool, puerts::WrapData*)) /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)
05-08 16:08:07.006  6877  6913 E CRASH   :       #02 pc 0000000000c32158(puerts::MethodCallback(pesapi_callback_info__*))  /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)
05-08 16:08:07.006  6877  6913 E CRASH   :       #03 pc 000000000157c9f0(v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo))  /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)
05-08 16:08:07.006  6877  6913 E CRASH   :       #04 pc 000000000157c0e0(v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments))  /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)
05-08 16:08:07.006  6877  6913 E CRASH   :       #05 pc 000000000157b898(v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*))  /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)
05-08 16:08:07.006  6877  6913 E CRASH   :       #06 pc 0000000001485648(Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit)  /data/app/com.developdream.rgd-5lIm8WGaogoWKtYmPliScQ==/lib/arm64/libil2cpp.so (BuildId: 728cad0afb7ff49ee32b5e57c745621906772349)

**Comment by mingxxming** [comment]
GameInstance_ConsumeReceiveMsg_mBC5A93ED67D7AB6379B700F690602F9C72003D40

**Comment by chexiongsheng** [comment]
看上去时Nullable处理的问题。

**Comment by zombieyang** [comment]
没有复现crash，但IL2CPP模式确实没有对nullable做针对处理，默认模式是有的。

**Comment by zombieyang** [comment]
> > 没有复现crash，但IL2CPP模式确实没有对nullable做针对处理，默认模式是有的。
> > TODO
> > 
> > * [ ]   IL2CPP模式加上nullable的处理，get/set都要
> 
> crash 有可能是wrap没生成，走反射了

你的栈里有wrapper的函数名w_s_bi4o_t
