### ISSUE TITLE
[Unity] Bug: IL2CPP raycasthit.point 返回的是raycasthit

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1321]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0-pre.0(master)

### Unity的版本 | Unity Version

2021.3.19f1

### 发生在哪个平台 | Platform

Android

### 问题重现 | Bug reproduce

c#:
```
public Action<GIputType, RaycastHit[]> InputCallback;
public RaycastHit[] CommonHits = new RaycastHit[] { new RaycastHit()};

public void test(){
        checkEvent(new Vector2(400, 400), 1);
}

private void checkEvent(Vector2 sp, GIputType tp) {
        var ray = Camera.main.ScreenPointToRay(sp);
        var hits = Physics.RaycastAll(ray, float.PositiveInfinity, LayerMask);
        if(hits.Length > 0)
            InputCallback?.Invoke(tp, hits);
}
```

ts:
```
export function GetNativeArrayItem<T>(ar, i:number):T {
    return ar.get_Item(i);
}
console.log("vcccccccccccccccc", <RaycastHit>GetNativeArrayItem(hits, 0), (<RaycastHit>GetNativeArrayItem(hits, 0)).point);
console.log("vxxxxxxxxxxx", (GetRaycastPoint(<RaycastHit>GetNativeArrayItem(hits, 0))));
```

非ilcpp:
vcccccccccccccccc	UnityEngine.RaycastHit	(-4.10, 0.00, 2.94)
vxxxxxxxxxxx	(-4.10, 0.00, 2.94)

il2cpp:
 vcccccccccccccccc       UnityEngine.RaycastHit  UnityEngine.RaycastHit
 vxxxxxxxxxxx    UnityEngine.RaycastHit

**Comment by mingxxming** [comment]
[FunctionBridge.Gen.txt](https://github.com/Tencent/puerts/files/11420480/FunctionBridge.Gen.txt)

**Comment by chexiongsheng** [comment]
raycasthit.point是raycasthit的第一个字段吧？这种情况下两个指针是相同的。
不过这种情况应该是考虑过的：https://github.com/Tencent/puerts/blob/master/unity/native_src_il2cpp/Src/CppObjectMapper.cpp#L109

通过ptr查找后会用类型信息(typeid)再找一次。可以看看是不是typeid有误。@zombieyang

**Comment by mingxxming** [comment]
而且hits还是raycasthit的数组

**Comment by mingxxming** [comment]
生成wrap时用GenerateCppWrappers代替GenerateCppWrappersInConfigure没问题了。

**Comment by mingxxming** [comment]
导致上面报错的是一个扩展方法：
    public static T limit<T>(this T v, T min, T max) where T : IComparable {
        if (v.CompareTo(min) == -1) {
            return min;
        }
        if (v.CompareTo(max) == 1) {
            return max;
        }
        return v;
    }

**Comment by chexiongsheng** [comment]
> 生成wrap时用GenerateCppWrappers代替GenerateCppWrappersInConfigure没问题了。 但是疯狂报错（程序却没有明显问题）： 05-09 11:41:30.251 10649 10675 E Unity : try load type throw System.InvalidOperationException: Operation is not valid due to the current state of the object. 05-09 11:41:30.251 10649 10675 E Unity : at PuertsIl2cpp.NativeAPI.Register (System.Type type, System.Reflection.MethodBase[] ctors, System.Reflection.MethodBase[] methods, System.Reflection.PropertyInfo[] properties, System.Reflection.FieldInfo[] fields, System.Boolean throwIfMemberFail) [0x00000] in <00000000000000000000000000000000>:0 05-09 11:41:30.251 10649 10675 E Unity : at PuertsIl2cpp.NativeAPI.RegisterNoThrow (System.IntPtr typeId, System.Boolean includeNonPublic) [0x00000] in <00000000000000000000000000000000>:0

应该这代表是反射的问题吧

**Comment by mingxxming** [comment]
> > 生成wrap时用GenerateCppWrappers代替GenerateCppWrappersInConfigure没问题了。 但是疯狂报错（程序却没有明显问题）： 05-09 11:41:30.251 10649 10675 E Unity : try load type throw System.InvalidOperationException: Operation is not valid due to the current state of the object. 05-09 11:41:30.251 10649 10675 E Unity : at PuertsIl2cpp.NativeAPI.Register (System.Type type, System.Reflection.MethodBase[] ctors, System.Reflection.MethodBase[] methods, System.Reflection.PropertyInfo[] properties, System.Reflection.FieldInfo[] fields, System.Boolean throwIfMemberFail) [0x00000] in <00000000000000000000000000000000>:0 05-09 11:41:30.251 10649 10675 E Unity : at PuertsIl2cpp.NativeAPI.RegisterNoThrow (System.IntPtr typeId, System.Boolean includeNonPublic) [0x00000] in <00000000000000000000000000000000>:0
> 
> 应该这代表是反射的问题吧

是的，还有一个是扩展方法 public static T limit(this T v, T min, T max) where T : IComparable  wrap出来也会出错，对应的 函数为ExtensionMethodInfo.GetExtendedType
 private static Type GetExtendedType(MethodInfo method)
        {
            var type = method.GetParameters()[0].ParameterType;
            if (!type.IsGenericParameter)
                return type;
            var parameterConstraints = type.GetGenericParameterConstraints();
            if (parameterConstraints.Length == 0) {
                throw new Exception("no parameter constraints ======= for " + type + ":" + method);// 我的案例中传入的是int32[]日志中的type为T而不是int32.有可能是这个函数在c#中未使用过？
            }
            
            var firstParameterConstraint = parameterConstraints[0];
            if (!firstParameterConstraint.IsClass) {
                throw new Exception("no firstParameterConstraint constraints ======= for " + type + ":" + method);
            }
            return firstParameterConstraint;
        }

**Comment by chexiongsheng** [comment]
> 主楼的问题在2020是好的，怀疑是csThis偏移导致

升级puerts可以解决？之前记得解决过类似的问题

**Comment by zombieyang** [comment]
在返回类型为object的C#函数里返回valuetype时没有拷贝。
