### ISSUE TITLE
[UE] 为什么我的项目中class world 无法导出 spawnActor 接口

### ISSUE THREAD

**Issue by RicuNi** [Tencent/puerts#1323]
## detail | 详细描述
在demo中 ， class World extends UE.Object 下可以查找到   SpawnActor(Class: $Nullable<UE.Class>, Transform: UE.Transform, SpawnCollisionHandlingOverride: UE.ESpawnActorCollisionHandlingMethod, Owner: $Nullable<UE.Actor>, Instigator: $Nullable<UE.Pawn>) : UE.Actor;
但是在我自己的项目中却没有这个接口，我使用的是最新普洱，引擎是4.27，请问下是哪里的setting要注意吗？

**Comment by chexiongsheng** [comment]
这是个纯c++方法，要自行添加，demo添加了。
自行添加推荐静态绑定，文档：https://puerts.github.io/docs/puerts/unreal/template_binding

也参考UObject几个方法的添加：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/Ext/UEExtension.cpp#L94

**Comment by chexiongsheng** [comment]
UE本身提供了蓝图方法，在UE.GameplayStatics那。
参考：https://github.com/chexiongsheng/BlockBreakerStarter/blob/master/TypeScript/TS_Player.ts#LL46C30-L46C30
