### ISSUE TITLE
[UE] Bug: 报告一个语法检测错误

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1324]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

全部

### UE的版本 | UE Version

全部

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

ts 环境下无法编译，无论怎样写都语法错误

### 问题重现 | Bug reproduce

以puerts_unreal_demo为模板

TsTestGameInstance.ts:
import {test} from './TsTestGameInstanceExt';

类添加函数
    ReceiveInit(): void {
        test(this, true);
    }

新创建一个文件：
TsTestGameInstanceExt.ts
import TsTestGameInstance from './TsTestGameInstance';

export function test(this:TsTestGameInstance, bad:boolean){
    console.log('hello')
};

**Comment by chexiongsheng** [comment]
你这个就是循环依赖了。
循环依赖ts不知道有没检测，即使ts没检测，js运行也可能有问题（在公版nodejs下）。

**Comment by terst6** [comment]
修改一下呢？没有循环了，语法错误依旧，调用提示ReceiveInit(this)中的this为非法参数，期待0参数

export function ReceiveInit(this:any): void {
    console.warn('TsTestGameInstance.ReceiveInit');
    if (this instanceof TsTestGameInstance) {
        this.StartNotify.Bind(() => this.OnStart());
    }
}

**Comment by terst6** [comment]
任何函数只要第一个参数名称是this，就会出这个错误，无法编译ts文件。这种添加this参数的做法是拆分大文件ts里用到的一个技巧。我目前没有用了，只是之前遇到过，这里提一下

**Comment by terst6** [comment]
> 这和ts版本有关把？

tsc 4.5.5 升级到 5.0.4后，问题一样，这种声明如果用 x.call() 没有问题，但如果在x里用 call（this）就会显示参数错误

**Comment by terst6** [comment]
避开循环引用后，把ReceiveInit(this)修改为 ReceiveInit() 可以正确编译
