### ISSUE TITLE
[UE] 可以静态绑定一个EditorOnly的方法吗?比如UObject的PostEditChangeProperty

### ISSUE THREAD

**Issue by Daktm** [Tencent/puerts#1325]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.1

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

错误提示：
E:\WorkSpace\Client\Plugins\Puerts\Source\JsEnv\Public\V8Converter.hpp(467): Error C2027 : 使用了未定义类型“puerts::converter::Converter<FPropertyChangedEvent *,void>

### 问题重现 | Bug reproduce

绑定代码：
UsingUStruct(FPropertyChangedEvent);
.Method("PostEditChangeProperty",MakeFunction(&UObject::PostEditChangeProperty))

**Comment by chexiongsheng** [comment]
绑定那可以加个只在Editor生效的宏

**Comment by Daktm** [comment]
@chexiongsheng 请问下怎么加一个只在Editor生效的宏

**Comment by Daktm** [comment]
@chexiongsheng 加了Editor的宏还是提示这个错误
![image](https://github.com/Tencent/puerts/assets/20082687/ddcbf177-7dfd-46c7-808a-eeae79208c87)

**Comment by chexiongsheng** [comment]
FPropertyChangedEvent好像不是UStruct

**Comment by Daktm** [comment]
@chexiongsheng 嗯，是的，是struct
![image](https://github.com/Tencent/puerts/assets/20082687/5c4a8dcb-45d4-4a20-8d18-f3993e64094a)

**Comment by chexiongsheng** [comment]
普通结构体按cpp的来，看cpp的例子
