### ISSUE TITLE
[UE] Bug: 多播代理在Remove Mixin之后的纯js函数回调失败

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1327]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

在C++定义个动态多播代理，js这边绑定 本地 js函数，无法动过 Remove 接口移除绑定关系

### 问题重现 | Bug reproduce

必现

**Comment by chexiongsheng** [comment]
标题有个Minxin，但内容好像和mixin没关系？

**Comment by ljporljp** [comment]
> 标题有个Minxin，但内容好像和mixin没关系？

可能。。。好像当时是多播代理无法remove掉指定的回调函数。

**Comment by chexiongsheng** [comment]
应该可以。
我盲猜你是因为闭包（或者bind）。你要remove得保存闭包引用。

**Comment by chexiongsheng** [comment]
先关闭，有问题再打开
