### ISSUE TITLE
[UE] Bug: 对于存在派生关系的2个代理蓝图，部分条件下Bind module顺序有误

### ISSUE THREAD

**Issue by mysticfarer** [Tencent/puerts#1336]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Latest

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

使用puerts继承模式，在UE Editor中第2次Play时，下面这种会生成代理蓝图的TS类，
在使用派生类对象(UBar)调用TestJSFunctionOverride函数时，会执行到其基类函数(UFoo)，而没有按预期执行派生类override后的函数：

```typescript
class UFoo extends UE.Object
{
    @no_blueprint()
    TestJSFunctionOverride(): void {}
}

class UBar extends UFoo
{
    @no_blueprint()
    TestJSFunctionOverride(): void {}
}
```

下面为第2次Play时的 puerts 日志：
```log
1. PuertsModule: Normal Mode started!
2. PuertsModule: Display: JsEnv created
3. Puerts: Display: (0x00000A14D5FE9130) Bind module [Game/UTestGameInstance] 
4. Puerts: Display: (0x00000A14D5FE9130) Bind module [Game/UTestGameInstance] 
5. Puerts: Display: (0x00000A14D5FE9130) Bind module [Game/UFoo] 
6. Puerts: (0x00000A14D5FE9130) UBar_C_0: UFoo.TestJSFunctionOverride
7. Puerts: Display: (0x00000A14D5FE9130) Bind module [Game/UBar] 
8. Puerts: (0x00000A14D5FE9130) UBar_C_0: UBar.TestUFunctionOverride
```
其中第6行期待应是 `UBar.TestJSFunctionOverride`

调试后发现与Bind module的顺序有关系，具体重现代码贴于“问题重现”段落中，
重现代码相对简单，可复制到任意UE工程中来重现，
感谢车总的辛苦支持:D

### 问题重现 | Bug reproduce

# 1. CPP
## TestSubsystem.h
```cpp
#pragma once

#include "CoreMinimal.h"
#include "Subsystems/EngineSubsystem.h"
#include "TestSubsystem.generated.h"

UCLASS()
class UTestObject : public UObject
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintImplementableEvent)
	void Test();
};

UCLASS()
class UTestSubsystem : public UEngineSubsystem
{
	GENERATED_BODY()

public:
	/** Implement this for initialization of instances of the system */
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;

	/** Implement this for deinitialization of instances of the system */
	virtual void Deinitialize() override;

	UFUNCTION(BlueprintCallable)
	void Test();

private:
	UPROPERTY()
	UTestObject* TestObject = nullptr;
};
```

## TestSubsystem.cpp
> 注：可能需要根据代理蓝图生成的位置，修改下这段代码中的Class资产路径：
```cpp
#include "TestSubsystem.h"

void UTestSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);

	if (!TestObject)
	{
		UClass* Class = LoadClass<UTestObject>(nullptr, TEXT("/Script/JsEnv.TypeScriptBlueprint'/Game/Blueprints/TypeScript/UBar.UBar_C'"));
		if (Class != nullptr)
		{
			TestObject = NewObject<UTestObject>(this, Class);
		}
	}
}

void UTestSubsystem::Deinitialize()
{
	Super::Deinitialize();
}

void UTestSubsystem::Test()
{
	if (TestObject)
	{
		TestObject->Test();
	}
}
```

# 2. TypeScript

## UFoo.ts
```typescript
import * as UE from 'ue';
import { no_blueprint } from 'ue';

class UFoo extends UE.TestObject
{
    Test(): void
    {
        this.TestJSFunctionOverride();
        this.TestUFunctionOverride();
    }

    @no_blueprint()
    TestJSFunctionOverride(): void
    {
        console.log(`${this.GetName()}: UFoo.TestJSFunctionOverride`);
    }

    TestUFunctionOverride(): void
    {
        console.log(`${this.GetName()}: UFoo.TestUFunctionOverride`);
    }
}

export default UFoo;
```

## UBar.ts
```typescript
import * as UE from 'ue';
import { no_blueprint } from 'ue';
import UFoo from './UFoo';

class UBar extends UFoo
{
    @no_blueprint()
    TestJSFunctionOverride(): void
    {
        console.log(`${this.GetName()}: UBar.TestJSFunctionOverride`);
    }

    TestUFunctionOverride(): void
    {
        console.log(`${this.GetName()}: UBar.TestUFunctionOverride`);
    }
}

export default UBar;
```

## UTestGameInstance.ts
此文件不重要，只是用来演示调用 `UE.TestSubsystem.Test();`，可在其它任意地方调用：
```typescript
import * as UE from 'ue';

class UTestGameInstance extends UE.GameInstance
{
    ReceiveInit(): void
    {
        let TestSubsystem = UE.SubsystemBlueprintLibrary.GetEngineSubsystem(UE.TestSubsystem.StaticClass()) as UE.TestSubsystem;
        if (TestSubsystem)
        {
            TestSubsystem.Test();
        }
    }
}

export default UTestGameInstance ;
```

**Comment by mysticfarer** [comment]
补充信息：
- puerts v1.0.3没有此问题；
- 最新版本存在此问题，但应该已经存在比较久了；

---

复现的条件比较复杂，关键点：
- 对象不是本次Play创建的，而是和Engine lifecycle一致的缓存下来的对象；
- 在C++中调用对象，而非在TS中调用对象；

在使用TS继承引擎的UAnimNotify时，其行为刚好满足上面条件，会触发此问题。

**Comment by chexiongsheng** [comment]
第2次Play的问题应该和之前的一个启动优化有关：之前一个内部项目第二次Play会很慢，因为第二次play加载在内存里头的代理蓝图类很多，这种类在虚拟机有个重新绑定的过程，所以慢。这个优化就是加快这一过程。

**Comment by chexiongsheng** [comment]
1.0.3后和这个问题相关的提交感觉就这两个：
https://github.com/Tencent/puerts/commit/c4ca0f8caac5afe73b9c1db6d5a67efd8c70fcac
https://github.com/Tencent/puerts/commit/b2bfcf078e36ae6b8d6c4293a3412aaf82ea35c6

如果你那比较容易重现可以试试是不是其中一个导致的

**Comment by chexiongsheng** [comment]
我感觉是这里改下：https://github.com/Tencent/puerts/commit/b2bfcf078e36ae6b8d6c4293a3412aaf82ea35c6#diff-262cf777d6bbcef1d697755e646acb10271585b8adf4f01ba003adea49ce0f0aL2077
~~~c++
auto Class = Cast<UTypeScriptGeneratedClass>(Function->GetOuterUClassUnchecked());
~~~
这里是获取Function的class。
试试改为获取Object的class
~~~c++
auto Class = Cast<UTypeScriptGeneratedClass>(ContextObject ?  ContextObject ->GetClass() : Function->GetOuterUClassUnchecked());
~~~

**Comment by mysticfarer** [comment]
```cpp
DEFINE_FUNCTION(UTypeScriptGeneratedClass::execLazyLoadCallJS)
{
    //auto Class = Cast<UTypeScriptGeneratedClass>(Function->GetOuterUClassUnchecked());
    auto Class = Cast<UTypeScriptGeneratedClass>(Context ?  Context->GetClass() : Function->GetOuterUClassUnchecked());
}
```
https://github.com/Tencent/puerts/blob/c5b9164d7b24930ae71e468f75eecb3a41cbbf3d/unreal/Puerts/Source/JsEnv/Private/TypeScriptGeneratedClass.cpp#LL44C70-L44C70

在修改`UTypeScriptGeneratedClass::execLazyLoadCallJS`后，我遇到的这种情况已经没有问题了；
如车总前面所提，`FJsEnvImpl::InvokeTsMethod` 中的 `Function->GetOuterUClassUnchecked` 也应该作同样修改吗，以及作这两处修改，逻辑上是否正确？ 
>  我理解是正确的，在被UE调用时，的确应该优先Bind UObject的类型，当UObject不存在时再Bind UFunction.Outer的类型（这种情况可能是static UFunction？）

关于 execLazyLoadCallJS 的调试细节：
> 执行到此处UFunction时，由于class UBar没有再override过Test，取到的Outer的确是class UFoo；
> 而此时的调用者，Context则是class UBar的对象；

---

另外还要更正下前面的信息，又详细测过了一下，在1.0.3版本也有此问题；
之前误以为没有，是因为我这儿的应用环境更复杂一些：

在下面这个提交中，原实现中有一个GetJsClass调用，里面会对 “代理蓝图的子类蓝图” 再做一次`MakeSureInject`，正是这个调用误打误撞Bind上了正确的JS class：
https://github.com/Tencent/puerts/commit/5d239cde2741f886c4e55fdec01b8f1f80ed5696#diff-262cf777d6bbcef1d697755e646acb10271585b8adf4f01ba003adea49ce0f0aL1629

**Comment by mysticfarer** [comment]
又看了下代码，
好像不用处理 `UTypeScriptGeneratedClass::execCallJS / execLazyLoadCallJS`，
直接在 `FJsEnvImpl::InvokeTsMethod` 中处理就可以了？

**Comment by mysticfarer** [comment]
只在execLazyLoadCallJS中优先用Context的Class后，还有种情况没处理到：
如果TS代理蓝图中只有uproperty，没有ufunction但有js function，
那么在第2次Play时也有bind不对的情况，overrided js function无法被正确调用；

**Comment by chexiongsheng** [comment]
想了下，都不能直接获取对象的Class，那个对象有可能是继承ts代理蓝图的普通蓝图。

现在js初始化都是放第一次push到js那，试试这样改下：

这里（https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L2123 ）修改为：
~~~c++
void FJsEnvImpl::TypeScriptInitial(UClass* Class, UObject* Object)
{
    TypeScriptInitial(Class->GetSuperClass(), Object);
    if (auto TypeScriptGeneratedClass = Cast<UTypeScriptGeneratedClass>(Class))
    {
        TsConstruct(TypeScriptGeneratedClass, Object);
    }
}
~~~

这里（https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L1681 ）修改为：
~~~c++
TypeScriptInitial(UEObject->GetClass(), UEObject);
~~~

**Comment by mysticfarer** [comment]
FindOrAdd时会被 `!SkipTypeScriptInitial` 条件拦住，不执行 `TypeScriptInitial`：

https://github.com/Tencent/puerts/blob/a7f2eea6b3aa24968af27a438d2b365ead8bb315/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L1679

**Comment by chexiongsheng** [comment]
> FindOrAdd时会被 `!SkipTypeScriptInitial` 条件拦住，不执行 `TypeScriptInitial`：
> 
> https://github.com/Tencent/puerts/blob/a7f2eea6b3aa24968af27a438d2b365ead8bb315/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L1679

这个SkipTypeScriptInitial为true的情况会导致开头描述那重现代码出问题吗？能重现我来处理吧

**Comment by mysticfarer** [comment]
我整理一个重现工程:D

**Comment by mysticfarer** [comment]
重现工程：
https://github.com/mysticfarer/puerts_unreal_demo

以 `testoverride` 为关键字筛选UE Editor Output Log，可见两次Play的结果不一致：
```log
Puerts: (0x00000461B057FBF0) --------TestOverride--------
Puerts: (0x00000461C57DAB70) UCat_C_0: UCat.TestOverride: JS-Function
Puerts: (0x00000461C57DAB70) UCat_C_0: UPet.TestOverride: UFunction
Puerts: (0x00000461C57DAB70) UDog_C_0: UDog.TestOverride: JS-Function
Puerts: (0x00000461C57DAB70) UDog_C_0: UPet.TestOverride: UFunction
Puerts: (0x00000461B9FD9F70) --------TestOverride--------
Puerts: (0x00000461B9FD3DF0) UCat_C_0: UAnimal.TestOverride: JS-Function
Puerts: (0x00000461B9FD3DF0) UCat_C_0: UPet.TestOverride: UFunction
Puerts: (0x00000461B9FD3DF0) UDog_C_0: UPet.TestOverride: JS-Function
Puerts: (0x00000461B9FD3DF0) UDog_C_0: UPet.TestOverride: UFunction
```

继承关系：
```cpp
class UTestObject : public UObject;
```
```typescript
class UAnimal extends UE.TestObject;
class UPet extends UAnimal;

class UCat extends UPet;
class UDog extends UPet;
```

**Comment by chexiongsheng** [comment]
我用你最开始的例子重现并修复了。
主要是最开始你说1.0.3后才出现，导致我都在后面的commit那找了。

**Comment by mysticfarer** [comment]
尴尬，误导车总了；
我这环境有些复杂，导致v1.0.3这个bug没有显现出来；
这就更新验证一下:D

**Comment by mysticfarer** [comment]
> 重现工程： https://github.com/mysticfarer/puerts_unreal_demo
> 
> 以 `testoverride` 为关键字筛选UE Editor Output Log，可见两次Play的结果不一致：
> 
> ```
> Puerts: (0x00000461B057FBF0) --------TestOverride--------
> Puerts: (0x00000461C57DAB70) UCat_C_0: UCat.TestOverride: JS-Function
> Puerts: (0x00000461C57DAB70) UCat_C_0: UPet.TestOverride: UFunction
> Puerts: (0x00000461C57DAB70) UDog_C_0: UDog.TestOverride: JS-Function
> Puerts: (0x00000461C57DAB70) UDog_C_0: UPet.TestOverride: UFunction
> Puerts: (0x00000461B9FD9F70) --------TestOverride--------
> Puerts: (0x00000461B9FD3DF0) UCat_C_0: UAnimal.TestOverride: JS-Function
> Puerts: (0x00000461B9FD3DF0) UCat_C_0: UPet.TestOverride: UFunction
> Puerts: (0x00000461B9FD3DF0) UDog_C_0: UPet.TestOverride: JS-Function
> Puerts: (0x00000461B9FD3DF0) UDog_C_0: UPet.TestOverride: UFunction
> ```
> 
> 继承关系：
> 
> ```c++
> class UTestObject : public UObject;
> ```
> 
> ```ts
> class UAnimal extends UE.TestObject;
> class UPet extends UAnimal;
> 
> class UCat extends UPet;
> class UDog extends UPet;
> ```

车总，这个例子还是需要看一下，这里还有些问题：
class UCat和class UDog中没有UFunction，只有JS-Function，这种时候它们的rebind还存在问题。
