### ISSUE TITLE
[UE] Bug: 最新主干代码在 Linux 编译 arm64 版本 android 包报错

### ISSUE THREAD

**Issue by AlanWalk** [Tencent/puerts#1339]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

主干最近代码

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

10:09:31  Building 26 actions with 26 processes...
10:09:31  [1/26] Compile m3_core.c [arm64]
10:09:31  clang++: error: no such file or directory: 'is'
10:09:31  clang++: error: no such file or directory: 'deprecated'
10:09:31  clang++: error: no such file or directory: 'and'
10:09:31  clang++: error: no such file or directory: 'should'
10:09:31  clang++: error: no such file or directory: 'always'
10:09:31  clang++: error: no such file or directory: 'be'
10:09:31  clang++: error: no such file or directory: 'considered'
10:09:31  clang++: error: no such file or directory: '1./) 1'

### 问题重现 | Bug reproduce

在 Windows 上编译 Android 包是正常的，在 Linux 上编译的时候就出错了，clang 报错的那段 is deprecated 看起来应该是 UE_DEPRECATED_MACRO 没正常解析导致的， @chexiongsheng 关于这块报错的原因车大有什么思路么。
![image](https://github.com/Tencent/puerts/assets/4654826/993a4175-191c-4bcf-9a08-e4c2f0f90014)

**Comment by chexiongsheng** [comment]
linux版本应该没问题吧？
是不是ndk的clang/gcc版本导致的呢？
还有有没可能是代码文件编码导致的呢？

**Comment by chexiongsheng** [comment]
ue在linux下编译android，用的是哪个编译命令呢？自己用这个命令加参数宏展开看看（比如gcc是-E）？

**Comment by AlanWalk** [comment]
看起来编editor用的gcc，编android用的clang

**Comment by AlanWalk** [comment]
Linux 下编 Android 用的 clang
```
NDK toolchain: r25b, NDK version: 250200, ClangVersion: 14.0.6
Compiling Native 64-bit code with NDK API 'android-26'
```
看了下 5.1 官方编 Linux 推荐的 clang 版本是 13.0.1
```
Linux
Native Linux Development
Recommended OS: Ubuntu 22.04 or CentOS 7
Compiler: clang 13.0.1
```

**Comment by AlanWalk** [comment]
在 Windows 上用 NDK r25b 编 Android 就能正常编过，clang 版本也是 14.0.6

**Comment by chexiongsheng** [comment]
那分别用window的ndk的clang和linux的宏展开那个文件对比下？
好像是：clang -E
