### ISSUE TITLE
[Unity] Bug: il2cpp绑定方式下，用传byte[]数组的方式构造Puerts.ArrayBuffer。第二次构造的arrayBuffer，内存会覆盖第一次构造的

### ISSUE THREAD

**Issue by Hibeginner** [Tencent/puerts#1340]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

master分支 4.20号commit id:eaf637a

### Unity的版本 | Unity Version

2021.318f1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

excelBufferUint8Array:,10,153,138,1
    at Function.LoadExcelConfigAsync (bin/js/bundle:509233:17)
    at Function.loadAsync (bin/js/bundle:509220:14)
    at Function.Init (bin/js/bundle:509336:22)
    at UnityBridge.OnBegin (bin/js/bundle:509882:16)
    at UnityBridge.JsManager.GetInstance.OnBegin (bin/js/bundle:509831:65)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
JSEnvMgr:Init() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\Managers\JSEnvMgr.cs:79)
JSEnvMgr:GetInstance() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\Managers\JSEnvMgr.cs:23)
<>c:<Start>b__3_0() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\UI\TestView.cs:19)
UnityEngine.Events.InvokableCall:Invoke() (at C:\build\output\unity\unity\Runtime\Export\UnityEvent\UnityEvent.cs:178)
UnityEngine.Events.UnityEvent:Invoke() (at C:\build\output\unity\unity\Runtime\Export\UnityEvent\UnityEvent\UnityEvent_0.cs:58)
UnityEngine.UI.Button:Press() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\UI\Core\Button.cs:70)
UnityEngine.UI.Button:OnPointerClick(PointerEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\UI\Core\Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\ExecuteEvents.cs:272)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:190)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:640)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:546)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:526)
UnityEngine.EventSystems.StandaloneInputModule:Process() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:280)
UnityEngine.EventSystems.EventSystem:Update() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\EventSystem.cs:501)

offsetBufferUint8Array:,8,1,18,171
    at Function.LoadExcelConfigAsync (bin/js/bundle:509238:17)
    at Function.loadAsync (bin/js/bundle:509220:14)
    at Function.Init (bin/js/bundle:509336:22)
    at UnityBridge.OnBegin (bin/js/bundle:509882:16)
    at UnityBridge.JsManager.GetInstance.OnBegin (bin/js/bundle:509831:65)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
JSEnvMgr:Init() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\Managers\JSEnvMgr.cs:79)
JSEnvMgr:GetInstance() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\Managers\JSEnvMgr.cs:23)
<>c:<Start>b__3_0() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\UI\TestView.cs:19)
UnityEngine.Events.InvokableCall:Invoke() (at C:\build\output\unity\unity\Runtime\Export\UnityEvent\UnityEvent.cs:178)
UnityEngine.Events.UnityEvent:Invoke() (at C:\build\output\unity\unity\Runtime\Export\UnityEvent\UnityEvent\UnityEvent_0.cs:58)
UnityEngine.UI.Button:Press() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\UI\Core\Button.cs:70)
UnityEngine.UI.Button:OnPointerClick(PointerEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\UI\Core\Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\ExecuteEvents.cs:272)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:190)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:640)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:546)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:526)
UnityEngine.EventSystems.StandaloneInputModule:Process() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:280)
UnityEngine.EventSystems.EventSystem:Update() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\EventSystem.cs:501)

excelBufferUint8Array2:,8,1,18,171
    at Function.LoadExcelConfigAsync (bin/js/bundle:509239:17)
    at Function.loadAsync (bin/js/bundle:509220:14)
    at Function.Init (bin/js/bundle:509336:22)
    at UnityBridge.OnBegin (bin/js/bundle:509882:16)
    at UnityBridge.JsManager.GetInstance.OnBegin (bin/js/bundle:509831:65)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
JSEnvMgr:Init() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\Managers\JSEnvMgr.cs:79)
JSEnvMgr:GetInstance() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\Managers\JSEnvMgr.cs:23)
<>c:<Start>b__3_0() (at D:\GitWorkspace\jjsg_unity_demo\Assets\Scripts\UI\TestView.cs:19)
UnityEngine.Events.InvokableCall:Invoke() (at C:\build\output\unity\unity\Runtime\Export\UnityEvent\UnityEvent.cs:178)
UnityEngine.Events.UnityEvent:Invoke() (at C:\build\output\unity\unity\Runtime\Export\UnityEvent\UnityEvent\UnityEvent_0.cs:58)
UnityEngine.UI.Button:Press() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\UI\Core\Button.cs:70)
UnityEngine.UI.Button:OnPointerClick(PointerEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\UI\Core\Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\ExecuteEvents.cs:272)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:190)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:640)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32) (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:546)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:526)
UnityEngine.EventSystems.StandaloneInputModule:Process() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\InputModules\StandaloneInputModule.cs:280)
UnityEngine.EventSystems.EventSystem:Update() (at D:\GitWorkspace\jjsg_unity_demo\Library\PackageCache\com.unity.ugui@1.0.0\Runtime\EventSystem\EventSystem.cs:501)

### 问题重现 | Bug reproduce

生成il2cpp绑定，unity构建Windows版本，backend script:il2cpp

![image](https://github.com/Tencent/puerts/assets/11421227/1225770c-aea2-4f97-ad49-75d96e308979)
JS脚本，用Resources.Load加载一个二进制文件。

![image](https://github.com/Tencent/puerts/assets/11421227/36ceaa88-5f9e-45fa-8cd4-01a331c678c0)
然后调用C#函数JsCshareUtil.TextAssetToArrayBuffer，转成Puerts.ArrayBuffer，返回给JS

![image](https://github.com/Tencent/puerts/assets/11421227/83973b00-5446-46c4-824a-f1e898bc55e6)
加载第一个二进制文件excelconfig.bin，构造一个Uint8Array excelBufferUint8Array，输出前4个字节为10 153 138 1，没有问题
加载第二个二进制文件exceloffset.bin后，构造一个Uint8Array offsetBufferUint8Array，输出前4个字节为8 1 18 171，没有问题

但是再次输出之前构造的excelBufferUint8Array，它的前4个字节变成了第二次加载的二进制文件！

**Comment by Hibeginner** [comment]
demo测试，没有问题。
估计是项目里js代码逻辑有问题

**Comment by zombieyang** [comment]
默认模式和IL2cpp表现不一致就肯定有问题，估计是内存被写掉了。持续关注下如何复现
