### ISSUE TITLE
[Unity] Bug: PuerTS/Generate for il2cpp binding(All in One) 报错

### ISSUE THREAD

**Issue by Halliwood** [Tencent/puerts#1342]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

commit 932e368a95f12200b1bf678208c9c9677825a37c (HEAD -> master, origin/master, origin/HEAD)

### Unity的版本 | Unity Version

2021.2.18f1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

BadImageFormatException: Method has zero rva
System.Reflection.RuntimeMethodInfo.GetMethodBody (System.IntPtr handle) (at <6073cf49ed704e958b8a66d540dea948>:0)
System.Reflection.RuntimeMethodInfo.GetMethodBody () (at <6073cf49ed704e958b8a66d540dea948>:0)
PuertsIl2cpp.Editor.Generator.FileExporter+<>c.<GenCPPWrap>b__6_39 (System.Reflection.MethodBase mb) (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:164)
PuertsIl2cpp.Editor.Generator.FileExporter.GenericArgumentInInstructions (System.Reflection.MethodBase node, System.Collections.Generic.HashSet`1[T] result, System.Collections.Generic.HashSet`1[T] proceed, System.Collections.Generic.HashSet`1[T] skipAssembles, System.Func`2[T,TResult] callingMethodsGetter) (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:90)
PuertsIl2cpp.Editor.Generator.FileExporter.GenericArgumentInInstructions (System.Reflection.MethodBase node, System.Collections.Generic.HashSet`1[T] result, System.Collections.Generic.HashSet`1[T] proceed, System.Collections.Generic.HashSet`1[T] skipAssembles, System.Func`2[T,TResult] callingMethodsGetter) (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:93)
PuertsIl2cpp.Editor.Generator.FileExporter.GenCPPWrap (System.String saveTo, System.Boolean onlyConfigure) (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:162)
PuertsIl2cpp.Editor.Generator.UnityMenu.GenerateCppWrappers () (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs:46)
PuertsIl2cpp.Editor.Generator.UnityMenu.GenV2 () (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs:26)

### 问题重现 | Bug reproduce

按照[文档](https://puerts.github.io/docs/puerts/unity/performance/il2cpp)的步骤，在执行第4步
> 生成编译所需的代码：点击Unity的PuerTS/Generate for il2cpp binding(All in One)。
时报以上报错。修改`unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs` line 164:
```C#
try
{
    if (mb.GetMethodBody() == null || mb.IsGenericMethodDefinition || mb.IsAbstract) return new MethodBase[] { };
    return mb.GetInstructions()
        .Select(i => i.Operand)
        .Where(o => o is MethodBase)
        .Cast<MethodBase>();
}
```
把GetMethodBody移到try后可以生成`FunctionBridge.Gen.h`，不过有个新的报错：
```
Exception: puerts/templates/extension_methods_gen.tpl.mjs:45: TypeError: pair.Key.GetFriendlyName is not a function

TypeError: pair.Key.GetFriendlyName is not a function
    at getExtendedTypeToExtensionTypeInfo (puerts/templates/extension_methods_gen.tpl.mjs:45:37)
    at TypingTemplate (puerts/templates/extension_methods_gen.tpl.mjs:16:28)
Puerts.GenericDelegate.Func[T1,TResult] (T1 p1) (at F:/tgit/libs/puerts/unity/Assets/core/upm/Runtime/Src/Default/JSType/GenericDelegate.cs:521)
PuertsIl2cpp.Editor.Generator.FileExporter.GenExtensionMethodInfos (System.String outDir) (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:356)
PuertsIl2cpp.Editor.Generator.UnityMenu.GenerateExtensionMethodInfos () (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs:75)
PuertsIl2cpp.Editor.Generator.UnityMenu.GenV2 () (at F:/tgit/libs/puerts/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs:27)
```

**Comment by zombieyang** [comment]
是哪个method触发的？

**Comment by Halliwood** [comment]
> 是哪个method触发的？

Int32 GetCornersNonAlloc(UnityEngine.Vector3[])
![image](https://github.com/Tencent/puerts/assets/860632/e409dc70-be3d-4b32-ad7a-2c18e9f77ffc)

**Comment by Halliwood** [comment]
TypeError: pair.Key.GetFriendlyName is not a function

**Comment by zombieyang** [comment]
这个函数是你自己的？GetMethodBody这个函数报错的话，可能是那个函数体导致的。
是否方便提供函数体内容？或者帮忙确认下什么情况GetMethodBody会报这个错。

兜底方案是下个版本会提供的Instruction过滤能力 #1307

**Comment by Halliwood** [comment]
> 这个函数是你自己的？GetMethodBody这个函数报错的话，可能是那个函数体导致的。 是否方便提供函数体内容？或者帮忙确认下什么情况GetMethodBody会报这个错。
> 
> 兜底方案是下个版本会提供的Instruction过滤能力 #1307

这个函数是unity自带的，`UnityEngine.AI.NavMeshPath`的成员函数
```C#
//
// 摘要:
//     Calculate the corners for the path.
//
// 参数:
//   results:
//     Array to store path corners.
//
// 返回结果:
//     The number of corners along the path - including start and end points.
[FreeFunctionAttribute("NavMeshPathScriptBindings::GetCornersNonAlloc", HasExplicitThis = true)]
public int GetCornersNonAlloc(Vector3[] results);
```

**Comment by Halliwood** [comment]
> 这个函数是你自己的？GetMethodBody这个函数报错的话，可能是那个函数体导致的。 是否方便提供函数体内容？或者帮忙确认下什么情况GetMethodBody会报这个错。
> 
> 兜底方案是下个版本会提供的Instruction过滤能力 #1307

另外，很多外部函数也都会报错，比如WeChatWASM就有一堆：
```C#
#if UNITY_WEBGL
        [DllImport("__Internal")]
#endif

        private static extern void WXCallFunction(string name, string data, string conf, string s, string f, string c);
#if UNITY_WEBGL
        [DllImport("__Internal")]
#endif
        private static extern void WXCallFunctionInit(string conf);
#if UNITY_WEBGL
        [DllImport("__Internal")]
#endif
        private static extern string WXCloudID(string cloudID);
```
