### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by juntaosun** [Tencent/puerts#1350]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

打包后，加载不到，如下描述

### 问题重现 | Bug reproduce

以下代码在UE编辑器中运行，蓝图控件可以正常加载和显示。
但是，打包成WinPC包，运行就加载不到了ViewClass==undefined，这是啥情况啊？   

import * as UE from 'ue'
let ViewClass = UE.Class.Load("WidgetBlueprint'/Game/Blueprints/UI/TestUI.TestUI_C'");

        setInterval(()=>{
            if (ViewClass == undefined) {
                console.log("UI没有找到？？？？？");
            }else{
                console.log("UI找到了");
            }
        },1000);

换了另一种加载方式，打包后也加载不到资源。但是编辑器里去行正常的
blueprint.load(UE.Game.Blueprints.UI.TestUI.TestUI_C);

另外那个群号UE4专属群：689643903 进群验证：小写组件名是啥啊，
怎么输入都不对，是不让加群交流吗？大佬

**Comment by chexiongsheng** [comment]
加载不成功就没有那资源，或者路径不对。
这个只是把路径透传给StaticLoadObject，js那返回undefined代表StaticLoadObject返回nullptr。

**Comment by juntaosun** [comment]
![1](https://github.com/Tencent/puerts/assets/22288197/1c948020-5685-4672-9523-5db31b3554ff)
编辑中正常，打包后可以看到路径变None。
UE.Class.Load("WidgetBlueprint'/Game/Blueprints/UI/TestUI.TestUI_C'");  //打包后路径变None
如果是依赖路径进行加载的，那么大家是怎么做的啊？

**Comment by juntaosun** [comment]
解决了
