### ISSUE TITLE
[Unity] Bug: dts.tpl.mjs 执行速度惨不忍睹

### ISSUE THREAD

**Issue by PleijaNet** [Tencent/puerts#1351]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.*

### Unity的版本 | Unity Version

any

### 发生在哪个平台 | Platform

All

### 错误信息 | Error Message

...

### 问题重现 | Bug reproduce

finished! use 618.4 s
index.d.ts 行数: 108334
i7 20线程, 生成一个10万行的文本文件需要10分钟, 这个 dts.tpl.mjs  真的是..shit?

**Comment by zombieyang** [comment]
倒是一直没有做过这个事情的性能指标。



建议的话，你可以尝试考虑不同的namespace生成不同的dts

比如写一个editor脚本，生成一个->将dts重命名->生成下一个->重复

因为dts用的是declare namespace，所以只要摆在项目里应该都会产生作用。

**Comment by chexiongsheng** [comment]
如果是quickjs才有的话，应该是字符串拼接导致的。如果没特别优化，所有带gc的语言在这场景下都会极其慢。当年xlua的代码生成我最开始用字符串拼接方式，也是极其慢，修改成先插入到数组，然后一次table.concat性能就提高了一个数量级以上。

v8是对字符串拼接做了优化的：构建一个ConsString对象引用原先两个字符串对象。这种办法不会产生大量的gc

**Comment by zombieyang** [comment]
quickjs也没有JIT吧

**Comment by chexiongsheng** [comment]
> quickjs也没有JIT吧

JIT不会导致这种差距。

**Comment by chexiongsheng** [comment]
> > quickjs也没有JIT吧
> 
> JIT不会导致这种差距。

脚本速度不是关键，即使是v8开jitless，这个场景下90%以上是反射的开销，剩下的脚本执行不到10%。开jit优化把那不到10%全优化了也提升不了多少。

而字符串拼接导致的性能问题，按之前xlua的测试是这个场景下所有反射调用的十倍以上。
