### ISSUE TITLE
[Unity] Bug: 更新到最新后，点 generate for il2cpp binding 报错

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1354]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0

### Unity的版本 | Unity Version

2021.3.16f

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

ArgumentException: Type provided must be an Enum.
Parameter name: enumType
System.RuntimeType.GetEnumUnderlyingType () (at <4ba27aa039714eafa1e8892e51af2932>:0)
System.Enum.GetUnderlyingType (System.Type enumType) (at <4ba27aa039714eafa1e8892e51af2932>:0)
PuertsIl2cpp.TypeUtils.GetTypeSignature (System.Type type) (at /Users/elendil/WorkSpaces/ascension/Puerts/puercore/unity/Assets/core/upm/Runtime/Src/IL2Cpp/TypeUtils.cs:228)
PuertsIl2cpp.Editor.Generator.FileExporter.IterateAllValueType (System.Type type, System.Collections.Generic.List`1[T] list) (at /Users/elendil/WorkSpaces/ascension/Puerts/puercore/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:115)
PuertsIl2cpp.Editor.Generator.FileExporter.GenCPPWrap (System.String saveTo, System.Boolean onlyConfigure) (at /Users/elendil/WorkSpaces/ascension/Puerts/puercore/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs:222)
PuertsIl2cpp.Editor.Generator.UnityMenu.GenerateCppWrappers () (at /Users/elendil/WorkSpaces/ascension/Puerts/puercore/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs:46)
PuertsIl2cpp.Editor.Generator.UnityMenu.GenV2 () (at /Users/elendil/WorkSpaces/ascension/Puerts/puercore/unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs:26)

### 问题重现 | Bug reproduce

直接点PuerTS/Generate for il2cpp binding

**Comment by zombieyang** [comment]
所处的commit hash发一下？昨晚最后的push应该修了的

**Comment by dunadain** [comment]
更新后可以了
