### ISSUE TITLE
[UE] 请教一个tsconfig.json配置参数问题

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1356]
## detail | 详细描述
以demo为例，在
tsconfig.json里添加以下参数
"noEmit": true,
后，UE编辑器环境工作正常，但是脱离编辑器后 tsc 编译不工作，没有任何提示，有人有相关建议没有？

**Comment by chexiongsheng** [comment]
noEmit按字面不是不输出的意思么？
UE能输出js是我没处理这个选项的原因

**Comment by terst6** [comment]
这样喔，感谢。
我用tsc 编译ts时，会在类里罗列出全部定义的变量，比如这样
class TsTestGameInstance extends UE.TypeScriptGameInstance {
    root;
    ReceiveInit() {
而ue编译出来就没有这个root，我以为那个参数不输出仅仅是指这里呢。这里不输出变量名称应该用什么参数呢？还是只能自己处理

**Comment by chexiongsheng** [comment]
这和ts版本有关，怎么升级ts版本看faq
