### ISSUE TITLE
[Unity] Bug: 

### ISSUE THREAD

**Issue by TencentMix** [Tencent/puerts#1357]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4.0

### Unity的版本 | Unity Version

2021.3.18

### 发生在哪个平台 | Platform

Other

### 错误信息 | Error Message

timer.js文件中对全局timer进行复写，会导致cocos引擎等引发异常，引擎依赖标准的timer行为

### 问题重现 | Bug reproduce

只要运行过puer webgl版本，timer完成改写就会引发异常

**Comment by zombieyang** [comment]
上面这个commit关联错了。该commit修正的是webgl下foreach很慢的问题：
![企业微信截图_f67af88a-0600-45e3-963f-548989326da9](https://github.com/Tencent/puerts/assets/5595819/ab8cd517-2b53-4ed9-a29e-7bf7e0f0db17)

![企业微信截图_fc0d86ec-9d99-4f12-ba41-c686e66bb61d](https://github.com/Tencent/puerts/assets/5595819/c9a5b39a-377d-44ae-80ee-cde61c37eb9f)

<img width="54" alt="企业微信截图_83252538-74ca-42ad-a38f-4cc5c95915d3" src="https://github.com/Tencent/puerts/assets/5595819/c3838f0b-4d07-4d7c-b04b-289ab94947f4">

**Comment by chexiongsheng** [comment]
关联错误，但这issue提的问题还没解决吧？怎么就关闭了呢？

**Comment by zombieyang** [comment]
> 这个性能测试有一点公平，前面的foreach慢的情况也可能是RubbishCan添加的时候，分配了内存，后面的foreach没有这一步操作，公平一点的话，应该就都提前分配好内存，再去测试

`(int)Math.Round((double)UnityEngine.Random.Range(0, 1))` 这个表达式不会得到1的，RubbishCan只是担心编译器把循环给优化了
