### ISSUE TITLE
能否加上Linux支持，方便于实现服务器客户端共享代码

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#136]

**Comment by chexiongsheng** [comment]
暂时没时间提供，可否自己搞下呢？
v8做了自动编译，把macos的改改就行：https://github.com/Tencent/puerts/blob/master/v8-build/macos.sh
编译了v8编plugins也简单。

**Comment by mingxxming** [comment]
> 暂时没时间提供，可否自己搞下呢？
> v8做了自动编译，把macos的改改就行：https://github.com/Tencent/puerts/blob/master/v8-build/macos.sh
> 编译了v8编plugins也简单。

ok
