### ISSUE TITLE
[Unity] (2021lts 多个版本都出现)il2cpp遇到一个非常诡异的问题，可能是unity的bug 

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1369]
C:\Projects\rgd\game\u3d\release\2023_6_2\GC_OHAYOO_MOCK_16_08.apk\unityLibrary\src\main\Il2CppOutputProject\IL2CPP\build\deploy\il2cpp.exe 
--compile-cpp 
--platform=Android 
--architecture=arm64 
--outputpath=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniLibs/arm64-v8a/libil2cpp.so 
--libil2cpp-static 
--baselib-directory=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a 
--incremental-g-c-time-slice=3 
--configuration=Release 
--dotnetprofile=unityaot-linux 
--profiler-report 
--profiler-output-file=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/build/il2cpp_arm64-v8a_Release/il2cpp_conv.traceevents 
--print-command-line 
--generatedcppdir=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/Il2CppOutputProject/Source/il2cppOutput 
--cachedirectory=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/build/il2cpp_arm64-v8a_Release/il2cpp_cache 
--tool-chain-path=C:\Users\monster\AppData\Local\Android\Sdk\ndk\21.3.6528147 
**--additional-libraries=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a/libpuerts_il2cpp.a 
--additional-libraries=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a/libwee8.a**
以上是il2cpp成功出android包的情况

C:\Projects\rgd\game\u3d\release\2023_6_2\GC_OHAYOO_MOCK_16_08.apk\unityLibrary\src\main\Il2CppOutputProject\IL2CPP\build\deploy\il2cpp.exe 
--compile-cpp 
--platform=Android 
--architecture=arm64 
--outputpath=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniLibs/arm64-v8a/libil2cpp.so 
--libil2cpp-static 
--baselib-directory=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a 
--incremental-g-c-time-slice=3 
--configuration=Release 
--dotnetprofile=unityaot-linux 
--profiler-report 
--profiler-output-file=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/build/il2cpp_arm64-v8a_Release/il2cpp_conv.traceevents 
--print-command-line 
--generatedcppdir=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/Il2CppOutputProject/Source/il2cppOutput 
--cachedirectory=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/build/il2cpp_arm64-v8a_Release/il2cpp_cache 
--tool-chain-path=C:\Users\monster\AppData\Local\Android\Sdk\ndk\21.3.6528147 
**--additional-libraries=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a/libwee8.a 
--additional-libraries=C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_16_08.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a/libpuerts_il2cpp.a**
以上是il2cpp出android包，在link阶段出现v8 的所有引用不存在的情况，如：
C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_17_51.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a/libpuerts_il2cpp.a(Puerts.cpp.o): In function `puerts::w_i4ti4o(void*, void (*)(), v8::FunctionCallbackInfo<v8::Value> const&, bool, puerts::WrapData*)':
/home/runner/work/puerts/puerts/unity/native_src_il2cpp/Src/FunctionBridge.Gen.h:7840: undefined reference to `v8::Value::IsObject() const'
/home/runner/work/puerts/puerts/unity/native_src_il2cpp/Src/FunctionBridge.Gen.h:7840: undefined reference to `v8::Value::IsObject() const'
/home/runner/work/puerts/puerts/unity/native_src_il2cpp/Src/FunctionBridge.Gen.h:7840: undefined reference to `v8::Value::IsFunction() const'
/home/runner/work/puerts/puerts/unity/native_src_il2cpp/Src/FunctionBridge.Gen.h:7840: undefined reference to `v8::Value::IsFunction() const'
C:/Projects/rgd/game/u3d/release/2023_6_2/GC_OHAYOO_MOCK_17_51.apk/unityLibrary/src/main/jniStaticLibs/arm64-v8a/libpuerts_il2cpp.a(Puerts.cpp.o

在AS中手动 调整俩库位置后编译成功。

**Comment by zombieyang** [comment]
调整两个库的位置 是指哪两个？

**Comment by mingxxming** [comment]
--additional-libraries=libpuerts_il2cpp.a --additional-libraries=libwee8.a ok
--additional-libraries=libwee8.a --additional-libraries=libpuerts_il2cpp.a fail

**Comment by chexiongsheng** [comment]
可以试试合并这两个库看能否解决问题。

**Comment by chexiongsheng** [comment]
用ndk的ar命令，如果能解决问题，后续修改CMakeList自动做这个合并操作。

**Comment by mingxxming** [comment]
测了几个合并方式都不成功
ar -x libpuerts_il2cpp.a
ar -rs libwee8.a *.o
mv libwee8.a  xxx/libpuerts_il2cpp.a【ar -t 显示没有确实.o 编译通过 ，但是所有wrap都不生效 走的发射】

ar -x libwee8.a
ar -rs libpuerts_il2cpp.a *.o
mv libpuerts_il2cpp.a  xxx/libpuerts_il2cpp.a【ar -t 显示没有确实.o v8 引用找不到】


ar -x libwee8.a
ar -x libpuerts_il2cpp.a
ar -crs libpuerts_il2cpp1.a *.o
mv libpuerts_il2cpp1.a  xxx/libpuerts_il2cpp.a【Archive has no index; run ranlib to add one】

**Comment by zombieyang** [comment]
要用NDK里的ar

而且v8里面 .o 之间也有互相依赖，添加 .o 的顺序也有讲究，要ar -t libwee8.a按照里面的顺序来一个一个添加

**Comment by mingxxming** [comment]
> 

不需要用ndk的 ar 不涉及编译，上面的测试是ok的。之前闪退是因为https://github.com/Tencent/puerts/issues/1376

**Comment by chexiongsheng** [comment]
> 要用NDK里的ar
> 
> 而且将libwee8 x出来重新打.a之后，无论如何它内部的依赖都会丢。唯一能通的情况似乎是 `ar x libpuerts_il2cpp.a`，然后 `ar q libwee8.a *.o`。即把puerts拆开来append到wee8里去，然后把libwee8.a丢进Unity。
> 
> 有空再查查原因

我说的就是你能通的做法，这做法本质就是两个.a合并成一个。并不是把libwee8拆开然后重现打包。

**Comment by zombieyang** [comment]
> > 要用NDK里的ar
> > 而且将libwee8 x出来重新打.a之后，无论如何它内部的依赖都会丢。唯一能通的情况似乎是 `ar x libpuerts_il2cpp.a`，然后 `ar q libwee8.a *.o`。即把puerts拆开来append到wee8里去，然后把libwee8.a丢进Unity。
> > 有空再查查原因
> 
> 我说的就是你能通的做法，这做法本质就是两个.a合并成一个。并不是把libwee8拆开然后重新打包。

我回复的是 @mingxxming 之前的评论，他的评论早上编辑过
