### ISSUE TITLE
[unreal] Blob不是V8的吧？编译linux过不了，是需要单独适配吗？

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#137]

**Comment by chexiongsheng** [comment]
你要针对linux生成blob文件。

**Comment by chexiongsheng** [comment]
有个通用的把blob文件转头 文件的工具，看下v8编译脚本。

**Comment by mingxxming** [comment]
> 有个通用的把blob文件转头 文件的工具，看下v8编译脚本。

没问题了。感谢~

**Comment by mingxxming** [comment]
> > > 有个通用的把blob文件转头 文件的工具，看下v8编译脚本。
> > 
> > 
> > 没问题了。感谢~
> 
> 怎么解决的

主干已经有linux编译了，不用处理了

**Comment by gocpplua** [comment]
> > > > 有个通用的把blob文件转头 文件的工具，看下v8编译脚本。
> > > 
> > > 
> > > 没问题了。感谢~
> > 
> > 
> > 怎么解决的
> 
> 主干已经有linux编译了，不用处理了

linux.sh　吗

**Comment by chexiongsheng** [comment]
直接下载：https://github.com/Tencent/puerts/releases/tag/V8_8.4.371.19_2020_05_06
