### ISSUE TITLE
[Unity] Bug: IL2cpp crash console.log(new Vector(1,1,1));

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1376]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0-pre.4(master)

### Unity的版本 | Unity Version

2021.3.19f1

### 发生在哪个平台 | Platform

Android

### 问题重现 | Bug reproduce

console.log(new Vector(1,1,1));

**Comment by zombieyang** [comment]
todo：this为valuetype但函数this类型为object时，需要一次boxing
