### ISSUE TITLE
[Unity]Why il2cpp is slower than dll When using Array? 为什么使用数组时il2cpp比dll慢？

### ISSUE THREAD

**Issue by danij91** [Tencent/puerts#1380]
Hello! First of all, I want to express my gratitude for everything you've done. Recently, I conducted a test on using CSharp native arrays from JavaScript, and the results were a bit peculiar. Allow me to explain the test I conducted:
你好！首先，非常感谢你所做的一切。最近，我进行了一项关于从JavaScript使用CSharp本机数组的测试，结果有些奇怪。让我解释一下我进行的测试：

1. I created 1000 native arrays, each consisting of 1000 elements with a data type of Double.
    我创建了1000个本机数组，每个数组包含1000个元素，元素的数据类型为Double。
2. I assigned values to each element of the arrays.
   我为每个数组的每个元素分配了值。

Initially, I assumed that il2cpp would outperform the DLL, but the results were quite the opposite. il2cpp took approximately 4000 milliseconds, whereas the DLL only took about 400 milliseconds. Could you please explain why this occurred? As a side note, when I performed the same task using native CSharp, it only took 40 milliseconds.
最初，我以为il2cpp会比DLL更快，但结果恰恰相反。il2cpp花费了大约4000毫秒，而DLL只需约400毫秒。请问你能解释一下为什么会发生这种情况吗？另外，值得一提的是，当我使用本机CSharp进行相同的操作时，只需要40毫秒。

I have attached the corresponding code below for your reference.
以下是相关代码的附加内容，供你参考。
`    public void RunJS()
    {
        int count = 1000;
        int length = 1000;

        var sw = new Stopwatch();
        var env = new JsEnv();
        env.Eval(@$"const count ={count}");
        env.Eval(@$"const length ={length}");
        
        env.Eval(@"const arrArr = [];
                           for(var i = 0;i<count;i++){
                             arrArr.push(CS.System.Array.CreateInstance(CS.System.Type.GetType('System.Double'), length));
                           }");
        sw.Start();
        env.Eval(@"for(var i = 0 ;  i<count; i++){
                             for(var j = 0 ;  j<length; j++){
                               arrArr[i].SetValue(1,j);
                             }
                           }");
        sw.Stop();
        env.Dispose();
        Debug.Log(sw.ElapsedMilliseconds);
    }`

Thank you in advance for your assistance!
非常感谢你的帮助！

**Comment by zombieyang** [comment]
也可以用nodejs作为后端。quickjs尚未支持。

你用于测试的是哪个版本？是否生成了全量的FunctionBridge.Gen.h

**Comment by danij91** [comment]
@zombieyang 
Thank you for answering my question!
I tested with commit 53f33017883749f3c692d05ae61de0f6aba0797b when I found this issue.
and I tried again with your solution. But result is same. il2cpp is still 10 times slower than non il2cpp.

**Comment by zombieyang** [comment]
thanks for you feed back.

I wrote a test: https://github.com/zombieyang/PerformanceTesting/blob/main/Assets/CScripts/Examples/Example40.cs

and the result with commit 53f3301 is still in my expectation (tested in windows)
* C#: 177ms
* puer xIl2cpp mode: 591ms
* puer default mode + unity il2cpp: 2000ms
* puer default mode + unity mono: 3300ms
* xLua: 1191ms

Could you provide more information about your testing step? If it is too much, You can contact me in the Discord.

**Comment by danij91** [comment]
Hello, I think I made mistake while applying IL2CPP, and I have a few further questions.

1. I have been following the instructions provided in this link: https://puerts.github.io/en/docs/puerts/unity/performance/il2cpp/, but seem to have missed something. I'm having trouble pinpointing exactly where I went wrong. Could you possibly provide some guidance on this?
2. My testing has been exclusively conducted in the Unity editor environment (Windows 64-bit). Could this be the source of any potential issues?

Thank you in advance for your assistance.

您好，我在应用IL2CPP时可能犯了一些错误，我还有一些其他的问题。

我一直按照这个链接中提供的说明进行操作：https://puerts.github.io/en/docs/puerts/unity/performance/il2cpp/ ，但似乎还是错过了一些东西。

我在确定我哪里出错上有些困难。你能给我一些指导吗？

我仅在Unity编辑器环境（Windows 64位）中进行了测试。这可能是潜在问题的源头吗？

希望我的翻译准确无误。

提前感谢你的帮助。

**Comment by zombieyang** [comment]
Il2cpp backend will not take effect in Unity Editor, It needs Unity Compilation pipeline to transfer C# code to IL and finally to C++. So you must build your project to a standalone exe to see the result.

**Comment by danij91** [comment]
我非常感谢你的帮助，它帮我解决了问题！

我还有一些问题想要问：

1. Puerts 2.0的正式版本计划何时发布？
2. 你们有没有计划开发一个可以在Unity编辑器模式下使用的IL2CPP版本？

再次感谢你的帮助。


Your message is already quite good, but here's a slightly more polished version:

I greatly appreciate your assistance, as it helped me resolve the issue!

I do have a few more questions I'd like to ask:

1. When is the official release of Puerts 2.0 scheduled?
2. Are there any plans to develop an IL2CPP version that's available in Unity editor mode?

Again, thank you very much for your help.

**Comment by chexiongsheng** [comment]
Unity itself does not support il2cpp in editor.
