### ISSUE TITLE
[Unity] Bug: unity 2022 发布il2cpp mac版本失败

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1384]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0

### Unity的版本 | Unity Version

2022.3.0

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

![image](https://github.com/Tencent/puerts/assets/3063621/edd51001-8cb0-4720-be50-d57cbec734c0)

### 问题重现 | Bug reproduce

建个空项目，把puer库加入，发布il2cpp mac版直接就失败

**Comment by zombieyang** [comment]
试了2022.2，添加普洱，build空场景，在mono和il2cpp下均无复现。

你可以试试删掉Library重新打开或者再详细描述下你的步骤

**Comment by dunadain** [comment]
是intel版的吗？我怎么build都build不出来
[TestMac2.zip](https://github.com/Tencent/puerts/files/11733361/TestMac2.zip)

**Comment by zombieyang** [comment]
intel能复现了，首次确实都会出现该问题。但随后删掉Library重新打开就能build了。

待查

**Comment by zombieyang** [comment]
最新的master已经不再复现，04e5f83f15918b0249739591ab3d536f7d223f47 修复的。看来是unity没有给出正确的错误信息。
