### ISSUE TITLE
[UE] Typescript Editor

### ISSUE THREAD

**Issue by faseceroo** [Tencent/puerts#1386]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

I am using Visual Studio Code (VS Code) to edit the .ts files. Every time I save a change in VS Code, the changes are automatically updated in Unreal Engine. 

I recently found out that Visual Studio 2022 also supports editing .ts files. However, when I edit a .ts file in Visual Studio and save, the changes are not updated to Unreal Engine. Is there a way to use Visual Studio to edit .ts files in Unreal Engine? Or should I stick with using VS Code?

### 问题重现 | Bug reproduce

Edit the .ts file in Visual Studio. Save the file and switch to Unreal Engine. The changes to the .ts file are not reflected in the Unreal Engine.

**Comment by chexiongsheng** [comment]
I am using FDirectoryWatcherModule of UE for dir watch: https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/SourceFileWatcher.cpp
It seem that change from some IDE not notify by FDirectoryWatcherModule.

**Comment by Lance3d** [comment]
我用vs code也不能实现热重载。。ue版本5.2.1

**Comment by chexiongsheng** [comment]
> 我用vs code也不能实现热重载。。ue版本5.2.1

如果是使用的是继承ue模式，默认是开启的，但也并不是任意更改都支持。
如果是自己构造的虚拟机，需要参考这自己组装下：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/PuertsEditor/Private/PuertsEditorModule.cpp#L121

**Comment by faseceroo** [comment]
Every time I save, PuerTs calls **UPEDirectoryWatcher::Watch(...)** from \Puerts\Source\PuertsEditor\Private\PEDirectoryWatcher.cpp

Inside this function the line 
`OnChanged.Broadcast(Added, Modified, Removed);`

calls .ts code or .js code
```
\Puerts\PuertsEditor\CodeAnalyze.ts
\Puerts\Content\JavaScript\PuertsEditor\CodeAnalyze.js
```

This is the js code

```
    var dirWatcher = new UE.PEDirectoryWatcher();
    global.__dirWatcher = dirWatcher; //防止被释放?
    dirWatcher.OnChanged.Add((added, modified, removed) => {
        setTimeout(() => {
            var changed = false;
            if (added.Num() > 0) {
                onFileAdded();
                changed = true;
            }
            if (modified.Num() > 0) {
                for (var i = 0; i < modified.Num(); i++) {
                    const fileName = modified.Get(i);
                    if (fileName in fileVersions) {
                        let md5 = UE.FileSystemOperation.FileMD5Hash(fileName);
                        if (md5 === fileVersions[fileName].version) {
                            console.log(fileName + " md5 not changed, so skiped!");
                        }
                        else {
                            console.log(`${fileName} md5 from ${fileVersions[fileName].version} to ${md5}`);
                            fileVersions[fileName].version = md5;
                            onSourceFileAddOrChange(fileName, true);
                            changed = true;
                        }
                    }
                }
            }
            if (changed) {
                console.log("versions saved to " + versionsFilePath);
                UE.FileSystemOperation.WriteFile(versionsFilePath, JSON.stringify(fileVersions, null, 4));
            }
        }, 100); //延时100毫秒，防止因为读冲突而文件读取失败
    });
```

Something in this function is not working for Visual Studio. Unfortunately I cannot debug this file because is not a c++ file.

**Comment by faseceroo** [comment]
I'm guessing I need to save CodeAnalyze.ts correctly so that a new CodeAnalyze.js file is created. Then I can check what's not working in Visual Studio. When I open the file, I see this message. How can I fix this?
![image](https://github.com/Tencent/puerts/assets/93630866/47ab2d39-7f4d-49fe-b1b7-30f93eef5397)

**Comment by faseceroo** [comment]
Nevermind, I figured it out. I need to delete the **tsconfig.json** file and the **Content\JavaScript\PuertsEditor\node_modules** folder, so it triggers the build after I run node **enable_puerts_module.js**. I have to redo this every time I edit **CodeAnalyze.js**.

So, I am placing **console.log()** statements around and I see them after I save in both Visual Studio (VS) and Visual Studio Code (VSCode). The difference is that VSCode saves the file directly, but Visual Studio saves the file to a temporary folder, deletes the file I'm saving, and replaces it with that temporary file.

So I need to play with the code I posted above to take into account this behavior from VS.

**Comment by chexiongsheng** [comment]
> I'm guessing I need to save CodeAnalyze.ts correctly so that a new CodeAnalyze.js file is created. Then I can check what's not working in Visual Studio. When I open the file, I see this message. How can I fix this?
> 
> ![image](https://user-images.githubusercontent.com/93630866/249650695-47ab2d39-7f4d-49fe-b1b7-30f93eef5397.jpg)

Run ·npm install .· in the Plugins\Puerts\PuertsEditor folder.

**Comment by chexiongsheng** [comment]
> Nevermind, I figured it out. I need to delete the **tsconfig.json** file and the **Content\JavaScript\PuertsEditor\node_modules** folder, so it triggers the build after I run **node enable_puerts_module.js**. I have to redo this every time I edit **CodeAnalyze.js**.
> 
> So, I am placing **console.log()** statements around and I see them after I save in both Visual Studio (VS) and Visual Studio Code (VSCode). The difference is that VSCode saves the file directly, while Visual Studio saves the file to a temporary folder, deletes the file I'm saving, and replaces it with that temporary file.
> 
> So I need to play with the code I posted above to take into account this behavior from VS.

Thank you for this crucial infomation.

**Comment by faseceroo** [comment]
Thanks to you. I can finally use Visual Studio for both c++ and typescript ^^
