### ISSUE TITLE
[Unity] Bug: Master分支上生成代码报错

### ISSUE THREAD

**Issue by Augkit** [Tencent/puerts#1389]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

Master:ea2787156434c4ba88844e96e3e2ec0a4cc023bf

### Unity的版本 | Unity Version

2022.3.1f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

和 #1365 一样依旧出现生成代码报错 。

### 问题重现 | Bug reproduce

原因是 c52798d517b48a941cfebbff258c9d52d176dbf0 没有通过单元测试

**Comment by zombieyang** [comment]
报错信息也一样么？

**Comment by Augkit** [comment]
点击Generate (all in one) 会出现如下报错：
Exception: puerts/templates/registerinfo.tpl.mjs:24: TypeError: Cannot read properties of null (reading 'WrapperName')

TypeError: Cannot read properties of null (reading 'WrapperName')
    at puerts/templates/registerinfo.tpl.mjs:24:59
    at Array.map (<anonymous>)
    at FOR (puerts/templates/tte.mjs:202:19)
    at RegisterInfoTemplate (puerts/templates/registerinfo.tpl.mjs:23:11)
Puerts.GenericDelegate.Func[T1,TResult] (T1 p1) (at C:/Users/m/FireflyWorkBench/tool/puerts_unity_demo/package/Runtime/Src/Default/JSType/GenericDelegate.cs:525)
Puerts.Editor.Generator.FileExporter.GenRegisterInfo (System.String outDir, Puerts.ILoader loader) (at C:/Users/m/FireflyWorkBench/tool/puerts_unity_demo/package/Editor/Src/Generator/FileExporter.cs:216)
Puerts.Editor.Generator.UnityMenu.GenRegisterInfo () (at C:/Users/m/FireflyWorkBench/tool/puerts_unity_demo/package/Editor/Src/Generator/UnityMenu.cs:111)
Puerts.Editor.Generator.UnityMenu.GenerateCode () (at C:/Users/m/FireflyWorkBench/tool/puerts_unity_demo/package/Editor/Src/Generator/UnityMenu.cs:40)
Puerts.Editor.Generator.UnityMenu.GenV1 () (at C:/Users/m/FireflyWorkBench/tool/puerts_unity_demo/package/Editor/Src/Generator/UnityMenu.cs:27)

**Comment by zombieyang** [comment]
看这个栈的话，你代码应该没更新，master上的 `package/Editor/Src/Generator/FileExporter.cs` 已经没有216行了
