### ISSUE TITLE
[Unity] Bug: nodejs xil2cpp build error

### ISSUE THREAD

**Issue by EverydayDevup** [Tencent/puerts#1390]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

Unity_v2.0.0-pre.5 git hash 7a722f0bebcc0a112c5905eea0ad6a18cbfecdbc

### Unity的版本 | Unity Version

unity 2021.3.17f1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

你好。 按照指南搭建xil2cpp时，如果使用nodejs，会报错。

https://puerts.github.io/en/docs/puerts/unity/performance/il2cpp

指南中编号4对应的构建从v8构建更改为nodejs如下。
节点 ../cli make --backend nodejs_16 --platform win --arch x64 --config 调试

构建结果
Puerts/unity/cli/make.mts:118
                  assert.equal(0, exec(`cmake --build ${CMAKE_BUILD_PATH} --config ${options.config}`).code)
                         ^

断言错误 [ERR_ASSERTION]: 0 == 1
      在 Object.hook (Puerts/unity/cli/make.mts:118:24)
      在 runPuertsMake (Puerts/unity/cli/make.mts:193:34) {
    生成的消息：真实的，
    代码：'ERR_ASSERTION'，
    实际：0；
    预期：1，
    运算符：'=='
}

出现同样的错误。

但是不支持 v8 构建成功 nodejs？

=================================================================================

hello. When building xil2cpp according to the guide, if you use nodejs, an error occurs.

https://puerts.github.io/en/docs/puerts/unity/performance/il2cpp

The build corresponding to number 4 in the guide was changed from v8 build to nodejs as follows.
node ../cli make --backend nodejs_16 --platform win --arch x64 --config Debug

build result
Puerts/unity/cli/make.mts:118
                 assert.equal(0, exec(`cmake --build ${CMAKE_BUILD_PATH} --config ${options.config}`).code)
                        ^

AssertionError [ERR_ASSERTION]: 0 == 1
     at Object.hook (Puerts/unity/cli/make.mts:118:24)
     at runPuertsMake (Puerts/unity/cli/make.mts:193:34) {
   generatedMessage: true,
   code: 'ERR_ASSERTION',
   actual: 0;
   expected: 1,
   operator: '=='
}

The same error occurred.

but v8 build is Success nodejs not supported?

### 问题重现 | Bug reproduce

1. Git Clone Local Path
2. Unity New Project
3. Add Package From Disk -> 1. Local Path
4. Guide 2st Build
- cd Puerts\unity\native_src
- node ../cli make --platform win --backend nodejs_16 --config Release --arch auto
- result : Puerts\unity\native_src\build_win_x64_nodejs_16_debug\RelWithDebInfo\puerts.dll
5. Unity Define Add
6. xil2cpp Build
- cd Puerts\unity\native_src_il2cpp
- node ../cli make --platform win --backend nodejs_16 --config Release --arch auto
- error

**Comment by mingxxming** [comment]
v8 也过不了：
/home/runner/work/puerts/puerts/unity/native_src_il2cpp/Src/Puerts.cpp:27:10: fatal error: 'UnityExports4Puerts.h' file not found
#include "UnityExports4Puerts.h"
         ^~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

**Comment by zombieyang** [comment]
Can you provide more error message? There should be more error information before these.

**Comment by zombieyang** [comment]
> v8 也过不了： /home/runner/work/puerts/puerts/unity/native_src_il2cpp/Src/Puerts.cpp:27:10: fatal error: 'UnityExports4Puerts.h' file not found #include "UnityExports4Puerts.h" ^~~~~~~~~~~~~~~~~~~~~~~
> 
> 1 error generated.

master上刚刚修改过了，`Plugins/puerts_il2cpp`的文件现在变成了生成出来的。否则不用xil2cpp模式的人体验受影响。

**Comment by EverydayDevup** [comment]
Using master branch 7a722f0bebcc0a112c5905eea0ad6a18cbfecdbc

In the terminal I ran:

cd Puerts\unity\native_src
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.

--Configuring done (0.0s)

-- Generating done (0.0s)

-- Build files have been written to: Puerts/unity/native_src/build_win_x64_nodejs_16_debug

cmake --build Puerts\unity\native_src/build_win_x64_nodejs_16_debug --config RelWithDebInfo

Microsoft (R) Build Engine 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

puerts.vcxproj -> Puerts_xlil2cpp\Puerts\unity\native_src\build_win_x64_nodejs_16_debug\RelWithDebInfo\puerts.dll

After it was done, I entered the following command:

cd Puerts\unity\native_src_il2cpp

node ../cli make --backend nodejs_16 --platform win --arch x64 --config Debug


node --loader ts-node/esm Puerts\unity\cli/cmd.mts make --backend nodejs_16 --platform win --arch x64 --config Debug
(node:45380) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

CHCP 65001

cmake --version

[Puer] download skip: nodejs_16 already exists

cmake -DBACKEND_DEFINITIONS="WITH_NODEJS" -DBACKEND_LIB_NAMES="/Lib/Win64/libnode.lib" -DBACKEND_INC_NAMES="/include;/deps/v8/include;/deps/uv/include" -DJS_ENGINE=nodejs_16 -DCMAKE_BUILD_TYPE=RelWithDebInfo - G "Visual Studio 16 2019" -A x64 ..

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.

--Configuring done (0.0s)

-- Generating done (0.0s)

-- Build files have been written to: Puerts/unity/native_src_il2cpp/build_win_x64_nodejs_16_debug

cmake --build Puerts\unity\native_src_il2cpp/build_win_x64_nodejs_16_debug --config RelWithDebInfo

Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.


   Puerts.cpp

Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\Inc\JSClassRegister.h(17,1): warning C4005: 'FORCEINLINE': macro override [Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vc xproj]

C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(356): message : See previous definition of 'FORCEINLINE'. [Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

Puerts_xlil2cpp\Puerts\unreal\Puerts\Source\JsEnv\Private\V8InspectorImpl.h(1,1): warning C4819: File contains characters that cannot be represented in the current code page (949). Save the file in Unicode format to avoid data loss. [Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\Src\Puerts.cpp(767,1): error C2660: 'puerts::BackendEnv::LogicTick': function does not take 2 arguments [Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

See declaration Puerts\unity\native_src\Inc\BackendEnv.h(51,14): message : 'puerts::BackendEnv::LogicTick'. [Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

file:///Puerts_xlil2cpp/Puerts/unity/cli/make.mts:118
                 assert.equal(0, exec(`cmake --build ${CMAKE_BUILD_PATH} --config ${options.config}`).code)
                        ^

AssertionError [ERR_ASSERTION]: 0 == 1
     at Object.hook (file:///Puerts/unity/cli/make.mts:118:24)
     at runPuertsMake (file:///Puerts/unity/cli/make.mts:193:34) {
   generatedMessage: true,
   code: 'ERR_ASSERTION',
   actual: 0;
   expected: 1,
   operator: '=='
}
===============================================================================

使用主分支 7a722f0bebcc0a112c5905eea0ad6a18cbfecdbc

在终端我跑了：

cd Puerts\unity\native_src
-- 选择 Windows SDK 版本 10.0.19041.0 以面向 Windows 10.0.19045。

--配置完成（0.0s）

-- 生成完成（0.0s）

-- 构建文件已写入：Puerts/unity/native_src/build_win_x64_nodejs_16_debug

cmake --build Puerts\unity\native_src/build_win_x64_nodejs_16_debug --config RelWithDebInfo

Microsoft (R) Build Engine 16.11.2+f32259642 for .NET Framework
版权所有 (C) Microsoft Corporation。 版权所有。

puerts.vcxproj -> Puerts_xlil2cpp\Puerts\unity\native_src\build_win_x64_nodejs_16_debug\RelWithDebInfo\puerts.dll

完成后，我输入了以下命令：

cd Puerts\unity\native_src_il2cpp

节点 ../cli make --backend nodejs_16 --platform win --arch x64 --config 调试


node --loader ts-node/esm Puerts\unity\cli/cmd.mts make --backend nodejs_16 --platform win --arch x64 --config 调试
（节点：45380）实验警告：自定义 ESM 加载器是一项实验性功能，可能随时更改
（使用 `node --trace-warnings ...` 显示创建警告的位置）

CHCP 65001

cmake --version

[普洱] 下载跳过：nodejs_16 已经存在

cmake -DBACKEND_DEFINITIONS="WITH_NODEJS" -DBACKEND_LIB_NAMES="/Lib/Win64/libnode.lib" -DBACKEND_INC_NAMES="/include;/deps/v8/include;/deps/uv/include" -DJS_ENGINE=nodejs_16 -DCMAKE_BUILD_TYPE=RelWithDebInfo - G“Visual Studio 16 2019”-A x64 ..

-- 选择 Windows SDK 版本 10.0.19041.0 以面向 Windows 10.0.19045。

--配置完成（0.0s）

-- 生成完成（0.0s）

-- 构建文件已写入：Puerts/unity/native_src_il2cpp/build_win_x64_nodejs_16_debug

cmake --build Puerts\unity\native_src_il2cpp/build_win_x64_nodejs_16_debug --config RelWithDebInfo

适用于 .NET Framework 的 Microsoft (R) 构建引擎版本 16.11.2+f32259642
版权所有 (C) Microsoft Corporation。 版权所有。


    普尔茨.cpp

x项目]

C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(356): 消息：请参阅“FORCEINLINE”的先前定义。 [Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

Puerts_xlil2cpp\Puerts\unreal\Puerts\Source\JsEnv\Private\V8InspectorImpl.h(1,1)：警告 C4819：文件包含无法在当前代码页 (949) 中表示的字符。 以 Unicode 格式保存文件以避免数据丢失。 [Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

Puerts_xlil2cpp\Puerts\unity\native_src_il2cpp\Src\Puerts.cpp(767,1): 错误 C2660: 'puerts::BackendEnv::LogicTick': 函数不接受 2 个参数 [Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_ il2c页。 vcxproj]

请参阅声明 Puerts\unity\native_src\Inc\BackendEnv.h(51,14)：消息：'puerts::BackendEnv::LogicTick'。 [Puerts\unity\native_src_il2cpp\build_win_x64_nodejs_16_debug\puerts_il2cpp.vcxproj]

文件:///Puerts_xlil2cpp/Puerts/unity/cli/make.mts:118
                  assert.equal(0, exec(`cmake --build ${CMAKE_BUILD_PATH} --config ${options.config}`).code)
                         ^

断言错误 [ERR_ASSERTION]: 0 == 1
      在 Object.hook（文件：///Puerts/unity/cli/make.mts:118:24）
      在 runPuertsMake (file:///Puerts/unity/cli/make.mts:193:34) {
    生成的消息：真实的，
    代码：'ERR_ASSERTION'，
    实际：0；
    预期：1，
    运算符：'=='
}

**Comment by zombieyang** [comment]
fixed. Thanks for your contribution
