### ISSUE TITLE
[UE] Bug: 首次启动Editor,PIE的时候缓存的UFunction被替换

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1395]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master 3459a0de

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

文字图片都是一个错误

Puerts: Error: (0x00000A1619139190) call TS_BlueprintFunctionLibrary_C::AnimalAutoKill 00000A160CCFA8C0 of 00000A1F4F3CBF70 fail: can not find Binded JavaScript Function

![e2513df67fdfa7ffacdaeb299872b25](https://github.com/Tencent/puerts/assets/5946974/9129d13d-387e-4667-a2bd-11227b036352)

### 问题重现 | Bug reproduce

问题产生是ts继承BlueprintFunctionLibrary类，被蓝图行为树节点以及ts调用。目前解决是把方法抽出去，ts不直接require这个对象，只让蓝图调用，暂时能够解决，但是原理尚不明确。

- 重现步骤

1. 继承BlueprintFunctionLibrary的继承引擎类
![image](https://github.com/Tencent/puerts/assets/5946974/8a52e604-c098-4908-a8be-5d2386ccdc2b)
2. 被原生ts调用
![image](https://github.com/Tencent/puerts/assets/5946974/464c59b9-a0ce-4f5c-9c9b-130bfb218056)
3. 生成的蓝图被蓝图节点调用
![image](https://github.com/Tencent/puerts/assets/5946974/4d33fcd9-5c2a-489e-977c-b6334b023291)

- 问题分析，感觉是对象创建通过MakeSureInject绑定了之后，又经过了重新编译，但是puerts没有收到通知处理

1、注意绑定的对象和函数的地址

![67c0f41f9aab6f8b1358a75b8c1fdb9](https://github.com/Tencent/puerts/assets/5946974/fc24c8f9-8408-4965-b304-6fbc16a13cde)

2、绑定后引擎调用了PurgeClass清空了Children,并且重新添加了Function

![788d64f606cb9ba37edd25d125a3202](https://github.com/Tencent/puerts/assets/5946974/7d511282-2650-4866-9cf2-d19ec74814bf)
![cb54333dc29cb3baa32ad1b30365bb4](https://github.com/Tencent/puerts/assets/5946974/75762bbd-82ed-4dca-8b9a-78219dfe9f55)

3、原有绑定函数的销毁通知被Puerts监听到，删除绑定
![ce7589bf69f46b4e191e910723c50fa](https://github.com/Tencent/puerts/assets/5946974/79f9f54b-de76-44a3-b82f-456a5fa83169)
4、这个时候函数调用过来发现，没有找到对应的映射，并且TS_BlueprintFunctionLibrary依然存在，所以没有重新绑定，报错
![ac4ed22ca63994b8fab721dcedf4325](https://github.com/Tencent/puerts/assets/5946974/1937fc06-207c-40d4-9abf-f9ec1eea92cb)
![e2513df67fdfa7ffacdaeb299872b25](https://github.com/Tencent/puerts/assets/5946974/43dc2253-10c1-4c99-91b2-a05e7fc1e5d0)

**Comment by chexiongsheng** [comment]
能在https://github.com/chexiongsheng/puerts_unreal_demo基础上加些代码做个重现工程么？
另外，也可以试试升级下，你这版本后面有些这块的修改。

**Comment by lzj10** [comment]
我更新一下复现试试

**Comment by lzj10** [comment]
启动编辑器首次启动游戏报错
![image](https://github.com/Tencent/puerts/assets/5946974/02b25b85-cd36-4a26-9841-5c2276b7c2bc)
不关闭编辑器再次启动游戏可正常绑定
![image](https://github.com/Tencent/puerts/assets/5946974/e4af56ea-d6f8-4d7b-820c-c05173756464)

**Comment by lzj10** [comment]
看代码确实是只有在Editor模式下会重新编译
![image](https://github.com/Tencent/puerts/assets/5946974/b49e1225-dcbe-4f41-891c-b3b37dbe0689)

**Comment by chexiongsheng** [comment]
TsTestGameMode::ReceiveBeginPlay 里加载TestBT
UE.BehaviorTree.Load("/Script/AIModule.BehaviorTree'/Game/Blueprints/TestBT.TestBT'")
TestBT引用了TsTestBlueprintFunctionLibrary

加载TestBT过程中，走到如下代码（ue5.2.1）
~~~c++
UObject* FLinkerLoad::CreateExport( int32 Index )
{
	// ......

		if ( Export.Object != NULL )
		{
			// If it's a struct or class, set its parent.
			if( UStruct* Struct = dynamic_cast<UStruct*>(Export.Object) )
			{
				if ( !Export.SuperIndex.IsNull() )
				{
					UStruct* SuperStruct = (UStruct*)IndexToObject(Export.SuperIndex);
					if (ULinkerPlaceholderFunction* Function = Cast<ULinkerPlaceholderFunction>(SuperStruct))
					{
						Function->AddDerivedFunction(Struct);
					}
					else
					{
						Struct->SetSuperStruct((UStruct*)IndexToObject(Export.SuperIndex));
					}
				}

				// If it's a class, bind it to C++.
				if (UClass* ClassObject = Cast<UClass>(Export.Object))
				{
					if (ClassObject->GetClass()->HasAnyClassFlags(CLASS_NeedsDeferredDependencyLoading))
					{
#if WITH_EDITOR
						// Before we serialize the class, begin a scoped class 
						// dependency gather to create a list of other classes that 
						// may need to be recompiled
						//
						// Even with "deferred dependency loading" turned on, we 
						// still need this... one class/blueprint will always be 
						// fully regenerated before another (there is no changing 
						// that); so dependencies need to be recompiled later (with
						// all the regenerated classes in place)
						FScopedClassDependencyGather DependencyHelper(ClassObject, GetSerializeContext());
#endif //WITH_EDITOR

						ClassObject->Bind();

						// Preload classes on first access.  Note that this may update the Export.Object, so ClassObject is not guaranteed to be valid after this point
						// If we're async loading on a cooked build we can skip this as there's no chance we will need to recompile the class. 
						// Preload will be called during async package tick when the data has been precached
						if (!FPlatformProperties::RequiresCookedData())
						{
							Preload(Export.Object);// 这里先触发了对TsTestBlueprintFunctionLibrary的构造和js注入
						}
                                                // 然后这析构DependencyHelper，触发对TsTestBlueprintFunctionLibrary（Export.Object变量）的修改
					}
					else
					{
						ClassObject->Bind();
					}
				}
			}
~~~
