### ISSUE TITLE
[Unity] Bug: 切换到webgl后，CS.UnityEngine.Vector3.op_Subtraction 报错（CS.UnityEngine.Vector3.op_Subtraction is not a function）

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1399]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0.pre5

### Unity的版本 | Unity Version

2022.3.0

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

Exception: chunk:5: TypeError: CS.UnityEngine.Vector3.op_Subtraction is not a function

### 问题重现 | Bug reproduce

切换到webgl平台，点 generate（one for all)

执行：
var jsEnv = new JsEnv();
        jsEnv.Eval(@"
console.log('hello world');
            const v = new CS.UnityEngine.Vector3(1, 1, 1);
            const v2 = new CS.UnityEngine.Vector3(0, 0, 0);
const tempnormal = CS.UnityEngine.Vector3.op_Subtraction(v, v2).normalized;
console.log(tempnormal);
");
就直接报错

**Comment by zombieyang** [comment]
十分感谢！
