### ISSUE TITLE
需要代码"热重载"功能

### ISSUE THREAD

**Issue by aschord** [Tencent/puerts#140]
可以效仿Unreal.js 增加程序运行时代码"热重载"功能！哥断定，Puerts未来必将超越 Unreal.js 和 UnLua

**Comment by chexiongsheng** [comment]
这功能大概几十行代码的事情，说得有多厉害似的。
目前在做的功能是实现ts和ue编辑器的无缝配合，比如ts类能够直接拖拽到场景，在ue编辑器选择一个ts类等。做这功能会顺手把这所谓的“热重载”实现。

**Comment by chexiongsheng** [comment]
顺带支持了，可以到demo那体验下：
1、ts继承UE类，自动生成蓝图（蓝图生成到Content\Blueprints\TypeScript下），蓝图包含ts的方法/事件/成员，可以直接在编辑器下使用，可被其它蓝图调用，例子提供的TsTestActor.ts，TsTestGameInstance.ts，TsTestGameMode.ts，TsTestActor生成的蓝图可以拖拽进场景，TsTestGameInstance可以在UE“项目设置”里头选择使用，TsTestGameMode可以在世界场景设置那选择使用，然后都能调用到具体的ts类相应逻辑。
2、运行时热刷新：TsTestActor拖进场景，运行后ReceiveTick会被调用，这时你修改ReceiveTick的逻辑后，不用重新播放，运行时立即生效；
3、代码自动增量编译，不需要外部再启动个ts编译器了；
体验方式：
1、puerts_unreal_demo\Content\JavaScript\PuertsEditor下执行：npm install .
2、Plugins\Puerts\Source\Puerts\Private\PuertsModule.cpp的Enabled改为true

**Comment by linonetwo** [comment]
Unity 会得到和 ue 一样的支持吗

**Comment by chiuan** [comment]
how about unity support??

**Comment by UpUpLiu** [comment]
我在unity里面模拟试了一下ue4的方案,  目前遇到的问题是 我reload只能reload当前文件, 而这个文件在其他文件中被 import回去的值无法更改. 
查阅资料发现 commonjs的加载方式的处理就是 加载回去的只是一个值拷贝, 当新的文件被reload的时候, 被copy的值不会受到影响.

**Comment by chexiongsheng** [comment]
@linonetwo @chiuan @UpUpLiu 
unity版本之前就有人提交了PR：https://github.com/Tencent/puerts/pull/114
需要通过ENABLE_CJS_AUTO_RELOAD开启

**Comment by Difficulty-in-naming** [comment]
调用了缓存清除.修改ts的log编辑器中的打印仍然没有生效.如果重新require的话就不是真正的热重载了.
请问有相关的demo可以看看吗.

**Comment by chexiongsheng** [comment]
> Unity版本调用了缓存清除.修改ts的log编辑器中的打印仍然没有生效.如果重新require的话就不是真正的热重载了.
> 请问有相关的demo可以看看吗.

unity版本没这功能，但你用chrome dev tool连接过去，在chrome dev tool上修改代码是可以热刷新的。

**Comment by hugebug4ever** [comment]
如果是用 [这个方法](https://github.com/Tencent/puerts/blob/master/doc/unreal/manual.md#%E8%87%AA%E8%A1%8C%E6%9E%84%E9%80%A0puertsfjsenv) 构造的 虚拟机，是不是不支持 HotReload ? 我试了下不行，是我手法不对么？

**Comment by chexiongsheng** [comment]
> Unreal 如果用 [自行构造 JsEnv 的模式](https://github.com/Tencent/puerts/blob/master/doc/unreal/manual.md#%E8%87%AA%E8%A1%8C%E6%9E%84%E9%80%A0puertsfjsenv) 构造的 JsEnv 是不是不支持这个功能？ 能改造不？

FJsEnv有个ReloadModule，你监听文件变化然后调用这个，或者用nodejs的chrome-remote-interface连接调试接口去刷新。
