### ISSUE TITLE
[Unity]What can replace GenericDelegate?

### ISSUE THREAD

**Issue by danij91** [Tencent/puerts#1400]
## detail | 详细描述
I've been using the 'GenericDelegate' class to set field values and invoke events in a C# class instantiated from TypeScript code. However, I discovered that 'GenericDelegate' is not supported in IL2CPP mode. I'm curious if there's an alternative to the 'GenericDelegate' class in this context or if I should explore a completely different approach. I would like to express my gratitude in advance for your guidance and for always providing answers to my questions.

我一直在使用 'GenericDelegate' 类来设置在 TypeScript 代码中实例化的 C# 类的字段值并调用事件。然而，我发现在 IL2CPP 模式下，'GenericDelegate' 类不被支持。我想知道在这种情况下是否有 'GenericDelegate' 类的替代品，或者我是否应该寻找一种完全不同的方法。在此，我提前感谢您的指导，并感谢您总是对我的问题作出回答。

**Comment by zombieyang** [comment]
You don't need GenericDelegate to do that. A c# object created in TS can be passed back to c#.

**Comment by danij91** [comment]
Thank you for your advice!
What if I try extending the TypeScript class from the C# class?

For example, consider the following C# class:
**TestClass.cs**
`public class TestClass
{
    public string testField;

    public void Log()
    {
        Debug.Log(testField);
    }
}`

And the TypeScript code:
**test.mjs**
`class TestClassEx extends CS.TestClass {
    LogInTs() {
        console.log("testField is " + this.testField)
    }
}

var classInstance = new TestClassEx();
classInstance.testField = "testFieldValue";
classInstance
`

In your C# code, you can try the following approach:
`public void Run()
    {
        var jsCode = Resources.Load<TextAsset>("test").text;
        using (var env = new Puerts.JsEnv())
        {
            var obj = env.Eval<TestClass>(jsCode);
            obj.Log();
        }
    }`
The result is printing "testFieldValue." However, I want to execute the LogInTs method in C#. Can you let me know how to do that?

**Comment by zombieyang** [comment]
Well, extends CS class in TS is not recommended because we don't know how to manage its memory. The memory management of JSObject and CSObject is totally different. more: #65 

I recommend to refer a CSClass in a JSClass instead of extend it. And if you want to override the behaviour of CSClass, maybe you can design a delegate field/property in CSClass, and change it in the JSClass.

**Comment by danij91** [comment]
Aha Okay! Then, What was the intended purpose of developing the GenericDelegate class?

**Comment by zombieyang** [comment]
> Aha Okay! Then, What was the intended purpose of developing the GenericDelegate class?

It is a internal class by design
