### ISSUE TITLE
[UE] Bug: 继承引擎类写法为啥缺陷太多，几乎用不了

### ISSUE THREAD

**Issue by lozn00** [Tencent/puerts#1402]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

new

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

下面代码均在 export  也就是自定义类里面的逻辑里面写的，
我发现 他能在里面只能调用c++定义的库

1.继承自定义的蓝图类报错、调用自身父类蓝图实现代码报错
2.直接拿到Getworld()去创建actor报错，
3.通过let world = (argv.getByName("GameInstance") as UE.GameInstance).GetWorld(); 报错 (也是想用来创建actor的）
4.调用其他类的实例化的蓝图类 报错 ，哪怕调用实例化的蓝图类的父类 c++类 也报错，

------------最后我通过 c++定义了纯蓝图库，js成功的在这里面调用没报错。。

但是 创建的actor（蓝图，或者蓝图父类c++）依然是不能调用方法的
但是 这些代码 在 直接 gameinstance load js 也就是类似quickstart.js里面调用都是没有问题的，但是我现在是要把代码写在一个actor里面，我不用这种方法我要怎么写，必须混入吗？

### 问题重现 | Bug reproduce

class TS_Actor extends UE.Actor {// UE.Game.CesiumSamples.Maps.$01.TSBsseActor.TSBsseActor_C{//

}

我就想在TS_Actor 里面来 实现 actor拖到场景 ，就自动创建一个ui,并设置里面的内容，
以及在这个actor进行网络去请求 解析城市然后创建ui actor，然后 uiactor设置布局，但是 现在显然让我没有感觉到这提升了效率，似乎 这个写法基本是个鸡肋了。

**Comment by terst6** [comment]
看看 demo，再看看 demo

**Comment by chexiongsheng** [comment]
有没怀疑过是自己的问题呢？
这特性几年前开发的，很多大项目都在用，都用得好好的。也很久没做过什么大改。
就你Q群问的那些问题，反映的最大的问题是对ue很陌生，puerts是把ue api封装给js用，这代表使用得有两个前提：对ue以及js有足够的了解。另外一个问题是你搞混了puerts的两种使用方式。

**Comment by chexiongsheng** [comment]
看到这个issue：https://github.com/Tencent/puerts/issues/1398 
我想起你的另外一个问题，也许是诸多问题的来源：你第一次在群上提axios，我说得用nodejs版本puerts，不知道你怎么选了个完全没人提过，比v8功能更弱的quickjs。
还有你这issue提到的argv.getByName，在demo那也有明确注释说明是自己从Start传入。
这些体现你比较急躁，有点不求甚解就动手开干了。你对ue的陌生应该也源于这点。
