### ISSUE TITLE
[UE] question 关于DefaultJSModuleLoader::Search模块的疑问和请教

### ISSUE THREAD

**Issue by joelyang0215** [Tencent/puerts#1404]
### 情况说明
在使用Puerts的过程中，想引入express这个模块，但是会报“can not find call-bind/callBound moduler” 和 "can not find ipaddr.js"这两个模块查找不到的错误。经过简单分析，是因为express模块依赖的模块在引入模块的时候使用的写法分别是require("call-bind/callBound")和require("ipaddr.js")。而如下代码所示，DefaultJSModuleLoader::Search方法在一次模块查找(SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))方法后，在接下来的文件夹向上查找过程中，做了判断，忽略了引用模块后缀为".js"和".mjs"，同时也忽略了模块内部有"/"符号的查找。同时在向上查找过程中，忽略对node_modules文件夹进行查找。之后就直接在Content路径下进行查找了。在删除掉相关忽略以后，express成功引入，并且使用正常。
### 疑问和请教
想请教一下，是出于什么考虑，加入了上面所述".js"、".mjs"文件和"node_modules"文件夹的忽略。
### 相关代码（由于没找到Issue直接引用仓库代码，所以就直接手贴到这里了）
文件路径：https://github.com/Tencent/puerts/tree/master/unreal/Puerts/Source/JsEnv/Private/DefaultJSModuleLoader.cpp
```
bool DefaultJSModuleLoader::Search(const FString& RequiredDir, const FString& RequiredModule, FString& Path, FString& AbsolutePath)
{
    if (SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))
    {
        return true;
    }
    if (RequiredDir != TEXT("") && !RequiredModule.GetCharArray().Contains('/') && !RequiredModule.EndsWith(TEXT(".js")) &&
        !RequiredModule.EndsWith(TEXT(".mjs")))
    {
        // 调用require的文件所在的目录往上找
        TArray<FString> pathFrags;
        RequiredDir.ParseIntoArray(pathFrags, TEXT("/"));
        pathFrags.Pop();    // has try in "if (SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))"
        while (pathFrags.Num() > 0)
        {
            if (!pathFrags.Last().Equals(TEXT("node_modules")))
            {
                if (SearchModuleInDir(FString::Join(pathFrags, TEXT("/")), RequiredModule, Path, AbsolutePath))
                {
                    return true;
                }
            }
            pathFrags.Pop();
        }
    }

    return SearchModuleInDir(FPaths::ProjectContentDir() / ScriptRoot, RequiredModule, Path, AbsolutePath) ||
           (ScriptRoot != TEXT("JavaScript") &&
               SearchModuleInDir(FPaths::ProjectContentDir() / TEXT("JavaScript"), RequiredModule, Path, AbsolutePath));
}
```

**Comment by chexiongsheng** [comment]
要杜绝这类问题，得等这个feature完成：https://github.com/Tencent/puerts/issues/1248

**Comment by PrimaryFantasty** [comment]
> ## detail | 详细描述
> ### 情况说明
> 在使用Puerts的过程中，想引入express这个模块，但是会报“can not find call-bind/callBound moduler” 和 "can not find ipaddr.js"这两个模块查找不到的错误。经过简单分析，是因为express模块依赖的模块在引入模块的时候使用的写法分别是require("call-bind/callBound")和require("ipaddr.js")。而如下代码所示，DefaultJSModuleLoader::Search方法在一次模块查找(SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))方法后，在接下来的文件夹向上查找过程中，做了判断，忽略了引用模块后缀为".js"和".mjs"，同时也忽略了模块内部有"/"符号的查找。同时在向上查找过程中，忽略对node_modules文件夹进行查找。之后就直接在Content路径下进行查找了。在删除掉相关忽略以后，express成功引入，并且使用正常。
> 
> ### 疑问和请教
> 想请教一下，是出于什么考虑，加入了上面所述".js"、".mjs"文件和"node_modules"文件夹的忽略。
> 
> ### 相关代码（由于没找到Issue直接引用仓库代码，所以就直接手贴到这里了）
> 文件路径：https://github.com/Tencent/puerts/tree/master/unreal/Puerts/Source/JsEnv/Private/DefaultJSModuleLoader.cpp
> 
> ```
> bool DefaultJSModuleLoader::Search(const FString& RequiredDir, const FString& RequiredModule, FString& Path, FString& AbsolutePath)
> {
>     if (SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))
>     {
>         return true;
>     }
>     if (RequiredDir != TEXT("") && !RequiredModule.GetCharArray().Contains('/') && !RequiredModule.EndsWith(TEXT(".js")) &&
>         !RequiredModule.EndsWith(TEXT(".mjs")))
>     {
>         // 调用require的文件所在的目录往上找
>         TArray<FString> pathFrags;
>         RequiredDir.ParseIntoArray(pathFrags, TEXT("/"));
>         pathFrags.Pop();    // has try in "if (SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))"
>         while (pathFrags.Num() > 0)
>         {
>             if (!pathFrags.Last().Equals(TEXT("node_modules")))
>             {
>                 if (SearchModuleInDir(FString::Join(pathFrags, TEXT("/")), RequiredModule, Path, AbsolutePath))
>                 {
>                     return true;
>                 }
>             }
>             pathFrags.Pop();
>         }
>     }
> 
>     return SearchModuleInDir(FPaths::ProjectContentDir() / ScriptRoot, RequiredModule, Path, AbsolutePath) ||
>            (ScriptRoot != TEXT("JavaScript") &&
>                SearchModuleInDir(FPaths::ProjectContentDir() / TEXT("JavaScript"), RequiredModule, Path, AbsolutePath));
> }
> ```

你的Puerts是哪一个版本的？我还没试过express，但react16里面有 `require('prop-types/checkProp')`, 同样是"/"分隔的，react16我在npm下似乎可以正常引入。pnpm子项目下不行，原因应该有因为被强行跳过"node_modules"

**Comment by joelyang0215** [comment]
> > ## detail | 详细描述
> > ### 情况说明
> > 在使用Puerts的过程中，想引入express这个模块，但是会报“can not find call-bind/callBound moduler” 和 "can not find ipaddr.js"这两个模块查找不到的错误。经过简单分析，是因为express模块依赖的模块在引入模块的时候使用的写法分别是require("call-bind/callBound")和require("ipaddr.js")。而如下代码所示，DefaultJSModuleLoader::Search方法在一次模块查找(SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))方法后，在接下来的文件夹向上查找过程中，做了判断，忽略了引用模块后缀为".js"和".mjs"，同时也忽略了模块内部有"/"符号的查找。同时在向上查找过程中，忽略对node_modules文件夹进行查找。之后就直接在Content路径下进行查找了。在删除掉相关忽略以后，express成功引入，并且使用正常。
> > ### 疑问和请教
> > 想请教一下，是出于什么考虑，加入了上面所述".js"、".mjs"文件和"node_modules"文件夹的忽略。
> > ### 相关代码（由于没找到Issue直接引用仓库代码，所以就直接手贴到这里了）
> > 文件路径：https://github.com/Tencent/puerts/tree/master/unreal/Puerts/Source/JsEnv/Private/DefaultJSModuleLoader.cpp
> > ```
> > bool DefaultJSModuleLoader::Search(const FString& RequiredDir, const FString& RequiredModule, FString& Path, FString& AbsolutePath)
> > {
> >     if (SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))
> >     {
> >         return true;
> >     }
> >     if (RequiredDir != TEXT("") && !RequiredModule.GetCharArray().Contains('/') && !RequiredModule.EndsWith(TEXT(".js")) &&
> >         !RequiredModule.EndsWith(TEXT(".mjs")))
> >     {
> >         // 调用require的文件所在的目录往上找
> >         TArray<FString> pathFrags;
> >         RequiredDir.ParseIntoArray(pathFrags, TEXT("/"));
> >         pathFrags.Pop();    // has try in "if (SearchModuleInDir(RequiredDir, RequiredModule, Path, AbsolutePath))"
> >         while (pathFrags.Num() > 0)
> >         {
> >             if (!pathFrags.Last().Equals(TEXT("node_modules")))
> >             {
> >                 if (SearchModuleInDir(FString::Join(pathFrags, TEXT("/")), RequiredModule, Path, AbsolutePath))
> >                 {
> >                     return true;
> >                 }
> >             }
> >             pathFrags.Pop();
> >         }
> >     }
> > 
> >     return SearchModuleInDir(FPaths::ProjectContentDir() / ScriptRoot, RequiredModule, Path, AbsolutePath) ||
> >            (ScriptRoot != TEXT("JavaScript") &&
> >                SearchModuleInDir(FPaths::ProjectContentDir() / TEXT("JavaScript"), RequiredModule, Path, AbsolutePath));
> > }
> > ```
> 
> 你的Puerts是哪一个版本的？我还没试过express，但react16里面有 `require('prop-types/checkProp')`, 同样是"/"分隔的，react16我在npm下似乎可以正常引入。pnpm子项目下不行，原因应该有因为被强行跳过"node_modules"

master分支，如果说版本的话，应该是Unreal1.0.4这个Release。可能是个别库的声明方式不同导致。

**Comment by joelyang0215** [comment]
> 要杜绝这类问题，得等这个feature完成：#1248

看了一下feature，目前大概了解了。感谢大佬的辛苦工作~希望项目越来越好~

**Comment by chexiongsheng** [comment]
之前预计要对JSModuleLoader重构，所有没太仔细看详细问题，我今天准备评估要不要实施重构，发现你这问题其实早解决了的，比如ipaddr.js在这里：https://github.com/Tencent/puerts/commit/5ad19653d350eec8311b6fc79030820fe7b5f061，我试了下express加载运行都很正常。是不是你的puerts版本太古老导致的？
