### ISSUE TITLE
[Unity] Bug: webgl打包后调用Raycast会报invalid arguments to Raycast

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1408]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0.pre5

### Unity的版本 | Unity Version

2022.3.0

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

![image](https://github.com/Tencent/puerts/assets/3063621/09fc680a-3a95-494b-842d-89e44fb589ba)

### 问题重现 | Bug reproduce

const hitInfo = puer.$ref();
CS.UnityEngine.Physics.Raycast(new CS.UnityEngine.Vector3(), CS.UnityEngine.Vector3.down, hitInfo);

这是调用代码，打包后运行就报错

**Comment by zombieyang** [comment]
应该是Vector3的无参构造函数被裁剪了，看下link.xml是否正确生成了

**Comment by zombieyang** [comment]
是new vector3导致的

TODO:
xil2cpp版本要补充结构体无参构造函数的调用逻辑

**Comment by zombieyang** [comment]
看错了，你说的是webgl。
已修复
