### ISSUE TITLE
有人尝试过使用puerts在c++独立应用中吗？不用unity不用unreal?

### ISSUE THREAD

**Issue by uniqss** [Tencent/puerts#141]
如题，我尝试像使用lua一样在独立的c++应用中使用puerts。有没有人做过这个尝试？我是第一个吃螃蟹的吗？如果有朋友尝试过的话麻烦给个链接，谢谢了！如果没有我单开一个repository吧。

**Comment by xosuperpig** [comment]
那和你直接用v8有什么区别

**Comment by Joycraft** [comment]
自带功能, 本来就支持, 你去读一下JsEnv就知道了

**Comment by Joycraft** [comment]
比V8多了一个绑定类的功能吧

**Comment by chexiongsheng** [comment]
c++不支持。
c#可以支持。
虽说unreal版本的宿主语言是C++，但强依赖于unreal的反射及gc，不能剥离使用。但市面上应该有v8 for c++ binding可用。

**Comment by uniqss** [comment]
好的，谢谢诸位！我只看到一个v8pp，也不好用。有其他v8 for c++ binding 好用的吗？V8实在太重度，跟个巨型坦克一样，光开动一下就要烧一吨油。

**Comment by chexiongsheng** [comment]
我们公司刚开源了一个：https://github.com/Tencent/ScriptX

**Comment by uniqss** [comment]
Thanks very much! I will try.

**Comment by HuShanjun** [comment]
> 如题，我尝试像使用lua一样在独立的c++应用中使用puerts。有没有人做过这个尝试？我是第一个吃螃蟹的吗？如果有朋友尝试过的话麻烦给个链接，谢谢了！如果没有我单开一个repository吧。

xscript 可以试试支持js ts lua
