### ISSUE TITLE
[UE] Bug: ue.d.ts文件过大时候，生成头文件崩溃

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1410]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

头文件生成成功了，但是在onSourceFileAddOrChange中崩溃了，定位到崩溃点是 program.getSemanticDiagnostics(sourceFile)方法，崩溃在v8里了
![image](https://github.com/Tencent/puerts/assets/5946974/8cc2e9f3-7058-4440-a454-524dc1a2f7f9)
![image](https://github.com/Tencent/puerts/assets/5946974/e2ab6e65-76fb-432a-9991-19d5a641515d)

### 问题重现 | Bug reproduce

原因是v8的堆内存不足，64位系统v8的默认堆内存只有1448Mb,调用 CreateParams.constraints.set_max_old_space_size(4096);重新设置堆内存后，可以正常生成。如果这个堆内存开一个参数会不会好一点？让编辑器和继承引擎类这种不同的v8实例可以分开设置
![image](https://github.com/Tencent/puerts/assets/5946974/760f6667-29fd-420f-a7a5-b6e5b2782170)
![image](https://github.com/Tencent/puerts/assets/5946974/5d0c0fc6-2e71-4342-bac2-9d8e370757f9)

提高内存后
![image](https://github.com/Tencent/puerts/assets/5946974/3bc0c950-4a57-4cb7-91f7-c35dab6ecf3d)

**Comment by chexiongsheng** [comment]
可以加个配置，然后PuertsEditor开的虚拟机可以设置大些
