### ISSUE TITLE
[UE] 静态绑定和扩展函数不能同时生效

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1413]
## detail | 详细描述
如题： 目前扩展函数和静态绑定扩展的接口并没有都添加到对应的类里面

**Comment by chexiongsheng** [comment]
可能你写错了吧，好些基本方法都是通过静态绑定加入的：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/Ext/UEExtension.cpp

有静态绑定应该不需要用到扩展函数了。也不建议用扩展函数

**Comment by ljporljp** [comment]
没写错，但又可以生成了。close
