### ISSUE TITLE
[Unity] Bug: 在IL2CPP构建中非静态GenericMethod不起作用( Non-Static GenericMethod Doesn't Work in IL2CPP Build)

### ISSUE THREAD

**Issue by danij91** [Tencent/puerts#1417]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

v2.0.0-pre.4,ApiLevel:31

### Unity的版本 | Unity Version

2021.3.17f

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

WindowsPlayer "MY_WINDOW_ID" puer.getGenericMethod not found Transform GetComponent Animation
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Run:Start()
------------------------------------
WindowsPlayer "MY_WINDOW_ID" InvalidOperationException: chunk:3: TypeError: Cannot read properties of null (reading 'call')

TypeError: Cannot read properties of null (reading 'call')
    at chunk:3:34
  at Run.Start () [0x00000] in <00000000000000000000000000000000>:0 

### 问题重现 | Bug reproduce

1. 在资源目录中创建 **generic.mjs** 文件( Create generic.mjs in the Resources directory):
```
(function(transform){
    let GetComponent= puer.$genericMethod(CS.UnityEngine.Transform, "GetComponent", CS.UnityEngine.Animation)
    var animation = GetComponent.call(transform);
    console.log(animation);
});
```
2. 编写 **Run.cs** 来运行 **generic.mjs**(Write **Run.cs** to run **generic.mjs**) :
```
using System;
using System.Collections;
using System.Collections.Generic;
using Puerts;
using UnityEngine;

public class Run : MonoBehaviour
{
    private void Start()
    {
        var env = new JsEnv();
        var jscode = Resources.Load<TextAsset>("generic").text;
        var act = env.Eval<Action<Transform>>(jscode);
        act(this.transform);
    }
}
```
3. 使用 **IL2CPP** 脚本后端进行构建 (Build with **IL2CPP** scripting backend.)
4. 结果(Result):
这些代码在编辑器（**Mono**）中工作正常，但在 **IL2CPP** 构建中无法工作。我还测试了静态泛型方法，它能正常工作。
(These codes work well in the Editor (**Mono**), but they don't work in the **IL2CPP** build. I also tested a static generic method, and it works well.)

**Comment by zombieyang** [comment]
First, I suggest you to use `public Component GetComponent(Type type);` instead of `public T GetComponent<T>();`, because the cost of 'makeGenericMethod' is higher.

https://docs.unity3d.com/ScriptReference/Component.GetComponent.html

------
And I will check this bug later.

**Comment by danij91** [comment]
@zombieyang In my experiments with the GenericMethod, I encountered a problem where a class instance that inherits from a parent class doesn't execute the GenericMethod as intended. To make it clearer, imagine we have a class A, which is a parent class having a public GenericMethod named "Test". We also have a class B, which is a child class that inherits from this parent class, Class A. Using the Test method through an instance of Class A in xil2cpp mode works flawlessly. However, trying to use the Test method through an instance of Class B in the same mode results in an error. Unsurprisingly, both classes operate correctly in mono mode.

**Comment by zombieyang** [comment]
Sorry for my late, I busy for an another work in last weeks.

And yes, you are right! That is the reason which cause this issue, thank you!
