### ISSUE TITLE
[UE] Bug: 无法定位程序输入点 Cr_z_compressBound 于动态链接库 \Plugins\Puerts\Binaries\Win64\v8.dll 上。

### ISSUE THREAD

**Issue by xxbld** [Tencent/puerts#1418]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.04  puerts_v8_84(94)

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

---------------------------
UnrealEditor.exe - 无法找到入口
---------------------------
无法定位程序输入点 Cr_z_compressBound 于动态链接库 \UEProject\Plugins\Puerts\Binaries\Win64\v8.dll 上。 
---------------------------

### 问题重现 | Bug reproduce

解压puerts_v8_84(94)到一个新建项目中 puerts插件加载失败保持

**Comment by chexiongsheng** [comment]
\UEProject\Plugins\Puerts\Binaries\Win64\下看看有没zlib.dll

**Comment by xxbld** [comment]
> \UEProject\Plugins\Puerts\Binaries\Win64\下看看有没zlib.dll
没有

**Comment by xxbld** [comment]
> \UEProject\Plugins\Puerts\Binaries\Win64\下看看有没zlib.dll

有的

**Comment by chexiongsheng** [comment]
那估计冲突了，应该是你有另外一个插件也用了zlib.dll，但它是另外一版本的（那版本没有Cr_z_compressBound ），比puerts插件先加载，所以先加载了它那版本的zlib.dll。
这就是window传说中的dll地狱了。

**Comment by chexiongsheng** [comment]
你可以找下这个用zlib.dll的地方。

**Comment by xxbld** [comment]
确实 我把另一个库移除就可以了，这两个一起运行有办法解决吗？ @chexiongsheng

**Comment by chexiongsheng** [comment]
> 确实 我把另一个库移除就可以了，这两个一起运行有办法解决吗？ @chexiongsheng

另外一个库是啥呢？
这种只能是其中一个升级或者降级，保持一致。

**Comment by xxbld** [comment]
商场里的，没有源码

**Comment by chexiongsheng** [comment]
最新版的zlib是有compressBound的，也就是你那插件用的版本太老了。你可以尝试升级下，找到那个插件目录下的zlib.dll，用puerts的zlib.dll覆盖过去。

**Comment by chexiongsheng** [comment]
> 商场里的，没有源码

你可以说下插件名，后面有碰到的童靴可以搜索到。

**Comment by xxbld** [comment]
Landscaping
