### ISSUE TITLE
存在或者之后会开发C# 调用JS的接口吗？

### ISSUE THREAD

**Issue by JowieXiang** [Tencent/puerts#142]
库非常棒！个人项目想试着实现像react native一样的JS和原生数据的双向绑定，目前puerts好像只支持JS向C#方向的，反过来可以支持吗？或者之后有计划开发这方面的接口吗？
感谢！

**Comment by Joycraft** [comment]
Unity Demo [07_JsObjectAccess]  有这个 c# get/set => js 的功能示例

**Comment by JowieXiang** [comment]
太棒了！多谢！
