### ISSUE TITLE
[UE] Bug: not support kind

### ISSUE THREAD

**Issue by qssq1** [Tencent/puerts#1420]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

new

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

![0NL`)GCESRDZ}BTSDR 3R1P](https://github.com/Tencent/puerts/assets/14260426/b51ddff4-439a-4cec-8b82-976a9454859e)

### 问题重现 | Bug reproduce

见上图，给继承类设置参数为字体信息，提示不支持，我删掉字体参数就没有警告

**Comment by chexiongsheng** [comment]
你参数2写类型了么？
