### ISSUE TITLE
[Unity] Bug: 

### ISSUE THREAD

**Issue by k569462166** [Tencent/puerts#1422]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

     "com.tencent.puerts.core": "2.0pre4",

### Unity的版本 | Unity Version

2021

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

BlittableCopy开启vector3优化时，不能访问vector3的成员xyz

### 问题重现 | Bug reproduce

    [BlittableCopy]
    static IEnumerable<Type> Blittables
    {
        get
        {
            return new List<Type>()
            {
                //打开这个可以优化Vector3的GC，但需要开启unsafe编译
                // typeof(Vector3),
            };
        }
    }

**Comment by zombieyang** [comment]
fixed in 7ffb2f42194501a0644430a7aa547abef146bcb9
