### ISSUE TITLE
[Unity] suggestion 希望能在代码中卸载已require的指定文件

### ISSUE THREAD

**Issue by ankisme** [Tencent/puerts#1424]
## detail | 详细描述

情况是这样的

我们项目把大量的数据文件都作为.js，然后使用require来动态按需加载js文件

比如，玩家进入地图1，则require(地图1的.js文件)

玩家进入地图2，则require(地图2的.js文件)

然后问题来了，当玩家进入地图2时，则(地图1的.js文件)不需要了，可以卸载了，但puerts似乎没提供这样的方法

所以(地图1的.js文件)会一直留在内存中，无法释放

用chrome查看内存，也发现这些.js代码占用了挺多内存的

把数据清空是没有这种效果的，因为是代码资源占了内存

```ts
加载的代码
function Load() {
	const r = require(`./想要加载的数据文件`)
	eval(`r.加载函数()`)
}
```

**Comment by zombieyang** [comment]
有的呀，clearModuleCache

ExecuteModule的话可以直接用`jsEnv.ClearModuleCache(name)`

**Comment by ankisme** [comment]
> 是有的。clearModuleCache
> 
> ExecuteModule的话可以直接用`jsEnv.ClearModuleCache(name)`

好的，我试试
