### ISSUE TITLE
[Unity] Bug: TypeError: pair.Key.GetFriendlyName is not a function

### ISSUE THREAD

**Issue by EverydayDevup** [Tencent/puerts#1437]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

master d6579c1c87fbc95c09674846430abd8e515b6a24

### Unity的版本 | Unity Version

2021.3.17f1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

Exception: puerts/templates/extension_methods_gen.tpl.mjs:51: TypeError: pair.Key.GetFriendlyName is not a function

TypeError: pair.Key.GetFriendlyName is not a function
    at getExtendedTypeToExtensionTypeInfo (puerts/templates/extension_methods_gen.tpl.mjs:51:37)
    at TypingTemplate (puerts/templates/extension_methods_gen.tpl.mjs:22:28)
Puerts.GenericDelegate.Func[T1,TResult] (T1 p1) (at 

### 问题重现 | Bug reproduce

    [Binding]
    public static List<Type> binding {
        get {
            return new List<Type>{
                typeof(System.Type),
                typeof(UnityEngine.Renderer),
                typeof(UnityEngine.RendererExtensions)
            };
        }
    }
    
    [Filter]
    static bool FilterMethods(MemberInfo memberInfo)
    {
        // Assets\Gen\System_Type_Wrap.cs(2551,50): error CS0117: 'Type' does not contain a definition for 'MakeGenericSignatureType'
        if (memberInfo.DeclaringType.ToString() == "System.Type" && memberInfo.Name == "MakeGenericSignatureType")
        {
            return true;
        }

        if (memberInfo.DeclaringType.ToString() == "System.Type" && memberInfo.Name == "IsCollectible")
        {
            return true;
        }

        return false;
    }

If you set the type as above, an error error occurs when you create ExtensionMethodInfo once every two times.

As expected, it seems that in some cases the TypeExtension.GetFriendlyName function is not registered as an extension method on the JsEnv Type when the System.Type is created.

==================================================================================

如果按照上面的方式设置类型，则每两次创建ExtensionMethodInfo时就会出现error错误。

正如预期的那样，在某些情况下，创建 System.Type 时，TypeExtension.GetFriendlyName 函数似乎没有注册为 JsEnv Type 上的扩展方法。

**Comment by zombieyang** [comment]
I can't reproduce this bug. What is your script definitions?

Could you try to change that line of code to [invoke GetFriendlyName like this way](https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Editor/Resources/puerts/templates/registerinfo.tpl.mjs#L50) and try again?

**Comment by EverydayDevup** [comment]
GetFriendlyName does not exist in the type created in RegisterInfo_Gen.

jsEnv.AddRegisterInfoGetter(typeof(${CS.Puerts.TypeExtensions.GetFriendlyName(item.Type)}), GetRegisterInfo_${item.WrapperName});`

The code is in registerinfo.tpl.mjs, but the same happens.

// Scripting Defint Symbol
// Only one define is set.
- EXPERIMENTAL_IL2CPP_PUERTS

**Comment by zombieyang** [comment]
still not able to reproduce. you can try to merge the change of 6c22bf4

**Comment by EverydayDevup** [comment]
https://github.com/Tencent/puerts/commit/6c22bf42d2a673acd8f76f4191c2085b66f72b0e 
It was resolved when I merged that commit.
