### ISSUE TITLE
[Unity] Bug: v2.0.0-rc.1 VSCode无法调试

### ISSUE THREAD

**Issue by xtutu** [Tencent/puerts#1440]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

v2.0.0-rc.1

### Unity的版本 | Unity Version

2022.3.3

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

在 puerts 1.4 里面，jsloader 返回是全路径。 
在 devtool 里看，也是全路径
vscode 可以调试

---
在 puerts 2.0 里面，jsloader 返回的 是全路径。 
但是在 devtool 里变成相对路径了。
vscode 无法调试

### 问题重现 | Bug reproduce

必现

**Comment by zombieyang** [comment]
[c441e24](https://github.com/Tencent/puerts/commit/c441e24d7b1435228c33f32fddced5da468b5d9a)
