### ISSUE TITLE
[Unity]BlittableCopy - il2cpp 

### ISSUE THREAD

**Issue by danij91** [Tencent/puerts#1441]
## detail | 详细描述
hello! 
Does blittableCopy mean anything to il2cpp?
If not, is there no need to set blittableCopy attribute to configure file when using il2cpp?

"blittableCopy"对于il2cpp有什么意义吗？
如果没有的话，在使用il2cpp时是否不需要设置blittableCopy属性到配置文件中？

**Comment by zombieyang** [comment]
Do you mean xil2cpp mode? Or just Unity il2cpp.
In Unity il2cpp, BlittableCopy does have meaning that it can decrease GC.
In xil2cpp, it does not mean anything, so I wrapped that field with a ScriptDefinition.
![image](https://github.com/Tencent/puerts/assets/5595819/4849b56b-2467-4dbf-be5d-d2fa1e278a0e)
