### ISSUE TITLE
[UE] Bug: ts多层继承会导致引用关系错误

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#1443]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

class A extends UE.Actor {
test: number;
}

class B extends A {
Mesh: StaticMeshComponent;
}

然后手动新建一个蓝图C 继承自B生成的蓝图，则会导致C直接引用A生成的蓝图和B生成的蓝图，但C在逻辑关系上不应该对A生成的蓝图有引用。

### 问题重现 | Bug reproduce

如上

**Comment by ljporljp** [comment]
> 

用UE的引用查看器看到的引用关系。如果都是手动建的蓝图，正常的继承链不会出现这种情况。

**Comment by chexiongsheng** [comment]
应该是这里导致的引用：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Public/TypeScriptGeneratedClass.h#L44

内部项目提交的一个优化，用于加速编辑下第二次Play的速度，仅编辑器有效

**Comment by ljporljp** [comment]
soga，表现有点奇怪，这个导致显示的还是硬引用
