### ISSUE TITLE
[UE] Bug: mixin 中 objectTakeByNative = true , ts 的持有依然阻止了 UE 的 GC .

### ISSUE THREAD

**Issue by Mortal111121111** [Tencent/puerts#1445]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.4

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

1. 从 Puerts 代码上看在 mixin 函数的 4106 行中，根据 objectTakeByNative 的值将 StructWrapper->IsNativeTakeJsRef 的值设置为 true 从而不让其加入 UserObjectRetainer 中。但是在 mixin 之前如果改类已经在 UserObjectRetainer 中( 比如我得在 mixin 之前进行一次 Class.Load ) 此时好像就无法阻止 UE 的 GC 了，mixin 中好像也并未做 UserObjectRetainer.Release 的操作。

2. 比如我要 mixin 的是一个 UMG ,  objectTakeByNative 同样给 true 。UMG 中的其他控件如 button 在触发 Getter 时也会将自己加入到 UserObjectRetainer ，从而导致 UE GC 的失效 

### 问题重现 | Bug reproduce

![20230721-162759](https://github.com/Tencent/puerts/assets/61452152/b98bf5e3-2483-4295-b3c9-fdd25201c5da)

**Comment by chexiongsheng** [comment]
在设置前构造的对象按之前的设置貌似也是合理的。

**Comment by Mortal111121111** [comment]
> 

您的意思是，那个对象在之前就加入了 UserObjectRetainer 里，之后再将 StructWrapper->IsNativeTakeJsRef 改为 True 是合理的吗？

**Comment by Mortal111121111** [comment]
> 在设置前构造的对象按之前的设置貌似也是合理的。

您的意思是，那个对象在之前就加入了 UserObjectRetainer 里，之后再将 StructWrapper->IsNativeTakeJsRef 改为 True 是合理的吗？

**Comment by chexiongsheng** [comment]
你执行mixin时传入的objectTakeByNative 只对此后对象生效，执行mixin之前的对象不生效是合理的

**Comment by Mortal111121111** [comment]
> 你执行mixin时传入的objectTakeByNative 只对此后对象生效，执行mixin之前的对象不生效是合理的

那之前的对象如果 v8 不 GC 对应的 Js 对象，UE 这边不就内存泄漏了吗。而且我试了一下 mixin 之后的对象，还是阻止了 UE 的GC
![img_v2_9b2d5bfb-bf0e-49c5-b880-7f3711b00fbg](https://github.com/Tencent/puerts/assets/61452152/d5867cd2-045b-45be-b2af-2d3d3730c5bf)

**Comment by Mortal111121111** [comment]
> mixin 之后new 的对象么？这种应该生效啊，设置后和继承ue类功能是一样的机制。

是的，原因就是对象依然存在 UserObjectRetainer 中，我尝试在 mixin 的函数中调用 UserObjectRetainer.Release() 去将之前的对象清除，就没有这个问题了。但是如果存在 2 中所说的那种情况就还是存在问题

**Comment by chexiongsheng** [comment]
我的意思是设置之前已经存在的对象，按之前的设定是合理。
