### ISSUE TITLE
[UE] Bug: 请教 UE Editor 下触发hotreload时崩溃

### ISSUE THREAD

**Issue by scutDavid** [Tencent/puerts#1452]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

4.24

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

实现方式 参考作者在FPuertsEditorModule::OnPostEngineInit的实现：
![image](https://github.com/Tencent/puerts/assets/30872025/888f7770-9507-4375-80fe-f9879a423f6e)
启动游戏后编译TS，触发热更，然后崩溃，最后的日志显示读取js文件失败
![企业微信截图_16904450172131](https://github.com/Tencent/puerts/assets/30872025/a5369dad-0ce4-4a42-93be-5f6ae8286826)
但又打印了一行reload js 不知道是从哪里触发的？
然后这是堆栈
![image](https://github.com/Tencent/puerts/assets/30872025/b163b7ad-5b24-4f21-b13d-cb08eca7c1cd)
后面是js的堆栈 没法显示。

### 问题重现 | Bug reproduce

修改js后触发热更，大概率复现，非必现

**Comment by chexiongsheng** [comment]
读取文件失败一般文件被锁定有关。
上面reload fail是你c++的打印。
下面的打印代表调用了ReloadSource函数，这是一个函数，有打印只有一个解释是有调用。

**Comment by scutDavid** [comment]
> 读取文件失败一般文件被锁定有关。 上面reload fail是你c++的打印。 下面的打印代表调用了ReloadSource函数，这是一个函数，有打印只有一个解释是有调用。

前面已经读取文件失败了，按道理不会走进ReloadSource，除非是短时间内（100多毫秒后）又触发了热更，并且这次读取文件成功，所以才又走进ReloadSource。自己没弄清为啥会崩，想请教下有什么保护措施吗

**Comment by chexiongsheng** [comment]
我的意思是你说的“除非是短时间内（100多毫秒后）又触发了热更”

live-edit功能是v8自带的，我只是调用接口把代码给v8，看你的崩溃信息是栈溢出了。可能碰到递归死循环了吧。可能你代码某种写法会导致这个功能的bug。

**Comment by scutDavid** [comment]
> 我的意思是你说的“除非是短时间内（100多毫秒后）又触发了热更”
> 
> live-edit功能是v8自带的，我只是调用接口把代码给v8，看你的崩溃信息是栈溢出了。可能碰到递归死循环了吧。可能你代码某种写法会导致这个功能的bug。

好的 我打印下崩溃时js的堆栈 定位下具体代码看下，感谢车神！

**Comment by chexiongsheng** [comment]
你看看是不是OnSourceLoaded回调和ReloadSource这两个在相互递归呢？

**Comment by scutDavid** [comment]
> 你看看是不是OnSourceLoaded回调和ReloadSource这两个在相互递归呢？
应该不是 看C++的堆栈 没有形成这个互相调用
