### ISSUE TITLE
[Unity] Bug: il2cpp DoTween 用dotext如果参数不填满就会闪退

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1456]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0

### Unity的版本 | Unity Version

2022.3.0

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

![image](https://github.com/Tencent/puerts/assets/3063621/b582a0b6-9784-45fc-996d-662fb30e1636)

### 问题重现 | Bug reproduce

this.uiText.DOText('abc', 5); 打包出il2cpp下直接闪退

必须把参数填满才不闪退
this.uiText.DOText('abc, 5, false, CS.DG.Tweening.ScrambleMode.None, '');

**Comment by zombieyang** [comment]
能否贴一份带dotween的demo给我，我对它不是很熟悉。

**Comment by dunadain** [comment]
[TestDoTweenCrash.zip](https://github.com/Tencent/puerts/files/12266254/TestDoTweenCrash.zip)

**Comment by dunadain** [comment]
又发现一个新问题，如果不加PUERTS_CPP_OUTPUT_TO_NATIVE_SRC_UPM, EXPERIMENTAL_IL2CPP_PUERTS 这俩个scripting symbols，这个DoTween在Editor下js无法调用。只要把我给的工程把这俩Symbol去掉就能复现

**Comment by zombieyang** [comment]
> 

如果有definition时生成了wrapper，去掉后要清理掉Gen目录重新生成，两个模式下的RegisterInfo有不一样

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Runtime/Src/Default/TypeMapping/TypeRegister.cs#L440
扩展类和被扩展类必须加入生成来使用，否则应该通过调用puer.$extension来手动扩展。编辑器下其实是不受限制的，但播放状态我也报这个错是担心你们忘了做生成的步骤，以至于打包才出问题

**Comment by zombieyang** [comment]
主楼的问题是扩展函数获取参数默认值时，index值不对（this参数占了一位）。待修复
