### ISSUE TITLE
[UE] Bug: Unreal QuickJs下编译报错。

### ISSUE THREAD

**Issue by iksu** [Tencent/puerts#1457]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.4

### UE的版本 | UE Version

4.27,5.0.3

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	"NewInstance": 不是 "v8::ObjectTemplate" 的成员	h5	K:\ue4\UnrealEngineProject\h5\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp	1730	

### 问题重现 | Bug reproduce

下载https://github.com/Tencent/puerts/releases/tag/Unreal_v1.0.4 的QuickJS版本，
更新backend：https://github.com/puerts/backend-quickjs/releases/tag/QJS_230504
然后启动UE直接报错，使用VS编译也报错。

**Comment by chexiongsheng** [comment]
新增了个v8方法调用，quickjs那没实现，明天加下

**Comment by chexiongsheng** [comment]
更新到最新代码，并且使用这个版本的quickjs：https://github.com/puerts/backend-quickjs/releases/tag/QJS_230804
