### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by chenhaoran10** [Tencent/puerts#1458]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

LoginId:ebe73c8f436e759fc7585a81fa005c7e
EpicAccountId:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

libnode
libnode
libnode
libnode
UnrealEditor_JsEnv!puerts::FJsEnvImpl::BindStruct() [D:\P4NZ\UnrealProject\Nezha\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp:2852]
UnrealEditor_JsEnv!puerts::FJsEnvImpl::FindOrAddStruct() [D:\P4NZ\UnrealProject\Nezha\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp:1825]
UnrealEditor_JsEnv!puerts::FScriptStructPropertyTranslator::UEToJs() [D:\P4NZ\UnrealProject\Nezha\Plugins\Puerts\Source\JsEnv\Private\PropertyTranslator.cpp:680]
UnrealEditor_JsEnv!puerts::FFunctionTranslator::CallJs() [D:\P4NZ\UnrealProject\Nezha\Plugins\Puerts\Source\JsEnv\Private\FunctionTranslator.cpp:626]
UnrealEditor_JsEnv!puerts::FJsEnvImpl::InvokeTsMethod() [D:\P4NZ\UnrealProject\Nezha\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp:2288]
UnrealEditor_JsEnv!UTypeScriptGeneratedClass::execCallJS() [D:\P4NZ\UnrealProject\Nezha\Plugins\Puerts\Source\JsEnv\Private\TypeScriptGeneratedClass.cpp:48]
UnrealEditor_CoreUObject!UFunction::Invoke() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6411]
UnrealEditor_CoreUObject!UObject::ProcessEvent() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2131]
UnrealEditor_Engine!AActor::ProcessEvent() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Engine\Private\Actor.cpp:1065]
UnrealEditor_Nezha!ANzCharacter::EvaluateAction() [D:\P4NZ\UnrealProject\Nezha\Intermediate\Build\Win64\UnrealEditor\Inc\Nezha\UHT\NzCharacter.gen.cpp:277]
UnrealEditor_SignificanceManager!USignificanceManager::FManagedObjectInfo::UpdateSignificance() [D:\P4NZ\UnrealProject\Engine\Plugins\Runtime\SignificanceManager\Source\SignificanceManager\Private\SignificanceManager.cpp:458]
UnrealEditor_SignificanceManager!`ParallelForImpl::ParallelForInternal<TFunctionRef<void __cdecl(int)>,<lambda_600b85aa2a81f4761389a82b02631227>,std::nullptr_t>'::`2'::FParallelExecutor::operator()() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Public\Async\ParallelFor.h:334]
UnrealEditor_SignificanceManager!LowLevelTasks::TTaskDelegate<LowLevelTasks::FTask * __cdecl(bool),48>::TTaskDelegateImpl<<lambda_6270a3d3cb9373e2bb024e43bd799761>,0>::CallAndMove() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Public\Async\Fundamental\TaskDelegate.h:171]
UnrealEditor_Core!LowLevelTasks::FTask::ExecuteTask() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Public\Async\Fundamental\Task.h:627]
UnrealEditor_Core!LowLevelTasks::FScheduler::ExecuteTask() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:150]
UnrealEditor_Core!LowLevelTasks::FScheduler::TryExecuteTaskFrom<LowLevelTasks::TLocalQueueRegistry<1024>::TLocalQueue,&LowLevelTasks::TLocalQueueRegistry<1024>::TLocalQueue::DequeueGlobal,0>() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:350]
UnrealEditor_Core!LowLevelTasks::FScheduler::WorkerMain() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:378]
UnrealEditor_Core!UE::Core::Private::Function::TFunctionRefCaller<<lambda_be2218a0adc66e92e8734764b1b5dd37>,void __cdecl(void)>::Call() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Public\Templates\Function.h:475]
UnrealEditor_Core!FThreadImpl::Run() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Private\HAL\Thread.cpp:67]
UnrealEditor_Core!FRunnableThreadWin::Run() [D:\P4NZ\UnrealProject\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]

### 问题重现 | Bug reproduce

接入了SignificanceManager框架做性能优化，如果尝试在TS中重写打分和具体的优化操作方法，会直接崩溃

**Comment by chexiongsheng** [comment]
你是改了puerts代码？

**Comment by chenhaoran10** [comment]
> 你是改了puerts代码？

项目里确实改了不少，但同事说这个问题是脚本层只能主线程执行什么的，SignificanceManager框架很大部分在异步执行，我把异步执行的步骤移到cpp里解决了

**Comment by chexiongsheng** [comment]
> > 你是改了puerts代码？
> 
> 项目里确实改了不少，但同事说这个问题是脚本层只能主线程执行什么的，SignificanceManager框架很大部分在异步执行，我把异步执行的步骤移到cpp里解决了

脚本引擎一般都不线程安全。换句话只能一个线程访问（倒不一定是主线程）。
有个THREAD_SAFE宏，加了可以多线程访问，但会降低性能，而且在ue异步加载场景可能导致死锁。
