### ISSUE TITLE
[Unity] Bug: webgl build error.

### ISSUE THREAD

**Issue by HiEdison** [Tencent/puerts#1459]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.0

### Unity的版本 | Unity Version

unity 2022.1.16f1c1

### 发生在哪个平台 | Platform

Editor(windows 11，webgl)

### 错误信息 | Error Message

Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: undefined symbol: ClearModuleCache (referenced by top-level compiled C/C++ code)
Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: undefined symbol: CreateInspector (referenced by top-level compiled C/C++ code)
Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: undefined symbol: CreateInspector (referenced by top-level compiled C/C++ code)

### 问题重现 | Bug reproduce

webgl 平台点击build后出现 大量错误，解决90条，我提交的是其中三条.
其中windows 打包没问题。 
难道是不支持webgl 吗？

**Comment by zombieyang** [comment]
我一直是主要用mac，不会有问题的。确认用了webgl包了吗？
报这两个错的话就是.jslib里找不到对应函数

**Comment by HiEdison** [comment]
感谢你的回答，我找到问题了，是我没看到webgl 支持页面，一致以为是全平台，不需要额外导入webgl.
我使用了链接中的方式，打包成功.  谢谢
https://openupm.com/packages/com.tencent.puerts.webgl/#modal-manualinstallation

**Comment by zombieyang** [comment]
牛逼！
