### ISSUE TITLE
[Unity][Bug] $typeof 获取 class类型错误

### ISSUE THREAD

**Issue by UpUpLiu** [Tencent/puerts#146]
Unity版本: 2019.4.15
Puerts版本: 使用example的版本 可以重现

重现脚本:
``

using UnityEngine;
using Puerts;

namespace PuertsTest
{
    public class BaseClass : MonoBehaviour
    {
        public void Awake()
        {
            Debug.LogError("BaseClass");
        }
    }
    
    public class BaseClass2 : BaseClass
    {
        public void Awake()
        {
            Debug.LogError("BaseClass2");
        }
    }

    public class JsCallCs : MonoBehaviour
    {
        JsEnv jsEnv;

        void Start()
        {
            jsEnv = new JsEnv();

            jsEnv.Eval(@"
            const csharp_1 = require('csharp');
            const puerts_1 = require('puerts');
            let go1 = new csharp_1.UnityEngine.GameObject('testObject2');
            go1.AddComponent(puerts_1.$typeof(csharp_1.PuertsTest.BaseClass));
            let go2 = new csharp_1.UnityEngine.GameObject('testObject3');
            // @ts-ignore
            go2.AddComponent(puerts_1.$typeof(csharp_1.PuertsTest.BaseClass2));
            ");
        }

        void OnDestroy()
        {
            jsEnv.Dispose();
        }
    }
}

``

正常应该输出:
BaseClass
BaseClass2

实际输出:
BaseClass
BaseClass

提议: 
可以给puerts加一个按钮菜单用于输出puerts当前版本 用于报bug, 或者检查是否版本太老导致的bug

**Comment by goodzsq** [comment]
我也遇到这个问题了
但是如果先AddComponent(子类) 后AddComponent(父类) 又正常了
