### ISSUE TITLE
[Unity] Bug: il2cpp bug using struct valueType & $unref 

### ISSUE THREAD

**Issue by gooooodday** [Tencent/puerts#1460]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0

### Unity的版本 | Unity Version

2021.3.17f1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

1. struct value is not equal in li2cpp build

The value of the constant field of the ParticleSystem's emission.rateOverTime is different.
In the editor, it is output as 10, but in li2cpp build value is undefined.

Error: 
System.InvalidOperationException: undefined:9: TypeError: Cannot read properties of undefined (reading 'constant')
TypeError: Cannot read properties of undefined (reading 'constant')
    at Struct.Start (eval at executeModule (puer-commonjs/modular.mjs:35:24), <anonymous>:9:65)

2. = this.w.GetGroundHit(refHit) is not working. ( player crashed )

In the editor, it is working well but it cause crash in li2cpp build.
Probably something similar to that issue **https://github.com/Tencent/puerts/issues/1455**

### 问题重现 | Bug reproduce

1. screenshot & code

example code is here.
```
import TMP_Text = CS.TMPro.TMP_Text;
import ParticleSystem = CS.UnityEngine.ParticleSystem;
//...
    public particle : ParticleSystem;
    public text:TMP_Text;
    
    Start()
    {
        this.text.text = `${this.particle.emission.rateOverTime.constant}`;
    }
```

2.screenshot & code

```
import WheelCollider = CS.UnityEngine.WheelCollider;
import $ref = puer.$ref;
import WheelHit = CS.UnityEngine.WheelHit;
import $unref = puer.$unref;
//...
    public w:WheelCollider;

    Update()
    {
        let verticalInput = Input.GetAxis("Vertical");
        let horizontalInput = Input.GetAxis("Horizontal");

        this.w.motorTorque = verticalInput * 500;
        this.w.steerAngle = horizontalInput * 30;
        
        const refHit = $ref<WheelHit>();
        
        if (this.w.GetGroundHit(refHit))
        {
            const unRef = $unref<WheelHit>(refHit);
            
            console.log(unRef);
        }
    }
```

**Comment by zombieyang** [comment]
is it works well in non-xil2cpp build?

**Comment by gooooodday** [comment]
yes. it is works well in non-xil2cpp build.

**Comment by zombieyang** [comment]
The first problem is because `UnityEngine.ParticleSystem+MinMaxCurve` got stripped. You can put it into the binding list and we will mark it in `link.xml` after c9dcaff
