### ISSUE TITLE
[Unity] Bug: xIl2cpp模式 android 打包如果有armeabi-v7a会报链接错误undefined reference to 'sigemptyset'

### ISSUE THREAD

**Issue by huntwx** [Tencent/puerts#1469]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

Unity_v2.0.0

### Unity的版本 | Unity Version

2019.4.39f1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

Android\libs\armeabi-v7a\libwee8.a(sampler.o):function v8::sampler::SignalHandler::IncreaseSamplerCount(): error: undefined reference to 'sigemptyset'
Android\libs\armeabi-v7a\libwee8.a(stack_trace_android.o):function v8::base::debug::EnableInProcessStackDumping(): error: undefined reference to 'sigemptyset'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation
只保留arm64-v8a能正常打包

### 问题重现 | Bug reproduce

unity android打包

**Comment by huntwx** [comment]
将sdk minimum api level改成了21， target api level也是选择了最高的sdk版本，依然会出现链接错误的问题。

**Comment by zombieyang** [comment]
2019和2020都复现了该问题，这两个版本的unity使用的都是ndk19。2021升级到了ndk21
https://docs.unity3d.com/2020.3/Documentation/Manual/android-sdksetup.html

v8_9.4编译使用的ndk是23
https://chromium.googlesource.com/android_ndk.git/+/8388a2be5421311dc75c5f937aae13d821a27f3d/source.properties

**Comment by chexiongsheng** [comment]
> mark: 2019和2020都复现了该问题，这两个版本的unity使用的都是ndk19。2021升级到了ndk21，没有该问题 https://docs.unity3d.com/2020.3/Documentation/Manual/android-sdksetup.html
> 
> v8_9.4编译使用的ndk是23 https://chromium.googlesource.com/android_ndk.git/+/8388a2be5421311dc75c5f937aae13d821a27f3d/source.properties

v8 8.4呢？

**Comment by zombieyang** [comment]
> > mark: 2019和2020都复现了该问题，这两个版本的unity使用的都是ndk19。2021升级到了ndk21，没有该问题 https://docs.unity3d.com/2020.3/Documentation/Manual/android-sdksetup.html
> > v8_9.4编译使用的ndk是23 https://chromium.googlesource.com/android_ndk.git/+/8388a2be5421311dc75c5f937aae13d821a27f3d/source.properties
> 
> v8 8.4呢？

没试过用8.4编xil2cpp模式，迟点试试
