### ISSUE TITLE
[UE] Bug: building for macOS-arm64 but attempting to link with file built for macOS-x86_64

### ISSUE THREAD

**Issue by ChenRenault** [Tencent/puerts#1471]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.4

### UE的版本 | UE Version

UE5.2

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message
0>ld: Warning : ignoring file /Users/test/TestProject/Plugins/Puerts/ThirdParty/v8/Lib/macOSdylib/libchrome_zlib.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
0>ld: Warning : ignoring file /Users/test/TestProject/Plugins/Puerts/ThirdParty/v8/Lib/macOSdylib/libv8_libplatform.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
0>ld: Warning : ignoring file /Users/test/TestProject/Plugins/Puerts/ThirdParty/v8/Lib/macOSdylib/libv8.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
0>ld: Warning : ignoring file /Users/test/TestProject/Plugins/Puerts/ThirdParty/v8/Lib/macOSdylib/libv8_libbase.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
0>Undefined symbols for architecture arm64:
0> "v8_inspector::V8Inspector::create(v8::Isolate*, v8_inspector::V8InspectorClient*)", referenced from:
0> puerts::V8InspectorClientImpl::V8InspectorClientImpl(int, v8::Localv8::Context) in Module.JsEnv.3_of_3.cpp.o
0> "v8::StackTrace::CurrentStackTrace(v8::Isolate*, int, v8::StackTrace::StackTraceOptions)", referenced from:
0> puerts::FJsEnvImpl::CurrentStackTrace() in Module.JsEnv.2_of_3.cpp.o
0> "v8::ArrayBuffer::New(v8::Isolate*, unsigned long)", referenced from:
0> puerts::FNameToArrayBuffer(v8::FunctionCallbackInfov8::Value const&) in Module.JsEnv.2_of_3.cpp.o
0> puerts::ToCString(v8::FunctionCallbackInfov8::Value const&) in Module.JsEnv.2_of_3.cpp.o
0> puerts::ToCPtrArray(v8::FunctionCallbackInfov8::Value const&) in Module.JsEnv.2_of_3.cpp.o
0> puerts::FArrayBufferPropertyTranslator::UEToJs(v8::Isolate*, v8::Localv8::Context&, void const*, bool) const in Module.JsEnv.3_of_3.cpp.o
0> puerts::FArrayBufferValuePropertyTranslator::UEToJs(v8::Isolate*, v8::Localv8::Context&, void const*, bool) const in Module.JsEnv.3_of_3.cpp.o
0> "v8::ArrayBuffer::Allocator::NewDefaultAllocator()", referenced from:
0> puerts::FJsEnvImpl::FJsEnvImpl(std::__1::shared_ptrpuerts::IJSModuleLoader, std::__1::shared_ptrpuerts::ILogger, int, std::__1::function<void (FString const&)>, FString, void*, void*) in Module.JsEnv.2_of_3.cpp.o
0> "v8::HandleScope::CreateHandle(v8::internal::Isolate*, unsigned long)", referenced from:
0> puerts::FCppObjectMapper::GetTemplateOfClass(v8::Isolate*, puerts::JSClassDefinition const*) in Module.JsEnv.1_of_3.cpp.o
0> puerts::FCppObjectMapper::FindOrAddCppObject(v8::Isolate*, v8::Localv8::Context&, void const*, void*, bool) in Module.JsEnv.1_of_3.cpp.o
0> FJsObject::operator=(FJsObject const&) in Module.JsEnv.1_of_3.cpp.o
0> void puerts::PromiseRejectCallbackpuerts::FJsEnvImpl(v8::PromiseRejectMessage) in Module.JsEnv.2_of_3.cpp.o
0> puerts::FJsEnvImpl::ExecuteModule(FString const&, std::__1::function<FString (FString const&, FString const&)>) in Module.JsEnv.2_of_3.cpp.o
0> puerts::FJsEnvImpl::CheckDelegateProxies(float) in Module.JsEnv.2_of_3.cpp.o
0> puerts::FJsEnvImpl::MakeSureInject(UTypeScriptGeneratedClass*, bool, bool) in Module.JsEnv.2_of_3.cpp.o
0> ...

### 问题重现 | Bug reproduce

在上诉环境Mac M1，编译连接时报错

原因是加载的地址是ThirdParty/v8/Lib/macOSdylib（里面的架构是x86_64)

本地尝试的解决方法：
**ThirdParty/v8/Lib/macOSdylib**    改名为    **ThirdParty/v8/Lib/macOSdylib_x86_64**, 
**ThirdParty/v8/Lib/macOSArm64dylib**    复制一份并改名为    **ThirdParty/v8/Lib/macOSdylib**
![image](https://github.com/Tencent/puerts/assets/8744395/c73855f1-de57-4b16-be98-ac47b977d262)
![image](https://github.com/Tencent/puerts/assets/8744395/17ca07ef-72a1-4fc3-a57d-7eeb5906850f)
静态库（ThirdParty/v8/Lib/macOS）也需要做类似处理
**ThirdParty/v8/Lib/macOS**    改名为    **ThirdParty/v8/Lib/macOS_x86_64**, 
**ThirdParty/v8/Lib/macOS_arm64**    复制一份并改名为    **ThirdParty/v8/Lib/macOS**

这样能编译成功，但是会在启动时崩溃
![image](https://github.com/Tencent/puerts/assets/8744395/71941453-1f48-40d4-b2ba-9f1ed561b081)

原因是头文件路径不正确，可用类似上面的方式处理解决
**ThirdParty/v8/Inc/Blob/macOS**    改名为    **ThirdParty/v8/Inc/Blob/macOS_x86_64**, 
**ThirdParty/v8/Inc/Blob/macOS_arm64**    复制一份并改名为    **ThirdParty/v8/Inc/Blob//macOS**
![image](https://github.com/Tencent/puerts/assets/8744395/569059e3-4313-4f95-83a0-c90c91c696b8)
![image](https://github.com/Tencent/puerts/assets/8744395/0ecfca75-aee3-4604-80f6-e680b94aa5c1)

**Comment by chexiongsheng** [comment]
你试试更新：https://github.com/Tencent/puerts/commit/54ef95d2ea5496059a0568a0aadb32bdea04fd23
另外你的目录要修改下，规则是加上_arm64后缀

**Comment by ChenRenault** [comment]
已测试，可以了。
