### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1473]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.04

### UE的版本 | UE Version

4.25/4.27

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

UE4.25 Windows 出现以下错误
UE4.27 Android 出现以下错误
UE4.27 IOS 没有问题

在tick中出现问题，actor卸载后发生，与1.03版本比较，出错那里确实是新代码。
希望这个问题已经解决了？

### 问题重现 | Bug reproduce

Unhandled Exception: 0x80000003

Test!v8::base::OS::Abort()
Test!v8::Function::Call()
Test!puerts::FFunctionTranslator::CallJs() [E:\Work\test4.25\Plugins\Puerts\Source\JsEnv\Private\FunctionTranslator.cpp:598]
Test!puerts::FJsEnvImpl::InvokeTsMethod() [E:\Work\test4.25\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp:2199]
Test!UTypeScriptGeneratedClass::execCallJS() [E:\Work\test4.25\Plugins\Puerts\Source\JsEnv\Private\TypeScriptGeneratedClass.cpp:45]
Test!UFunction::Invoke() [F:\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5543]
Test!UObject::ProcessEvent() [F:\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1916]
Test!AActor::ProcessEvent() [F:\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:798]
Test!AActor::ReceiveTick() [E:\Work\test4.25\Intermediate\Build\Win64\Test\Inc\Engine\Actor.gen.cpp:1933]
Test!AActor::Tick() [F:\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:1029]
Test!AActor::TickActor() [F:\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:1009]
Test!FActorTickFunction::ExecuteTick() [F:\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:172]
Test!FTickFunctionTask::DoTask() [F:\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:284]
Test!TGraphTask<FTickFunctionTask>::ExecuteTask() [F:\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:852]
Test!FNamedTaskThread::ProcessTasksNamedThread() [F:\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:692]
Test!FNamedTaskThread::ProcessTasksUntilQuit() [F:\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:587]
Test!FTaskGraphImplementation::WaitUntilTasksComplete() [F:\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:1478]
Test!FTickTaskSequencer::ReleaseTickGroup() [F:\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:558]
Test!FTickTaskManager::RunTickGroup() [F:\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:1523]
Test!UWorld::RunTickGroup() [F:\UE4\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:783]
Test!UWorld::Tick() [F:\UE4\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1678]
Test!UGameEngine::Tick() [F:\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1686]
Test!FEngineLoop::Tick() [F:\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4850]
Test!GuardedMain() [F:\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
Test!GuardedMainWrapper() [F:\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
Test!WinMain() [F:\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
Test!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by chexiongsheng** [comment]
崩在if (!Result.IsEmpty()) ？这是一直都有也应该有的代码。
你这是哪个版本的？你说1.0.4，但我看JsEnvImpl.cpp:2199和1.0.4对不上。
能在demo那搞个重现的例子么？

**Comment by terst6** [comment]
估计重现问题很难，不知道该模拟什么情况。贴上来只是想看看，这个调用堆栈逻辑，你看得出来问题不。那里与1.03代码不一样。  我1.04代码有一点修改，开启了运行时允许动态注入，配合JS代码热更新。JsEenvimpl.cpp:2199的上一个语句是
      FuncInfo->FunctionTranslator->CallJs(
            Isolate, Context, FuncInfo->JsFunction.Get(Isolate), ThisObj, ContextObject, Stack, RESULT_PARAM);

        if (TryCatch.HasCaught())

**Comment by chexiongsheng** [comment]
看不出来问题
