### ISSUE TITLE
[Unity] Bug:  In xil2cpp Window builds the more Arrays are created, the slower it is.

### ISSUE THREAD

**Issue by EverydayDevup** [Tencent/puerts#1480]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

master a64c497934ffa7c2ed4389ddb4de806d6b0fe1e2

### Unity的版本 | Unity Version

unity 2021.3.17f1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

in xil2cpp Window builds the more Arrays are created, the slower it is.
- 在 xil2cpp Window 构建中，创建的数组越多，速度就越慢。

There is no slowdown in Array creation in Mono.
- Mono 中数组创建并没有减慢。

xil2cpp test result
// 1st : 231.15 ms
// 2st : 344.7 ms
// 3st : 318.316 ms

### 问题重现 | Bug reproduce

The issue occurred when the following TestCode function was run 3 times.    

This code creates a Vector3 Array with a size of 100000, 1000 times and measures the average speed over 20 times.

private TestCode() {
        const startTime = Date.now();
        for (let i = 0; i < 20; i++) {
            for (let j = 0; j < 1000; j++) {
                const arr1 = CS.System.Array.CreateInstance(puer.$typeof(CS.UnityEngine.Vector3), 100000);
            }
        }
        const endTime = Date.now();
        console.log((endTime - startTime)/20);
        // 1st : 231.15 ms
        // 2st : 344.7 ms
        // 3st : 381.316 ms
    }

**Comment by zombieyang** [comment]
Does memory always growing during these three procedure?

**Comment by EverydayDevup** [comment]
Memory does not grow continuously. It seems that memory is returned when GC is called.

Each time the code runs, the memory increases, but it does not just increase because it decreases.

When I continued testing, I noticed that it took between 430 ms and 450 ms.

What I'm curious about
When testing with Puerts Static Wrapper in Mono, there is no difference in time even if the test code continues to run, but in xil2cpp, it gradually takes more time.

Under normal circumstances, xil2cpp is faster than mono, but I wonder why xil2cpp is slower in that situation.

**Comment by zombieyang** [comment]
I got `c# exception:Out of memory` when running your code... Let me checkit

**Comment by EverydayDevup** [comment]
It's the same test code, but it seems that Out of Memory occurred because the PC specifications are different. My PC is 64 GB Ram, Window 10 64bit.
When I ran the test code in Window Build, the memory profiling information
11-12GB went up on the managed heap.

It seems that you need to check the limit of memory by changing the number of iterations of j from 1000 -> 500 -> 250 -> 100.

**Comment by zombieyang** [comment]
So much memory your computer has... it makes me jealous :)
Have you ever try about running Unity's il2cpp backend but without xil2cpp mode?
I think it is more likely caused by Unity il2cpp's strategy.

**Comment by EverydayDevup** [comment]
When testing with the Unity backend il2cpp puerts mono build, the same issue of gradually slowing down the test code occurred. As you said, Unity il2cpp seems to be the problem.

Could you give me a hint if you know what could cause this issue in Unity il2cpp's strategy?. :)

**Comment by zombieyang** [comment]
To be honest I don't know exactly why. It is most possibly related to GC.

In profiler. The slower case always has less GC.Collect() invoke. But I think maybe it is the bug of profiler, maybe [aggressive GC](https://learn.microsoft.com/en-us/dotnet/api/system.gccollectionmode?view=net-7.0) cannot be shown in it.

mono: 
![image](https://github.com/Tencent/puerts/assets/5595819/c92d0018-cf0f-4c45-b473-5554ead78ce0)

il2cpp:
![image](https://github.com/Tencent/puerts/assets/5595819/ca8ebc81-748c-49c1-8d8d-c2da26e78b08)

**Comment by EverydayDevup** [comment]
thank you
