### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by chenghui-xiao** [Tencent/puerts#1484]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0

### UE的版本 | UE Version

5.01

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

在删除uasset文件后，我不能通过自动编译再次生成代理蓝图了 
![image](https://github.com/Tencent/puerts/assets/49576006/147ea3a5-4c71-4f19-bb93-9f449bd767e9)

### 问题重现 | Bug reproduce

补充 ：通过监视tsconfig.json 重新生成了js文件 但代理蓝图无法生成 我尝试其他方法也无法重新生成代理蓝图

**Comment by chexiongsheng** [comment]
修改下文件可以触发编译
或者控制台输入puerts compile
