### ISSUE TITLE
[UE] Bug: UE交叉编译链接错误（nodejs）

### ISSUE THREAD

**Issue by xiasun** [Tencent/puerts#1491]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.4

### UE的版本 | UE Version

5.0.3

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

UATHelper: Packaging (Linux): [1/3] Compile PesapiFrameworkLoader.mm
UATHelper: Packaging (Linux): error: Objective-C was disabled in PCH file but is currently enabled
UATHelper: Packaging (Linux): 1 error generated.
UATHelper: Packaging (Linux): [2/3] WriteMetadata XXX.target cancelled
UATHelper: Packaging (Linux): [3/3] Link (lld) XXX cancelled
UATHelper: Packaging (Linux): Took 5.9416204s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Linux): UnrealBuildTool failed. See log for more details. (C:\Users\xxx\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Programs+Epic+Games+UE_5.1\UBT-XXX-Linux-Development.txt)
PackagingResults: Error: Objective-C was disabled in PCH file but is currently enabled
UATHelper: Packaging (Linux): AutomationTool executed for 0h 0m 9s
UATHelper: Packaging (Linux): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Linux): BUILD FAILED
PackagingResults: Error: Unknown Error

### 问题重现 | Bug reproduce

尝试在Windows下交叉编译Linux程序，会尝试编译.mm文件，删掉后可正常编译。

**Comment by chexiongsheng** [comment]
改名成.cpp可以。
ue4是没问题的，ue5需要改名。但我没确认改名后对ue4有没影响，就一直没改
