### ISSUE TITLE
[UE] Bug: linux下dedicated server，进程无法正常退出

### ISSUE THREAD

**Issue by gongziyiyi** [Tencent/puerts#1502]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

5.2.1

### 发生在哪个平台 | Platform

Other

### 错误信息 | Error Message

linux：debian10

以单线程模式运行ds，执行kill -15或者内部逻辑触发FPlatformMisc::RequestExit，引擎都会执行退出、但是进程长期卡住无法退出，
gdb查看当前执行栈：
![265209330-55896a1d-0967-41ba-bed4-2128a0bce162](https://github.com/Tencent/puerts/assets/26919714/5b894a97-3154-4595-8813-1ba8fd507409)
似乎是卡在v8的内部线程join上面
只能kill -9强杀ds

### 问题重现 | Bug reproduce

重现流程已在上面说明

**Comment by chexiongsheng** [comment]
是哪个脚本后端呢？v8 8.4，v9 9.4， nodejs？

**Comment by gongziyiyi** [comment]
> 

走的咱们文档默认的下载链接，应该是v8 8.4

**Comment by chexiongsheng** [comment]
我看默认并没有启动线程，是你们自己修改了v8::platform::NewDefaultPlatform调用么？

**Comment by gongziyiyi** [comment]
这块没动过呢，

**Comment by chexiongsheng** [comment]
传0确实也会按cpu核数启动了线程。
这些工作线程v8主要用来执行些后台任务，比如jit。进程退出前按理说得等这些线程执行完任务。
是不是等一下这些任务完成就可以了呢？要卡很久都没退出？

**Comment by gongziyiyi** [comment]
> 传0确实也会按cpu核数启动了线程。 这些工作线程v8主要用来执行些后台任务，比如jit。进程退出前按理说得等这些线程执行完任务。 是不是等一下这些任务完成就可以了呢？要卡很久都没退出？

嗯，一直卡着不退。。。等几个小时也不行

**Comment by chexiongsheng** [comment]
有一个办法是能确保没有Worker Thread的：
* v8加个--single-threaded启动参数（确保v8不会用到Worker线程）
* NewDefaultPlatform改为NewSingleThreadedDefaultPlatform（可选，确保v8不会启动Worker线程）

这样设置有可能会因为jit或者gc产生卡顿。

**Comment by chexiongsheng** [comment]
你可以切换下线程，看看那些Worker线程在干啥么？

**Comment by gongziyiyi** [comment]
> 你可以切换下线程，看看那些Worker线程在干啥么？

我把可能的业务线程都屏蔽掉以后，kill -15可以杀掉，但是产生了coredump
![8618305986e656a2c8d41148fd82cb4](https://github.com/Tencent/puerts/assets/26919714/4abd96ec-9d61-442c-a034-e6015aef9f83)
gdb查看只有1个线程。。。

是不是有这种可能，编译工具链不同？
unreal在linux下边是clang的一套，是不是和v8的编译环境不同

**Comment by chexiongsheng** [comment]
最好在同一环境编译。
linux的编译相对是比较简单的
