### ISSUE TITLE
[Unity] Bug: 新版unity IL2CPP Thread::GetThreadStaticDataForThread参数变更

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1503]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### Unity的版本 | Unity Version

2022.3.8f1

### 发生在哪个平台 | Platform

Android

### 问题重现 | Bug reproduce

Thread.h:  
        static void* GetThreadStaticDataForThread(int32_t offset, Il2CppInternalThread* thread);

Puerts_il2cpp.cpp需要改成（但不知道是哪个版本开始变化的）:
                    threadStaticData = Thread::GetThreadStaticDataForThread(field->parent->thread_static_fields_offset, il2cpp::vm::Thread::**CurrentInternal**());

**Comment by zombieyang** [comment]
我在unityhub和官网只找到2022.3.7版本，试了没问题。3.8是哪来的
具体表现是执行报错还是编译报错？

**Comment by mingxxming** [comment]
如果3.7好的，那就是3.8开始的。就是Thread接口改参数了
https://unity.com/releases/editor/whats-new/2022.3.8#release-notes
安装链接：unityhub://2022.3.8f1/b5eafc012955
