### ISSUE TITLE
[UE] Bug: 

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1505]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.05

### UE的版本 | UE Version

ue4.27

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

相同的项目用相同的puerts版本，源码版4.25正常，源码版4.27就有问题：编辑器启动之前修改保存的ts文件，启动编辑器后不会自动编译，每次都需要去检查js文件是否有修改后的代码。不知道其它用户，有没有相同的情况。我重启电脑后问题一样存在

### 问题重现 | Bug reproduce

不知道其它用户，有没有相同的情况。如果说是项目的特殊情况导致的，ue4.25又是正常的，所以，在这里问一下

**Comment by terst6** [comment]
保存以后的ts文件，如果在编辑器启动后，再次保存，在编辑器里可以看到正常的编译信息，没有说文件相同跳过编译的提示，说明启动时确实没有自动编译

**Comment by chexiongsheng** [comment]
不会每次重启都编译js，ts文件没改变不会编译，有没改变是根据md5，md5存放ts_file_versions_info.json文件

**Comment by chexiongsheng** [comment]
另外，提issue要写标题
