### ISSUE TITLE
[UE] Bug: 定义UEnum类型的TArray，调用Add时有编译错误

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1507]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master  5409d2af

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

应该是infer的类型推断出了问题，导致调用Add时编译报错

1. 错误的类型推断
 ![image](https://github.com/Tencent/puerts/assets/5946974/a7d16fa7-168f-444a-bbc6-02785fc2be36)
2. 调用Add时报错
![image](https://github.com/Tencent/puerts/assets/5946974/83d3fff0-f50e-4608-bd96-34cf92159ed5)
3.推断类型
![image](https://github.com/Tencent/puerts/assets/5946974/aa6c7767-dab4-4ae2-95d8-6a76c6cff117)
4.枚举定义
![image](https://github.com/Tencent/puerts/assets/5946974/c8bca9a5-7154-421e-a8e8-ca18258b6d43)

### 问题重现 | Bug reproduce

typescript版本4.7.4
随意定义一个UEnum类型的TArray，然后调用Add

**Comment by chexiongsheng** [comment]
我这里没报错，语法也没问题，枚举有个固定的__typeKeyDoNoAccess值，这个值的类型不就是当前枚举的类型么。

**Comment by lzj10** [comment]
找到原因了 原因是我的vscode用的tsdk版本不是编译用的4.7.4，是5.1所以会报错 我改了就好了
