### ISSUE TITLE
[Unity]/[UE] can you run a js app as a game object Unity example ?

### ISSUE THREAD

**Issue by chromafunk** [Tencent/puerts#1514]
## detail | 详细描述
I am trying to make an app that shows some charts made in JS in a unity game. Can I run / show the chart in a game as a gameobject or some object using this framework ? Is there any basic example besides hello world that shows how this would work ? 

Thanks !

**Comment by zombieyang** [comment]
I think it is more related to how the charts is rendered.
If it is base on HTML. I think is it hard to finished unless you are aim to publish to WebGL platform.

**Comment by chromafunk** [comment]
these are WASM. charts, but the JS must be typically placed in a div like this : 

` <script type="module" src="streaming.js"></script>`. Streaming is a JS app that runs the underlying WASM.

Can it be used, or I'm in the wrong project ? :) 

Thanks

**Comment by zombieyang** [comment]
Still hard to understand how it work. But I think this will help you: 
https://github.com/zombieyang/puerts_unity_webgl_demo

It provide a chance to let your run in browser's VM so you can access streaming.js as same as a browser app.

**Comment by chromafunk** [comment]
thank you for taking the time to answer. I have finally switched to three.js, because it's much easier to do what I want to do
good luck with this impressive project !
