### ISSUE TITLE
[UE] Bug: 结构体嵌套的gc问题

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1518]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master  5409d2a

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

结构体嵌套的时候，当外层结构体被gc的时候即使内层结构体被ts引用也会被销毁
![image](https://github.com/Tencent/puerts/assets/5946974/731bc43b-a77d-4a3c-a1ac-573baeb1ebcf)

### 问题重现 | Bug reproduce

1、嵌套结构FTest_StructA、FTest_StructB
![image](https://github.com/Tencent/puerts/assets/5946974/0c78f31c-4f55-4f76-afd6-694c821f23fe)

2、ts里创建A，持有B，并设置TestNumB的值
![image](https://github.com/Tencent/puerts/assets/5946974/bb3d9df7-6d95-48f4-806a-7e8c7e0567f0)

3、A被回收后,B也被回收了 TestNumB值出错。
![image](https://github.com/Tencent/puerts/assets/5946974/731bc43b-a77d-4a3c-a1ac-573baeb1ebcf)

因是js是引用传递，但实际上struct嵌套是在一块内存中，A的内存清理掉后，B确实也被清理了

目前只能尽量避免这么使用，但是UE本身有很多结构也是嵌套的比如常用的FHitResult  所以还是有点危险
比如要保存FHitResult里面的Location字段，要么需要保存FHitResult本身，要么需要重新根据Loction new一个新Vector保存

**Comment by chexiongsheng** [comment]
有个WITH_OUTER_LINK宏可以让内存持有外层引用

**Comment by chexiongsheng** [comment]
> 有个WITH_OUTER_LINK宏可以让内存持有外层引用

内层引用外层。
可以解决你说的问题，但有一定的性能开销

**Comment by lzj10** [comment]
我去试试

**Comment by terst6** [comment]
原来是这个原因，FHitResult里面的Location字，使用失败，我是new 一个新的
