### ISSUE TITLE
[UE] 在Ubantu20上编译插件报ld.lld: error: unable to find library -lnode

### ISSUE THREAD

**Issue by blueroseslol** [Tencent/puerts#1521]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

v1.0.4

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Other

### 错误信息 | Error Message

Building
Determining max actions to execute in parallel (32 physical cores, 32 logical cores)
  Executing up to 32 processes, one per physical core
@progress 'Compiling C++ source code...' 0%
Building 7 actions with 7 processes...
@progress 'Compiling C++ source code...' 14%
[1/7] Compile Module.JsEnv.1_of_3.cpp
@progress 'Compiling C++ source code...' 29%
[2/7] Link (lld) libUnrealEditor-JsEnv.so
ld.lld: error: unable to find library -lnode
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
@progress 'Compiling C++ source code...' 43%
[3/7] Link (lld) libUnrealEditor-Puerts.so cancelled
@progress 'Compiling C++ source code...' 57%
[4/7] Link (lld) libUnrealEditor-EasyEditorPlugin.so cancelled
@progress 'Compiling C++ source code...' 71%
[5/7] Link (lld) libUnrealEditor-PuertsEditor.so cancelled
@progress 'Compiling C++ source code...' 86%
[6/7] Link (lld) libUnrealEditor-DeclarationGenerator.so cancelled
@progress 'Compiling C++ source code...' 100%

### 问题重现 | Bug reproduce

使用Nodejs版本，在Ubantu20上编译插件会出现以下报错。请问该如何解决？

[2/7] Link (lld) libUnrealEditor-JsEnv.so
ld.lld: error: unable to find library -lnode
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

```   
void ThirdPartyNodejs(ReadOnlyTargetRules Target)
{
    else if (Target.Platform == UnrealTargetPlatform.Linux) 
    {
        string V8LibraryPath = Path.Combine(LibraryPath, "Linux");
        PublicAdditionalLibraries.Add(Path.Combine(V8LibraryPath, "libnode.so"));
        RuntimeDependencies.Add("$(TargetOutputDir)/libnode.so.93", Path.Combine(V8LibraryPath, "libnode.so.93"));
    }
}
```

**Comment by chexiongsheng** [comment]
应该是编译环境和运行环境不一致导致的。
你在你的环境编译一个libnode.so，参考我们的编译脚本：https://github.com/puerts/backend-nodejs/blob/master/linux.sh

**Comment by chexiongsheng** [comment]
下次提issue麻烦写下标题

**Comment by blueroseslol** [comment]
我看了一下backend-nodejs的release，比如[nodejs_bin_16.16.0.tgz](https://github.com/puerts/backend-nodejs/releases/download/NodeJS_16.16.0_230216/nodejs_bin_16.16.0.tgz)。Linux里面是有libnode.so存在的。而puerts的node release下载里面却没有libnode.so。我将backend-nodejs的Linux里的2个so文件放入插件，编译就过了。

但进项目会提示JsEnv无法载入，操作系统或者模块没有setup

另外能简单说一下这个编译脚本如何使用么？我是输入./linux.sh backend-nodejs 18.x,运行之后会出现一些c++编译错误的提示。

**Comment by chexiongsheng** [comment]
这脚本依赖github action的一些环境变量
都是最简单的linux shell语法，你自己打开看看

**Comment by blueroseslol** [comment]
- Clang 15.0.7

经过一下午不断测试，编译会提示以下错误：
```
In file included from ../deps/v8/src/base/file-utils.cc:5:
../deps/v8/src/base/file-utils.h:8:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
In file included from ../deps/v8/src/base/cpu.cc:5:
In file included from ../deps/v8/src/base/cpu.h:17:
../deps/v8/src/base/macros.h:8:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
In file included from ../deps/v8/src/base/debug/stack_trace.cc:5:
../deps/v8/src/base/debug/stack_trace.h:13:10: fatal error: 'iosfwd' file not found
#include <iosfwd>
         ^~~~~~~~
In file included from ../deps/v8/src/base/bits.cc:5:
../deps/v8/src/base/bits.h:9:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
In file included from ../deps/v8/src/base/functional.cc:11:
../deps/v8/src/base/functional.h:11:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
In file included from ../deps/v8/src/base/bounded-page-allocator.cc:5:
In file included from ../deps/v8/src/base/bounded-page-allocator.h:8:
../deps/v8/include/v8-platform.h:11:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
1 error generated.
../deps/v8/src/base/ieee754.cc:18:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/bits.o] 错误 1
make[1]: *** 正在等待未完成的任务....
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/debug/stack_trace.o] 错误 1
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/functional.o] 错误 1
1 error generated.
In file included from ../deps/v8/src/base/division-by-constant.cc:9:
../deps/v8/src/base/logging.h:8:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/cpu.o] 错误 1
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/file-utils.o] 错误 1
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/bounded-page-allocator.o] 错误 1
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/division-by-constant.o] 错误 1
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libbase.target.mk:179：/home/user/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/ieee754.o] 错误 1
make: *** [Makefile:113：node] 错误 2
```

**Comment by chexiongsheng** [comment]
这些不是基本的c++头文件么？

**Comment by blueroseslol** [comment]
问题解决了，重新编译并且替换so文件有效。

至于编译问题是因为没有安装对应的库：
- sudo apt-get install libc++-dev
- sudo apt-get install libc++abi-dev
