### ISSUE TITLE
[UE] 有没有静态绑定的自动化生成工具

### ISSUE THREAD

**Issue by stdnxd** [Tencent/puerts#1523]
关于UE里面的普通C++类(非蓝图类)的静态绑定
有没有什么软件或者插件自动生成静态绑定代码 
现在写一个C++类 还需要写大量的绑定代码 非常麻烦

**Comment by stdnxd** [comment]
其实我很好奇puerts提供的 FVector_Wrap.cpp 这几个用什么工具生成的
这个工具可以开放出来吗 
其实我这边不需要自动化生成代码工具有多精确
只需要可以帮我生成80%以上的代码 剩下的有问题我手动修改就好了

**Comment by chexiongsheng** [comment]
用静态绑定不需要“大量的绑定代码”吧：https://puerts.github.io/docs/puerts/unreal/template_binding

如果是 FVector_Wrap.cpp这种写法确实是大量代码。 FVector_Wrap.cpp是用libclang的python版本做的，但这工具只能解析ast，碰到模板是很难搞定的，所以弃用了。
不过如果把静态模板绑定和libclang结合一下，可以避免模板处理不了的问题，也能做到自动化。

**Comment by stdnxd** [comment]
谢谢 明白了
