### ISSUE TITLE
[Unity] Bug: Wrapper Vector3、Camera、Transform并开启unsafe编译后 使用Camera.WorldToScreenPoint进行坐标转换仍会产生GC

### ISSUE THREAD

**Issue by sd1840888** [Tencent/puerts#1527]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0

### Unity的版本 | Unity Version

2021.3.29f

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

![333](https://github.com/Tencent/puerts/assets/11204673/d3917588-5041-4bb7-a6dd-76f0808967a9)

### 问题重现 | Bug reproduce

![111](https://github.com/Tencent/puerts/assets/11204673/701d669d-5f35-4dad-a499-12750b35d317)

![222](https://github.com/Tencent/puerts/assets/11204673/6358bc4e-9993-4820-be86-6ae9f3bb87d4)

项目代码
[t.zip](https://github.com/Tencent/puerts/files/12646352/t.zip)

**Comment by zombieyang** [comment]
wrapper中产生了一次装箱，待优化

**Comment by chexiongsheng** [comment]
早年的一次优化带入：https://github.com/Tencent/puerts/pull/1023
非常感谢你的反馈和PR。
