### ISSUE TITLE
[Unity] Puerts 2.0.0 pre.v4 Android Build Environment

### ISSUE THREAD

**Issue by EverydayDevup** [Tencent/puerts#1528]
## detail | 详细描述

Puerts Git master branch is using hash value 6222719ccf7387011dee3c52d259dcf9ce261680.
I tried to build a plugin for the Android build of Puerts 2.0, but it failed.
My PC environment is Windows, and I attempted to build by referring to Android in the git action.

To build, I downloaded android-ndk-r21e-windows-x86_64.zip and unzipped it in the user folder.
C:\Users\pjhara\android-ndk-r21e

To set environment variables for the process, I ran the following command in cmd.
set ANDROID_NDK=%USERPROFILE%\android-ndk-r21e

And since I needed puerts based on nodejs backend, I ran the following command.
node ../cli make --platform android --backend nodejs_16 --config Release

An error occurred as follows:
node --loader ts-node/esm C:\Users\pjhara\Desktop\Test\puerts\unity\cli/cmd.mts make --platform android --backend nodejs_16 --config Release --arch auto
(node:708) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

CHCP 65001

cmake --version

NDK : C:\Users\pjhara\android-ndk-r21e <- my log

cmake -DBACKEND_DEFINITIONS="V8_94_OR_NEWER;WITH_NODEJS" -DBACKEND_LIB_NAMES="/lib/Android/armeabi-v7a/libbrotli.a;/lib/Android/armeabi-v7a/libnode_stub.a;/lib/Android/armeabi-v7a/libv8_libbase.a;/lib/Android/armeabi-v7a/libcares.a;/lib/Android/armeabi-v7a/libopenssl.a;/lib/Android/armeabi-v7a/libv8_libplatform.a;/lib/Android/armeabi-v7a/libhistogram.a;/lib/Android/armeabi-v7a/libuv.a;/lib/Android/armeabi-v7a/libv8_snapshot.a;/lib/Android/armeabi-v7a/libllhttp.a;/lib/Android/armeabi-v7a/libuvwasi.a;/lib/Android/armeabi-v7a/libv8_zlib.a;/lib/Android/armeabi-v7a/libnghttp2.a;/lib/Android/armeabi-v7a/libv8_base_without_compiler.a;/lib/Android/armeabi-v7a/libzlib.a;/lib/Android/armeabi-v7a/libnode.a;/lib/Android/armeabi-v7a/libv8_compiler.a;/lib/Android/armeabi-v7a/libv8_initializers.a" -DBACKEND_INC_NAMES="/include;/deps/v8/include;/deps/uv/include" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DJS_ENGINE=nodejs_16 -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI=armeabi-v7a -H. -BC:\Users\pjhara\Desktop\Test\puerts\unity\native_src/build_android_armv7_nodejs_16 -DCMAKE_TOOLCHAIN_FILE=C:\Users\pjhara\android-ndk-r21e/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_TOOLCHAIN=clang -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9

CMake Error at CMakeLists.txt:10 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine for NET Framework version 16.11.2+f32259642
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started: 2023-09-20 11:54:53 AM
   Project "C:\Users\pjhara\Desktop\Test\puerts\unity\native_src\build_android_armv7_nodejs_16\CMakeFiles\3.26.2\VCTargetsPath.vcxproj" on node 1 (default target).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath .vcxproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Debug' Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\pjhara\Desktop\Test\puerts\unity\native_src\build_android_armv7_nodejs_16\CMakeFiles\3.26.2\VCTargetsPath.vcxproj]
    Build project "C:\Users\pjhara\Desktop\Test\puerts\unity\native_src\build_android_armv7_nodejs_16\CMakeFiles\3.26.2\VCTargetsPath.vcxproj" (default target). - failure

-- Configuring incomplete, errors occurred!

Build failed.

    "C:\Users\pjhara\Desktop\Test\puerts\unity\native_src\build_android_armv7_nodejs_16\CMakeFiles\3.26.2\VCTargetsPath.vcxproj" (default target)(1)->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath .vcxproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Debug' Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\pjhara\Desktop\Test\puerts\unity\native_src\build_android_armv7_nodejs_16\CMakeFiles\3.26.2\VCTargetsPath.vcxproj]

        0 warnings
        1 error

    Elapsed time: 00:00:00.10

  Exit code: 1

file:///C:/Users/pjhara/Desktop/Test/puerts/unity/cli/make.mts:31
                assert.equal(0, exec(`cmake ${cmakeDArgs} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DJS_ENGINE=${options.backend} -DCMAKE_BUILD_TYPE=${options.config} -DANDROID_ABI=${ABI} -H. -B${CMAKE_BUILD_PATH} -DCMAKE_TOOLCHAIN_FILE=${NDK}/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=${API} -DANDROID_TOOLCHAIN=clang -DANDROID_TOOLCHAIN_NAME=${TOOLCHAIN_NAME}`).code)

**What do I need to set up for my build?**

**Comment by zombieyang** [comment]
android binary is not supported to be built in Windows cmd or bash.
use a mac or build it in WSL.

**Comment by EverydayDevup** [comment]
Thank you. Let’s take a look at WSL. This is my first time in this field, so I think I'll keep asking questions. Will an Android build guide be provided just like the Windows build guide is in the puerts document?

**Comment by zombieyang** [comment]
> Thank you. Let’s take a look at WSL. This is my first time in this field, so I think I'll keep asking questions. Will an Android build guide be provided just like the Windows build guide is in the puerts document?

Yes, but you may need to download NDK first, in one word following GitHub action is ok

**Comment by zombieyang** [comment]
same as another issue. your import setting is wrong, you can recover the meta file from github repo
