### ISSUE TITLE
[Unity] Android Build Error

### ISSUE THREAD

**Issue by EverydayDevup** [Tencent/puerts#1529]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

master 6222719ccf7387011dee3c52d259dcf9ce261680

### Unity的版本 | Unity Version

2021.3.17f1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

2023-09-20 13:19:18.618 10893 10919 Error Unity [Puer001] DllNotFoundException detected. You can solve this problem following the FAQ.
2023-09-20 13:19:18.622 10893 10919 Error Unity DllNotFoundException: puerts assembly:<unknown assembly> type:<unknown type> member:(null)
2023-09-20 13:19:18.622 10893 10919 Error Unity   at (wrapper managed-to-native) Puerts.PuertsDLL._GetApiLevel()
2023-09-20 13:19:18.622 10893 10919 Error Unity   at Puerts.PuertsDLL.GetApiLevel () [0x00013] in <8bb0d946dde34f0491ef8d2711115523>:0 
2023-09-20 13:19:18.622 10893 10919 Error Unity   at Puerts.JsEnv..ctor (Puerts.ILoader loader, System.Int32 debugPort, System.IntPtr externalRuntime, System.IntPtr externalContext) [0x00053] in <8bb0d946dde34f0491ef8d2711115523>:0 
2023-09-20 13:19:18.622 10893 10919 Error Unity   at Puerts.JsEnv..ctor () [0x00006] in <8bb0d946dde34f0491ef8d2711115523>:0 

### 问题重现 | Bug reproduce

To test the Android build, we proceeded as follows.

puerts.git master branch 6222719ccf7387011dee3c52d259dcf9ce261680 was pulled.

After creating a new project in unity, I connected the locally cloned puerts/unity/Assets/core/upm/package.json using the add disk menu in the package manager.

Since Android Plugins did not exist, I downloaded and copied the file in puerts.git Action.
https://github.com/Tencent/puerts/actions/runs/6157921257
Unity_Plugins(nodejs_16_Release)

I connected a very simple script to a button click and confirmed that puerts was working properly in the Editor.

public class HelloWorld : MonoBehaviour
{
//One. Hello World
    public void OnHello() {
        Puerts.JsEnv env = new Puerts.JsEnv();
        env.Eval(@"
            console.log('hello world');
        ");
    }
}

When testing after building on backend Mono, Android, the error above occurred.
(We confirmed that it operates normally in the Windows build.)

This issue is related to https://github.com/Tencent/puerts/issues/1528.

**Comment by zombieyang** [comment]
if you use the binary downloaded from github action. Remember to remove the PUERTS_EXPERIMENTAL_IL2CPP definition.

**Comment by EverydayDevup** [comment]
When building android in unity, the build proceeded without defining PUERTS_EXPERIMENTAL_IL2CPP. Is there something I missed?

**Comment by zombieyang** [comment]
sorry, is `EXPERIMENTAL_IL2CPP_PUERTS`. did you build android without it?

then follow https://github.com/Tencent/puerts/blob/master/doc/unity/en/faq.md#puer001dllnotfoundexception-puerts. I think all `dll not found` will be solved

**Comment by EverydayDevup** [comment]
The build was done excluding EXPERIMENTAL_IL2CPP_PUERTS.

I tried changing the import setting from arm64 -> arm7, but libpuerts.so is missing in the built apk.

When I changed it to .apk -> zip and checked, the lib/armeabi-v7a folder contained
Only libmain.so / libmonobdwgc-2.0.so / libmono-native.so / lubMonoPosixHelper.so / libunity.so files exist.

I tried building several times but failed.

**Comment by EverydayDevup** [comment]
I copied the meta file and it was resolved.
