### ISSUE TITLE
[UE] JsEnv关闭，UE容器有泄露的可能

### ISSUE THREAD

**Issue by woshidashan** [Tencent/puerts#1530]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

所有版本

### UE的版本 | UE Version

4.26

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

![QQ图片20230921133123](https://github.com/Tencent/puerts/assets/58979193/fb32dd63-1398-4d8d-b0a7-01f5298c1d44)
![QQ图片20230921133128](https://github.com/Tencent/puerts/assets/58979193/a8791929-51a3-4032-8ce1-6cba9f9ab26a)
重启虚拟机，内存泄漏，容器的Translator在FJsEnvImpl析构的时候没有释放
我们尝试把这个新new的容器放到Array里 在析构的时候delete掉就ok了

### 问题重现 | Bug reproduce

启动虚拟机实例销毁

**Comment by chexiongsheng** [comment]
漏了一个文件：https://github.com/Tencent/puerts/commit/d60bc9e1d279572f3d9c9f307d156fbdf70b63fd

**Comment by scutDavid** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
> * [x]  [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)
> 
> ### Puer的版本 | Puer Version
> 所有版本
> 
> ### UE的版本 | UE Version
> 4.26
> 
> ### 发生在哪个平台 | Platform
> iOS
> 
> ### 错误信息 | Error Message
> ![QQ图片20230921133123](https://private-user-images.githubusercontent.com/58979193/269497888-fb32dd63-1398-4d8d-b0a7-01f5298c1d44.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDg2NTEsIm5iZiI6MTcxMDQwODM1MSwicGF0aCI6Ii81ODk3OTE5My8yNjk0OTc4ODgtZmIzMmRkNjMtMTM5OC00ZDhkLWIwYTctMDFmNTI5OGMxZDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5MjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZDQwMDUzN2QyMzRiYzMxNjgyZjAzNzE5YzJhYWJmYzBkMjhlMGUzM2JlNDM0YjNjNzMyMGI0ODg0ZmIzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztJ-pIR267yvAl6RL3tBmdOomVhG3kbbh_nBmAwUefc) ![QQ图片20230921133128](https://private-user-images.githubusercontent.com/58979193/269497900-a8791929-51a3-4032-8ce1-6cba9f9ab26a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDg2NTEsIm5iZiI6MTcxMDQwODM1MSwicGF0aCI6Ii81ODk3OTE5My8yNjk0OTc5MDAtYTg3OTE5MjktNTFhMy00MDMyLThjZTEtNmNiYTlmOWFiMjZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5MjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YTM3YzVlMGI1NWMwNGVjZGQ5YWRmMzQwMWNmMjY1Y2JkYTk4Y2EwZGQyY2I2MmE3ZDljZTc3NWUxNDVlY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztInlM9KSXKCkst36gD73pEF3Vc4zWV5iLGPXTDTjnM) 重启虚拟机，内存泄漏，容器的Translator在FJsEnvImpl析构的时候没有释放 我们尝试把这个新new的容器放到Array里 在析构的时候delete掉就ok了
> 
> ### 问题重现 | Bug reproduce
> 启动虚拟机实例销毁

请问你是怎么操作才能看到包含了v8的堆栈信息的呢 v8是以dll的形式加载进来的，是要再补充对应的pdb吗
