### ISSUE TITLE
[UE] Bug: TS访问容器内数据有概率崩溃

### ISSUE THREAD

**Issue by wusidn** [Tencent/puerts#1531]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.0

### UE的版本 | UE Version

4.26

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

主要有两个崩溃栈  都是在访问容器内的值UEToJS时崩溃  
是不是对容器使用有什么需要注意的地方
![image](https://github.com/Tencent/puerts/assets/12872482/42eb2e79-b754-47f9-9d79-8cd8fb3c9727)
![image](https://github.com/Tencent/puerts/assets/12872482/7e335fb2-68e1-4f8f-bbf3-944ba001b417)

### 问题重现 | Bug reproduce

多次关闭启动虚拟机执行游戏逻辑时概率出现

**Comment by chexiongsheng** [comment]
是不是这个容器被释放了？比如它是一个UObject或者FStruct的字段，UObject或者FStruct释放了，这个容器就是无效的，类似这个issue：https://github.com/Tencent/puerts/issues/1518

**Comment by wusidn** [comment]
经过验证确实是这个原因导致的 感谢车神
