### ISSUE TITLE
V8 版本11.6

### ISSUE THREAD

**Issue by caiyuncheng** [Tencent/puerts#1533]
官方有打算升级V8 版本吗？ [cocos那边反馈提升明显](https://forum.cocos.org/t/topic/151218)
@chexiongsheng

**Comment by terst6** [comment]
速度不可能提升100倍，我之前做puerts.js/slua/unreal.js速度测试，是把测速功能，延迟到游戏启动完成10-20秒后，估计所有延迟加载都完成了，再运行测试代码，如果多次测试结果都差不多，就没有问题
