### ISSUE TITLE
[UE] Bug: 把一个继承自被mixin的蓝图A的蓝图B扔进场景，PIE第二次结束运行的时候引擎崩溃

### ISSUE THREAD

**Issue by SeaRocJ** [Tencent/puerts#1536]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.5

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

![image](https://github.com/Tencent/puerts/assets/55874468/41bc2ca3-807a-4410-b4a6-b7094600204d)

### 问题重现 | Bug reproduce

创建一个继承自Actor的蓝图A，创建一个ts文件mixin蓝图A，然后再创建一个蓝图B继承于蓝图A,把蓝图B扔在场景里，PIE运行第二次结束运行的时候就崩溃，每次运行ts类的ReceiveBeginPlay正常执行了打印，附上mixin的ts文件内容
![image](https://github.com/Tencent/puerts/assets/55874468/905b8e52-8b27-425e-86d9-b2832091112d)

**Comment by chexiongsheng** [comment]
最好提供一个基于demo修改的工程

**Comment by chexiongsheng** [comment]
主要是光贴代码不一定能重现，有时和这个代码的执行的时机也有关。

**Comment by SeaRocJ** [comment]
在demo工程里没有复现出来

**Comment by chexiongsheng** [comment]
所以感觉没那么简单，可能和其它因素交叉导致的

**Comment by terst6** [comment]
遇到最多的编辑器退出崩溃，发生在ue_log函数上，里面引用了已经退出的空对象属性。抓这种 bug 要从VS里启动ue，带debug附着

**Comment by SeaRocJ** [comment]
目前只发现这种使用方式有崩溃问题，不过好在这个崩溃问题解决了，解决方式是加载js模块之后要保持对这个模块的引用

**Comment by chexiongsheng** [comment]
> 目前只发现这种使用方式有崩溃问题，不过好在这个崩溃问题解决了，解决方式是加载js模块之后要保持对这个模块的引用

啊，这个问题我在demo着重标注了的啊：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TypeScript/UsingMixin.ts#L10C38-L10C38
