### ISSUE TITLE
[UE] Bug: DebugEditor下调用MulticastDelegate.Add(target: Object, methodName: string): void 报错

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1538]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master  5409d2a

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

感觉问题是因为MulticastDelegate.Add(target: Object, methodName: string): void 中，Property->AddDelegate的第二个参数应该是Property的Owner，而不是第一个参数带入的Object,
因为MulticastDelegate.Add(fn : T): void 的 Property->AddDelegate 第二个参数传入的就是Owner
1、报错
![image](https://github.com/Tencent/puerts/assets/5946974/2007ecab-0a80-41c0-a7b7-4aa926bf2269)
2、Add(target: Object, methodName: string)的调用参数
![image](https://github.com/Tencent/puerts/assets/5946974/035236b8-2c7c-40d8-9210-3684e076a15f)
3、Add(fn : T): void的调用参数
![image](https://github.com/Tencent/puerts/assets/5946974/1b1c6404-c8cc-4328-ab3b-c76c5b5f271b)

### 问题重现 | Bug reproduce

继承引擎类通过自身调用MulticastDelegate. Add(target: Object, methodName: string): void接口
![image](https://github.com/Tencent/puerts/assets/5946974/f1054b4c-ff23-4157-a16c-309a5639529c)

**Comment by chexiongsheng** [comment]
我在4.27和5.3上试了都没报错

**Comment by chexiongsheng** [comment]
不过我没走到MulticastSparseDelegatePropertyMacro那个分支

**Comment by chexiongsheng** [comment]
我改为SparseDelegate没报错，但也不生效，传nullptr就生效了，以前估计没测试到。
我修改了你试试看
