### ISSUE TITLE
[UE] Bug:  UStruct 析构可能发生在后台线程

### ISSUE THREAD

**Issue by BlurryLight** [Tencent/puerts#1539]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

Any

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

https://github.com/Tencent/puerts/issues/752 与这个issue提到的优化有关。
最简单可复现的例子:

```cpp
USTRUCT()
struct FPuertsTestGCStruct
{
	GENERATED_BODY();
	UPROPERTY()
	int tmp = 0;
	~FPuertsTestGCStruct()
       {
	check(IsInGameThread());
        // some other clean operations happens on GameThread
       }
};
```

项目里有一些UStruct有一些自定义的析构函数，非POD类型。
在`HAS_ARRAYBUFFER_NEW_WITHOUT_STL`或者 `WITH_BACKING_STORE_AUTO_FREE`宏定义的情况下，析构有可能发生在v8的gc线程。

![image](https://github.com/Tencent/puerts/assets/14940338/955c7755-4536-442d-9e48-903dcfd331d3)

目前一个方案是ArrayBuffer被GC的时候调用的UStruct析构前判断一下线程，不在gamethread的话重新推回主线程去做，但是这块想看下有没有什么更好的方案

**Comment by chexiongsheng** [comment]
所有arraybuffer的释放都在v8的gc线程么？

**Comment by chexiongsheng** [comment]
v8有个--single-threaded参数，可以试试看（参考加--expose-gc参数的方法，搜索代码可以看到）

**Comment by BlurryLight** [comment]
![image](https://github.com/Tencent/puerts/assets/14940338/b9b3b62c-b7c5-45d5-9925-4bdcaff50b02)

v8的文档只说了有多个线程参与gc，没有说arraybuffer的事，应该可能在任意线程。 不过我跑了>10次测试基本都是在后台线程释放的。 --single-threaded应该会降低v8的gc性能吧，我测试下试试

**Comment by chexiongsheng** [comment]
--single-threaded不单止影响gc，jit本来也是抛给后台线程异步做的，单线程也放前台了。
不过有个项目后台基于省资源的考虑，后台用单线程，貌似没反馈什么性能问题。

**Comment by BlurryLight** [comment]
又看了下源码，`FJSObject`本身是一个`UStruct`。`FJSObject`析构的时候会调用触发几个`v8::Global::Reset` 的调用，这里有race condition，在多个线程操作虚拟机了。

**Comment by chexiongsheng** [comment]
> 又看了下源码，`FJSObject`本身是一个`UStruct`。`FJSObject`析构的时候会调用触发几个`v8::Global::Reset` 的调用，这里有race condition，在多个线程操作虚拟机了。

FJsObject特殊处理的，push到js那是取js对象push过去，如果光是单独的FJsObject不会在js那以arraybuffer的方式存在，但是如果FJsObject放在另外一个UStruct上作为它的成员应该会有问题

**Comment by chexiongsheng** [comment]
确认一件事，是不是设置!WITH_BACKING_STORE_AUTO_FREE && !defined(HAS_ARRAYBUFFER_NEW_WITHOUT_STL)后，或者说用优化前的那种方式，就一定不会走gc线程了？

**Comment by BlurryLight** [comment]
1.  v8 9.4以上注释掉HAS_ARRAYBUFFER_NEW_WITHOUT_STL似乎编不过去了.. ArrayBuffer没有GetContents这个函数。
2.  降级到v8 8.4，回到以前的SetWeak的方式，似乎一定是在主线程gc的。

**Comment by chexiongsheng** [comment]
ok，我换个不用backing store的方案

**Comment by chexiongsheng** [comment]
之前引入backing store是为了省下ScriptStructFinalizeInfoMap的插入和删除
新方案去掉backing store，改为FObjectCacheNode添加个指针来存放。
缺点是消耗了些内存（其实可以用ScriptStructWrapper作为TypeId，这样的缺点是在FindOrAddStruct多异常Struct到ScriptStructWrapper的查找）
更新一下试试，应该不会在gc线程回调了。

**Comment by BlurryLight** [comment]
仔细思考了下，其实这个特性可以利用一下。 
- 对于非POD的UStruct，应该回到主线程(或者JSEnv在的线程)析构。
- 对于POD的UStruct(比如FVector / FRotator之类的)，可以在其他线程析构分摊压力。

是否是POD可以通过`UScriptStruct`的StructFlags是否包含STRUCT_IsPlainOldData Flag来拿到。

**Comment by chexiongsheng** [comment]
> 仔细思考了下，其实这个特性可以利用一下。
> 
> * 对于非POD的UStruct，应该回到主线程(或者JSEnv在的线程)析构。
> * 对于POD的UStruct(比如FVector / FRotator之类的)，可以在其他线程析构分摊压力。
> 
> 是否是POD可以通过`UScriptStruct`的StructFlags是否包含STRUCT_IsPlainOldData Flag来拿到。

想法不错，要不，你来实现，然后PR过来？把之前的宏分支拿出来作为POD的分支就可以了

**Comment by BlurryLight** [comment]
我本地实现了一版，观察一下稳定性。没什么问题的话后面pr过来

**Comment by chexiongsheng** [comment]
我有点怀疑我之前那个修改的性能测试，ScriptStructFinalizeInfoMap的插入删除并没有那么大的影响，真正的影响是析构放在v8的worker线程了。

**Comment by chexiongsheng** [comment]
> 我本地实现了一版，观察一下稳定性。没什么问题的话后面pr过来

差不多可以PR过来，这版本是优化版本，正合适。
