### ISSUE TITLE
[UE] Bug: QuickStart.ts中的delegate成员无法初始化

### ISSUE THREAD

**Issue by weyenrooney** [Tencent/puerts#1545]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0

### UE的版本 | UE Version

4.27

### 发生在哪个平台 | Platform

Editor(windows)

### 错误信息 | Error Message

    RightMouseDown(Key: UE.Key) : void
    {

        let gameInstance = (argv.getByName("GameInstance") as UE.GameInstance);
        let actor =  UE.GameplayStatics.BeginDeferredActorSpawnFromClass(this.GetWorld(), MainActor.StaticClass(), undefined) as MainActor;

        function MutiCast1(i) {
            console.warn("MutiCast1<<<", i);
        }

        console.log("Right button ");
        actor.NotifyWithInt.Add(MutiCast1);
}

按照quickstart.ts的案例,此处调用actor.NotityWithInt为undefined

### 问题重现 | Bug reproduce

实现了一个最简单的测试类
import * as UE from "ue";
import {$Ref} from "puerts";
import {$Delegate, $MulticastDelegate, Class, Object} from "ue";

class MainActor extends UE.Actor {
    //constructor(Outer?: Object, Name?: string, ObjectFlags?: number);
    NotifyWithInt: $MulticastDelegate<(A: number) => void>;
    NotifyWithString: $Delegate<(A: string) => void>;
    NotifyWithRefString: $Delegate<(A: $Ref<string>) => void>;
    NotifyWithStringRet: $Delegate<(A: string) => string>;
    NotifyWithNothing: $MulticastDelegate<() => void>;
    //static StaticClass(): Class;
    //static Find(OrigInName: string, Outer?: Object): MainActor;
   // static Load(InName: string): MainActor;

    __tid_MainActor__: boolean;
}

export default MainActor

Delegate成员都无法正确初始化,看过demo里面也没有专门需要手动初始化的代码

**Comment by chexiongsheng** [comment]
最近有个相关的修改，你回退下试试：https://github.com/Tencent/puerts/commit/c74faf14c0b728a988079321ec2fd4b43bf67205

**Comment by weyenrooney** [comment]
那个版本稳定点,现在测试的情况multiDelegate,Delegate都无法正常初始化.反复测试和翻阅文档搞了大半天,脑壳都大了&nbsp;


water-world
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月4日(星期三) 上午10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/puerts] [UE] Bug: QuickStart.ts中的delegate成员无法初始化 (Issue #1545)





 
最近有个相关的修改，你回退下试试：c74faf1

**Comment by oVeRoVeRo** [comment]
你用的是demo里复制来的代码进行测试，但没有给出C++的代码，从你下面说的“实现了一个最简单的测试类”来看，你这段测试代码不涉及到c++的内容，而是自己在ts里把生成的MainActor声明复制过来了，你没有想过这只是一个声明，只具备代码补全的功能。
请看以下真正的核心代码，你的用法是完全错误的，基于错误的思路，当然不可能运行。
你测试bug的方式也不对，你应该完全在demo的工程里，基于现有的测试案例进行测试，很显然如果你在demo里的QuickStart.ts里跑NotifyWithInt是完全能跑通的，这时候应该怀疑你自己的问题。
```
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FNotifyWithInt, int32, A);

UCLASS()
class PUERTS_UNREAL_DEMO_API AMainActor : public AActor
{
	GENERATED_BODY()

public:
    UPROPERTY()
    FNotifyWithInt NotifyWithInt;
```

如果你只想要在ts里实现类似的功能，有ts的方法，而Dynamic Multicast Delegate是独属于UE和c++的用法。

**Comment by weyenrooney** [comment]
我确实是用的ts代码复制过来的,我的目的就是想用ts实现timeline的功能,目前看过很多issue问答都没有找到ts案例只看到说delegate成员变量要挂在uobject对象下面,然后quickstart代码处有delegate的演示,就复制过来测试发现没有用处.纯c++的实现我当然会,现在只是更多的想用ts替代版本,毕竟热更新c++无法替代ts

**Comment by terst6** [comment]
timeline 的ts实现，其实就是一个tick 里，用时间从timeline里读取值，没有必要弄这么复杂

**Comment by chexiongsheng** [comment]
看上去是你对ts的误解导致的，*.d.ts只是个声明，只是作为IDE提示、编译检查用，在那增加字段不会有效果，你应该在其背后的真正的类中新增字段，比如MainActor 是个C++类的话，应该在这个C++类中添加字段。
