### ISSUE TITLE
[UE] Bug: Commandlet 和 DeclarationGenerator 相关讨论

### ISSUE THREAD

**Issue by hewenning** [Tencent/puerts#1549]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

最新版

### UE的版本 | UE Version

UE5.3

### 发生在哪个平台 | Platform

win

### 问题重现 | Bug reproduce

1、ExportDTSCommandlet 相关在最新版本已经被移除了，如果我想在 pipline 里面做一些事情，远端编译 C++，导出 ue.d.ts 然后再编译 ts 文件，然后做后续处理，删除之后没有办法全 Jenkins，可否回复呢
2、另外 DeclarationGenerator 会把 DTS 文件生成到项目的最外层，而不是 PuertsPlugin 下面的 Typing 中，这样子会让插件和项目很耦合，可否做一下修改呢

**Comment by hewenning** [comment]
如果 1 或者 2 可以的话我这边可以直接提交 pr

**Comment by chexiongsheng** [comment]
从来就没有ExportDTSCommandlet吧？
有这需求看看这个：https://github.com/Tencent/puerts/issues/879

**Comment by hewenning** [comment]
感谢，这个问题解决了，那第二条这么设计的原因是什么呢

**Comment by hewenning** [comment]
关于 1 这个仍旧是需要修改代码的，我觉得 commandlet 可能更合适一些，不需要再修改 puerts 的代码，而且项目可以根据自己的实际自行调用，关于 2 的话，目前我导出 Typing 会出现在项目最外层。。这么设计的目的是什么呢，我感觉放在插件文件夹内更合适

**Comment by chexiongsheng** [comment]
commandlet 不是有时有些模块没加载么？ExecCmds没这问题，而且不用修改代码更好些。
Typing放项目更合理些，Plugins是可以支持安装到引擎目录的（目前已经支持，但现在没发到epic的market place，但可以自行编译放入），Typing放Plugins目录各个项目会冲突。

**Comment by hewenning** [comment]
commandlet 暂时没有遇到什么问题，我看 ExecCmds 有可能导致蓝图生成不全，还是要像 [llxisdsh] 说的补全命令（仍旧需要修改代码）才行，而且 commandlet 本身就是虚幻用于自动化任务的。commandlet 不会加载的应该是项目用到的编辑器插件，对于自动化任务或者是打包流水线本身就不能依赖于编辑器的插件做相关的工作。commandlet 比 ExecCmds 更适合做自动化任务。ExecCmds 命令通常是在编辑器或游戏运行时执行的，一些编辑器插件通过这种方式做倒是没有问题。如果项目流水线使用仍旧不推荐这种方式。

**Comment by hewenning** [comment]
2 的话我理解了，我们是每个项目根据需要安装 Puerts，声明的 Typing 文件都会在 Plugins/Puerts/Typing  文件夹下，而不是项目最外层文件夹下，这个我们做一些修改即可

**Comment by chexiongsheng** [comment]
ExecCmds和Commandlet是有区别的，区别是Commandlet时，一些插件是不会加载的（这会导致有些需要导出的插件类型的声明在Commandlet模式下，就丢失了），而ExecCmds就和正常启动编辑器一样，加载的插件数量什么的都是一致的

**Comment by hewenning** [comment]
我上面已经回复过了，commandlet 不会加载的应该是项目用到的编辑器插件，对于自动化任务或者是打包流水线本身就不能依赖于编辑器的插件做相关的工作
