### ISSUE TITLE
[UE] Bug: 内存泄漏，不用的js模块源码和compiled code不会被释放

### ISSUE THREAD

**Issue by wusidn** [Tencent/puerts#1554]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.0

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

加载js模块到内存中即使不使用也不会释放  使用require也是同样的结果这里为了方便与浏览器对比使用new Function
从下面的图片看以看出内存只有增加没有减少，一直执行
```
let num = 0;
    setInterval(() => {
        (new Function(`/*调试器通过websocket发送断点信息，可能断点生效前脚本已经执行完备，可以通过debugger语句来主动触发断点调试器通过websocket发送断点信息，可能断点生效前脚本已经执行完备，可以通过debugger语句来主动触发断点*/
            console.log(${++num}${num}${num}${num})
        `))();
    }, 1000);
```
![image](https://github.com/Tencent/puerts/assets/12872482/ea71592a-c4e2-4d5c-b64b-086d5728cb45)
持续执行一段时间内存明显上涨
![image](https://github.com/Tencent/puerts/assets/12872482/d7db014f-9321-489f-a10b-094445c0e99c)

浏览器中执行相同代码内存快照并不会增加字符串和代码
通过持有函数引用的方式可以看出内存确实被释放了
···
    <head>
        <title>测试源码内存回收</title>
        <script type="text/javascript">

            window.onload = function() {
                console.log("window onload");
                let num = 0;
                const funcs = [];

                const wmap = new WeakMap();

                document.querySelector("#test").addEventListener("click", () => {
                    console.log(`-->> click`);
                    num++;
                    const func = (new Function(`/*调试器通过websocket发送断点信息，可能断点生效前脚本已经执行完备，可以通过debugger语句来主动触发断点调试器通过websocket发送断点信息，可能断点生效前脚本已经执行完备，可以通过debugger语句来主动触发断点*/
            console.log(${++num}${num}${num}${num})
        `));
                    funcs.push(func);
                    func();
                });

                document.querySelector("#clear").addEventListener("click", () => {
                    console.log(`-->> clear`);
                    funcs.length = 0;
                });
            }
            
        </script>
    </head>
    <body>
        <button id="test">test</button>
        <button id="clear">clear</button>
    </body>
···
点击测试按钮内存增加
![image](https://github.com/Tencent/puerts/assets/12872482/d7e38ad7-3c63-4098-9a49-ba769bfdec57)
点击清除按钮内存释放
![image](https://github.com/Tencent/puerts/assets/12872482/b6d1fa8b-f292-4c67-b240-1599990e42c2)

**Comment by chexiongsheng** [comment]
如果是cjs模块，加载后不释放是合理的，这是cjs的特点，require后会放到cache以备下次使用，你在nodejs中实现也会如此。

你的测试代码测试的就完全是v8的行为了，puerts没对v8做什么修改。如果真有问题，应该去google那里提。但我觉得不太可能是v8的问题。
首先，你的测试代码就不完全对等；
其次，gc策略是个内部行为，它会根据当前的内存使用情况自行决定要不要gc，有可能是浏览器内存更紧张，有可能是配置了更激进的gc策略；

你完全可以在puerts的测试中加个主动强制gc请求来验证是不是真的没释放：
1、打开这两行注释：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L342
2、在调用你创建的Function后面加上`globalThis.gc();`

**Comment by wusidn** [comment]
测试代码不对等问题：浏览器中执行相同的代码内存就不会涨 查看内存快照的时候就触发gc释放了
globalThis.gc()试过了 没作用

**Comment by wusidn** [comment]
关于gc策略问题，我的项目中源码体积非常大 频繁require脚本内存无限增加最后触发OOM崩溃

**Comment by chexiongsheng** [comment]
> 我用node后端测试了结果也是不会释放，直接用node是可以释放的

你真的测试了？
我刚刚看了16.16的代码，cache的逻辑和我的差不多，都是path做key，存在Object里头，你说的可以释放是不可能的（如果是Weak类型的容器才可能自动释放）。
cache创建的地方：https://github.com/nodejs/node/blob/v16.16.0/lib/internal/modules/cjs/loader.js#L193
cache访问：https://github.com/nodejs/node/blob/v16.16.0/lib/internal/modules/cjs/loader.js#L767

**Comment by chexiongsheng** [comment]
最新的node cjs也是强引用cache：https://github.com/nodejs/node/blob/main/lib/internal/modules/cjs/loader.js#L269

不过你那new Function倒有可能是chrome和nodejs对v8做了某些参数设置释放了。不过你不是通过eval或者new Function来动态生成，也不会动态增加。

**Comment by wusidn** [comment]
> > 我用node后端测试了结果也是不会释放，直接用node是可以释放的
> 
> 你真的测试了node的require可以释放？ 我刚刚看了16.16的代码，cache的逻辑和我的差不多，都是path做key，存在Object里头，你说的可以释放是不可能的（如果是Weak类型的容器才可能自动释放）。 cache创建的地方：https://github.com/nodejs/node/blob/v16.16.0/lib/internal/modules/cjs/loader.js#L193 cache访问：https://github.com/nodejs/node/blob/v16.16.0/lib/internal/modules/cjs/loader.js#L767

因为我调用forceReeload把缓存强制清除了，项目有需求刷新js代码又想重新运行装饰器，使用hotReload只会刷新代码不会重新运行一遍代码

**Comment by terst6** [comment]
settimeout 一定要保存具柄，如果相同函数下一次调用还没有结束，并释放具柄，我会先释放。timer里面的功能如果你不释放，地图结束了，它还会继续运行

**Comment by wusidn** [comment]
> 最新的node cjs也是强引用cache：https://github.com/nodejs/node/blob/main/lib/internal/modules/cjs/loader.js#L269
> 
> 不过你那new Function倒有可能是chrome和nodejs对v8做了某些参数设置释放了。

这个new function有没有解决思路，只要这个可以释放就能满足我的需求

**Comment by chexiongsheng** [comment]
> > 最新的node cjs也是强引用cache：https://github.com/nodejs/node/blob/main/lib/internal/modules/cjs/loader.js#L269
> > 不过你那new Function倒有可能是chrome和nodejs对v8做了某些参数设置释放了。
> 
> 这个new function有没有解决思路，只要这个可以释放就能满足我的需求

看下nodejs的代码，我找也是得看

**Comment by chexiongsheng** [comment]
把更多信息发上来，chrome的版本，内置v8版本和你本地puerts用的v8一样么？
nodejs是什么版本？是怎么测试的，也是new Function么？能释放么？（cjs就不用讨论了）

**Comment by wusidn** [comment]
> 把更多信息发上来，chrome的版本，内置v8版本和你本地puerts用的v8一样么？ nodejs是什么版本？是怎么测试的，也是new Function么？能释放么？（cjs就不用讨论了）

目前我是用较新版本Edge浏览器测试的，v8版本更新一些。 nodejs用的v18.6.0 也是测试的new Function 是可以释放的。我再用使用v8-9.4版本的chrome和node 16测试一下 稍后附上结果

**Comment by wusidn** [comment]
> > 把更多信息发上来，chrome的版本，内置v8版本和你本地puerts用的v8一样么？ nodejs是什么版本？是怎么测试的，也是new Function么？能释放么？（cjs就不用讨论了）
> 
> 目前我是用较新版本Edge浏览器测试的，v8版本更新一些。 nodejs用的v18.6.0 也是测试的new Function 是可以释放的。我再使用v8-9.4版本的chrome和node 16测试一下 稍后附上结果

使用chrome93.0.4577.82 测试确实有相同的问题，应该是需要升级v8版本解决这个问题了

**Comment by chexiongsheng** [comment]
没问题的chrome是哪个版本的v8呢？

**Comment by wusidn** [comment]
> 没问题的chrome是哪个版本的v8呢？

应该都没问题 只不过每个版本的gc策略不一样 11.8 版本不用的模块会立即释放 9.4版本会在达到一定内存阈值后释放之前不用的模块 推测是在事件循环之后 因为我使用for循环创建巨量function会把系统内存用完
