### ISSUE TITLE
[Unity] System.DateTime 生成的类型声明不正确

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#1565]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0

### Unity的版本 | Unity Version

2022.3.8

### 发生在哪个平台 | Platform

Other

### 错误信息 | Error Message

C# 中的 `System.DateTime` 类型在生成的 TS 类型声明中被转换为了 JS 的 `Date` 但在实际运行时并不是 JS 的 `Date` 类型对象。

Related #1145

### 问题重现 | Bug reproduce

```ts
const info = new DirectoryInfo('Assets');
const date = info.LastWriteTimeUtc; // 这里 date 被推断为 Date 类型但实际为 CS.System.DateTime
```

**Comment by chexiongsheng** [comment]
之前版本确实是映射到js的Date，2.0后改了，但可能typing生成那没改。
