### ISSUE TITLE
[Unity] Puerts.Utils.GetExtensionMethodsOf的消耗

### ISSUE THREAD

**Issue by cuinc** [Tencent/puerts#1566]
## detail | 详细描述
在windows UnityProfiler GetExtensionMethodsOf CPU 用了1727ms,内存使用了7.1M,这个是否正常情况？
![image](https://github.com/Tencent/puerts/assets/8214244/f0b740ad-130f-4ead-a731-6adfd0be8995)

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/blob/master/unity/Assets/core/upm/Runtime/Src/Default/TypeMapping/TypeRegister.cs#L542C5-L542C33
是正常情况见此处代码
