### ISSUE TITLE
[Unity] Bug: xil2cpp unity 2022 ios 编译失败

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1573]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.2

### Unity的版本 | Unity Version

2022.3.11f1

### 发生在哪个平台 | Platform

Editor(mac)， xcode 15

### 错误信息 | Error Message

![image](https://github.com/Tencent/puerts/assets/3063621/b2fd21a0-9bf7-4fe7-b13c-7629451e29d9)

### 问题重现 | Bug reproduce

[repro.zip](https://github.com/Tencent/puerts/files/13110403/repro.zip)
直接用这个工程打xil2cpp ios工程即可

**Comment by dunadain** [comment]
![image](https://github.com/Tencent/puerts/assets/3063621/916cf3fc-5b1f-467d-a9da-477936ecc63b)
貌似debug + development build 才会编译报错。
如果改成release就可以了

**Comment by birnfly** [comment]
这个报错的原因是因为二进制文件太大，超过了限制。
解决的办有：
1、提高 unity strip level
2、xil2cpp 构建时使用 release模式
3、unity构建成release模式
4、删除不必要的库
5、将静态库修改为动态库
6、xcodebuild 不要使用debug，改为release模式

**Comment by dunadain** [comment]
只有puerts一个库，看来只能release了
