### ISSUE TITLE
[Unity] Bug: xil2cpp发包(windows/mac/ios) uitoolkit的button 会报 add_clicked is not a function

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1574]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.2

### Unity的版本 | Unity Version

2022.3.11f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

add_clicked is not a function

### 问题重现 | Bug reproduce

[TestClickBug.zip](https://github.com/Tencent/puerts/files/13120219/TestClickBug.zip)
用这个项目打xil2cpp ios包就能复现
const uiDoc = go.GetComponent('UIDocument');
const root = uiDoc.rootVisualElement;
const btn = root.Q('btn');
btn.add_clicked(() => {
      console.log('uitoolkit btn');
});
这里btn能取到，但add_clicked方法缺失

**Comment by dunadain** [comment]
[TestClickBug2.zip](https://github.com/Tencent/puerts/files/13162273/TestClickBug2.zip)
更新下复现工程，前面的忘了把button绑定出来

**Comment by dunadain** [comment]
无论发啥包都有问题。而且是最新的才改出的问题。记得之前发包一直没问题，更新到最新就不行了

**Comment by chexiongsheng** [comment]
被剪裁了。要生成下link.xml吧

**Comment by dunadain** [comment]
![image](https://github.com/Tencent/puerts/assets/3063621/468adaed-91ed-49fb-b607-5c91a7043ac8)
![image](https://github.com/Tencent/puerts/assets/3063621/9bb68735-dfa0-49a0-af0a-26f9a5a73fd9)
都有，发出xil2cpp包就不行了。而且add_clicked 不是他原生的方法，是给event单独加的吧

**Comment by chexiongsheng** [comment]
“不是他原生的方法”
你的意思是Extension Methods吧？

**Comment by dunadain** [comment]
应该是c# event 在js端使用的时候，发布xil2cpp 都会有问题。add_clicked是对clicked event的一个wrapper

**Comment by dunadain** [comment]
就是add_clicked 是给原生 clicked event的加的wrapper吧
在c#端使用是 button.clicked += () => {};
在js端要用button.add_clicked(() => {});

**Comment by dunadain** [comment]
我怀疑是所有c# event在js端使用 发xil2cpp都会有这个问题

**Comment by dunadain** [comment]
感觉是被裁减，但搞不清为啥，改生成的都生成了

**Comment by dunadain** [comment]
找到问题了。是因为uitoolkit取button都是用的extension method. 然后方法参数都有默认值，导致传参失败
参见
https://github.com/Tencent/puerts/issues/1586
