### ISSUE TITLE
unreal  调试，断点全部显示unbound breakpoint

### ISSUE THREAD

**Issue by wangyhbupt** [Tencent/puerts#158]
下载了demo工程，按照 unreal debug指引 里面描述的配置方法
能够attach成功，但是所有的断点显示unbound breakpoint
请问这是什么原因
项目的launch.json和tsconfig.json都没有改动过

**Comment by chexiongsheng** [comment]
你是自己创建FJsEnv，还是用自动生成蓝图功能？

**Comment by chexiongsheng** [comment]
应该是文件名对不上，vscode要打开puerts_unreal_demo目录，而不是TsProj

**Comment by wangyhbupt** [comment]
原因找到了
是因为demo启动的时候，在
FPuertsModule::StartupModule和UTsGameInstance::OnStart中分别创建了一个FJsEnv
调试器Attach的是第一个，而执行的测试代码运行在第二个中
