### ISSUE TITLE
[UE] Bug: 偶现带FJSObject的UObject析构时崩溃

### ISSUE THREAD

**Issue by scutDavid** [Tencent/puerts#1582]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

4.24

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

给Listview的ItemWidget 写了个FJSObject成员（用UPROPERTY包裹），
![image](https://github.com/Tencent/puerts/assets/30872025/7067ca0e-7d0f-4bb4-bf2d-ae6fca1b8d07)
发现ItemWidget在GC时 会调到FJSObject的析构函数，然后就崩溃了。
堆栈：
![image](https://github.com/Tencent/puerts/assets/30872025/e89db66e-8449-467d-844b-60221f4dee9b)
![image](https://github.com/Tencent/puerts/assets/30872025/4ba83e49-8a16-4cca-a6ba-645f10a98a48)
之前看作者在这个issue提过， https://github.com/Tencent/puerts/issues/1539#issuecomment-1736823380
不知道问题是出在哪里 以及得怎么修复呢 是FJSObject析构时 对应的JS对象还在吗。 我这里会在IteWidget析构前把ItemWidget
的JS 对象设为undefined的。

### 问题重现 | Bug reproduce

给UClass 写一个UProperty的FJSObject类型的成员，析构时可能出现。

**Comment by chexiongsheng** [comment]
> 不知道问题是出在哪里 以及得怎么修复呢

你更新到最新版本试试

**Comment by chexiongsheng** [comment]
你这个和 https://github.com/Tencent/puerts/issues/1539#issuecomment-1736823380 不太一样
你这个时FJsObject析构时，JsEnv已经析构导致的。
比较合理的做法应该时业务负责在虚拟机销毁前，销毁指向js资源的对象。

不过我试下加个规避代码，你试试看能解决不。

**Comment by scutDavid** [comment]
> 你这个和 [#1539 (comment)](https://github.com/Tencent/puerts/issues/1539#issuecomment-1736823380) 不太一样 你这个时FJsObject析构时，JsEnv已经析构导致的。 比较合理的做法应该时业务负责在虚拟机销毁前，销毁指向js资源的对象。
> 
> 不过我试下加个规避代码，你试试看能解决不。

所以Unreal v1.0.5也有可能还未解决是吧。  我试下提前销毁这个办法。

**Comment by chexiongsheng** [comment]
> > 你这个和 [#1539 (comment)](https://github.com/Tencent/puerts/issues/1539#issuecomment-1736823380) 不太一样 你这个时FJsObject析构时，JsEnv已经析构导致的。 比较合理的做法应该时业务负责在虚拟机销毁前，销毁指向js资源的对象。
> > 不过我试下加个规避代码，你试试看能解决不。
> 
> 所以Unreal v1.0.5也有可能还未解决是吧。 我试下提前销毁这个办法。

你更新下，或者合入我刚刚提交的commit。

**Comment by scutDavid** [comment]
好的

**Comment by mysticfarer** [comment]
在C++侧持有FJsObject，等于持有了JS object的引用，这容易在两套GC间（UE & v8）产生循环引用导致释放不掉吧？ @chexiongsheng

**Comment by chexiongsheng** [comment]
> 在C++侧持有FJsObject，等于持有了JS object的强引用，这容易在两套GC间（UE & v8）产生循环引用导致释放不掉吧？ @chexiongsheng

这本来在所有双gc系统都不可避免。
有个新加的api，你可以告诉v8 gc引用关系：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Public/V8Object.hpp#L165
