### ISSUE TITLE
[UE] Bug: FinalizationRegistry 无法正常使用

### ISSUE THREAD

**Issue by parnny** [Tencent/puerts#1585]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### UE的版本 | UE Version

5.3.1

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

无法正常收到js obj销毁的回调

### 问题重现 | Bug reproduce

let obj = {
    name: "a",
};
let info = {
    name: "b",
};

const registry = new FinalizationRegistry(function (val) {
if (val === "obj") {
    console.error("obj对象被销毁");
}
if (val === "info") {
    console.error("info对象被销毁");
}
});

registry.register(obj, "obj");
registry.register(info, "info");
obj = null;
info = null;

C++：
FJsEnv::LowMemoryNotification()

**Comment by zhaojunmeng** [comment]
FinalizationRegistry，从JS引擎的实现角度，不保证一定会被调用的，参考：

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry#notes_on_cleanup_callbacks

> A conforming JavaScript implementation, even one that does garbage collection, is not required to call cleanup callbacks. When and whether it does so is entirely down to the implementation of the JavaScript engine. When a registered object is reclaimed, any cleanup callbacks for it may be called then, or some time later, or not at all.
