### ISSUE TITLE
[UE] Bug: 打包模式下BeginDeferredActorSpawnFromClass不会生成一个Character

### ISSUE THREAD

**Issue by 313364973** [Tencent/puerts#1594]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

5.3.1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

使用默认的第三人称模板的角色，在QuickStart.ts里执行let uCharacterClass = UE.Class.Load('/Game/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.BP_ThirdPersonCharacter_C');
const ThirdPersonCharacter = blueprint.tojs<typeof UE.Game.ThirdPerson.Blueprints.BP_ThirdPersonCharacter.BP_ThirdPersonCharacter_C>(uCharacterClass);
let character = UE.GameplayStatics.BeginDeferredActorSpawnFromClass(gameInstance, ThirdPersonCharacter.StaticClass(), undefined) as UE.Game.ThirdPerson.Blueprints.BP_ThirdPersonCharacter.BP_ThirdPersonCharacter_C
UE.GameplayStatics.FinishSpawningActor(character, undefined)；
生成一个第三人称模板的角色，在编辑器模式下没有问题，可以生成，但是打包window后，运行，不见角色生成，但是其他蓝图是可以生成的，不知道和Character有啥关系吗

### 问题重现 | Bug reproduce

使用默认的第三人称模板的角色，在QuickStart.ts里执行let uCharacterClass = UE.Class.Load('/Game/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.BP_ThirdPersonCharacter_C');
const ThirdPersonCharacter = blueprint.tojs<typeof UE.Game.ThirdPerson.Blueprints.BP_ThirdPersonCharacter.BP_ThirdPersonCharacter_C>(uCharacterClass);
let character = UE.GameplayStatics.BeginDeferredActorSpawnFromClass(gameInstance, ThirdPersonCharacter.StaticClass(), undefined) as UE.Game.ThirdPerson.Blueprints.BP_ThirdPersonCharacter.BP_ThirdPersonCharacter_C
UE.GameplayStatics.FinishSpawningActor(character, undefined)；
生成一个第三人称模板的角色，在编辑器模式下没有问题，可以生成，但是打包window后，运行，不见角色生成，但是其他蓝图是可以生成的，不知道和Character有啥关系吗

**Comment by 313364973** [comment]
试了下，在QuickStart.ts中增加了一个settimeout再执行生成，就可以了

**Comment by chexiongsheng** [comment]
创建时机问题吧。
这类问题是ue的规则。puerts只是启动虚拟机，让js能调用到引擎的api。
至于具体某引擎api有什么限制，应查阅并遵从ue的文档。
