### ISSUE TITLE
[Unity] Bug: 打包到ios版本12.5.7运行崩溃

### ISSUE THREAD

**Issue by fuhongpu3299** [Tencent/puerts#1599]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

已升级到最新

### Unity的版本 | Unity Version

2021.3.1f1c1

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

->  0x100ae8000: .long  0xfeedfacf                ; unknown opcode
    0x100ae8004: .long  0x0100000c                ; unknown opcode
    0x100ae8008: udf    #0x0
    0x100ae800c: udf    #0x6
    0x100ae8010: udf    #0x38
    0x100ae8014: udf    #0x1c68
    0x100ae8018: .long  0x00918085                ; unknown opcode
    0x100ae801c: udf    #0x0

打印输出看到再执行PuertsDLL.CreateJSEngine();得时候报错

### 问题重现 | Bug reproduce

![image](https://github.com/Tencent/puerts/assets/30929529/27213c8d-e88a-41fb-869c-d82457f7157a)
![image](https://github.com/Tencent/puerts/assets/30929529/9a9ab7f4-2361-44e6-87a5-9320c1f0b1f5)

**Comment by fuhongpu3299** [comment]
经过测试只有ios版本13以下会出现,13以上就没有问题,

**Comment by chexiongsheng** [comment]
有可能是v8的9.4版本不支持低版本的ios。
可以试试构建一个8.4版本的plugin，方法看这里：https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/other/building.md

**Comment by fuhongpu3299** [comment]
node ../cli make --backend v8_8.4 --platform ios 如此构建的时候报错
![image](https://github.com/Tencent/puerts/assets/30929529/2c95387f-ad59-4901-aa71-0284abf8ff0f)

**Comment by fuhongpu3299** [comment]
而且9.4的库也非常卡,有没有办法只想.cn地址呢

**Comment by fuhongpu3299** [comment]
> 有可能是v8的9.4版本不支持低版本的ios。 可以试试构建一个8.4版本的plugin，方法看这里：https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/other/building.md

我尝试了构建,下面是构建时候出现的问题,应该如何去处理呢

**Comment by fuhongpu3299** [comment]
> 有可能是v8的9.4版本不支持低版本的ios。 可以试试构建一个8.4版本的plugin，方法看这里：https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/other/building.md

![image](https://github.com/Tencent/puerts/assets/30929529/2c97b7af-4b0c-472a-9060-c619f92d5c2d)

**Comment by zombieyang** [comment]
重复 #1601
