### ISSUE TITLE
[Unity] Bug: c#定义JSObject，js端返回null，会崩溃

### ISSUE THREAD

**Issue by ctxdegithub** [Tencent/puerts#1606]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.3

### Unity的版本 | Unity Version

2022.3.10f

### 发生在哪个平台 | Platform

Editor(mac)

### 问题重现 | Bug reproduce

```csharp
public class JSObjectTest {
    public JSObject JsObj;
}
```

```ts
function tryCreateJsObject(jsObjTest: CS.JSObjectTest) {
    jsObjTest.JsObj = null;
}
```

JsObj赋值为null是会崩溃

**Comment by chexiongsheng** [comment]
是xil2cpp吗？

**Comment by chexiongsheng** [comment]
在master，普通模式和xil2cpp我都试过，都没崩溃，你看是不是后续版本已经修复了

**Comment by ctxdegithub** [comment]
master分支
```cs
public class HelloWorlder : MonoBehaviour
{
    public static JSObject JsObj;
    private JsEnv env;
    void Start()
    {
        env = new JsEnv(new DefaultLoader());
        env.Eval("console.log(CS.HelloWorlder.JsObj);");
    }
}
```
运行后，直接访问JsObj会报异常
![image](https://github.com/Tencent/puerts/assets/8472028/56b860e4-3cec-41ac-bb4c-b2db80624f28)
![image](https://github.com/Tencent/puerts/assets/8472028/28e501b0-74bf-4a9f-873f-a90e35cb5056)

**Comment by chexiongsheng** [comment]
这种比较容易修复，建议你直接修复了提PR。
如果你想修的话，别用?语法糖，puerts需要在比较低的c#版本下运行。
