### ISSUE TITLE
[UE] suggestion: PuerTS as Engine Plugin

### ISSUE THREAD

**Issue by faseceroo** [Tencent/puerts#1608]
Currently, using PuerTS requires installation and compilation within each individual project.

Is there a way to install the plugin inside Epic plugin folder? 

It could be then easily activated upon project creation, simplifying the workflow working with PuerTS across multiple projects.

**Comment by chexiongsheng** [comment]
You can do it manually:
1.build plugin 
for window and android: 
`YOUR_UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildPlugin -Plugin="unreal\Puerts\Puerts.uplugin" -Package="output" -Rocket -TargetPlatforms=Win64+Android -VS2019`
for mac and ios:
`YOUR_UE_PATH\Engine/Build/BatchFiles/RunUAT.sh BuildPlugin -Plugin=unreal/Puerts/Puerts.uplugin -Package=output -Rocket -TargetPlatforms=Mac+IOS`
2. place the built plugin to `YOUR_UE_PATH\Engine\Plugins`

**Comment by faseceroo** [comment]
The plugin has been compiled sucessfully and copied to UE_PATH\Engine\Plugins. After create a test project and enable Puerts, upon restarting I get this message
![image](https://github.com/Tencent/puerts/assets/93630866/67cfb4f7-8515-41f1-8ee4-064805983b83)

**Comment by chexiongsheng** [comment]
built plugin may in here: 
C:\PROGRA~1\EPICGA~1\UE_5.3\output\HostProject\Plugins\Puerts

**Comment by faseceroo** [comment]
Made some progress, I've set `Plugin="..."` value to the path of a compiled Puerts plugin as a project plugin first. I have renamed the output as Puerts and copied it to `UE_PATH\Engine\Plugins`.

Not it works, when I create a new project, I enable the plugin, after a restart it enters correctly so the plugin is working as an engine plugin. I click the **Puerts** button in the toolbar to create the **Typing** folder and then I manually create the **TypeScript** folder.
![image](https://github.com/Tencent/puerts/assets/93630866/717f95ef-cad8-49c0-8322-b39d49e4c69e)

Now I don't know to activate **enable_puerts_module.js** since I don't have the plugin in the project.

If I open a test file in VSCode this happens
![image2](https://github.com/Tencent/puerts/assets/93630866/805c52c5-f57a-4d89-b5bf-06a9d9fa1b02)

**Comment by chexiongsheng** [comment]
Open enable_puerts_module.js with text editor to have a look at what jobs it do and do it manually.
including install libs, create tsconfig.json (project file just similar to *.sln for vs project), tsconfig.json not existing make type info of 'ue' not useable.

**Comment by faseceroo** [comment]
I was expecting this answer. I'll work on this tomorrow, thank you so much for helping me. As a side note, it would be nice to find the plugin in the marketplace :). Programming with typescript is way more easy and fast than c++, and a lot better than BP.

**Comment by faseceroo** [comment]
Copying the instructions in `enable_puerts_module.js` manually has solved the problem. I can now create projects easily, copy a few folders, and have everything working. It's much faster and saves a lot of disk space.

In addition, I had to copy the `ThirdParty/V8` folder to the plugin within the epic folder for it to work correctly.

The only thing I'm missing is being able to package successfully. I can package Epic's projects, but when I try to package one using the engine's puerts plugin, the output says that a dll does not exist:

`UATHelper: Packaging (Windows): Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Binaries\DotNET\UnrealBuildTool\Plugins\CSharpParamDefaultValueMetas\CSharpParamDefaultValueMetas.dll'`

Who knows which installer installs this dll...

**Comment by faseceroo** [comment]
I see CSharpParamDefaultValueMetas belongs to Puerts but it is located in a different directory:
`C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\Puerts\Source\CSharpParamDefaultValueMetas\obj\Development`
