### ISSUE TITLE
[UE] Bug: FObjectPropertyTranslator::UEToJs函数偶现Crash

### ISSUE THREAD

**Issue by coder2018cp** [Tencent/puerts#1612]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.3

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

偶现Crash，根据堆栈可以看到应该是TArray类型数据Get函数时挂掉了。
![image](https://github.com/Tencent/puerts/assets/43199779/59c262b9-2ae9-4b4f-a599-f7684e55b65b)

详细Crash堆栈如下：

1 xxGame 0x0000000105e9a104 UObjectBase::IsValidLowLevelFast(bool) const (./Runtime/CoreUObject/Private/UObject/UObjectBase.cpp:360) 
2 xxGame 0x000000010407dbe8 puerts::FObjectPropertyTranslator::UEToJs(v8::Isolate*, v8::Local<v8::Context>&, void const*, bool) const (/xxGame/Plugins/Puerts/Source/JsEnv/Private/PropertyTranslator.cpp:473) 
3 xxGame 0x000000010407dbe8 puerts::FObjectPropertyTranslator::UEToJs(v8::Isolate*, v8::Local<v8::Context>&, void const*, bool) const (/xxGame/Plugins/Puerts/Source/JsEnv/Private/PropertyTranslator.cpp:473) 
4 xxGame 0x0000000103f2add0 puerts::FScriptArrayWrapper::Get(v8::FunctionCallbackInfo<v8::Value> const&) (/xxGame/Plugins/Puerts/ThirdParty/v8/Inc/v8.h:11046) 
5 xxGame 0x00000001015f4e70 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 536 
6 xxGame 0x00000001015f4418 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 460 
7 xxGame 0x00000001015f3bf4 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 224 
8 xxGame 0x000000010150488c _Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 108 
9 xxGame 0x000000010149d634 _Builtins_InterpreterEntryTrampoline + 244 
10 xxGame 0x000000010149d634 _Builtins_InterpreterEntryTrampoline + 244 
11 xxGame 0x000000010149d634 _Builtins_InterpreterEntryTrampoline + 244 
12 xxGame 0x000000010149aee4 _Builtins_JSEntryTrampoline + 164 13 xxGame 0x000000010149ab88 _Builtins_JSEntry + 168

Crash时通过寄存器看到UEObject值为0x3f80000000000000。

### 问题重现 | Bug reproduce

iOS偶现, Android和PC暂未出现

**Comment by chexiongsheng** [comment]
看栈的话，比较有可能是这样的场景：ts/js中主动构造了一个TArray并持有，并往里面填入UObject。
这个场景下，UObject没有直接被js引用，puerts不会为此向ue的gc增加引用，而该TArray也没有被UObject引用，所以这些UObject会被清理。
清理的时候，因为这些UObject在js侧没直接引用，也不会触发puerts的ue对象生命周期跟踪，于是就是野指针了。

**Comment by isaf** [comment]
那这种情况要如何处理比较好呢？

**Comment by Lee-Ft** [comment]
车神你好，我们也遇到了类似的崩溃堆栈，这种间接引用有规避方案吗？已经开启了WITH_OUTER_LINK宏

**Comment by chexiongsheng** [comment]
> 车神你好，我们也遇到了类似的崩溃堆栈，这种间接引用有规避方案吗？已经开启了WITH_OUTER_LINK宏

类似堆栈不代表是类似原因。这个堆栈只是说明被访问的对象坏了，但不代表是弱引用导致被gc了。c++程序让一块内存坏掉的姿势有N种。
