### ISSUE TITLE
[UE] Bug: 撤销C++类的Mixin后没有正常恢复原来的行为

### ISSUE THREAD

**Issue by slowmna** [Tencent/puerts#1618]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

5.3.2 

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

定义一个MyActor类，在Tick中调用声明为BlueprintNativeEvent的TestUFun

```C++
// UFUNCTION(BlueprintNativeEvent)
// void TestUFun(double DeltaTime);

void AMyActor::TestUFun_Implementation(double DeltaTime)
{
	FRotator Rotator = GetActorRotation();
	SetActorRotation(FRotator(0, Rotator.Yaw + DeltaTime * 30, 0));
}

// Called every frame
void AMyActor::Tick(float DeltaTime)
{
	TestUFun(DeltaTime);
	Super::Tick(DeltaTime);
}
```

再创建一个蓝图类指定父类为刚刚的MyActor，添加一个StaticMesh组件网格体用自带的Cube。保存，然后拖拽蓝图到默认关卡里命名TestMyActor。
此时运行，可以看到TestMyActor在旋转。

编写一个TS脚本TS_Player，并将编译后的蓝图TS_Player拖拽到默认关卡里
```TypeScript
import * as UE from 'ue'
import {$ref, $unref, $set, argv, on, toManualReleaseDelegate, releaseManualReleaseDelegate, blueprint} from 'puerts';

class TS_Player extends UE.Character {

    //StaticMesh: UE.StaticMeshComponent;
    
    Constructor() {
        // this.MixinCPPClass();
    }
    MixinCPPClass(): void {
        const MixinUE = blueprint.tojs<typeof UE.MyActor>(UE.MyActor.StaticClass());
        const MixinTestWithMixin = blueprint.mixin(MixinUE, ExtendMyActor);
    }
    
    UnMixinCPPClass(): void
    {
        const MixinUE = blueprint.tojs<typeof UE.MyActor>(UE.MyActor.StaticClass());
        const MixinTestWithMixin = blueprint.unmixin(MixinUE);
    }

interface ExtendMyActor extends UE.MyActor {}
class ExtendMyActor {
    ReceiveBeginPlay(): void {
        console.log("ExtendMyActor ReceiveBeginPlay");
    }

    TestUFun(delta : number):void {
        console.log("ExtendMyActor TS TestUFun");
        // this.CallFromTS();
    }
}

export default TS_Player;

```
可以看到这次执行之后之前的TestMyActor不再旋转了，而是不断的输出“ExtendMyActor TS TestUFun”Log。
然后停止运行后，注释掉TS_Player的Constructor调用MixinCPPClass，再次运行。依旧不转，而且也没有Log输出，断点后发现调用回了C++侧的TestUFun，但是参数和Tick的参数对不上，几乎为0。
![image](https://github.com/Tencent/puerts/assets/38640830/ece9e3a2-72cd-46c7-8045-d8b571a41b01)

![image](https://github.com/Tencent/puerts/assets/38640830/039a7ee4-37df-49b9-aee4-72546ed2c791)

试过在停止运行前主动调用UnMixinCPPClass还是有问题。

**Comment by chexiongsheng** [comment]
可以基于这个：https://github.com/chexiongsheng/puerts_unreal_demo
搞个可重现的例子吗？

**Comment by slowmna** [comment]
https://github.com/chexiongsheng/puerts_unreal_demo/compare/master...slowmna:puerts_unreal_demo:master
@chexiongsheng 提交了一个示例，把TS_Player拖到场景，TestMyActor拖到场景，运行后TestMyActor有个立方体。运行三次，分别不注释-注释-不注释，第一三次运行效果不一样
（开启这行后就不转了）
![image](https://github.com/Tencent/puerts/assets/38640830/84d0b383-c69f-419e-b44e-e03e860db3cd)

**Comment by chexiongsheng** [comment]
> [chexiongsheng/puerts_unreal_demo@master...slowmna:puerts_unreal_demo:master](https://github.com/chexiongsheng/puerts_unreal_demo/compare/master...slowmna:puerts_unreal_demo:master) @chexiongsheng 提交了一个示例，把TS_Player拖到场景，TestMyActor拖到场景，运行后TestMyActor有个立方体。运行三次，分别不注释-注释-不注释，第一三次运行效果不一样 （开启这行后就不转了） ![image](https://private-user-images.githubusercontent.com/38640830/292701936-84d0b383-c69f-419e-b44e-e03e860db3cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjE2MzgsIm5iZiI6MTcwMzU2MTMzOCwicGF0aCI6Ii8zODY0MDgzMC8yOTI3MDE5MzYtODRkMGIzODMtYzY5Zi00MTllLWI0NGUtZTAzZTg2MGRiM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAzMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjIwMTRjM2IwZWNhOTFhNmFlZTI3YzRjOTVjYjg5YjJlYzk4NzViMGQwYzNmOGQ5NWUzNDA4YzNkZmFkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0CzYWKmZd2MyfdPyj4NJZASKB11_lsbwfjLq29q2pDQ)

好的，谢谢。
顺便问下，你这工程不删ReactUMG在ue 5.3能编译得过吗？我这会报引擎里的Widget.h有语法错误。

**Comment by slowmna** [comment]
> > [chexiongsheng/puerts_unreal_demo@master...slowmna:puerts_unreal_demo:master](https://github.com/chexiongsheng/puerts_unreal_demo/compare/master...slowmna:puerts_unreal_demo:master) @chexiongsheng 提交了一个示例，把TS_Player拖到场景，TestMyActor拖到场景，运行后TestMyActor有个立方体。运行三次，分别不注释-注释-不注释，第一三次运行效果不一样 （开启这行后就不转了） ![image](https://private-user-images.githubusercontent.com/38640830/292701936-84d0b383-c69f-419e-b44e-e03e860db3cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjE2MzgsIm5iZiI6MTcwMzU2MTMzOCwicGF0aCI6Ii8zODY0MDgzMC8yOTI3MDE5MzYtODRkMGIzODMtYzY5Zi00MTllLWI0NGUtZTAzZTg2MGRiM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAzMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjIwMTRjM2IwZWNhOTFhNmFlZTI3YzRjOTVjYjg5YjJlYzk4NzViMGQwYzNmOGQ5NWUzNDA4YzNkZmFkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0CzYWKmZd2MyfdPyj4NJZASKB11_lsbwfjLq29q2pDQ)
> 
> 好的，谢谢。 顺便问下，你这工程不删ReactUMG在ue 5.3能编译得过吗？我这会报引擎里的Widget.h有语法错误。

可以编过，不知道你报的什么错？

**Comment by chexiongsheng** [comment]
报的错误和这个一样：https://forums.unrealengine.com/t/is-including-widgetcomponent-h-no-longer-possible-in-5-3/1388339

你是自己编译的ue还是官方下载的？我是官方下载的5.3.2版本。

**Comment by chexiongsheng** [comment]
还有个区别是你的工程在我这里编译还会报错找不到UStaticMeshComponent和UStaticMesh，得加相关的头文件。
这个可能和你那能编译有点关联，感觉是你那自动include了很多文件。

**Comment by chexiongsheng** [comment]
我用的是vs2022

**Comment by chexiongsheng** [comment]
另外，我跑你那demo好像也没看到立方体，更没看到转。

**Comment by slowmna** [comment]
> 另外，我跑你那demo好像也没看到立方体，更没看到转。

你已经解决了报错对吗？我首次出现是在官方Lyra工程，使用编译的5.3官方引擎。 后续这个demo复现用的是5.1官方安装版引擎，都未出现include报错。
立方体需要手动将Content/Blueprints/TestMyActor拖到你的场景中，我没有提交场景。启动后F8脱离控制双击大纲中TestMyActor定位查看
![image](https://github.com/Tencent/puerts/assets/38640830/5778fea4-9d48-4e28-be5f-ab2e9228acd7)
然后将Content/Blueprints/TypeScript/下的TS_Player拖到场景中，参照我前面说的修改TS_Player脚本测试。

**Comment by chexiongsheng** [comment]
Widget.h的报错只在5.3有，而且删了reactumg就可以了。这个报错我试过起一个新的空工程，搞个类继承UUserWidget就会有同样的报错。
比5.3低的都不会报错。

**Comment by chexiongsheng** [comment]
> > 另外，我跑你那demo好像也没看到立方体，更没看到转。
> 
> 你已经解决了报错对吗？我首次出现是在官方Lyra工程，使用编译的5.3官方引擎。 后续这个demo复现用的是5.1官方安装版引擎，都未出现include报错。 立方体需要手动将Content/Blueprints/TestMyActor拖到你的场景中，我没有提交场景。启动后F8脱离控制双击大纲中TestMyActor定位查看 ![image](https://private-user-images.githubusercontent.com/38640830/292819861-5778fea4-9d48-4e28-be5f-ab2e9228acd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDI1NTAsIm5iZiI6MTcwMzY0MjI1MCwicGF0aCI6Ii8zODY0MDgzMC8yOTI4MTk4NjEtNTc3OGZlYTQtOWQ0OC00ZTI4LWJlNWYtYWIyZTkyMjhhY2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAxNTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYWI3OWExYjgwY2QxNDc4NTQyMWVkMDVhZWE3NjVlMTFkMzI3MTdmYTMyZWRjYzU2NmY2NTQxYzEwNWEzYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrAJE4ZxOm6NomRlxsO32DwqcdcPrX1IoNJIGOzByM0) 然后将Content/Blueprints/TypeScript/下的TS_Player拖到场景中，参照我前面说的修改TS_Player脚本测试。

我是拖到场景了，没看到立方体，可能是我用5.3打开不兼容吧。也没看到转，我也没看到你哪里写逻辑让它转呀。是不是漏提交东西了？

**Comment by slowmna** [comment]
最新的提交里有这个啊， 我昨天还特意检查了下，MyActor.cpp, 
https://github.com/chexiongsheng/puerts_unreal_demo/compare/master...slowmna:puerts_unreal_demo:master
![image](https://github.com/Tencent/puerts/assets/38640830/872bb540-3387-4a19-b440-acc345b26530)

**Comment by chexiongsheng** [comment]
我在5.2重现了，确实很奇怪的现象。都重现调用回c++了，参数确不对。

**Comment by chexiongsheng** [comment]
你试试，我这里测试没问题了。

这问题是ue我认为不合理的一些设计导致的。

首先参数读取调用FFrame::StepCompiledIn，如果FFrame::Code不为空就执行（蓝图）指令，空就就通过反射获取。没mixin前是后者（原生实现也会用反射读参数？性能不太好）。

FFrame::Code是来自UFunction::Script.GetData()，比较坑的来自这里，Script是一个TArray，mixin的时候我把它保存，unmixin的时候我恢复到原来的UFunction里头，逻辑上没错。但一个空TArray没插入过任何数据GetData()返回为nullptr，但如果这个空的空TArray用另外一个空TArray赋值后，GetData()就不为nullptr了。也就是同样是元素为0，GetData()返回是不确定的，但FFrame::StepCompiledIn却依赖了这不确定。
如果是我，至少FFrame::Code的初始化应该改为Code = Scripts.Num() ?  Scripts.GetData() : nullptr;
