### ISSUE TITLE
[Unity] Bug: XCODE升级15.1后，原有项目启动crash

### ISSUE THREAD

**Issue by ffllyy012** [Tencent/puerts#1619]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4.1

### Unity的版本 | Unity Version

2019.4.40f

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

    0x10dcea10c <+28>:  mov    x0, x19
    0x10dcea110 <+32>:  bl     0x10de49670               ; v8::Value::IsObject() const
    0x10dcea114 <+36>:  cbz    w0, 0x10dcea28c           ; <+412>
    0x10dcea118 <+40>:  mov    x0, x20
    0x10dcea11c <+44>:  bl     0x10de47188               ; v8::Isolate::GetCurrentContext()
    0x10dcea120 <+48>:  mov    x21, x0
    0x10dcea124 <+52>:  mov    x0, x19
    0x10dcea128 <+56>:  mov    x1, x21
    0x10dcea12c <+60>:  bl     0x10de49ce8               ; v8::Value::ToObject(v8::Local<v8::Context>) const
    0x10dcea130 <+64>:  mov    x19, x0
    0x10dcea134 <+68>:  cbz    x0, 0x10dcea3f8           ; <+776>
    0x10dcea138 <+72>:  adrp   x1, 8110
    0x10dcea13c <+76>:  add    x1, x1, #0xeed            ; "value"
    0x10dcea140 <+80>:  mov    x0, x20
    0x10dcea144 <+84>:  mov    w2, #0x0
    0x10dcea148 <+88>:  mov    w3, #-0x1
    0x10dcea14c <+92>:  bl     0x10de510e4               ; v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int)
    0x10dcea150 <+96>:  mov    x22, x0
    0x10dcea154 <+100>: cbz    x0, 0x10dcea400           ; <+784>
    0x10dcea158 <+104>: mov    x0, x19
    0x10dcea15c <+108>: mov    x1, x21
    0x10dcea160 <+112>: mov    x2, x22
    0x10dcea164 <+116>: bl     0x10de4cd10               ; v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
    0x10dcea168 <+120>: cbz    x0, 0x10dcea28c           ; <+412>
    0x10dcea16c <+124>: mov    x19, x0
    0x10dcea170 <+128>: mov    x0, x20
    0x10dcea174 <+132>: bl     0x10de47188               ; v8::Isolate::GetCurrentContext()

### 问题重现 | Bug reproduce

项目编译后，执行若干脚本，然后使用XCODE15版本进行编译
14.3.1编译运行正常
15.1编译运行crash

**Comment by chexiongsheng** [comment]
你试试用你的环境从新编译v8，然后基于你编译的v8重新编译plugin

**Comment by ffllyy012** [comment]
有时间我试试看

**Comment by chexiongsheng** [comment]
"项目编译后，执行若干脚本，然后使用XCODE15版本进行编译"
意思是运行的过程中xcode编译吗？

**Comment by ffllyy012** [comment]
就是使用xcode15运行自己做的demo工程的意思

**Comment by chexiongsheng** [comment]
“项目编译后，执行若干脚本”意思就是在Unity下跑？
“使用XCODE15版本进行编译”就是在Unity生成的xcode工程上跑？

**Comment by ffllyy012** [comment]
包含puerts使用例子的Unity工程导出xcode工程，使用xcode15打开它，编译xcode工程并运行的意思

**Comment by chexiongsheng** [comment]
有没有在xcode重编译plugin试试呢？最好把v8也重编译

**Comment by ffllyy012** [comment]
没有，目前还是用的14.3.1，准备在临近4月29日版本废弃前试试重新编译或者更换puerts版本

**Comment by chexiongsheng** [comment]
可能和这个问题的原因一样：https://github.com/Tencent/puerts/issues/1669

你看是不是安装了，com.tencent.puerts.webgl，如果是的话，就删了。

**Comment by ffllyy012** [comment]
的确是使用了com.tencent.puerts.webgl，删除后使用xcode15正常了

**Comment by chexiongsheng** [comment]
那关单吧，不是这个仓库的问题，com.tencent.puerts.webgl那已经有人提issue了。
