### ISSUE TITLE
[UE] Bug: 关于TMap，Remove后遍历的问题

### ISSUE THREAD

**Issue by mimiky** [Tencent/puerts#1620]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.5

### UE的版本 | UE Version

5.1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

the argument is an invalid index

### 问题重现 | Bug reproduce
测试代码：
`let m1 = UE.NewMap(UE.BuiltinInt, UE.BuiltinInt);
 m1.Set(1001,1)
 m1.Set(1002,2)
 m1.Remove(1001)
 for (let i = 0; i < m1.Num(); i++) {
        let key = m1.GetKey(i);
        let value = m1.Get(key)
        console.log("key:"+key+ " value:"+value)
    }` ,
看了一下源码ts实现TMap的Remove方法调用的是RemoveAt：
![image](https://github.com/Tencent/puerts/assets/44563230/e7e4f99e-cba2-4034-a134-0ab73d79d00c)
但是这样会导致我在Ts中调用TMap的Remove，   for (let i = 0; i < m1.Num(); i++) 这样遍历会invalid index，能否RemoveAt后更新对应的索引？

**Comment by mimiky** [comment]
目前我的解决方法一个是遍历GetMaxIndex（），然后判断是否invalid ，第二个是写了一个GetKeys方法，但是目前ts端返回的是Array<TKey>;，暂时还不知道怎么弄成TArray,现在暂时用的第二个方法
`void FScriptMapWrapper::GetKeys(const v8::FunctionCallbackInfo<v8::Value>& Info)
{
    v8::Isolate* Isolate = Info.GetIsolate();
    v8::HandleScope HandleScope(Isolate);
    v8::Local<v8::Context> Context = Isolate->GetCurrentContext();

    auto Self = FV8Utils::GetPointerFast<FScriptMap>(Info.Holder(), 0);
    
    auto KeyPropertyTranslator = FV8Utils::GetPointerFast<FPropertyTranslator>(Info.Holder(), 1);
    auto KeyProperty = KeyPropertyTranslator->Property;
    auto ValuePropertyTranslator = FV8Utils::GetPointerFast<FPropertyTranslator>(Info.Holder(), 2);
    auto ValueProperty = ValuePropertyTranslator->Property;
    v8::Local<v8::Array> Keys = v8::Array::New(Isolate);
    if (!KeyPropertyTranslator->PropertyWeakPtr.IsValid() || !ValuePropertyTranslator->PropertyWeakPtr.IsValid())
    {
        Info.GetReturnValue().Set(Keys);
        FV8Utils::ThrowException(Isolate, "key/value info is invalid!");
        return;
    }

    auto ScriptLayout = GetScriptLayout(KeyProperty, ValueProperty);
    int32 Index = 0;
    int32 Count = Self->Num();
    while (Count)
    {
        if (Self->IsValidIndex(Index))
        {
            uint8* Data = reinterpret_cast<uint8*>(Self->GetData(Index, ScriptLayout));
            void* KeyPtr = Data + GetKeyOffset(ScriptLayout);
            Keys->Set(Context, Keys->Length(), KeyPropertyTranslator->UEToJs(Isolate, Context, KeyPtr, false)).FromJust();
            --Count;
        }

        ++Index;
    }

    Info.GetReturnValue().Set(Keys);
}`
`   interface TMap<TKey, TValue> {
        //...        
        GetKeys(): Array<TKey>;
       //...
    }`

**Comment by chexiongsheng** [comment]
这些都是UE接口的封装。
你了解了TMap，就知道这些接口怎么用了，还不知道可以在过往的issue找找，我应该回答过。

**Comment by chexiongsheng** [comment]
不用改puerts的源码，本来提供的api就足够遍历。ue的map和set都是基于稀疏数组，遍历方法同稀疏数组

**Comment by mimiky** [comment]
感谢车神，受教了
