### ISSUE TITLE
[UE]  萌新不清楚，为什么调用UE.uproperty注解会失效，但是import uproperty 之后直接调用uproperty是正常的

### ISSUE THREAD

**Issue by xiaoliubenliu** [Tencent/puerts#1621]
## detail | 详细描述

![38d1b7bfc6054b083acd1f033a7230ff](https://github.com/Tencent/puerts/assets/103810986/41b43cb0-0e2b-4a71-a045-13ec19cd062c)
![f3efeb03a36e2bc01978760ba04466c2](https://github.com/Tencent/puerts/assets/103810986/fe13464b-02cb-4e4c-9a45-80cf020829a4)

群里大大没有回复我的，(哭)

**Comment by xiaoliubenliu** [comment]
测试代码

import * as UE from 'ue'
import { uproperty } from 'ue';
class TsTestActor extends UE.Actor 
{
    @UE.uproperty.umeta(UE.uproperty.Category="TEST Property")
    value:number;
    
    @uproperty.umeta(uproperty.Category="TEST Property")
    value2:number;

}
export default TsTestActor;

**Comment by chexiongsheng** [comment]
提交这个特性的人写死了

**Comment by xiaoliubenliu** [comment]
哦哦，好的好的
