### ISSUE TITLE
[UE] Bug: 为ts UMG创建子类，蓝图全编译报循环引用错误

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1627]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

4.27.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

OwnerClass should not be 'REINST_'! This means that a REINST class was parented to another REINST class, causing unwanted recursion! /Engine/Transient.REINST_SKEL_TSUserWidget_Child_C_6

### 问题重现 | Bug reproduce

以官方事例为基础：BlockBreakerStarter-master

创建一个类：
TSUserWidget.ts:
import * as UE from 'ue'

import TS_Player from './TS_Player'

export class TSUserWidget extends UE.UserWidget {
    Pawn:TS_Player

    OnInitialized(): void {
        let PC = this.GetOwningPlayer()
        this.Pawn =PC.AcknowledgedPawn as TS_Player
        console.log("TSUserWidget ReceiveBeginPlay", PC, this.Pawn);
    }

    Test(): void {
        console.log("TSUserWidget Test", this.Pawn.FpsCamera);
    }
}

export default TSUserWidget

然后创建这个蓝图的子类，里面添加一个cavas panel后，添加一个按钮，按钮调用 Test()函数；然后在关卡蓝图创建并显示这个子类；运行程序，按钮功能正常工作。然后用以下命令全编译项目蓝图：
"path\UE4Editor.exe" "path\BlockBreakerStarter.uproject" -run=CompileAllBlueprints>1.txt
，就会报如下错误。
OwnerClass should not be 'REINST_'! This means that a REINST class was parented to another REINST class, causing unwanted recursion! /Engine/Transient.REINST_SKEL_TSUserWidget_Child_C_6

**Comment by chexiongsheng** [comment]
至少不支持继承UMG，动画和level。
UE内部对这些（可能还有更多）做了特殊处理，如果要支持，代码量多很多。

**Comment by terst6** [comment]
是否可以像slua那样，做一个UMG可以用的interface？

**Comment by chexiongsheng** [comment]
> 是否可以像slua那样，做一个UMG可以用的interface？

可以自己做？

**Comment by terst6** [comment]
感觉上，interface方式还是很丑，每一个UI都需要去设置一下。我目前的使用方式比这个方式干净，我用蓝图扩展函数定义一个全局GI变量函数，然后把对UI的操作做这个Ts的GI里面，这样在蓝图里，UI里取得GI然后调用里面的UI函数
