### ISSUE TITLE
[UE] Bug: 在setTimeout中清理自身后，嵌套的setInterval和setTimeout不会执行

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1631]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master 6256231

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

All

### 问题重现 | Bug reproduce

类似这么写的代码，test interval nest，test timeout nest不会输出，虽然代码写的有点奇怪，但是再chrome中可以正常运行，因为在复杂嵌套的时候很难保证在嵌套中没有清理自身的handle
```
        let a = setTimeout(() => {
            clearTimeout(a);
            console.warn(`test timeout`);
            setInterval(() => {
                console.warn(`test interval nest`);
            }, 1000);
        }, 1000);
```

```
        let a = setTimeout(() => {
            clearTimeout(a);
            console.warn(`test timeout`);
            setTimeout(() => {
                console.warn(`test timeout nest`);
            }, 1000);
        }, 1000);
```

原因是在clearTimeout的回调中释放了DelegateHandleId，然后在callback中调用setTimeout或者setInterval重新申请，callback调用结束后又再次删除了重新申请的DelegateHandleId

![image](https://github.com/Tencent/puerts/assets/5946974/e6e10140-55d2-469f-b8e7-ff51da2e150c)

在chrome中可以正常运行。所以感觉是不是可以在callback执行后，判断!Continue删除定时器的时候，判断一下执行Function前后的TimerInfos[DelegateHandleId].TickerHandle是否一致，判断id是否有被复用申请再删除

**Comment by lzj10** [comment]
如果可以的话我提个pr

**Comment by terst6** [comment]
感谢，正好游戏中遇到这个问题。
我还遇到代理具柄疯狂增长的问题
