### ISSUE TITLE
[Unity] Bug: $typeof 操作嵌套命名空间内的类型时返回 undefined

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#1633]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.4

### Unity的版本 | Unity Version

2022.3.13

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

**此问题在WebGL平台会出现，编辑器中运行正常**

$typeof 操作嵌套命名空间内的类型时返回 `undefined`

### 问题重现 | Bug reproduce

```ts
const type = puer.$typeof(CS.UnityEngine.Playables.PlayableDirector);
```

断点调试发现这里递归使用了一个 `cache` 来缓存，里面存在如下所示的内容，这块是否会存在字命名空间覆盖的问题？
```ts
{
  UnityEngine: Proxy(...),
  Playables: Proxy(...),
}
```

如：tiny.Utils 和 game.Utils 是否会出现问题呢？

**Comment by zombieyang** [comment]
这是个树形结构，namespace会组成一个proxy树的

**Comment by Geequlim** [comment]
确实是被裁剪了，感谢
