### ISSUE TITLE
[UE] 有关于新的定时器id复用机制容易导致错误清除的问题

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1634]
## detail | 详细描述
新的定时器id复用机制导致定时器id被密集复用，错误的清理一个失效的定时器id经常容易导致其他新申请的定时器被错误的清除。
原因是新的定时器id依赖于TSparseArray返回，往往是刚刚失效就被申请出来。所以如果清理一个已经被执行过的setTimeout的id,经常会导致新分配的定时器被错误的清理。有没有可能对id进行处理，用一个不重复的id和TimerInfos的index做一层映射，防止id复用出现错误清理。

在chrome中是用一个自增id来表示settimeout和setinterval的返回值，而不是复用id，可以相对有效防止错误和重复clear带来的问题
![image](https://github.com/Tencent/puerts/assets/5946974/07ad132d-317c-436b-a32c-23821947a940)

![image](https://github.com/Tencent/puerts/assets/5946974/23ef6898-cab6-479d-9561-9c8b0edfbc01)

**Comment by chexiongsheng** [comment]
这个issue：https://github.com/Tencent/puerts/issues/1631
修改后还有别的问题么？发下测试用例？

**Comment by lzj10** [comment]
> 这个issue：#1631 修改后还有别的问题么？发下测试用例？
由于id复用，类似这么写的代码，b的interInterval会被已经失效的a的timerout的handle错误的清理
![image](https://github.com/Tencent/puerts/assets/5946974/f37e230d-03e1-44f2-b259-58b8d07728b9)

**Comment by chexiongsheng** [comment]
> > 这个issue：#1631 修改后还有别的问题么？发下测试用例？
> > 由于id复用，类似这么写的代码，b的interInterval会被已经失效的a的timerout的handle错误的清理
> > ![image](https://private-user-images.githubusercontent.com/5946974/296702845-f37e230d-03e1-44f2-b259-58b8d07728b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDkyNTYsIm5iZiI6MTcwNTMwODk1NiwicGF0aCI6Ii81OTQ2OTc0LzI5NjcwMjg0NS1mMzdlMjMwZC0wM2UxLTQ0ZjItYjI1OS01OGI4ZDA3NzI4YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMDg1NTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk1OTVhZmZiNWM5ZmU5ZjdjMzc3ZGUzZDJlMWQ2MDM2MjM3NTE0YjcyMDI5OTc3YjkzMGNkNmFhNGMwZmYzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.05e1EKerwl_qPL5LROsZM1gJ8yOshTq9hJoreqJkH9Q)

这个修复了呀，你更新到最新代码试试

**Comment by lzj10** [comment]
我更到最新了2a79733，这个不是之前的那个问题是新的问题了，之前的问题是在timeout的callback中清理自身导致的问题，新的问题是由于timeout执行后，id被回收复用，然后重新分配出来后，再去清理这个过期持有的timeout的handle,然后把新创建的给清理掉了
由于a 和b得到的id都是1，b得到的是a执行了之后被回收重新分配出来的id，这时候如果再去清理a ,b也就没了

**Comment by lzj10** [comment]
所以日志是这样的，b对应的interval已经被清理掉了不会再执行了
Log Puerts (0x000004F28D9DE1D0) setTimeout a 1
Log Puerts (0x000004F28D9DE1D0) a 1
Log Puerts (0x000004F28D9DE1D0) setInterval b 1

**Comment by chexiongsheng** [comment]
更新下，现在timerid是不断递增了

**Comment by chexiongsheng** [comment]
规范中没说不能为0，最好写代码别做这样的假定。

**Comment by chexiongsheng** [comment]
你可以提个PR，把TimerID++改为++TimerID，不过如果溢出绕回来还是可能为0。
如果为这不是规范的规则增加逻辑则不太建议。

**Comment by lzj10** [comment]
了解，我觉得没问题

**Comment by lzj10** [comment]
看到了返回之非0的概念但是不确定是不是强制的
![image](https://github.com/Tencent/puerts/assets/5946974/2028cd94-97b3-40f1-84a4-c911b0163cfa)

https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers

![image](https://github.com/Tencent/puerts/assets/5946974/2fe8e743-59fb-40e9-822e-35ca3bc2a3ad)

**Comment by chexiongsheng** [comment]
ok，从大流吧

**Comment by chexiongsheng** [comment]
最新代码更新后还有问题吗？没有的话我准备出个patch版本

**Comment by lzj10** [comment]
目前看没有问题了
