### ISSUE TITLE
[UE] Bug: ue_bp.d.ts在引用插件里蓝图的地方报错，请问有什么比较好的解决办法

### ISSUE THREAD

**Issue by BlackdWing** [Tencent/puerts#1636]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [x] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.01

### UE的版本 | UE Version

5.03

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

ue_bp.d.ts在引用插件里蓝图的地方报错，没有生成插件蓝图内容，请问有办法能生成插件蓝图的内容吗
![image](https://github.com/Tencent/puerts/assets/72174866/cbb34986-5bf2-4674-9df6-ff8b37e4becb)

### 问题重现 | Bug reproduce

ue_bp.d.ts在引用插件里蓝图的地方报错

**Comment by chexiongsheng** [comment]
有什么简单的测试方法吗？

**Comment by BlackdWing** [comment]
不好意思没写简单复现，下面是复现过程

创建一个自定义插件带显示内容目录
![image](https://github.com/Tencent/puerts/assets/72174866/782f6091-6799-43a6-9550-f3cf52fe86fd)
在插件内容里创建个蓝图
![image](https://github.com/Tencent/puerts/assets/72174866/04491f01-f289-4cbb-ab5c-8f8df701f2db)
回到Game/Content里将新创建的蓝图作为父类创建个蓝图
![image](https://github.com/Tencent/puerts/assets/72174866/63f09fce-af5d-4a64-a7e8-e761ffdc018e)
点击生成*.d.ts按钮，vscode里ue_bp.d报错
![image](https://github.com/Tencent/puerts/assets/72174866/64ec1b57-58d1-4b4f-bc9c-6e1a479a823b)

**Comment by chexiongsheng** [comment]
你更新这个commit试试：https://github.com/Tencent/puerts/commit/dae96bc65ef8963d1b47f3098e24d9f5b9abe925

**Comment by BlackdWing** [comment]
> 你更新这个commit试试：[dae96bc](https://github.com/Tencent/puerts/commit/dae96bc65ef8963d1b47f3098e24d9f5b9abe925)

可以了。多谢
