### ISSUE TITLE
[UE] Bug: Mixin 基类，PIE第二次启动后会崩溃

### ISSUE THREAD

**Issue by operatorkai** [Tencent/puerts#1639]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.6.1

### UE的版本 | UE Version

5.3

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

BP_BaseDerive
--BP_Base
----Pawn

对BP_Base做了Mixin，重写了ReceiveBeginPlay ReceiveTick函数
运行时spawn BP_BaseDrive
PIE第二次崩溃
![image](https://github.com/Tencent/puerts/assets/3296962/06736ee3-ae13-4fa5-a3a9-6acb0f087682)

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000900000027

UnrealEditor_CoreUObject!UObjectBaseUtility::GetPathName() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBaseUtility.cpp:58]
UnrealEditor_CoreUObject!UObjectBaseUtility::GetPathName() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBaseUtility.cpp:50]
UnrealEditor_CoreUObject!GetObjectExternalPackageThreadSafe() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectHash.cpp:1620]
UnrealEditor_CoreUObject!UObjectBase::GetExternalPackage() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBase.cpp:258]
UnrealEditor_CoreUObject!UObjectBaseUtility::GetOutermost() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBaseUtility.cpp:299]
UnrealEditor_CoreUObject!UField::GetMetaData() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:446]
UnrealEditor_Engine!AActor::ProcessEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:1112]
UnrealEditor_Engine!AActor::BeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:4249]
UnrealEditor_Engine!APawn::BeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Pawn.cpp:179]
UnrealEditor_Engine!AActor::DispatchBeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:4189]
UnrealEditor_Engine!AActor::PostActorConstruction() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:3975]
UnrealEditor_Engine!AActor::FinishSpawning() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:3874]
UnrealEditor_Engine!UGameplayStatics::FinishSpawningActor() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\GameplayStatics.cpp:892]
UnrealEditor_Engine!UGameplayStatics::execFinishSpawningActor() [D:\build\++UE5\Sync\Engine\Intermediate\Build\Win64\UnrealEditor\Inc\Engine\UHT\GameplayStatics.gen.cpp:1568]
UnrealEditor_CoreUObject!UObject::execCallMathFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1075]
UnrealEditor_CoreUObject!UObject::execLetObj() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2884]
UnrealEditor_CoreUObject!ProcessLocalScriptFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1209]
UnrealEditor_CoreUObject!UObject::ProcessInternal() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1306]
UnrealEditor_CoreUObject!UFunction::Invoke() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6665]
UnrealEditor_CoreUObject!UObject::ProcessEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2145]
UnrealEditor_Engine!AActor::ProcessEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:1122]
UnrealEditor_Engine!FLatentActionManager::TickLatentActionForObject() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:314]
UnrealEditor_Engine!FLatentActionManager::ProcessLatentActions() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:232]
UnrealEditor_Engine!UWorld::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1560]
UnrealEditor_UnrealEd!UEditorEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1924]
UnrealEditor_UnrealEd!UUnrealEdEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:531]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5825]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

### 问题重现 | Bug reproduce

![image](https://github.com/Tencent/puerts/assets/3296962/15fc9edf-6ac5-4430-9252-3ff7c8c03a32)

[puerts_unreal_demo.zip](https://github.com/Tencent/puerts/files/13984008/puerts_unreal_demo.zip)
demo在QuickStart.ts中执行mixin
play后，3秒后BP_GameMode会spawn一个 BP_BaseDrive，此时运行良好
stop play
再次play，spawn BP_BaseDrive 后崩溃

**Comment by chexiongsheng** [comment]
可以fork一份puerts_unreal_demo，改了提交吗？
改了啥我可以清楚看见。我们内部出于安全考虑也不能随便打开个外部工程编译运行。

**Comment by operatorkai** [comment]
同事帮忙提了一个，辛苦看下问题吧

**Comment by chexiongsheng** [comment]
记录下分析的原因：
UClass::FindFunctionByName会把查找结果放到cache里头，清理mixin时，没清cache，导致查找到了过时的UFunction对象。原来代码只清理当前类cache，未清除其子类的cache

**Comment by YuquanZhao** [comment]
非常感谢, 问题已得到修复
