### ISSUE TITLE
[UE] suggestion 建议将用户js目录移动一下

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#1642]
## detail | 详细描述
最新版本修正了代理具柄疯狂增长的问题，谢谢。

疑问或者建议一：
V8InspectorImpl.cpp 文件 229行，这么多语句是不是可以用一行代替？
#if PLATFORM_WINDOWS
    int len = MultiByteToWideChar(CP_ACP, 0, Exception.what(), -1, NULL, 0);
    wchar_t* wstr = new wchar_t[len + 1];
    memset(wstr, 0, len + 1);
    MultiByteToWideChar(CP_ACP, 0, Exception.what(), -1, wstr, len);
    len = WideCharToMultiByte(CP_UTF8, 0, wstr, -1, NULL, 0, NULL, NULL);
    char* str = new char[len + 1];
    memset(str, 0, len + 1);
    WideCharToMultiByte(CP_UTF8, 0, wstr, -1, str, len, NULL, NULL);
    delete[] wstr;
    UE_LOG(LogV8Inspector, Warning, TEXT("%s, errno:%d, message:%s"), JobInfo, Exception.code().value(), UTF8_TO_TCHAR(str));
    delete[] str;
#else
    UE_LOG(LogV8Inspector, Warning, TEXT("%s, errno:%d, message:%s"), JobInfo, Exception.code().value(),
        ANSI_TO_TCHAR(Exception.what()));
#endif

代替语句：
    UE_LOG(LogV8Inspector, Warning, TEXT("%s, errno:%d, message:%S"), JobInfo, Exception.code().value(), Exception.what());

建议二，将目录 Content/JavaScript 下生成的用户js文件，移动到 Content/JavaScript/JavaScript 子目录，这样做的好处是，用户只需要添加 Content/JavaScript/JavaScript 目录和Content/JavaScript/puerts到打包设置里，其它编辑器用的文件就可以不打包到发行版本里了。感觉上有些东西全部打包进去（Content/JavaScript/PuertsEditor），有风险。如果选择打包了 Content/JavaScript/目录，它下面的子目录是无法排出的，至少4.27及之前版本是这样。我目前是移动到这个目录，只需要修改一下下面两个文件
enable_puerts_module.js
    "outDir": "Content/JavaScript/JavaScript"
PuertsSetting.h
    FString RootPath = "JavaScript/JavaScript";

**Comment by chexiongsheng** [comment]
MultiByteToWideChar那堆代码是为了解决中文乱码。你换成你那行有中文的话会乱码吗？

建议二的改就不可能改的了，改了会冲击其他项目。PuertsSetting.h本来就是一个配置，可以到UE界面设置的。enable_puerts_module.js只是我看很多人搞不定配置，做的自动化脚本。

**Comment by terst6** [comment]
没有测试中文是否会乱吗，同样那个代码如果中文有问题就转一下utf8，就肯定没有问题，也是一行代码。第二那个目录设置了不行，即便是连默认设置一起改了，在windows下的浏览器里，运行时热更新好像也常常不起作用了
