### ISSUE TITLE
[UE] Bug: mixin 覆盖的函数中调用super 异常

### ISSUE THREAD

**Issue by operatorkai** [Tencent/puerts#1643]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.6

### UE的版本 | UE Version

5.3

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

![image](https://github.com/Tencent/puerts/assets/3296962/7642b811-4b38-4a61-b86f-5127c1714fb8)
调用super异常了

### 问题重现 | Bug reproduce

两个蓝图类：
BP_Char
--BP_CharBase

BP_CharBase中定义了一个函数 FuncToOverride
ts中mixin了BP_Char 并重写FuncToOverride函数
![image](https://github.com/Tencent/puerts/assets/3296962/563c4739-7186-48c3-be49-400d7074fa6a)
![image](https://github.com/Tencent/puerts/assets/3296962/f3efc549-fe61-4335-8a4c-792113db71e3)
![image](https://github.com/Tencent/puerts/assets/3296962/321c7a90-002f-4659-b8bd-20bb1954961b)
![image](https://github.com/Tencent/puerts/assets/3296962/f3efc549-fe61-4335-8a4c-792113db71e3)

示例 https://github.com/operatorkai/puerts_unreal_demo_fork
启动游戏，按M键

**Comment by chexiongsheng** [comment]
这有个super的例子：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TypeScript/UsingMixin.ts#L52
你这个还是有点区别的

**Comment by operatorkai** [comment]
哦哦，需要手动组织prototype链。看花眼了... 没看到基类的load...
