### ISSUE TITLE
[UE] Bug: 使用Puerts Axios Http上传文件的问题

### ISSUE THREAD

**Issue by cesarzero** [Tencent/puerts#1646]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

last

### UE的版本 | UE Version

last

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

以下图片是  测试 Puerts 使用node第三方模块axios ,上传90MB的文件的用时
![test1](https://github.com/Tencent/puerts/assets/25058404/ec82d6a7-e7f0-4949-9d4f-00e6e8da9b29)
以下图片是  测试使用node第三方模块axios ,上传90MB的文件的用时
![test2](https://github.com/Tencent/puerts/assets/25058404/4a97a5c9-0dfc-436f-8c50-c837380978ac)

请问这种问题有什么优化的方法，

### 问题重现 | Bug reproduce

如上

**Comment by chexiongsheng** [comment]
在node要多久呢？
puerts下node由于要配合ue，要比正常node的io慢一些。

**Comment by cesarzero** [comment]
> 在node要多久呢？ puerts下node由于要配合ue，要比正常node的io慢一些。

第一张图用的puerts_nodejs版本，第二张图用的纯node  。 90M文件 ，puerts_nodejs 版用时15秒，普通nodejs 用时2秒  。我试了超过GB以上的文件， 文件越大，他们之间所用时间差异会非常f大。   本来想利用js来避开UE C++一些网络相关的繁琐步骤= .=   我看网上文章也说明了如何优化puerts 的IO http://www.manongjc.com/detail/60-fkdtlbncqoqqeot.html     看来只能先把网络和IO的部分移到C++里面去，看看大佬这块内容后续还有没有优化的空间

**Comment by chexiongsheng** [comment]
差不多，我之前测试是6倍的差距。
主要是脚本要在主线程中执行，需要通过GraphTask跑，延迟比较大。
