### ISSUE TITLE
[UE] Bug: Mixin实例持有的js实例丢失了

### ISSUE THREAD

**Issue by operatorkai** [Tencent/puerts#1658]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.6

### UE的版本 | UE Version

UE 5.3.2

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

蓝图BP_Char 派生自 BP_CharBase

**代码：**
BP_CharBase_ts是BP_CharBase的mixin实现，持有一个js对象
![image](https://github.com/Tencent/puerts/assets/3296962/c4f613e2-28f8-4f4f-8390-f98ac15c432f)
![image](https://github.com/Tencent/puerts/assets/3296962/7d2da3d2-b888-4403-99f8-2357b16eabd0)

### 问题重现 | Bug reproduce
https://github.com/operatorkai/puerts_unreal_demo_fork

修改Editor参数，独立进程，启动1个DS +  2Client 
![image](https://github.com/Tencent/puerts/assets/3296962/5a5230a2-d249-459e-89f7-36d4b422cba7)
![image](https://github.com/Tencent/puerts/assets/3296962/273fe526-82d7-497f-9e6b-1007f39e610a)

启动Play

一秒或者几秒后 出现js异常
![image](https://github.com/Tencent/puerts/assets/3296962/c0bd7892-1cb6-4c68-8b10-0f8fcf8014f0)

PS: 只有1个角色 貌似没问题 运行1分钟也未报错，有第二个人就会出错

**Comment by chexiongsheng** [comment]
不好意思，回去过年了。
我稍后看。

**Comment by operatorkai** [comment]
新年好~ 多谢多谢

**Comment by chexiongsheng** [comment]
我试了下，只有“单进程下运行”去掉勾才会报错，其它设置相同不会报错。

**Comment by operatorkai** [comment]
本来是 分别启动发布的ds，client 进程，出现这个问题，上面写的复现方式 是方便您看这个问题

**Comment by operatorkai** [comment]
本来是这样：分别启动独立编译出的 DS.exe 和 client.exe ，ds和client都会出现丢失实例
勾掉 单进程下运行 是模拟正常的多进程独立环境，上面的复现步骤是想着方便您做复现操作

**Comment by chexiongsheng** [comment]
我觉得是mixin执行时机的问题，objectTakeByNative对已经创建并传入js的对象无效。

**Comment by chexiongsheng** [comment]
我加了打印，确实是这个原因，先执行了进入js的Bind，然后再执行mixin，那个0就是objectTakeByNative的标记

[2024.02.20-03.35.10:626][  0]LogTemp: Error: Bind BP_CharBase:0
[2024.02.20-03.35.10:637][  0]Puerts: Warning: (0x00000B4A37404610) mixin blueprint.mixin(BP_CharBase, BP_CharBase_ts);
[2024.02.20-03.35.10:640][  0]LogTemp: Error: mixin BP_CharBase_C:1

**Comment by chexiongsheng** [comment]
定位原因是你mixin的是基类，指明objectTakeByNative的是基类。
但创建的对象是子类。按目前的设定不会生效基类的设置。

**Comment by operatorkai** [comment]
嗯 按照常规，基类会包含一些基础实现
那么 您建议是 这种情况可以添加支持 还是 换一种使用方式呢 【比如基类持有的通用logic实例就是在蓝图或cpp中 或 其他方式】

**Comment by operatorkai** [comment]
感觉是用法问题哈哈，基类的字段和函数，子类ts也不容易复用
不过针对这个用法，想了个办法：ts中的对象，主动记录到蓝图中持有一下 就可以

**Comment by chexiongsheng** [comment]
我考虑下是否添加支持

**Comment by chexiongsheng** [comment]
我加了，你更新试试

**Comment by operatorkai** [comment]
试了下，可以了~
