### ISSUE TITLE
[Unity] Bug: IOS 初始化的时候奔溃

### ISSUE THREAD

**Issue by xtutu** [Tencent/puerts#1669]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.4

### Unity的版本 | Unity Version

2022.3.20

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

xcode 版本 15.2
![53cea893a41c43a1642f5e29c0bb870e](https://github.com/Tencent/puerts/assets/12950709/88510f24-3286-481c-a1fe-65519bf40d28)

![cd7eb7ae3ba0cb904581e3eabee6fd67](https://github.com/Tencent/puerts/assets/12950709/440ae6a0-cd9f-4049-9251-76c8eb0b0720)

![65a7f469f46c34eee84b80b12a108233](https://github.com/Tencent/puerts/assets/12950709/70bb2300-7f8d-4d80-b028-edacd3d4898b)
奔溃在这个位置。

奔溃信息：
![e983d8fd727061a1721e9a4be1ea439c](https://github.com/Tencent/puerts/assets/12950709/9b93d958-8651-4b67-b2f3-822ac4ee77ee)

暂时就这些信息。

### 问题重现 | Bug reproduce

无

**Comment by chexiongsheng** [comment]
在你的xcode重编译plugin试试呢？如果不行把v8也重编译下试试

**Comment by xtutu** [comment]
项目里还装了： com.tencent.puerts.webgl  2.0.4
排查下来，发现：只要把这个删掉，IOS 就不会奔溃。

**Comment by chexiongsheng** [comment]
哦，应该是com.tencent.puerts.webgl 2.0.4导致的，它下面有个cpp文件，里面有些符号和puerts plugin是一样的
https://github.com/zombieyang/puerts_unity_webgl_demo/blob/master/packages/webgl/upm/Runtime/Plugins/WebGL/puerts.cpp

**Comment by chexiongsheng** [comment]
你试试在
https://github.com/zombieyang/puerts_unity_webgl_demo/blob/master/packages/webgl/upm/Runtime/Plugins/WebGL/puerts.cpp

加宏让这些代码只在webgl生效
~~~c++
#ifdef __EMSCRIPTEN__
//原来的代码
#endif
~~~

**Comment by xtutu** [comment]
按照上面的方式，修好了
