### ISSUE TITLE
[Unity] Bug:Crash  C#中执行ExecuteModule时如果被加载模块有语法错误Unity会崩溃

### ISSUE THREAD

**Issue by daijunli** [Tencent/puerts#1670]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.4

### Unity的版本 | Unity Version

2021.3.6f1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

using System;
using System.Collections;
using System.Collections.Generic;
using Puerts;
using UnityEngine;
using System.IO;
using System.Runtime.InteropServices;

public class JSLoader : DefaultLoader // ILoader,IModuleChecker
{
    public bool FileExists(string filepath)
    {
        if (base.FileExists(filepath))
            return true;
        return File.Exists(filepath);
    }

    public string ReadFile(string filepath, out string debugpath)
    {
        if (base.FileExists(filepath))
            return base.ReadFile(filepath, out debugpath);
        
        var fileContent = File.ReadAllText(filepath);
        debugpath = filepath;
        return fileContent;
    }

}

//在场景中创建多个GameObject 挂载该文件，
public class TestCrash : MonoBehaviour
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    delegate int CBCreateObject();

    public JsEnv env;

    public static TestCrash instance;
    void Awake()
    {
        if (instance == null)
        {
            instance = this;
            env = new JsEnv(new JSLoader(), 9229);
        }
        IntPtr pCallback = Marshal.GetFunctionPointerForDelegate<CBCreateObject>(CBCreateTest);
        TestCBCrash(pCallback);
    }
    
    static int CBCreateTest()
    {
        Debug.Log("=======CBCreateTest=====");
        instance.env.Eval($@"
console.log('============test js env==');
");

        // AModule.mjs 的import路径上有语法错误，会崩溃
        instance.env.ExecuteModule("Assets/Resources/AModule.mjs");
        return 0;

    }
    [DllImport("forTest", CallingConvention = CallingConvention.Cdecl)]
    public static extern void TestCBCrash(IntPtr callback);
}

C++ forTest.dll 的测试代码

![@FV{J2L 82EX3J### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.4

### Unity的版本 | Unity Version

2021.3.6f1

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

using System;
using System.Collections;
using System.Collections.Generic;
using Puerts;
using UnityEngine;
using System.IO;
using System.Runtime.InteropServices;

public class JSLoader : DefaultLoader // ILoader,IModuleChecker
{
    public bool FileExists(string filepath)
    {
        if (base.FileExists(filepath))
            return true;
        return File.Exists(filepath);
    }

    public string ReadFile(string filepath, out string debugpath)
    {
        if (base.FileExists(filepath))
            return base.ReadFile(filepath, out debugpath);
        
        var fileContent = File.ReadAllText(filepath);
        debugpath = filepath;
        return fileContent;
    }

}

//在场景中创建多个GameObject 挂载该文件，
public class TestCrash : MonoBehaviour
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    delegate int CBCreateObject();

    public JsEnv env;

    public static TestCrash instance;
    void Awake()
    {
        if (instance == null)
        {
            instance = this;
            env = new JsEnv(new JSLoader(), 9229);
        }
        IntPtr pCallback = Marshal.GetFunctionPointerForDelegate<CBCreateObject>(CBCreateTest);
        TestCBCrash(pCallback);
    }
    
    static int CBCreateTest()
    {
        Debug.Log("=======CBCreateTest=====");
        instance.env.Eval($@"
console.log('============test js env==');
");

        // AModule.mjs 的import路径上有语法错误，会崩溃
        instance.env.ExecuteModule("Assets/Resources/AModule.mjs");
        return 0;

    }
    [DllImport("forTest", CallingConvention = CallingConvention.Cdecl)]
    public static extern void TestCBCrash(IntPtr callback);
}

C++ forTest.dll 的测试代码

![图片](https://github.com/Tencent/puerts/assets/4178598/73863c70-1a25-456e-a0c5-616f2ce9aff4)

### 问题重现 | Bug reproduce

[TestPuertsCrash.zip](https://github.com/Tencent/puerts/files/14503654/TestPuertsCrash.zip)
![9A%ONSBIEEVP_}3V1Z5B~VW](https://github.com/Tencent/puerts/assets/4178598/3e4479a9-f746-4cb0-9ed1-f5d7d02e47e4)

**Comment by chexiongsheng** [comment]
你在QQ群上不是说要自行定位下吗？又没结果？
