### ISSUE TITLE
[Unreal]TS文件不变，但生成的蓝图每次会有一些细微差别

### ISSUE THREAD

**Issue by huzhangyang** [Tencent/puerts#168]
如图，大部分内容是相同的，但有几个字节的内容每次启动UE（测试版本4.26）都会被修改。

这会导致版本控制每次会识别蓝图文件被更改。

![QQ图片20210309103541](https://user-images.githubusercontent.com/5735704/110410563-0756b380-80c4-11eb-9a7d-8c4e8b87af8b.png)

**Comment by huangwc94** [comment]
不知道是不是这个原因，如果我用蓝图继承JS，每次更改JS重新生成，那么蓝图覆写的函数会被顶掉
![image](https://user-images.githubusercontent.com/8810189/110876908-4ab04e00-828d-11eb-850e-7febc8362fc6.png)
![image](https://user-images.githubusercontent.com/8810189/110876932-56037980-828d-11eb-8aa9-b5d977f78bc3.png)

**Comment by huzhangyang** [comment]
> 不知道是不是这个原因，如果我用蓝图继承JS，每次更改JS重新生成，那么蓝图覆写的函数会被顶掉
> ![image](https://user-images.githubusercontent.com/8810189/110877040-94009d80-828d-11eb-96fc-51021d46760f.png)
> ![image](https://user-images.githubusercontent.com/8810189/110877066-9ebb3280-828d-11eb-928f-daf38131a1c8.png)
> 更改一下JS
> ![image](https://user-images.githubusercontent.com/8810189/110877104-b397c600-828d-11eb-95ba-f01787746206.png)
> ![image](https://user-images.githubusercontent.com/8810189/110877140-c5796900-828d-11eb-9f39-df87455ab9cc.png)

应该不是，我是ts文件（和js文件）每次不变的情况下，蓝图依然会有改变
