### ISSUE TITLE
[Dotnet] 能否支持dotnet的NativeAOT？

### ISSUE THREAD

**Issue by scgm0** [Tencent/puerts#1683]

**Comment by chexiongsheng** [comment]
只要是C#环境就支持呀。
unity的il2cpp也是AOT的一种

**Comment by scgm0** [comment]
> 只要是C#环境就支持呀。 unity的il2cpp也是AOT的一种

我的意思是像il2cpp一样对dotnet的NativeAOT有专门的处理，因为直接用会有问题（工作量好大的样子。。。）

**Comment by chexiongsheng** [comment]
有什么问题呢？具体说下？
生成wrapper后，我觉得在任何AOT上跑都没问题。

**Comment by scgm0** [comment]
> 有什么问题呢？具体说下？ 生成wrapper后，我觉得在任何AOT上跑都没问题。

原来如此，谢谢大佬！
