### ISSUE TITLE
[UE] nodejs后端只支持node16吗，一些library(如openai-node)不支持node16

### ISSUE THREAD

**Issue by Yimi81** [Tencent/puerts#1693]
我想使用openai-node这个库，像这样
![image](https://github.com/Tencent/puerts/assets/66633207/7baecaca-81bc-4930-8837-649c33ecc41d)

但是会报错
![image](https://github.com/Tencent/puerts/assets/66633207/fc6abb15-27be-44c2-93fe-8143e90ccecf)

查询后显示openai-node似乎[不支持node16](https://github.com/openai/openai-node/issues/304#issuecomment-1720039206)了
请问我可以使用更新的nodejs版本吗，我该如何升级？JSEnv.Build.cs中有相应的设置吗？

**Comment by chexiongsheng** [comment]
你搞定你需要版本的编译就可以了。
node16编译脚本在这里：https://github.com/puerts/backend-nodejs
