### ISSUE TITLE
Unity C#转ts，多载方法变成没有多载

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#17]
我在Unity C#写了一个函数void Foo(string s = "bar")，按下Generate Code，转成ts，该函数变成Foo(s:string):void。但这样就没有多载，只能手动填入C#函数的预设参数。

**Comment by chexiongsheng** [comment]
语法上ts声明（d.ts文件）不支持缺省值。
自己实现的class倒是可以

**Comment by chexiongsheng** [comment]
通过可选值可以支持，但是现在不支持。
