### ISSUE TITLE
[Unity] Bug: Crash when trying to access transform or gameObject properties through a JS proxy

### ISSUE THREAD

**Issue by raad-genies** [Tencent/puerts#1709]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

Latest

### Unity的版本 | Unity Version

2021.3

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

Crashing 

### 问题重现 | Bug reproduce

Its custom code, I am executing a module that binds a JS object to a monobehavior using a proxy, when accessing the transform or gameObject properties it crashes. I also tested passing them directly from my monobehavior to the executed module and they crash immediately.

**Comment by chexiongsheng** [comment]
Could you please provide a minimal, reproducible example or project that demonstrates the issue you've reported? This will help us to better understand and address the problem. In addition, it would be best if you could provide the reproducible code based on the UT (Unit Test) project. This will greatly assist us in identifying and resolving the issue. Thank you!

**Comment by raad-genies** [comment]
@chexiongsheng will do! Just doing some debugging on my side to ensure it's not an issue with my code.

**Comment by chexiongsheng** [comment]
I run this ut case:
```c#
        [Test]
        public void CallByProxyTest()
        {
            var jsEnv = UnitTestEnv.GetEnv();
            var ret = jsEnv.Eval<string>(@"
                (function() {
                    const helper = new CS.Puerts.UnitTest.CrossLangTestHelper();
                    const proxy = new Proxy(helper, {
                       get: function(target, name) {
                           return target[name];
                       }
                    });
                    const val = proxy.GetDateTime();
                    return '' + (val instanceof CS.System.DateTime) + (val instanceof Date)
                })()
            ");
            Assert.AreEqual("truefalse", ret);
            jsEnv.Tick();
        }
```
Got a Exception, Not carsh
```
   System.Exception : chunk:9: Error: c# exception:Object reference not set to an instance of an object.,stack:   at PuertsStaticWrap.Puerts_UnitTest_CrossLangTestHelper_Wrap.M_GetDateTime(IntPtr isolate, IntPtr info, IntPtr self, Int32 paramLen, Int64 data) in C:\puerts\unity\test\dotnet\Src\StaticWrapper\Puerts_UnitTest_CrossLangTestHelper_Wrap.cs:line 46

Error: c# exception:Object reference not set to an instance of an object.,stack:   at PuertsStaticWrap.Puerts_UnitTest_CrossLangTestHelper_Wrap.M_GetDateTime(IntPtr isolate, IntPtr info, IntPtr self, Int32 paramLen, Int64 data) in C:\puerts\unity\test\dotnet\Src\StaticWrapper\Puerts_UnitTest_CrossLangTestHelper_Wrap.cs:line 46
    at chunk:9:39
    at chunk:11:19
  堆栈跟踪:
     at Puerts.JsEnv.Eval[TResult](String chunk, String chunkName) in C:\puerts\unity\Assets\core\upm\Runtime\Src\Default\JsEnv.cs:line 353
   at Puerts.UnitTest.CrossLangTest.CallByProxyTest() in C:\puerts\unity\test\Src\Cases\CrossLang\CrossLangTest.cs:line 868
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by raad-genies** [comment]
Was an issue from my side!
