### ISSUE TITLE
[UE] Bug: RegisterTArray报错及使用问题，及模板绑定相关问题

### ISSUE THREAD

**Issue by kfj24** [Tencent/puerts#1738]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

5.4.1

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

1. 问题1
RegisterTArray在编码期报错，定位到错误代码如下，见下图
`.Method("RemoveAt", SelectFunction(void (TArray<FString>::*)(int), &TArray<FString>::RemoveAt))`

![image](https://github.com/Tencent/puerts/assets/67983334/997147b0-3b61-4513-9ae9-b764844606d8)
![image](https://github.com/Tencent/puerts/assets/67983334/726185a3-3f97-4d25-82c0-352b6d5e01d8)

2. 问题2
我关注到文档中确实描述了TArray的注册，但在官方demo和代码仓库中没有发现相关使用的方法。如果注册TArray需要每次传入一个类型，这个写法看起来有点臃肿，因为任何东西都可以作为TArray的类型，对此是否有一些好的建议或例子可以参考？

3. 问题3
基于模板绑定的单位（作用域）是什么？我尝试在插件中的两个不同模块声明两个cpp文件分别绑定同一个方法，没有发生编译错误，这是否合理？

基于问题3和RegisterTArray宏，对于基于模板绑定的写法有什么建议吗，例如对于组成结构的建议（对于TArray的注册写在哪一级，业务扩展绑定写在哪一级等）？

万分感谢大佬回答~

**Comment by morirain** [comment]
5.4里面RemoveAt的参数改了

**Comment by kfj24** [comment]
> 5.4里面RemoveAt的参数改了

感谢，同步一下修改结果：
`#define RegisterTArray(CLS)                                                                                                                                      \
    PUERTS_NAMESPACE::DefineClass<TArray<CLS>>()                                                                                             \
        .Method("Get", SelectFunction(CLS& (TArray<CLS>::*) (int), &TArray<CLS>::operator[]))                                 \
        .Method("GetRef", SelectFunction(CLS& (TArray<CLS>::*) (int), &TArray<CLS>::operator[]))                            \
        .Method("Num", MakeFunction(&TArray<CLS>::Num))                                                                                     \
        .Method("Contains", MakeFunction(&TArray<CLS>::Contains<CLS>))                                                              \
        .Method("RemoveAt", SelectFunction(void (TArray<CLS>::*)(int, /* 5.4新增 */EAllowShrinking), &TArray<CLS>::RemoveAt))  \
        .Method("IsValidIndex", MakeFunction(&TArray<CLS>::IsValidIndex))                                                               \
        .Method("Empty", MakeFunction(&TArray<CLS>::Empty))                                                                                 \
        .Register()`

问题2和问题3也希望能回答下

**Comment by chexiongsheng** [comment]
> > 5.4里面RemoveAt的参数改了
> 
> 感谢，同步一下修改结果，在RegisterTArray宏中修改如下： `.Method("RemoveAt", SelectFunction(void (TArray<CLS>::*)(int, /* 5.4 new */EAllowShrinking), &TArray<CLS>::RemoveAt))` 问题2和问题3也希望能回答下

你就5.4的修改提个PR吧。

2、只能一个个来，模板实例化后就一个新的类型，c++也没反射，不能运行时自动查找实例；
3、这是c++模板的特性，编辑器会自动处理这种情况。

**Comment by kfj24** [comment]
> > > 5.4里面RemoveAt的参数改了
> > 
> > 
> > 感谢，同步一下修改结果，在RegisterTArray宏中修改如下： `.Method("RemoveAt", SelectFunction(void (TArray<CLS>::*)(int, /* 5.4 new */EAllowShrinking), &TArray<CLS>::RemoveAt))` 问题2和问题3也希望能回答下
> 
> 你就5.4的修改提个PR吧。
> 
> 2、只能一个个来，模板实例化后就一个新的类型，c++也没反射，不能运行时自动查找实例； 3、这是c++模板的特性，编辑器会自动处理这种情况。

问题2明白了，非常感谢，问题3还有些疑惑
我测试在模块A中的模板绑定文件中，绑定了一个返回TArray的方法，仅UsingContainer进行了声明，在模块B的绑定文件中UsingContainer+RegisterTArray，这样能过编译，但在TS环境中这个方法返回出来的TArray还是不识别（.Num()之类的方法全都报运行时not function），所以我理解这个RegisterTArray需要紧跟绑定才能生效，这样对吗？还是说依赖编译顺序之类的？

**Comment by chexiongsheng** [comment]
UsingContainer能让它以指针形式返回js，RegisterTArray是注册方法

**Comment by chexiongsheng** [comment]
PR提下吧，虽然我改也不费事，不过我一般希望谁解决谁提交。

**Comment by kfj24** [comment]
> PR提下吧，虽然我改也不费事，不过我一般希望谁解决谁提交。

#1742
