### ISSUE TITLE
[Unity] 仿照unreal使用v8::StackTrace::CurrentStackTrace获取js堆栈，但返回GetFrameCount总是0

### ISSUE THREAD

**Issue by zxt5105515** [Tencent/puerts#1739]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.4

### Unity的版本 | Unity Version

2021.3.21f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

按照unreal的写法
![img_v3_02ba_be3980e4-8d67-451c-b4b3-699ecd9e910g](https://github.com/Tencent/puerts/assets/6982924/0e755c01-5275-4499-b14e-d67c9f750efe)

在unity/native_src/Src/Puerts.cpp中添加了方法
```cpp
// modify from unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp:
V8_EXPORT const char *GetCurrentStackTrace(v8::Isolate* Isolate, int frameLimit, int *Length)
{
#ifndef WITH_QUICKJS
#ifdef THREAD_SAFE
    v8::Locker Locker(Isolate);
#endif
    v8::Isolate::Scope IsolateScope(Isolate);
    v8::HandleScope HandleScope(Isolate);
    auto JsEngine = FV8Utils::IsolateData<JSEngine>(Isolate);

    auto trace = v8::StackTrace::CurrentStackTrace(Isolate, frameLimit, v8::StackTrace::kDetailed);
    // frameCount 是 0
    int frameCount = trace->GetFrameCount();
    std::string StackTrace = StackTraceToString(Isolate, trace);
    *Length = (int)StackTrace.length();
    if (JsEngine->StrBuffer.size() < *Length) JsEngine->StrBuffer.reserve(*Length);
    memcpy(JsEngine->StrBuffer.data(), StackTrace.data(), *Length);
    return JsEngine->StrBuffer.data();
#else
    *Length = 0;
    return nullptr;
#endif
}
```
在PuertsDLL.cs中加上对应导出方法
然后在mac m1上编译运行后，
v8::StackTrace::CurrentStackTrace返回的GetFrameCount总是0，这是什么原因？是unity这边和unreal有区别吗？

**Comment by chexiongsheng** [comment]
这最近版本本来就支持了

**Comment by chexiongsheng** [comment]
另外为0大概率是你的js代码没在跑。js运行中才会有栈。
