### ISSUE TITLE
[Unity] Bug: Fields with internal type exposed via explicit interface is always undefined

### ISSUE THREAD

**Issue by CreepGin** [Tencent/puerts#1741]
### Pre-reading

- [X] [Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer Version

2.0.5

### Unity Version

2023.2

### Platform

All

### Bug reproduce

This pattern is used by Unity's UI Toolkit. `VisualElement.style` and `VisualElement.resolvedStyle` are both backed by internal types `InlineStyleAccess` and `ResolvedStyleAccess`. When accessing any related fields (i.e. `VisualElement.style.width` or `VisualElement.width`) from JS, it'll always return undefined.

Here's a minimal test case.

```cs
// C#
namespace MyNamespace {
    public class FooVE {
        public IFoo foo;

        public FooVE() {
            foo = new FooAccess();
        }
    }

    public interface IFoo {
        float width { get; }
    }

    internal class FooAccess : IFoo {
        public float width => 1.23f;
    }
}
```

```ts
// JS
var fooVE = new CS.MyNamespace.FooVE()
console.log(fooVE) // MyNamespace.FooVE
console.log(fooVE.width) // undefined
```

**Comment by chexiongsheng** [comment]
your test code is wrong. 
The correct version is:
```
var fooVE = new CS.MyNamespace.FooVE()
console.log(fooVE) // MyNamespace.FooVE
console.log(fooVE.foo.width)
```
You are using TypeScript? TypeScript compiler will point out your mistake.

**Comment by CreepGin** [comment]
Ah yes, I'm sorry. I did the minimal test case too fast (and didn't use TS). Let's use `VisualElement.style` directly then. 

```cs
[RequireComponent(typeof(UIDocument))]
public class TestComp : MonoBehaviour {
    public static TestComp instance;
    
    public VisualElement ve;
    
    UIDocument _doc;

    void Awake() {
        instance = this;
        _doc = GetComponent<UIDocument>();
    }

    void Start() {
        ve = new VisualElement();
        ve.style.width = 100f;
        ve.style.height = 80f;
        ve.style.backgroundColor = Color.red;
        _doc.rootVisualElement.Add(ve);
    }

    public StyleLength GetWidth() {
        return ve.style.width;
    }
}
```

```ts
// @ts-ignore
var testComp = CS.TestComp.instance
setTimeout(() => { // in case the style is not set yet in current frame
    console.log(testComp.ve.style) // UnityEngine.UIElements.InlineStyleAcces
    console.log(testComp.ve.style.width) // undefined
    console.log(testComp.GetWidth())  // 100px
}, 1000)
```

**Comment by CreepGin** [comment]
Ty for the quick fix!🎉
