### ISSUE TITLE
[Unity] Bug: 运行puerts的nodejs http示例，localhost访问不到

### ISSUE THREAD

**Issue by 1162064779** [Tencent/puerts#1745]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.5

### Unity的版本 | Unity Version

2022.3.23

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

运行puerts的nodejs http示例，例如mjs：
const server = require('node:http').createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end('<h1>Hello, World!</h1><p>This is a simple Node.js HTTP server using ES modules.</p>');
});
const PORT = 9223;
server.listen(PORT, () => {
    console.log(`Server is running at http://localhost:${PORT}`);
});
或者是直接通过env.Eval调用：
const http = require('node:http');
http.createServer((req, res)=> { res.writeHead(200);res.end('helloworld') }).listen(9223);
**在editor下运行，不会报错，netstat显示服务端口正在运行，但http get没有反应**
另外，当尝试使用import http时，报错module not found，为什么require就能找到呢？用的应该是同一个node.dll吧

### 问题重现 | Bug reproduce

稳定复现，get不了服务的问题

**Comment by chexiongsheng** [comment]
`const PORT = 8081

var http = require('http');

http.createServer(function (request, response) {
    response.writeHead(200, {'Content-Type': 'text/plain'});

    response.end('Hello World\n');
}).listen(PORT);

console.log(`Server running at http://127.0.0.1:${PORT}/`);`

**Comment by 1162064779** [comment]
> ```
> const PORT = 8081
> 
> var http = require('http');
> 
> http.createServer(function (request, response) {
>     response.writeHead(200, {'Content-Type': 'text/plain'});
> 
>     response.end('Hello World\n');
> }).listen(PORT);
> 
> console.log(`Server running at http://127.0.0.1:${PORT}/`);
> ```

您好，感谢回复，我想知道这段代码和我原本的有什么本质区别嘛？我现在运行下来还是一样的问题，创建的server还是无法访问：
![image](https://github.com/Tencent/puerts/assets/43094910/04056621-3b28-4ff1-ab42-da69e5a13ec5)

**Comment by chexiongsheng** [comment]
如果是unity，你应该要在update那调用JsEnv.Tick

**Comment by 1162064779** [comment]
> 如果是unity，你应该要在update那调用JsEnv.Tick

十分感谢！这对我很有用！我会去仔细研究这个函数的含义，感谢您的解答！

**Comment by 1162064779** [comment]
@chexiongsheng 我很遗憾的是，虽然nodejs在editor中好使了，但在我打包出的unity apk运行在手机上时，他依旧无法成功创建服务，我很确定我下载的puerts是最新的且backend为nodejs：
![image](https://github.com/Tencent/puerts/assets/43094910/4dbb7967-6d19-4302-9807-99e49e268176)
因为editor下好使但移动端不好使，所以我只能猜测是我的node相关lib有问题，我发现下载下来的lib中很多这样的meta文件
![image](https://github.com/Tencent/puerts/assets/43094910/d87c0f87-1265-4b8d-9fbb-e5a6654701cc)
这和我在backend-nodejs项目中看到的类似，我猜测可能是这些.a都被一同打包进了libpuerts.so，所以不再需要了？我简单的使用您[backend-nodejs](https://github.com/puerts/backend-nodejs)项目中的armv8产物替换这里的lib发现编译不过，我很想知道这里面是哪一块出了问题？

**Comment by chexiongsheng** [comment]
editor可以，手机上应该就没问题。你看是不是场景没启动，脚本没启动，防火墙之类的问题。
