### ISSUE TITLE
[Unity] 如何安装？

### ISSUE THREAD

**Issue by Yiiip** [Tencent/puerts#1749]
## 如何安装？

> 前往 [Github Releases](https://github.com/Tencent/puerts/releases) 下载PuerTS_V8_x.x.x.tgz 或是别的你需要的Puerts版本。
> 将压缩包内的Puerts文件夹解压至你的Assets目录

下载好的PuerTS_V8_2.0.5.tgz，里面并没有Puerts文件夹

**Comment by chexiongsheng** [comment]
看release的标题，你下载的unreal engine版本

**Comment by Yiiip** [comment]
？？我下载的是Unity_v2.0.5,ApiLevel:32
[PuerTS_V8_2.0.5.tgz](https://github.com/Tencent/puerts/releases/download/Unity_v2.0.5/PuerTS_V8_2.0.5.tgz)

**Comment by chexiongsheng** [comment]
> ？？我下载的是Unity_v2.0.5,ApiLevel:32 [PuerTS_V8_2.0.5.tgz](https://github.com/Tencent/puerts/releases/download/Unity_v2.0.5/PuerTS_V8_2.0.5.tgz)

哦，这个是对的。
但这里只有plugins，要结合源码使用。
推荐用upm安装

**Comment by chexiongsheng** [comment]
https://puerts.github.io/docs/puerts/unity/install
