### ISSUE TITLE
[Unity] 请问在mjs中如何import cjs？

### ISSUE THREAD

**Issue by Yiiip** [Tencent/puerts#1753]
## detail | 详细描述
Unity 2021.3.29
puerts 2.0.5

```js
// A.mjs
import b from './B.cjs';
export function test() {
    console.log(b.pi);
}
```
```js
// B.cjs
const pi = 3.14;
module.exports = { pi };
```
```csharp
// C# MonoBehaviour
Action test = jsEnv.ExecuteModule<Action>("A.mjs", "test");
test?.Invoke();

/*
报错：
Exception: A.mjs:: SyntaxError: The requested module './B.cjs' does not provide an export named 'default'
*/
```
报错如上，是不支持这样做吗？

比如有些库 protobufjs 有相关的 import 需求`import * as $protobuf from "./protobufjs/minimal.cjs";`，它是 module.exports 的方式，所以也会import报错。

如果 A.mjs 中改用 require 的方式`const b = require('./B.cjs');`，会报错`Exception: node:internal/modules/cjs/loader:933: Error: Cannot find module './B.cjs'`。

**Comment by chexiongsheng** [comment]
问题的前半部分，是js的基本语法问题，为什么跑来这里问？
至于require加载不了，需要你：1、启用commonjs模块；2、实现合适的loader

**Comment by Yiiip** [comment]
问题的前半部分，只是因为nodejs里能跑。
3Q

**Comment by chexiongsheng** [comment]
> 问题的前半部分，只是因为nodejs里能跑。
> 
> > 1、启用commonjs模块；2、实现合适的loader
> 
> 3Q，我去参考下[EvalTest](https://github.com/Tencent/puerts/blob/master/unity/test/Src/Cases/API/EvalTest.cs)里`ESModuleExecuteCJS() : 379`
> 
> #1002



> 问题的前半部分，只是因为nodejs里能跑。
> 
> > 1、启用commonjs模块；2、实现合适的loader
> 
> 3Q，我去参考下[EvalTest](https://github.com/Tencent/puerts/blob/master/unity/test/Src/Cases/API/EvalTest.cs)里`ESModuleExecuteCJS() : 379`
> 
> #1002

nodejs做了esm中import一个cjs模块的支持。
