### ISSUE TITLE
[Unity]/[UE] suggestion Unity打包到小游戏过程中，怎么处理能改动到library.js脚本

### ISSUE THREAD

**Issue by Zjax** [Tencent/puerts#1757]
## detail | 详细描述
Unity打包到小游戏过程中，怎么处理能改动到library.js脚本
我看unity环境下又library,ts的脚本，目前改了并没有改动到，所以过来询问一波

**Comment by chexiongsheng** [comment]
小游戏的问题在这里提：https://github.com/zombieyang/puerts_unity_webgl_demo
