### ISSUE TITLE
[UE] Bug: MIxin的类被原生蓝图继承类调用的问题

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#1762]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

6f50d33

### UE的版本 | UE Version

5.4

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

通过原生蓝图调用父类被mixin的函数，mixin的ReceiveBeginPlay无法调用到，但是普通函数可以正常调用

### 问题重现 | Bug reproduce

1. 有蓝图类TestActor ，mixin到ts类TestActor

![image](https://github.com/Tencent/puerts/assets/5946974/2c204f03-09d3-4c89-a409-0f9830c0fb39)
![image](https://github.com/Tencent/puerts/assets/5946974/764537e9-d1dc-4a0e-ad20-a5b8ba2ce17a)
![image](https://github.com/Tencent/puerts/assets/5946974/815e5b1f-664a-4532-b423-a58453c35e2e)

2.有蓝图类TestActor_Child继承自TestActor ，并且在蓝图中重写了ReceiveBeginPlay和TestFunction并调用父类方法TestFunction2

![image](https://github.com/Tencent/puerts/assets/5946974/d2d371ed-1b33-474a-af58-0a0f20438dba)
![image](https://github.com/Tencent/puerts/assets/5946974/89a54093-11a7-458d-ab4b-33dc58cd5572)
![image](https://github.com/Tencent/puerts/assets/5946974/4450fdc1-0844-4aca-b8b6-d4c0dfb413c7)

3.创建 TestActor_Child，并调用TestFunction，发现通过调用父类函数，TestFunction和TestFunction2均可以调用到，但是父类的ReceiveBeginPlay无法调用到

![image](https://github.com/Tencent/puerts/assets/5946974/1ad84fa9-da51-42f8-bc6b-13ad5207acbe)

**Comment by chexiongsheng** [comment]
你试试先加载了子类，然后再mixin父类？

**Comment by lzj10** [comment]
我多测试了几次 ，感觉跟编辑器启动的加载顺序有关 ，跟代码里的类加载顺序关系不大，多重启几次编辑器有的时候调用父类就可以生效，但是调用生效的时候不关闭编辑器，PIE第二次会卡死。

**Comment by lzj10** [comment]
多次重启工程，有时候调用父类生效了，但是再次PIE直接卡死
![image](https://github.com/Tencent/puerts/assets/5946974/8f6e9a36-b3b6-4e26-8e92-e2223cff6e3e)
![image](https://github.com/Tencent/puerts/assets/5946974/f2214f8c-744c-4ddd-96af-694c4470f9e2)
卡死的时候应该是调用到父类ReceiveBeginPlay的时候，父类子类的ReceiveBeginPlay都没有打印出来 ，testfunction都执行成功
![image](https://github.com/Tencent/puerts/assets/5946974/c1b7f513-ff2b-4840-a787-88c5231d5eb2)

**Comment by lzj10** [comment]
追踪到是在蓝图执行的时候死循环了
![image](https://github.com/Tencent/puerts/assets/5946974/a6225d41-f60b-4210-a3de-cde136509c95)
![image](https://github.com/Tencent/puerts/assets/5946974/69179431-bd3c-41d5-b8d2-12b36c76350d)

**Comment by lzj10** [comment]
提交了一个demo分支
https://github.com/lzj10/puerts_unreal_demo/tree/test_mixin

**Comment by lzj10** [comment]
感觉第二次PIE启动的时候子类ReceieveBeginPlay的SuperStruct和父类的ReceieveBeginPlay的UFunction对象地址不同，TestFunction是一致的
![2ce91b3ea94b9193e90adff2bab5b1e](https://github.com/Tencent/puerts/assets/5946974/dec88288-3964-4b10-8622-eb06aeda3a6e)
![211e14dee1003e760b259acfa7bef64](https://github.com/Tencent/puerts/assets/5946974/9435159a-d8c3-48e4-a8f2-26d9089e9f04)

**Comment by chexiongsheng** [comment]
我没重现调用不到的情况。
倒是卡死是100%重现的。
卡死的原因倒是找到了：你给的demo，TestActor没有BeginPlay，你先mixin TestActor会导致TestActor添加BeginPlay，然后加载TestActor_Child会产生对TestActor添加BeginPlay的引用，然后停止播放后，被mixin的类都有一个restore行为，会把添加的方法删除，于是TestActor_Child引用了一个已经被删除的UFunction实例。

暂时的规避方法：你手动在TestActor添加一个空的BeginPlay重载。

**Comment by chexiongsheng** [comment]
你如果先加载了子类然后再mixin，子类调用基类将触发不了TestActor没有BeginPlay。因为对基类的调用已经定向到Actor那了。这应该是你偶尔不触发的原因。

**Comment by lzj10** [comment]
收到 感谢~

**Comment by chexiongsheng** [comment]
我把卡死解决掉。不过如果TestActor没有BeginPlay的话，仍然根据加载顺序不一样会出现不触发的可能。然后通过文档约束下。
