### ISSUE TITLE
[UE] suggestion 求问使用c++提供接口给ts，编译的时候v8报错。

### ISSUE THREAD

**Issue by pheyahu** [Tencent/puerts#1763]
## detail | 详细描述
求问使用c++提供接口给ts，编译的时候v8报错。使用的是注册的方式。
![20240618-151154](https://github.com/Tencent/puerts/assets/45094035/30264e01-42e5-4562-b583-872bc04095cf)
![20240618-151308](https://github.com/Tencent/puerts/assets/45094035/33062e13-41b2-41a7-b702-c86d695b371e)
![20240618-151319](https://github.com/Tencent/puerts/assets/45094035/ec77bbb6-64dd-455f-a4ee-49505ff95cc4)
![20240618-151252](https://github.com/Tencent/puerts/assets/45094035/f4e16823-8f6c-4221-8295-2c9e1c4bb972)

**Comment by chexiongsheng** [comment]
有个配置项没设置，看调用c++的文档

**Comment by pheyahu** [comment]
这些项都配置了的。
![20240618-152716](https://github.com/Tencent/puerts/assets/45094035/acdcc284-2182-4eda-9fff-93eea2a16c37)
![20240618-152726](https://github.com/Tencent/puerts/assets/45094035/8c74ccad-d7d0-47f5-b328-b3ae95679a46)

**Comment by chexiongsheng** [comment]
ue5.3+的ubt有bug，打开pch会让bEnableUndefinedIdentifierWarnings失效，需要关闭pch，你去参考下demo。
我文档补充下说明

**Comment by pheyahu** [comment]
没错了。 感谢

**Comment by chexiongsheng** [comment]
还是彻底去掉这要求好了
