### ISSUE TITLE
[UE] question 在ue5.4中，使用了异步加载出现数据获取不到。

### ISSUE THREAD

**Issue by pheyahu** [Tencent/puerts#1764]
## detail | 详细描述
自己封装了一个异步加载c++ manager async(path, callback）在ts中 callback(object){this.xxx //是一个undefined} 请问下这种方式如何处理？尝试把jsenv的singlethreaded = true 和threadsafe = true也无效 ，还尝试使用async wait promise也是没效果。

外边是一个单例，如果把回调传入c++中，c++的脚本object是否是从新创建了一个类，而不是之前的原先那个object了。如果使用static就可以获取到。

**Comment by chexiongsheng** [comment]
这貌似是js的基础问题吧？
需要bind一下？
