### ISSUE TITLE
[UE] Bug: 插件的蓝图类不生成type

### ISSUE THREAD

**Issue by ZhouXinyu001** [Tencent/puerts#1766]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

v1.0.6p1

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

插件的蓝图类不生成type

表现型错误
1. UE5.2, 在下述提交之前，插件的蓝图类，是生成到ue.d.ts
2. 在下述提交之后， 插件的蓝图类，就不生成了
![image](https://github.com/Tencent/puerts/assets/30308170/493975b8-bef0-4cc6-be7b-86e0106eb571)
https://github.com/Tencent/puerts/commit/dae96bc65ef8963d1b47f3098e24d9f5b9abe925

### 问题重现 | Bug reproduce

插件里任意蓝图必现

**Comment by chexiongsheng** [comment]
首先以前不可能生成到ue.d.ts的啊，生成到ue.d.ts有个`Obj->IsNative()`条件蓝图肯定得false。
生成到ue.d.ts的条件只是添加了个“或”，相当多了一种情况，这不会减少ue.d.ts的内容，只会持平或者增加。

要么你搞错出问题的commit了，要么你搞错或者描述错问题了。

**Comment by chexiongsheng** [comment]
这个commit是把原来生成到ue_bp.d.ts的内容挪到ue.d.ts，你是不是找错文件了？

**Comment by ZhouXinyu001** [comment]
我check了一下

情况如下
1. 现在使用v1.0.6p1 （未修改任何插件代码）
    插件中的蓝图，不生成typing，ue.bp.ts和ue.d.ts 都没有，相关引用报红
 2. 基于v1.0.6p1 revert 该commit中的内容
    插件中的蓝图，生成到ue.d.ts


有一些前提不知道会不会影响到生成
1. node作为backend
2. 下载v1.0.6p1的release中的[puerts_nodejs.tgz](https://github.com/Tencent/puerts/releases/download/Unreal_v1.0.6p1/puerts_nodejs.tgz)包
2. 开启引擎继承类

**Comment by chexiongsheng** [comment]
那你用基于v1.0.6p1 添加该commit中的内容就可以了。

**Comment by ZhouXinyu001** [comment]
嗯呢，非常感谢
