### ISSUE TITLE
[UE] question unreal ts中的class方法注册到ue中actor的委托，回调丢失ts的实例

### ISSUE THREAD

**Issue by pheyahu** [Tencent/puerts#1769]
## detail | 详细描述 大概的代码
class TsActor : UE.NewActor
{
    num = 3
    BeginPlay()
   {
       this.NotifyTest(this.test);
       this.NotifyTest(callback);
   ｝
    test()
   {
        console.debug(num);   //输出是undefined
    }
}

曲线救国：
function callback(obj:object)
{
      let o = <TsActor >obj;
      o.test();// 输出3
}

c++ NewActor : Actor
DECLARE_DYNAMIC_DELEGATE(FNotifyTest);
DECLARE_DYNAMIC_DELEGATE_OneParam(FNotifyTest1, const AActor*, A);

NotifyTest.Execute();
NotifyTest1.Execute(this);

结论：委托调用ts的时候把apply(this)丢失了，这个有更好的办法处理么？

**Comment by chexiongsheng** [comment]
有。
但这是基本的ts/js语法问题，建议先过一遍ts/js语法

**Comment by chexiongsheng** [comment]
原来这也是你提的啊：https://github.com/Tencent/puerts/issues/1764
我不是在那回复过了吗？
