### ISSUE TITLE
[UE] Bug:  NewMap(UE.BuiltinString, UE.BuiltinFloat) 作为函数参数传入蓝图函数，所有value赋值为0.000

### ISSUE THREAD

**Issue by ZhouXinyu001** [Tencent/puerts#1775]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

v1.0.6p1

### UE的版本 | UE Version

5.2

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

猜测是UE的蓝图Float为双精度，UE.BuiltinFloat 为单精度 （帮忙确认一下）
 导致NewMap(UE.BuiltinString, UE.BuiltinFloat) 无法转换成 蓝图中的Map((String, Float)
![image](https://github.com/Tencent/puerts/assets/30308170/6a3ed40b-7e0c-4688-8237-ce2562368eac)

### 问题重现 | Bug reproduce

    TS代码：
    const tMap = UE.NewMap(UE.BuiltinString, UE.BuiltinFloat)；
    tMap.Set('a', 1.1 );
    tMap.Set('b', 2.2);
    component.Test(tMap)
    
    
 蓝图中的Test函数
![image](https://github.com/Tencent/puerts/assets/30308170/42b70d99-67b3-41e6-aae5-109e45f06d85)

 运行时蓝图断点：
    NewParam: {
        a: 0.000,
        b: 0.000
    }

**Comment by chexiongsheng** [comment]
5以后的蓝图的float改为double了：https://github.com/Tencent/puerts/issues/712
不过C++写的UFunction那还有float，UE.BuiltinFloat还得保留并保持为float类型。
可以新增一个UE.BuiltinDouble

**Comment by chexiongsheng** [comment]
你试试用UE.NewMap(UE.BuiltinString, UE.BuiltinDouble)；

**Comment by ZhouXinyu001** [comment]
感谢更新~
