### ISSUE TITLE
关于文档的一些建议或者意见

### ISSUE THREAD

**Issue by llint** [Tencent/puerts#1781]
说说我的看法：

首先，对于PuerTS的思想我非常认同，代码质量还没有来得及没有仔细看，仅仅从使用者的角度提一些意见。

PuerTS的文档对于初次使用者非常的不友好，现有的文档里面并没有从使用者的角度基于几种典型的用例一步一步的引导；现有文档安装部分还行，但是使用手册只讲了一些功能性和实现方面的问题，完全没有从用户的角度，怎样从零开始使用PuerTS，就算有一些，也是零散的分布在文档和demo的说明中 - 从使用的易用性来讲，PuerTS相比UnLua还是有比较大的差距

比如使用C++代码创建JS虚拟机，是否是使用PuerTS唯一的方式？但是从 https://github.com/chexiongsheng/BlockBreakerStarter/ 这个示例看来其实可以不用手动创建虚拟机；然而，这个示例的说明也非常的晦涩，比如这个示例包括官方文档本身也没有说明，TypeScript目录下的TS_xxx.ts文件们和Content/Blueprints/TypeScript下的TS_xxx.uasset资源的对应方式 - 基于我自己的测试，这些资源应该是基于TS_xxx.ts文件自动生成的（我在本地删除了对应的BP - TS_xxx.uasset，重新打开编辑器，这些资源会自动生成）；然而，这些生成的蓝图的EventGraph又是可以编辑的 - 而没有任何文档说明如果对生成的蓝图进行编辑会造成什么样的影响 - 以UnLua的思维模式，一个蓝图会显示的绑定到一个Lua脚本，Lua脚本里面可以override蓝图里面的方法（当然不能在蓝图生成新的变量等等，这个是PuerTS的黑魔法），而PuerTS里面生成的蓝图资源和原始的ts脚本并没有一个非常明确的对应关系 - 目前的感觉是生成的蓝图和原始的ts脚本是有对应关系的 - 是通过Content/Blueprints/TypeScript/TS_xxx.uasset这个路径来对应根目录下的TypeScript/TS_xxx.ts文件的吗（或者是Content/Javascript/TS_xxx.js对应的）？文档里面无从得知。我试验过将TS_Player.uasset蓝图里面的EventBeginPlay节点删掉，发现脚本里面相应的ReceiveBeginPlay的逻辑不会再被调用 - 但是，但是，既然这个蓝图是基于TS/JS脚本生成的，那么这个蓝图的逻辑就不应该被修改，否则任何人都可以开始修改这个蓝图，最终导致脚本和蓝图不同步 - 这个现在看来是一个比较大的问题。

该方案适合C++调用ts脚本，类似于UnLua里面的脚本覆盖蓝图方法来实现将逻辑无缝的切换到脚本使用 - 当然目前看来从ts脚本里面调用UE的方法这个方式是支持得比较完善的

上面的是使用用例之一（无论其本身的问题 - 如果有问题，那么文档也应该清晰的标明）；然后就是我看到的实例里面的第二个用例：手动创建虚拟机，然后直接加载一个ts文件，执行里面的逻辑，主要在： https://github.com/chexiongsheng/puerts_unreal_demo 详细的就不多说了，在示例的说明里面，总是看得到“怎么跑这个demo”，然后blahblah的描述一番，好像我只要能跑这个demo就行了，但是根本没有描述，比如他的使用场景是什么，比如自己创建JsEnv并且加载一个脚本的使用场景是什么 - 就是文档有意无意的忽略了一些重要的细节，说了很多功能，但是有省略掉了很多 - 就好像一切都应该是不言自明的 - 不要忘记，作为PuerTS开发者，你的开发环境，上下文很多东西对于用户来讲都是不知道的 - 你一个demo扔出来，说明文档里面只有怎么跑是完全不够的 - 使用者根本没有你的上下文，很多东西是怎么来的根本不清楚 - 可以学习一下国外的软件是怎么写step by step guide的。

现在已经是UE5的时代了，而所有的示例还是基于UE4，虽然可以自己本地做一些修改，但是官方应该做一个UE5的分支，降低使用者的门槛

上面举的例子不是要作者来这里解答我的疑问，而重点是你的文档写得真的很不好 - 而实际使用体验也并没有非常丝滑 - 并不是你的文档或者说明里面描述得这么轻松（对，你的文档里面透露出一种举重若轻的轻松的感觉，觉得一切都很简单，你拿着跑就行了，其实实际情况不是这样的）

写了这么多，也是因为对puerts还是抱着期望的，希望作者能够采纳我的意见（我承认有点吐槽，因为使用下来的感受确实不太好），希望你们越做越好

**Comment by chexiongsheng** [comment]
首先呢有一部分历史原因：
最开始我希望往这个方向发展：https://github.com/chexiongsheng/BlockBreakerStarter，这貌似比较契合ue程序员的习惯，深度嵌入引擎。
但从和一些深度使用的游戏交流来看：https://github.com/chexiongsheng/puerts_unreal_demo，自己启动虚拟机，自己设计一个合理的脚本框架（他们一开始都是BlockBreakerStarter，后面随着使用变成了puerts_unreal_demo），脚本和引擎 有着清晰的界限更适合大型项目的运作。
所有基本上后期我都没做过BlockBreakerStarter方向的分享了，文档中我也添加了很多相关的说明，文档其实如果你从使用手册开始读，应该你的疑惑会少些。但如果你从网络分享的时间先后来看，会有你说的困惑。

并不是只有demo，文档在这里：https://puerts.github.io/docs/puerts/unreal/install

**Comment by llint** [comment]
感谢你的回复！

我必须要申明一点，我是认真看文档，而不是捡起半截就开跑的那种开发者。这才会对我造成比较大的困惑 - 我吐槽的其实就是github主页上的说明，以及 https://puerts.github.io/docs/puerts/unreal/manual/ 这个页面下的文档 - 其实里面的信息还是比较丰富的，但是并不是"Manual"或者“使用手册”真正应该讲的。

当然你的回复其实在某种程度上澄清了BlockBreakerStarter并不是PuerTS官方推荐的方式，那么在使用手册里面，或者这个demo的说明里面应该明确的标明（明确不是说可能在哪里提过一嘴，而是能通过读文档很明确的知道正确路径）

确实很多细节是可以通过看代码研究，但是step by step guide也是非常必要的，叫做"Tutorial“，里面不应该讲本质，而是假设你什么都不懂，我一步一步的教你怎么用官方推荐的方法搭建起这个demo，而不是说，我能做123，然后这个是demo，你自己看代码去 - 可以请一个专门写技术文档的 - PuerTS应该很有潜力，文档是门面。

**Comment by chexiongsheng** [comment]
可能和你理解的不太一样，[puerts_unreal_demo](https://github.com/chexiongsheng/puerts_unreal_demo)不是展示你实际项目怎么做，只是用来演示api使用。
不需要什么step by step搭建那个demo，随便搞个空项目，在任意地方（例子是GameInstance，但这不是必要的）构造FJsEnv都可以跑那脚本。
无论是ue还是unity下的所有脚本方案，都是提供个脚本环境并让其和宿主环境交互。游戏用这种方案，都是在你的系统画一条线，一边是引擎（宿主），一边是脚本，然后用提供的交互方式把他们结合起来。这条线随自己业务需要来画，我不做规定，不做约束，不做示范（你理解这点就理解puerts_unreal_demo的做法）。
脚本怎么用有语言本身官方或者非官方的文档。所有脚本方案最应该做的是描述清楚“怎么交互”。

**Comment by chexiongsheng** [comment]
就脚本使用来说，unity社区远远比unreal社区应用得广泛而深入。都是自己new 1个或者n个虚拟机的方式。我在xlua的实例也是演示“怎么交互”，而不是具体某个游戏demo。

**Comment by llint** [comment]
此回复聚焦到一个具体问题：蓝图Mixin的使用

目前看来，Puerts从ts侧（通过反射）调用UE API这部分功能是没有什么问题的。然而从UE侧调用ts脚本逻辑至少在文档和用例上面不是非常清晰。

以UnLua为例，其主要的方式（也是其最丝滑的方式）是为每个蓝图类显式绑定一个Lua脚本，然后通过方法覆盖（method overriding）的方式将逻辑导入到Lua脚本。每个Lua脚本和一个蓝图一一对应，脚本以一个非常解耦的方式存在，Lua脚本内部也不需要显式的去绑定任何一个蓝图（脚本代码里面加载蓝图不算）。不需要使用者显式在一个集中的地方注册所有绑定Lua脚本的蓝图，有点类似于C++里面的static registration的概念。

而目前puerts从UE侧将逻辑“引导”到脚本有下面几种方式：

1. 通过C++侧创建的JsEnv，调用其Start方法来显式执行一个ts脚本，该脚本应该可以做一些初始化操作（下面会描述一个基于我的理解可能是一个不错的想法）
2. 通过DELEGATE方式从C++触发脚本逻辑
3. 通过蓝图Mixin用脚本覆盖的方式执行脚本逻辑（类似UnLua的覆盖方式？）
4. 通过ts脚本直接继承引擎类的方式；目前看起来虽然方便，但是其实并不是推荐的方案，而且上面的描述也讨论了一些使用上的问题 - 其实该方案是最像UnLua，并且从宏观使用层面比UnLua/mixin的覆盖方式更加强大，但是。。。

由于机制不一致，puerts和unlua的脚本在激活方式上非常的不一样
UnLua: 在蓝图里面绑定到对应的UnLua脚本，然后只要脚本里面有覆盖的方法，那么相应的覆盖脚本逻辑就会被执行
Puerts: 没有类似于UnLua的脚本绑定机制 - 目前看到的唯一（也可能不是唯一，除了上面的第4点，直接继承引擎类）的脚本入口方式是通过JsEnv.Start的方式加载一个脚本。

所以，其实在[文档](https://puerts.github.io/docs/puerts/unreal/manual)和示例代码里面我能看到被显式加载的脚本只有两个：QuickStart和FFITest，都是在相应的TsGameInstance.cpp以及FFITestGameInstance.cpp这两个文件里面（文档里面只提到QuickStart）。

那看这个文档以及puerts_unreal_demo随之而来的疑问就是：其他的这些ts是如何被加载的？里面的逻辑是哪里被调用的？？比如以Mixin举例，文档里面以及示例里面详细的描述了怎么去mixin，但是这个ts代码是哪里被触发的？？文档里面找不到答案，打开puerts_unreal_demo里面搜C++代码，蓝图MixinTest.uasse里面本身没有信息。。。直到我突然意识到，是不是需要把JsEnv->Start("QuickStart", ...)里面的QuickStart替换为UsingMixins才能显式的加载UsingMixins.ts，并执行里面的代码？而我随后也在AsyncTest.ts和UsingWidget.ts这两个文件的开头找到了这样的话：“UTsGameInstance::OnStart里头，把QuickStart改为AsyncTest” - 所以这里先不说文档，在demo或者是测试代码的组织方式上，其实也是有一些问题的：不能手工的改代码来展示或者测试不同的scenarios。

文档里面对于JsEnv->Start的描述其实也是一笔带过：此方法是启动整个虚拟机的函数，还是说可以调用多次来执行不同的脚本，也就是说起功能类似LoadScript（加载脚本）的功能？实测下来，Start函数一个JsEnv只能被调用一次。

因此使用DELEGATE或者Mixin的方式调用ts脚本需要有一个地方能够触发delegate或者mixin的注册（注册本身发生在ts脚本内部，而且要手动代码注册）- 而整个puterts唯一能够触发ts入口的地方只有JsEnv.Start这一个地方（且只能调用一次），因此这个入口脚本在一个真实的项目里起到的作用其实就显得尤为重要 - UnLua在这个层面上，使用者并不需要特别关心这个脚本入口 - 因为一旦进行了蓝图和脚本的绑定，脚本逻辑会自动覆盖，不需要再手动的去写代码来进行mixin注册 - 对的，UnLua其实和Mixin的方式类似，然后puerts的mixin需要在脚本里面反向的加载一个蓝图或者Native类进行代码级别的注册才能使用。

因此无论从文档还是puerts_unreal_demo的示例代码，都没有对真实应用场景进行一个建议性的方案 - 一个真实的项目，举一个简单的例子：我有任意一个AMyActor C++类，其有一个蓝图子类BP_MyActor，那么我这个时候需要有一个对应的ts脚本来覆盖BP_MyActor或者AMyActor基类的某些方法，在一个真实的项目中应该怎么做？我不可能创建一个MyActor.ts脚本，内部进行Mixin或者delegate的手动注册，然后用JsEnv.Start来启动它吧？我如果还有AMyActor2, AMyActor3, ....不断增加的类呢？而在开发的过程中可能还得删掉一些蓝图和C++类（太多组合情况），文档和示例代码都没有给出任何实际的建议。而UnLua的绑定方式非常自然的解决了上述问题。

并且，在UsingMixin.ts这个示例里面，对于蓝图的Mixin使用，SpawnActor其实是Spawn我的Mixin类，而并不是蓝图类本身 - 那如果我在其他地方，比如在另外一个蓝图里面去SpawnActor的时候如果只指定了蓝图类，这个情况下，生成的Actor实例是否可以调用mixin里面覆盖的方法？这个我还没有试验，但是文档和示例也都没有说明。如果只能在脚本里面Spawn mixin之后的类，那这个基本上没有实际的意义 - 对比UnLua，绑定了UnLua的蓝图类在其他地方按原始蓝图类进行实例化，而实例化之后的Actor仍然可以调用被Lua覆盖的方法 - 这个就很自然，就非常的non-intrusive。_实测结论_：一旦在入口执行了mixin的注册之后，在其他蓝图里面实例化原始蓝图之后，是可以调用到minin覆盖的方法的 - 但是在文档里面并没有将此重要事实标明。

*** UsingMixin.ts的47行其实应该把`MixinTestWithMixin.StaticClass()`改为`ucls`，这样就很好的演示了就算spawn原始的蓝图类，也能调用被覆盖的脚本逻辑。

最后，基于我到目前为止的理解，上面提到的如何在真实项目内，为每个（任意多个）蓝图类注册对应的ts类来覆盖其方法（类似UnLua的工作流程），我大概有下面的想法（其实官方应该推荐一个建议的方式）：_可以看出比UnLua要复杂_

1. 在<ProjectRoot>/TypeScript脚本根目录下，创建和蓝图类对应的目录结构
2. 每一个蓝图类对应一个ts文件，比如BP_MyActor0蓝图类对应MI_MyActor0.ts脚本（路径也对应）
3. MI_MyActor0.ts脚本内部进行对应蓝图BP_MyActor0的Mixin注册，并且编写相应的覆盖逻辑（比如MixinTest蓝图类的Log方法）- 将注册代码包装到一个函数比如init()里面，并且在ts脚本最后调用init()
4. 在TypeScript脚本根目录下定义一个全局的入口函数：Entry.ts，该脚本内部使用[这个stackoverflow问题](https://stackoverflow.com/questions/40702842/how-to-import-all-modules-from-a-directory-in-typescript)提供的方法之一来自动的import TypeScript目录下的对应的蓝图mixin目录下的ts文件，实际效果就是所有的蓝图mixin注册会自动的被调用，所有的mixin方法都会被注册完毕
5. 在JsEnv.Start方法传入唯一的这个Entry.ts文件执行上述逻辑
6. 当然Entry.ts还可以有其他的初始化逻辑

我不知道这个方案是否合理，当然官方文档也没有任何的建议，或者有更好的方法？（这里不再讨论继承引擎类的方法）期待回复！

**Comment by chexiongsheng** [comment]
你希望得到的是框架，而我希望puerts的定位是一些核心机制，你要的框架应该由社区提供（当然，官方也是社区的一部分，如果没人提供，官方提供也行，但那不是puerts，是另外一个项目。）

我做公共组件那么多年，发现很多人的一个误区是总觉得自己的情况就是全世界普适。实际情况不是这样，各项目千差万别。

以你提到的最简单的一个点为例：FJsEnv的构建。有另外一个做游戏平台的项目是用户点击了按钮才启动虚拟机，退出那个小游戏就释放FJsEnv，然后我把你说的FJsEnv的构建定死了，然后那个项目不用或者自己费力去改造吗？除了这个项目还有其它项目有他们不同的述求呢。

即使能通过各种复杂的配置支持满足各色需求，那也会导致臃肿和增加单个客户使用复杂性。
你看nodejs，只是提供一些核心机制：异步，网络，文件。。然后再由第三方形成一些框架来满足各种需求：electron是客户端框架，express.js是http服务器框架，commander可以用来编写命令行工具。。。

回到这个问题，我也希望能够形成各色框架来满足各种差异化的需求。

你如果觉得你提的述求很普适，何不把它们做出来形成一个框架呢？

**Comment by chexiongsheng** [comment]
另外，脚本间引用通过import来，这是ts的语法。不一定非得放Start才能执行。
mixin自动加载我之前回复过一些讨论和issue，给过一些项目实践，由于通用性不好，没搞到puerts，我还是希望用户自己去根据自己实际情况做合适的自动加载。ps：你有没真正在项目里头用过unlua呢？据项目反馈它那种自动加载方式有比较大的问题。

**Comment by llint** [comment]
PuerTS不应该作为一个框架提供吗？如果你做一个PuerTS，无论它是什么，它不应该有一个或者一些应用场景在你的做这个东西的时候作为一个设计导向吗？本来一个库和一个框架能很难说要去真正普适所有的应用场景，PuerTS是否被设计出来想去适用于所有的场景的？就算是，这个在你的文档里面也没有描述。另外就算一个相对比较通用的库或者框架，在介绍它的时候，也应该有一个导向性的，或者是作者在做这个库或者框架的时候，心里应该也有一个比较理想的使用方式和适用场景吧？而且这些使用方式应该是尽量能够符合真实使用场景，而不仅仅是一个比较受限的，仅仅展示一些功能的东西，做一个东西连解决一个真实使用场景的案例都没有，只在细节上说我有这样那样的功能，到最后来发现实际使用场景其实是非常受限的，或者还需要用户去猜能够怎样做，

另外你提到UnLua，“据项目反馈”，我不知道是哪个项目的反馈？是一个项目反馈还是所有使用UnLua的项目都有一样的反馈？另外“自动加载方式有比较大的问题”，有具体问题的描述吗？那如果确实UnLua的脚本加载方式确实有问题的话，那么PuerTS建议的方式是什么呢？或者使用PuerTS项目大概是以一些什么方式在使用呢？如果都是把JsEnv->Start作为所有脚本的入口，然后所有的逻辑成为都以脚本驱动了（是否连主循环都在脚本里面？我不得而知）- 那这个方式也不能被认为是普适的方案吧？

脚本间的引用和执行确实不需要Start来执行，但是你的最初的脚本入口现在看来其实就只有从JsEnv->Start才能触发（不谈脚本继承引擎类的功能，最初我觉得这个可能是最有希望的方案，但是连你自己都不建议了）。

多的不说了，打字其实也可能会造成很多的误解，也不一定能够真正的把问题阐述清楚，本来可能只是就事论事，希望更好，结果有可能被读的人误解，而且另外一个帖子里面还有人说风凉话，这根本不利于大家constructively的讨论让这个软件做得更好。如果有机会可以以不用打字的方式交流，我觉得可能会更叫有效。

这个thread的讨论就此为止吧。有机会可以单独沟通一下。

**Comment by chexiongsheng** [comment]
> PuerTS不应该作为一个框架提供吗？如果你做一个PuerTS，无论它是什么，它不应该有一个或者一些应用场景在你的做这个东西的时候作为一个设计导向吗？本来一个库和一个框架能很难说要去真正普适所有的应用场景，PuerTS是否被设计出来想去适用于所有的场景的？就算是，这个在你的文档里面也没有描述。另外就算一个相对比较通用的库或者框架，在介绍它的时候，也应该有一个导向性的，或者是作者在做这个库或者框架的时候，心里应该也有一个比较理想的使用方式和适用场景吧？而且这些使用方式应该是尽量能够符合真实使用场景，而不仅仅是一个比较受限的，仅仅展示一些功能的东西，做一个东西连解决一个真实使用场景的案例都没有，只在细节上说我有这样那样的功能，到最后来发现实际使用场景其实是非常受限的，或者还需要用户去猜能够怎样做，
> 
> 另外你提到UnLua，“据项目反馈”，我不知道是哪个项目的反馈？是一个项目反馈还是所有使用UnLua的项目都有一样的反馈？另外“自动加载方式有比较大的问题”，有具体问题的描述吗？那如果确实UnLua的脚本加载方式确实有问题的话，那么PuerTS建议的方式是什么呢？或者使用PuerTS项目大概是以一些什么方式在使用呢？如果都是把JsEnv->Start作为所有脚本的入口，然后所有的逻辑成为都以脚本驱动了（是否连主循环都在脚本里面？我不得而知）- 那这个方式也不能被认为是普适的方案吧？
> 
> 脚本间的引用和执行确实不需要Start来执行，但是你的最初的脚本入口现在看来其实就只有从JsEnv->Start才能触发（不谈脚本继承引擎类的功能，最初我觉得这个可能是最有希望的方案，但是连你自己都不建议了）。
> 
> 多的不说了，打字其实也可能会造成很多的误解，也不一定能够真正的把问题阐述清楚，本来可能只是就事论事，希望更好，结果有可能被读的人误解，而且另外一个帖子里面还有人说风凉话，这根本不利于大家constructively的讨论让这个软件做得更好。如果有机会可以以不用打字的方式交流，我觉得可能会更叫有效。
> 
> 这个thread的讨论就此为止吧。有机会可以单独沟通一下。

首先，启动虚拟机然后一个Start入口这怎么就不普适了？几乎所有语言都是类似的方式（以c为例子就是一切从main函数开始）。这你质疑啥？

如果具体到游戏脚本，unity下所有脚本方案都是类似的方式，有妨碍unity是脚本应用最广泛的引擎吗？

如果再具体到puerts，那么多项目使用上也没多少问题，鸣潮都全球全平台上线了。

puerts目前用继承ue类方式的项目有，用自己启动虚拟机加上个mixin功能的项目也有，以上两者都不用只用最基础的交互能力也有。我觉得设计能力越好的团队，我就越建议用最基础的交互能力。继承ue类方式和mixin功能对于有设计能力的都是条条框框。

其实我理解你就是希望人家做了规范，设计好整个架构，然后你只是填下空。自由度一高就不知道从何入手。

**Comment by llint** [comment]
(这句是最后加的，第一二段话针对你的回复有一些情绪的回复，本来想删了，但是觉得直接表达一下也没问题，就留下了，但是你看看就好，don't take it too personally，互相攻击一下，最后能拉回来就行，哈哈)

我在跟你讨论软件设计，文档的完整度，没有质疑你个人的能力，我甚至都没有说Puerts做得不好，只是一些特定方面有不足或者至少是没有清晰描述，而你就开始攻击Puerts潜在用户的设计能力？有点可笑，说明你的格局很有问题。你始终是不愿意承认Puerts（注意我说的是Puerts，不是你个人）在文档上，在使用场景上的设计（特定于UE5场景，而不是Unity）是有欠缺的。就像你做了一个产品，然后宣称，不要对这个产品有质疑，不会用说明你能力有问题，不是我的产品设计有问题 - 格局应该打开一点，有人愿意花这么多精力来和你探讨其实已经是对这个软件和作者的尊重 - 不知道你有没有经常去国外软件讨论社区比如stackoverflow或者reddit上面看过，大家的讨论都是非常正向的，非常的constructive的。到了国内这个环境，本来觉得一个软件还比较promising，结果发现作者怎么一付：“又不是不能用“的态度，有一些疑问和质疑，作者就开始来对提出疑问的人的能力进行攻击。是不是国内的开发思路都是这样？

回到讨论本身，其实通过我们的交流，我对于Puerts的使用场景的设计是有了更深入的了解，我就不做结论性的总结了，免得继续陷入无谓的争论最后发展成人身攻击。可能你周围的人都是对这个东西膜拜，敢站出来吐槽的估计没有，就算心里有疑惑的，可能也只有自我怀疑一下，是不是我能力不行，算了还是别问了这种心态。往往敢站出来吐槽的，可能反而是人群里面清醒的那个。

还是保持constructiveness，我把我上面的自动注册mixin的想法写了一个ts脚本，并且本地验证是可行的，我重新开一个issue，把ts代码分享出来，也算是给到一个比较实际的案例，至少给到更多想要使用puerts的用户一个思路。

**Comment by chexiongsheng** [comment]
文档完整度建议我接受啊。
或者对设计上的任意质疑我都可以讨论。
但问题是puerts现在提供是机制，不是框架，这有啥好质疑的？
就好比我开面粉店，你跑过来说想要面包，跑过来说我卖面粉不对？？（原话：PuerTS不应该作为一个框架提供吗？）
我觉得有点浪费时间。
我也反复解释了，我提供面粉，是希望不仅仅满足做面包客户的需求，还可以满足做面条的，做烧饼，又质疑面粉没有通用性？你不觉得有点浪费时间吗？
我也明白你要的是面包，我也建议要么自己买面粉回去自己做，要么等别人做出现成的。
你回头看是不是我通篇都在说这个？

**Comment by morirain** [comment]
你想要的比给的更多而已，问题是就算别人做好一整套方案你也不可能去用啊，目前的几种接入方式已经足够了，再往深入扩展不就到项目级的需求了吗？

**Comment by llint** [comment]
https://github.com/Tencent/puerts/issues/1786

**Comment by WenzhiShao** [comment]
看大佬们的讨论觉得收获很多。做为初次尝试接入TS到ue的同学，确实会对一些概念比较困惑，在文档中似乎一时也找不到答案。关于作者提到，有多种接入虚拟机的方法，我觉得作者有时间的话不妨可以总结一下自己丰富的经验，可以尝试探讨一下不同的方案，优劣在哪里，顺便给出几个简单的例子。有的时候太灵活，提供的方案太多，反而会拉高学习门槛。比如常见的认知是，Vue的灵活度小于React，但是却更易用更受欢迎。又比如unreal提供了更完整却更固定的gameplay框架，Unity只提供了组件，需要自己搭建gameplay框架，后者显然更普适。但是对初学者来说，有这么一个现成的，更易学习。

**Comment by llint** [comment]
一个面粉店在广告里面展示各种精美的面包，烧饼，馒头。

顾客被面粉店的广告吸引，来到店里，发生了下面的对话：

顾客：你们广告上的这款面包很不错，有卖的吗？
老板：没有的哦亲，我们只卖面粉哦
顾客：那你们广告打那个精美的面包
老板：我们的面粉肯定是可以做出那个精美的面包哦，但是面包得你自己做哦
顾客：好吧，那我第一次做面包，有没有推荐的做法啊，我买了面粉回去试着做做吧
老板：我们是面粉店，没有推荐的面包做法的哦，你可以按你自己的想法作哦，而且我们的面粉除了可以做面包还可以做面条和烧饼哦，做不出来那是你自己的问题哦亲~
顾客：。。。。。。。。。。。。

**Comment by NEUGWB** [comment]
> 一个面粉店在广告里面展示各种精美的面包，烧饼，馒头。
> 
> 顾客被面粉店的广告吸引，来到店里，发生了下面的对话：
> 
> 顾客：你们广告上的这款面包很不错，有卖的吗？ 老板：没有的哦亲，我们只卖面粉哦 顾客：那你们广告打那个精美的面包 老板：我们的面粉肯定是可以做出那个精美的面包哦，但是面包得你自己做哦 顾客：好吧，那我第一次做面包，有没有推荐的做法啊，我买了面粉回去试着做做吧 老板：我们是面粉店，没有推荐的面包做法的哦，你可以按你自己的想法作哦，而且我们的面粉除了可以做面包还可以做面条和烧饼哦，做不出来那是你自己的问题哦亲~ 顾客：。。。。。。。。。。。。

可是这家店从来没展示精美的面包，烧饼，馒头，也没说自己家面粉能做精美的面包，烧饼，馒头——因为这会让你不会做面条、包子、馄饨。
