### ISSUE TITLE
[UE] Bug: WaitGameplayEvent 蓝图没有问题，但是Ts调用后无反应

### ISSUE THREAD

**Issue by 313364973** [Tencent/puerts#1799]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

5.3.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

![image](https://github.com/user-attachments/assets/c1d76282-b69e-4ecc-9a77-ba48d8100574)
蓝图的代码可以打印出"收到取消事件",同样的方式，使用ts去执行
![image](https://github.com/user-attachments/assets/438d9fa1-7fa2-4f3e-9e78-498f449cb78b)
已经确定这个函数是执行了的，log里也无报错，但是没有打印出收到取消事件

### 问题重现 | Bug reproduce

![image](https://github.com/user-attachments/assets/c1d76282-b69e-4ecc-9a77-ba48d8100574)
蓝图的代码可以打印出"收到取消事件",同样的方式，使用ts去执行
![image](https://github.com/user-attachments/assets/438d9fa1-7fa2-4f3e-9e78-498f449cb78b)
已经确定这个函数是执行了的，log里也无报错，但是没有打印出收到取消事件

**Comment by 313364973** [comment]
想问下GameAbility是不是不支持呢。

**Comment by 313364973** [comment]
这个GameAbility类是用ts的mixin方法的

**Comment by 313364973** [comment]
这个节点是个latent节点，是不是不支持这种节点，比如说类似于Delay这种节点

**Comment by chexiongsheng** [comment]
试过调用过。
不过调用起来比较复杂。
含latent的函数在蓝图中调用，蓝图会自动帮你生成些东西让你看上去是同步调用，没有这种自动生成要使用会显得复杂（c#和js的await也类似，看起来顺序，其实是编译器通过生成代码糖化了）。
所以并不建议在ts直接用，可以封装下给ts使用。

**Comment by 313364973** [comment]
好的，感谢大佬，那蓝图封装下给Ts再调用好了
