### ISSUE TITLE
在C#定义一个enum，转成ts后，在ts里将一个number转成该enum，转出来的值是undefined

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#18]
我在C#里定义一个enum：
enum Foo{
    A = 1,
    B = 2
}
然后将这个enum纳入Binding列表。在Unity按下Generate Code，转成ts。
接着在一份ts档里写下这两行代码：
import {Foo} from "csharp";
console.log(Foo[2]);
打印出来的类型是undefined。预期应该要能打印出B。

**Comment by chexiongsheng** [comment]
这样访问：Foo.A
