### ISSUE TITLE
[UE] Bug: 线上环境 V8 偶先 GC 崩溃，本地无法复现

### ISSUE THREAD

**Issue by hewenning** [Tencent/puerts#1808]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.2

### UE的版本 | UE Version

5.3

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

![image](https://github.com/user-attachments/assets/63ee65b3-f41d-4c23-b15c-e2ae78ebcb96)
![image](https://github.com/user-attachments/assets/5d30ecd4-9a73-4820-899e-c7269caf269f)
![image](https://github.com/user-attachments/assets/40f48c98-c700-4b3f-8bf2-cf469c27a96e)

### 问题重现 | Bug reproduce

我们线上环境偶先崩溃，崩溃时虚幻日志是同一行，我检查了下相关的代码，没有发现异常的写法，崩溃发生在游戏刚启动时，业务系统刚刚创建完，不知道车大有没有遇见过类似的崩溃栈，我准备编译一个 asan 版本看看

**Comment by hewenning** [comment]
我看日志崩溃是在同一行，但是没有崩溃的相关的信息记录在日志里面。崩溃发生时候抓到的调用栈也都不一样，但是都是 GC 触发的。

**Comment by chexiongsheng** [comment]
有可能是这个问题导致：https://github.com/puerts/backend-v8/issues/13
你更新到最新编译的v8看能否解决，推荐94版本：https://github.com/puerts/backend-v8/releases/tag/V8_9.4.146.24_240730

**Comment by hewenning** [comment]
我尝试下，看这块触发的情景，应该是这个问题，感谢车大~~~
