### ISSUE TITLE
[UE] Bug: 应该对 #1744 引入的变更用文档说明

### ISSUE THREAD

**Issue by morirain** [Tencent/puerts#1810]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

目前

### UE的版本 | UE Version

UE 5.4

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

改动后移除了变量默认的flag，使其在编辑器下默认不可见，这个行为与之前的版本差异很大

**Comment by morirain** [comment]
相关 #1744

**Comment by chexiongsheng** [comment]
这PR本来只是改bug，倒没留意引入变更。
我觉得可以在这PR的基础上加个默认值？

**Comment by chexiongsheng** [comment]
你修改下然后PR过来？
