### ISSUE TITLE
[UE] tsc怎么转换单个ts到js？

### ISSUE THREAD

**Issue by meilaopo** [Tencent/puerts#1822]
## detail | 详细描述
以demo为例，在vs code 打开项目文件夹，
在终端执行tsc TypeScript/QuickStart.ts 有报错
node_modules/@types/react-reconciler/index.d.ts:412:34 - error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

手册页面没找到相关说明
https://puerts.github.io/en/docs/puerts/unreal/manual

**Comment by chexiongsheng** [comment]
这是typescript的内容，我不可能把整个typescript社区的文档搬过来。
有tsconfig.json，意味着这是一个ts工程。tsconfig.json就是这个工程配置，相当于vc的.proj文件，你应该编译它。
