### ISSUE TITLE
[UE] unreal有没有StaticWrapper功能

### ISSUE THREAD

**Issue by meilaopo** [Tencent/puerts#1823]
## detail | 详细描述
unity版本的文档提到生成静态绑定代码功能，unreal版本有没有此功能呢？

**Comment by chexiongsheng** [comment]
对应到unreal就是模板绑定功能。
模板绑定功能比默认的反射快，但其实一般项目也用不上那么快。ue的反射比unity的静态wrap还快，目前没项目反馈不够用得上模板绑定。
模板绑定目前大多用来实现不支持反射的api的封装（不是为了性能）。ue本身有些api不支持反射，还有业务自己写的，还有些第三方库等等。

**Comment by meilaopo** [comment]
多谢
