### ISSUE TITLE
[UE] import ue问题

### ISSUE THREAD

**Issue by meilaopo** [Tencent/puerts#1830]
## detail | 详细描述
在unity demo中QuickStart.mjs可以直接使用CS.UnityEngine.Debug.Log('hello world');
而unreal demo中需要先import * as UE from 'ue'
为啥会有这种区分

**Comment by chexiongsheng** [comment]
最开始unity也是import * as csharp from 'csharp'
其实这种比全局变量更好，不过这种方式在esm下支持不了lazyload。
