### ISSUE TITLE
[UE] puerts gen tools 这个工具是不是没有开源？

### ISSUE THREAD

**Issue by meilaopo** [Tencent/puerts#1831]
## detail | 详细描述
常用结构体的静态绑定代码是通过这个程序生成的，怎么扩展更多的结构体胶水代码呢

**Comment by chexiongsheng** [comment]
这是过时淘汰的技术。
现在用模板绑定。适用性更强，更简单。

**Comment by 13007234056** [comment]
> 这是过时淘汰的技术。 现在用模板绑定。适用性更强，更简单。

请问有参考链接吗
