### ISSUE TITLE
[Unity] Bug: new JsEnv() can't be always called on a separate thread in the Editor

### ISSUE THREAD

**Issue by DoctorGester** [Tencent/puerts#1847]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.1.0

### Unity的版本 | Unity Version

2023.1.13f1

### 发生在哪个平台 | Platform

Editor(mac)

### 问题重现 | Bug reproduce

This highly depends on installed packages, but `JsEnv` constructor calls `TypeManager.InitArrayTypeId();` which in turn calls `Puerts.Utils.GetExtensionMethodsOf(typeof(Array))`. Certain packages seem to call Unity-specific methods in their static constructors which produces an error when called outside of the main thread.

We have this hack in the main thread before launching a Thread which creates JsEnv

```cs
    private void MaybeInitializePuertsHack() {
        // Workaround to run JsEnv on a separate thread, otherwise it tries to discover some extension methods
        //  of Array class which trigger static init of things which can only be initialized on the main thread, sigh...
        // Only seems to happen in the editor though
#if UNITY_EDITOR
        if (!initializedPuertsHack) {
            Puerts.Utils.GetExtensionMethodsOf(typeof(Array));
            initializedPuertsHack = true;
        }
#endif
    }
```

We don't need reflection at all because all of our methods are registered from the generated source bindings but it seems like there is no way to turn off discovery of extension methods specifically for Array class when in the editor. It also produces a huge multi-second delay for us.

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/e86e0ce9-a9e1-4bf3-a749-549c79765185">

**Comment by chexiongsheng** [comment]
The main reason is that the editor supports development without generating code, At this time, reflection is used. If you also generate code for development in the editor, the logic of reflecting ExtentionMethods can be removed. If you don't use ExtentionMethods at all, you can simply remove this feature.

**Comment by DoctorGester** [comment]
> The main reason is that the editor supports development without generating code, At this time, reflection is used. If you also generate code for development in the editor, the logic of reflecting ExtentionMethods can be removed. If you don't use ExtentionMethods at all, you can simply remove this feature.

I feel like there should be a define to disable this even in the editor, another define maybe? I can edit the code, but then I would have to patch it after every update and what about openupm users?

**Comment by chexiongsheng** [comment]
PUERTS_DISABLE_REFLECT_EXTENSION in the next openupm version.
