### ISSUE TITLE
[UE] Bug: rider下直接编译工程，会有The "CheckIfPackageReferenceShouldBeFrameworkReference" task could not be loaded的报错

### ISSUE THREAD

**Issue by cgsgood** [Tencent/puerts#1849]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

git上的最新版本

### UE的版本 | UE Version

UE 5.4.2

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

>Microsoft.NET.Sdk.DefaultItems.Shared.targets(80,5): Error MSB4062 : The "CheckIfPackageReferenceShouldBeFrameworkReference" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\8.0.107\Sdks\Microsoft.NET.Sdk\targets\..\tools\net8.0\Microsoft.NET.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。 Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. (H:\UEProj\puerts_unreal_demo\Plugins\Puerts\Source\CSharpParamDefaultValueMetas\CSharpParamDefaultValueMetas.ubtplugin.csproj)

11>Microsoft.NET.TargetFrameworkInference.targets(138,5): Error MSB4062 : The "AllowEmptyTelemetry" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\8.0.107\Sdks\Microsoft.NET.Sdk\targets\..\tools\net8.0\Microsoft.NET.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。 Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. (H:\UEProj\puerts_unreal_demo\Plugins\Puerts\Source\CSharpParamDefaultValueMetas\CSharpParamDefaultValueMetas.ubtplugin.csproj)

### 问题重现 | Bug reproduce

1、下载puerts_unreal_demo工程，并配置一切需要的依赖，用UE 5.4.2（源码版）生成 .sln文件
2、直接用rider 2024.2.4 打开工程后，直接编译puerts_unreal_demo工程，则会报上述错误

**Comment by BlurryLight** [comment]
算是Rider自身的问题吧，通常是由于电脑安装了高版本的DotNet环境，导致Rider会自动寻找到高版本的Dotnet。
修改Rider的设置，改到虚幻自带的DotNet就可以了。
![image](https://github.com/user-attachments/assets/0c43de96-ec8a-40cc-bc39-eafabe278215)

**Comment by cgsgood** [comment]
试了下_BlurryLight_的解决方法，确实可行！非常感谢

**Comment by AKe-063** [comment]
成功解决了问题，非常感谢！

**Comment by Purlemon** [comment]
谢谢你露娜
