### ISSUE TITLE
[unity] 安卓ARMv7平台, 首次启动时获取C# enum异常

### ISSUE THREAD

**Issue by layerpsr** [Tencent/puerts#185]
在安卓ARMv7平台使用sqlite3的过程中遇到一个问题:
当我安装app后, 首次启动时在js中调用C# enum类型, 得到不是number类型.

puerts libVersion: 10;

代码:
![5YM`0$HAZ~XR0~2JN1$_WSU](https://user-images.githubusercontent.com/45587825/111859272-8aa4be80-897a-11eb-8354-8aeae7a75a6d.png)

错误的输出(仅首次启动):
![FTQIYAB5 `LY(SJ X8RL2(0](https://user-images.githubusercontent.com/45587825/111859204-179b4800-897a-11eb-97cf-a0c928e7b45e.png)
正常的输出:
![F7H%J1W2H933T81~FV DAM6](https://user-images.githubusercontent.com/45587825/111859208-1c5ffc00-897a-11eb-9917-46e922a50507.png)

C#类型:
![{W`EXPCIL A` 8{P%C$%AVV](https://user-images.githubusercontent.com/45587825/111859215-25e96400-897a-11eb-816d-1885829197d9.png)
![C)PPC~M6~KX`TZY2PSG4TBH](https://user-images.githubusercontent.com/45587825/111859217-28e45480-897a-11eb-8434-b8966bcf49c2.png)

**Comment by layerpsr** [comment]
在sqlite[http://www.sqlite.org]中下载了安卓sqlite3库文件(版本更大)并替换, 发现问题暂时消失了...

**Comment by chexiongsheng** [comment]
感觉像是这个DbType被剪裁了。
剪裁的话，CS.namespace.enumclass会被认为是个namespace，namespace是用个js object来表达的。
