### ISSUE TITLE
[UE] Bug: TS里的属性，在蓝图里无法访问

### ISSUE THREAD

**Issue by cocochengang** [Tencent/puerts#1854]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.7

### UE的版本 | UE Version

UE 5.4.4

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

如图，升级到 1.0.7后，是需要在哪里设置吗，才能跟以前的版本一样可以在蓝图里访问到TS 里的属性？
![ee91e5de6d9715c9061fe3c7eecef77](https://github.com/user-attachments/assets/f87514a2-9e27-405e-a673-ec768ea036a5)

**Comment by morirain** [comment]
合入这个commit:
50414f97bf8f0042e653085a54f8965f3a8d0ccd

**Comment by morirain** [comment]
合入就没问题了，还看不见变量的要刷新一下文件
