### ISSUE TITLE
[Unreal 4.26]绑定的Action Mappings无法在TypeScript中被调用

### ISSUE THREAD

**Issue by sdspageprotein** [Tencent/puerts#186]
绑定的Action Mappings无法在TypeScript中被调用，Axis ``Mappings是可以的。跟踪C++代码发现在`UPEBlueprintAsset::AddFunction`中只处理了UK2Node_InputAxisEvent，好像没处理UK2Node_InputActionEvent？

**Comment by chexiongsheng** [comment]
是的，只处理了axis

**Comment by chexiongsheng** [comment]
你可以帮忙加下啊，提个PR过来
