### ISSUE TITLE
[Unity]/[UE] question 为什么PushUInt64要把ulong类型的值转成long呢

### ISSUE THREAD

**Issue by IHACOU** [Tencent/puerts#1862]
## detail | 详细描述
在C#中定义一个UInt64位的数，大小等于Int64_MAX+1，读取到ts中会变成有符号的负数
StaticTranslate.cs中PushUInt64将ulong类型的值转成了long，为什么要这样做呢？

**Comment by chexiongsheng** [comment]
虽然bigint能容纳ulong，但我不想再增加plugin接口。
信息没丢就行，lua5.3的整数支持也只是int64，xlua也是这么转。

**Comment by IHACOU** [comment]
收到，感谢
