### ISSUE TITLE
[UE] Bug: DataTable遍历崩溃

### ISSUE THREAD

**Issue by kimxee** [Tencent/puerts#1864]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

puerts_v8_94

### UE的版本 | UE Version

5.4.4

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

LoginId:c1e7b8594a43cfd73fefc48d4b0e05e6
EpicAccountId:cb029eaa86424cdf9151cea6a554b47b

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000001a786b

v8
UnrealEditor_JsEnv!puerts::FStringPropertyTranslator::UEToJs() [F:\Unreal\aaa\Plugins\Puerts\Source\JsEnv\Private\PropertyTranslator.cpp:376]
UnrealEditor_JsEnv!puerts::FScriptArrayWrapper::Get() [F:\Unreal\aaa\Plugins\Puerts\Source\JsEnv\Private\ContainerWrapper.cpp:95]
v8
v8
v8
v8
v8
v8
v8
v8
v8
v8
v8
v8
UnrealEditor_JsEnv!puerts::FFunctionTranslator::CallJs() [F:\Unreal\aaa\Plugins\Puerts\Source\JsEnv\Private\FunctionTranslator.cpp:460]
UnrealEditor_JsEnv!puerts::FJsEnvImpl::InvokeDelegateCallback() [F:\Unreal\aaa\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp:1937]
UnrealEditor_JsEnv!UDynamicDelegateProxy::ProcessEvent() [F:\Unreal\aaa\Plugins\Puerts\Source\JsEnv\Private\DynamicDelegateProxy.cpp:26]
UnrealEditor_LDemo!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:917]
UnrealEditor_LDemo!FNotifyWithCharacter_DelegateWrapper() [F:\Unreal\aaa\Intermediate\Build\Win64\UnrealEditor\Inc\LDemo\UHT\LDemoCharacter.gen.cpp:67]
UnrealEditor_LDemo!TBaseUObjectMethodDelegateInstance<0,ALDemoCharacter,void __cdecl(FInputActionValue const &),FDefaultDelegateUserPolicy>::Execute() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:650]
UnrealEditor_LDemo!FEnhancedInputActionEventDelegateBinding<TDelegate<void __cdecl(FInputActionValue const &),FDefaultDelegateUserPolicy> >::Execute() [E:\UE\UnrealEngine-5.4.4-release\Engine\Plugins\EnhancedInput\Source\EnhancedInput\Public\EnhancedInputComponent.h:309]
UnrealEditor_EnhancedInput!UEnhancedPlayerInput::EvaluateInputDelegates() [E:\UE\UnrealEngine-5.4.4-release\Engine\Plugins\EnhancedInput\Source\EnhancedInput\Private\EnhancedPlayerInput.cpp:603]
UnrealEditor_Engine!UPlayerInput::ProcessInputStack() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\UserInterface\PlayerInput.cpp:1149]
UnrealEditor_Engine!APlayerController::ProcessPlayerInput() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:2738]
UnrealEditor_Engine!APlayerController::TickPlayerInput() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:5035]
UnrealEditor_Engine!APlayerController::PlayerTick() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:2342]
UnrealEditor_Engine!APlayerController::TickActor() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:5194]
UnrealEditor_Engine!FActorTickFunction::ExecuteTick() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\Actor.cpp:238]
UnrealEditor_Engine!FTickFunctionTask::DoTask() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:278]
UnrealEditor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1235]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksNamedThread() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:760]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:651]
UnrealEditor_Core!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:2122]
UnrealEditor_Engine!FTickTaskSequencer::ReleaseTickGroup() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:556]
UnrealEditor_Engine!FTickTaskManager::RunTickGroup() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:1583]
UnrealEditor_Engine!UWorld::RunTickGroup() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:772]
UnrealEditor_Engine!UWorld::Tick() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1499]
UnrealEditor_UnrealEd!UEditorEngine::Tick() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:2015]
UnrealEditor_UnrealEd!UUnrealEdEngine::Tick() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:550]
UnrealEditor!FEngineLoop::Tick() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5921]
UnrealEditor!GuardedMain() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Launch\Private\Launch.cpp:180]
UnrealEditor!GuardedMainWrapper() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
UnrealEditor!LaunchWindowsStartup() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
UnrealEditor!WinMain() [E:\UE\UnrealEngine-5.4.4-release\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

### 问题重现 | Bug reproduce

```
let TestTable= UE.DataTable.Load("/Game/DataTables/TestTable");
let testKeys = UE.NewArray(UE.BuiltinString); 
        UE.DataTableFunctionLibrary.GetDataTableRowNames(TestTable,$ref(testKeys ));
        console.warn("testKeys .Num():" + testKeys .Num());
        for(var j=0; j < testKeys .Num(); j++) {
            console.log(j, ":", testKeys.Get(j));//执行Get出现崩溃
        }
```

**Comment by chexiongsheng** [comment]
你这么写参考的哪里？

**Comment by kimxee** [comment]
> 你这么写参考的哪里？

抱歉抱歉，实在是不知道怎么写

**Comment by chexiongsheng** [comment]
TArray<FName>你为啥用BuiltinString？不是有BuiltinName吗？
甚至留空也行
```
let rn = $ref<UE.TArray<string>>();
UE.DataTableFunctionLibrary.GetDataTableRowNames(testTable, rn);
```
