### ISSUE TITLE
[UE] Bug: Class which was marked abstract was trying to be loaded in Outer /Engine/Transient.  It will be nulled out on save. None Object

### ISSUE THREAD

**Issue by yxd7822544** [Tencent/puerts#1876]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### UE的版本 | UE Version

5.44

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

引擎警告:Class which was marked abstract was trying to be loaded in Outer /Engine/Transient.  It will be nulled out on save. None Object

### 问题重现 | Bug reproduce

1.继承uobject
import * as UE from 'ue';

class TS_ListViewItemData extends UE.Object
{
     public ItemName : string; 

}

export default TS_ListViewItemData

2.  new TS_ListViewItemData();时就会发生上面的报错，使用蓝图就不会出现此问题

**Comment by chexiongsheng** [comment]
继承ue类的ts，本质上是蓝图，只不过把函数重定向到js。
所以用其生成的蓝图类来构造。
