### ISSUE TITLE
[UE] Bug: 从c++获取到的uobject ，赋值到ts类成员变量，ts变量有被gc可能。

### ISSUE THREAD

**Issue by pheyahu** [Tencent/puerts#1890]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master

### UE的版本 | UE Version

5.4.2

### 发生在哪个平台 | Platform

Editor(win)

### 问题重现 | Bug reproduce

不是继承
ts: 
class xxx
private _component:UE.ActorComponent;
init(actor:UE.Actor):void
{
           this._component = actor.GetComponent();

}

tick()
{
         this._component.DoSomething();
}

有一定几率出现this._component invalid  是不是开启宏WITH_OUTER_LINK可以解决这种问题？ 如果不开启宏有没有更好的写法，还是每次tick都要从actor里获取component处理？

**Comment by pheyahu** [comment]
补充下 是v8

**Comment by BlurryLight** [comment]
Actor / ActorComponent失效 不等于 UObject失效。
Actor 的失效形式包括 world partition 流送卸载 / 切换地图 / 逻辑主动调用了destroy Actor 等很多种情况。

**Comment by pheyahu** [comment]
并没有切换场景等操作，就挂在同一个场景中，也不是c++层的uobject失效，在c++层这个component和actor还是存在的。是ts层的_component 失效了。

**Comment by chexiongsheng** [comment]
WITH_OUTER_LINK不能是用来解决你说的问题，它使用场景是gc管理之外的对象，比如ustruct。如果是uobject，报invalid了就必然是被释放了，可能是没引用，也可能是@BlurryLight 提到的各自情况。
另外，并不是js持有的必定是强引用，faq有相关条目：https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md#gc%E7%9B%B8%E5%85%B3

**Comment by pheyahu** [comment]
我在c++的actortick打印component，component是没有被释放的，ts层重新获取component是可以获取到的，但是之前在init里获取的已经失效了，至于@BlurryLight提及的情况确认是没有出现的。是不是js的stub已经被释放了？提示：
js callback exception  ： Error: access a invalid object

**Comment by chexiongsheng** [comment]
this._component.DoSomething()报错，可能是this无效，也可能是_component无效。你可以通过let tmp = this._component访问下。
报access a invalid object就是被访问的对象释放了。你认真理解下这个话的含义。从你问“js的stub已经被释放了？”这点来看，你没理解。

**Comment by pheyahu** [comment]
this是没释放的。我上边提到的在tick里获取component是没问题的，但是在init里获取到的是失效的，
tick（actor:UE.Actor）
｛
if （this._component)
{
//这里还是能进入的
}
 actor.GetComponent().DoSomething();//正确
this._component.DoSomething();//invalid

｝像这种直接从ue中获取的对象是“stub对象由js gc管理“吧？那对象还是被js引用住的，怎么被gc了呢？

**Comment by chexiongsheng** [comment]
说直白点，出现访问一个对象access a invalid object，只有一种情况：UE通过NotifyUObjectDeleted通知这个对象删除了，这回调什么情况调用可以查下ue文档。这块逻辑很简单，而且好几年处理逻辑没变过，那么多项目也没反馈过这块和预期不一致的。
1、拷贝局部代码一般意义不大，谁知道你其它地方有没做其它处理；
2、c++项目还有个问题是unsafe，可能出现越界之类的情况整出些奇怪现象。

**Comment by pheyahu** [comment]
好的，我跟踪下。感谢车神回答。
