### ISSUE TITLE
[Unity] Bug: xil2cpp如果struct没有配到binding, delegate 的方法不会生成

### ISSUE THREAD

**Issue by dunadain** [Tencent/puerts#1896]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.1.0

### Unity的版本 | Unity Version

2022.3.47f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

![8d2d649a250909cc2fe04d5fe3e656f6](https://github.com/user-attachments/assets/810ae61c-9fae-4889-aef5-dbe8990717e7)

### 问题重现 | Bug reproduce

![813ded341bda0010d4d995b09b6556eb](https://github.com/user-attachments/assets/28ef099b-027e-4caa-9147-f412927cf7ef)

**Comment by chexiongsheng** [comment]
其实搜索到AsyncOperationHandle<List<string>>了，但没进一步去看它的函数有没delegate

**Comment by chexiongsheng** [comment]
我的测试工程原来生成200+个delegate bridge，在这个修改后变成了1000+，可能后续还让用户指定对哪些delegate生成。
