### ISSUE TITLE
[unreal] 一个crash，不是很确定是不是puerts的问题。

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#190]
UE4Editor-JsEnv.dll!v8::internal::GlobalHandles::IterateYoungStrongAndDependentRoots(class v8::internal::RootVisitor *)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Heap::IterateStrongRoots(class v8::internal::RootVisitor *,enum v8::internal::VisitMode)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Heap::IterateRoots(class v8::internal::RootVisitor *,enum v8::internal::VisitMode)	C++
 	UE4Editor-JsEnv.dll!v8::internal::ScavengerCollector::CollectGarbage(void)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Heap::Scavenge(void)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Heap::PerformGarbageCollection(enum v8::internal::GarbageCollector,enum v8::GCCallbackFlags)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Heap::AllocateRawWithRetryOrFail(int,enum v8::internal::AllocationType,enum v8::internal::AllocationAlignment)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Factory::CopyJSObjectWithAllocationSite(class v8::internal::Handle<class v8::internal::JSObject>,class v8::internal::Handle<class v8::internal::AllocationSite>)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Factory::CopyJSObject(class v8::internal::Handle<class v8::internal::JSObject>)	C++
 	UE4Editor-JsEnv.dll!v8::internal::ApiNatives::InstantiateFunction(class v8::internal::Handle<class v8::internal::FunctionTemplateInfo>,class v8::internal::MaybeHandle<class v8::internal::Name>)	C++
 	UE4Editor-JsEnv.dll!v8::internal::ApiNatives::InstantiateObject(class v8::internal::Isolate *,class v8::internal::Handle<class v8::internal::ObjectTemplateInfo>,class v8::internal::Handle<class v8::internal::JSReceiver>)	C++
 	UE4Editor-JsEnv.dll!v8::internal::CustomArguments<class v8::FunctionCallbackInfo<class v8::Value> >::GetReturnValue<class v8::internal::Object>(class v8::internal::Isolate *)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Builtins::InvokeApiFunction(class v8::internal::Isolate *,bool,class v8::internal::Handle<class v8::internal::HeapObject>,class v8::internal::Handle<class v8::internal::Object>,int,class v8::internal::Handle<class v8::internal::Object> * const,class v8::internal::Handle<class v8::internal::HeapObject>)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Execution::CallWasm(class v8::internal::Isolate *,class v8::internal::Handle<class v8::internal::Code>,unsigned __int64,class v8::internal::Handle<class v8::internal::Object>,unsigned __int64)	C++
 	UE4Editor-JsEnv.dll!v8::internal::Execution::New(class v8::internal::Isolate *,class v8::internal::Handle<class v8::internal::Object>,class v8::internal::Handle<class v8::internal::Object>,int,class v8::internal::Handle<class v8::internal::Object> * const)	C++
 	UE4Editor-JsEnv.dll!v8::Function::NewInstanceWithSideEffectType(class v8::Local<class v8::Context>,int,class v8::Local<class v8::Value> * const,enum v8::SideEffectType)	C++
 	UE4Editor-JsEnv.dll!v8::Function::NewInstance(class v8::Local<class v8::Context>,int,class v8::Local<class v8::Value> * const)	C++
>	UE4Editor-JsEnv.dll!puerts::FJsEnvImpl::FindOrAddStruct(v8::Isolate * Isolate, v8::Local<v8::Context> & Context, UScriptStruct * ScriptStruct, void * Ptr, bool PassByPointer) 行 1320	C++
 	UE4Editor-JsEnv.dll!puerts::FScriptStructPropertyTranslator::UEToJs(v8::Isolate * Isolate, v8::Local<v8::Context> & Context, const void * ValuePtr, bool PassByPointer) 行 442	C++
 	[内联框架] UE4Editor-JsEnv.dll!puerts::FPropertyTranslator::UEToJsInContainer(v8::Isolate *) 行 30	C++
 	UE4Editor-JsEnv.dll!puerts::FFunctionTranslator::Call(v8::Isolate * Isolate, v8::Local<v8::Context> & Context, const v8::FunctionCallbackInfo<v8::Value> & Info) 行 126	C++
 	UE4Editor-JsEnv.dll!puerts::FFunctionTranslator::Call(const v8::FunctionCallbackInfo<v8::Value> & Info) 行 89	C++
 	[外部代码]	
 	UE4Editor-JsEnv.dll!puerts::FFunctionTranslator::CallJs(v8::Isolate * Isolate, v8::Local<v8::Context> & Context, v8::Local<v8::Function> JsFunction, v8::Local<v8::Value> This, void * Params) 行 178	C++
 	UE4Editor-JsEnv.dll!puerts::FJsEnvImpl::InvokeJsCallabck(UDynamicDelegateProxy * Proxy, void * Parms) 行 1422	C++
 	UE4Editor-JsEnv.dll!UDynamicDelegateProxy::ProcessEvent(UFunction * __formal, void * Parms) 行 20	C++
 	[内联框架] UE4Editor-View.dll!FViewFrameTick_DelegateWrapper(const TScriptDelegate<FWeakObjectPtr> &) 行 30	C++
 	[内联框架] UE4Editor-View.dll!FViewFrameTick::ExecuteIfBound(const float) 行 30	C++
 	UE4Editor-View.dll!UvGameInstance::TimeTick(float delta) 行 89	C++
 	UE4Editor-Engine.dll!AActor::TickActor(float DeltaSeconds, ELevelTick TickType, FActorTickFunction & ThisTickFunction) 行 1093	C++
 	UE4Editor-Engine.dll!FActorTickFunction::ExecuteTick(float DeltaTime, ELevelTick TickType, ENamedThreads::Type CurrentThread, const TRefCountPtr<FGraphEvent> & MyCompletionGraphEvent) 行 173	C++
 	UE4Editor-Engine.dll!FTickFunctionTask::DoTask(ENamedThreads::Type CurrentThread, const TRefCountPtr<FGraphEvent> & MyCompletionGraphEvent) 行 284	C++
 	UE4Editor-Engine.dll!TGraphTask<FTickFunctionTask>::ExecuteTask(TArray<FBaseGraphTask *,TSizedDefaultAllocator<32>> & NewTasks, ENamedThreads::Type CurrentThread) 行 886	C++
 	[内联框架] UE4Editor-Core.dll!FBaseGraphTask::Execute(TArray<FBaseGraphTask *,TSizedDefaultAllocator<32>> & CurrentThread, ENamedThreads::Type) 行 524	C++
 	UE4Editor-Core.dll!FNamedTaskThread::ProcessTasksNamedThread(int QueueIndex, bool bAllowStall) 行 709	C++
 	UE4Editor-Core.dll!FNamedTaskThread::ProcessTasksUntilQuit(int QueueIndex) 行 601	C++
 	[内联框架] UE4Editor-Core.dll!FTaskGraphImplementation::ProcessThreadUntilRequestReturn(ENamedThreads::Type CurrentThread) 行 1473	C++
 	UE4Editor-Core.dll!FTaskGraphImplementation::WaitUntilTasksComplete(const TArray<TRefCountPtr<FGraphEvent>,TInlineAllocator<4,TSizedDefaultAllocator<32>>> & Tasks, ENamedThreads::Type CurrentThreadIfKnown) 行 1525	C++
 	UE4Editor-Engine.dll!FTickTaskSequencer::ReleaseTickGroup(ETickingGroup WorldTickGroup, bool bBlockTillComplete) 行 564	C++
 	UE4Editor-Engine.dll!FTickTaskManager::RunTickGroup(ETickingGroup Group, bool bBlockTillComplete) 行 1578	C++
 	UE4Editor-Engine.dll!UWorld::RunTickGroup(ETickingGroup Group, bool bBlockTillComplete) 行 782	C++
 	UE4Editor-Engine.dll!UWorld::Tick(ELevelTick TickType, float DeltaSeconds) 行 1457	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::Tick(float DeltaSeconds, bool bIdleMode) 行 1720	C++
 	UE4Editor-UnrealEd.dll!UUnrealEdEngine::Tick(float DeltaSeconds, bool bIdleMode) 行 426	C++
 	UE4Editor.exe!FEngineLoop::Tick() 行 4834	C++
 	[内联框架] UE4Editor.exe!EngineTick() 行 62	C++
 	UE4Editor.exe!GuardedMain(const wchar_t * CmdLine) 行 169	C++
 	UE4Editor.exe!WinMain(HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) 行 257	C++

**Comment by mingxxming** [comment]
项目原生代码bug导致的

**Comment by chexiongsheng** [comment]
那也分享下这个bug是咋的？后面的人可以避免犯同样的错误

**Comment by mingxxming** [comment]
目前还没想明白原因。但是这不仅导致上面crash，还概率性产出 引擎代码crash的堆栈
struct C_AIPlanner {
	actionplanner_t ap;
	worldstate_t state;
	entt::entity actions[MAXACTIONS];
};
struct C_AIAction {
	int index;
	ActionSate state;
	RunActionCallback callback;
	actionplanner_t* ap;
	void* userData;
};
C_AIAction 的ap原本计划是记录C_AIPlanner ap的地址。

**Comment by chexiongsheng** [comment]
概率出现不同的crash，往往是踩内存导致的。
单单定义这个结构体应该不会有问题。可能是结构体的使用中有那里越界了，或者操作了野指针。

**Comment by mingxxming** [comment]
不是定义时候出现的，是获取 action 内的ap。对ap的属性读写出现的。像是ap记录的这个地址，早已经被释放并且被其他系统使用了。所以访问到的已经不是actionplanner_t 那么就做地址偏移读出的数据完全错误，可能越界可能未分配
