### ISSUE TITLE
[UE] Bug: 在QuickJs下，构造SoftClassPtr/SoftObjectPtr崩溃

### ISSUE THREAD

**Issue by rhm0325** [Tencent/puerts#1907]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.6

### UE的版本 | UE Version

All

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

![屏幕截图 2024-11-12 001111](https://github.com/user-attachments/assets/18f7eb3b-0e4c-47a3-a500-e9bc47916327)
![image](https://github.com/user-attachments/assets/c424e598-e4c1-4ce5-aa96-c50a40ec37cb)

在v8下正常，QuickJs下崩溃

### 问题重现 | Bug reproduce

在QuickJs下构造SoftClassPtr

**Comment by chexiongsheng** [comment]
quickjs-backend的一个bug导致：https://github.com/puerts/backend-quickjs/commit/e540ffaa68ad2b8e38a845dc3274631f06c3ebee
可以更新下quickjs-backend解决。
不过我也在puerts这规避下。
