### ISSUE TITLE
[Unity] 未来会支持 WebGL 吗 ？

### ISSUE THREAD

**Issue by liangxieq** [Tencent/puerts#192]
如题

**Comment by chexiongsheng** [comment]
如果是quickjs版本，由于纯c写的解析器，和lua类似，要支持webgl还是比较简单的。像xlua这样搞个文件，include一下quickjs的代码即可：https://github.com/Tencent/xLua/blob/master/Assets/Plugins/WebGL/xlua_webgl.cpp
但这比较奇怪，用wasm跑一个js虚拟机来跑js，但问题是webgl环境本来是js环境。
我觉得要做这事情，最好能unity合作去做这事情。

**Comment by liangxieq** [comment]
好，感谢回答，我这边的需求是这样的，我的游戏由于前期需要和玩家和团队做频繁的早期测试，所以用 WebGL 的方式发布是最快的方式，玩家不用直接安装客户端就能体验到，然后给反馈，这样对游戏迭代本身有很大的好处。

然后我这边的技术栈如果是用 TypeScript 会多很多个帮手，如果用  lua 的话 可能就会少一些帮手，而且 TypeScript 有类型检查，目前支持 WebGL 的脚本方案有 xLua 和 MoonSharp，目前在用 MoonSharp，测试了下 xLua 和 MoonSharp，xLua 哪方面都好，就是放在工程里会影响编译速度，而 Puerts 和 MoonSharp 都不错，如果 Puerts 支持的话 肯定用 Puerts，MoonSharp 目前是妥协方案，如果一直用未来肯定要切换到 xLua 上的，当然这样也会造成很多工作量。

然后我的游戏未来要加上 Mod 支持，如果做 Mod 支持，用 JavaScript/TypeScript 的基数会比 Lua 多很多。

所以如果可以的话帮忙支持一下 WebGL 平台，🙏。

**Comment by chexiongsheng** [comment]
xLua影响编译速度？是编译webgl版本么？

**Comment by liangxieq** [comment]
不是的，是 xLua 放在 Unity 工程里，然后修改一下脚本要编译一段时间。

**Comment by chexiongsheng** [comment]
不会吧，你是不是生成了很多代码？xlua也是不用生成代码就可以用的。

**Comment by chexiongsheng** [comment]
看下XLua\Gen目录，如果有很多代码 ，就删了。
生成wrap代码建议只生成你需要调用的那些类。

**Comment by liangxieq** [comment]
嗯嗯 晓得了 可能是我工程里插件太多了。

**Comment by liangxieq** [comment]
![image](https://user-images.githubusercontent.com/24365011/112479065-9f84b600-8daf-11eb-8906-f770e2db701e.png)

然后我的 Mac 上用 Puerts 有这个问题。

**Comment by chexiongsheng** [comment]
程序没签名导致的的，你先按faq操作下：https://github.com/Tencent/puerts/blob/master/doc/unity/faq.md#maos1015%E4%BB%A5%E4%B8%8A%E5%90%AF%E5%8A%A8unity%E7%9A%84%E6%97%B6%E5%80%99%E6%8F%90%E7%A4%BApuertsbundle%E6%8D%9F%E5%9D%8F%E7%A7%BB%E5%8A%A8%E5%88%B0%E5%BA%9F%E7%BA%B8%E7%AF%93
如果还不行，要自己在自己机器上编译才行。

**Comment by liangxieq** [comment]
好的 谢谢

**Comment by liangxieq** [comment]
修好了 不好意思 没读 faq

**Comment by liangxieq** [comment]
我试了下导出 WebGL 的方法，打包 WebGL 的时候会报下边的错误：
![image](https://user-images.githubusercontent.com/24365011/112484622-107a9c80-8db5-11eb-909a-9a2af32478e2.png)

我的 puerts_webgl.cpp 如下:

``` cpp
extern "C" {
#include "../../../WebGLPlugins/cutils.c"
#include "../../../WebGLPlugins/libbf.c"
#include "../../../WebGLPlugins/libregexp.c"
#include "../../../WebGLPlugins/libunicode.c"
#include "../../../WebGLPlugins/quickjs.c"
}
```

然后把 quickjs 代码房贷  WebGLPlugins 里了，如下：

![image](https://user-images.githubusercontent.com/24365011/112484838-41f36800-8db5-11eb-952c-a9d11ae8a97d.png)


初步尝试没走通。帮忙看下是不是我没放对？还是因为啥？

**Comment by chexiongsheng** [comment]
可能是quickjs写得兼容性没那么好吧，在CMake这编译要加些参数才能编：https://github.com/Tencent/puerts/blob/master/quickjs-build/CMakeLists.txt#L10

**Comment by liangxieq** [comment]
好的 感谢。
