### ISSUE TITLE
[Unity] 含system.intptr参数的函数没有被生成 

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1923]
被标记为 DontBinding 
实测执行是没问题的

**Comment by chexiongsheng** [comment]
你什么场景下需要传intptr呢？

什么类型不支持，怎么支持我有我的考量。

如果你碰到实际的问题，可以基于这个实际问题来看怎么改合适，别没头没尾的提个修改建议，像这个，连没上下文，没分析：https://github.com/Tencent/puerts/issues/1913

**Comment by mingxxming** [comment]
我有很多基于c++的接口，ts保留了指针，调用接口的时候会把指针传递到c#

**Comment by chexiongsheng** [comment]
不是一直都不支持IntPtr吗，都没相应的类型映射。
是你自己加的吗？

**Comment by mingxxming** [comment]
我看diff 生成代码确实没变，但之前是有生成出来，我并没有修改任何代码。

**Comment by mingxxming** [comment]
确实是后面加的， 我之前的版本是[2.1.0] - 2024-06-25，FilterBigStructAndPointerOfPointer 这个函数为新增

**Comment by chexiongsheng** [comment]
il2cpp版本加的，你可以临时去掉看看。

**Comment by chexiongsheng** [comment]
只去掉IntPtr的限制

**Comment by chexiongsheng** [comment]
另外，你可以参考下我觉得很优秀的issue提法：https://github.com/Tencent/puerts/issues/1924，清楚的描述碰到的问题
你这种先自己分析了下，然后**仅仅**用分析结果而不附带原问题的提问题的方式不利于问题的解决，可以看下这篇文章：https://coolshell.cn/articles/10804.html

**Comment by mingxxming** [comment]
> 只去掉IntPtr的限制

去掉限制没问题

**Comment by chexiongsheng** [comment]
你们之前是怎么传IntPtr？结构体？

**Comment by chexiongsheng** [comment]
普通版本目前是按结构体处理了。

**Comment by chexiongsheng** [comment]
按普通结构体处理，也是挺大开销的，这种情况感觉用反射或者wrapper区别不大

**Comment by mingxxming** [comment]
> 你们之前是怎么传IntPtr？结构体？

之前并没有进行任何处理，是正确执行的，但是没有测过32位。性能没太关注，因为没有高频调用。
