### ISSUE TITLE
[UE] Bug: 打包 IOS 后首次打开有概率闪退

### ISSUE THREAD

**Issue by lovelypeople** [Tencent/puerts#1936]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.7

### UE的版本 | UE Version

5.4.4

### 发生在哪个平台 | Platform

iOS

### 错误信息 | Error Message

5.4.4 + 1.0.7 v8_94 打包发布到 TestFlight 后安装5～10次会必然出现1次闪退
空工程测试的崩溃如图所示：
![p1](https://github.com/user-attachments/assets/11f44a22-147b-4398-8aae-000308f2d13a)
游戏的崩溃如图所示：
![p2](https://github.com/user-attachments/assets/9dafb082-42a7-4b55-a347-73b55ce001a5)
查看 issues 发现该错误比较像 #1593 里的，尝试如图的方式禁用掉 new/delete 重载(不确定禁用重载是不是这么做）还是会闪退在同样的地方
![p3](https://github.com/user-attachments/assets/c2a7ca80-b9d9-4838-8f15-8b25731b4c69)

### 问题重现 | Bug reproduce

1.5.4.4 下新建一个空工程
2.接入 1.0.7 v8_94 的 puerts，改下 ThirdParty/v8_9.4.146.24 为 ThirdParty/v8 让它能编译不报错
3.打包 iOS 并发布到 TestFlight，从 TestFlight 上安装10次，10次以内可以必现上述崩溃

**Comment by zhaojunmeng** [comment]
试试在iOS下面，换不同的内存分配器，还会崩溃在这里吗？比如使用Binned1的内存分配器。

**Comment by chexiongsheng** [comment]
可以试试切换内存分配器，ansi最稳，5.4用Binned1应该也没问题。
如果是Binned3，官方已经承认是有bug的。你c++有用到std::string都有可能触发，如果你可以修改引擎，可以参考Binned1去修复。
另外，我们也在搞一个v8的版本来规避这个bug。

**Comment by chexiongsheng** [comment]
附上Binned1的这个bug修复的关键代码：
![5ae13da0a28c3f00e0e1f9b46d3da437](https://github.com/user-attachments/assets/b0bf9e69-c58f-48b7-a714-d808cf41235a)

**Comment by lovelypeople** [comment]
> 可以试试切换内存分配器，ansi最稳，5.4用Binned1应该也没问题。 如果是Binned3，已经和官方确认是有bug的。你c++有用到std::string都有可能触发，如果你可以修改引擎，可以参考Binned1去修复。 另外，我们也在搞一个v8的版本来规避这个bug。

尝试不编译引擎在 project.target.cs 和 projecteditor.target.cs 中加上 
bOverrideBuildEnvironment = true;
GlobalDefinitions.Add("FORCE_ANSI_ALLOCATOR=1");
来使用 ansi，崩溃的位置看上去似乎差不多
![p4](https://github.com/user-attachments/assets/db8b44f1-cd44-484a-82ee-d61b9a546547)
Binned1 和图示的思路似乎得改源码才能试了，我再试下

**Comment by chexiongsheng** [comment]
> > 可以试试切换内存分配器，ansi最稳，5.4用Binned1应该也没问题。 如果是Binned3，已经和官方确认是有bug的。你c++有用到std::string都有可能触发，如果你可以修改引擎，可以参考Binned1去修复。 另外，我们也在搞一个v8的版本来规避这个bug。
> 
> 尝试不编译引擎在 project.target.cs 和 projecteditor.target.cs 中加上 bOverrideBuildEnvironment = true; GlobalDefinitions.Add("FORCE_ANSI_ALLOCATOR=1"); 来使用 ansi，崩溃的位置看上去似乎差不多 ![p4](https://private-user-images.githubusercontent.com/3139983/392357317-db8b44f1-cd44-484a-82ee-d61b9a546547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjYyODMsIm5iZiI6MTczMzM2NTk4MywicGF0aCI6Ii8zMTM5OTgzLzM5MjM1NzMxNy1kYjhiNDRmMS1jZDQ0LTQ4NGEtODJlZS1kNjFiOWE1NDY1NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDIzMzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQxN2YyM2Q2YmIyZWZlOWIyMjlkMjNiNGU1N2I0ZjBiNDgzOGFmMTZkNTk1Y2Y5YjBiZTJlZTg2MTBjNjZjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bgaiSksFIS1IoL4VxjwdpYEepgiTQB-dHBOpBGQdLFw) Binned1 和图示的思路似乎得改源码才能试了，我再试下

如果确实切换到ansi，应该问题也能解决的。

**Comment by lovelypeople** [comment]
> 你试试换这个版本的v8：https://github.com/puerts/backend-v8/releases/tag/V8_11.8.172_with_new_wrap_241205 解压到[ThirdParty](https://github.com/Tencent/puerts/tree/master/unreal/Puerts/ThirdParty)后[JsEnv.Build.cs这里](https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/JsEnv.Build.cs#L26)改成V11_8_172
> 
> 不用修改引擎。

应该可以了！我手上的设备测试没有再出现崩溃了，感谢！

方法：
用目前 Master 下的 JSEnv 文件夹覆盖 release 1.0.7 的 JSEnv（否则会有 link 错误），然后按照指引配置打包即可

**Comment by lovelypeople** [comment]
@chexiongsheng 在 Android 上用11似乎是有编译错误的
[errorlog.txt](https://github.com/user-attachments/files/18046098/errorlog.txt)
![errorlog](https://github.com/user-attachments/assets/da0f37ca-bfbf-497f-9271-3102e17507e4)

**Comment by chexiongsheng** [comment]
在linux（可以通过window的wsl安装个Ubuntu）下到v8_11.8.172\Lib\Android\arm64-v8a（其他架构类似）
```
llvm-objcopy \
  --redefine-sym=_ZNSt11logic_errorC2EPKc=___ZNSt11logic_errorC2EPKc \
  --redefine-sym=_ZNSt11logic_errorC2ERKS_=___ZNSt11logic_errorC2ERKS_ \
  --redefine-sym=_ZNSt13runtime_errorC2EPKc=___ZNSt13runtime_errorC2EPKc \
  --redefine-sym=_ZNSt13runtime_errorC2ERKS_=___ZNSt13runtime_errorC2ERKS_ \
  --redefine-sym=_ZNSt11logic_erroraSERKS_=___ZNSt11logic_erroraSERKS_ \
  --redefine-sym=_ZNSt13runtime_erroraSERKS_=___ZNSt13runtime_erroraSERKS_ \
  libwee8.a
```
如果碰到其它符号重复你就同样的改下名。报错的(.text._ZNSt11logic_errorC2EPKc)里的_ZNSt11logic_errorC2EPKc就是要改的符号，你新符号前面加两个下划线即可。
全部改对后，你发下要改的符号，我统一加到v8构建脚本。

llvm-objcopy没有就安装个llvm：`sudo apt install llvm`

**Comment by lovelypeople** [comment]
我用 mac 上的 llvm 执行了以下的命令，但是有4个符号还是有问题
![duplicate_symbols](https://github.com/user-attachments/assets/e52eea8f-dd11-49c9-b8ca-0f5fe752ba6f)

命令是：
llvm-objcopy \
  --redefine-sym=_ZTVSt16nested_exception=___ZTVSt16nested_exception \
  --redefine-sym=_ZTISt16nested_exception=___ZTISt16nested_exception \
  --redefine-sym=_ZTSSt16nested_exception=___ZTSSt16nested_exception \
  --redefine-sym=_ZNSt11logic_errorC2EPKc=___ZNSt11logic_errorC2EPKc \
  --redefine-sym=_ZNSt11logic_errorC2ERKS_=___ZNSt11logic_errorC2ERKS_ \
  --redefine-sym=_ZNSt11logic_erroraSERKS_=___ZNSt11logic_erroraSERKS_ \
  --redefine-sym=_ZNSt13runtime_errorC2EPKc=___ZNSt13runtime_errorC2EPKc \
  --redefine-sym=_ZNSt13runtime_errorC2ERKS_=___ZNSt13runtime_errorC2ERKS_ \
  --redefine-sym=_ZNSt13runtime_erroraSERKS_=___ZNSt13runtime_erroraSERKS_ \
  libwee8.a

llvm 是在 [clang+llvm-18.1.8-arm64-apple-macos11.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-arm64-apple-macos11.tar.xz) 这里下载的

**Comment by chexiongsheng** [comment]
更改后的符号还冲突？
你再改下，改成其它的？只是内部使用，随便都可以，不冲突就行。

**Comment by lovelypeople** [comment]
> 更改后的符号还冲突？ 你再改下，改成其它的？只是内部使用，随便都可以，不一定只能加下划线，不冲突就行。

是的，除了这4个之外的其他的符号都可以解决，这4个比如我改成 ___puerts_wrap 依然不行
![wrapissue](https://github.com/user-attachments/assets/ae43ac90-d181-4b99-ad48-c137ae0cdcbc)

**Comment by chexiongsheng** [comment]
我看名字都不一样了，有没可能是编译缓存导致的？

**Comment by lovelypeople** [comment]
> 符号名字都不一样了，有没可能是编译缓存导致的？

试了 full rebuild + 手动删掉 Binaries、Intermediate 错误是一样的，它报错的符号名字是 redefine 后的，比如加两个下划线，报错的重复的就是加两个下划线后的
![issue2](https://github.com/user-attachments/assets/50ddb574-d06c-49f6-8858-5716cb221e35)

**Comment by chexiongsheng** [comment]
比较奇怪，我本地搞了下也是同样的报错，目前也没啥头绪。
不过你可以暂时在android下用标准版本的v8 11.8.172：https://github.com/puerts/backend-v8/releases/tag/V8_11.8.172__241009
android的下据说没那么容易出现这个问题。有项目测试ios下程序第一次和第二次启动重载是不一样的。

**Comment by chexiongsheng** [comment]
看报错android用的是静态库的libc++，应该没那重载问题了，android直接用这个的：https://github.com/puerts/backend-v8/releases/tag/V8_11.8.172__241009，然后ios用这个的：https://github.com/puerts/backend-v8/releases/tag/V8_11.8.172_with_new_wrap_241205

**Comment by lovelypeople** [comment]
> 看报错android用的是静态库的libc++，应该没那重载问题了，android直接用这个的：https://github.com/puerts/backend-v8/releases/tag/V8_11.8.172__241009 ，然后ios用这个的：https://github.com/puerts/backend-v8/releases/tag/V8_11.8.172_with_new_wrap_241205

好的

**Comment by hanbim520** [comment]
https://zhuanlan.zhihu.com/p/1889829631009485501 标准答案在这里，这个问题可以关闭了
