### ISSUE TITLE
[unity] 多线程中创建多个JsEnv实例, 一段时间后主线程调用C# api异常

### ISSUE THREAD

**Issue by layerpsr** [Tencent/puerts#195]
附Demo: https://github.com/layerpsr/puerts_debug

在多线程中, 每个线程创建各自的JsEnv实例(此处为主线程和一条子线程).

执行一段代码后并等待几分钟, 其后主线程调用C# Api出现异常

## 错误信息
![error](https://github.com/layerpsr/puerts_debug/raw/master/pic/error.png)

## 关键代码
![code](https://github.com/layerpsr/puerts_debug/raw/master/pic/code.png)

## 其他
好像必需执行以下两处代码才会出现上述问题:(如果任意注释掉一处, 上述问题短时间内未复现)

主线程代码

![code](https://github.com/layerpsr/puerts_debug/raw/master/pic/code_1.png)

子线程代码

![code](https://github.com/layerpsr/puerts_debug/raw/master/pic/code_2.png)

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/commit/cb57ae0e20a216702ae99286341e16f5286883b6
修了一下我这可以了，你也试试

**Comment by layerpsr** [comment]
@zombieyang 好的, 谢谢! 我明天确认一下

**Comment by layerpsr** [comment]
Issues demo更新后跑起来没什么问题, 把项目puerts也更新后运行也正常了.
