### ISSUE TITLE
Delegate 对象被GC

### ISSUE THREAD

**Issue by Justin-sky** [Tencent/puerts#198]
C#中定义如下类：
public class TestP
{
}

public class TestC 
{
    public delegate TestP PCreator();
    public static PCreator pCreator;  //PCreator

    public static TestP _P; 

    public static TestP getObj()
    {
        if(_P == null )  _P = pCreator();
        return _P;
    }

    public static void SetPackageItemExtension(PCreator creator)
    {
        pCreator = creator;
    }
}

在TS中这样调用：
//test delegate
  TestC.SetPackageItemExtension(()=>{
      return new TTestC();
  })

  setInterval(()=>{
      let p = TestC.getObj();
      if(p instanceof TTestC){
          console.log("aaaaaaaaaaaaaaaa")
      }else{
          console.log("bbbbbbbbbbbbbbbbbbbb")
      }

  },1000)

一段时间后，获取到的对象p开始出错，得到 {} 空对象

**Comment by Justin-sky** [comment]
![Uploading image.png…]()

**Comment by zombieyang** [comment]
ts里的TestC和TTestC有啥区别？

**Comment by Justin-sky** [comment]
忘记加TTestC 代码了： TTestC 继承 C#中的TestP

class TTestC extends TestP{

    public test(){
        console.log("hello test delegate")
    }
}

**Comment by Justin-sky** [comment]
GenericDelegate.cs 116行：
Dictionary<IntPtr, WeakReference> nativePtrToGenericDelegate = new Dictionary<IntPtr, WeakReference>();
我怀疑是因为这里用的WeakReference 所以被GC了

**Comment by zombieyang** [comment]
如果是GenericDelegate被GC，那应该是调用的时候就会报错。我比较倾向于是Delegate被调用了，只是返回过程里出现了问题。

**Comment by Justin-sky** [comment]
在确是被调用了，我测试输出：前20秒正确，20秒后就开始出错 
![image](https://user-images.githubusercontent.com/58215826/112791477-3d200400-9094-11eb-8280-1dbd51ad1797.png)

**Comment by zombieyang** [comment]
我这边差不多跑20分钟才会出现一次，比较难复现。麻烦帮忙看一下c#侧return前，和JS侧拿到的值的对比

**Comment by Justin-sky** [comment]
![image](https://user-images.githubusercontent.com/58215826/112797158-92144800-909d-11eb-8acf-778d3347a329.png)
![image](https://user-images.githubusercontent.com/58215826/112797241-b2dc9d80-909d-11eb-8ab4-07e9cf5ab4ff.png)
C#侧拿到的对象始终是 TestP

**Comment by Justin-sky** [comment]
Js侧在出错后拿到的对象变成 p:{}

**Comment by Justin-sky** [comment]
https://github.com/Justin-sky/Nice-TS  我把测试代码提交到这了。。我用这代码很容易重现，启动 LaunchScene 这个场景就能看输出，
c#类 ： Nice-TS\Assets\Scripts\GameLaunch\Test.cs

**Comment by zombieyang** [comment]
查明和 #65 问题一致，是JS对象继承CS对象导致的。TTestC被GC了，但原型链上的TestP没被GC。

目前有一个解决办法是在 C# 侧使用 JsObject 对象来持有它。参见 #180 。 example: https://github.com/chexiongsheng/puerts_unity_demo/pull/16

**Comment by zombieyang** [comment]
后续再讨论看看有没有更好的办法
