### ISSUE TITLE
C2280        'std::shared_ptr<T> std::dynamic_pointer_cast<T,v8::Data>(const std::shared_ptr<v8::Data> &) noexcept': attempting to reference a deleted function        puerts_unreal_demo        E:\UEProject\puerts_unreal_demo\Plugins\Puerts\Source\QuickJS\Public\v8.h        254 

### ISSUE THREAD

**Issue by RPG3D** [Tencent/puerts#199]
去掉了V8，只用QuickJS引擎，原版Quick JS对MSVC很不友好，用的修改版(https://github.com/c-smile/quickjspp)；
去掉了JSEnv引用QuickJS里面依赖的各种链接库，直接使用QuickJS源码作为一个模块编译；
遇到这个转换失败，PuertS-QuickJS在UE4模式下需要特别的设置吗？

**Comment by chexiongsheng** [comment]
我这有能用的，编译好的：https://github.com/Tencent/puerts/actions/runs/635005535
解压到Puerts/ThirdParty，然后这改为true：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/JsEnv.Build.cs#L17

不过很奇怪，你UE为啥要用quickjs呢？按我目前的测试看，quickjs除了包体小一点（但v8也不大），其它全面都不如v8，包括性能，对象多了，内存占用也比v8高很多，工具链也一个在天，一个在地。

**Comment by chexiongsheng** [comment]
v8本身也不大，ipa只增加5M

**Comment by RPG3D** [comment]
纠结的不是运行时大小，有时候想做github同步一些很小的测试代码，用Quick JS方便一些，V8 Library 375MB有点大。
另外直接用源代码的方式也是希望方便调试Quick JS相关的代码，代码本身不多，没必要预编译。

**Comment by chexiongsheng** [comment]
不预编译quickjs在msvc用不了，别用那些别人改的，改得有可能有问题，而且随官方版本同步困难。

**Comment by chexiongsheng** [comment]
你根本不用同步v8库，v8库基本上不会变，你每个人下载就可以了

**Comment by chexiongsheng** [comment]
不过你用quickjs版本，对我来说是好事情。

**Comment by RPG3D** [comment]
之前纠结这个插件就是v8太复杂，hold不住。后来发现quickjs修改版，准备再试试。用lua插件的时候也是改用源码编译，方便定位问题。

**Comment by chexiongsheng** [comment]
不应该需要你hold得住啊，v8作为一个广泛应用、充分验证的库，当一个黑盒用就好了。
要是那么纠结，如果你发android的版本，android的代码你是不是要看一遍呢？

**Comment by RPG3D** [comment]
还是准备试试quickjs，搞不定了再用预编译版

**Comment by RPG3D** [comment]
需要开启RTTI
