### ISSUE TITLE
调用某些 C# 函数报错

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#20]
这段代码再 C# 中正常
```ts
System.Text.Encoding.UTF8.GetBytes("Hello World")
```
在TS中调用会在如下位置报异常
https://github.com/Tencent/puerts/blob/f33c76e9ff87b4571dab2f169fb120728c408c7d/unity/Assets/Puerts/Src/GenericDelegate.cs#L304-L313

报错内如如下
```ts
Exception: D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\webapi.js:520: Error: invalid arguments to GetBytes
    return csharp__WEBPACK_IMPORTED_MODULE_0__["System"].Convert.ToBase64String(csharp__WEBPACK_IMPORTED_MODULE_0__["System"].Text.Encoding.UTF8.GetBytes(text));
                                                                                                                                                 ^
Error: invalid arguments to GetBytes
    at btoa (D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\webapi.js:520:146)
    at GameLauncher.initialize (D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\bundle.js:128:22)
    at JavaScriptApplication.initialize (D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\bundle.js:190:26)
    at new JavaScriptApplication (D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\bundle.js:186:14)
    at main (D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\bundle.js:172:5)
Puerts.GenericDelegate.Action[T1] (T1 p1) (at Assets/Libraries/Puerts/Src/GenericDelegate.cs:311)
tiny.JavaScript.Awake () (at Assets/Scripts/tiny/scripts/JavaScript.cs:74)
UnityEngine.GameObject:AddComponent()
tiny.main:Awake() (at Assets/Scripts/main.cs:12)
```

**Comment by chexiongsheng** [comment]
这是由于子类UTF8Encoding有同名的函数，但没有该重载，目前的实现调用不了。
xlua也有这样的问题，https://github.com/Tencent/xLua/issues/734，不过xlua那有个cast可以规避下这问题。
我想下有没更好的解决办法。

**Comment by chexiongsheng** [comment]
目前想到最好的办法是这么写下：
```csharp
Object.setPrototypeOf(System.Text.Encoding.UTF8, System.Text.Encoding.prototype);//只需要调用过一次即可。
System.Text.Encoding.UTF8.GetBytes("helloworld");
```

**Comment by Geequlim** [comment]
```ts
import { System } from "csharp";
Object.setPrototypeOf(System.Text.Encoding.UTF8, System.Text.Encoding.prototype);

function btoa(text: string): string {
	return System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(text));
}
```
仍然报错
```
Exception: D:/work/repositories/zombie/project/Assets/StreamingAssets\scripts\webapi.js:537: Error: invalid arguments to ToBase64String
```

**Comment by Geequlim** [comment]
确认该问题还存在
```ts
import { System } from "csharp";
Object.setPrototypeOf(System.Text.Encoding.UTF8, System.Text.Encoding.prototype);
Object.setPrototypeOf(System.Text.Encoding.ASCII, System.Text.Encoding.prototype);

function btoa(text: string): string {
	return System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(text));
}

function atob(base64: string): string {
	let data = System.Convert.FromBase64String(base64);
	let base64Decoded = System.Text.Encoding.ASCII.GetString(data);
	return base64Decoded;
}

const raw = 'Hello World!';
btoa(raw) === 'SGVsbG8gV29ybGQh'
atob(btoa(raw)) === raw
```

```
Error: invalid arguments to GetBytes
```

**Comment by CreepGin** [comment]
Yes this issue is still present. And there's another subtle issue here. `String.fromCharCode(0, 0x61, 0x73, 0x6d)` in JS will return a string of length 4 even though the first char is null terminator. But if you implement atob in C# and calls it from JS, only the partial string (up to the null terminator) will be returned. 

This is problematic because 3rdparty libs that work with wasm needs to atob the wasm binary that decodes into a string that starts with '\x00asm'.

**Comment by chexiongsheng** [comment]
> Yes this issue is still present. And there's another subtle issue here. `String.fromCharCode(0, 0x61, 0x73, 0x6d)` in JS will return a string of length 4 even though the first char is the null terminator. But if you implement atob in C# and calls it from JS, only the partial string (up to the null terminator) will be returned.
> 
> This is problematic because 3rdparty libs that work with wasm needs to atob the wasm binary that decodes into a string that starts with '\x00asm'.
> 
> Current workaround I have is to implement atob and btoa in JS:
> 
> ```js
> export function btoa(text: string): string {
> 	const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
> 	let str = text;
> 	let output = '';
> 
> 	for (let i = 0; i < str.length; i += 3) {
> 		let block = (str.charCodeAt(i) << 16) | ((i + 1 < str.length ? str.charCodeAt(i + 1) : 0) << 8) | (i + 2 < str.length ? str.charCodeAt(i + 2) : 0);
> 		output += chars[(block >> 18) & 0x3F] +
> 			chars[(block >> 12) & 0x3F] +
> 			(i + 1 < str.length ? chars[(block >> 6) & 0x3F] : '=') +
> 			(i + 2 < str.length ? chars[block & 0x3F] : '=');
> 	}
> 
> 	return output;
> }
> 
> export function atob(base64: string): string {
> 	const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
> 	let str = base64.replace(/=+$/, '');
> 	let output = '';
> 
> 	if (str.length % 4 == 1) {
> 		throw new Error('Invalid base64 string');
> 	}
> 
> 	for (let bc = 0, bs = 0, buffer, idx = 0; buffer = str.charAt(idx++); ~buffer && (bs = bc % 4 ? bs * 64 + buffer : buffer, bc++ % 4) ? output += String.fromCharCode(255 & bs >> (-2 * bc & 6)) : 0) {
> 		buffer = chars.indexOf(buffer);
> 	}
> 
> 	return output;
> }
> ```

C# version btoa do not return a string, return a Puerts.ArrayBuffer or byte[] instead, and convert it to string in ts/js.

**Comment by chexiongsheng** [comment]
The root cause is plugin api do not passing length for string: https://github.com/Tencent/puerts/blob/81b0f39a40c5ec9ce878c28bfbda6d88d250f03e/unity/Assets/core/upm/Runtime/Src/Default/Native/PuertsDLL.cs#L304
