### ISSUE TITLE
[Unity] MacOS启动Unity Examples提示puerts.bundle已损坏

### ISSUE THREAD

**Issue by GeneralWar** [Tencent/puerts#200]
如图：
![image](https://user-images.githubusercontent.com/37786563/112797285-c12ab980-909d-11eb-8a8a-8ed2ccbaef7f.png)
系统信息：
![image](https://user-images.githubusercontent.com/37786563/112797378-df90b500-909d-11eb-8123-a43984682157.png)

**Comment by zombieyang** [comment]
请看仓库的release页
