### ISSUE TITLE
[unity]类型名字字母一致 大小写不同时，自动生成的代码前面生成的会被后面生成的覆盖

### ISSUE THREAD

**Issue by 050602** [Tencent/puerts#201]
[unity]类型名字字母一致 大小写不同时，自动生成的代码前面生成的会被后面生成的覆盖
![QBV@ZHBAXW4%S6} 1 JKH6G](https://user-images.githubusercontent.com/26473448/112922670-75305100-913f-11eb-96f4-e9f96931a98e.jpg)
![Z}}3G94)9IOL}HWDP))}@4S](https://user-images.githubusercontent.com/26473448/112922678-78c3d800-913f-11eb-89f6-c91e7079f4a6.jpg)
![MA2CI2AAX_B56P`QH Q4SC5](https://user-images.githubusercontent.com/26473448/112922683-7a8d9b80-913f-11eb-8a9e-ed4055a94e88.jpg)

**Comment by zombieyang** [comment]
类型名字字母一致 大小写不同，这种情况是避免不了的么。。。总感觉这么干迟早也会在别的地方被坑

**Comment by 050602** [comment]
这个是引擎的东西，那个大写的是拿来描述entityCall里面的结构。一般当然会避免，但是它有这种情况出现，也没办法。
