### ISSUE TITLE
UE4里导出dts时规则存在问题

### ISSUE THREAD

**Issue by AlanWalk** [Tencent/puerts#205]
```cpp
static FString SafeName(const FString &Name)
{
    auto Ret = Name.Replace(TEXT(" "), TEXT("")).Replace(TEXT("-"), TEXT("_"))
        .Replace(TEXT("/"), TEXT("_")).Replace(TEXT("("), TEXT("_"))
        .Replace(TEXT(")"), TEXT("_")).Replace(TEXT("?"), TEXT("$"))
        .Replace(TEXT(","), TEXT("_"));
    if (Ret.Len() > 0)
    {
        auto FirstChar = Ret[0];
        if ((TCHAR)'0' <= FirstChar && FirstChar <= (TCHAR)'9')
        {
            return TEXT("_") + Ret;
        }
    }
    return Ret;
}
```
1. 现在的导出DTS取变量名的逻辑是这个样子的，对于空格采用了直接移除，但是蓝图中的变量命名是允许空格存在的，虽然说变量名里加空格不一定是一个好的写法，但是感觉是不是应该和蓝图里规则兼容，转成_而不是直接移除？
比如我发现美术同学用蓝图的时候定义了bool叫"LeftGlass"，然后又定义了一个int32叫"Left Glass"，导到dts中，这俩变量就重名了，导致了报错。

2. 为什么 `?` 不和其他的字符一样替换成 `_`，而是选择了 `$` 呢？这样规则不统一了

**Comment by chexiongsheng** [comment]
感觉包含这种不支持字符的直接不生成还好些。因为现在的运行时部分是没做转换的，生成转换了其实也访问不到。

**Comment by layerpsr** [comment]
ts的变量允许声明为 public ["any character"]: string 这种形式, 如果是特殊字符串可以这样处理

**Comment by AlanWalk** [comment]
> ts的变量允许声明为 public ["any character"]: string 这种形式, 如果是特殊字符串可以这样处理

这个方式感觉可行，如果目前运行期没做替换的话，现有规则反正也不生效，可以考虑替换成这样~
