### ISSUE TITLE
请教几个 Puerts for Unreal 的问题

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/puerts#207]
Puerts 的作者您好，我是从 UnLua 转过来的，刚刚接触 Unreal 版本的 Puerts 不久，有几个问题想请教一下：

1. 请问如何导出纯 C++ （非蓝图）的类，结构体和枚举类给 TypeScript 使用呢？
2. 请问如何访问纯蓝图类（BlueprintGeneratedClass）的静态代码呢？我发现静态 Binding 也是支持纯蓝图类的，例如在项目中创建一个蓝图 MyBPObject，它可以导出类名为 MyBPObject_C 的静态代码给 TypeScript 使用，但是运行的时候会有报错，提示需要使用 puerts.blueprint 来加载。
3. 请问如何用反射 Binding 的方式访问纯蓝图结构体（UserDefinedStruct）呢？例如在项目中创建一个蓝图结构体 MyBPStruct，我尝试直接访问 UE.MyBPStruct，会提示它是一个蓝图类型，需要使用 puerts.blueprint 来加载；然后我尝试使用 puerts.blueprint("/Game/**/MyBPStruct.MyBPStruct") 来加载，路径是正确的，但是会提示无法从目标路径中加载蓝图类。
4. 请问在使用反射 Binding 的情况下，能否使用显示名称（DisplayName）来访问纯蓝图枚举类（UserDefinedEnum）的枚举值呢？例如在项目中创建一个蓝图枚举类，枚举值的显示名称为 EnumValueA，EnumValueB，EnumValueC……，我发现在 TypeScript 中并不能使用这些显示名称来访问，而是只能使用引擎默认生成的识别名称，例如 NewEnumerator0，NewEnumerator1，NewEnumerator2……
5. 在使用静态 Binding 的情况下，我发现纯蓝图结构体的静态代码中会产生冗余的成员属性，例如 StringArray，StringSet 和 StringIntMap，请问它们的用途是什么呢？
6. 在使用静态 Binding 的情况下，我发现纯蓝图枚举类的静态代码中会出现枚举值不完整的情况，而且名称也会变化。例如原先的枚举值有 EnumValueA，EnumValueB，EnumValueC……，但是在静态代码中只剩下 One 和 Two 两个枚举值。请问这个问题要如何解决呢？

我使用的 Puerts 版本是 [Release 1.0.13](https://github.com/Tencent/puerts/releases/tag/v1.0.13)。

**Comment by chexiongsheng** [comment]
1、推荐用扩展函数（demo有例子），还有个静态代码生成器，不过静态代码生成器不一定能适应所有c++语法；
2~3、demo有例子，看例子；
3~6，你看到的，都是通过UE的反射api获取到的名字，反射返回啥，就生成啥。

**Comment by GotGimhong** [comment]
> 1、推荐用扩展函数（demo有例子），还有个静态代码生成器，不过静态代码生成器不一定能适应所有c++语法；
> 2 ~ 3、demo有例子，看例子；
> 3 ~ 6，你看到的，都是通过UE的反射api获取到的名字，反射返回啥，就生成啥。

收到，感谢解答。

关于问题2，4~ 6：已了解，没有其他疑问了。

关于问题1：请问扩展函数的例子，是不是指 `AutoRegisterForFBox2D`，`AutoRegisterForFVector` 等的那些 Wrap 代码呢？我仿照它们的写法试用了一下，确实能够为**纯 C++ 类和结构体**生成静态代码。不过感觉写起来有点不方便，其实有很多代码是可以复用的，需要自己做些封装，请问有没有提供类似 UnLua 那样（例如 `EXPORT_NAMED_CLASS`，`ADD_FUNCTION` 和 `ADD_PROPERTY`）的宏呢？另外请问**纯 C++ 的枚举类**需要怎么导出呢？

关于问题3：我在 Demo 中只找到了纯蓝图类的例子（TestBlueprint_C），没有找到纯蓝图结构体的例子。请问纯蓝图结构体是不是不支持使用反射的方式来访问呢？

**Comment by chexiongsheng** [comment]
AutoRegisterForFBox2D那些是自动生成的，用这个工具：https://github.com/chexiongsheng/puerts_unreal_demo/tree/master/Plugins/Puerts/Generator，但其实还有更简单的方式，用扩展函数功能，这个是对Object的一些非UFunction的封装的示例：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/Puerts/Private/ObjectExtension.h
用宏没那么简单，因为puerts还需要生成api声明文件，用宏只能解决静态封装的问题。

默认我只生成UClass的声明，如果一个UStruct和UEnum被UClass引用了，也会生成，单独的UStruct不会生成，单独的一个UStruct没有函数使用到，似乎没生成的必要。当然，你自己也可以改生成规则。

**Comment by GotGimhong** [comment]
> AutoRegisterForFBox2D那些是自动生成的，用这个工具：https://github.com/chexiongsheng/puerts_unreal_demo/tree/master/Plugins/Puerts/Generator ，但其实还有更简单的方式，用扩展函数功能，这个是对Object的一些非UFunction的封装的示例：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/Puerts/Private/ObjectExtension.h
> 用宏没那么简单，因为puerts还需要生成api声明文件，用宏只能解决静态封装的问题。
> 
> 默认我只生成UClass的声明，如果一个UStruct和UEnum被UClass引用了，也会生成，单独的UStruct不会生成，单独的一个UStruct没有函数使用到，似乎没生成的必要。当然，你自己也可以改生成规则。

请问是不是给错了示例呢？`ObjectExtension` 里面只有 UFunction，并没有非 UFunction。
![QQ截图20210412180721](https://user-images.githubusercontent.com/16437644/114378250-1c8a9a80-9bba-11eb-84bb-9b17ecb399db.png)

**Comment by chexiongsheng** [comment]
没错啊，这是声明，实现看cpp，简单来说，就是讲非UFunction封装成UFunction

**Comment by GotGimhong** [comment]
> 没错啊，这是声明，实现看cpp，简单来说，就是讲非UFunction封装成UFunction

明白了，感谢，之前一下子没理解你的意思。

还有一个问题就是，能否生成非 UENUM 枚举类的静态代码呢？例如：
```c++
enum class EMyEnum
{
    MyEnum_A,
    MyEnum_B,
    MyEnum_C,
}
```

我知道 UENUM 的枚举类是可以的，但是非 UENUM 的就不清楚了。

**Comment by chexiongsheng** [comment]
能反射的就能生成。
不能反射的只能用那个工具去分析代码来生成。

**Comment by GotGimhong** [comment]
> 能反射的就能生成。
> 不能反射的只能用那个工具去分析代码来生成。

好的，以上问题全部了解。

我按照 README.md 试用了一下静态代码生成工具，发现在 ue_project.py 中有报错，看起来是无法从 vcxproj 文件中找到引擎头文件的包含目录，我直接在 Demo 下运行也会出现同样的问题。报错信息如下：

```
Traceback (most recent call last):
    File "main.py", line 280, in <module>
        main()
    File "main.py", line 252, in main
        ue_proj = UEProj(opts.project_path)
    File "D:\puerts_unreal_demo\Plugins\Puerts\Generator\ue_project.py", line 15, in __init__
        include_search_paths = root.find('ns:PropertyGroup/ns:NMakeIncludeSearchPath', namespaces).text.replace('$(NMakeIncludeSearchPath)', NMakeIncludeSearchPath)
AttributeError: 'NoneType' object has no attribute 'text'
```

报错出现在 ue_project.py 的第15行：引擎头文件包含目录的获取，不过第16行：预编译宏的获取则是正常的。请问是我哪里操作不当呢？

**Comment by chexiongsheng** [comment]
这工具并没发布，有问题自己看代码解决，不做支持。

**Comment by GotGimhong** [comment]
> 这工具并没发布，有问题自己看代码解决，不做支持。

了解，感谢解答。

**Comment by chexiongsheng** [comment]
问题4最新改为GetAuthoredNameStringByIndex了

**Comment by GotGimhong** [comment]
> 问题4最新改为GetAuthoredNameStringByIndex了

收到，感谢提醒。试用过，体验比之前好了很多。
