### ISSUE TITLE
[Unreal] 关于LoadFile失败后是抛出异常还是打印Error日志

### ISSUE THREAD

**Issue by AlanWalk** [Tencent/puerts#211]
你好，最近升级到最新插件发现了一处修改，是把LoadFile失败后的异常处理改为了纯打印日志，修改提交：
https://github.com/Tencent/puerts/commit/ec3960539c79d831f2e6b7a8badc1febcfb195f9

个人觉得之前的抛出异常会更好一点，因为异常可以被Cache住，但是LogError不行，比如我们项目引用了 `source-map-support`这个库，这个库一起来会尝试 `require('fs')`，`fs` 模块不是它的必要依赖，所以做了trycatch。

![image](https://user-images.githubusercontent.com/4654826/114511181-28ce3080-9c6a-11eb-9ce8-79fb0535e2c2.png)

基于这种情况，以前的代码Error就直接被Catch了，不会有任何日志输出，但是现在被Cache了也会在C++这层打印一条Error日志出来。

希望可以考虑一下改回之前的抛出JSError，让使用者自行处理~

**Comment by chexiongsheng** [comment]
那个JSError以前也是打日志，而且这如果是JS调用，还是跑js异常的：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnv.cpp#L2509

**Comment by AlanWalk** [comment]
嗯，所以如果找不到module的时候会打印一条Error日志，并抛出异常，异常可以通过trycatch捕获，但是Error日志不管怎么样都会有，这个就比较讨厌了。

**Comment by chexiongsheng** [comment]
这个可以改下。主要是这函数C++入口也用到，c++入口只能打日志
