### ISSUE TITLE
BP 调用TS实现的Actor 函数无法编译成功

### ISSUE THREAD

**Issue by jiayuwangcj** [Tencent/puerts#213]
```

import * as UE from 'ue'
import { $ref, $unref, blueprint } from 'puerts'
import TS_SamCharacter from './TS_SamCharacter';

class TS_XXXController extends UE.PlayerController {
    Constructor() {
    }

    // @flags:FUNC_BlueprintEvent | FUNC_Event | FUNC_Public
    DelegateStartFovChange(value: number): void {
    }

    // SomeOtherFunc():{
    // }
}
```
首次运行可能会成功， 但是一旦做出修改， 比如打开函数 SomeOtherFunc
所有调用该方法的蓝图都会报如下编译错误

![image](https://user-images.githubusercontent.com/24957044/114525303-95e8c280-9c78-11eb-91f7-951a16b80062.png)

**Comment by chexiongsheng** [comment]
试试这里加个FUNC_Event？
https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/TypeScriptGeneratedClass.cpp#L70

**Comment by jiayuwangcj** [comment]
测试了可以了，但是需要删掉之前自动生成的bp
我再多测试下

**Comment by jiayuwangcj** [comment]
后来多测试了下， 问题依旧
