### ISSUE TITLE
使用puerts进行服务器开发是否可行？

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/puerts#214]
目前想到了几个问题，想向您请教一下：
1. 64位v8限制内存上限约为1.4GB，这个上限是否可以突破？根据我搜索的信息，可以通过max-old-space-size来扩展，puerts是否也是支持的？
2. puerts目前不支持多线程，这个我们有没有办法自己添加这部分功能？根据我搜索的信息，v8虽然有Isolate，但是不支持共享js对象。
3. v8在堆内存较大的时候GC表现如何？我看到有人说，使用约1.5GB内存，一次全量GC需要1s，一次增量GC需要50ms。
4. 是否还有其他您能想到的问题？

**Comment by chexiongsheng** [comment]
puerts用的V8，和nodejs是一样的，而且版本号也和lts版本一样。所以和js执行相关的，包括内存上限，gc啥的都可以和node一致。
多线程这块倒不好弄。
你用puerts是为了和.net交互么？如果不是，直接用node不就可以了么？

**Comment by iNeverSleeeeep** [comment]
用ts是为了和客户端共用代码，客户端为UE+ts，服务器为UE Server+ts，这套技术选型你感觉怎么样？

**Comment by chexiongsheng** [comment]
可以啊，V8在服务器上是开jit的，据说按v8的喜欢的方式写代码（网上有相关的文章），能接近原生的性能。

**Comment by chexiongsheng** [comment]
配置UseNewV8，然后用action 编译好的v8的8.4.371.19版本，这个版本和nodejs v14.15是同版本的v8
