### ISSUE TITLE
蓝图继承TS编写的类，并在蓝图子类中调用父类函数，TS类的函数修改了，子类蓝图的函数还是没修改

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#219]
UE4.26.1
1.随便新建一个TS类
![QQ截图20210420152507](https://user-images.githubusercontent.com/5086299/115354822-a0610a00-a1ec-11eb-89b6-448b936663e3.png)

2.随便新建一个蓝图类，继承步骤1中的TS类，并调用TS中函数
![QQ图片20210420152635](https://user-images.githubusercontent.com/5086299/115354994-d0101200-a1ec-11eb-8bb1-7dbd16c270c3.png)
3.把蓝图子类丢到场景中，这个时候会打印
![image](https://user-images.githubusercontent.com/5086299/115355411-3ac14d80-a1ed-11eb-825e-40b4a5fff0c4.png)
4.关闭蓝图子类（一定要关闭），然后修改TS类
![image](https://user-images.githubusercontent.com/5086299/115355602-66dcce80-a1ed-11eb-9297-c396e17b0594.png)
5.运行，这个时候打印的还是修改之前的
![image](https://user-images.githubusercontent.com/5086299/115355678-7a883500-a1ed-11eb-8dff-02496f123e64.png)
6.打开蓝图子类，随便移动下节点，然后保存（关键是保存）
![image](https://user-images.githubusercontent.com/5086299/115355825-a1466b80-a1ed-11eb-8389-2a391669992c.png)
7.这个时候TS修改的才能在蓝图子类中生效
![image](https://user-images.githubusercontent.com/5086299/115356017-d18e0a00-a1ed-11eb-91e3-7745fb0f14af.png)

**Comment by chexiongsheng** [comment]
我按你操作没任何问题。
你修改TS只是修改函数体的话，其实只是调用V8的hot-reload更新脚本而已，和你蓝图关闭保存这些都没关系。

**Comment by chexiongsheng** [comment]
因为只是hot-reload，你看看日志里头有没相关日志，没有可能是你那个状态下没监听到文件变动，考虑到我用的UE提供的watch，和蓝图编辑器互相影响也可能：
Puerts: (0x000001D8D8CC7E70) E:/puerts_unreal_demo/TsProj/MyTestActor.ts md5 from 2562c31e7584d4e9da0e211d1f3f3e27 to 3f90f102b0f77d2765ca8a333195c6ab
Puerts: (0x000001D8D8CC7E70) incremental compile E:/puerts_unreal_demo/TsProj/MyTestActor.ts using 304ms
Puerts: (0x000001D8D8CC7E70) write E:/puerts_unreal_demo/Content/JavaScript/MyTestActor.js.map ...
Puerts: (0x000001D8D8CC7E70) write E:/puerts_unreal_demo/Content/JavaScript/MyTestActor.js ...
Puerts: Display: (0x000001D907FA09F0) reload js module [E:/puerts_unreal_demo/Content/JavaScript/MyTestActor.js]
Puerts: Display: (0x000001D907FA09F0) reload blueprint module [MyTestActor]
Puerts: (0x000001D8D8CC7E70) gen blueprint for MyTestActor, path:

**Comment by CasonCaly** [comment]
我发现我这么是这样出现的，先修改TS_Player
![image](https://user-images.githubusercontent.com/5086299/115367662-fc319000-a1f8-11eb-94ab-31b503a89422.png)
改成这样之后
![image](https://user-images.githubusercontent.com/5086299/115367724-094e7f00-a1f9-11eb-8e72-e81da74080a0.png)
在控制台是有文件变更日志的
![image](https://user-images.githubusercontent.com/5086299/115367698-0489cb00-a1f9-11eb-9ba3-a89f82d32cda.png)
第一次运行是没有生效的
![image](https://user-images.githubusercontent.com/5086299/115367945-3307a600-a1f9-11eb-8134-4129df64726b.png)
Stop之后，再Play就可以生效
![image](https://user-images.githubusercontent.com/5086299/115368025-4581df80-a1f9-11eb-9083-bf4abe1240af.png)

**Comment by chexiongsheng** [comment]
我没问题，我是最新的版本，或者你更新到最新看看

**Comment by CasonCaly** [comment]
已经是最新版本了
![image](https://user-images.githubusercontent.com/5086299/115369097-5717b700-a1fa-11eb-967d-a625cc55020e.png)

**Comment by chexiongsheng** [comment]
关闭蓝图子类（一定要关闭），指的是关闭那个蓝图编辑窗口？

**Comment by CasonCaly** [comment]
不好意思，这个不是必要的，我之前以为这个是必要步骤

**Comment by CasonCaly** [comment]
我后面再看下我有没有遗漏其他步骤
