### ISSUE TITLE
[unity] Linux 上importdll puerts不成功。/code/libpuerts.so: error: symbol lookup error: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev (fatal)

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#221]
6:	
         6:	file=/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/puerts.so [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=/code/puerts.so [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=puerts.so [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	find library=puerts.so [0]; searching
         6:	 search path=/code		(LD_LIBRARY_PATH)
         6:	  trying file=/code/puerts.so
         6:	 search cache=/etc/ld.so.cache
         6:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
         6:	  trying file=/lib/x86_64-linux-gnu/puerts.so
         6:	  trying file=/usr/lib/x86_64-linux-gnu/puerts.so
         6:	  trying file=/lib/puerts.so
         6:	  trying file=/usr/lib/puerts.so
         6:	
         6:	
         6:	file=/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libpuerts.so [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=/code/libpuerts.so [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	file=/code/libpuerts.so [0];  generating link map
         6:	  dynamic: 0x00007f655bfd5ce0  base: 0x00007f655af0c000   size: 0x00000000010f1cb8
         6:	    entry: 0x00007f655afd2e40  phdr: 0x00007f655af0c040  phnum:                  8
         6:	
         6:	checking for version `GCC_3.0' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.2.5' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libm.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBCXX_3.4.11' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `CXXABI_1.3.9' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBCXX_3.4.21' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBCXX_3.4' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `CXXABI_1.3' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.17' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3.2' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.4' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3.4' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.7' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.14' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	object=/code/libpuerts.so [0]
         6:	 scope 0: /usr/bin/dotnet /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2 /usr/lib/x86_64-linux-gnu/liblttng-ust-tracepoint.so.0 /usr/lib/x86_64-linux-gnu/liburcu-bp.so.4 /usr/lib/x86_64-linux-gnu/liburcu-cds.so.4 /usr/lib/x86_64-linux-gnu/liburcu-common.so.4 /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclrtraceptprovider.so /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0 /lib/x86_64-linux-gnu/librt.so.1
         6:	 scope 1: /code/libpuerts.so /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2
         6:	
         6:	
         6:	relocation processing: /code/libpuerts.so (lazy)
         6:	symbol=__pthread_key_create;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	binding file /code/libpuerts.so [0] to /lib/x86_64-linux-gnu/libpthread.so.0 [0]: normal symbol `__pthread_key_create'
         6:	symbol=__pthread_key_create;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	binding file /code/libpuerts.so [0] to /lib/x86_64-linux-gnu/libpthread.so.0 [0]: normal symbol `__pthread_key_create'
         6:	symbol=__cxa_pure_virtual;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=__cxa_pure_virtual;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=__cxa_pure_virtual;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	symbol=__cxa_pure_virtual;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
         6:	binding file /code/libpuerts.so [0] to /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]: normal symbol `__cxa_pure_virtual' [CXXABI_1.3]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liblttng-ust-tracepoint.so.0 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liburcu-bp.so.4 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liburcu-cds.so.4 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liburcu-common.so.4 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclrtraceptprovider.so [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liblttng-ust.so.0 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/librt.so.1 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/code/libpuerts.so [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
         6:	/code/libpuerts.so: error: symbol lookup error: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev (fatal)
         6:	
         6:	file=/code/libpuerts.so [0];  destroying link map
         6:	
         6:	file=libpuerts.so [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	find library=libpuerts.so [0]; searching
         6:	 search path=/code		(LD_LIBRARY_PATH)
         6:	  trying file=/code/libpuerts.so
         6:	
         6:	file=libpuerts.so [0];  generating link map
         6:	  dynamic: 0x00007f655bfd5ce0  base: 0x00007f655af0c000   size: 0x00000000010f1cb8
         6:	    entry: 0x00007f655afd2e40  phdr: 0x00007f655af0c040  phnum:                  8
         6:	
         6:	checking for version `GCC_3.0' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.2.5' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libm.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBCXX_3.4.11' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `CXXABI_1.3.9' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBCXX_3.4.21' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBCXX_3.4' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `CXXABI_1.3' in file /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.17' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3.2' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.4' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3.4' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.7' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.3' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.14' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /code/libpuerts.so [0]
         6:	object=/code/libpuerts.so [0]
         6:	 scope 0: /usr/bin/dotnet /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2 /usr/lib/x86_64-linux-gnu/liblttng-ust-tracepoint.so.0 /usr/lib/x86_64-linux-gnu/liburcu-bp.so.4 /usr/lib/x86_64-linux-gnu/liburcu-cds.so.4 /usr/lib/x86_64-linux-gnu/liburcu-common.so.4 /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclrtraceptprovider.so /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0 /lib/x86_64-linux-gnu/librt.so.1
         6:	 scope 1: /code/libpuerts.so /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2
         6:	
         6:	
         6:	relocation processing: /code/libpuerts.so (lazy)
         6:	symbol=__pthread_key_create;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	binding file /code/libpuerts.so [0] to /lib/x86_64-linux-gnu/libpthread.so.0 [0]: normal symbol `__pthread_key_create'
         6:	symbol=__pthread_key_create;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=__pthread_key_create;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	binding file /code/libpuerts.so [0] to /lib/x86_64-linux-gnu/libpthread.so.0 [0]: normal symbol `__pthread_key_create'
         6:	symbol=__cxa_pure_virtual;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=__cxa_pure_virtual;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=__cxa_pure_virtual;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	symbol=__cxa_pure_virtual;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
         6:	binding file /code/libpuerts.so [0] to /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]: normal symbol `__cxa_pure_virtual' [CXXABI_1.3]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/bin/dotnet [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liblttng-ust-tracepoint.so.0 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liburcu-bp.so.4 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liburcu-cds.so.4 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liburcu-common.so.4 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclrtraceptprovider.so [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/liblttng-ust.so.0 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/librt.so.1 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/code/libpuerts.so [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
         6:	symbol=_ZNSt3__119__shared_weak_countD2Ev;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
         6:	/code/libpuerts.so: error: symbol lookup error: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev (fatal)
         6:	
         6:	file=/code/libpuerts.so [0];  destroying link map
         6:	
         6:	file=/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/puerts [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=/code/puerts [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=puerts [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	find library=puerts [0]; searching
         6:	 search path=/code		(LD_LIBRARY_PATH)
         6:	  trying file=/code/puerts
         6:	 search cache=/etc/ld.so.cache
         6:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
         6:	  trying file=/lib/x86_64-linux-gnu/puerts
         6:	  trying file=/usr/lib/x86_64-linux-gnu/puerts
         6:	  trying file=/lib/puerts
         6:	  trying file=/usr/lib/puerts
         6:	
         6:	
         6:	file=/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libpuerts [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=/code/libpuerts [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	
         6:	file=libpuerts [0];  dynamically loaded by /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so [0]
         6:	find library=libpuerts [0]; searching
         6:	 search path=/code		(LD_LIBRARY_PATH)
         6:	  trying file=/code/libpuerts
         6:	 search cache=/etc/ld.so.cache
         6:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
         6:	  trying file=/lib/x86_64-linux-gnu/libpuerts
         6:	  trying file=/usr/lib/x86_64-linux-gnu/libpuerts
         6:	  trying file=/lib/libpuerts
         6:	  trying file=/usr/lib/libpuerts
         6:	
2021-04-21T10:00:07.658Z d2407ce6-f525-4372-9292-2a9a29959929 [ERROR] System.DllNotFoundException: Unable to load shared library 'puerts' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpuerts: cannot open shared object file: No such file or directory
   at Puerts.PuertsDLL.GetLibVersion()
   at Puerts.JsEnv..ctor(ILoader loader, Int32 debugPort, IntPtr externalRuntime, IntPtr externalContext)
   at Client.JSManager..ctor(Dictionary`2 paras)

**Comment by mingxxming** [comment]
会不会是使用std::string 的原因，，

**Comment by mingxxming** [comment]
选用libstdc++为标准库重新编译v8 可以解决
https://stackoverflow.com/questions/54723720/how-to-use-linked-libraries-compiled-with-libc-libstdc-mixed

**Comment by chexiongsheng** [comment]
把puerts改为链接libc++也可以，我本地环境是能编译且正常运行，但不知道为啥github的action编译不过

**Comment by chexiongsheng** [comment]
升级下github虚拟机的clang就能成功编译了。
libc++才是标准，应该好些，苹果老早就升级了。

**Comment by mingxxming** [comment]
你是在linux下c#调用吗？

**Comment by chexiongsheng** [comment]
是的，可以调用成功
