### ISSUE TITLE
[unity]对通过 package.json 文件来定义要加载的 js 文件的第三方库 require() 多次会出错, 如 ts-typed-events 库

### ISSUE THREAD

**Issue by daxiazh** [Tencent/puerts#223]
经查找发现 modular.js.txt 中有 bug, 如图:
![image](https://user-images.githubusercontent.com/8003994/115558498-6293dc80-a2e5-11eb-92d0-4c010bab4f79.png)

**Comment by chexiongsheng** [comment]
是要加，要不你提交个PR过来？
