### ISSUE TITLE
[Unity]请问关于Update调用的推荐的实现方式

### ISSUE THREAD

**Issue by xhds** [Tencent/puerts#228]
您好，在 unity 的 demo 工程的 04_JsBehaviour 这一个样例中，写了一句注释 ：“只是演示纯用js实现MonoBehaviour逻辑的可能，但从性能角度这并不是最佳实践，会导致过多的跨语言调用”。

我想请问一下，商业项目中，如果想用 puerts 实现类似的业务框架，当需要具有 tick、 update 一类的频繁调用的功能，或者需要频繁的通过unity的update调用ts、或者ts频繁调用unity时，请问您建议的实现方式是怎么做？有没有比较合适的最佳实践例子？ 谢谢~

**Comment by zombieyang** [comment]
可以在QQ群上讨论，有更多有实际游戏开发经验的朋友们
