### ISSUE TITLE
1.0.13版，在部分iOS設備，第二次開啟app時會閃退

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#230]
<img width="635" alt="{42428C6B-85B7-9529-A50A-0E82BE6E4CB7}" src="https://user-images.githubusercontent.com/12165833/116089071-0f4ecf00-a6d5-11eb-8e3d-dfeeb4924716.png">
<img width="741" alt="{71F7D875-D7CA-6B2A-849E-B7D08419F892}" src="https://user-images.githubusercontent.com/12165833/116089087-1249bf80-a6d5-11eb-8675-7231e033ad5d.png">
<img width="752" alt="{E460632C-3683-568D-18EF-594E27D38C54}" src="https://user-images.githubusercontent.com/12165833/116089103-15dd4680-a6d5-11eb-9f42-450a2c0ac4fe.png">

**Comment by h3902340** [comment]
目前測試以下設備必定會在第二次開啟app閃退：
iPad 7, 14.4.2：必現
iPhone 6, 12.5.1：必現

**Comment by hszhsh** [comment]
多个delegate引用同一个JSFunction释放时会有问题，可以给JSFunction加上引用计数来释放

```c++
    JSFunction* JSEngine::CreateJSFunction(v8::Isolate* InIsolate, v8::Local<v8::Context> InContext, v8::Local<v8::Function> InFunction)
    {
        std::lock_guard<std::mutex> guard(JSFunctionsMutex);
        auto maybeId = InFunction->Get(InContext, FV8Utils::V8String(InIsolate, FUNCTION_INDEX_KEY));
        if (!maybeId.IsEmpty()) {
            auto id = maybeId.ToLocalChecked();
            if (id->IsNumber()) {
                int32_t index = id->Int32Value(InContext).ToChecked();
                return JSFunctions[index];
            }
        }
        JSFunction* Function = nullptr;
        for (int i = 0; i < JSFunctions.size(); i++) {
            if (!JSFunctions[i]) {
                Function = new JSFunction(InIsolate, InContext, InFunction, i);
                JSFunctions[i] = Function;
                break;
            }
        }
        if (!Function) {
            Function = new JSFunction(InIsolate, InContext, InFunction, static_cast<int32_t>(JSFunctions.size()));
            JSFunctions.push_back(Function);
        }
        InFunction->Set(InContext, FV8Utils::V8String(InIsolate, FUNCTION_INDEX_KEY), v8::Integer::New(InIsolate, Function->Index));
        return Function;
    }

    void JSEngine::ReleaseJSFunction(JSFunction* InFunction)
    {
        std::lock_guard<std::mutex> guard(JSFunctionsMutex);
        JSFunctions[InFunction->Index] = nullptr;
        delete InFunction;
    }
```

**Comment by chexiongsheng** [comment]
> 多个delegate引用同一个JSFunction释放时会有问题，可以给JSFunction加上引用计数来释放
> 
> ```c++
>     JSFunction* JSEngine::CreateJSFunction(v8::Isolate* InIsolate, v8::Local<v8::Context> InContext, v8::Local<v8::Function> InFunction)
>     {
>         std::lock_guard<std::mutex> guard(JSFunctionsMutex);
>         auto maybeId = InFunction->Get(InContext, FV8Utils::V8String(InIsolate, FUNCTION_INDEX_KEY));
>         if (!maybeId.IsEmpty()) {
>             auto id = maybeId.ToLocalChecked();
>             if (id->IsNumber()) {
>                 int32_t index = id->Int32Value(InContext).ToChecked();
>                 return JSFunctions[index];
>             }
>         }
>         JSFunction* Function = nullptr;
>         for (int i = 0; i < JSFunctions.size(); i++) {
>             if (!JSFunctions[i]) {
>                 Function = new JSFunction(InIsolate, InContext, InFunction, i);
>                 JSFunctions[i] = Function;
>                 break;
>             }
>         }
>         if (!Function) {
>             Function = new JSFunction(InIsolate, InContext, InFunction, static_cast<int32_t>(JSFunctions.size()));
>             JSFunctions.push_back(Function);
>         }
>         InFunction->Set(InContext, FV8Utils::V8String(InIsolate, FUNCTION_INDEX_KEY), v8::Integer::New(InIsolate, Function->Index));
>         return Function;
>     }
> 
>     void JSEngine::ReleaseJSFunction(JSFunction* InFunction)
>     {
>         std::lock_guard<std::mutex> guard(JSFunctionsMutex);
>         JSFunctions[InFunction->Index] = nullptr;
>         delete InFunction;
>     }
> ```

不会有问题啊，同一个JS函数映射到C#都是同一个GenericDelegate，然后多个Delegate引用这个GenericDelegate而已。你之前碰到多delegate问题的话，应该和这个问题有关。

**Comment by hszhsh** [comment]
> > 多个delegate引用同一个JSFunction释放时会有问题，可以给JSFunction加上引用计数来释放
> > ```c++
> >     JSFunction* JSEngine::CreateJSFunction(v8::Isolate* InIsolate, v8::Local<v8::Context> InContext, v8::Local<v8::Function> InFunction)
> >     {
> >         std::lock_guard<std::mutex> guard(JSFunctionsMutex);
> >         auto maybeId = InFunction->Get(InContext, FV8Utils::V8String(InIsolate, FUNCTION_INDEX_KEY));
> >         if (!maybeId.IsEmpty()) {
> >             auto id = maybeId.ToLocalChecked();
> >             if (id->IsNumber()) {
> >                 int32_t index = id->Int32Value(InContext).ToChecked();
> >                 return JSFunctions[index];
> >             }
> >         }
> >         JSFunction* Function = nullptr;
> >         for (int i = 0; i < JSFunctions.size(); i++) {
> >             if (!JSFunctions[i]) {
> >                 Function = new JSFunction(InIsolate, InContext, InFunction, i);
> >                 JSFunctions[i] = Function;
> >                 break;
> >             }
> >         }
> >         if (!Function) {
> >             Function = new JSFunction(InIsolate, InContext, InFunction, static_cast<int32_t>(JSFunctions.size()));
> >             JSFunctions.push_back(Function);
> >         }
> >         InFunction->Set(InContext, FV8Utils::V8String(InIsolate, FUNCTION_INDEX_KEY), v8::Integer::New(InIsolate, Function->Index));
> >         return Function;
> >     }
> > 
> >     void JSEngine::ReleaseJSFunction(JSFunction* InFunction)
> >     {
> >         std::lock_guard<std::mutex> guard(JSFunctionsMutex);
> >         JSFunctions[InFunction->Index] = nullptr;
> >         delete InFunction;
> >     }
> > ```
> 
> 不会有问题啊，同一个JS函数映射到C#都是同一个GenericDelegate，然后多个Delegate引用这个GenericDelegate而已。你之前碰到多delegate问题的话，应该和这个问题有关。

对于同一个js函数，两次Eval会生成两个不同的GenericDelegate，引用同一个JSFunction，我这个版本GenericDelegateFactory没有缓存的操作，如果C#里能保证是同一个就没问题了

**Comment by chexiongsheng** [comment]
@hszhsh 用新版的就可以了，只会影响到一个
