### ISSUE TITLE
[unreal] react-umg 模块化

### ISSUE THREAD

**Issue by qqwx1986** [Tencent/puerts#238]
目前生成的 react-umg/index.d.ts 都是单独导出的
能不能弄成 ue 模块一样模块化，这样用起来会方便些
如下面这样
declare module "react-umg" {
}
这样就能和ue&puerts一样放到Typing/下面

**Comment by qqwx1986** [comment]
我这边改了下，如果有需求该我这可以提个pr @chexiongsheng 
`
declare module "react-umg" {
    import * as React from 'react';
    import * as ue from 'ue';
    type TArray<T> = ue.TArray<T>;

    interface PanelSlot {
    }
...
`

**Comment by chexiongsheng** [comment]
可以啊，puerts_unreal_demo也帮忙调整下，也提个PR过来。
