### ISSUE TITLE
[UE4 4.26]Delegate作为参数传递失败

### ISSUE THREAD

**Issue by greatzane** [Tencent/puerts#247]
在如下的类中，定义一个TestDelegate的属性和一个接收Delegate参数的方法Test：
![image](https://user-images.githubusercontent.com/2712575/117524018-2acbab00-afee-11eb-962b-f783033316a5.png)
在TestDelegate上绑定一个方法OnTest：
![image](https://user-images.githubusercontent.com/2712575/117524064-69616580-afee-11eb-8871-c8504971a114.png)
然后在C++中调用Test方法，传入TestDelegate，此时是正常的，TestDelegate在Test方法中可以通过Execute调用绑定的方法：
![image](https://user-images.githubusercontent.com/2712575/117524144-daa11880-afee-11eb-8a67-c64326fe5141.png)
然而如果写一个该类的ts子类，用ts调用Test方法传入TestDelegate：
![image](https://user-images.githubusercontent.com/2712575/117524209-2227a480-afef-11eb-9643-ed14018822f3.png)
则传入Test方法的Delegate并不是TestDelegate，因此并不能调用到绑定的OnTest方法。
看起来Delegate作为参数传递到C++函数中的时候并没有传递成功，实际传入的是另一个Delegate实例。

**Comment by CasonCaly** [comment]
感觉是你用错了吧，DYNAMIC_MULTICAST_DELEGATE是用来Add的吧
![image](https://user-images.githubusercontent.com/5086299/117747578-01ef2400-b241-11eb-9213-a3488d7b282b.png)
下面是TS中调用
![image](https://user-images.githubusercontent.com/5086299/117747682-34991c80-b241-11eb-8543-fd4bf554b2c1.png)

**Comment by greatzane** [comment]
> 感觉是你用错了吧，DYNAMIC_MULTICAST_DELEGATE是用来Add的吧
> ![image](https://user-images.githubusercontent.com/5086299/117747578-01ef2400-b241-11eb-9213-a3488d7b282b.png)
> 下面是TS中调用
> ![image](https://user-images.githubusercontent.com/5086299/117747682-34991c80-b241-11eb-8543-fd4bf554b2c1.png)

直接Delegate上add是没问题的，但是我的情况是我使用的第三方库要求在函数参数上传入一个delegate，而ts里传入的delegate在C++函数中接收不到，应该是有问题的。

**Comment by chexiongsheng** [comment]
貌似关键代码都没贴，贴个类声明？玩猜谜么？

**Comment by greatzane** [comment]
完整代码如下：
![image](https://user-images.githubusercontent.com/2712575/118070074-d94d6280-b3d7-11eb-8d41-7ef21ebffc4b.png)
![image](https://user-images.githubusercontent.com/2712575/118070142-eec28c80-b3d7-11eb-9a81-c0b884d2fc66.png)
![image](https://user-images.githubusercontent.com/2712575/118070168-fc781200-b3d7-11eb-8dfe-4b48a14d729c.png)
我的问题是：从ts中把Delegate作为参数传递给函数的时候，在C++中接收到的不是传入的Delegate，因此OnTest不会被调用。箭头处同样的C++代码传入的就没有问题，OnTest会被调用。

**Comment by chexiongsheng** [comment]
那我知道原因了，目前把Delegate参数忽略了，我看要不要加下

**Comment by greatzane** [comment]
> 那我知道原因了，目前把Delegate参数忽略了，我看要不要加下

好的，辛苦了

**Comment by chexiongsheng** [comment]
最新代码支持了
