### ISSUE TITLE
unreal:又出现蓝图子类调用TS父类函数递归死循环问题

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#248]
写一个TS类
![image](https://user-images.githubusercontent.com/5086299/117531825-1e0f7d00-b017-11eb-8949-c08e4603152b.png)
蓝图类继承这个TS类
![image](https://user-images.githubusercontent.com/5086299/117531871-51eaa280-b017-11eb-9c22-9f2c8e8e52b6.png)
丢到场景中，运行死循环
![image](https://user-images.githubusercontent.com/5086299/117531897-662e9f80-b017-11eb-8014-75dc661fee20.png)

**Comment by chexiongsheng** [comment]
这个提交：https://github.com/Tencent/puerts/commit/073c7257dcabfc054021f180e44a75ab269c2b60  ， 没考虑到继承时，子类的创建不会触发父类的非CDO构造，所以函数没设置成native而导致没走js逻辑。
