### ISSUE TITLE
完全相同的代码, 业务逻辑都是JS，都在相同的环境（Linux）下执行。（U3D/C#）执行时间是UE的4倍左右

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#249]
有没有感兴趣的同学一起测试一下。

**Comment by chexiongsheng** [comment]
你的逻辑是怎样的呢？只是纯js，还是涉及到跨语言调用？

**Comment by mingxxming** [comment]
有涉及跨语言调用，我尝试过把跨语言调用的频率降低了80% 时间并没有明显减少

**Comment by chexiongsheng** [comment]
跨语言没可比性。甚至c#和c++都没可比性。
只有纯js才有可比性，但我觉得纯js是一样的

**Comment by mingxxming** [comment]
c# 只是做wrap的，c++ 和 js是完全一样的。额外消耗应该只在c++ ->c#->js 这两个绑定, UE是C++ ->js 一个绑定

**Comment by mingxxming** [comment]
确实之前C#有遗漏的逻辑，移除后 差距在20%这样
