### ISSUE TITLE
[UE4 4.26]项目打包后运行出错，提示“Plugin 'Puerts' failed to load because module 'JsEnv' could not be found.”

### ISSUE THREAD

**Issue by ZaiqiangWu** [Tencent/puerts#250]

**Comment by ZaiqiangWu** [comment]
> 纯蓝图工程吗,纯蓝图工程的话需要添加任意c++类使其变成c++工程

感谢回答！问题解决了

**Comment by ljporljp** [comment]
这样子解决感觉不是很优雅

**Comment by juntaosun** [comment]
这样子解决感觉不是很优雅

**Comment by chexiongsheng** [comment]
> 这样子解决感觉不是很优雅

纯蓝图工程正常的步骤应该是到unreal市场下载编译好的二进制版本吧。或者puerts官方提供二进制版本。
但问题是二进制版本在不同版本ue不一定通用，而ue发版本也比较频繁，puerts本身也有版本，意味着要维护很多二进制版本。
