### ISSUE TITLE
最新版puerts + V8在部分安卓設備仍會閃退

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#253]
這是閃退的堆棧：
libpuerts.v8::Context::Enter() (Enter:8)
libpuerts.puerts::JSFunction::~JSFunction() (~JSFunction:178)
libpuerts.puerts::JSEngine::ReleaseJSFunction(puerts::JSFunction*) (ReleaseJSFunction:64)
libpuerts.ReleaseJSFunction (ReleaseJSFunction:66)
libil2cpp.0x1a421c4
libil2cpp.0x1a41ad8
libil2cpp.0x1a418b4
libil2cpp.0xa838fc
libil2cpp.0x5a34e8
libil2cpp.0x7691f4
libunity.0x23656d
libunity.0x23fadb
libunity.0x245f7b
libunity.0x15e5d1
libunity.0x1d1897
libunity.0x1d18b3
libunity.0x1d1a51
libunity.0x288229
libunity.0x296055
base.0x20d6b

**Comment by chexiongsheng** [comment]
你们是不是有多线程的调用呢？

**Comment by chexiongsheng** [comment]
定位到其中一种情况会发生此类crash
puerts用WeakReference来跟踪GenericDelegate是否被GC，然后在GenericDelegate的析构函数进行原生的jsfunction的释放。之前代码假设一个对象被GC了，其构造函数也被调用了。但实际测试c#里头WeakReference的IsAlive应设置成false了，但析构函数可能还未释放。
这导致可能存在两个待调用析构函数的GenericDelegate都持有同一个指针。如果系统存在大量对象要gc，这两个对象可能会分批被析构，而且中间隔着一个jsEnv.Update，这时会导致重复释放问题。
解决办法是改为在C#那用引用计数来跟踪指针的释放
