### ISSUE TITLE
 unreal: TArray<string>中的string是不是没法指定为FName

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#255]
![image](https://user-images.githubusercontent.com/5086299/118600339-70088d80-b7e3-11eb-9344-964d673b9d52.png)
用TArray<string>没法转换为TArray<FName>,已经加了/*@cpp:name*/，在蓝图中还是String类型
![image](https://user-images.githubusercontent.com/5086299/118600430-91697980-b7e3-11eb-837a-66895797e6dd.png)

**Comment by CasonCaly** [comment]
![image](https://user-images.githubusercontent.com/5086299/118600751-fb821e80-b7e3-11eb-8d30-e62750b17e0a.png)
上图的TS写法有错，应该是这张图这样。但蓝图那边还是没变

**Comment by chexiongsheng** [comment]
还不支持
