### ISSUE TITLE
[Unity][WebGL]能不能支持unity发布h5?

### ISSUE THREAD

**Issue by jun7th** [Tencent/puerts#260]
目前好像只支持ios+android+window 
能不能支持unity发布h5?

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts_unity_webgl_demo
之前做过一个初步的。最近重点在于优化性能所以没有继续，你有需要可以在这个上面基础上先弄。

**Comment by zombieyang** [comment]
但如 #192  所说，插件会是比较麻烦的部分，不在puerts项目组该管的范围内了。

**Comment by jun7th** [comment]
> https://github.com/zombieyang/puerts_unity_webgl_demo
> 之前做过一个初步的。最近重点在于优化性能所以没有继续，你有需要可以在这个基础上先弄。

感谢

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts_unity_webgl_demo
已经在实际运作中，关闭此issue，后续可在该项目中讨论。
