### ISSUE TITLE
希望能支援iOS模擬器

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#262]
https://developers.facebook.com/docs/ios/create-a-simulator-build/
臉書需要開發者提供iOS模擬器版本，才能審核。希望puerts能夠支援iOS模擬器。

**Comment by chexiongsheng** [comment]
unity不支持模拟器plugins：https://answers.unity.com/questions/768959/why-are-unity-plugins-disabled-on-the-ios-simulato.html

**Comment by h3902340** [comment]
後來我們臉書審核已通過，可以透過其他方式審核。將app過審後，給臉書promo code即可。結案。
