### ISSUE TITLE
[Unity]生成绑定C# Wrap代码不像XLua那样可以自动过滤被标记Obsolete属性的内容

### ISSUE THREAD

**Issue by 3wz** [Tencent/puerts#267]
虽然在puerts_unity_demo工程里发现了PuertsConfig这个配置，里面相当于自己写了个手动过滤的方法，但是感觉还是XLua那个Generate写的更周全一些。建议把XLua里的一些Generate代码参考移植到Puerts里的Generate中。

**Comment by throw-out** [comment]
puerts灵活性更高, 可以自己实现过滤.  
比如: 想要过滤过时的方法, 只需要以下代码:
![image](https://user-images.githubusercontent.com/45587825/119923627-9331fa80-bfa4-11eb-8340-5089a69f9ff5.png)

**Comment by 3wz** [comment]
就是一些常用默认的感觉还是内置到里面会更合适 一些吧，特殊的再自定义过滤方法

**Comment by 3wz** [comment]
另外如果整个类被标记Obsolete了咋整，这个是只能过滤废弃方法的吧

**Comment by chexiongsheng** [comment]
整个类被标记Obsolete了，你本来就不该从白名单返回。
Filter是过滤白名单的类里头的成员。
基于Filter可以扩展出任意的过滤效果，比如 @throw-out 扩展出来的blacklist：https://github.com/chexiongsheng/puerts_unity_demo/blob/master/Assets/Examples/Editor/PuertsFilter.cs
puerts的理念是核心只提供易于扩展的一些机制，其它的由周边组件和框架来实现。

**Comment by 3wz** [comment]
嗯，我是直接指定的程序集，现在我是直接把Obsolete检测放到遍历程序集那块逻辑了。那就建议把这个检测在那个demo工程里的PuertsConfig也加一下吧，那个里面我看就指定了很多排除类，但是Obsolete类的加个判断处理就省的指定了不是。
