### ISSUE TITLE
【Unreal】ts使用第三方插件(例如:tslog)会报错，无法使用

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#269]
目前我导入tslog插件无法使用
tslog项目插件路径:https://github.com/fullstack-build/tslog
npm安装命令行:npm install tslog
安装目录:
![install_path](https://user-images.githubusercontent.com/18215765/119954547-ac9d6b80-bfd1-11eb-87e5-2a14c97cd2b0.png)
工程报错：
![ts_error_1](https://user-images.githubusercontent.com/18215765/119954632-c3dc5900-bfd1-11eb-9a4d-afcc8dd70411.png)
![tslog_error_2](https://user-images.githubusercontent.com/18215765/119954639-c63eb300-bfd1-11eb-94d6-604bfb262b10.png)
ts里使用插件:
![tslog_use](https://user-images.githubusercontent.com/18215765/119954748-e53d4500-bfd1-11eb-94f9-024f102ea68e.png)

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/blob/master/doc/faq.md#npm%E4%B8%8A%E6%89%80%E6%9C%89%E5%8C%85%E9%83%BD%E5%8F%AF%E7%94%A8%E4%B9%88
