### ISSUE TITLE
[Unity]当类以私有方式实现接口方法的时候，生成的Index.d.ts报错对应类缺少对应接口实现方法

### ISSUE THREAD

**Issue by 3wz** [Tencent/puerts#270]
先解释一下私有方式实现接口的意思：
例如子类实现IDisposable里的Dispose的方法的时候，可以使用void IDisposable.Dispose()这种方式实现接口，但是此时实现的接口方法变成了私有了，Generate里获取类方法其中一个过滤条件是Public，很显然上面那种实现方式就直接把方法过滤没了。然后我又指定生成IDisposable的wrap文件，index.d.ts把接口的方法都列出来了，但是以上面私有方式实现接口的子类则提示报错：类型 "xxxx" 中缺少属性 "Dispose"，但类型 "IDisposable" 中需要该属性。

测试例子：typeof(UnityEngine.TextGenerator)，typeof(IDisposable)
加上这俩导出类就可以复现问题。

**Comment by zombieyang** [comment]
`TextGenerator`的`Dispose()`并不是私有的，只是需要通过`(IDisposable)tg.Dispose`的方式调用。这个在c#称之为显式接口实现。
需要点时间实现方案，预计会在稍晚的版本处理。目前你可以先手动删掉d.ts里的implements语句用着。

**Comment by zombieyang** [comment]
采用群里梦晓的光的方案，暂时修复了index.d.ts的报错。https://github.com/Tencent/puerts/commit/bd6ddec9de54beb81868d6e2123dfbc26a9c4b9d。

但TS目前还无法调用类似TextGenerator.Dispose的方法。后续开issue #291 跟进。

**Comment by 3wz** [comment]
嗯嗯了解了，我现在是临时屏蔽生成接口的方法和属性来解决报错，反正派生类里有定义，接口的方法和字段不生成也不碍事。

**Comment by zombieyang** [comment]
@3wz 修复了dts生成，试试

还不支持从ts调用这类方法，#291 跟进
