### ISSUE TITLE
 (unreal)蒙太奇中调用AnimNofityState问题

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#271]
https://github.com/Tencent/puerts/issues/266
现在是能调用了，但是不能实时的修改TS代码，修改了有时候能调用到，有时候又调用不到。当能调用的时候报这个错误
`Puerts: Error: (0x0000020EC9B41510) call JumpSectionNS_C::Received_NotifyBegin of 0000020EC9AD7D80 fail: can not find Binded JavaScript Object`

**Comment by CasonCaly** [comment]
有时候重启了，也不生效

**Comment by chexiongsheng** [comment]
重启了或者修改代码不生效是原来的逻辑没改完整。
而can not find Binded JavaScript Object是因为重新运行有个虚拟机重启，但蒙太奇创建AnimNofityState后，就一直使用，不会因为新场景而重新创建，而重启虚拟机后没重新绑定该对象导致的
