### ISSUE TITLE
[Unity]生成的index.d.ts语法错误

### ISSUE THREAD

**Issue by zhaozhantao** [Tencent/puerts#272]
unity 2020.3.2f1c1 
UnityEngine.ArticulationReducedSpace里面有个结构体：

public struct <x>e__FixedBuffer
{
            public float FixedElementField;
}

然后index.d.ts不认识<x>这种东西

**Comment by zhaozhantao** [comment]
是《x》e__FixedBuffer，

**Comment by zombieyang** [comment]
index.d.ts不认识的话，报的错具体是什么？
如果不好描述的话，方便传个能复现问题的小repository否

**Comment by icynare** [comment]
把<x>删掉就好了

**Comment by icynare** [comment]
把<x>删掉就好了

**Comment by benloong** [comment]
@zombieyang   https://github.com/chexiongsheng/puerts_unity_demo 这个工程，unity 2020.3.10下会报错。
