### ISSUE TITLE
生成的index.d.ts语法错误，addressable相关类

### ISSUE THREAD

**Issue by zhaozhantao** [Tencent/puerts#273]
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle

**Comment by zhaozhantao** [comment]
该文件里有一个public static implicit operator AsyncOperationHandle(AsyncOperationHandle<TObject> obj);

导出index.d.ts后，说静态方法on_implicit不能使用TObject

**Comment by zombieyang** [comment]
和 #272 一起处理
