### ISSUE TITLE
【Unreal】自动绑定模式TSoftObjectPtr类型的成员变量无法输出

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#276]
类型为UE.TSoftObjectPtr<T>无法使用
ts：
![TSoftObject1](https://user-images.githubusercontent.com/18215765/120192156-6bb18b00-c24d-11eb-8df9-52dad6866cde.png)

报错：
![TSoftObject12](https://user-images.githubusercontent.com/18215765/120192283-90a5fe00-c24d-11eb-980e-17b270ec7ea6.png)

**Comment by chexiongsheng** [comment]
文档中没有都是不支持：https://github.com/Tencent/puerts/blob/master/doc/unreal/manual.md#%E8%87%AA%E5%8A%A8%E7%BB%91%E5%AE%9A%E6%A8%A1%E5%BC%8F%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B

**Comment by chexiongsheng** [comment]
不过加上更友好的提示吧
