### ISSUE TITLE
v8升到9.1后编译不过

### ISSUE THREAD

**Issue by wzlsh** [Tencent/puerts#278]
v8升级后头文件有变化，插件里用到了一些之前deprecated的接口没有了

**Comment by chexiongsheng** [comment]
还涉及了quickjs版本的调整，所以先不改。
你为啥要升级呢？8.4也是nodejs最新lts所用的版本。

**Comment by wzlsh** [comment]
没有 只是看到release里放了一个9.1的版本 试试 那就不升了
