### ISSUE TITLE
[UE4.自动绑定模式] 更改蓝图类，导致编辑器崩溃

### ISSUE THREAD

**Issue by MrBaoquan** [Tencent/puerts#282]
[自动绑定模式]
复现案例:
蓝图MainPlayer继承TS类 TS_Player
更改 MainPlayer 的任意函数实现,  在TS代码中 通过 调用 (UE.GameplayStatics.GetPlayerPawn as UE.MainPlayer_C).SomeMethod 蓝图方法，编辑器就会崩溃
独立窗口运行以及打包后可以正常运行,**仅在编辑器下会出现这个问题**

![image](https://user-images.githubusercontent.com/36908656/120428125-ac241c80-c3a5-11eb-8cb7-66a9ba61e490.png)

![image](https://user-images.githubusercontent.com/36908656/120428190-cc53db80-c3a5-11eb-9c81-c0e3cff69d58.png)

_Originally posted by @MrBaoquan in https://github.com/Tencent/puerts/issues/277#issuecomment-852735012_

**Comment by chexiongsheng** [comment]
UE.GameplayStatics.GetPlayerPawn as UE.MainPlayer_C是啥？
GetPlayerPawn看上去是一个函数，MainPlayer_C是一个类

**Comment by chexiongsheng** [comment]
要不你搞个最小重现例子吧

**Comment by chexiongsheng** [comment]
像这种明确而简单的重现步骤，就容易定位：https://github.com/Tencent/puerts/issues/280

**Comment by chexiongsheng** [comment]
为什么关闭了？是解决了么？
