### ISSUE TITLE
[Unity]结构体的构造代码生成冗余

### ISSUE THREAD

**Issue by chinagzcp** [Tencent/puerts#283]
原始代码如下：
![image](https://user-images.githubusercontent.com/13399635/120433159-78e58b80-c3ad-11eb-8bf7-f7b17c6ee180.png)
生成代码如下：
![image](https://user-images.githubusercontent.com/13399635/120433246-94e92d00-c3ad-11eb-9b43-2e08f3926588.png)
经断点发现：
![image](https://user-images.githubusercontent.com/13399635/120433493-df6aa980-c3ad-11eb-980d-05925b1fcd03.png)
重复添加了无参构造
![image](https://user-images.githubusercontent.com/13399635/120433533-ed202f00-c3ad-11eb-9987-c48228001f19.png)

**Comment by zombieyang** [comment]
问题确认的话可以直接提PR

**Comment by zombieyang** [comment]
#285 终于反应过来了。这是个默认参数的问题
