### ISSUE TITLE
【Unreal】自动模式下，删除JavaScript下自己写的文件夹文件，重新打开ue编辑器，重新生成时，会报错，

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#288]
1. 平常使用正常，就是重新全部删除了(JavaScript下自己写的文件夹文件)，重新打开编辑器会报错，第二次打开就又好好的了，只有第一次重新删除文件才会出现

报错内容：
![error1](https://user-images.githubusercontent.com/18215765/120744225-1adfb200-c52d-11eb-8811-e0d29d73058b.png)

2. 继承关系:

![Entity](https://user-images.githubusercontent.com/18215765/120744397-7873fe80-c52d-11eb-994f-8c36a8b46c34.png)
![Goods](https://user-images.githubusercontent.com/18215765/120744405-7c078580-c52d-11eb-91d3-b78bf7d09d22.png)
![dr](https://user-images.githubusercontent.com/18215765/120744413-7e69df80-c52d-11eb-8157-854ef92a89e7.png)

3. 这个报错是要在类里面加构造函数才可以是吗？

![error4](https://user-images.githubusercontent.com/18215765/120744457-a22d2580-c52d-11eb-955a-e58f283d426c.png)

4. 像Entity继承的是UE.Object，这样的我可以在ts声明为抽象类嘛？

![image](https://user-images.githubusercontent.com/18215765/120744673-1962b980-c52e-11eb-8640-fbd8ad1e8fcd.png)

**Comment by chexiongsheng** [comment]
怎么感觉你玩脱了。。
ts生成蓝图，只是让你在必要情况下使用，比如你必须接收Tick，声明周期之类的回调，并且这类回调只提供override的方式。
其它走ts内部即可，不必凡事都在蓝图那走一遍，每个ts都得继承自引擎类。

**Comment by chexiongsheng** [comment]
不过你反馈的也是问题。
删了全部代码后报错，是因为目前的处理逻辑是一个个文件的分析ts，生成对应的js以及蓝图。而蓝图加载会加载对应的js，但其依赖的ts还没分析到，所以没生成，所以没找到。
这种情况可以通过先来一次全量的js生成来解决

**Comment by zhang357622852** [comment]
> 怎么感觉你玩脱了。。
> ts生成蓝图，只是让你在必要情况下使用，比如你必须接收Tick，声明周期之类的回调，并且这类回调只提供override的方式。
> 其它走ts内部即可，不必凡事都在蓝图那走一遍，每个ts都得继承自引擎类。

Entity类生成蓝图，是因为打算项目ts和蓝图混用，有的类就定义为生成蓝图了，而有的类只是ts用的话，就走ts自己的一套，不生成蓝图也不继承UE的类

**Comment by zhang357622852** [comment]
> 怎么感觉你玩脱了。。
> ts生成蓝图，只是让你在必要情况下使用，比如你必须接收Tick，声明周期之类的回调，并且这类回调只提供override的方式。
> 其它走ts内部即可，不必凡事都在蓝图那走一遍，每个ts都得继承

**Comment by zhang357622852** [comment]
> 不过你反馈的也是问题。
> 删了全部代码后报错，是因为目前的处理逻辑是一个个文件的分析ts，生成对应的js以及蓝图。而蓝图加载会加载对应的js，但其依赖的ts还没分析到，所以没生成，所以没找到。
> 这种情况可以通过先来一次全量的js生成来解决

嗯，试了先用tsc生成所有js，在打开项目，没问题，可以，

**Comment by zhang357622852** [comment]
Entity类是打算蓝图也能用，有的业务是写在蓝图里的，需要用到一些类，这些类就生成蓝图，而有的类只是ts用的话，就走ts自己的一套，不生成蓝图也不继承UE的类


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/puerts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/puerts] 【Unreal】自动模式下，删除JavaScript下自己写的文件夹文件，重新打开ue编辑器，重新生成时，会报错， (#288)





 
怎么感觉你玩脱了。。
 ts生成蓝图，只是让你在必要情况下使用，比如你必须接收Tick，声明周期之类的回调，并且这类回调只提供override的方式。
 其它走ts内部即可，不必凡事都在蓝图那走一遍，每个ts都得继承自引擎类。
