### ISSUE TITLE
[unity] GetComponent 返回结果异常

### ISSUE THREAD

**Issue by doupihule** [Tencent/puerts#293]
版本:master, tag:809c525e620a632143d5a1bc119e8bc83ee9a946
问题描述:
在ts端, 如果某个gameobject没有CanvasGroup这个组件, 调用下面这个接口的时候返回的是"null"字符串.
var rt = this.__cobject.GetComponent($typeof(UnityEngine.CanvasGroup));
log(rt =="null");   打印的结果是true;
但是 同一个对象, 
var rt2= this.__cobject.GetComponent($typeof(UnityEngine.UI.Image)); 
rt2 == null 结果是true. 
rt2  =="null"  是false.
其中 __cobject 是GameObject对象.

现在目前已知只有CanvasGroup返回的是null字符串. 其他组件是真null. 不确定是否有遗漏.

**Comment by chexiongsheng** [comment]
看faq：https://github.com/Tencent/puerts/blob/master/doc/unity/faq.md#getcomponent%E5%9C%A8cs%E4%B8%BAnull%E4%BD%86%E5%9C%A8js%E8%B0%83%E7%94%A8%E5%8D%B4%E4%B8%8D%E4%B8%BAnull%E4%B8%BA%E4%BB%80%E4%B9%88

**Comment by doupihule** [comment]
好的 感谢!
