### ISSUE TITLE
[unity]照着 faq 处理Source Map 提示  can not find source-map-support

### ISSUE THREAD

**Issue by lsx1994** [Tencent/puerts#296]
node_modules已经安装了，还是找不到。
请问有可运行的示例demo吗？ 不胜感激！

**Comment by zombieyang** [comment]
source-map-support是一个node_modules，所以还需要使用webpack把它打包出来，或者把里面的js复制出来命名为.txt使用。

**Comment by lsx1994** [comment]
> source-map-support是一个node_modules，所以还需要使用webpack把它打包出来，或者把里面的js复制出来命名为.txt使用。

感谢回复，命名为txt使用是什么意思呢？在js代码中，可以require 一个txt文件吗

**Comment by zombieyang** [comment]
是的，参见example里typescript那一块。

**Comment by lsx1994** [comment]
> 是的，参见example里typescript那一块。

非常感谢！

**Comment by Joycraft** [comment]
> > source-map-support是一个node_modules，所以还需要使用webpack把它打包出来，或者把里面的js复制出来命名为.txt使用。
> 
> 感谢回复，命名为txt使用是什么意思呢？在js代码中，可以require 一个txt文件吗

打包这个文件对于新手可能比较麻烦, 你可以用这个我导出的 [https://gist.github.com/Joycraft/1388fcfd1f768fcaf04e16f0e00f489b](url)

**Comment by lsx1994** [comment]
> > > source-map-support是一个node_modules，所以还需要使用webpack把它打包出来，或者把里面的js复制出来命名为.txt使用。
> > 
> > 
> > 感谢回复，命名为txt使用是什么意思呢？在js代码中，可以require 一个txt文件吗
> 
> 打包这个文件对于新手可能比较麻烦, 你可以用这个我导出的 https://gist.github.com/Joycraft/1388fcfd1f768fcaf04e16f0e00f489b
> 
> 下载这个文件, 放到Assets/Resources里面, 然后把faq里面的代码抄到一个js.txt文件里面, jsenv启动的时候require一下就完事了

谢谢， 刚接触这一块，对我帮助很大。

**Comment by Joycraft** [comment]
> > > > source-map-support是一个node_modules，所以还需要使用webpack把它打包出来，或者把里面的js复制出来命名为.txt使用。
> > > 
> > > 
> > > 感谢回复，命名为txt使用是什么意思呢？在js代码中，可以require 一个txt文件吗
> > 
> > 
> > 打包这个文件对于新手可能比较麻烦, 你可以用这个我导出的 https://gist.github.com/Joycraft/1388fcfd1f768fcaf04e16f0e00f489b
> > 下载这个文件, 放到Assets/Resources里面, 然后把faq里面的代码抄到一个js.txt文件里面, jsenv启动的时候require一下就完事了
> 
> 谢谢， 刚接触这一块，对我帮助很大。
> 这个webpack是把模块所依赖的文件全部打包成一个文件吗？
> 我最早尝试过直接复制node_modules中的source-map-support，但是缺少很多依赖， 应该就是少了这个打包步骤。

这个只是用npm install source-map-support 然后到node_modules里面用ncc打包成单文件而已, 因为测试可行, 我自己也在用, 所以顺便发出来
