### ISSUE TITLE
是否能支持C#拓展方法

### ISSUE THREAD

**Issue by dong52008** [Tencent/puerts#30]
未来是否能通过优化生成index.d.ts来支持C#的拓展方法。Unity中DOTween和一些自己写的拓展方法，目前不好调用。

**Comment by chexiongsheng** [comment]
考虑下要怎么支持

**Comment by Geequlim** [comment]
JS 中建议使用 tween.js 减少跨语言调用
https://github.com/tweenjs/tween.js

**Comment by dong52008** [comment]
> JS 中建议使用 tween.js 减少跨语言调用
> https://github.com/tweenjs/tween.js

用tween.js的话，跨语言调用还是会有吧，比如要在onupdate中吧参数回传给C#

**Comment by Joycraft** [comment]
其实也不是不能支持, 但是得实现生成器规则, 需要检索所有Assembly里面的静态类, 然后检查第一个参数, 再绑定到类里面, 因为C#里面是能执行的, 至于这个生成器谁去写, 什么时候才能看到写好的就不好说了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/puerts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午4:15
收件人:&nbsp;"Tencent/puerts"<puerts@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/puerts] 是否能支持C#拓展方法 (#30)





 
Closed #30.

**Comment by chexiongsheng** [comment]
> 其实也不是不能支持, 但是得实现生成器规则, 需要检索所有Assembly里面的静态类, 然后检查第一个参数, 再绑定到类里面, 因为C#里面是能执行的, 至于这个生成器谁去写, 什么时候才能看到写好的就不好说了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/puerts" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月22日(星期四) 下午4:15 收件人:&nbsp;"Tencent/puerts"<puerts@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/puerts] 是否能支持C#拓展方法 (#30) Closed #30. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已经支持了啊，看demo，有示例
