### ISSUE TITLE
[Unity] DevTools中不能执行console输入的js代码

### ISSUE THREAD

**Issue by benloong** [Tencent/puerts#304]
DevTools连接成功后，内存快照，Profiler 功能正常，但是console不能输入代码执行只有输出。

![image](https://user-images.githubusercontent.com/1171605/121483870-3ea96900-ca01-11eb-9384-0e3a32eb7f1d.png)

没有执行js代码

**Comment by zombieyang** [comment]
已经无法复现了。如果能复现可重新打开并告知我版本。
