### ISSUE TITLE
(unreal)UExtensionMethods扩展类方法时直接使用this调用扩展方法报错

### ISSUE THREAD

**Issue by BoringMing** [Tencent/puerts#307]
报错：
![image](https://user-images.githubusercontent.com/27050014/121625053-4d495c00-caa5-11eb-9065-a9ce5e5f401b.png)
ts调用：
![image](https://user-images.githubusercontent.com/27050014/121625147-78cc4680-caa5-11eb-828b-744e6ba8ff67.png)
C++中的扩展方法：
![image](https://user-images.githubusercontent.com/27050014/121625196-94cfe800-caa5-11eb-8333-9a7b653dac72.png)

只有在打开编辑器后第一次启动游戏会有报错，使用
![image](https://user-images.githubusercontent.com/27050014/121625362-eb3d2680-caa5-11eb-832c-8b98de5a796b.png)
这种方式调用就不报错，是使用this访问有问题吗？

**Comment by chexiongsheng** [comment]
看faq。

**Comment by BoringMing** [comment]
> 看faq。

是puerts模块启动时间问题吗，那为什么用UE.UserWidgetExtensionMethods.GetWidgetFromName这种方式调用就没报错呢

**Comment by chexiongsheng** [comment]
是启动时间问题，按faq做就可以了
