### ISSUE TITLE
[unity]建议优化C# Wrap层中ArgumentHelper构造函数中非必要的JsValueType获取，用到时再获取，减少与c++胶水层的交互次数

### ISSUE THREAD

**Issue by liuwjchinal** [Tencent/puerts#316]
PuertsDLL.GetJsValueType性能热点：
https://github.com/Tencent/puerts/blob/master/unity/Assets/Puerts/Src/ArgumentHelper.cs#L26

TestCase：2w次的Ts脚本调用C#导出F_SetBuffByIndex调用，三个参数
![image](https://user-images.githubusercontent.com/23007669/122350779-192bda80-cf80-11eb-85f2-758bcff710f3.png)

真机Profiler火焰图：
![企业微信截图_16237509963453](https://user-images.githubusercontent.com/23007669/122350284-ab7fae80-cf7f-11eb-826f-b103c250fe58.png)

改成用到时再获取(testcase中不需要用到JsValueType)后性能对比：
![企业微信截图_16237510311830](https://user-images.githubusercontent.com/23007669/122350576-ebdf2c80-cf7f-11eb-93c4-cee28a82c4a3.png)

优化后，PuertsDLL.GetJsValueType性能热点消失

**Comment by zombieyang** [comment]
已合入，JSValueType是给反射模式使用的。代码生成的情况下确实没有必要计算。
