### ISSUE TITLE
[Unity] C#调用TS的函数时如何传递参数？

### ISSUE THREAD

**Issue by lsx1994** [Tencent/puerts#320]
demo里面只看到纯字符串的调用， 我想传递 C#的对象给TS， 该如何做？

比如网络层在C#，解析了一个消息，把这个数据对象传递给TS的网络接收函数，不额外产生GC。

**Comment by chexiongsheng** [comment]
https://github.com/chexiongsheng/puerts_unity_demo/blob/master/TsProj/QuickStart.ts

**Comment by lsx1994** [comment]
> https://github.com/chexiongsheng/puerts_unity_demo/blob/master/TsProj/QuickStart.ts

你好，这个我之前看过，但是没发现我想要的， 或者是我没理解到， 能说说是哪一个部分吗？
我使用的是sproto协议， 在C#中解析后会得到 {key:{key:data...}, key:data...} 这种多层嵌套的数据， 传给js层我想保留这种结构， 转成json的话开销太大了。 如果不能传输对象，那我只能把二进制数据发给js自己解析了。

**Comment by chexiongsheng** [comment]
直接传对象就可以了。在ts可以直接访问

**Comment by lsx1994** [comment]
> 直接传对象就可以了。在ts可以直接访问

 好的， 非常感谢。

**Comment by gejiyu** [comment]
可以使用sproto的js解析 解析成一个js对象 更加方便使用

**Comment by lsx1994** [comment]
> 可以使用sproto的js解析 解析成一个js对象 更加方便使用

因为C#代码也有业务逻辑， 所以我想统一网络模块到C#， TS只用来写UI系统， 有一些性能损耗无所谓了
