### ISSUE TITLE
[Unreal]频繁切换地图后关闭游戏报错

### ISSUE THREAD

**Issue by BoringMing** [Tencent/puerts#329]
LoginId:7f4b10d048854ff40ab580986c7eb601
EpicAccountId:c399cd4807e44608ae89a1816af9023a

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

UE4Editor_JsEnv!v8::internal::GlobalHandles::NodeSpace<v8::internal::GlobalHandles::Node>::Release()
UE4Editor_JsEnv!puerts::FJsEnvImpl::~FJsEnvImpl() [F:\HMS_git\Plugins\Puerts\Source\JsEnv\Private\JsEnvImpl.cpp:379]
UE4Editor_JsEnv!puerts::FJsEnvImpl::`scalar deleting destructor'()
UE4Editor_Puerts!FPuertsModule::`scalar deleting destructor'()
UE4Editor_Core
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

使用OpenLevel(by Name)蓝图节点切换
![image](https://user-images.githubusercontent.com/27050014/123436860-a961c380-d601-11eb-9a46-c646aed3a9dc.png)

概率出现

**Comment by chexiongsheng** [comment]
看上去和这个commit解决的问题一样：https://github.com/Tencent/puerts/commit/336c17c3e92f9a7418b8257c913388fb6d8c12ee
你看下你的版本有没更新到这commit。

**Comment by BoringMing** [comment]
更新后解决了

**Comment by VegetableWithChicken** [comment]
你这个，继承自GameInstancez之后，然后通过OpenLevel，加载地图，会导致，一直启动当前地图么

**Comment by BoringMing** [comment]
> 你这个，继承自GameInstancez之后，然后通过OpenLevel，加载地图，会导致，一直启动当前地图么

没有发现，这个也是很久之前的问题了
