### ISSUE TITLE
EWidgetClipping 生成.d.ts类型定义错误

### ISSUE THREAD

**Issue by FishOrBear** [Tencent/puerts#330]
```
export type EWidgetClipping = "Inherit" | "ClipToBounds" | "ClipToBoundsWithoutIntersecting" | "ClipToBoundsAlways" | "OnDemand" | "EWidgetClipping_MAX";

```

实际的类型定义为:enum class EWidgetClipping : uint8

此时传入字符串是不正确的,应该传入number

**Comment by chexiongsheng** [comment]
你自己魔改的？还是哪里下载的版本？
生成代码的逻辑里头根本没生成这种声明的地方：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp

**Comment by chexiongsheng** [comment]
看了下记录，你这种生成是差不多一年前的版本。后面都不知道多少个commit了。

**Comment by FishOrBear** [comment]
确实我删除以前生成的就行了
