### ISSUE TITLE
require相对路径，读取到的类的静态属性为null

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#34]
在Unity C#内，执行JsEnv.Eval("require('ClassA')")，将ClassA.js内的ClassA的静态属性给与非null的值。
然后再执行JsEnv.Eval("require('ClassB')")。ClassB.js内有require('../../ClassA')，require内的路径对应到ClassB.js与ClassA.js实质上的相对路径。但是此时require出来的ClassA的静态属性为null。
原因可能为require('ClassA')与require('../../ClassA')被认定是require不同的档案。

**Comment by chexiongsheng** [comment]
看了下你的demo，感觉是loader那实现得有问题。只要文件名是ok的，不管路径是啥，都返回true。
比如ClassB，它在子目录下，本来就不应该直接通过ClassB能够拿到。
而ClassA，传了个../../ClassA.js，你也返回能获取到。

**Comment by h3902340** [comment]
已经找到解法。在tsconfig.json的compilerOptions内，加入"baseUrl": "src"。这样所有模块都能从src底下开始寻找，不需要使用相对路径，也就没有此问题了。
