### ISSUE TITLE
[unity] c#函数有泛型参数，无法导出函数给ts用

### ISSUE THREAD

**Issue by YellowWang** [Tencent/puerts#343]
例如用Addressables，里面的LoadAssetAsync函数就是有泛型，导不出来，ts没办法加载资源

**Comment by zombieyang** [comment]
https://github.com/chexiongsheng/puerts_unity_demo/blob/master/Assets/Examples/05_Typescript/Resources/QuickStart.js.txt#L50
这个有看么，是否是没有加$generic而已

**Comment by YellowWang** [comment]
> https://github.com/chexiongsheng/puerts_unity_demo/blob/master/Assets/Examples/05_Typescript/Resources/QuickStart.js.txt#L50
> 这个有看么，是否是没有加$generic而已

不是，是函数是有泛型参数的，例如GetComponent<type> 这样的函数，在index.d.ts里面根本没有

**Comment by zombieyang** [comment]
还不是很明白，官方demo的index.d.ts里就有GetComponent的。

还是说你是想表达index.d.ts里的ts函数没有泛型？

**Comment by chexiongsheng** [comment]
一般没有生成就代表不支持。需要封装成非泛型版本给ts调用。

**Comment by YellowWang** [comment]
明白，那我就自己封装一下
