### ISSUE TITLE
可以增加三方库吗，protobuf这种？

### ISSUE THREAD

**Issue by lanyantao** [Tencent/puerts#35]
可以增加三方库吗，protobuf这种？

**Comment by chexiongsheng** [comment]
google就有官方的js支持，好像是纯js的，你直接拿过来用就行

**Comment by lanyantao** [comment]
> google就有官方的js支持，好像是纯js的，你直接拿过来用就行

谢作者回复，我的意思是会想xlua那样可以添加三方库进去吗，不光是protobuf，当然这个可能是用的最多的，另外您的意思是否是，其他的比如json库这种也可以找个js可以支持的放进去用就可以了，也不需要配置什么

**Comment by Geequlim** [comment]
可以使用npm仓库内的大量第三方库，也能直接使用符合commonjs规范的库，建议配合webpack之类的编译工具使用。
这个issue可以关了。

**Comment by chexiongsheng** [comment]
> > google就有官方的js支持，好像是纯js的，你直接拿过来用就行
> 
> 谢作者回复，我的意思是会想xlua那样可以添加三方库进去吗，不光是protobuf，当然这个可能是用的最多的，另外您的意思是否是，其他的比如json库这种也可以找个js可以支持的放进去用就可以了，也不需要配置什么

json库？你开玩笑么？json就是JavaScript Object Notation，本来就是js的格式，内部直接支持。
