### ISSUE TITLE
[Unity]导出wrap代码设置action 输出为null

### ISSUE THREAD

**Issue by chenanbao** [Tencent/puerts#356]
工程用的https://github.com/Tencent/puerts/tree/master/unity 最新的
例子用的https://github.com/chexiongsheng/puerts_unity_demo/tree/master/Assets/Examples/04_JsBehaviour

ExamplesCfg 里添加 typeof(PuertsTest.JsBehaviour), 生成wrap代码。Rotate.js 打印 console.log(this.bindTo.JsUpdate)， 输出是null。如果不生成wrap代码，可以正常输出

**Comment by zombieyang** [comment]
先回滚了相关代码 #357
