### ISSUE TITLE
Unity 断点调试时执行表达式会崩溃

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#36]
复现方式
- 启动任意项目
- 使用 VSCode 调试器连接 puerts 的 V8 调试器
- 按暂定键或通过 `debugger` 进入断点
- 在VSCode 中切换到调试窗口，打开 `调试控制台`
- 在控制台内输入任意 JavaScript 表达式
- 如未复现，重复上一步，手动输入如 `globalThis.puerts` 之类的即可复现

**Comment by Geequlim** [comment]
在调试器的监视面板添加监视同样会出现
![image](https://user-images.githubusercontent.com/6964556/93449987-00669980-f908-11ea-9d96-b83c29a5031e.png)

**Comment by chexiongsheng** [comment]
然而我试了并不会，unity和unreal版本都没这问题。

**Comment by Geequlim** [comment]
再测试了一下发现是个特定的对象，只要监视它就会出现。
等我缩小可复现情况上传一个项目。

**Comment by Geequlim** [comment]
记录一下： 由于JS中存在循环引用的属性导致调试展开属性时死循环
```js
get xxx() {  return this.xxx; }
```
