### ISSUE TITLE
[Unreal]Typescript是否可以让变量属性在编辑器公开可编辑实例

### ISSUE THREAD

**Issue by hefujie1988** [Tencent/puerts#363]
怎么在Typescript里面定义可以在编辑器公开可编辑的属性变量呢，每次保存热更新之后都全部变成不公开的
![image](https://user-images.githubusercontent.com/26532399/127090286-c55e3818-9777-4b93-aaf3-cb8aee9f7bc3.png)

**Comment by chexiongsheng** [comment]
最新版本已经支持加个@edit_on_instance()修饰器
