### ISSUE TITLE
[Unity]请问是否可以引入rxjs库？（Unity + Typescript开发环境）

### ISSUE THREAD

**Issue by cpzhang** [Tencent/puerts#372]
你好，引入rxjs之后，在编辑器允许时，报错，无法找到的module
请问如何才可以支持？

**Comment by chexiongsheng** [comment]
放到合适的位置，require就可以了。
比较特殊的是unity不认js后缀的文件。
要么你改名扔进去，像这样：https://github.com/chexiongsheng/puerts_unity_demo/blob/master/TsProj/copyJsFile.js
要么你实现自己的loader。
建议后者，因为默认的loader只支持Resources目录，你最后总得实现一个。

**Comment by cpzhang** [comment]
好的，谢谢
