### ISSUE TITLE
How to use Coroutine

### ISSUE THREAD

**Issue by sekkit** [Tencent/puerts#376]
How to use coroutine ( startcoroutine/stopcoroutine ) feature with typescript in Unity?

**Comment by zombieyang** [comment]
Although there are some way to use coroutine in JS, we recommend to use async/await instead of coroutine.
If you stick to do that, you can upload your coroutine code here and we try to give you an example.

**Comment by sekkit** [comment]
> Although there are some way to use coroutine in JS, we recommend to use async/await instead of coroutine.
> If you stick to do that, you can upload your coroutine code here and we try to give you an example.

`
class Test: MonoBehaviour
{
     void Start() {
           StartCoroutine("hello");
    }

   IEnumerator hello()  
   {
        yield return new WaitForSeconds(1);
        UnityEngine.Debug.Log("hello");
   }
}
`

**Comment by zombieyang** [comment]
That's really simple.
You can do like this https://github.com/zombieyang/puerts_unity_demo/blob/master/Assets/Examples/04_JsBehaviour/Resources/rotate.js.txt#L9

**Comment by sekkit** [comment]
> That's really simple.
> You can do like this https://github.com/zombieyang/puerts_unity_demo/blob/master/Assets/Examples/04_JsBehaviour/Resources/rotate.js.txt#L9

Thx
