### ISSUE TITLE
RegisterFunction无法覆盖

### ISSUE THREAD

**Issue by chenanbao** [Tencent/puerts#379]
public class ClassTest
{

    public static void Init()
    {
        int typeId = PuertsTest.Test.jsEnv.GetTypeId(typeof(FuncTest));

        PuertsDLL.RegisterFunction(PuertsTest.Test.jsEnv.isolate, typeId, "SetArrayX", false, JsEnvCallbackWrap, PuertsTest.Test.jsEnv.Idx);
        Debug.Log("FuncTest.Init");
    }

    [MonoPInvokeCallback(typeof(V8FunctionCallback))]
    internal static void JsEnvCallbackWrap(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
    {
        Debug.Log("JsEnvCallbackWrap");
    }

}

public class FuncTest
{
    public void SetArrayX()
    {
        Debug.Log("SetArrayX");
    }
    public void SetArray()
    {
        Debug.Log("SetArray");
    }
}

namespace PuertsTest
{
    public class Test : MonoBehaviour
    {
        public static JsEnv jsEnv;

        void Start()
        {
            jsEnv = new JsEnv();
            ClassTest.Init();
            jsEnv.Eval(@"
                const CS = require('csharp');
                CS.UnityEngine.Debug.Log('cab');
                let f = new CS.FuncTest();
                f.SetArrayX();
            ");
        }

        private void Update()
        {
            jsEnv.Tick();
        }

        void OnDestroy()
        {
            jsEnv.Dispose();
        }
    }
}

导出FuncTest的wrap，不导出ClassTest，运行Test ，有时候输出SetArrayX，有时输出JsEnvCallbackWrap，不是确定的输出，目的是想覆盖掉FuncTest里的SetArrayX方法注册

**Comment by zombieyang** [comment]
如果只是想覆盖类函数，我觉得有个更好的方式可以实现，直接在JS里加上这行代码即可
`
CS.FuncTest.prototype.SetArrayX = function() { console.log('another SetArrayX') }
`
赋值过去的这个function也可以是另外一个csharp导出的函数，那应该就足以满足你的需求了。

**Comment by zombieyang** [comment]
如果这个办法能满足你需求的话，我就稍晚点再查这个问题

**Comment by chenanbao** [comment]
想在c#侧覆盖掉 ，目的c#重写ArrayBuffer的处理，C#侧 ArrayBuffer里Marshal.Copy性能 gc 不满足我们的需求

**Comment by zombieyang** [comment]
class ClassTest:
`
public static void Init()
{
    int typeId = PuertsTest.Test.jsEnv.GetTypeId(typeof(FuncTest));

    PuertsDLL.RegisterFunction(PuertsTest.Test.jsEnv.isolate, typeId, "SetArrayX_optimized", false, JsEnvCallbackWrap, PuertsTest.Test.jsEnv.Idx);
}
`
classTest:
`
    void Start()
    {
        jsEnv = new JsEnv();
        ClassTest.Init();
        jsEnv.Eval(@"
            const CS = require('csharp');
            CS.FuncTest.prototype.SetArrayX = CS.FuncTest.prototype.SetArrayX_change;
            let f = new CS.FuncTest();
            f.SetArrayX();
        ");
    }
`


我直接写了个V8代码测试，发现FunctionTemplate::Set就是无法产生覆盖效果的，unity为什么产生随机结果还不清楚。但上面这个写法应该满足你要求。
