### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by Justin-sky** [Tencent/puerts#38]
在某些情况下，比如接入flatbuffer,  flatbuffer不会被打包进js中，因此需要在Eval脚本前这样调用一下  jsEnv.ExecuteFile("puerts/flatbuffers.js");   , 为了不修改Puerts框架代码， 希望 ExecuteFile 这个方法声明为public , 或者框架中提供一个执行用户自定义文件的方法

**Comment by zombieyang** [comment]
更新：已有ExecuteModule
