### ISSUE TITLE
【Unreal】【需求】函数支持设置Call In Editor

### ISSUE THREAD

**Issue by huzhangyang** [Tencent/puerts#386]
![image](https://user-images.githubusercontent.com/5735704/128865607-fd076a93-f5b3-47be-9be5-4e7fc193ab3e.png)

如图，Call In Editor功能使得函数可以在Inspector下被调用，目前可以手动设置并生效，但会导致内部生成TRASHCLASS

希望可以在装饰器中以类似edit_on_instance()的方法设置

**Comment by chexiongsheng** [comment]
最新的这个PR应该能满足你的需求：https://github.com/Tencent/puerts/commit/8d937dcec217a255e2e6a7b4fb554f61bd56d2a4

**Comment by huzhangyang** [comment]
可以设置了，感谢
