### ISSUE TITLE
[unity][新手上路]如何声明C#类的声明给ts? 

### ISSUE THREAD

**Issue by kenkinky** [Tencent/puerts#387]
- 我在`demo`项目中的"Assets/Gen/Typing/csharp/"目录下, 仿照`index.d.ts`文件, 在路径下新建了一个`index2.d.ts`, 代码如下:
```ts
declare module 'csharp' {
    namespace kk {
        class log {
            public static fatal(content: string): void;
            public static error(content: string): void;
            public static warn(content: string): void;
            public static info(content: string): void;
            public static verbose(content: string): void;
        }
    }
}
```
在`TsProj`中没有效果: 找不到 namespace kk;

- 然后, 我修改模块名称也是不行的:
> declare module 'csharp' => declare module 'csharp2'

- 我直接把这段代码放入`index.d.ts`文件是可行的, 莫非, 这就是常规方案? 
- 因为我不想把自己敲的代码和已有的框架代码混在一起

**Comment by throw-out** [comment]
csharp module是puerts提供的访问C# types的模块(唯一), 而在ts中是不允许重复declare module.

要让C#类型导出到index.d.ts声明文件中, 请查阅手册文档配置类型:
https://github.com/Tencent/puerts/blob/master/doc/unity/manual.md#binding

然后在Unity中执行选项(如图):
![image](https://user-images.githubusercontent.com/45587825/129155241-3772d2e1-b6b4-49fc-aa85-f8ee8c3d8ca9.png)

选项说明:
-> Generate Code           \\生成静态wrap类, 并且生成index.d.ts声明文件
-> Generate index.d.ts     \\仅生成index.d.ts声明文件
-> Clear Generate Code   \\清空生成文件(Assets/Gen目录)

**Comment by throw-out** [comment]
你可以参照demo中的例子来配置:
https://github.com/chexiongsheng/puerts_unity_demo/blob/master/Assets/Examples/Editor/PuertsConfig.cs

**Comment by kenkinky** [comment]
好的, 谢谢大佬!

追问一下: 关于代码生成的文档在哪个位置? 我没有找到相关的信息, 是我看漏了?
