### ISSUE TITLE
[Unreal]Mac平台使用Xcode并开Address Sanitizer选项时异常

### ISSUE THREAD

**Issue by KaiQian** [Tencent/puerts#391]
如题，附上截图
<img width="1652" alt="{1A6CEBE8-4459-C227-2A6C-449EB954EBE2}" src="https://user-images.githubusercontent.com/9209140/129502893-56ff5573-22f8-41d0-8cf2-a59868849ac6.png">

**Comment by chexiongsheng** [comment]
HandleMapChanged由非主线程触发导致的。
简单的非主线程就跳过这逻辑好了。本来这逻辑也是防止人手动在编辑器下切地图，这场景下应该是主线程

**Comment by KaiQian** [comment]
#393
