### ISSUE TITLE
[Unity]加入TS代码后，Xcode中打包Build报错

### ISSUE THREAD

**Issue by CZyl1997** [Tencent/puerts#394]
部分报错信息
Ld /Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/tu/URP1021/URPproject/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Products/ReleaseForRunning-iphoneos -L/Users/tu/URP1021/URPproject/ios/Libraries -F/Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Products/ReleaseForRunning-iphoneos -filelist /Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -ObjC -framework CoreTelephony -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -weak_framework Metal -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/tu/Library/Developer/Xcode/DerivedData/Unity-iPhone-bplhidqhoxwpzohipxwekgdmfcau/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/tu/URP1021/URPproject/ios/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_PushArrayBufferForJSFunction", referenced from:
      _PuertsDLL_PushArrayBufferForJSFunction_mE18C120D1CDA766736AC1845D77FE713570FA447 in Assembly-CSharp21.o
      _SetValueToArgumentImpl_SetArrayBuffer_m88B5AD0807A474DABD3C53C2CBA523FF2DEA61CE in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_PushArrayBufferForJSFunction_mE18C120D1CDA766736AC1845D77FE713570FA447)
  "_SetArrayBufferToOutValue", referenced from:
      _PuertsDLL_SetArrayBufferToOutValue_mF1DEDBA32DFE5C189595F7ED4B3C07087E6215AA in Assembly-CSharp21.o
      _SetValueToByRefArgumentImpl_SetArrayBuffer_m2A631E178E262B3FC17E3017CC03F9F40EF34325 in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_SetArrayBufferToOutValue_mF1DEDBA32DFE5C189595F7ED4B3C07087E6215AA)
  "_ReturnArrayBuffer", referenced from:
      _PuertsDLL_ReturnArrayBuffer_m8B843EEA2E8124C1213CB01FBE227340575D963D in Assembly-CSharp21.o
      _SetValueToResultImpl_SetArrayBuffer_mAEEFBECEBA14A220032E6455E893B65764E02B43 in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_ReturnArrayBuffer_m8B843EEA2E8124C1213CB01FBE227340575D963D)
  "_SetLogCallback", referenced from:
      _PuertsDLL_SetLogCallback_m46727F64583ADF7E4968907987674379B4D10209 in Assembly-CSharp21.o
      _PuertsDLL_SetLogCallback_m58C64435F1E37333A0650798E17D2D48631ADB1B in Assembly-CSharp21.o
     (maybe you meant: Application_CUSTOM_SetLogCallbackDefined(unsigned char), _PuertsDLL_SetLogCallback_m46727F64583ADF7E4968907987674379B4D10209 , Register_UnityEngine_Application_SetLogCallbackDefined() , _PuertsDLL_SetLogCallback_m58C64435F1E37333A0650798E17D2D48631ADB1B , _PuertsDLL_SetLogCallback_m58C64435F1E37333A0650798E17D2D48631ADB1B_MetadataUsageId )
  "_PushJSObjectForJSFunction", referenced from:
      _PuertsDLL_PushJSObjectForJSFunction_m44CB1FD25D5BB02566A3D956D6374E0F72CF63F1 in Assembly-CSharp21.o
      _SetValueToArgumentImpl_SetJSObject_m039E1BF29A9C69D370D27039AFE2E89E2D76FD0F in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_PushJSObjectForJSFunction_m44CB1FD25D5BB02566A3D956D6374E0F72CF63F1)
  "_PushObjectForJSFunction", referenced from:
      _PuertsDLL_PushObjectForJSFunction_mDC6B74F2C3EF34D1501C523E0FF2EA40FA99C0FF in Assembly-CSharp21.o
      _SetValueToArgumentImpl_SetNativeObject_m2FE364017B47A0AFB05A7F1DBA4F5B83B467F90C in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_PushObjectForJSFunction_mDC6B74F2C3EF34D1501C523E0FF2EA40FA99C0FF)
  "_PushNumberForJSFunction", referenced from:
      _PuertsDLL_PushNumberForJSFunction_mCE53D6E77BED6896FBD9823FA2BDA16018993E26 in Assembly-CSharp21.o
      _SetValueToArgumentImpl_SetNumber_mBB900C6AFA3AF2BB981976585859BCEE3C170100 in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_PushNumberForJSFunction_mCE53D6E77BED6896FBD9823FA2BDA16018993E26)
  "_PushStringForJSFunction", referenced from:
      _PuertsDLL___PushStringForJSFunction_m21B02CCE3FC4E6B48570407CBEDCF8DACF2C1279 in Assembly-CSharp21.o
      _PuertsDLL_PushStringForJSFunction_mFE3AE669B100C2A65176AB30C37201D554CE5348 in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL___PushStringForJSFunction_m21B02CCE3FC4E6B48570407CBEDCF8DACF2C1279, _PuertsDLL_PushStringForJSFunction_mFE3AE669B100C2A65176AB30C37201D554CE5348 )
  "_PushBigIntForJSFunction", referenced from:
      _PuertsDLL_PushBigIntForJSFunction_m257BC102F0DE888353956EC57F4CAB4677CD87FC in Assembly-CSharp21.o
      _SetValueToArgumentImpl_SetBigInt_mB60633FEFA5CE75A9AAB60C1E570A8E55356BFFC in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_PushBigIntForJSFunction_m257BC102F0DE888353956EC57F4CAB4677CD87FC)
  "_PushBooleanForJSFunction", referenced from:
      _PuertsDLL_PushBooleanForJSFunction_mEBC03A4CD32E6A7B12FF1CEA7CD6743984EA3BA6 in Assembly-CSharp21.o
      _SetValueToArgumentImpl_SetBoolean_mCC451BB62E9B9E2C60FB704F1D6AC464F14F2FB1 in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_PushBooleanForJSFunction_mEBC03A4CD32E6A7B12FF1CEA7CD6743984EA3BA6)
  "_SetNullToOutValue", referenced from:
      _PuertsDLL_SetNullToOutValue_m0C7BBA8DB343C6CF36FE1F64B9065EE06072DB13 in Assembly-CSharp21.o
      _SetValueToByRefArgumentImpl_SetNull_mF6EEEABB05B37B2212C61796A028679A86E3B478 in Assembly-CSharp21.o
     (maybe you meant: _PuertsDLL_SetNullToOutValue_m0C7BBA8DB343C6CF36FE1F64B9065EE06072DB13)
  "_PushDateForJSFunction", referenced from:
      _PuertsDLL_PushDateForJSFunction_mCEB7383EF7D543908A1FB490C4E89DC0145C1A5C in Assembly-CSharp21.o
![Uploading 截屏2021-08-16 下午6.47.23.png…]()

**Comment by zombieyang** [comment]
看不到图，文字里只有一个warning?

**Comment by CZyl1997** [comment]
图片内容是报错信息，列几条如下：
Arm64 function not 4-byte aligned: _unwind_tester from ./ios/Libraries/libiPhone-lib.a(unwind_test_arm64.o)

Undefined symbol: _PushArrayBufferForJSFunction
Undefined symbol: _SetArrayBufferToOutValue
Undefined symbol: _ReturnArrayBuffer

**Comment by chexiongsheng** [comment]
ios的库没下载或者没提交吧？

**Comment by CZyl1997** [comment]
ios的库指的是什么？在没有加入TS代码前，能够正常打包到真机运行，加入TS代码Build报错。

ios库指的是终端lipo -info查看静态库吗？
lipo -info ./ios/Libraries/libiPhone-lib.a
Architectures in the fat file: ./ios/Libraries/libiPhone-lib.a are: arm64 armv7

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/releases/tag/Unity_Plugin_v1.0.16

**Comment by CZyl1997** [comment]
解压缩之后unity/assets中这两个文件：Plugins、Puerts。原来在工程中已经有了，替换之后还是有问题
![Uploading 截屏2021-08-17 下午7.25.53.png…]()

**Comment by chexiongsheng** [comment]
这个：https://github.com/Tencent/puerts/releases/download/Unity_Plugin_v1.0.16/Plugins_V8_ver11.tgz

**Comment by chexiongsheng** [comment]
你缺的是ios的plugins
要下载的是这个：https://github.com/Tencent/puerts/releases/download/Unity_Plugin_v1.0.16/Plugins_V8_ver11.tgz
这个并没有Puerts目录

**Comment by CZyl1997** [comment]
这个在工程中也有

**Comment by chexiongsheng** [comment]
有可能没放对位置吧。
报
Undefined symbol: _PushArrayBufferForJSFunction
Undefined symbol: _SetArrayBufferToOutValue
Undefined symbol: _ReturnArrayBuffer
就是xcode觉得你没有。

**Comment by CZyl1997** [comment]
"_PushArrayBufferForJSFunction", referenced from:
 _PuertsDLL_PushArrayBufferForJSFunction_mE18C120D1CDA766736AC1845D77FE713570FA447 in Assembly-CSharp21.o
_SetValueToArgumentImpl_SetArrayBuffer_m88B5AD0807A474DABD3C53C2CBA523FF2DEA61CE in Assembly-CSharp21.o
(maybe you meant: _PuertsDLL_PushArrayBufferForJSFunction_mE18C120D1CDA766736AC1845D77FE713570FA447)

我改了Xcode中buildsetting-bitcode后报错现在是这样的

**Comment by CZyl1997** [comment]
我Unity重新build之后，可以成功打包到真机了，感谢🙏帮助！
另外QQ群申请有时间能通过一下吗，谢谢！

**Comment by CZyl1997** [comment]
我关闭了Xcode BuildSetting 中的Enable bitcode，对puerts项目有什么影响吗？

**Comment by chexiongsheng** [comment]
就是要关闭bitcode

**Comment by chexiongsheng** [comment]
你看下xcode工程有没这两个文件：libpuerts.a，libwee8.a，没有的话，要么unity工程下没有，要么是没放对位置。

**Comment by zombieyang** [comment]
QQ群没有设置验证，你答对了问题就能进了。

**Comment by CZyl1997** [comment]
感谢，已解决！
