### ISSUE TITLE
[Unity] 如何在TypeScript中启用装饰器

### ISSUE THREAD

**Issue by kevinchen2046** [Tencent/puerts#395]
Unity中报错：ReferenceError: __decorate is not defined
当前是不支持装饰器？
还是tsconfig设置不正确?
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "esnext",
    "noEmitHelpers": true,
    "sourceMap": true,
    "baseUrl": "..",
    "outDir": "output"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "lib",
    "src"
  ]
}

**Comment by chexiongsheng** [comment]
差不多吧，我没一个个字符检查是否配置正确，这有个正确的示例：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/tsconfig.json

**Comment by kevinchen2046** [comment]
配置正确， 言下之意就是不支持装饰器 ？

**Comment by chexiongsheng** [comment]
言下之意是支持

**Comment by kevinchen2046** [comment]
可是这个报错 怎么解决呢？
Unity中报错：ReferenceError: __decorate is not defined

**Comment by chexiongsheng** [comment]
我这里可以。
是否支持，主要取决于typescript编译器。可能是你环境有问题吧。

**Comment by kevinchen2046** [comment]
问下你的 tsc 版本是？我试试

**Comment by kevinchen2046** [comment]
找到原因了 ！
删除"noEmitHelpers": true 就可以了
