### ISSUE TITLE
Android v8库缺少x86_64

### ISSUE THREAD

**Issue by RPG3D** [Tencent/puerts#4]
在模拟器调试Android需要x86版本，ue4目前支持Android x86_64

**Comment by chexiongsheng** [comment]
好，我后续提交一个

**Comment by chexiongsheng** [comment]
先打开跟踪吧，没那么快
主要是现在的android库用的是7.4，而其它平台是7.7，看能不能统一起来，然后再一起提交

**Comment by slb1988** [comment]
Unity Release也能同步更新一下么？
