### ISSUE TITLE
[Unity]用插件生成的csharp index.d.ts啥也没有咋回事

### ISSUE THREAD

**Issue by Sumxx** [Tencent/puerts#400]
Gen\Typing\csharp

用插件生成的csharp index.d.ts啥也没有咋回事
![image](https://user-images.githubusercontent.com/1875780/129867716-352d8eca-5161-485b-a970-079ccee556ff.png)

**Comment by chexiongsheng** [comment]
需要加到生成列表：https://github.com/Tencent/puerts/blob/master/doc/unity/manual.md

**Comment by Sumxx** [comment]
我没有bind其他东西喔，unity引擎相关的库函数没有生成出来

**Comment by chexiongsheng** [comment]
引擎的也要自己加，不加就不生成
