### ISSUE TITLE
[Unity] TS下无法直接调用GameObject.AddComponent(UnityEngine.Component)吗？

### ISSUE THREAD

**Issue by kevinchen2046** [Tencent/puerts#401]
`node.AddComponent(UnityEngine.SpriteRenderer)`
如上所示,调用失败。
按道理应该先取得对象的`System.Type`,可是TS下调用不到csharp的`typeof`.
然后我又尝试通过`类名称反射类型`,但是也失败.
有没有办法可以解决这个问题?

**Comment by yosun** [comment]
Can you explain how you solved it?

Exception: chunk:21: Error: c# exception:AddComponent(string) is deprecated,stack:  at UnityEngine.GameObject.AddComponent (System.String className) [0x00001] in /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/GameObject.deprecated.cs:19 
  at (wrapper managed-to-native)
