### ISSUE TITLE
反射调用，struct作为引用参数时报错

### ISSUE THREAD

**Issue by annayxguo** [Tencent/puerts#41]
public struct ss
{
    int age;
    string name;
    public int Age
    {
        get { return age; }
        set { age = value; }
    }
    public string Name
    {
        get{return name;}
        set{name = value;}
    }
    public ss(int i, string j) : this()
    {
        age = i;
        name = j;
    }
}

public class Su : Ba
{
    public string printStructRef(ref ss s)
    {
        s.Age = 20;
        return ("name : " + s.Name + " , age : " + s.Age);
    }
}

不点击Generate Code时，报错
![image](https://user-images.githubusercontent.com/63293951/94145606-62de0d80-fea5-11ea-893c-2e5bff73fe89.png)
点击Generate Code后，就没有错误

**Comment by chexiongsheng** [comment]
已修复：https://github.com/Tencent/puerts/commit/ca563a03016b661b0ef322f4137992267d76b60e
