### ISSUE TITLE
【Unreal】使用CallInEditor的Metadata，会导致生成的蓝图自动重编译

### ISSUE THREAD

**Issue by huzhangyang** [Tencent/puerts#410]
例子：
@UE.ufunction.ufunction(UE.ufunction.CallInEditor)
Test(): void {
｝

**Comment by chexiongsheng** [comment]
自动重编译是什么意思呢？本来东西改了就要重新编译

**Comment by huzhangyang** [comment]
> 自动重编译是什么意思呢？本来东西改了就要重新编译

描述的不够准确，就是在代码没有变化的情况下，蓝图产生了变化。之前报告过类似情况。

**Comment by chexiongsheng** [comment]
更新试试

**Comment by Lcyexiaoci** [comment]
好，目前这套是完全基于词法分析的，考虑到如果添加前缀会引入一些语法分析的成分，如import ufunction as absdfasdfe 之类的用法，虽然在语法上一致，但也会导致分析失败，因此，在解析代码里索性仅允许一种合法使用方式，对于CallInEditor，应该写为@ufunction.ufunction(ufunction.CallInEditor), 具体解析代码
![image](https://user-images.githubusercontent.com/12186398/131802756-45b59652-5cc3-4cc7-bed6-9df792b5f83f.png)
![image](https://user-images.githubusercontent.com/12186398/131802939-0ea8119c-422a-42e6-bd11-03a6ea501252.png)

在这里，如果项目对于decorator的使用标准跟默认的使用方式有冲突，改这两个函数里的正则表达式就行

**Comment by huzhangyang** [comment]
按上述方式修改后可以了
