### ISSUE TITLE
能简单说一下 puerts 的含义吗？

### ISSUE THREAD

**Issue by vanxining** [Tencent/puerts#43]
puerts：普洱 typescript？
纯属好奇，谢谢。

**Comment by chexiongsheng** [comment]
我在这篇文章的互动回答过这问题：https://zhuanlan.zhihu.com/p/195320417

**Comment by vanxining** [comment]
谢谢！我 copy 过来：
```想起个国风一点的名字。茶文化在中国源远流长，自古就是出口海外的重要物资，而普洱茶有个特点，越陈越香。这些和我的期望挺契合的：希望puerts越来越好用，而且能够走出国门。```
