### ISSUE TITLE
[unreal]空项目ts可以生成蓝图，多文件项目移植就无法生成蓝图了

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#435]
有没有log一类的东西，可以看到自动生成 蓝图过程中，出现了什么问题吗？

另外，ue4.25使用最新v8库，修改cs文件 使用newV8为true会导致v8.h无法找到的错误

**Comment by chexiongsheng** [comment]
按教程执行下enable_puerts_module.js，然后在TypeScript目录提交ts就可以了。
用新v8库，要另外下载，看教程，也有说明

**Comment by terst6** [comment]
肯定是执行了的喔，就是按照说明下载了最新版本，按照说明修改cs文件使用最新v8，才出现的问题，不修改没有问题。包含文件路径问题

**Comment by chexiongsheng** [comment]
可能哪里遗漏吧，4.25以上大多数人都在用新版本v8

**Comment by terst6** [comment]
逐步过滤，发现无法ts编译蓝图，是因为扩展的父类是蓝图类，如果父类是更高一级的cpp类，就没有问题。如果是项目移植到puerts，原来都是基于蓝图与cpp，感觉有点费功夫，如果用到函数覆盖功能的话。
另外，建议类扩展的那个注释语句应该像cpp的public 那种，不是一句一个注释。不输出的特性和函数//@no blueprint

**Comment by terst6** [comment]
如果其它蓝图引用了ts生成的蓝图对象，在任何错误发生，不能编译到蓝图的情况下，因为外部引用无效，反过来会导致ts无法编译到蓝图。所以外部蓝图不应该引用ts蓝图
