### ISSUE TITLE
typescript 语法检测错误

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#440]
以下代码在JavaScript目录下可以正常运行，得到回掉结果，但是在typescript目录里是语法错误
post(url,
            (out) => {
                let str=out.Str                
            }
        )

提示错误如下：
Argument of type '(out: any) => void' is not assignable to parameter of type '$Delegate<(ret: PostCallBack_Params) => void>'.
  Type '(out: any) => void' is missing the following properties from type '$Delegate<(ret: PostCallBack_Params) => void>': Bind, Unbind, IsBound, Executets(2345)

cpp 定义接口如下：
DECLARE_DYNAMIC_DELEGATE_OneParam(FCallbackDelegate, FPostCallBack_Params, ret);

UFUNCTION(BlueprintCallable)
void post(FString url, FCallbackDelegate callback);

因为会编译错误，整个文件内容不能被转换为 js文件。有谁遇到过，有什么建议吗？

**Comment by chexiongsheng** [comment]
学下ts，另外，例子有

**Comment by terst6** [comment]
已经搞定了，谢谢
