### ISSUE TITLE
[Unity]导出的wrap存在函数重载类型遗漏的情况

### ISSUE THREAD

**Issue by DavyGao** [Tencent/puerts#442]
发现导出的wrap存在遗漏的情况， C#中 父类A，包含5个重载方法, 子类B override其中3个，此时子类B生成的wrap文件中，只包含了override的3个方法类型检查，缺少了剩余两个父类的方法

**Comment by zombieyang** [comment]
目前来看是正常现象。只是应该把父类wrap也一起自动导出出来。我找车神确认一下
