### ISSUE TITLE
ue4 ts 调用蓝图函数，不会返回任何值

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#456]
如题

**Comment by chexiongsheng** [comment]
因为那个蓝图函数没有任何返回值

**Comment by chexiongsheng** [comment]
我也没开玩笑。
你那蓝图生成的ts定义是怎样的？有返回值么？

**Comment by terst6** [comment]
因为特殊用途，我的一个函数必须在蓝图中，蓝图计算结果我放蓝图另外一个变量里，运行蓝图函数后，我去取那个值作为返回。那个蓝图是一个actor或者object，都一样结果，试了直接结果返回，用cpp定义函数蓝图覆盖，用自己定义结构ref返回结果，试了很多方案，最后只好用一个独立的变量存储，计算完马上去取。你这么不信我说的，为什么你不把那个demo，访问蓝图函数的例子返回一个值，在ts里打印出来呢？那个例子没有返回东西，只在蓝图打印了数据

**Comment by chexiongsheng** [comment]
我让你发下“那蓝图生成的ts定义”

**Comment by terst6** [comment]
GetV(GM: $Nullable<WVGameMode>, V: $Ref<string>): void;

**Comment by terst6** [comment]
class NewBlueprintV_C extends Object {
        constructor(Outer?: Object, Name?: string, ObjectFlags?: number);
        V: string;
        GetV(GM: $Nullable<WVGameMode>, V: $Ref<string>): void;
        static StaticClass(): Class;
        static Find(OrigInName: string, Outer?: Object): NewBlueprintV_C;
        static Load(InName: string): NewBlueprintV_C;
    }

**Comment by chexiongsheng** [comment]
那不是对了么？返回值是void。
你是被蓝图的翻译或者概念搞混了。
你说的“返回”，其实只是out参数，可以有多个。
真正的返回值，还需要加多一个条件：名字是ReturnValue

**Comment by terst6** [comment]
蓝图

**Comment by terst6** [comment]
晕了网页版本git都不能传图，必须安装app

**Comment by chexiongsheng** [comment]
没看到我的回复么？Outputs，还是复数，你觉得这是返回值的意思么？

**Comment by chexiongsheng** [comment]
对应到GetV(GM: $Nullable<WVGameMode>, V: $Ref<string>): void;
有什么问题？
void不是已经告诉你没返回值了么？

**Comment by terst6** [comment]
奇怪的是int类型可以，因为我之前的速度测试用到同样方法，但是返回的int类型，计算结果正确

**Comment by terst6** [comment]
晕了，那个是ue蓝图标准定义返回值的方式，你让我怎么写返回值？

**Comment by chexiongsheng** [comment]
别奇怪，要么你记错，要么搞错。
你把V那个名字改为ReturnValue就可以了。这是UE的规则，从4.21开始都是这样。

**Comment by terst6** [comment]
在ts里用$ref取返回值

**Comment by terst6** [comment]
但是你返回undefined，我怎么取值呢

**Comment by chexiongsheng** [comment]
能否看下我的回复？？？？？？？？？？？？？？？？？？？？？

**Comment by chexiongsheng** [comment]
直白点吧：V那个名字改为ReturnValue，就会有返回值
如果想从$ref取值，看下例子或者教程，都有

**Comment by terst6** [comment]
let g_obj = UE.NewObject(UE.Class.Load('/Game/NewBlueprintV.NewBlueprintV_C'), me);
    let v;
    g_obj.GetV(me, (0, puerts_1.$ref)(v));
    console.log("V=", v);

[2021.09.23-09.16.22:255][422]Puerts: (0x0000016D1E9275F0) V=,undefined

你告诉我的是怎样返回一个结果，没有错，谢谢。我要告诉你的是，我用蓝图默认方式传递返回结果，然后用ts的方式取结果，结果是空，请问是我代码问题吗？为什么返回int可以

**Comment by terst6** [comment]
g_obj.GetV(me,$ref(v));
    console.log("V=",v)
是不是转化问题，ts 到jjs

**Comment by chexiongsheng** [comment]
看下例子
