### ISSUE TITLE
[unity]THREAD_SAFE win下执行正常，android 报错

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#462]
-23 18:54:16.901 15022 15135 E Unity   : RangeError: Maximum call stack size exceeded
09-23 18:54:16.901 15022 15135 E Unity   :   at Puerts.GenericDelegate.Action () [0x00000] in <00000000000000000000000000000000>:0
09-23 18:54:16.901 15022 15135 E Unity   :   at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0
09-23 18:54:16.901 15022 15135 E Unity   :   at PuertsTest.JsBehaviour.<Start>b__7_0 () [0x00000] in <00000000000000000000000000000000>:0
09-23 18:54:16.901 15022 15135 E Unity   :   at System.Threading.ThreadStart.Invoke () [0x00000] in <00000000000000000000000000000000>:0
09-23 18:54:16.901 15022 15135 E Unity   :   at System.Threading.ContextCallback.Invoke (System.Object state) [0x00000] in <0000000000000000000000000000
0000>:0
09-23 18:54:16.901 15022 15135 E Unity   :   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, Syste
m.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0
09-23 18:54:16.901 15022 15135 E Unity   :   at System.Threading.ThreadStart.Invoke () [0x00000] in <00000000000000000000000000000000>:0
09-23 18:54:16.901 15022 15135 E Unity   : PuertsTest.JsBehaviour:<Start>b__7_0()
09-23 18:54:16.901 15022 15135 E Unity   : System.Threading.ThreadStart:Invoke()
09-23 18:54:16.901 15022 15135 E Unity   : System.Threading.ContextCallback:Invoke(Obje
09-23 18:54:17.912 15022 15135 E Unity   : System.Exception: undefined:0:

demo:https://github.com/mingxxming/puerts_unity_demo/commit/0b5cefdef4c5e79fc879d6b59dd2c26931b805a2
用demo 里的04_JsBehaviour/RotateCube测试。

**Comment by zombieyang** [comment]
我能在安卓复现你说的问题，但win下使用v12并不能。你能把你v12有问题的版本传一个分支上来吗？

**Comment by mingxxming** [comment]
我之前测 把v13替过去win就好了。。 我现在把v12替回去并不能复现了，直接还原到之前有问题的版本也不能复现，不加THREAD_SAFE 也未能复现。 android 依旧可以复现

**Comment by zombieyang** [comment]
你这个问题我在mac上也能必现。
JS引擎是单线程设计，v8里isolate是和线程绑定的，跨线程调用本身就会报错。
简单地说，你这个情况应该在子线程创建JSEnv。（windows为什么可以还不太确定）

**Comment by mingxxming** [comment]
是不是nodejs 才能用多线程？

**Comment by zombieyang** [comment]
不是

**Comment by mingxxming** [comment]
v8::lock 可用于线程锁，不过对这个报错跟线程调用是否有因果关系表示怀疑。 win下不开thread_safe只是偶发性crash，android是必现。这个错在Linux上也遇到过，不过虽然是多线程，但是每个线程是相互隔离的jsenv， 也有概率会出这个错

**Comment by mingxxming** [comment]
> 试了下你这个问题我在mac上也能必现。
> 理论上JS引擎是单线程设计，v8里isolate是和线程绑定的，跨线程调用本身就会报错。（windows为什么可以还不太确定）
> 简单地说，你这个情况应该在子线程创建JSEnv。

jsenv 不是和 isolate绑定的吗？ 好像没有跟线程挂钩，isolate 在jsenv初始化后就存着了，所有native 接口都有把isolate传过去。

**Comment by zombieyang** [comment]
jsenv是和isolate绑定，v8底层会把isolate和线程绑定，所以就这样了。
你这个问题估计跟锁还没扯上关系。

**Comment by zombieyang** [comment]
在windows的UnitTest项目加多线程调用时复现，C#侧的THREAD_SAFE对该问题没有作用。

在C++侧添加v8::Locker后确认可以解决该问题。稍晚合入

**Comment by mingxxming** [comment]
ok.合入后我再试试。。。

**Comment by zombieyang** [comment]
加上v8::Locker后经压测发现C#调用JS会慢一倍，迟点再解决

**Comment by zombieyang** [comment]
6afb0a72551474789eb21f9643d996aa42ddf147
在主干上加了 由THREAD_SAFE宏包裹着的 v8::Locker，在CMakeLists.txt里把definition放开就可以编译出有Locker的dll用于测试。

我在我这个项目 https://github.com/zombieyang/puerts_unity_perf_baseline 里测得的结果确实CallJS速度直接满了一倍

**Comment by mingxxming** [comment]
我丢项目里测试帧率也远不如单线程。 可能因为v8的locker 只是解决多线程调用问题，反而会导致严重的线程资源竞争，所以帧率掉了还不稳定。
