### ISSUE TITLE
[unreal]函数的返回值应该借鉴unreal js

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#463]
为了返回mesh约束盒大小，puerts用了10行语句，而unreal js就一行，返回一个对象，把所有返回内容放里面
     let Origin:UE.Vector;
      let BoxExtent:UE.Vector
      let SphereRadius:number
      var Originref=$ref(Origin)
      var BoxExtentref=$ref(BoxExtent)
      var SphereRadiusref=$ref(SphereRadius)
      UE.KismetSystemLibrary.GetComponentBounds(this.SkeletalMesh,Originref,BoxExtentref,SphereRadiusref)
      Origin=$unref(Originref)
      BoxExtent=$unref(BoxExtentref)
      SphereRadius=$unref(SphereRadiusref)

      let out=UE.KismetSystemLibrary.GetComponentBounds(this.SkeletalMesh,Originref,BoxExtentref,SphereRadiusref)
 out:{Origin,BoxExtent,SphereRadius}

**Comment by chexiongsheng** [comment]
我不觉得应该借鉴。哪个好并不是看代码行数，特别是某个特殊例子的代码行数。
puerts的定义更接近原本的定义，你用c++写个接口对比下看看。
其次unreal.js丢失了接口签名信息，当然，由于unreal.js只提供反射调用，而UE的UFunction又不支持重载，这问题不大。但puerts是支持重载的（模板绑定方式），void Foo(int a);和void Foo(int & a);将无法区分

**Comment by terst6** [comment]
外部函数参数在ts里不是都有严格的定义吗，是不是指针语法检测就提示错误，每一个参数什么位置类型都知道，没有必要要用户再声明一下，返回类型也是确定的。一条语句能够完成用很多语句去做，违背了简单易读的原则

**Comment by chexiongsheng** [comment]
> 外部函数参数在ts里不是都有严格的定义吗，是不是指针语法检测就提示错误，每一个参数什么位置类型都知道，没有必要要用户再声明一下，返回类型也是确定的。一条语句能够完成用很多语句去做，违背了简单易读的原则

没搞懂我说啥。
在ts这样的语句：obj.Foo(1)，你告诉我调用的是哪个呢？

**Comment by chexiongsheng** [comment]
简单易读原则，并不是“你的”简单易读原则。
每个人对这个都有不同的定义，我觉得puerts这种才是简单易读。算字符个数的衡量方式太low了。
