### ISSUE TITLE
[UE]修改完绑定蓝图的ts后，运行游戏崩溃

### ISSUE THREAD

**Issue by champinn** [Tencent/puerts#471]
定义了一个继承自UE.Character的ts类型TsCharacter，蓝图中创建了一个继承TsCharacter的BpCharacter，当TsCharacter修改保存后，运行游戏后，BpCharacter调用了父类Ts的方法，这个方法对TsCharacter中定义的蓝图成员变量进行取值或赋值的时候崩溃。
源码调试进入崩溃断点时，发现v8访问器取出来的FProperty对象是ts修改前的，并不是最新的，查看JsEnvImpl中TsCharacter类型的Wrapper，是修改ts后最新的值，怀疑继承的原型链出问题，经log定位后，发现在GetJsClass的时候，直接子类只在第一次的时候设置父类原型对象，所以导致后来有修改ts已经重新修改了父类原型，但是子类的父类原型对象一直没有更新。

**Comment by terst6** [comment]
目前好像还没有到可以这样自由使用的地步，我的经验是ts只能继承一次非ts类，蓝图继承ts类，使用ts类都极其不稳定，多小规模测试后再用

**Comment by ljporljp** [comment]
这应该是个bug，至少应该子类给一个提示

**Comment by chexiongsheng** [comment]
> 这应该是个bug，至少应该子类给一个提示

问题是按他描述的做，根本重现不了，包括他自己也没在独立的工程里头重现，所以应该还有其它条件触发这问题。所以是不是bug还不能确定，是什么导致这个bug也不能确定
