### ISSUE TITLE
TS中给Character设置SkeletalMesh和AnimClass无效

### ISSUE THREAD

**Issue by konlil** [Tencent/puerts#475]
`// TS_Hero.ts

import * as UE from 'ue'
import "./ObjectExt"

class TS_Hero extends UE.Character
{
    Constructor()
    {
        let CharMesh = UE.SkeletalMesh.Load("/Game/Prototype/Characters/Mannequin/Character/Mesh/SK_Mannequin");
        let CharAnimClass = UE.Class.Load("/Game/Prototype/Characters/Mannequin/Animations/ThirdPerson_AnimBP.ThirdPerson_AnimBP_C");
        this.Mesh.SetSkeletalMesh(CharMesh, true);
        this.Mesh.SetAnimationMode(UE.EAnimationMode.AnimationBlueprint);
        this.Mesh.SetAnimClass(CharAnimClass);
        console.log("xxxxxxxxxxxxxxxxxxxx"); 
    }
}

export default TS_Hero;`

**Comment by terst6** [comment]
无论大写小写构造，都不会有效果。问题多得很

**Comment by chexiongsheng** [comment]
这个UE的一些特殊设定导致的，没法在构造函数直接设置，这有分析：https://github.com/Tencent/puerts/issues/287
可以去掉构造函数，然后在生成的蓝图按以前的方式设置

**Comment by chexiongsheng** [comment]
Duplicate of #287

**Comment by chexiongsheng** [comment]
> 无论大写小写构造，都不会有效果。问题多得很

发现问题开issue提下。这个issue描述的是很早前的已知限制，由于UE的设定没法支持。其它的构造函数的限制在文档里头有：https://github.com/Tencent/puerts/blob/master/doc/unreal/manual.md#%E8%87%AA%E5%8A%A8%E7%BB%91%E5%AE%9A%E6%A8%A1%E5%BC%8F
如果在两者之外的问题请提issue描述跟踪

**Comment by chexiongsheng** [comment]
也可以试试在Component的构造函数设置自己属性

**Comment by terst6** [comment]
那应该在unreal demo的那个扩展实例里，把你以上建议写注释里

另外我遇到的一个大坑就是，覆盖父类函数时，如果那个函数有返回值没有被定义为 return value ，ts不提示错误，运行就crash，如果没有契而不舍的精神，很容易就放弃了

**Comment by konlil** [comment]
> 也可以试试在Component的构造函数设置自己属性

嗯，感谢，试试这个方法，这个issue就关了先
