### ISSUE TITLE
setTimeout 第三个参数传参有问题

### ISSUE THREAD

**Issue by zhnet** [Tencent/puerts#477]
setTimeout((count:number) => {
            console.log(count);//undefined
        }, 1000, 1);

**Comment by zombieyang** [comment]
已修

**Comment by zhnet** [comment]
unreal，改了?

**Comment by chexiongsheng** [comment]
直接bind不就可以了么？

**Comment by terst6** [comment]
参数直接填count那里

**Comment by zhnet** [comment]
> 参数直接填count那里

嗯，这里没有闭包问题，不用第三个参数传参。这个语法和我之前的认知有问题，还以为函数结束变量也没了
