### ISSUE TITLE
ue 在vscode的debug console输入vector. crash ue

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#478]
在断点状态下，用鼠标查看vector变量属性没有问题，在控制台输入这个变量.X，UE就挂了

**Comment by chexiongsheng** [comment]
栈？

**Comment by terst6** [comment]
TsTestActor.ts

    ReceiveBeginPlay(): void {
        console.warn("TsTestActor.ReceiveBeginPlay this.Add", this.Add(55, 66));
	    let V= new UE.Vector(1,2,3)
        debugger
    }
vscode debug console, V.

static void _FVectorXGet_(const v8::FunctionCallbackInfo<v8::Value>& Info)
{
    v8::Isolate* Isolate = Info.GetIsolate();
    v8::HandleScope HandleScope(Isolate);
    v8::Local<v8::Context> Context = Isolate->GetCurrentContext();

    auto Self = puerts::DataTransfer::GetPointerFast<FVector>(Info.This()); //XXXX

    auto V8Result =v8::Number::New(Isolate, Self->X);
    Info.GetReturnValue().Set(V8Result);
}


+		Context	{val_=0x0000024289b9c5f8 {...} }	v8::Local<v8::Context>
+		HandleScope	{isolate_=0x00000242cb5ea640 {...} prev_next_=0x0000024289b9c5f8 {4377542131985} prev_limit_=0x0000024289b9e3f0 {...} }	v8::HandleScope
+		Info	{implicit_args_=0x000000f48f374a78 {2697491320065} values_=0x000000f48f374bf8 {2304675939721} length_=...}	const v8::FunctionCallbackInfo<v8::Value> &
		Isolate	0x00000242cb5ea640 {...}	v8::Isolate *
+		Self	0x0000000000000000 <NULL>	FVector *
+		V8Result	{val_=0x0000000000000000 <NULL> }	v8::Local<v8::Number>


>	UE4Editor-JsEnv-Win64-DebugGame.dll!_FVectorXGet_(const v8::FunctionCallbackInfo<v8::Value> & Info) Line 3182	C++
 	[External Code]	
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::V8InspectorChannelImpl::DispatchProtocolMessage(const std::string & Message) Line 85	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::V8InspectorClientImpl::OnReceiveMessage(std::weak_ptr<void> Handle, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager>> Message) Line 417	C++
 	[External Code]	
 	UE4Editor-JsEnv-Win64-DebugGame.dll!websocketpp::connection<websocketpp::config::asio>::handle_read_frame(const std::error_code & ec, unsigned __int64 bytes_transferred) Line 1099	C++
 	[External Code]	
 	UE4Editor-JsEnv-Win64-DebugGame.dll!websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void __cdecl(std::error_code const &,unsigned __int64)> handler, const std::error_code & ec, unsigned __int64 bytes_transferred) Line 897	C++
 	[External Code]	
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::asio_handler_invoke<asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,std::error_code,unsigned __int64>>(asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,std::error_code,unsigned __int64> & function, ...) Line 69	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::strand_service::dispatch<asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,std::error_code,unsigned __int64>>(asio::detail::strand_service::strand_impl * & impl, asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,std::error_code,unsigned __int64> & handler) Line 61	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>::operator()<std::error_code,unsigned __int64>(const std::error_code & arg1, const unsigned __int64 & arg2) Line 98	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>::operator()(const std::error_code & ec, unsigned __int64 bytes_transferred, int start) Line 286	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::asio_handler_invoke<asio::detail::rewrapped_handler<asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64>,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>>>(asio::detail::rewrapped_handler<asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64>,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>> & function, ...) Line 69	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::completion_handler<asio::detail::rewrapped_handler<asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64>,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>>>::do_complete(void * owner, asio::detail::win_iocp_operation * base, const std::error_code & __formal, unsigned __int64 __formal) Line 69	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::strand_service::dispatch<asio::detail::rewrapped_handler<asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64>,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>>>(asio::detail::strand_service::strand_impl * & impl, asio::detail::rewrapped_handler<asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64>,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>> & handler) Line 87	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::asio_handler_invoke<asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64>,asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>(asio::detail::binder2<asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>,std::error_code,unsigned __int64> & function, asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running> * this_handler) Line 231	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::win_iocp_socket_recv_op<asio::mutable_buffers_1,asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffers_1,asio::mutable_buffer const *,asio::detail::transfer_at_least_t,asio::detail::wrapped_handler<asio::io_context::strand,websocketpp::transport::asio::custom_alloc_handler<std::_Binder<std::_Unforced,void (__cdecl websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void __cdecl(std::error_code const &,unsigned __int64)>,std::error_code const &,unsigned __int64),std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>>,std::function<void __cdecl(std::error_code const &,unsigned __int64)> &,std::_Ph<1> const &,std::_Ph<2> const &>>,asio::detail::is_continuation_if_running>>>::do_complete(void * owner, asio::detail::win_iocp_operation * base, const std::error_code & result_ec, unsigned __int64 bytes_transferred) Line 98	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::win_iocp_io_context::do_one(unsigned long msec, std::error_code & ec) Line 420	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::detail::win_iocp_io_context::poll(std::error_code & ec) Line 211	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!asio::io_context::poll() Line 91	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::V8InspectorClientImpl::Tick(float __formal) Line 330	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::V8InspectorClientImpl::Tick() Line 347	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::V8InspectorClientImpl::runMessageLoopOnPause(int __formal) Line 469	C++
 	[External Code]	
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::FFunctionTranslator::CallJs(v8::Isolate * Isolate, v8::Local<v8::Context> & Context, v8::Local<v8::Function> JsFunction, v8::Local<v8::Value> This, UObject * ContextObject, FFrame & Stack, void * Z_Param__Result) Line 375	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::FJsEnvImpl::InvokeTsMethod(UObject * ContextObject, UFunction * Function, FFrame & Stack, void * Z_Param__Result) Line 1464	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!puerts::FJsEnvImpl::TsDynamicInvokerImpl::InvokeTsMethod(UObject * ContextObject, UFunction * Function, FFrame & Stack, void * Z_Param__Result) Line 328	C++
 	UE4Editor-JsEnv-Win64-DebugGame.dll!UTypeScriptGeneratedClass::execCallJS(UObject * Context, FFrame & Stack, void * const Z_Param__Result) Line 25	C++
 	UE4Editor-CoreUObject.dll!UFunction::Invoke(UObject * Obj, FFrame & Stack, void * const Z_Param__Result) Line 5542	C++
 	UE4Editor-CoreUObject.dll!UObject::ProcessEvent(UFunction * Function, void * Parms) Line 1916	C++
 	UE4Editor-Engine.dll!AActor::ProcessEvent(UFunction * Function, void * Parameters) Line 798	C++
 	UE4Editor-Engine.dll!AActor::BeginPlay() Line 3457	C++
 	UE4Editor-Engine.dll!AActor::DispatchBeginPlay(bool bFromLevelStreaming) Line 3397	C++
 	UE4Editor-Engine.dll!AWorldSettings::NotifyBeginPlay() Line 246	C++
 	UE4Editor-Engine.dll!AGameStateBase::HandleBeginPlay() Line 205	C++
 	UE4Editor-Engine.dll!UWorld::BeginPlay() Line 4184	C++
 	UE4Editor-Engine.dll!UGameInstance::StartPlayInEditorGameInstance(ULocalPlayer * LocalPlayer, const FGameInstancePIEParameters & Params) Line 478	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::CreateInnerProcessPIEGameInstance(FRequestPlaySessionParams & InParams, const FGameInstancePIEParameters & InPIEParameters, int InPIEInstanceIndex) Line 2792	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::OnLoginPIEComplete_Deferred(int LocalUserNum, bool bWasSuccessful, FString ErrorString, FPieLoginStruct DataStruct) Line 1474	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::CreateNewPlayInEditorInstance(FRequestPlaySessionParams & InRequestParams, const bool bInDedicatedInstance, const EPlayNetMode InNetMode) Line 1708	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::StartPlayInEditorSession(FRequestPlaySessionParams & InRequestParams) Line 2580	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::StartQueuedPlaySessionRequestImpl() Line 1089	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::StartQueuedPlaySessionRequest() Line 1016	C++
 	UE4Editor-UnrealEd.dll!UEditorEngine::Tick(float DeltaSeconds, bool bIdleMode) Line 1611	C++
 	UE4Editor-UnrealEd.dll!UUnrealEdEngine::Tick(float DeltaSeconds, bool bIdleMode) Line 414	C++
 	UE4Editor-Win64-DebugGame.exe!FEngineLoop::Tick() Line 4850	C++
 	[Inline Frame] UE4Editor-Win64-DebugGame.exe!EngineTick() Line 62	C++
 	UE4Editor-Win64-DebugGame.exe!GuardedMain(const wchar_t * CmdLine) Line 169	C++
 	UE4Editor-Win64-DebugGame.exe!WinMain(HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 257	C++
 	[External Code]
