### ISSUE TITLE
[Unity] 将 Js function 绑定至 C# Delegate 后无法获取 function 的 context 信息.

### ISSUE THREAD

**Issue by liu3656** [Tencent/puerts#481]
你好.

项目需求要将 js function 绑定至 C# Delegate (当前使用的是 Action), 然后直接在 C# 调用 Action 以达到调用 JS 的目的.
在 Js 端, 每个 Js object 会缓存对应信息, 这样在调用 function 时无需将 onwer 作为参数传入.

问题:
在 C# 调用 Js function 时, 我们发现 function 内的 this.XXX 都无法获取, 值为 undefined. 经过检查, 我们发现绑定完 c# action 后, Js 侧输出 c# action. Method 是值为 Js 方法体, action.Target 也是这个 function. C# 侧, action.Method 为方法体, 而 action.Target 则是一个GenericDelegate.
 
我们猜测是否是因为 action.Target 不是 function owner object 而导致了 this context 的缺失?

我们希望能够在 Js 环境内创建与 C# 相同的 action, 即 action.Method 与 action.Target 都是 valid 的. 这样在调用时可以使用到 this context. 

示例 TS 代码如下

```typescript
// ......
var EventAction = $generic(cs.System.Action$1, cs.Game.Ecs.IEventData);

class TestTimingClass
{
    constructor(ownerEntity)
    { 
        this.OwnerEntity = ownerEntity;
    }

    BindContainer()
    {
        // 此处可以正确获得 this.OwnerEntity
        console.log('This.OwnerEntity:' + this.OwnerEntity);
        this.SubscribeGlobalEvent(GlobalEvents.AnyRoundFlowStarted, this.HandleGlobalEvent);
    }

    HandleGlobalEvent(event)
    {
        // 通过 c# action 调用此方法时, 无法获得 this.OwnerEntity, 值为 undefined.
        console.log("Handle global event, this.OwnerEntity: " + this.OwnerEntity);
        if(event.RoundNumber > 2)
        {
            console.log("Test timing class handle RoundStartEvent triggered.");
        }
    }

    SubscribeGlobalEvent(eventType, func)
    {
        // 获取由 c# 传入的 global event manager.
        let globalEventManager = core.GetGlobalEventManager();
        // 创建 c# action.
        let a = new EventAction(func);
        // 调取 c# subscribe function.
        globalEventManager.SubscribeGlobal(eventType, a);
    }
}

// ......
```

谢谢!

**Comment by Joycraft** [comment]
这是绑定时的写法导致的, 而不是底层, 你要提供绑定时的写法才能找出问题, this丢失是常见的js写法错误, 比如像 fn.apply(target, ...args)这种调用方式就能正确传入this到对象的方法调用使它内部的this正常表示对象本身

**Comment by liu3656** [comment]
谢谢您的快速回复.
我补充一下 C# 的代码. 上面代码段中的 core.GetGlobalEventManager() 指的就是这个 GlobanEventManager

```csharp
public class GlobalEventManager : MonoBehaviour
{
    private Dictionary<Type, List<Action<IEventData>>> eventDict;

    protected override void Awake()
    {
        base.Awake();
        eventDict = new Dictionary<Type, List<Action<IEventData>>>();
    }
        
    public void SubscribeGlobal(Type eventType, Action<IEventData> action)
    {
        if (!eventDict.ContainsKey(eventType))
        {
            eventDict.Add(eventType, new List<EventDelegate>());
        }
                        
            eventDict[eventType].Add(action);
        }

    public void UnsubscribeGlobal(Type eventType, Action<IEventData> action)
    {            
        foreach (var eventDelegate in eventDict[eventType])
        {
            if (eventDelegate.Method == action.Method && eventDelegate.Target == action.Target)
            {
                eventDict[eventType].Remove(action);
                break;
            }
        }
    }

    public void SendEvent(IEventData e)
    {
        var type = e.GetType();
            
        if (eventDict.ContainsKey(type))
        {
            foreach (var action in eventDict[type])
            {
                action(e);
            }
        }
    }
}
```

具体的绑定部分是第一个帖子中的 

> SubscribeGlobalEvent(eventType, func) 

流程是: 使用 js function 作为参数创建一个 c# delegate, 再把这个 delegate 传回 c# 进行使用.



> 这是绑定时的写法导致的, 而不是底层, 你要提供绑定时的写法才能找出问题, this丢失是常见的js写法错误, 比如像 fn.apply(target, ...args)这种调用方式就能正确传入this到对象的方法调用使它内部的this正常表示对象本身

您的例子是 fn.apply(target, ...args), 是不是指需要将 this 的 object 作为 function 的第一个参数传入?

谢谢

**Comment by Joycraft** [comment]
这跟c#的代码没有关系, 你可以查阅js文档, 看 Funtion.Apply 的具体用法在ts代码里就能解决这个问题

**Comment by Joycraft** [comment]
ts代码: 
`
class MyClass {
   public callFn(...args: any[]){
    //todo
 }
}
global $call=function(...args: any[]){
let obj=new MyCall();
return obj.callFn.apply(obj,arguments);
}
`
c#代码
`
jsEnv.Eval<Action<int>>("$call")?.Invoke(1);
`
大概类似这个样子, 可能有错误, 在评论框里手写的, 没有实际测试

**Comment by liu3656** [comment]
> ts代码:
> 
> class MyClass {
>    public callFn(...args: any[]){
>     //todo
>  }
> }
> global $call=function(...args: any[]){
> let obj=new MyClass();
> return obj.callFn.apply(obj,arguments);
> }
> 
> c#代码
> 
> jsEnv.Eval>("$call")?.Invoke(1);
> 大概类似这个样子, 可能有错误, 在评论框里手写的, 没有实际测试

收到, 我看看怎么能应用到我们项目里去.
非常感谢!

**Comment by Joycraft** [comment]
应该也能这样写
<pre>
global $myObj = new MyClass;
</pre>
<pre>
jsEnv.Eval<Action<MyUnityClass,int>>("$myObj.callFn.call").Invoke(new MyUnityClass,1);
</pre>
应该也能调用obj.callFn,并且在callFn里面的this正确指向obj本身, 应该就能实现你的需求, 但是需要测试才知道是否可行

**Comment by liu3656** [comment]
收到

**Comment by Joycraft** [comment]
`jsEnv.Eval < Action< int>>("(...args) => $myObj.callFn.apply($myObj, args)").Invoke(1);`
