### ISSUE TITLE
需求：保存蓝图属性，删除蓝图重新生成蓝图后，导入之前保存的特性

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#482]
类似于整个蓝图特性拷贝粘贴到另外一个蓝图。当出现crash后，删除蓝图重新生成很必要，但是设置会全部丢失

**Comment by KaiQian** [comment]
是自动绑定模式么？是的话，不要直接使用TS直接生成的蓝图而是继承它再使用比较好。

**Comment by terst6** [comment]
SaveTSClass("/Game/Blueprints/TypeScript/TSGameMode.TSGameMode_C","TSGameMode")


void A1GameMode::SaveTSClass(const FString ClassName, const FString Saveto)
{
#if WITH_EDITOR
	UClass* classObj = FindObject<UClass>(ANY_PACKAGE, *ClassName);   //获得表示MyClass的UClass*
	if (classObj) {
		FProperty* prop;
		FString KeyName;
		FString valueStr;
		FString CSV = FString::Printf(TEXT("%s\r\n"),*ClassName);
		const uint8* PropertyAddr;
		for (TFieldIterator<FProperty> it(classObj); it; ++it) {
			prop = *it;
			KeyName = prop->GetName();
			valueStr.Empty();
			PropertyAddr = prop->ContainerPtrToValuePtr<uint8>(classObj->ClassDefaultObject);
			prop->ExportTextItem(valueStr, PropertyAddr, NULL, NULL, PPF_None);
			if (!valueStr.IsEmpty() && valueStr !=TEXT("None") && valueStr != TEXT("0") && valueStr != TEXT("()") && valueStr != TEXT("False")) {
				CSV += FString::Printf(TEXT("%s:%s\r\n"), *KeyName, *valueStr);
			}
		}
		FString FileLocation = FPaths::ConvertRelativePathToFull(FPaths::ProjectSavedDir() + Saveto);
		FArchive* FileWriter = IFileManager::Get().CreateFileWriter(*FileLocation);
		if (FileWriter) {
			FileWriter->Serialize(TCHAR_TO_ANSI(*CSV), CSV.Len());
			FileWriter->Close();
			delete FileWriter;
			UE_LOG(LogTemp, Log, TEXT("SaveTSClass %s to %s"), *ClassName , *Saveto);
		}
	}
	else {
		UE_LOG(LogTemp, Log, TEXT("SaveTSClass Class not found: %s"), *ClassName);
	}
#endif
}

void A1GameMode::LoadCSVToClass(const FString ClassName, const FString CSVFile)
{
#if WITH_EDITOR
	UClass* classObj = FindObject<UClass>(ANY_PACKAGE, *ClassName);   //获得表示MyClass的UClass*
	if (classObj) {
		ANSICHAR* CSV = 0;
		FString FileLocation = FPaths::ConvertRelativePathToFull(FPaths::ProjectSavedDir() + CSVFile);
		FArchive* FileReader = IFileManager::Get().CreateFileReader(*FileLocation);
		if (FileReader) {
			const int64 FileSize = FileReader->TotalSize();
			CSV = (ANSICHAR*)FMemory::Malloc(FileSize + 1);
			FileReader->Serialize(CSV, FileSize);
			FileReader->Close();
			delete FileReader;
			CSV[FileSize] = 0;
		}
		FProperty* prop;
		ANSICHAR* KeyName;
		char findStr[MAX_SPRINTF] = ("");
		ANSICHAR valueStr[MAX_SPRINTF] = ("");
		uint8* PropertyAddr;
		classObj->ClassDefaultObject->Modify();
		for (TFieldIterator<FProperty> it(classObj); it; ++it) {
			prop = *it;
			KeyName = TCHAR_TO_ANSI(*prop->GetName());
			findStr[0] = 0;
			strcat(findStr, "\r\n");
			strcat(findStr, KeyName);
			strcat(findStr, ":");
			ANSICHAR* i = strstr(CSV, findStr);
			if (i > CSV) {
				ANSICHAR* j = strchr(i + 1, '\r');
				if (j > i) {
					i += strlen(KeyName) + 3;
					FCStringAnsi::Strncpy(valueStr, i, j - i + 1);
					PropertyAddr = prop->ContainerPtrToValuePtr<uint8>(classObj->ClassDefaultObject);
					prop->ImportText(ANSI_TO_TCHAR(valueStr), PropertyAddr, PPF_None, classObj->ClassDefaultObject);
					FPropertyChangedEvent PropertyChangedEvent(prop, EPropertyChangeType::ValueSet);
					classObj->PostEditChangeProperty(PropertyChangedEvent);
				}
			}
		}
		FMemory::Free(CSV);
		UE_LOG(LogTemp, Log, TEXT("LoadCSVToClass %s to %s"), *CSVFile, *ClassName);
	}
	else {
		UE_LOG(LogTemp, Log, TEXT("LoadCSVToClass Class not found: %s"), *ClassName);
	}
#endif
}
