### ISSUE TITLE
[unity]即使有生成代码，registerType也会反射补充没有生成到的类成员。可能导致初始化缓慢。

### ISSUE THREAD

**Issue by zombieyang** [Tencent/puerts#485]

**Comment by zombieyang** [comment]
```
    public enum TypeRegisterMode 
    {
        Mixed = 0,
        GeneratedCodeFirst = 1,
        GeneratedCodeOnly = 2
    }
```

`Mixed`：默认状态。会先用生成的代码，然后再反射补上缺的。
`GeneratedCodeFirst`：没有生成代码就用反射。有生成就用生成的，不会再用反射补缺。
`GeneratedCodeOnly`：只用生成的代码。如果没有生成，这个类就是空的。

**Comment by chexiongsheng** [comment]
> ```
>     public enum TypeRegisterMode 
>     {
>         Mixed = 0,
>         GeneratedCodeFirst = 1,
>         GeneratedCodeOnly = 2
>     }
> ```
> 
> `Mixed`：默认状态。会先用生成的代码，然后再反射补上缺的。 `GeneratedCodeFirst`：没有生成代码就用反射。有生成就用生成的，不会再用反射补缺。 `GeneratedCodeOnly`：只用生成的代码。如果没有生成，这个类就是空的。

这种信息要写在使用手册里头，包括之前node的参数

**Comment by zombieyang** [comment]
和车神交流了一下上述草案改动较多。且目前尚未在Puerts实现Lazy注册功能。所以`1.14.0`版本先以去掉TypeRegister里的GetMethods为目标。
