### ISSUE TITLE
PC缺少x86的库，有些构建出来的客户端还是32位下的

### ISSUE THREAD

**Issue by Ollydbg** [Tencent/puerts#5]
如题，缺少x86的库。

**Comment by chexiongsheng** [comment]
你用的是unreal还是unity版本？

**Comment by Ollydbg** [comment]
Unity版本

**Comment by Ollydbg** [comment]
> 你用的是unreal还是unity版本？

请问有计划发布Unity 32位的的v8支持吗？

**Comment by ChasonTang** [comment]
Unity support iOS 10+, iPhone 5 is armv7 32 bit device, puerts use arm64 v8 for iOS, Is there any armv7 v8 static library?

**Comment by 3wz** [comment]
同求unity版本x86库

**Comment by chexiongsheng** [comment]
支持x86了：https://github.com/Tencent/puerts/releases/tag/v1.0.6

**Comment by Ollydbg** [comment]
> 支持x86了：https://github.com/Tencent/puerts/releases/tag/v1.0.6

感谢。
