### ISSUE TITLE
struct作为引用参数，传入ts代码，赋值该对象的成员变量后不起作用，获取该变量仍然为初始值

### ISSUE THREAD

**Issue by alimwang** [Tencent/puerts#50]
把struck改成class后就没有该问题

**Comment by jihuayu** [comment]
> class 作为参数类型传递，传递的是引用地址，struct 作为参数类型传递，传递的是值。
[Doc](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method)
我猜测是这个原因。

**Comment by chexiongsheng** [comment]
你怎么把struct作为引用参数传入ts代码的呢？
