### ISSUE TITLE
ue4 在通知函数中使用 timer 总是提示错误

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#503]
QuickStart.ts

function MutiCast2(i) {
    console.warn("MutiCast2>>>", i);
    actor.NotifyWithInt.Remove(MutiCast2);//调用一次后就停掉
    setTimeout(() => {
        this.MutiCast1(i)
    }, 1000);
}

如果用蓝图子类覆盖这个函数用timer 去执行相同功能就没有问题

Puerts: Warning: (0x0000022A0A315230) JS Execution Exception: demo\Content\JavaScript\QuickStart.js:131: TypeError: this.MutiCast1 is not a function
TypeError: this.MutiCast1 is not a function
demo\Content\JavaScript\QuickStart.js:131:14

**Comment by chexiongsheng** [comment]
和timer没关，和你对js语法里头this的理解有关
