### ISSUE TITLE
蓝图侧调用ts定义的函数，只要有引用调用的参数，就一定会奔溃

### ISSUE THREAD

**Issue by forget-js** [Tencent/puerts#508]
我在ts里定义了一个函数，其中有个参数是引用调用的方式，因为我希望在蓝图侧调用这个函数时，可以有多个返回值。这个函数定义如下：

`    RefFuncTest(name: $Ref<string>): boolean {
        console.log("Error: RefFuncTest name = ", name.value);
        if(name) {
            name.value = "capture1";
            return true;
        }
        return false;
    }
`
当我在蓝图中调用它时，首先name这个参数没有出现在节点右侧，而是出现在左侧（我希望它出现在右侧），其次只要参数是引用调用的方式，运行后引擎就会崩溃，奔溃提示的代码为
Assertion failed: OutParmRec [File:D:/Projects/PluginTest/Plugins/Puerts/Source/JsEnv / Private/ FunctionTranslator.cpp][Line: 387]

**Comment by forget-js** [comment]
抱歉，描述里的代码没有格式化。

**Comment by forget-js** [comment]
RefFuncTest(name: $Ref<string>): boolean {
        console.log("Error: RefFuncTest name = ", name.value);
        if(name) {
            name.value = "capture1";
            return true;
        }
        return false;
    }

**Comment by forget-js** [comment]
插件版本：9a3d215

**Comment by chexiongsheng** [comment]
这问题早就解决了：https://github.com/Tencent/puerts/commit/cd21a4ec05fc3b7edb43b500781d885899347e5f#diff-d252dd5da6cf735e4d2e1728a0d779916f6f6e5f2fb8097a869522870c47f037
