### ISSUE TITLE
有没有应用过商业项目

### ISSUE THREAD

**Issue by 823639792** [Tencent/puerts#52]
如题：
有没有应用过商业项目，比如鹅厂应用到了实际产品中吗？是什么？

**Comment by chexiongsheng** [comment]
有啊，但都还没上线

**Comment by chiuan** [comment]
> 有啊，但都还没上线

有计划推动公司项目用这个方案。请问性能比ILRuntime怎样的？

**Comment by chexiongsheng** [comment]
> > 有啊，但都还没上线
> 
> 有计划推动公司项目用这个方案。请问性能比ILRuntime怎样的？

不是说已经有项目了么？开发中没上线而已。都是大项目，开发周期一般2年+。
开源后外部小公司倒是有小项目已经上线。
性能看你咋衡量。ILRuntime本身就是C#实现，没有跨语言交互开销，所以调原生会快。
如果是虚拟机部分，ILRuntime和google的v8，无论是性能还是任何一方面，应该没有任何可比性的。

**Comment by liuhuiting1985** [comment]
和LUA比呢 性能怎么样

**Comment by BobbyBao** [comment]
非jit模式的性能估计肯定比不上lua，要是在lua性能的50%以上就不错了
