### ISSUE TITLE
【ue4】 在代码中使用装饰器时，提示错误警告，是否可以在项目中使用装饰器

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#523]
代码：
![image](https://user-images.githubusercontent.com/18215765/139389262-c6068f15-81e3-4a85-a129-7b338d541cb3.png)

警告：
![image](https://user-images.githubusercontent.com/18215765/139389318-77be046d-e94a-4b8e-a2d5-e1d1cfdd3447.png)

tsconfig 设置
![image](https://user-images.githubusercontent.com/18215765/139389413-b2ec584f-6712-41e0-a12c-e296c458dd57.png)

**Comment by chexiongsheng** [comment]
语言问题google
