### ISSUE TITLE
ue4 软目标类在手机上运行时无效

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#526]
像是每执行一次卸载一次。如果把软目标类改为ue.class在对象启动时赋值，就完全没有问题，而软目标类即使每次执行时检测加载，都会出问题

**Comment by chexiongsheng** [comment]
这不就是softclass的行为么？
另外，puerts没实现新的softclass，都是调用原来ue引擎的接口，引擎本来是怎样就怎样。
