### ISSUE TITLE
puerts 有没有内置的 Http 和 WebSocket 支持

### ISSUE THREAD

**Issue by jianlailing** [Tencent/puerts#534]

**Comment by Joycraft** [comment]
不可能

**Comment by jianlailing** [comment]
> 桌面版的nodejs里面有, 因为带了nodejs的dll, node里面有什么就有什么

这个我明白，现在手机平台应该是要自己实现，我是在想如果网络通讯频繁的话，用内置的会不会比调用C#的要好

**Comment by Joycraft** [comment]
内置怎么会比自己实现好..
内置的只可能是简单的通用方案, 而通讯库开源的都一堆, 每个公司每个游戏的需求都不一样, 有人必须要用protobuf, 有人只需要http, 你内置了结果一半以上的人压根用不了, 还是要自己实现, 那不是浪费

**Comment by Joycraft** [comment]
这就跟汽车发动机引擎自带车轮差不多

**Comment by throw-out** [comment]
因为http或WebSocket是浏览器或nodejs特有的API, 详见: [general faq](doc/faq.md)

**Comment by zombieyang** [comment]
上面两位说得差不多了。这些功能太具体并且有很多现成的了，目前puerts不考虑内置。
