### ISSUE TITLE
ue 异常困难的错误，终于重现出来了

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#536]
demo\MainObject.h
void PassJsFunctionAsDelegate(FCallback Callback, UWorld* world) const;

demo\MainObject.cpp
void UMainObject::PassJsFunctionAsDelegate(FCallback Callback, UWorld* world) const

[ue.d.ts]

QuickStart.ts
let world1 = (argv.getByName("GameInstance") as UE.GameInstance).GetWorld();
let obj = new UE.MainObject();

function test() {
    let proxy=toManualReleaseDelegate(IsJohn)
    console.log('obj1',obj,world1,proxy);
    obj.PassJsFunctionAsDelegate(proxy,world1);
    setTimeout(() => {
        test();
    }, 1000);  
}

test();

至此环境搭建完成，启动demo把地图保存为 test，运行一会然后控制台执行
open test ，重现打开关卡，出现如下错误

Puerts: Warning: (0x0000016CB51455F0) JS Execution Exception: ...\QuickStart.js:10: Error: passing a invalid object
Error: passing a invalid object
    at test (...\QuickStart.js:10:9)
    at ...\QuickStart.js:12:9

具体表现在this对象地址不是空，但是内容全部被破坏。如果你认为这是碰巧，那就错了，我在其它环境遇到过多次，这次比较好找错误，因为你只要做如下修改，问题就没有了。只要参数不是唯一一个就出问题了
MainObject.h MainObject.cpp
void PassJsFunctionAsDelegate(FCallback Callback) const;
void UMainObject::PassJsFunctionAsDelegate(FCallback Callback) const

[ue.d.ts]

QuickStart.ts
PassJsFunctionAsDelegate(proxy)
open test

**Comment by chexiongsheng** [comment]
？？？
UE引擎切换地图后，world就是无效的呀。
passing a invalid object这个错误恰恰是puerts提供的一个防止野指针操作的功能。这是一个作为亮点来宣传功能，可以有效防止C++操作野指针而导致更严重的后果。

**Comment by terst6** [comment]
我的真实环境是热更新完成后，重现打开主地图，所以累计运行正常，tsgamemode继承于cpp父类，所有功能都正常，直到调用cpp父类对象属性，发现 cpp对象被破坏了。道理上父类对象不应该被破坏才对喔

**Comment by chexiongsheng** [comment]
总之你写的例子就应该报那个异常

**Comment by terst6** [comment]
我重新做了一个测试，第一次访问cpp父类出错，后面就正确了，我提交一个新的bug上来
