### ISSUE TITLE
【unreal】C++Actor类->Ts类A->Ts类B。 创建B类实体，B的Constructor 会调用两次。

### ISSUE THREAD

**Issue by cchorseless** [Tencent/puerts#537]
## detail | 详细描述
<img width="413" alt="企业微信截图_16364518789602" src="https://user-images.githubusercontent.com/23015511/140903061-94750f8f-34b4-48c9-9744-970396fabfe3.png">
<img width="467" alt="企业微信截图_16364518566193" src="https://user-images.githubusercontent.com/23015511/140903088-7e534d37-9325-4c10-b9d9-161fb95e1e12.png">
<img width="224" alt="企业微信截图_16364518979014" src="https://user-images.githubusercontent.com/23015511/140903114-69eda5ba-c9d6-4e12-802d-8b0637628e0b.png">

**Comment by chexiongsheng** [comment]
UE的CDO也要构造

**Comment by terst6** [comment]
不要在 ts使用构造，才能在B类设置保持属性，把代码初始工作放begin里

**Comment by chexiongsheng** [comment]
> 不要在 ts使用构造，才能在B类设置保持属性，把代码初始工作放begin里

题主问的就不是这个，别瞎掺和啊。

**Comment by cchorseless** [comment]
> UE的CDO也要构造
明白了
