### ISSUE TITLE
ue刷新地图后，第一次从timer里访问父类无效

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#538]
1.
demo\puerts_unreal_demoGameModeBase.h

public:
		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		FString Text = TEXT("Test");

2.
TSGameMode.ts
import * as UE from 'ue'

export class TSGameMode extends UE.puerts_unreal_demoGameModeBase {
    N:number
    //@cpp:int
    T:number

    ReceiveBeginPlay(): void {
        this.T=0
        this.N=Math.random()
        console.warn("TSGameMode.ReceiveBeginPlay",this.N);
        this.test();
    }

    //@no-blueprint
	test():void {
        console.warn("test.setTimeout", this.Text,this.T,this.N);
    	setTimeout(()=>{this.T++;this.test()}, 1000)
    }
}

export default TSGameMode;

3.把默认地图保存为test

4.set gamemode TSGameMode
运行demo后，控制台重新打开地图 open test 出现以下错误，这里重现代码后续可以正常运行，我的代码会中断后面的逻辑

Puerts: Warning: (0x000001B9CF437F70) TSGameMode.ReceiveBeginPlay,0.2905605733394623
Puerts: Warning: (0x000001B9CF437F70) test.setTimeout,Test,1,0.2905605733394623
LogLoad: Took 0.048158 seconds to LoadMap(/Game/UEDPIE_0_test)
Puerts: Warning: (0x000001B9CF437F70) JS Execution Exception: ...\TSGameMode.js:13: Error: access a null object
Error: access a null object
    at Object.test (...\TSGameMode.js:13:9)
    at ...\TSGameMode.js:15:33
Puerts: Warning: (0x000001B9CF437F70) test.setTimeout,Test,2,0.2905605733394623
Puerts: Warning: (0x000001B9CF437F70) test.setTimeout,Test,3,0.2905605733394623
Puerts: Warning: (0x000001B9CF437F70) test.setTimeout,Test,4,0.2905605733394623

**Comment by terst6** [comment]
如果在语句前面增加一个条件
if (this.T<5)setTimeout(()=>{this.T++;this.test()}, 1000)
在我的电脑上上面的错误不会出现，但是把5改大就出现了

**Comment by chexiongsheng** [comment]
这也是正常的
切换地图GameMode会析构然后重新新建一个，并调用新的GameMode的ReceiveBeginPlay。
报错的Timer不是切换地图后的第一个，而是切换地图前的最后一个Timer。
我会 改下报错信息，改为access a invalid object。
