### ISSUE TITLE
[Unity]c#函数调用到ts，如果ts再次触发这个函数，但是传入的参数不同，新的调用使用的是旧的调用的参数

### ISSUE THREAD

**Issue by wtmsuperman** [Tencent/puerts#539]
我们启动时，会在ts测注册一个static委托到c#
client_code.JsCall.callCreateTs = CreateTsBehaviour

通过自定义的MonoBehaviour的Awake里，调用这个委托，通知ts创建对象，绑定起来，并触发ts测脚本的Awake，继承后来执行业务逻辑。

ui逻辑在Awake时调用Instantiate创建多个子节点，子节点上也有这个脚本用来通知ts创建对象（不同的类型）；断点看，发现子节点实例化时，委托调用传入了正确的参数，但是ts测传入的参数，是前一次调用的参数。
出现的现象就是这个ui又执行了一次awake，awake里创建item又触发ui的awake，死循环了。

本质上应该是c#调用js，js立即触发了c#调用js，相同的函数调用，就会出现问题，没用委托，用了eval也会出这个问题。

目前我们让c#调用js时，正常结束，实例化放在另一个函数里可以不触发这个问题。

测试代码，模拟一次递归调用，每次-1，正常应该输出4，3，2，1，目前达到最大调用数后强制退出

`

using UnityEngine;
using Puerts;

namespace PuertsTest
{
    public delegate void func(int value);

    public class Callback : MonoBehaviour
    {
        static JsEnv jsEnv;

        private static int callCount = 0;

        public class TestClass2
        {
            public void Test(int value)
            {
                if (callCount > 10)
                {
                    return;
                }
                
                if (value <= 0)
                {
                    return;
                }
                
                callCount++;
                var del = jsEnv.Eval<func>("calljs");
                value = value - 1;
                Debug.Log("cs call :" + value);
                del(value);
            }
        }

        void Awake()
        {
            jsEnv = new JsEnv();
            jsEnv.UsingAction<int>();
            jsEnv.Eval(@"
                        const CS = require('csharp');
                        var calljs =function(value){
                            console.log('js recv:' + value);
                            let obj = new CS.PuertsTest.Callback.TestClass2();
                            obj.Test(value);
                        }
            ");

            var test = new TestClass2();
            test.Test(5);
        }
}
`

业务中，是在Awake里实例化item触发了递归

应该输出4，3，2，1
实际输出：
![image](https://user-images.githubusercontent.com/1977474/141781507-822ac875-e2bd-4001-8e51-fef8700bbead.png)
js始终得到第一次参数，不管c#传入的是什么参数

**Comment by Joycraft** [comment]
这是你本应该每个脚本awake执行单独的函数, 结果你们搞成了每次都去执行同一个js里面的单例了吧

**Comment by Joycraft** [comment]
提供代码差不多, 光描述解决不了任何问题

**Comment by wtmsuperman** [comment]
是单独的脚本，没有单例，断点能看到c#调用参数是对的，参数传入到了ts侧才出现了问题

**Comment by Joycraft** [comment]
ts里面你require直接用就是个单例, 因为require只会执行一次就缓存了, 问题还是出在你的写法上

**Comment by Joycraft** [comment]
没代码这问题问得没有什么意义

**Comment by wtmsuperman** [comment]
你并没有看我的问题描述啊。这里并没有require，也没有单例，ts注册一个方法到c# static变量。每次调用时参数是不同的，这样来创建不同类型的ts对象。就算不用static变量，直接c#测eval，也会出问题。正常使用是没有问题的，触发了递归才会出现这个问题。改成异步调用错1帧，或者不出现递归，就没有问题。代码我尝试建立了一个空工程演示一下。

**Comment by throw-out** [comment]
你用的puerts版本是不是最新的?
你贴上来的代码中, 并没有声明全局变量calljs, 那么 var del = jsEnv.Eval<func>("calljs");是取不到有效值的

**Comment by Joycraft** [comment]
随便传个1进去就死循环了, 干嘛不把value -= 1;放在value == 0的判断前面,这样你不会执行后面的js

**Comment by Joycraft** [comment]
写个全局限制执行次数你就能log出来它的逻辑到底是怎么执行的

**Comment by wtmsuperman** [comment]
> 随便传个1进去就死循环了, 干嘛不把value -= 1;放在value == 0的判断前面,这样你不会执行后面的js

我是模拟一次递归啊，如果js测收到的参数是对的，最终肯定会安全退出递归啊，不知道你在说什么。。。

**Comment by wtmsuperman** [comment]
> 写个全局限制执行次数你就能log出来它的逻辑到底是怎么执行的

不过你说的对，我补上全局限制，不让他崩溃，输出日志

**Comment by throw-out** [comment]
验证了一下, 的确有问题, 如果是异步调用就正常.
猜想是js function处于调用堆栈中, 再次调用相同的js function的新参数未能正确入栈. 当然也可能和eval环境有关
![image](https://user-images.githubusercontent.com/45587825/141884718-b8ba26e3-81f8-4477-9a83-c0c3180bdd1c.png)

**Comment by throw-out** [comment]
我当前所用puetrs为v12, 并非最新版puerts

**Comment by zombieyang** [comment]
82f06c33ae7325f48d3b08ac4a0a9de0da66ffd5
这个commit所致的bug
