### ISSUE TITLE
[Unreal]如何在TS中以相对路径读写文件？

### ISSUE THREAD

**Issue by raytaylorlin** [Tencent/puerts#545]
翻了半天看到`CodeAnalyze.js`中通过UE的API `UE.FileSystemOperation.ReadFile`来读，但要求传入绝对路径，而且看上去要用上还很麻烦。如何在TS中以相对路径读写文件？

**Comment by chexiongsheng** [comment]
如果是默认裸v8，v8没有任何文件读写能力，都是通过c++去实现。c++怎么支持就怎么支持。

ps：CodeAnalyze.js调用的是我自己写的，满足我自己要求的一个c++api。你不一定要用，而且建议别用

**Comment by raytaylorlin** [comment]
那我再另外封装一个C++的API给TS用，但有个问题：有没有办法在C++获得当前正在执行中的TS文件的路径（这样我就可以用相对路径进行一些处理）？

ps：我是想要做些改造可以用TS来做UE的编辑器工具，所以会需要用到读写文件的功能

**Comment by chexiongsheng** [comment]
ts不行，执行的是js。
js里可以通过__filename获取文件名
