### ISSUE TITLE
UE4打包后出现无法找不到JavaScript Object的情况

### ISSUE THREAD

**Issue by mumumomo** [Tencent/puerts#549]
## error log | 日志或报错信息
![image](https://user-images.githubusercontent.com/92135806/142758629-c24166aa-4ca8-4294-9338-30024a9ee44a.png)

## context | 编译/运行环境
UE4：4.26  VS:2019
## how to reproduce | 复现

1. 按照以下步骤对TS进行环境搭建：
TypeScript编程环境搭建
下载（或clone）puerts；
拷贝unreal/Puerts目录到到BlockBreakerStarter/Plugins目录下；
命令行进入BlockBreakerStarter/Plugins/Puerts，执行命令：`node enable_puerts_module.js`
双击BlockBreaker.uproject打开项目，点击puerts的生成按钮，这步骤会生成UE API的TypeScript声明。

2. 在VSCode中编写TS脚本:
~~~typescript
import * as UE from 'ue'
class TS_BaseGun extends UE.Actor {
 
  Tsreadcontentflietext(): void{
   
       UE.KismetSystemLibrary.PrintString(this,"TSReadContentFlietext",true,true, new UE.LinearColor(0,0.66,1,1),2)
 
    }
}
export default TS_BaseGun;
~~~

3. 把TS映射的蓝图放到场景中,然后使用键盘键启功该函数
4. 然后在UEeditor中项目设置/打包/Additional Not-Asset Directories to Package”，把Content下的“JavaScript”目录添加进去
5. 然后进行打包，打包出现后运行调试

**Comment by chexiongsheng** [comment]
“键盘键启功该函数”具体是啥操作呢？

**Comment by mumumomo** [comment]
> “键盘键启功该函数”具体是啥操作呢？
![image](https://user-images.githubusercontent.com/92135806/142800995-cc9d0197-1c59-40ca-a35e-5198ca31dd82.png)

**Comment by chexiongsheng** [comment]
你修改了TS_BaseGun生成的蓝图么？

**Comment by mumumomo** [comment]
> 你修改了TS_BaseGun生成的蓝图么？
修改是什么意思，是在TS_BaseGun生成的蓝图中增加了键盘事件这样的吗

**Comment by mumumomo** [comment]
> 你修改了TS_BaseGun生成的蓝图么？

我今天打开这个蓝图，这个蓝图上带的方法都报错了，错误是找不到此函数

**Comment by chexiongsheng** [comment]
> > “键盘键启功该函数”具体是啥操作呢？
> > ![image](https://user-images.githubusercontent.com/92135806/142800995-cc9d0197-1c59-40ca-a35e-5198ca31dd82.png)

你这个在哪里添加的呢？关卡蓝图？还是TS_BaseGun那个蓝图？

**Comment by mumumomo** [comment]
> > > “键盘键启功该函数”具体是啥操作呢？
> > > ![image](https://user-images.githubusercontent.com/92135806/142800995-cc9d0197-1c59-40ca-a35e-5198ca31dd82.png)
> 
> 你这个在哪里添加的呢？关卡蓝图？还是TS_BaseGun那个蓝图？

在TS_BaseGun这个蓝图中

**Comment by chexiongsheng** [comment]
> > > > “键盘键启功该函数”具体是啥操作呢？
> > > > ![image](https://user-images.githubusercontent.com/92135806/142800995-cc9d0197-1c59-40ca-a35e-5198ca31dd82.png)
> > 
> > 
> > 你这个在哪里添加的呢？关卡蓝图？还是TS_BaseGun那个蓝图？
> 
> 在TS_BaseGun这个蓝图中

这么操作我这根本不响应键盘事件（简单PrintString也没反应），是漏了描述什么操作么？

**Comment by mumumomo** [comment]
![image](https://user-images.githubusercontent.com/92135806/142808065-955c4a20-7fd3-4ced-ae4a-130aafa83e81.png)


> > > > > “键盘键启功该函数”具体是啥操作呢？
> > > > > ![image](https://user-images.githubusercontent.com/92135806/142800995-cc9d0197-1c59-40ca-a35e-5198ca31dd82.png)
> > > 
> > > 
> > > 你这个在哪里添加的呢？关卡蓝图？还是TS_BaseGun那个蓝图？
> > 
> > 
> > 在TS_BaseGun这个蓝图中
> 
> 这么操作我这根本不响应键盘事件（简单PrintString也没反应），是漏了描述什么操作么？

![image](https://user-images.githubusercontent.com/92135806/142808080-38758ffa-ec22-49f7-b916-460c0075ae79.png)
你试一试这样可不可以

**Comment by chexiongsheng** [comment]
重现了，这种情况下，打包后构造函数就不调用了，但编辑器下却是调用的。

**Comment by mumumomo** [comment]
> 重现了，这种情况下，打包后构造函数没有调用了，但编辑器下却是调用的。

您知道这是一个什么问题引起的吗。而且目前我的TS生成的蓝图，蓝图中生成的函数也都消失了

**Comment by chexiongsheng** [comment]
这种情况下，UE打包后和编辑器下一些回调时序不一样导致的。

ps，“蓝图中生成的函数也都消失”我这没出现，其次，一个问题归一个问题，即使有问题也别在这讨论，可以另外开issue，描述好重现步骤

**Comment by mumumomo** [comment]
> 这种情况下，UE打包后和编辑器下一些回调时序不一样导致的。

> 这个回调时序怎么解决？








> ps，“蓝图中生成的函数也都消失”我这没出现，其次，一个问题归一个问题，即使有问题也别在这讨论，可以另外开issue，描述好重现步骤
好的，这个问题我暂时也没办法重现

**Comment by chexiongsheng** [comment]
记录下这种情况的时序
UTypeScriptGeneratedClass::Bind（PinedDynamicInvoker没设置）
NotifyObjectCreate（CDO）
NotifyObjectCreate（Not CDO，构造了，但此时没Bind）
UTypeScriptGeneratedClass::Bind
调用Ts方法，找不到绑定的对象。

最近在优化绑定方案，刚刚实测新方案在这场景下也不会有问题。测试完善后会更新上去。

**Comment by mumumomo** [comment]
> NotifyObjectCreate

好的，那我等更新。谢谢

**Comment by chexiongsheng** [comment]
新方案已经更新
