### ISSUE TITLE
UE这样绑定碰撞事件，是有什么问题吗？

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#554]
puerts_fps_demo

TS_Player.ts添加函数：
   OnComponentBoundEvent(HitComponent: $Nullable<UE.PrimitiveComponent>, OtherActor: $Nullable<UE.Actor>, OtherComp: $Nullable<UE.PrimitiveComponent>, NormalImpulse: UE.Vector, Hit: UE.HitResult) : void{
        console.log('OnComponentBoundEvent', HitComponent, OtherActor.GetName());
        setTimeout(() => {
            console.log('OnComponentBoundEvent setTimeout', HitComponent , OtherActor.GetName());
        }, 1000);
    }

  然后在函数里添加绑定  ReceiveBeginPlay(): void {        
        this.CapsuleComponent.OnComponentHit.Add(this.OnComponentBoundEvent) 
    }
在场景中拖一个ts player角色，
TS_Player
设置CapsuleComponent组件属性：
check:	Simulate Physics
	Simulation Generate Hit Eevnts
Collosion Presets: BlockAll

运行游戏提示错误：
Puerts: Error: (0x000001BE53274F10) js callback exception undefined:0: Error: access a null object
Error: access a null object

其它地方也遇到过这种null目标

**Comment by chexiongsheng** [comment]
学下ts/js的语法

**Comment by terst6** [comment]
你能给一个正确的语法吗？

**Comment by chexiongsheng** [comment]
this的问题不是js第一课么？

**Comment by terst6** [comment]
CapsuleComponent.是tsplayer组件，OnComponentBoundEvent是tsplayer函数，不用this用什么？

**Comment by chexiongsheng** [comment]
要bind一下。你们那没人用过js么？问问用过的人啊，js的this的作用域问题不是初学者必学的么？

**Comment by terst6** [comment]
this.CapsuleComponent.OnComponentHit.Add(this.OnComponentBoundEvent) 这个不是bind？this的对象在一个类里

**Comment by ljporljp** [comment]
> 要bind一下。你们那没人用过js么？问问用过的人啊，js的this的作用域问题不是初学者必学的么？

请教下：按照 this.CapsuleComponent.OnComponentHit.Add(this.OnComponentBoundEvent.bind(this)) 也是有问题的，参数接收那块有问题，但是直接用 lambda是好的。

**Comment by ljporljp** [comment]
我也碰到类似问题。。。。

**Comment by ljporljp** [comment]
是动态多播代理有问题
