### ISSUE TITLE
[Unreal]Node.js Win64 Shipping环境链接不通过，openSSL库相关符号重复定义

### ISSUE THREAD

**Issue by PrimaryFantasty** [Tencent/puerts#555]
### VS的项目生成控制台或UE编辑器的打包日志，内容太多有所省略：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2005	BIO_free 已经在 libnode.lib(libnode.dll) 中定义	PuertsTest	D:\work\ueproject\PuertsTest\Intermediate\ProjectFiles\libcurl_a.lib(bio_lib.obj)	1	
错误	LNK2005	BIO_new_mem_buf 已经在 libnode.lib(libnode.dll) 中定义	PuertsTest	D:\work\ueproject\PuertsTest\Intermediate\ProjectFiles\libcurl_a.lib(bss_mem.obj)	1	
错误	LNK2005	EVP_PKEY_assign 已经在 libnode.lib(libnode.dll) 中定义	PuertsTest	D:\work\ueproject\PuertsTest\Intermediate\ProjectFiles\libcurl_a.lib(p_lib.obj)	1	
错误	LNK2005	EVP_PKEY_new 已经在 libnode.lib(libnode.dll) 中定义	PuertsTest	D:\work\ueproject\PuertsTest\Intermediate\ProjectFiles\libcurl_a.lib(stack.obj)	1	
错误	LNK2005	d2i_RSAPublicKey 已经在 libnode.lib(libnode.dll) 中定义	PuertsTest	D:\work\ueproject\PuertsTest\Intermediate\ProjectFiles\libcurl_a.lib(rsa_asn1.obj)	1	
错误	LNK2005	X509_STORE_CTX_get0_chain 已经在 libnode.lib(libnode.dll) 中定义	PuertsTest	D:\work\ueproject\PuertsTest\Intermediate\ProjectFiles\libcurl_a.lib(e_aes.obj)	1	
错误	LNK1169	找到一个或多个多重定义的符号	PuertsTest	D:\work\ueproject\PuertsTest\Binaries\Win64\PuertsTest-Win64-Shipping.exe	1	

## context | 编译/运行环境
Windows10 x64 UE4.27.1 VS2019 在VS中选择win64 Shipping 或者 UE Editor下直接选择Win64 Shipping打包
## how to reproduce | 复现步骤
1.  从Puerts GitHub actions中下载最新的Nodejs_Bin，解压后将其下“nodejs"目录拷贝至Puerts的ThirdParty目录下，生成项目
2.  新建一个C++ UE项目，使用”自行启动JsEnv"的模式，模仿Puerts Github上的示例进行最简配置即可，Ts代码仅写了一句console.warn(); 此时如果在VS中选择Shipping环境生成，则应该就会报上述错误；
## more | 其他
1. 用了一个空的测试项目来测试了一下，还是一样的错误，我并没有主动编写任何和SSL相关的功能；
2. 尝试用vs的dumpbin工具解析libnode.lib，确实能看到那些重复的符号，但是在修改这些符号并再次转换回去的过程失败了；
3. NodeJS似乎是把它deps下的所有头文件都导出了，我想排除掉openssl的，Windows下，尝试查看puerts的nodejs构建脚本，但是在合并lib_uv_add_on_watcher_queue_updated.patch这个补丁时出错，另外，即便能合并下去，我也不清楚，具体应该用什么配置项之类的把openssl排除掉，请问这个能帮忙在构建脚本里面处理吗？

**Comment by dawnarc** [comment]
报错log显示工程有引用`libcurl_a.lib`，而这个库里面winssl的api，去掉`libcurl`的引用试下？

**Comment by FishOrBear** [comment]
在Http.build.cs中 或者其他的模块中 引用了libcurl 和 openssl 会导致试用nodejs时 Shipping编译不通过
