### ISSUE TITLE
ue settimeout返回值number保存到tarray导致ue崩溃

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#557]
调试不显示这个值数据，log这个值也出错

**Comment by chexiongsheng** [comment]
补充下详细信息

**Comment by chexiongsheng** [comment]
puerts的settimeout返回值不是number，其次，你为什么要保存在tarray呢？

**Comment by terst6** [comment]
显然不是number，但是鼠标提示返回值是number，不管什么类型，好像都应该支持打印吧？log打印都提示错误。一个模块大量用到了定时特性，比如写100个timerhandle，干脆直接保存到数组里，如果具柄不同就保存，在endplay里象征性地clear timeout，可以防止pendingkill后激活timer

**Comment by chexiongsheng** [comment]
保存到一个js的数组就可以了
