### ISSUE TITLE
[Unity]error when loading(sometime)

### ISSUE THREAD

**Issue by DOSexample** [Tencent/puerts#563]
init.js:24: SyntaxError: Unexpected token '.'

SyntaxError: Unexpected token '.'
Puerts.JsEnv.Eval (System.String chunk, System.String chunkName) (at Assets/TS/Puerts/Src/JsEnv.cs:210)
Puerts.JsEnv.ExecuteFile (System.String filename) (at Assets/TS/Puerts/Src/JsEnv.cs:193)
Puerts.JsEnv..ctor 

PuertsDLL.cs
old
```
#if PUERTS_GENERAL && !PUERTS_GENERAL_OSX
        [DllImport(DLLNAME, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr Eval(IntPtr isolate, byte[] code, string path);

        public static IntPtr EvalChecked(IntPtr isolate, string code, string path)
        {
            if (code == null)
            {
                throw new InvalidProgramException("eval null string");
            }
            return Eval(isolate, Encoding.UTF8.GetBytes(code), path);
        }
#else
```

new
```
#if PUERTS_GENERAL && !PUERTS_GENERAL_OSX
        [DllImport(DLLNAME, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr Eval(IntPtr isolate, byte[] code, string path);

        public static IntPtr EvalChecked(IntPtr isolate, string code, string path)
        {
            if (code == null)
            {
                throw new InvalidProgramException("eval null string");
            }
            System.Collections.Generic.List<byte> bufferTemp = new System.Collections.Generic.List<byte>( Encoding.UTF8.GetBytes(code) );
bufferTemp.Add(0);//last byte of const char*
            return Eval(isolate, bufferTemp , path);
        }
#else
```

**Comment by DOSexample** [comment]
Still getting error sometimesjs\main.js:4: SyntaxError: Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at executeModule (TsProj\js\puerts\modular.js:44:30)
    at require (TsProj\js\puerts\modular.js:99:17)
    at chunk:1:1
	
	
main.js
line 1 const module1 = require('module1');
line 2
line 3 module1.callMe('from john');
line 4

**Comment by zombieyang** [comment]
In design, the definition `PUERTS_GENERAL` is only available in c# console program. Are you sure you got error from these Method in PuertsDLL.cs ?

**Comment by zombieyang** [comment]
could you provide the content of `module1.js` for me?

**Comment by DOSexample** [comment]
I solved it by loading method.

Loader.js
namespace Puerts
{
    public interface ILoader
    {
        bool FileExists(string filepath);
        string ReadFile(string filepath, out string debugpath);
    }

    public class DefaultLoader : ILoader
    {
        private string root = "";

        public DefaultLoader():this("G:\\Unity\\TsProj\\js")
        {
        }

        public DefaultLoader(string root)
        {
            this.root = root;
        }

        private string PathToUse(string filepath)
        {
            return filepath.EndsWith(".cjs") ? 
                filepath.Substring(0, filepath.Length - 4) : 
                filepath;
        }

        private string GetPath(string filepath)
        {
            string fpath = System.IO.Path.Combine(root, filepath);
#if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
            fpath = fpath.Replace("/", "\\");
#endif
            return fpath;
        }

        public bool FileExists(string filepath)
        {
            if ( filepath.Contains("puerts") )//ex: Execute("puerts/init.js")
            {
                string pathToUse = PathToUse(filepath);
                return UnityEngine.Resources.Load(pathToUse) != null;//check unity resource
            }
            return System.IO.File.Exists( GetPath(filepath) );//check my path
        }

        public string ReadFile(string filepath, out string debugpath)
        {
            if ( filepath.Contains("puerts") )//ex: Execute("puerts/init.js")
            {
                string pathToUse = PathToUse(filepath);
                debugpath = filepath;
                UnityEngine.TextAsset file = (UnityEngine.TextAsset)UnityEngine.Resources.Load(pathToUse);//load from unity resource
                return file == null ? null : file.text;
            }
            debugpath = GetPath(filepath);
            return System.IO.File.ReadAllText(debugpath);//load from my path
        }
    }
}

Requre.cs
namespace PuertsTest
{
        public class Require : MonoBehaviour
        {
		JsEnv jsEnv;
                void Start()
                {
                    public jsEnv = new JsEnv();
                    jsEnv.Eval(@"const m = require('ts/main');");
                }
         }
}


//package.json "run:tsc": "tsc -p tsconfig.json -w"
G:\Unity\TsProj\ts\main.ts
import {callMe} from "./module1"

callMe('from john');

G:\Unity\TsProj\ts\module1.ts

console.log('module1 loading');

export function callMe(msg: any)
{
    console.log('callMe called', msg);
}

G:\Unity\TsProj\js\ts\main.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const module1_1 = require("./module1");
(0, module1_1.callMe)('from john');
//# sourceMappingURL=main.js.map

G:\Unity\TsProj\js\ts\main.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.callMe = void 0;
console.log('module1 loading');
function callMe(msg) {
    console.log('callMe called', msg);
}
exports.callMe = callMe;
//# sourceMappingURL=module1.js.map
