### ISSUE TITLE
Timer需进行异常处理

### ISSUE THREAD

**Issue by wchrt** [Tencent/puerts#57]
setInterval和setTimeout. 如果触发时抛出异常, 会导致计时器紊乱: 
1. 计时器抛出异常后, 该计时器没有被认为没有执行过, 在下一次Tick中又会被执行.
2. 一个计时器抛出异常, 会导致其他计时器也无法执行.
timer.js.txt源码: 
`
    function timerUpdate() {
        const now = Date.now();
        while (true) {
            const time = timers.peek();
            if (time && time.next_time <= now) {

                if(removing_timers.has(time.id)){
                    removing_timers.delete(time.id)
                }
                else {

                    time.handler(time.args);  //这里的调用如果抛出异常, 接下来的逻辑都会中断, 包括pop和调用其他的计时器
                    if (time.timeout) {
                        time.next_time = now + time.timeout;
                        timers.push(time);
                    }
                }
                timers.pop();
            } else {
                break;
            }
        }
    }
`

**Comment by chexiongsheng** [comment]
嗯，加个try-catch就可以了
