### ISSUE TITLE
[Unreal]我神奇的操作导致了声明报错，UE4 4.24版本 vs2019 puerts 1.0

### ISSUE THREAD

**Issue by ooijopk** [Tencent/puerts#570]
## detail | 详细描述
![image](https://user-images.githubusercontent.com/73647670/145155984-fe35f07a-5ea2-4729-b1eb-9741c8215603.png)

点了生成声明按钮,生成类 的构造变成了这样，不知道有没有遇到跟我一样的，之前正常生成是正常没有报错的，我不知道自己做了啥，就这样了，我无法解决这个问题，只能重新再建项目

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp#L39
在这加上把%号替换成_试试？
~~~c++
auto Ret = Name.Replace(TEXT(" "), TEXT("")).Replace(TEXT("-"), TEXT("_"))
        .Replace(TEXT("/"), TEXT("_")).Replace(TEXT("("), TEXT("_"))
        .Replace(TEXT(")"), TEXT("_")).Replace(TEXT("?"), TEXT("$"))
        .Replace(TEXT(","), TEXT("_"))..Replace(TEXT("%"), TEXT("_"));
~~~

**Comment by ooijopk** [comment]
这样做确实减少了很多错误，但还有错误剩余，最后我还是选择新建了项目，把原来的内容迁移过去，然后项目正常了，感谢您的回答！

**Comment by chexiongsheng** [comment]
这次出现，新建你将来还会出现。
其实就是你蓝图里的一些特殊符号导致。看到一个就添加一个替换旧可以了

**Comment by chexiongsheng** [comment]
> 如果定义变量函数名称有中文，就肯定出问题，我的解决办法是把safe name那个函数重新写一下，所有非字母数字的全部替换

变量和函数名称有中文肯定没问题。这早处理了。
他这里是参数名有特殊字符。
