### ISSUE TITLE
[Unity]在导出UniTask插件的Code时提示Type.FullName为空

### ISSUE THREAD

**Issue by TiuSong** [Tencent/puerts#573]
## error log | 日志或报错信息
TypeExtensions.cs：217 (替换成type.FullName??type.Name可解决报错问题)
![V `_8O9X%GOJ{9(2YA{@(QW](https://user-images.githubusercontent.com/13657983/145316297-f5910b82-75b0-41df-aba6-ba2e03c42d02.png)

定位到报错的导出类：Cysharp.Threading.Tasks.UnityBindingExtensions
![S6EDU7T 5%RV85R)UOS6_79](https://user-images.githubusercontent.com/13657983/145316639-b28eff4a-769a-4372-a156-4cea2d5d4b47.png)

**Comment by zombieyang** [comment]
本质问题是这个方法不支持生成
