### ISSUE TITLE
[Unity]泛型类的静态泛型方法，导出index代码出错

### ISSUE THREAD

**Issue by wtmsuperman** [Tencent/puerts#574]
如图的泛型基类
![image](https://user-images.githubusercontent.com/1977474/145546537-0b6e79bb-8ef7-4734-ac0c-0660e23f2d04.png)

导出index后的代码
![image](https://user-images.githubusercontent.com/1977474/145546725-6e571591-aa7f-4c5d-b75e-e482f737ca08.png)

可以看到泛型属性方法，正常导出成了any类型返回值
而静态方法，返回值类型是T，无法正常编译成js

目前可以手改成any，希望可以让泛型类静态方法也和静态属性一样，都是返回any

**Comment by zombieyang** [comment]
Typescript中的静态变量不支持泛型，只能用any解决。

**Comment by wtmsuperman** [comment]
另外补充一个问题，泛型基类被继承后，filter没法把他的方法过滤掉，始终会导出

**Comment by wtmsuperman** [comment]
> Typescript中的静态变量不支持泛型，只能用any解决。

这个没有问题，现在是代码生成成了T，希望可以生成成any

**Comment by zombieyang** [comment]
确认了下#216已经修过这个问题，在最新版本验证已经是any。你确认下你的版本哈

**Comment by zombieyang** [comment]
> 

这个我没复现，你有例子的话新提一个issue处理哈

**Comment by wtmsuperman** [comment]
> 确认了下 #216 已经修过这个问题，在最新版本验证已经是any。你确认下你的版本哈

我更新了现在是最新，还是一样，属性是any，方法不是

**Comment by wtmsuperman** [comment]
> > 另外补充一个问题，泛型基类被继承后，filter没法把他的方法过滤掉，始终会导出
> 
> 这个我没复现，你有例子的话新提一个issue处理哈

好的，我周一尝试弄一个最小化的例子

**Comment by zombieyang** [comment]
返回值那里确实有个大小写的bug，已修复。

下面这个问题有例子后下周另提issue哈
