### ISSUE TITLE
[Unreal]TS蓝图继承Actor直接放置在场景中，打包成dedicatedServer在log中报错can not find Binded JavaScript Object

### ISSUE THREAD

**Issue by websixsix** [Tencent/puerts#580]
## error log | 日志或报错信息
call ActorTS_C::ReceiveBeginPlay of 000001367BBAC380 fail: can not find Binded JavaScript Object
## context | 编译/运行环境
dedicated Server log模式
## how to reproduce | 复现步骤
1.写一个ts类ActorTS继承UE.Actor，重写ReceiveBeginPlay
2.将生成的TS蓝图放置到场景中
3.将Server Default Map设置成该场景
4.PackageProject -> build Target 设为 TestProjectServer，打包dedicate server
5.将打包后的TestProjectServer.exe创建快捷方式，然后用log模式打开

**Comment by chexiongsheng** [comment]
UE版本是哪个？
puerts是哪个版本呢？

**Comment by websixsix** [comment]
> UE版本是哪个？ puerts是哪个版本呢？

UE是4.27，puerts应该是9月13号的abcb481da85d9b5f5baa7f8947b6ca08ac5f839a

**Comment by chexiongsheng** [comment]
> puerts应该是9月13号

那你更新下，后面版本有针对这个错误做过修改。
