### ISSUE TITLE
[Unity] Debugger.setScriptSource 遇到复杂的情况大概率失效

### ISSUE THREAD

**Issue by wchrt** [Tencent/puerts#584]
环境: unity2019.4 puerts1.1.2 win10

无论是自己用ws调用Debugger.setScriptSource, 还是通过DevTools改代码, 都有较大概率不生效.
简单的改动都是能生效的, 比如修改一个循环调用的方法, 在里面加点日志输出, 是没问题的.
但是改动规模稍大, 比如在循环调用的方法中调用另一个方法, Debugger.setScriptSource后就没有效果了, 并且以后无论怎么改同一个js脚本, 也不会生效
尝试重新建立ws连接, 通过Debugger.scriptParsed收到好几个scriptId不同, 但是url缺都是这个js脚本的消息, 将这些scriptId对应脚本获取下来,内容正好是测试不生效时的那几次改动后的代码.
![企业微信截图_16395620862696](https://user-images.githubusercontent.com/20762359/146164498-3f227c0e-2b9f-4729-99b0-2e0c162635f2.png)

**Comment by wchrt** [comment]
这是一个必现的例子, 将'111'替换成变量aaa
![企业微信截图_16395683641407](https://user-images.githubusercontent.com/20762359/146180010-6a4b83ce-3795-4a1f-b86a-1b4391dd6382.png)
![企业微信截图_16395683845862](https://user-images.githubusercontent.com/20762359/146180054-156a6915-afe4-409e-9209-a4ab62b931eb.png)

**Comment by wchrt** [comment]
难受, 用nodejs测试也是同样的情况, 只能改很小的局部的代码, 这样对开发调试能有多大的用处

**Comment by zombieyang** [comment]
这个是 chrome devtool 协议限制导致的，setScriptSource 就是只能改函数内部本身的一些东西。
我理解的完美热重载应该根据情况来选择使用 setScriptSource 或是 清除模块缓存重新 require。这应该是一个第三方工具链。本身puerts_unity_demo里的热重载也只是抛砖引玉而已
