### ISSUE TITLE
[Unreal]TS继承UE.AnimInstance后作为动画蓝图的父类会出现can not find Binded JavaScript Object报错

### ISSUE THREAD

**Issue by websixsix** [Tencent/puerts#588]
## error log | 日志或报错信息
call RoleAnimBP_C::TestFunc of 00002839EC15D00 fail: can not find Binded JavaScript Object
## context | 编译/运行环境
UE 4.26/4.27  puerts版本：12月14日 4cb62ff94e2efbc26116ad06f6048778e7d2bfcb
## how to reproduce | 复现步骤
1.新建一个C++类继承UAnimInstance，再新建一个TS类继承这个C++类
2.创建一个动画蓝图继承这个TS类
3.TS类中实现一个函数，在蓝图中覆写该函数
4.在场景中调用该函数，log中出现报错

## more | 其他
ts直接继承UE.AnimInstance也有再经过上方 2 3 4 步骤，也有概率出现这个问题

**Comment by chexiongsheng** [comment]
4是怎么调用的呢？或者直接基于puerts_unreal_demo搞个重现工程？

**Comment by websixsix** [comment]
> 4是怎么调用的呢？或者直接基于puerts_unreal_demo搞个重现工程？

在BeginPlay里调用就会报错了。 后面测到 在编辑器里打开动画蓝图进行编译和保存，再运行游戏就不会报错了，但是关闭编辑器重新打开后运行游戏又会出现报错。 重现比较简单，我后续看看搞个重现工程

**Comment by chexiongsheng** [comment]
你更新到最新代码试试？

**Comment by websixsix** [comment]
> 

最新代码测试没什么问题了
