### ISSUE TITLE
[unity]支持apple M1，即osx arm64

### ISSUE THREAD

**Issue by zombieyang** [Tencent/puerts#591]

**Comment by zombieyang** [comment]
周末有热心群友帮忙看过，瓶颈在于v8没有osx arm64版本。

根据nodejs issue库里的说法，v8 8.6+才支持apple silicon。
这个事情会和v8/nodejs升级合并处理，提上日程。 #608

**Comment by chiuan** [comment]
> 

那nodejs版本是否支持apple silicon了？

**Comment by zombieyang** [comment]
更新：编译了一份arm64 nodejs版puerts，给某位网友试过运行会crash。

大概三月份我才会拿到一台m1调试，或者这段时间有愿意帮忙调试C++的朋友可以联系我

**Comment by plumeworld** [comment]
m1的支持怎么样啦

**Comment by zombieyang** [comment]
快了

**Comment by chexiongsheng** [comment]
我试了能跑了，之前编译M1版本放到工程一直崩溃，后面删了工程里头的x64 x86架构的就运行正常了。
重点
1、要删了工程里头的x64 x86架构的库；
2、arm64的库要放在plugins/arm64目录下；

**Comment by chiuan** [comment]
> 

可以发一下这个M1版本的库文件吗~谢谢

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts/releases/tag/tempm1
临时版本，下个月我拿到m1之后会整正式版

**Comment by zombieyang** [comment]
`unity-1.4.0-preview.0`已带上

**Comment by chexiongsheng** [comment]
> @zombieyang 只有untiy支持了吗，unreal版本不支持m1/osx arm64的吗

主要是arm64版本的v8的编译。unity用静态版本的，我加了动态库版本的：https://github.com/puerts/backend-v8/releases/tag/V8_9.4.146.24_230423

你试试看，用这个覆盖后，然后这里加个ARM64判断：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L75 ， include Blob/macOS_arm64/SnapshotBlob.h 文件
