### ISSUE TITLE
[Unity]Linux下无法链接调试器

### ISSUE THREAD

**Issue by windyslove** [Tencent/puerts#592]
## detail | 详细描述
linux 下断点无法命中，使用了WaitDebuggerAsync，一运行就直接返回debugger链接成功了，而且rider设置的调试器却连不上

![image](https://user-images.githubusercontent.com/6903175/146671467-98b136cc-5e7d-4276-95c7-d615d17140a1.png)

## context | 编译/运行环境
deepin 20.3
Linux windys-dde-PC 5.10.60-amd64-desktop #3 SMP Tue Nov 9 20:52:29 CST 2021 x86_64 GNU/Linux

**Comment by zombieyang** [comment]
如果不使用Async版本的WaitDebugger呢

**Comment by windyslove** [comment]
> 如果不使用Async版本的WaitDebugger呢

**不适用async依然不会等待调试器连接**
![image](https://user-images.githubusercontent.com/6903175/147253869-df85661b-39d0-4189-9f8c-e4d637dc9b1e.png)
![image](https://user-images.githubusercontent.com/6903175/147253935-fe3e21f1-4ccc-433a-8cf4-4698f6523eaf.png)
![image](https://user-images.githubusercontent.com/6903175/147253962-2597c8d7-7de6-485c-be8a-adc414253ec3.png)

**Comment by chexiongsheng** [comment]
Linux默认没开Debug支持。
需要加WITH_INSPECTOR宏重新编译plugin

**Comment by windyslove** [comment]
> Linux默认没开Debug支持。 需要加WITH_INSPECTOR宏重新编译plugin

好的
