### ISSUE TITLE
ue4 蓝图结构体疑是bug情况，这个是否是bug或者操作有问题???

### ISSUE THREAD

**Issue by ooijopk** [Tencent/puerts#596]
## detail | 详细描述
![image](https://user-images.githubusercontent.com/73647670/146893490-11db74b8-84de-40ac-9eed-015b48d777b3.png)
在GameInstance的蓝图中使用该结构体声明变量，能在ue.d.ts中生成声明，
![image](https://user-images.githubusercontent.com/73647670/146893886-16a4ebae-5f94-499f-9ad8-0f918f6118a9.png)
再次点击时，ue.d.ts中的该结构体声明消失，请问这是否有问题还是使用方法错误，想知道正确的使用，还望告知，万分感谢!

**Comment by ooijopk** [comment]
复现，随便用蓝图写一个结构体，在gameInstall中声明变量，点击按钮生成ue的ts声明，发现生成成功，然后再次点击，声明消失,gameInstall里面的变量也消失....

**Comment by chexiongsheng** [comment]
默认结构体都不生成。声明了该类型的变量才会生成。
所以问题在于那个变量时有时无。
而变量是UE反射API返回的结果，UE反射返回有就有，没就没。直白说这就是UE的返回。而我猜是你没保存蓝图并编译导致的

**Comment by ooijopk** [comment]
可能真的是没有保存蓝图并编译导致的，现在复现不了，可能成功了，感谢回复

**Comment by ooijopk** [comment]
![image](https://user-images.githubusercontent.com/73647670/146923474-ce2cc8c0-f040-4b23-948b-37313dd8352c.png)
问题复现了，ts的声明消失了，而且是在点击了保存蓝图并编译的情况
![image](https://user-images.githubusercontent.com/73647670/146923639-f8478d58-c4f3-4d65-9c25-35645b2df692.png)
gameInstance里面声明的变量也消失了想不明白啥原因

**Comment by ooijopk** [comment]
ue4 版本 4.24.3    ，声明变量是方式是在蓝图里面声明一次，在ts里面也声明了一次，导致了冲突，会不会是这个问题呢，再研究吧
