### ISSUE TITLE
[Unreal]当前版本对于TS绑定的修改有些问题

### ISSUE THREAD

**Issue by morirain** [Tencent/puerts#599]
只影响打包，编辑器无影响。
bug情况是部分TS能够成功绑定并且正常运行，但有些则是只作为蓝图运行，没有成功绑定，log中无报错。
在设置里修改虚拟机的数量大于1后，bug消失。

**Comment by chexiongsheng** [comment]
有重现的例子么？

**Comment by chexiongsheng** [comment]
另外你是哪个版本的puerts呢？

**Comment by morirain** [comment]
从ba2e07c开始
关于重现，我用uedemo进行了测试，ue版本4.27
开启自动绑定，虚拟机数量1，修改GameMode为TsTestGameMode，打包设置只修改了复制Javascript文件。
```
Log中相关信息
[2021.12.27-07.18.16:304][  0]Puerts: Display: (0x0000014D3F50BD90) Bind module [TsTestGameMode] 
[2021.12.27-07.18.16:305][  0]LogLoad: Game class is 'TsTestGameMode_C'
```
后面的log中没有收到TS的ReceiveBeginPlay消息，而是执行了TsTestGameMode的蓝图BeginPlay。
同样，虚拟机设置为2之后bug消失。

编辑器下则是正常的，我目前看到的是只影响GameMode和PlayerController这样固定的几种类型？像Character类就正常绑定了。

**Comment by chexiongsheng** [comment]
好的，我看看
