### ISSUE TITLE
[Unreal]tarray的性能问题,puerts里面的tarray 元素引用类型问题

### ISSUE THREAD

**Issue by weyenrooney** [Tencent/puerts#604]
## detail | 详细描述
代码片段如下
const StGirdBlueprint= blueprint<typeof UE.st_grid>("UserDefinedStruct'/Game/HeightMap/blueprint/st_grid.st_grid'");
        //let  list:TArray<UE.st_grid>;
        let  list:TArray<$Ref<UE.st_grid>>;
        //<ContainerKVType<$Ref<CGrid>>>
        list=UE.NewArray<ContainerKVType<$Ref<UE.st_grid>>>(StGirdBlueprint);
        let TestStruct = UE.UserDefinedStruct.Load("UserDefinedStruct'/Game/HeightMap/blueprint/st_grid.st_grid'");
        let  grid=$ref(UE.NewStruct(TestStruct) as UE.st_grid);
        $unref(grid).h=100;
        list.Add(grid)
        let  num=list.Num();
        let  t=list.Get(0) as $Ref<UE.st_grid>;
        //@ts-ignore
       t.h+=100;
        let   t1=list.Get(0)
经过测试array 中使用结构体,获取出来的数据是复制的副本,想改成ref引用类型经过测试也不行,
有什么办法像ue中的unlua   array.GetRef()获取的是结构体的引用,这样修改成员变量而不需要再设置回array中,性能比较好

**Comment by terst6** [comment]
蓝图里可以覆盖ts函数，结构体可以定义在cpp或者ts里，不要定义在蓝图里，ts不能继承于蓝图。相当于cpp第一级，ts第二级、蓝图第三级，这种继承关系用得多。我lua函数全部转ts了，包括蓝图的函数。lua与蓝图混编等都很成熟稳定了

**Comment by weyenrooney** [comment]
好的谢谢,那就是设计规范的问题,按照你说的规范就可以了,顺便问一下,ts里面定义的结构体,蓝图继承ts之后能在编辑器里面使用么

**Comment by chexiongsheng** [comment]
最早的Get就是返回引用，但后面出于安全考虑，改为值拷贝了：https://github.com/Tencent/puerts/commit/b37dbb8bacee3f243fbfea2bf1394dfd5e91fa5a
添加个名字不同，和原来Get逻辑一样的函数就可以了。

**Comment by chexiongsheng** [comment]
不过我觉得添加这么个接口挺混淆的，当元素是int之类的基本类型，或者FString这些，都是值拷贝，只有类似Struct，Array这些才是返回引用（这在unlua里也是）。换句话说，接口名字和真实功能不符合，所以我不会加这样的接口，有需要你可以自行添加。
