### ISSUE TITLE
[unreal][nodejs] 请求异常

### ISSUE THREAD

**Issue by FishOrBear** [Tencent/puerts#605]
ue5 nodejs环境下.使用以下代码无法返回值,怀疑和https://github.com/Tencent/puerts/issues/460 相关.

npm i got

```typescript
//hack got
globalThis.versions = {};
//@ts-ignore
globalThis.setImmediate = (callback: (args: void) => void) => setTimeout(callback, 1);

import got from 'got';

got.get('http://127.0.0.1/').then(r =>
{
    console.log(r.body);
});
```

经过调试,发现似乎是这个流无法到达.
![image](https://user-images.githubusercontent.com/19372111/147637007-a882fabd-ee11-4cba-a934-a2447760216b.png)

有时候可以响应 有时候永远无法响应

**Comment by chexiongsheng** [comment]
#460 早就解决了

**Comment by chexiongsheng** [comment]
我看你用到了setTimeout，不知道是不是和puerts用ue的timer覆盖了nodejs的timer导致，你改改这里

**Comment by FishOrBear** [comment]
我看这个代码也无法到达 可能和这个有关系 

import http from 'http';
http.request('http://www.youdao.com/w/eng/request/#keyfrom=dict2.index', r =>
{
    //无法到达这里
    console.log(r);
});


但是https是可以到的
// import https from 'https';
// https.get('https://www.baidu.com/', r =>
// {
//     console.log(r);
// });

**Comment by chexiongsheng** [comment]
setTimeout改了么？

**Comment by FishOrBear** [comment]
会这样: unhandledRejection,ReferenceError: setTimeout is not defined,ReferenceError: setTimeout is not defined

**Comment by FishOrBear** [comment]
我看这个请求的也有Pipe 所以我怀疑问题和原先的有点类似
![image](https://user-images.githubusercontent.com/19372111/147641263-28540385-320f-400b-8a20-4d6b9a4c33d5.png)

**Comment by FishOrBear** [comment]
非常奇怪
```

//先跑这个
import https from "https";
https.get('https://www.baidu.com/');

//之后可以了...
got.get('https://www.baidu.com/').then(r =>
{
    console.log(1);
});
got.get('http://127.0.0.1/').then(r =>
{
    console.log(2);
});
```

**Comment by FishOrBear** [comment]
nodejs原生的setTimeout无法响应回调.奇怪..

import { setTimeout } from "timers";

**Comment by chexiongsheng** [comment]
> nodejs原生的setTimeout无法响应回调.奇怪..
> 
> import { setTimeout } from "timers";

可能这个本来和全局那个就不是一个。你用之前没加no-browser-global就有正常的setTimeout了。不过用了也解决不了第一个问题。第一个问题我再看下是什么原因。

**Comment by FishOrBear** [comment]
import { setTimeout } from "timers";
用这个代码在编辑器里面可以跑 但是行为会很奇怪 会导致崩溃
而且会立即执行.

**Comment by chexiongsheng** [comment]
> 这个流无法到达.

定位发现是没有io事件导致的，我以为我哪里写得有问题，但我直接用nodejs官方的嵌入式例子来试也是一样。

**Comment by chexiongsheng** [comment]
我之前的测试的一个下载文件，然后写文件的例子，在puerts以及官方嵌入式例子都能跑通。
但如果我把这个例子的写文件的部分去掉，只保留网络下载，就都不能跑通了

**Comment by FishOrBear** [comment]
怎么办 无解了吗 只能这样去hack它了吗 先跑个代码 让其他代码可以跑起来

**Comment by chexiongsheng** [comment]
好像我只保留网络下载，在nodejs跑也是不行的

**Comment by chexiongsheng** [comment]
这个代码，我用nodejs跑也是执行不end那个回调的逻辑

~~~javascript
const fs = require('fs');
const http = require('http'); 

const saveFileName = "nodejs_bin_14.16.1.dl.tgz";
if (fs.existsSync(saveFileName)) {
    fs.unlinkSync(saveFileName);
    console.log ("unlinkSync " + saveFileName);
}
//const file = fs.createWriteStream(saveFileName);
let beginTime = new Date();
let i = 0;
const request = http.get("http://127.0.0.1:8080/nodejs_bin_14.16.1.tgz", function (response)
{
    //response.pipe(file);
    //response.on('data', function (chunk) {
    //    console.log(`${i++} Received ${chunk.length} bytes of data.`);
    //});
    response.on('end', function () {
        let endTime = new Date();
        console.log ("down using " + (endTime.getTime() - beginTime.getTime()) + "ms");
        //file.close();
        //fs.unlinkSync(saveFileName);
        //console.log ("unlinkSync " + saveFileName);
    });
});
~~~

**Comment by FishOrBear** [comment]
我简化了用例,下面这个代码可以在nodejs上跑,但是在puerts+nodejs上不行.

```javascript
const http = require('http');
http.get("http://127.0.0.1", function (response)
{
    console.log(1);//这里到不了
});
```
