### ISSUE TITLE
[Unity] 把cs对js的调用缓存到delegate里，嵌套调用会导致unity crash

### ISSUE THREAD

**Issue by Zmrn** [Tencent/puerts#610]
我用这样的方式从CS里调用JS代码，把delegate缓存了起来。

![QQ图片20211231162026](https://user-images.githubusercontent.com/16983764/147812225-e6fe6acc-a8b6-4718-81a7-38aaafff2d5f.png)
![2](https://user-images.githubusercontent.com/16983764/147812229-f3e49d2b-6d78-4dfa-b1ce-b559693009eb.png)

但是嵌套的调用会导致unity crash

![0](https://user-images.githubusercontent.com/16983764/147812230-2ad9ffe5-ab27-4397-a122-5c54470a62f4.png)
↑unity会在红框处crash

不缓存delegate的话就没有问题
![3](https://user-images.githubusercontent.com/16983764/147812270-92b307c1-2254-4194-acf5-2a94629dd9d9.png)
↑这样的话就可以正常运行

![4](https://user-images.githubusercontent.com/16983764/147812291-9711c673-7bca-4d00-92d1-c61b40bf802f.png)

为什么会这样呢？delegate的缓存能节省不少性能，有没有可能只用一个delegate解决这个问题？

**Comment by zombieyang** [comment]
更新到最新版本即可，前两天修过了

**Comment by zombieyang** [comment]
928baa81dd28e7c966713cb8423a417fd5485332

**Comment by Zmrn** [comment]
> [928baa8](https://github.com/Tencent/puerts/commit/928baa81dd28e7c966713cb8423a417fd5485332)

感谢
