### ISSUE TITLE
[unreal]使用蓝图继承Ts的类之后，每次编译蓝图都会提示call TsConstruct fail

### ISSUE THREAD

**Issue by scutjames85** [Tencent/puerts#613]
## detail | 详细描述
创建蓝图继承TsTestGameMode。然后修改蓝图的BeginPlay之后编译蓝图
![image](https://user-images.githubusercontent.com/82795479/148052366-701863c7-1fdd-4017-9f41-26a870b4d7a2.png)

编辑器Output提示如下:
![image](https://user-images.githubusercontent.com/82795479/148052176-c2e96067-a6ba-48e6-ba0f-6b885ddd58f5.png)

运行时，修改是生效的，只是每次编译都有这个报错好像很诡异。

请问大佬，是哪里姿势不正确么？

**Comment by chexiongsheng** [comment]
最新版本应该不会有这类错误

**Comment by scutjames85** [comment]
刚刚拉到最新，版本在主干863ae38。
引擎版本是官版的 4.27.2

刚启动编辑器直接编译一个蓝图的GameMode，该蓝图继承了Ts定义的GameMode，这样的话没有报错，但是PIE运行一次游戏之后，每次编译都会报上面说的错误（虽然编译是成功的）。
![image](https://user-images.githubusercontent.com/82795479/148184902-511851e3-4359-4199-bfd0-7ff15deb943f.png)


录制了GIF如下：
![Bug](https://user-images.githubusercontent.com/82795479/148183452-0a4d5a9d-536c-4ec5-9b5d-a3db44a0840e.gif)

希望大佬查证一下，谢谢

**Comment by scutjames85** [comment]
> 最新版本不会有这类错误

刚刚拉到最新，版本在主干863ae38。
引擎版本是官版的 4.27.2

刚启动编辑器直接编译一个蓝图的GameMode，该蓝图继承了Ts定义的GameMode，这样的话没有报错，但是PIE运行一次游戏之后，每次编译都会报上面说的错误（虽然编译是成功的）。
![image](https://user-images.githubusercontent.com/82795479/148184902-511851e3-4359-4199-bfd0-7ff15deb943f.png)


录制了GIF如下：
![Bug](https://user-images.githubusercontent.com/82795479/148183452-0a4d5a9d-536c-4ec5-9b5d-a3db44a0840e.gif)

希望大佬查证一下，谢谢
