### ISSUE TITLE
[Unreal]可否将某个指定的引擎常用但非BlueprintCallable类型函数暴露给TS

### ISSUE THREAD

**Issue by dawnarc** [Tencent/puerts#614]
## detail | 详细描述
比如，我在BeginPlay()中创建SkeletalMeshCompnent：

![image](https://user-images.githubusercontent.com/3351764/148096433-0a52e48b-0aed-4ded-9aed-27783ba49f1a.png)

此时我需要调用非BlueprintCallable函数`UActorComponent::RegisterComponent()`

![image](https://user-images.githubusercontent.com/3351764/148095859-43ff80a1-2482-46de-b480-612ca45fa004.png)

不知有没办法可以不自己封装工具函数，来实现调用引擎的非BlueprintCallable函数。  
若可以修改PuerTS源码来实现，可否指点下大概思路，谢谢！

**Comment by morirain** [comment]
[https://github.com/Tencent/puerts/blob/master/doc/unreal/template_binding.md](https://github.com/Tencent/puerts/blob/master/doc/unreal/template_binding.md)
看这个

**Comment by terst6** [comment]
这种处理方式，不如把组件隐藏起来，该显示的时候显示出来。不影响速度

**Comment by dawnarc** [comment]
@morirain 非常感谢 :thumbsup:，前几天没来得及尝试，目前已按你给的文档解决。
@chexiongsheng 车神，不知可否将ActorComponent::RegisterComponent()的ts扩展加入官方版本，运行时动态创建Component的需求还是挺多的 :grin:
![image](https://user-images.githubusercontent.com/3351764/148632629-77e659ca-b84a-4f41-8501-875b32a26c5e.png)
