### ISSUE TITLE
更新到最新版本后，使用PIE启动游戏会报找不到JavaScript对象的错误

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/puerts#616]
## detail | 详细描述
使用的继承关系如下
Character
CppCharacter
TsCharacter
BP_Character
经过调查，在加载BP_Character的时候，返回的UClass的ClassConstructor未指向UTypeScriptGeneratedClass::StaticConstructor
将PuertsModule::Enable中的宏`if !WITH_EDITOR`去掉后，返回的UClass可以正确指向UTypeScriptGeneratedClass::StaticConstructor。
我对于puerts的框架还不够熟悉，感觉不应该随便的就把宏去掉（这里肯定是设计如此的），查了一天没有找到问题所在，求作者指点迷津。

**Comment by iNeverSleeeeep** [comment]
我尝试合入了 #615 ，依然没有解决，看起来 #615 解决的是在编辑器内勾选了`Standalone Game`，而我使用的是`Selected Viewport`，请问如果我如果去掉`#if !WITH_EDITOR`宏会有什么问题？

**Comment by iNeverSleeeeep** [comment]
合入了 863ae38 之后，还是存在一个空指针异常的问题。
我在`ProjectSettings/Maps & Modes/Selected GameMode`里面设置了`Default Pawn Class`为BP_Character后，在结束游戏运行时，UFunction::Invoke抛出异常Func为空。这个Function是调用的TsCharacter内实现的ReciveControllerChanged，而且FEditorDelegates::EndPIE是先于这个Invoke执行的（堆栈上是从CleanupGameViewport进入的，刚好晚于FEditorDelegates::EndPIE），是不是应该把JsEnv的执行时机移动到更之后一些（我没有找到更后面的Delegate）。

**Comment by chexiongsheng** [comment]
没看到有ReciveControllerChanged，这是你们自己搞的回调么？
