### ISSUE TITLE
最新版本在PIE模式结束游戏运行时，UFunction::Invoke会报Func为空的异常

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/puerts#617]
## detail | 详细描述
使用的继承关系如下
Character
CppCharacter
TsCharacter
BP_Character
我在ProjectSettings/Maps & Modes/Selected GameMode里面设置了Default Pawn Class为BP_Character后，在PIE模式下结束游戏运行时，UFunction::Invoke抛出异常Func为空。这个Function是调用的TsCharacter内实现的ReciveControllerChanged，而且FEditorDelegates::EndPIE是先于这个Invoke执行的（堆栈上是从CleanupGameViewport进入的，刚好晚于FEditorDelegates::EndPIE），是不是应该把JsEnv的执行时机移动到更之后一些（我没有找到更后面的Delegate）。

**Comment by iNeverSleeeeep** [comment]
找到了FGameDelegates::Get().GetEndPlayMapDelegate()，简单测试了没有问题，是否应该替换为这个Delegate？

**Comment by chexiongsheng** [comment]
先确认下问题。按道理即使在EndPIE后执行也不会触发你说的那个异常。
你的ReciveControllerChanged是自己搞的回调么？好像没搜索到有这函数

**Comment by iNeverSleeeeep** [comment]
我使用的是UE5版本，这个函数是在Pawn.h:350行
```c++
/** Event called after a pawn's controller has changed, on the server and owning client. This will happen at the same time as the delegate on GameInstance */
UFUNCTION(BlueprintImplementableEvent)
void ReceiveControllerChanged(AController* OldController, AController* NewController);
```

**Comment by iNeverSleeeeep** [comment]
![puerts crash1](https://user-images.githubusercontent.com/8469299/148313415-b1b8f0a0-df15-4df5-b473-8f9b17c915f8.png)
![puerts crash2](https://user-images.githubusercontent.com/8469299/148313419-aa66557e-20ce-4520-8299-9fb416b34de7.png)
