### ISSUE TITLE
PIE模式下FFunctionTranslator::CallJs时执行到Return->JsToUE时发生崩溃

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/puerts#622]
## detail | 详细描述
崩溃时显示Arguments.size()为0，实际这个函数是有三个参数的，在FFunctionTranslator::Init中打断点发现是正确的初始化了Arguments的三个参数。
进一步使用内存断点，发现本次崩溃的FFunctionTranslator在之前运行中已经在JsEvnImpl::MakeSureInject中已经被析构了（通过`TsFunctionMap.erase(Function)`)。但是在JsEnvImple::InvokeTsMethod中执行到`FuncIter->second.FunctionTranslator`时使用的还是这个对象(通过this值看到地址是同一个)。
如果需要的话我可以进一步提供一些信息。

**Comment by iNeverSleeeeep** [comment]
我尝试改了一下，好像没问题了，大佬看一下是否应该这样改？
```c++
auto FUncIter = TsFunctionMap.Find(Function);
if (FuncIter == TsFunctionMap.end())
{
    TsFunctionMap[Function] = {
        XXX
    }
}
else
{
    TsFunctionMap[Function].JsFunction = XXX;
}
```

**Comment by chexiongsheng** [comment]
MakeSureInject里头erase后马上重新赋值了，而在InvokeTsMethod那查找返回的应该是重新赋值的值。
所以应该不是你说的原因（ps，如果是这个原因，应该很容易触发，但没其它项目反馈这样的问题）。
有能重现的简单工程么？

**Comment by iNeverSleeeeep** [comment]
我之前理解错了，确实这里有些奇怪。现在没有简单工程可以复现，我再继续调试看一下是什么问题引起的吧。

**Comment by iNeverSleeeeep** [comment]
这个问题是我最近升级了puerts之后才出现的，大概是从去年10月份的版本升级过来的

**Comment by chexiongsheng** [comment]
除非你有多线程访问，我看了下代码，TsFunctionMap要么找不到，要么找到的就是最新的。

**Comment by iNeverSleeeeep** [comment]
大概猜到原因了，是在InvokeTsMethod的过程中又触发了一次修改TsFunctionMap。导致自身被析构了。

**Comment by chexiongsheng** [comment]
哪里会触发TsFunctionMap修改呢？

**Comment by iNeverSleeeeep** [comment]
在FUnctionTranslator::CallJs中，执行到JsFunction->Call的时候修改了TsFunctionMap，因为在那个函数里面生成了新的TsCharacter。之后再执行Return->JsToUE的时候就崩溃了

**Comment by chexiongsheng** [comment]
新的TsCharacter是啥？和TsFunctionMap有啥关系呢？

**Comment by chexiongsheng** [comment]
你的意思是js的执行中，会触发本类的重新MakeSureInject么？

**Comment by chexiongsheng** [comment]
你是调用了一个CDO对象的方法，重定向到js后，又触发了本类的对象的构造么？

**Comment by iNeverSleeeeep** [comment]
确实是触发了本类的重新MakeSureInject

**Comment by iNeverSleeeeep** [comment]
等我给你一下重新触发MakeSureInject的堆栈

**Comment by iNeverSleeeeep** [comment]
![puerts1](https://user-images.githubusercontent.com/8469299/148365306-c179a6dc-8cfe-4fdf-9ad9-146950535b43.png)
![puerts3](https://user-images.githubusercontent.com/8469299/148365315-6486f76f-05c3-41ec-ab60-3e93449f2cae.png)

**Comment by chexiongsheng** [comment]
你的栈和你说的不一致。
是要在FunctionTranslator::CallJs执行的过程中，触发本类的MakeSureInject。
你发的栈是正常的

**Comment by iNeverSleeeeep** [comment]
我没有截图那么长。。 那再等我发一个

**Comment by iNeverSleeeeep** [comment]
我用红色箭头指向了，这个是入口的地方，可以和上面发的第一个截图对照看一下
![puerts4](https://user-images.githubusercontent.com/8469299/148366595-cfe41784-8f9f-43f0-9df0-a503776bbb91.png)

**Comment by chexiongsheng** [comment]
你第一个CallJs是不是CDO呢？然后你在该类的函数SpawnActor，输入的是自身类么？

**Comment by chexiongsheng** [comment]
> 你第一个CallJs是不是CDO呢？然后你在该类的函数SpawnActor，输入的是自身类么？

贴下那CallJs执行的逻辑？或者参考这逻辑写个简单能重现的例子？

**Comment by iNeverSleeeeep** [comment]
是通过DataTable获取的Class，然后执行的SpawnActor，不是输入的自身类。

**Comment by chexiongsheng** [comment]
那你看看那个类是不是就是当前类

**Comment by iNeverSleeeeep** [comment]
你指的那个类指的是Actor吗？这个函数是在Component上的。

**Comment by iNeverSleeeeep** [comment]
是XActor的YComponent Spawn了ZActor(也包含YComponent)

**Comment by iNeverSleeeeep** [comment]
这个函数是YComponent的一个函数

**Comment by chexiongsheng** [comment]
中间的spawn部分是你们自己写的吧？可能这块怎么写也是有关系的，最好能抽取个能重现的简单工程给我。

**Comment by chexiongsheng** [comment]
或者贴下SpawnActorEntity以及LoadNzActor的逻辑

**Comment by chexiongsheng** [comment]
我好像重现了

**Comment by chexiongsheng** [comment]
重现方法：
1、输入如下Component代码：
~~~typescript
import * as UE from 'ue'
import * as AsyncUtils from './AsyncUtils'

class CompC extends UE.ActorComponent {
    LoadActorB(): number {
        console.warn("BlueprintB_C");
        let p = AsyncUtils.AsyncLoad("/Game/BlueprintB.BlueprintB_C");
        p.then((cls: UE.Class) => {
            console.warn("loaded class:" + cls.GetName());
            this.GetWorld().SpawnActor(cls, undefined, UE.ESpawnActorCollisionHandlingMethod.Undefined, undefined, undefined);
            console.warn("spawn actor:" + cls.GetName());
        });
        return 1;
    }
}

export default CompC;
~~~
2、建立两个普通蓝图，BlueprintA，BlueprintB，均把CompC添加到组件。
3、BlueprintA在ReceiveBeginPlay中调用LoadActorB
4、场景添加BlueprintA并运行；

在这个使用场景里头，BlueprintA ReceiveBeginPlay调用LoadActorB时，该CompC已经是一个非CDO对象了，但在加载BlueprintB，依然重现初始化CompC的CDO对象（按我的理解，CompC已经加载并且第一个非CDO对象已经创建了，在Class未发生变更时，不应该重现初始化CompC的CDO对象，这是UE这块比较奇怪的一点）

如果BlueprintB已经在内存了（比如上述逻辑执行过一次），则不会触发CompC的CDO对象的重现初始化。
