### ISSUE TITLE
[Unreal]蓝图无法正确传递TArray引用

### ISSUE THREAD

**Issue by GreatXu** [Tencent/puerts#626]
TS中写了一个暴露给UE蓝图的方法TestCode()，在蓝图中调用引擎接口BoxTraceMultiForObjects后将返回结果中的TArray<FHitResult>& OutHits传递给TestCode()。
1、TestCode()中的参数不能声明为$Ref<UE.TArray<UE.HitResult>>类型，会提示无法蓝图无法识别此类型。只能写为UE.TArray<UE.HitResult>，并且可以在蓝图中连接。
2、拿到的数据实为$Ref<UE.TArray<UE.HitResult>>，并且其中的Value不正确。
![1](https://user-images.githubusercontent.com/17290089/148478028-98e8b10c-f4ef-44d9-84e1-0c226b8a974c.png)
![2](https://user-images.githubusercontent.com/17290089/148478051-d516656d-bad5-4011-b1a8-ab6eb928815b.png)
![4](https://user-images.githubusercontent.com/17290089/148480199-75327968-64fe-4736-8c2f-c409a4db1005.png)

**Comment by terst6** [comment]
直接在ts里用boxtraceceMultiForObjects

**Comment by GreatXu** [comment]
> 直接在ts里用boxtraceceMultiForObjects

因为要提供给策划配置，所以是创建了一个AnimNotify来做的，以方便在动画预览是可以显示框体大小。

**Comment by terst6** [comment]
我在ts里用的也有调试内容，在蓝图里设置显示调试框和时间，trace目标类型也由蓝图设置，目标类型程序里显示不友好

**Comment by chexiongsheng** [comment]
蓝图的函数的容器参数处理有点奇怪的潜规则。
即使编辑器下手工编辑的蓝图，同一个函数，参数是TArray时，会是引用传递，但如果是Map、Set则不会引用传递。

**Comment by GreatXu** [comment]
> 蓝图的函数的容器参数处理有点奇怪的潜规则。 即使编辑器下手工编辑的蓝图，同一个函数，参数是TArray时，无论是否勾选了“pass-by-reference”，都是引用传递，但如果是Map、Set，是否引用传递，取决于是否勾选了“pass-by-reference”。

如我上面截图1和截图三所示，即使我强行视为引用再去取值，结果也是不对的，此外，我也不能在声明暴露给蓝图的TS函数中把参数类型加上$Ref。请问一下，这个之后会处理吗？还是说遇到这种情况都采用上面那位老哥的方法去做？

**Comment by chexiongsheng** [comment]
我先确认下这个奇怪的规则是UE的bug，还是UE的特性，是不是各版本都是这规则。

**Comment by chexiongsheng** [comment]
> 我先确认下这个奇怪的规则是UE的bug，还是UE的特性，是不是各版本都是这规则。

官方的三年前的答复。
https://udn.unrealengine.com/s/question/0D52L00004luufsSAA/%E8%93%9D%E5%9B%BE%E5%87%BD%E6%95%B0array%E7%B1%BB%E5%9E%8B%E5%8F%82%E6%95%B0%E5%BC%95%E7%94%A8%E9%97%AE%E9%A2%98

当时为了快速修复一个bug引入的奇怪规则。

**Comment by GreatXu** [comment]
> > 我先确认下这个奇怪的规则是UE的bug，还是UE的特性，是不是各版本都是这规则。
> 
> 官方的三年前的答复。 https://udn.unrealengine.com/s/question/0D52L00004luufsSAA/%E8%93%9D%E5%9B%BE%E5%87%BD%E6%95%B0array%E7%B1%BB%E5%9E%8B%E5%8F%82%E6%95%B0%E5%BC%95%E7%94%A8%E9%97%AE%E9%A2%98
> 
> 当时为了快速修复一个bug引入的奇怪规则。

HI，你给的这个链接似乎无法打开。听上去似乎是UE本身的问题，那请问一下，后续puerts这边会处理吗？因为这种情况下，哪怕在TS中将收到的参数视为引用类型来使用，其值也是不对的。

**Comment by chexiongsheng** [comment]
解决了$Ref<UE.TArray<UE.HitResult>>会报错的问题，但也未必能满足你的需求，目前来说，$Ref<XXX>都是生成到output那

**Comment by GreatXu** [comment]
实测了一下，在TS中将TArry以参数传递都会有问题。
![截图2](https://user-images.githubusercontent.com/17290089/149062302-17d0142f-5c93-46b8-9634-f5efd0e3725f.png)
![截图1](https://user-images.githubusercontent.com/17290089/149062308-43c650aa-feae-444b-b877-8a565fcc9557.png)

**Comment by chexiongsheng** [comment]
在你的尝试中，感觉你没太理解这问题的原因：UE在处理某bug的时候，对Array做了特殊处理，无论是否勾选了“pass-by-reference”，它内部处理都默认把你的勾选上了。
可能需要在生成蓝图的ts函数，禁用掉UE.TArray<XX>的作为参数。你目前不做这方面的尝试就可以了。或者你可以把哪个Numbers尝试，强转为$Ref<UE.TArray<number>>来用。

**Comment by GreatXu** [comment]
> 在你的尝试中，感觉你没太理解这问题的原因：UE在处理某bug的时候，对Array做了特殊处理，无论是否勾选了“pass-by-reference”，它内部处理都默认把你的勾选上了。 可能需要在生成蓝图的ts函数，禁用掉UE.TArray的作为参数。你目前不做这方面的尝试就可以了。或者你接受到那个Numbers参数后，强转为`$Ref<UE.TArray<number>>`来用。

我在其他地方已经尽量避免使用这种情况。但是我现在面临的问题是需要在RPC函数中传递TArray，所以无法避免这种情况。

**Comment by chexiongsheng** [comment]
> 或者你接受到那个Numbers参数后，强转为`$Ref<UE.TArray<number>>`来用。

那你先按这种方式处理

**Comment by chexiongsheng** [comment]
目前的问题在于如果是TArray，UE只支持引用，也就是$Ref，但问题是目前的puerts的规则$Ref会处理成output。后续我会
1、禁用掉TArray作为输入参数
2、新增一个类型（或者标记），表达指定$Ref需要处理成input；

你目前暂时通过强转解决

**Comment by chexiongsheng** [comment]
> 目前的问题在于如果是TArray，UE只支持引用，也就是$Ref，但问题是目前的puerts的规则$Ref会处理成output。后续我会 1、禁用掉TArray作为输入参数 2、新增一个类型（或者标记），表达指定$Ref需要处理成input；
> 
> 你目前暂时通过强转解决

这个已经完成，你使用最新添加的$InRef即可。

**Comment by GreatXu** [comment]
> > 目前的问题在于如果是TArray，UE只支持引用，也就是$Ref，但问题是目前的puerts的规则$Ref会处理成output。后续我会 1、禁用掉TArray作为输入参数 2、新增一个类型（或者标记），表达指定$Ref需要处理成input；
> > 你目前暂时通过强转解决
> 
> 这个已经完成，你使用最新添加的$InRef即可。

不好意思现在才有时间测试您说的事。我添加了$InRef以后，确实能被蓝图识别。但是这只是解决了蓝图函数生成的问题。如我前面也提到的，即使将这个变量视为引用，取到的值也是空的，为此我做了一个类似的测试。
![代码截图](https://user-images.githubusercontent.com/17290089/151101877-5e2a211e-9213-49d0-958f-d3a58b621fdb.png)
![蓝图连接](https://user-images.githubusercontent.com/17290089/151101883-bb86245c-c92f-4fb0-a7e6-63fbeb9ee2c0.png)
其中TestCode1只是用来标明这次碰撞确实命中了Actor，TestCode2用来表明我说的情况，输出结果如下：
![输出结果](https://user-images.githubusercontent.com/17290089/151101980-40a28208-b167-4b69-bc71-2f76e50f832e.png)
可以看到TestCode2中命中结果一直是空。不知道是我的用法问题，还是确实存在这个bug

**Comment by chexiongsheng** [comment]
你在哪个版本测试的？

**Comment by GreatXu** [comment]
UE5

**Comment by chexiongsheng** [comment]
> UE5

puerts的版本，我怀疑是没更新完整导致

**Comment by chexiongsheng** [comment]
> 取到的值也是空的

你说的空，指的是TArray里元素个数为零么？

**Comment by GreatXu** [comment]
> > 取到的值也是空的
> 
> 你说的空，指的是TArray里元素个数为零么？

是的，我上面的TestCode2里将$InRef的参数unref以后，从来没有进入到下面的循环里去过。

**Comment by chexiongsheng** [comment]
那这和之前的现象就不一样，之前是unref以后是个undefined，调用Num函数就异常了

**Comment by chexiongsheng** [comment]
看代码也没法确认传进来的数组是空的，还是由数据的。

**Comment by GreatXu** [comment]
> 看代码也没法确认传进来的数组是空的，还是由数据的。

数据是空的，您可以测试一下。我总结一下我这边的情况，问题其实两部分：
1、最早的问题其实就是蓝图传递给ts，参数类型只能写为“UE.TArray<UE.HitResult>”，否则不能生成蓝图函数。
2、在这种情况下，把接收到的数据直接视为TArray，对其掉Num()方法会报错，因为类型不匹配；视为$Ref<UE.TArray>类型，$unref以后对其掉Num()方法不会报错，但是数组长度是0；
后来您这边加上$InRef，我认为解决的是第一部分的事。
关于蓝图那边实际传进来的数组，在最新测试中，我做了一次SphereTrace，在蓝图的循环节点中单次调用TestCode1，分别传递是结果中的各个HitResult，通过输出可以看到是碰到了BP_Pushable_C_1的，TestCode1除了输出Actor名字没有做别的操作。在蓝图的循环体执行完以后，将完整的HitResult数组传递给TestCode2，就出现了类似第二部分的情况。（由于SphereTrace做了多次，所以有多次输出，单次寄过如下图所示）
![1643344762034](https://user-images.githubusercontent.com/17290089/151488332-15f23593-c989-4049-89b9-e9cce02d3e81.png)

**Comment by chexiongsheng** [comment]
我的意思是：
数组长度是0，有可能你当时调用函数是，输入的数组参数长度本来就是0。

**Comment by chexiongsheng** [comment]
找到原因了，你更新到最新代码试试
