### ISSUE TITLE
puerts能否兼容到cocos creator 或 如果有html5游戏/微信小游戏场景能支持吗？

### ISSUE THREAD

**Issue by NoraGithub** [Tencent/puerts#628]
## detail | 详细描述
假设，我的设想是，希望能兼容h5/小游戏 的场景。那么ts作为语言，能否 `write once, run everywhere` 、`Write components once, run everywhere`。 或者只是 `Learn Once, Write Anywhere`。

毕竟还没开始，掉头快。
looking forward to any suggestion

**Comment by FishOrBear** [comment]
不行[狗头]

**Comment by chexiongsheng** [comment]
行。只要你把调用UE或者Unity的接口，把H5接口实现了就可以了。

**Comment by zombieyang** [comment]
目前unity用webgl构建出来的东西是能跑在h5/微信小/抖音小上的。没必要走Cocos。

或者你按车神的说法，自行实现一个unity->cocos的接口adaptor也可以。

**Comment by NoraGithub** [comment]
> 行。只要你把调用UE或者Unity的接口，把H5接口实现了就可以了。

懂你什么意思了 >_< ，向开源大佬学习
