### ISSUE TITLE
[Unity] 希望可以将代码报错输出至 chrome devtool 中

### ISSUE THREAD

**Issue by imengyu** [Tencent/puerts#629]
## detail | 详细描述
实际测试了下，使用 `jsEnv.Eval` 执行的代码，如果 JS 代码中出现异常，似乎只会在C#抛出异常，如果是异步回调中报错，try catch Tick 可以获取异常信息。
console.log 是可以在 devtool 中正常显示的，但是代码错误不会显示。
如果 JS 报错的话需要返回unity的Console在异常中找到报错文件、行号，手动找到报错位置，然后查看错误，比较麻烦。

假如可以把 JS 的报错显示到 devtool 中就好了，这样可以直接点击报错文件行号，跳转到 Sources 中，直接查看报错位置，在 Sources 中设置断点，进一步调试。这样调试会方便很多。如图：

![1](https://user-images.githubusercontent.com/32213395/148681893-e563b7c3-8c46-4a9e-854a-80f8906a24d2.png)

（目前我是try catch 然后 console.error 输出的，勉强可以查看报错，但是觉得不够优雅，如果引擎自己输出就好了）

**Comment by zombieyang** [comment]
错误自动输出到console上，本来就是一种不正常的行为。

一般来说，只有"uncaughtException"才会自动打在console里，但JS开发者都知道，这种情况在浏览器里还好，如果是做node的话，就会导致进程crash。这种错误在JS世界里是需要极力避免的。

那么对于"非uncaughtException"或者说有被正常catch的错误，一般来说也是不打印的，尤其是作为一个底层的库的时候更甚。你可以反过来想想，如果一大堆node_modules里的库产生的错误，不管需不需要开发者关心都打印出来，那控制台输出就会很凌乱。常规的做法就是需要开发者关心的错误，都抛回给开发者，由开发者自行决定怎么处理，而不是底层库自行产生一些有干扰性的信息。

`jsEnv.Eval`这个函数的实际行为是由开发者传入的参数所定的，因此执行错误回抛给开发者，开发者自行决定怎么处理，我觉得这样设计没什么问题。

---
目前执行JS的接口就只有Eval一个，所以你对它进行一次封装再给业务使用，就能很容易的实现你项目的需求，就没什么必要由puerts提供了。如果以后这类接口变多了，可以再考虑提供一个全局事件来减少你封装的复杂度，但是综上所述应该也不会由puerts直接产生打印。

**Comment by imengyu** [comment]
@zombieyang :
非常感谢您的解答和说明！
看了您的说明，我觉得也是由C#处理的话会比较合适。

之前我个人意见其实是，像未捕获的异常，UnhandledRejection，自动显示在console里，catch 过的异常当然不显示，方便开发者调试。因为前端做多了，觉得在devtools中查看异常是比较方便的（比Unity的console看起来清晰）。目前我们是想做游戏内MOD的功能，JS作为MOD的脚本，用户可能会用devtools调试代码。

研究了下，目前是在c# Tick 和 Eval 包裹 try catch, 然后捕获异常后再用 console.error 打印出来，可以实现需求了（只不过和原生打印的堆栈信息有点不一样）。

**Comment by zombieyang** [comment]
你打印的时候，是把c#侧的Exception直接toString打印出来么？
你其实是不是需要拿到JS侧的Error实例

**Comment by imengyu** [comment]
@zombieyang :
是的，目前只能打印C#的Exception，输出到控制台上时部分文件路径devtools识别有误并不能正确跳转。(这样子打印出来看报错是没有问题了，只是与平时浏览器调试时显示的有点不一样)
![1](https://user-images.githubusercontent.com/32213395/148865723-e1808755-e200-4c66-a919-dd1e4f818f7d.jpg)

**Comment by zombieyang** [comment]
我晚点加个获取原始JS Error的办法

**Comment by imengyu** [comment]
@zombieyang :
非常感谢！
建议可以参考nodejs一样，由puerts提供一个uncaughtexception事件，方便程序员在JS端自由处理未捕获异常，这个感觉比较实用：
[http://nodejs.cn/api/process.html#event-uncaughtexception](http://nodejs.cn/api/process.html#event-uncaughtexception)
