### ISSUE TITLE
为什么用commonjs module

### ISSUE THREAD

**Issue by hjmhjms** [Tencent/puerts#633]
## detail | 详细描述
在tsconfig.json里面我看到module用commonjs
    "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",

为什么用commonjs呢？有没有什么特别的原因？当然我试过demo工程里面改到es2015也是可以的

**Comment by zombieyang** [comment]
最近刚新增支持了es module

**Comment by hjmhjms** [comment]
是master已经done了吗？还是说正在做？

**Comment by chexiongsheng** [comment]
> 为什么用commonjs呢？有没有什么特别的原因？当然我试过demo工程里面改到es2015也是可以的

是不是搞混了概念了？commonjs是模块加载，es2015是编译目标，两个在tsconfig.json是不同的设置。
其次，为什么不能用commonjs？

**Comment by hjmhjms** [comment]
了解了，谢谢大家
