### ISSUE TITLE
[unreal]最新版蓝图命名空间下导出的ue.d.ts有错误

### ISSUE THREAD

**Issue by scutjames85** [Tencent/puerts#639]
## error log | 日志或报错信息
蓝图定义的枚举，被使用的地方有找不到定义的错误，如下图
![image](https://user-images.githubusercontent.com/82795479/149689061-69c72a88-2a68-41e0-a7ad-d460993c3d9e.png)

蓝图继承TS的类，在extends的地方，有错误提示如下图
![image](https://user-images.githubusercontent.com/82795479/149689145-5c62c89c-cce6-4b38-bc23-7f48628c572c.png)

UE自带的TutorialCharacter_C也有extend错误
![image](https://user-images.githubusercontent.com/82795479/149689189-50ee3c27-d96c-46b4-a13f-041a3a2b0123.png)

## context | 编译/运行环境
puerts更新到最新
ue4.27.2

## how to reproduce | 复现步骤
1.点击生成ue.d.ts

**Comment by chexiongsheng** [comment]
我这里没有报错。
特别是你反馈的第二点，我这里也有，并没报错。会不会是第一个错误导致的呢？第一个那个EMMOFlyingStatus是枚举吧？

**Comment by chexiongsheng** [comment]
第二个问题是不是你们定义了个叫Game的原生类呢？

**Comment by scutjames85** [comment]
> 我这里没有报错。 特别是你反馈的第二点，我这里也有，并没报错。会不会是第一个错误导致的呢？第一个那个EMMOFlyingStatus是枚举吧？

嗯嗯 EMMOFlyingStatus 是蓝图的枚举
![image](https://user-images.githubusercontent.com/82795479/149700647-88773f41-4e8c-42df-b1aa-aea090b6b354.png)

其他的问题  我试试在puerts的unreal demo重现一下

**Comment by chexiongsheng** [comment]
第三个我的环境也有类似的

**Comment by scutjames85** [comment]
嗯 第二个问题我这边确认一下  我们这边没有Game的原生类

**Comment by chexiongsheng** [comment]
蓝图的枚举的问题我已经解决，你再更新下试试，可能其它编译错误是它引发也不一定。

**Comment by scutjames85** [comment]
枚举问题已经解决了，但第2和第3个问题还在。
关于第二个问题，如果我手动把extends里面的Game.Blueprint去掉，就是可以正确找到位置的。这里的命名空间下好像环境不太一样。我这边的测试如图：
![image](https://user-images.githubusercontent.com/82795479/149703939-f2b89909-b7d6-434f-9017-53a89d4f7935.png)
这样是正确的：
![image](https://user-images.githubusercontent.com/82795479/149703971-966010f9-392d-4171-b11e-00d4ca6859e5.png)
在namespace下点Game. 提示的内容是这样的
![image](https://user-images.githubusercontent.com/82795479/149704033-7ea8e314-cfda-464e-ba02-18f5c0f4e9d3.png)
但在namespace外面点Game. 提示内容是这样的
![image](https://user-images.githubusercontent.com/82795479/149704085-111d6594-7651-4533-bbdf-be21229d0331.png)

希望能有所帮助

**Comment by chexiongsheng** [comment]
应该是你们的目录放置比较特殊导致的。
你们把纯蓝图放在Game目录，所以往上找会找到最近的Game目录。

**Comment by scutjames85** [comment]
嗯 确实我用你的fps_demo是没有这个问题，我调整一下目录结构看看

**Comment by chexiongsheng** [comment]
> 嗯 确实我用你的fps_demo是没有这个问题，我调整一下目录结构看看

不用调整，也能支持

**Comment by scutjames85** [comment]
嗯嗯  我们原来Blueprints目录下有个Game目录  所以导致了命名空间的混乱，我将目录名修改成GlobalGame之后，就OK了。
![image](https://user-images.githubusercontent.com/82795479/149708173-102cb61d-8d59-48ef-a134-eceb68871712.png)
谢谢提醒哈  

现在只剩下最后一个问题了，引擎哪个自带的找不到Character。其他都OK了 👍
![image](https://user-images.githubusercontent.com/82795479/149708218-ecbe6191-5279-4f7b-bd81-2ccb42b71f4a.png)

**Comment by chexiongsheng** [comment]
它上面的那个目录包含了个Character

**Comment by chexiongsheng** [comment]
> 它上面的那个目录包含了个Character

这个也解决了，更新到最新代码

**Comment by scutjames85** [comment]
嗯嗯 更新到最新 全部问题已经解决，感谢
