### ISSUE TITLE
number引用返回

### ISSUE THREAD

**Issue by xiewendan** [Tencent/puerts#641]
## detail | 详细描述
c++
`bool Send(const FArrayBuffer& Buffer, int32& BytesSent)`

在ts中定义了BytesSent，调用如下：
`let BytesSent = 0; 
bool bSend = Send(buffer, $ref(BytesSent));`
这里，BytesSent在ts中没办法返回，依然为0，但在c++层，已经修改了。

想问一下，支持number的引用吗？

**Comment by chexiongsheng** [comment]
看文档或者示例。
