### ISSUE TITLE
使用多线程同时创建多个JsEnv崩溃

### ISSUE THREAD

**Issue by hlxxiang** [Tencent/puerts#642]
## error log | 日志或报错信息
![image](https://user-images.githubusercontent.com/10176022/150053021-41613d6d-daf2-4464-8b17-2f17ee6cf97b.png)

## context | 编译/运行环境
Unity
## how to reproduce | 复现步骤
1. 使用多线程同时执行  `var jsEnv = new JsEnv(new DefaultLoader());`
2. 使用多线程等待前一个线程的jsEnv 初始化完不会有异常
## more | 其他
初步断定时静态变量导致异常
`        if (!GPlatform)
        {
            GPlatform = v8::platform::NewDefaultPlatform();
            v8::V8::InitializePlatform(GPlatform.get());
            v8::V8::Initialize();
        }`

**Comment by zombieyang** [comment]
有没有加THREAD_SAFE宏？

**Comment by hlxxiang** [comment]
![image](https://user-images.githubusercontent.com/10176022/150270432-dc602f8b-7245-46b7-a598-472b1b9f4f2e.png)
加上 THREAD_SAFE 宏，使用 lock 就没问题

**Comment by zombieyang** [comment]
嗯，多线程并发的话加上THREAD_SAFE即可
