### ISSUE TITLE
[Unreal]更新puerts版本后，修改ts文件不会引起蓝图文件的更新，如何手动更新？原本设置里的ResetInPIE现在要如何修改呢？

### ISSUE THREAD

**Issue by ZhengChengGui** [Tencent/puerts#652]
1、更新puerts版本后，修改ts文件不会引起蓝图文件的更新，如何手动更新？

2、原本设置里的ResetInPIE现在要如何修改呢？

**Comment by chexiongsheng** [comment]
Play期间不会修改蓝图，你在play期间别改类的声明就可以了，可以改函数逻辑
