### ISSUE TITLE
ue4 UPARAM(REF) 导致ue崩溃

### ISSUE THREAD

**Issue by terst6** [Tencent/puerts#655]
在cpp里声明消息函数，msg 被指定为输入参数，但是ts实现后msg成为了输出参数，同样一个实现函数修改一下名称，在蓝图里使用才看到是输出参数，ue里很多地方用到这个，以前遇到cpp里声明的标准组件，如果碰撞信息在ts里实现覆盖，也会出现类似的错误，只能在蓝图里碰撞，再去调用ts	UFUNCTION(BlueprintImplementableEvent)
	void OnMessage(UPARAM(REF) FString& msg);
多数时间错误提示是堆栈益处。
如果在ts里可以也指定参数是输入类型，也许可以解决这个问题

**Comment by terst6** [comment]
在ts里定义一个函数，是覆盖cpp里定义的两个输入类型字符串：OnSuccess(type:$Ref<string>, msg:$Ref<string>): void

 在生成的蓝图里取这个ts函数，结果是没有输入，一个输出的函数 OnSuccess()type:string。现在只能又在蓝图里覆盖，再去调ts另外定义的函数，与之前遇到的组件碰撞事件一样的方法

**Comment by terst6** [comment]
OnSuccess(type:$Ref<string>, msg:$Ref<string>): void

 OnSuccess()type:string

**Comment by chexiongsheng** [comment]
没看懂你表达的是啥问题。
直接描述问题的现象，重现步骤就可以了。
