### ISSUE TITLE
[UE4]最新版插件，动态委托报错崩溃

### ISSUE THREAD

**Issue by fengzehua** [Tencent/puerts#662]
## error log | 日志或报错信息
![调用堆栈](https://user-images.githubusercontent.com/33305400/153880099-47da6575-4f48-49ba-8e2a-10f29435c4db.png)

## context | 编译/运行环境
UE4.26
## how to reproduce | 复现步骤
![动态委托报错崩溃测试工程说明](https://user-images.githubusercontent.com/33305400/153880155-d6cf0f77-5744-4978-8744-b2dee266053e.jpg)

## more | 其他
测试工程
链接：https://pan.baidu.com/s/1Unn9byfeUcFYbKRradvDFA 
提取码：lc0c

**Comment by chexiongsheng** [comment]
百度网盘要安装客户端才能下载？

**Comment by fengzehua** [comment]
> 百度网盘要安装客户端才能下载？

是吗，那我把工程发你邮箱，你邮箱多少？

**Comment by chexiongsheng** [comment]
已经下载了。。为啥不直接github上fork一个demo修改后提交呢？
还有那截图比较模糊，是这个commit吧？https://github.com/Tencent/puerts/commit/fe0ffa9c0a5d633293a1a399a7c21701233f5c85

**Comment by fengzehua** [comment]
> 已经下载了。。为啥不直接github上fork一个demo修改后提交呢？
> 还有那截图比较模糊，是这个commit吧？[fe0ffa9](https://github.com/Tencent/puerts/commit/fe0ffa9c0a5d633293a1a399a7c21701233f5c85)

没错，是这个节点。哈哈哈，忘了直接提交了git了。下次一定

**Comment by chexiongsheng** [comment]
反复操作多少次会崩溃？

**Comment by fengzehua** [comment]
没有固定，偶发。大多在20几次

**Comment by fengzehua** [comment]
没有固定，偶发。大多在20几次

**Comment by fengzehua** [comment]
复现就是点击按钮，上拖或下拉，然后松开。反复

**Comment by fengzehua** [comment]
![调用堆栈](https://user-images.githubusercontent.com/33305400/153986598-fe924f37-ee0e-4067-a52d-53f933574a87.png)

**Comment by chexiongsheng** [comment]
应该解决了，我试了50+次都没问题了

**Comment by fengzehua** [comment]
牛哇 感谢大大

**Comment by chexiongsheng** [comment]
下载 打开工程一小时，定位半分钟。

**Comment by chexiongsheng** [comment]
> 下载 打开工程一小时，定位半分钟。

得益于你的重现工程，以及缩小代码范围。

**Comment by fengzehua** [comment]
> 下载 打开工程一小时，定位半分钟。

哈哈哈 下次用git
