### ISSUE TITLE
【Unity】 C# 属性能否注册导出为 configurable

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#667]
## error log | 日志或报错信息

在JS中重新定义C#属性时报错
```
TypeError: Cannot redefine property
```

## how to reproduce | 复现步骤

```ts
Object.defineProperty(FairyGUI.GObject.prototype, 'data', {
	configurable: true, enumerable: true,
	get() { return this.$data; },
	set(v: any) { this.$data = v; }
});
```

## more | 其他
可参考 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_redefine_property

**Comment by zombieyang** [comment]
我感觉这里设计的原意应该是 “来自C#的函数/属性，就保持C#的规则，无法运行时修改函数/属性行为”

有什么具体需求会要在原属性上修改而不是定义一个新属性来处理吗

**Comment by Geequlim** [comment]
需要替换某些库的属性实现，比如说上述实例代码里 FairyGUI 的 自定义 数据

**Comment by chexiongsheng** [comment]
原则上不应重新定义（建议通过proxy之类的方式来实现类似的目的）。
如果非要，可以自行修改代码解除。
由于这flag目前用来做readonly字段的优化的flag（优化为只传递一次），所以改起来会麻烦一点点，而且改了后这个优化就没了。
1、这个文件：https://github.com/Tencent/puerts/blob/master/unity/Assets/Puerts/Src/TypeRegister.cs ，里面所有PuertsDLL.RegisterProperty的最后一个参数都改为false
2、这个文件：https://github.com/Tencent/puerts/blob/master/unity/Assets/Puerts/Src/Resources/puerts/csharp.mjs ，把这一段给注释了
~~~js
        for(var key in cls) {
            let desc = Object.getOwnPropertyDescriptor(cls, key);
            if (desc && desc.configurable && (typeof desc.get) == 'function' && (typeof desc.value) == 'undefined') {
                let val = cls[key];
                Object.defineProperty(cls, key, {
                    value: val,
                    writable: false,
                    configurable: false
                });
                if (cls.__p_isEnum && (typeof val) == 'number') {
                    cls[val] = key;
                }
            }
        }
~~~

**Comment by zombieyang** [comment]
`unity-1.4.0-preview.0`已带上
