### ISSUE TITLE
请问 会支持动态绑定吗？

### ISSUE THREAD

**Issue by snadax** [Tencent/puerts#67]
比如在 unreal 下如果要用 ts 写gamemode 的逻辑 现在应该如何去做呢？

**Comment by chexiongsheng** [comment]
规划了类似的功能：https://github.com/Tencent/puerts/projects/1
效果大概是写ts继承了某个UE类，会自动生成对应的适配蓝图类，类也会有对应ts里头的方法的适配方法。
然后可以在UE里头按正常的蓝图那样使用该ts类。

**Comment by chexiongsheng** [comment]
https://zhuanlan.zhihu.com/p/346531865
