### ISSUE TITLE
[Unity]泛型类的静态泛型方法，导出index代码出错 

### ISSUE THREAD

**Issue by wtmsuperman** [Tencent/puerts#670]
升级到最新的puerts后，之前的bug又出现了
![image](https://user-images.githubusercontent.com/1977474/154919885-072330fb-2cbe-4c65-8fb4-708c57cda7b7.png)
之前已经正确的处理成了any，现在又变回了T
#574

**Comment by zombieyang** [comment]
重构生成模板时写错了个地方，已修复 53c23da791945a0b7a016de39a1dbaa778469e55
