### ISSUE TITLE
怎么在rider下调试ts呢

### ISSUE THREAD

**Issue by 83630037** [Tencent/puerts#672]

**Comment by 787786815** [comment]
楼主怎么调试的，可否分享下？

**Comment by Alvine1r43** [comment]
用rider好像有bug调试不了（我是用rider启动unreal工程的），用webStrom亲测可以，也是Jetbrains一家公司的。调试步骤：Run->Debug->Edit Configurations->选择Attach To Node.js/Chrome->更改端口号为->Debug
