### ISSUE TITLE
[unreal]preview 打包失败 error C2039: 'ClassGeneratedBy': is not a member of 'UClass'

### ISSUE THREAD

**Issue by FishOrBear** [Tencent/puerts#673]
Private\JSGeneratedClass.cpp(51): error C2039: 'ClassGeneratedBy': is not a member of 'UClass'

原因是这个属性现在只有在编辑器中才会有

![~PYOVI7F_EE3ZH@ }H3CP)O](https://user-images.githubusercontent.com/19372111/155666129-e624c824-6652-4858-bf2d-160e5d93cd49.png)

**Comment by chexiongsheng** [comment]
PR
