### ISSUE TITLE
ue 4.26 点按钮生成puerts类 的问题

### ISSUE THREAD

**Issue by weyenrooney** [Tencent/puerts#676]
## detail | 详细描述
4.26版本,点编辑器中的按钮生成ts类,  class  world
中的函数
SpawnActor(Class: $Nullable<Class>, Transform: Transform, SpawnCollisionHandlingOverride: ESpawnActorCollisionHandlingMethod, Owner: $Nullable<Actor>, Instigator: $Nullable<Pawn>) : Actor;
没有生成,demo工程中是有这个函数的,这大概是什么原因呢

**Comment by morirain** [comment]
https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/Source/puerts_unreal_demo/WorldExtensionMethods.h

看这个
