### ISSUE TITLE
[unreal] 如何正确设置TimelinePostUpdateFunc？Bind提示为undefined。附测试代码片段。谢谢

### ISSUE THREAD

**Issue by richard-tian** [Tencent/puerts#677]
## error log | 日志或报错信息
在puerts_unreal_demo参考样例项目的QuickStart.ts中，新增一段测试TimelineComponent设置代码，目标是在JS中实现TimelinePostUpdateFunc。

- TimelineComponent.TheTimeline.TimelinePostUpdateFunc类型为$Delegate<() => void>
- 参考QuickStart.ts中样例代码，用TimelinePostUpdateFunc.Bind绑定JS实现
- 结果出错，

> 报错提示
TypeError: Cannot read property 'Bind' of undefined
![image](https://user-images.githubusercontent.com/1821335/155876943-511e06f2-4f70-4898-aedc-2df3d91a77d5.png)

> 出错代码位置
![image](https://user-images.githubusercontent.com/1821335/155876995-c1f3e681-1953-40bf-83fa-7341256c1d1d.png)

> 对应类型
![image](https://user-images.githubusercontent.com/1821335/155875216-53955602-5ca2-4868-ba3f-72b79b8726e0.png)

## context | 编译/运行环境
UE版本：4.27
基于代码 [puerts_unreal_demo](https://github.com/chexiongsheng/puerts_unreal_demo)

## how to reproduce | 复现步骤
1. 下载puerts_unreal_demo，测试在UE4环境下正常运行
2. QuickStart.ts中加入下面代码片段

```
console.log("waiting native call script..........."); //原代码这行下面加

///新增测试代码片段开始
let timelineVar = new UE.TimelineComponent(actor);
//这行会出错
timelineVar.TheTimeline.TimelinePostUpdateFunc.Bind(() => {
    console.log("timelineVar.TheTimeline.TimelinePostUpdateFunc");
});
//下面代码还没有运行到
let floatCurveVar = UE.CurveFloat.Load("/Game/TimelineCurve_BP");
let floatTrackVar = new UE.TimelineFloatTrack();
floatTrackVar.FloatCurve = floatCurveVar;
floatTrackVar.TrackName = "NewTrack_0";
timelineVar.SetComponentTickEnabled(true);
timelineVar.bIgnoreTimeDilation = true;
timelineVar.TheTimeline.InterpFloats.Add(floatTrackVar);
timelineVar.SetTimelineLengthMode(UE.ETimelineLengthMode.TL_TimelineLength);
timelineVar.SetTimelineLength(3);
timelineVar.SetActive(true, true);
actor.SetActorTickEnabled(true);
timelineVar.PlayFromStart();
///新增测试代码片段结束
```

5. （可选）将下面asset复制到Game Content下
[TimelineCurve_BP.uasset.zip](https://github.com/Tencent/puerts/files/8148340/TimelineCurve_BP.uasset.zip)
6. 执行就能重现

**Comment by morirain** [comment]
看了下ue的代码 你绑定的这个东西可能本来就是空的
```
// Set up delegate that gets called after all properties are updated
FScriptDelegate UpdateDelegate;
UpdateDelegate.BindUFunction(Actor, TimelineTemplate->GetUpdateFunctionName());
NewTimeline->SetTimelinePostUpdateFunc(FOnTimelineEvent(UpdateDelegate));
```

**Comment by richard-tian** [comment]
@morirain
> UpdateDelegate.BindUFunction(Actor, TimelineTemplate->GetUpdateFunctionName());
NewTimeline->SetTimelinePostUpdateFunc(FOnTimelineEvent(UpdateDelegate));

上面代码是UBlueprintGeneratedClass::CreateTimelineComponent()，这个加上断点后没有执行过。

![image](https://user-images.githubusercontent.com/1821335/156885653-ad842f32-8f2c-4c43-8078-85c0313c797a.png)

目前分析
TimelineComponet.TheTimeline.TimelinePostUpdateFunc是$Delegate<() => void>;

在new实例构造时，
> let timelineVar = new UE.TimelineComponent(actor);

timelineVar.TheTimeline..TimelinePostUpdateFunc这个属性是空值。这样后面执行
> timelineVar.TheTimeline.TimelinePostUpdateFunc.Bind(() => {
     console.log("timelineVar.TheTimeline.TimelinePostUpdateFunc");
 });

经由FDelegatePropertyTranslator，转到JS中就是个无效值，这样会不会就造成无法执行Bind绑定了？

是TS应用没有正确编写，还是接口层实现需要调整？

对于需要设置组合成员的Delegate方法时，这可能是普遍的问题。

@chexiongsheng 各位大佬给帮忙看看

**Comment by morirain** [comment]
你的用法不对，你要先有一个`FOnTimelineEvent` 然后bind这个`FOnTimelineEvent` 最后`SetTimelinePostUpdateFunc`为你建立的`FOnTimelineEvent`
关于ts里的用法，你要看看文档，应该可以直接用`toManualReleaseDelegate`把你的ts函数设置过去

**Comment by richard-tian** [comment]
@morirain 尝试了下，没有成功
![image](https://user-images.githubusercontent.com/1821335/156906771-23bc5789-ad5d-45d4-9c4c-cf22722c1ef8.png)

重头跟踪了执行，在仅仅单步 （就是还没有执行TimelinePostUpdateFunc.绑定）
> let timelineVar = new UE.TimelineComponent(actor);

执行后，在JS调试控制台尝试查看 "timelineVar.TheTimeline"
![image](https://user-images.githubusercontent.com/1821335/156906891-dbd1791f-ce88-449a-a028-2c2680e1cfdf.png)
puerts会进行初始化模板属性（FStructWrapper::InitTemplateProperties）
![image](https://user-images.githubusercontent.com/1821335/156907154-e51ea15c-591c-4954-9616-dbb0f2916493.png)
执行到TimelineComponent对应 FPropertyTranslator::SetAccessor 时，
![image](https://user-images.githubusercontent.com/1821335/156906964-23f02299-311a-4d8f-b040-41d11b85698d.png)
>if (Property->GetOwnerStruct()->IsA<UClass>())    // only uobject support

上面条件没有成立。就是初始化模板时，”从属于某个UObject“从开始就没有通过。

在[Issue 252](https://github.com/Tencent/puerts/issues/252)中提过“按UE的规则是Delegate要从属于某个UObject”，是和这个相关？

**Comment by chexiongsheng** [comment]
对，UE的规则是Delegate要从属于某个UObject。
所以一个delegate是一个UObject的字段的话，obj.XXDelegate返回的对象会记录下owner，以便后续Bind操作时关联。如果是个普通类就做不到了。
试试这个：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TsProj/QuickStart.ts#L180
