### ISSUE TITLE
[Unreal]UEExtension.cpp中注册新接口后导致编译错误

### ISSUE THREAD

**Issue by dawnarc** [Tencent/puerts#679]
## error log | 日志或报错信息
```
2>  [2/21] Module.PuertsEditor.gen.cpp
2>  [3/21] UEExtension.cpp
2>D:\workspace\TestProj\Plugins\Puerts\Source\JsEnv\Public\TypeInfo.hpp(34): Error C2039 : 'value': is not a member of 'puerts::ScriptTypeName<UWidget,void>'
2>D:\workspace\TestProj\Plugins\Puerts\Source\JsEnv\Public\TypeInfo.hpp(34): Reference C2039 : see declaration of 'puerts::ScriptTypeName<UWidget,void>'
2>D:\workspace\TestProj\Plugins\Puerts\Source\JsEnv\Public\TypeInfo.hpp(121): Reference C2039 : see reference to class template instantiation 'puerts::ScriptTypeName<T,void>' being compiled
2>          with
2>          [
```

## context | 编译/运行环境
vs 2019
puerts master分支

## how to reproduce | 复现步骤
1. 在`UEExtension.cpp`中添加一个接口注册，例如：https://github.com/Tencent/puerts/issues/678
2. 然后重新编译工程，编译时就会报错上述错误；
3. 为了解决这个错误，可以添加一行`static constexpr const char* value = nullptr;`解决：
![image](https://user-images.githubusercontent.com/3351764/155885974-c77b9029-8228-4c4f-aac4-1711a30ad009.png)
但是不清楚这样添加是否会引起其他问题。

**Comment by chexiongsheng** [comment]
不就是因为你加了static constexpr const char* value = nullptr;所以引发了这问题么：https://github.com/Tencent/puerts/issues/678
当编译提示“'value': is not a member of 'puerts::ScriptTypeName<UWidget,void>'”正是提醒你要加UsingUClass(UWidget);
不过提示看可不可以优化一下。

**Comment by dawnarc** [comment]
@chexiongsheng 重新验证了下，确实是这个问题。如果注册带返回值的接口时一开始就把返回值类型添加上，就不会有这个问题。感谢车神！
