### ISSUE TITLE
UE5 Preview版本,没法编译FunctionTranslator.cpp

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#680]
如题，FunctionTranslator.cpp的25行 InitParamDefaultMetas.inl是不是漏传了

**Comment by morirain** [comment]
你看看是不是这个问题 https://github.com/Tencent/puerts/pull/637

**Comment by CasonCaly** [comment]
看着不是一回事，我是直接拿源码来编译的，编译环境为UE5 Preview版本，然后FunctionTranslator.cpp中这部分代码就没法编译
PRAGMA_DISABLE_OPTIMIZATION
static int ParamDefaultMetasInit()
{
    //PC = &ParamDefaultMetas.Add(TEXT("MainObject"));
    //PF = &PC->Add(TEXT("DefaultTest"));
    //PF->Add(TEXT("Str"), TEXT("i am default"));
    //PF->Add(TEXT("I"), TEXT("10"));
    //PF->Add(TEXT("Vec"), TEXT("1.100000,2.200000,3.300000"));
//#include "InitParamDefaultMetas.inl"
    return 0;
}
PRAGMA_ENABLE_OPTIMIZATION

**Comment by morirain** [comment]
你的`#include "InitParamDefaultMetas.inl"`怎么被注释了？
我的环境跟你一样的，没有问题

**Comment by CasonCaly** [comment]
这个是我自己注释的，注释了才能编译过

**Comment by chexiongsheng** [comment]
这文件是这模块生成的：[ParamDefaultValueMetas](https://github.com/Tencent/puerts/tree/master/unreal/Puerts/Source/ParamDefaultValueMetas) ，你试试添加这个模块的依赖

**Comment by chexiongsheng** [comment]
> 这文件是这模块生成的：[ParamDefaultValueMetas](https://github.com/Tencent/puerts/tree/master/unreal/Puerts/Source/ParamDefaultValueMetas) ，你试试添加这个模块的依赖

最新代码加了这个依赖，你看看解决你的问题不

**Comment by CasonCaly** [comment]
> > 这文件是这模块生成的：[ParamDefaultValueMetas](https://github.com/Tencent/puerts/tree/master/unreal/Puerts/Source/ParamDefaultValueMetas) ，你试试添加这个模块的依赖
> 
> 最新代码加了这个依赖，你看看解决你的问题不

可以了
