### ISSUE TITLE
[Unity] C# 调用 JS 时因 GC 触发导致参数变成无效对象

### ISSUE THREAD

**Issue by 1901** [Tencent/puerts#681]
## 详细描述
Unity 2019 的环境中，在 C# 调到 JS 的方法时（图中代码：497 行），传到 JS 的参数，在执行 PuertsDLL.InvokeJSFunction 的时候从对象池里移除掉了，具体可以看图中的调用堆栈。这样导致传到 JS 层的对象就无法正常使用了。

## 问题分析
目前看起来应该是在 C++ 的 JSEngine.cpp 中的 OnGarbageCollected 方法因为 gc 被触发，然后代码调回到 C# 的 StaticCallbacks.GeneralDestructor 方法，导致对象从对象池中移除。

## 问题
1. 请问这个问题要怎么处理或有办法绕过吗？
2. 因为是 gc 触发导致出现的问题，所以不能稳定重现，是否有办法手动触发 gc 来方便调试？

![5C485EE0-9A10-4776-8188-DB8D290F40B1](https://user-images.githubusercontent.com/806675/156355091-6ddd11c8-8b74-4ede-aa2e-def3fe072478.png)

**Comment by zombieyang** [comment]
图中看不出你是怎么使用Action的。

原理上来说，每个到C#变成delegate的JS函数，在C++侧都会有一个JSFunction对象，使用PersistentHandler持有它。
而JSFunction的释放是在C#侧generalDelegate的析构函数执行的时候执行的。
也就是C#不GC delegate，上C++ JSFunction对象就不会析构，进而JS侧也不可能GC那个JS函数。

所以你这个case就挺离奇，看看你能不能按这个思路先查查。

**Comment by 1901** [comment]
@zombieyang 感谢回复。

Action 是这样的，在 C# 这边有个事件处理器，在 JS 调用 C# 的方法传入了一个 Function 作为事件监听者。当事件派发的时候，通过这个 Action 回调到 JS 层。
```js
// this.onLoopCompleteBind 是一个 JS 的 Function，传入到 C# 生成那个 Action。
this.onLoopCompleteBind = this.onLoopCompleteDBEvent.bind(this);
this.armatureComponent.addDBEventListener(EventObject.LOOP_COMPLETE, this.onLoopCompleteBind);

private onLoopCompleteDBEvent(type: string, eventObject: dragonBones.EventObject) {
    if (eventObject && eventObject.animationState) { // JS 报错行
        this.onLoopComplete(eventObject);
    }
}
```

现在的问题并不是这个 JSFunction 被释放了。而是调用这个 Function 的时候传入的参数从 ObjectPool 里被移除了，这样就会导致参数传到 JS 后。在 JS 里使用这个参数的时候（上面代码块中的 `eventObject.animationState`），调用到 C# 下面的代码，在 `Puerts.Utils.GetSelf((int)data, self)` 这一步的时候无法取到 eventObject 这个对象，因为对象之前已经从 ObjectPool 中移除掉了。

```C#
[Puerts.MonoPInvokeCallback(typeof(Puerts.V8FunctionCallback))]
private static void G_animationState(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
{
    try
    {
        var obj = Puerts.Utils.GetSelf((int)data, self) as DragonBones.EventObject;
        var result = obj.animationState; // C# 报错行
        Puerts.ResultHelper.Set((int)data, isolate, info, result);
    }
    catch (Exception e)
    {
        Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
    }
}

```

**Comment by zombieyang** [comment]
这个EventObject，基类是不是一个C#对象，然后JS侧将其extends了？

**Comment by 1901** [comment]
> 

EventObject 是 C# 的一个类，但没有在 JS 层继承他，和 #65 不太一样。

但是今天有点新的发现，在 C# 调到 JS 时传的参数 eventObject 是从一个对象池（非 Puerts.ObjectPool）中取出来了，因为是复用的对象，出问题前也多次将这个对象传入到 JS。猜测是不是 GC 的时候清理之前的对象，导致这次的复用对象也被清理？

**Comment by chexiongsheng** [comment]
> 但是今天有点新的发现，在 C# 调到 JS 时传的参数 eventObject 是从一个对象池（非 Puerts.ObjectPool）中取出来了，因为是复用的对象，出问题前也多次将这个对象传入到 JS。猜测是不是 GC 的时候清理之前的对象，导致这次的复用对象也被清理？

看上去有这么个可能。

https://github.com/Tencent/puerts/blob/master/unity/native_src/Src/JSFunction.cpp#L98
这行之后，这个js对象会被handle持有，不会被gc。
但在此之前，如果那些HandleScope之类的语句会触发gc的话，那个对象有可能被释放。因为那个时候参数放到c++的JsFunction里头只是保存了对象ID而已，并没有在js那增加应用。

**Comment by zombieyang** [comment]
@chexiongsheng SetValueToArgument处会重新执行C#的FindOrAddObject，SetValueToArgument和InvokeJSFunction又是同步的连续操作。你是说SetValueToArgument和InvokeJSFunction执行过程中间会被v8插入一个gc么。
如果是这样，解决方案是否是在SetValueToArgument处就用PersistentHandle来存储参数

**Comment by 1901** [comment]
@chexiongsheng @zombieyang 

感谢两位的回复。

经过测试分析，发现我的应用场景可能确实是跟对象池有关系。但是我做了另外一个测试，也能重现问题。

## 示例代码
- Unity 代码片段一
```C#
public static void TestEventObject(Action<string, DragonBones.EventObject> handler)
{
    Game.Instance.ScheduleUpdate(() =>
    {
        var eventObject = new DragonBones.EventObject();
        handler(eventObject.type, eventObject); // 注释 A
        handler(eventObject.type, eventObject); // 注释 B
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
        handler(eventObject.type, eventObject);
    });
}
```
- Unity 代码片段二
```C#
[Puerts.MonoPInvokeCallback(typeof(Puerts.V8FunctionCallback))]
private static void G_type(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
{
    try
    {
        var obj = Puerts.Utils.GetSelf((int)data, self) as DragonBones.EventObject;
        var result = obj.type; // 报错行
        Puerts.PuertsDLL.ReturnString(isolate, info, result);
    }
    catch (Exception e)
    {
        Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
    }
}
```

- TypeScript（JavaScript）
```js
onTestEventObject(type: string, eventObject: dragonBones.EventObject): void {
    if (eventObject && eventObject.type) { // 报错行

    }
}

test(): void {
    UnityTest.TestEventObject(this.onTestEventObject.bind(this));    
}
```

## 问题分析
1. C# 代码运行至注释 A 的时候调用 handler 传入 eventObject，JS 层正常得到这个对象，没有问题。
2. 代码继续运行到注释 B 的时候（具体代码行：PuertsDLL.InvokeJSFunction(...)），V8 的 GC 触发，发现之前 A 处传到 JS 层的 eventObject 已无引用，然后从 ObjectPool 中将其移除。
3. 等 JS 层 onTestEventObject 方法被调用到，在里面使用 eventObject 的时候，调回到 C# 层（Unity 代码片段二），C# 层根据 objectId 去 ObjectPool 中取 eventObject 时候返回空，导致出现异常。

**Comment by zombieyang** [comment]
大概明白问题在哪了。顺便确认一下你用的plugin版本是v8还是quickjs？

**Comment by 1901** [comment]
> 大概明白问题在哪了。顺便确认一下你用的plugin版本是v8还是quickjs？

v8 
版本大概是前天下载的最新版本。

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/tree/681
因为我这边无法复现，麻烦帮忙用这个分支验证一下哈

**Comment by 1901** [comment]
> https://github.com/Tencent/puerts/tree/681 因为我这边无法复现，麻烦帮忙用这个分支验证一下哈

看 commit 信息，似乎改过 native 的代码了，请问哪里可以下载到对应编译好的库文件 `macOS/puerts.bundle`？

**Comment by 1901** [comment]
> > https://github.com/Tencent/puerts/tree/681 因为我这边无法复现，麻烦帮忙用这个分支验证一下哈
> 
> 看 commit 信息，似乎改过 native 的代码了，请问哪里可以下载到对应编译好的库文件 `macOS/puerts.bundle`？

找到了，应该是这个吧？https://github.com/Tencent/puerts/actions/runs/1932215308

**Comment by zombieyang** [comment]
是的

**Comment by 1901** [comment]
@zombieyang 经过测试，在上面的例子和我的实际应用场景中都不会再出现错误。

问题应该是已经修复了，再次感谢！

**Comment by zombieyang** [comment]
好，你先用着，后续我优化好代码之后再合入master

**Comment by 1901** [comment]
好的，谢谢

**Comment by bluedoom** [comment]
> @zombieyang 经过测试，在上面的例子和我的实际应用场景中都不会再出现错误。
> 
> 问题应该是已经修复了，再次感谢！

老哥你试过静态生成代码模式吗，我合并之后用生成代码会出问题，反射是正常的

**Comment by bluedoom** [comment]
我把这个合并到1.2.2上了，情况好了一些，但是没有完全好
https://github.com/bluedoom/puerts/commit/b24aefcb6fe56ef3be145e82fa7742d47a166ad2

![image](https://user-images.githubusercontent.com/29087010/158160705-b3b82994-3c9a-486e-819e-053cc50a2b7d.png)
![image](https://user-images.githubusercontent.com/29087010/158165515-51a85e50-58bf-41c6-83c6-b38bd2575563.png)
![image](https://user-images.githubusercontent.com/29087010/158165987-6ab4e745-6d3c-4099-923c-aa1747727dc4.png)
复现方法有点尴尬，上面那个Ts代码会每帧执行，然后挂机等，几分钟会跳一个报错。（手动GC没用，感觉需要等引擎自己GC）
不过有一点好一些的是，之前上面错误出现之后还会出现，下面的错误。
![image](https://user-images.githubusercontent.com/29087010/158166668-145a74ea-449b-4bf9-8fab-a38e220c6ba6.png)
this.R.Empty.gameObject.SetActive ：解释一下，这里面R是Js Object，Empty是Unity Component
