### ISSUE TITLE
[unity]GeneralGetterManager/GeneralSetterManager优化

### ISSUE THREAD

**Issue by chexiongsheng** [Tencent/puerts#688]
目前的生成代码，js 传递给C#一个C#对象，需要动态获取转换器（GeneralGetter/GeneralSetter）
路径是
~~~csharp
ArgumentHelper.Get<T> ->StaticTranslate<T>.Get -> GeneralSetterManager.GetTranslateFunc/GeneralGetterManager.GetTranslateFunc
~~~
优化建议
StaticTranslate<T>的Get\Set是可以设置的，但该delegate定义目前和GeneralSetterManager.GetTranslateFunc/GeneralGetterManager.GetTranslateFunc的返回定义不一致（前者多了一个jsEnvIdx参数）
可以把GeneralSetterManager/GeneralGetterManager改为和jsEnv实例不绑定，并把GeneralSetterManager.GetTranslateFunc/GeneralGetterManager.GetTranslateFunc的返回改为和StaticTranslate<T>的Get\Set一致，那么就可以直接赋值cache起来

好处：
1、不用每次都查找TranslateFunc；
2、GeneralSetterManager和GeneralGetterManager可以全局一份，不用每个jsEnv new一个，能减少一点内存。

**Comment by chexiongsheng** [comment]
具体点就是GeneralSetterManager和GeneralGetterManager改为单件。负责映射类型->转换器
原来GeneralSetterManager通过保存objectPool引用，可改为实时通过jsEnvIdx找到对应的objectPool
GeneralSetterManager提供带泛型参数的GetTranslateFunc接口，
然后StaticTranslate<T>.Get/StaticTranslate<T>.Set默认赋值为泛型参数的GetTranslateFunc接口

**Comment by chexiongsheng** [comment]
从数据上GeneralGetterManager/GeneralSetterManager可以搞成全局的，如果搞成全局的，要考虑多线程访问的问题

**Comment by zombieyang** [comment]
https://github.com/Tencent/puerts/commit/3c850d4290e72bd0fe50faab72bcb4e2b67bda28
