### ISSUE TITLE
请教：有没有iOS不支持jit的模式下和lua的性能对比

### ISSUE THREAD

**Issue by watsonsong** [Tencent/puerts#69]
v8比较担心的是无法jit的情况下，堆栈虚拟机的性能和lua相比是否会有显著下降？

**Comment by Joycraft** [comment]
这种基准测试第三方很难测试出来的, 主要看具体操作, V8官方有jit和jitless的测试, 某些操作性能会下降很多, 有些影响不大. 建议直接参考官方测试


用V8 jitless的也并非只有游戏, 还有很多Nodejs的方案,像NativeScript, React Native也在用, 和Lua做比较没什么意义, 这得看你用Lua能写什么, 用TS能写什么.如果能写能用的东西都不一样, 做些hello world的比较其实也没什么意义吧, 如果你能用Lua和TS写出来同样的业务逻辑, 然后再去综合比较性能和实现成本才有实际意义.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/puerts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 下午4:04
收件人:&nbsp;"Tencent/puerts"<puerts@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Tencent/puerts] 请教：有没有iOS不支持jit的模式下和lua的性能对比 (#69)





 
v8比较担心的是无法jit的情况下，堆栈虚拟机的性能和lua相比是否会有显著下降？
