### ISSUE TITLE
[unreal] UE5的Preview2版本生成的ue.d.ts有如下报错

### ISSUE THREAD

**Issue by scutjames85** [Tencent/puerts#701]
## error log | 日志或报错信息
![image](https://user-images.githubusercontent.com/82795479/158789250-4a7b05c5-2792-4476-b9ac-a16699fd3e52.png)
![image](https://user-images.githubusercontent.com/82795479/158789290-a6cd817d-c9e5-44bf-a577-807a269fb830.png)
搜索了一下UE的代码，这个变量值是这里出现过
![image](https://user-images.githubusercontent.com/82795479/158789492-2a589cee-0cd0-4dd9-9695-79f760251b55.png)
![image](https://user-images.githubusercontent.com/82795479/158789669-c16b082c-984e-482a-9076-4d52074e1e03.png)

## context | 编译/运行环境
UE5 Preview2 
Puerts最新版

## how to reproduce | 复现步骤
启动编辑器，Cmd 输入 Puerts.Gen

求大佬看一看，谢谢

**Comment by scutjames85** [comment]
嗯 我自己定位了一下问题，大概知道原因了。 因为这个AnimBlueprintGeneratedMutableData是UE自动生成的一个UClass结构，但是又不是Native的。因此Puerts会为他生成了命名空间。但由于这个并不是蓝图对象，在下一个动画蓝图需要生成AnimBlueprintGeneratedMutableData的时候，就会被跳过
![image](https://user-images.githubusercontent.com/82795479/158942328-63d66471-9d41-4459-97b0-876c22816fab.png)
因此就出现了上述问题。

目前我这边的解决办法是，修改了一下Namespace生成的判断是 蓝图对象才生成，不知道这样做合不合理。
![image](https://user-images.githubusercontent.com/82795479/158942495-e765c665-0ffc-42a3-907d-77a9bb6d441b.png)

**Comment by chexiongsheng** [comment]
你试试更新到这个：https://github.com/Tencent/puerts/commit/03381995853da1f47f705604a1d3655e578b1f90

**Comment by ljporljp** [comment]
我也有这个问题

**Comment by CoderJackLiu** [comment]
> 最新版本

我也是遇到了同样问题，不知道老哥解决了吗？

**Comment by ljporljp** [comment]
> > 最新版本
> 
> 我也是遇到了同样问题，不知道老哥解决了吗？

我目前是不让它生成，加到屏蔽列表去了。

**Comment by ljporljp** [comment]
参照 https://github.com/Tencent/puerts/pull/829

**Comment by CoderJackLiu** [comment]
> 

更新到了这个，代码也跟更新后的一样，也不行。还是报一样的错。

**Comment by chexiongsheng** [comment]
> > 
> 
> 更新到了这个，代码也跟更新后的一样，也不行。还是报一样的错。

之前那错误么？我这没有。如果不是一模一样可能是另外的一种情况，开个新issue写明情况。

**Comment by chexiongsheng** [comment]
> > 
> 
> 更新到了这个，代码也跟更新后的一样，也不行。还是报一样的错。

你试试把Plugins/Puerts/Typing/ue/ue_bp.d.ts删了重新生成看看？

**Comment by chexiongsheng** [comment]
这是一个package含超过一个类型，只生成一个类型导致的
