### ISSUE TITLE
【Unreal】 大概啥时候出个稳定release版本?

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#702]
## detail | 详细描述
项目预计下半年上线，希望能早点出个稳定版本。

**Comment by throw-out** [comment]
这个应该就是unreal的包, 只是没把unreal写上去
![image](https://user-images.githubusercontent.com/45587825/158923052-7b8b34f9-5cc1-4883-b306-e1135b45b510.png)

**Comment by ljporljp** [comment]
他们这个版本管理特别混乱的，我之前也问过他们：
[https://github.com/Tencent/puerts/issues/504](url)

**Comment by ljporljp** [comment]
而且看这个崩溃的概率和修复崩溃的commits，可能一时半会稳定不下来。。。

**Comment by ljporljp** [comment]
> 这个应该就是unreal的包, 只是没把unreal写上去 ![image](https://user-images.githubusercontent.com/45587825/158923052-7b8b34f9-5cc1-4883-b306-e1135b45b510.png)

那个只是最后打包的提交记录，跟unreal没有关系。

**Comment by throw-out** [comment]
可能是的, puerts好像在tencent内部用, 有什么问题会及时修复

**Comment by throw-out** [comment]
所以才会说仓库主分支是最优的吧(笑)

**Comment by chexiongsheng** [comment]
> 他们这个版本管理特别混乱的，我之前也问过他们： #504

不是混乱，unreal是目前还没出正式版本，主要是去年出了继承ue类的功能，这个功能业界貌似没可以参考的对象，想和一个项目探索最终的用法。怕的是用法变动，而不是崩溃什么的。
最近的那些崩溃都是调试器相关，和主流程关系不大。ue从我接触到现在版本，一直存在一个window下，用非微软输入法时，操作日志窗口可能导致崩溃的bug呢。

**Comment by chexiongsheng** [comment]
目前看来，用法基本稳定下来了，最近都没相关调整，也没继承ue类相关的用法和实现上的调整了。准备出一个正式版本。

**Comment by chexiongsheng** [comment]
> > 他们这个版本管理特别混乱的，我之前也问过他们： #504
> 
> 不是混乱，unreal是目前还没出正式版本，主要是去年出了继承ue类的功能，这个功能业界貌似没可以参考的对象，想和一个项目探索最终的用法。怕的是用法变动，而不是崩溃什么的。 最近的那些崩溃都是调试器相关，和主流程关系不大。ue从我接触到现在版本，一直存在一个window下，用非微软输入法时，操作日志窗口可能导致崩溃的bug呢。

可以透露点信息，那个项目重度使用了继承ue类的功能，战斗部分就有1000+个代理蓝图，一些编辑器插件，比如技能编辑器也是用ts开发。

**Comment by zhang357622852** [comment]
> 

编辑器这块，我这里目前是尝试用了Electron开发的，原生ue编辑器开发不怎么好用？

**Comment by zhang357622852** [comment]
> > > 他们这个版本管理特别混乱的，我之前也问过他们： #504
> > 
> > 
> > 不是混乱，unreal是目前还没出正式版本，主要是去年出了继承ue类的功能，这个功能业界貌似没可以参考的对象，想和一个项目探索最终的用法。怕的是用法变动，而不是崩溃什么的。 最近的那些崩溃都是调试器相关，和主流程关系不大。ue从我接触到现在版本，一直存在一个window下，用非微软输入法时，操作日志窗口可能导致崩溃的bug呢。
> 
> 可以透露点信息，那个项目重度使用了继承ue类的功能，战斗部分就有1000+个代理蓝图，一些编辑器插件，比如技能编辑器也是用ts开发。

编辑器这块，我这里目前是尝试用了Electron开发的，原生ue编辑器开发不怎么好用？

**Comment by chexiongsheng** [comment]
他们用的是puerts，你们用Electron，怎么调用ue的api呢？

**Comment by ljporljp** [comment]
> 目前看来，用法基本稳定下来了，最近都没相关调整，也没继承ue类相关的用法和实现上的调整了。准备出一个正式版本。

nice

**Comment by ljporljp** [comment]
> 比如技能编辑器也是用ts开发。

技能编辑器是runtime的还是editor的？是和官方的editor utility widget和utility bluprint配合使用吗？

**Comment by zhang357622852** [comment]
> 他们用的是puerts，你们用Electron，怎么调用ue的api呢？

我的这个编辑器目前不需求调用ue的api，所以。。。只是数据编辑用的，像第三方行为树编辑那样的

**Comment by GotGimhong** [comment]
@zhang357622852 您好，我们也有在 UE 项目当中使用 Puerts 的计划，请问你们是怎么解决调试堆栈问题的呢？

我们遇到的问题是，调试堆栈，包括行号等都是 JS 的，而不是 TS 的，所以调试起来会不太方便。在开发环境下，我们倒还可以利用 VSCode 来断点调试，但是在手机上的话调试起来就有些繁琐了。

我看 #172 提到 Unity 可以自己写一个脚本，利用 SourceMap 将调试堆栈重定向至 C# 的控制台，我们尝试在 UE 上参考这种做法。不知道您的项目是不是也是用类似的方法，还是有其他做法呢？
