### ISSUE TITLE
Chrome os需要 x86的android架构

### ISSUE THREAD

**Issue by leinlin** [Tencent/puerts#705]
## context | 编译/运行环境
unity的lib
希望提供一下x86和x86_64的 so库，最新的unity2020又加回去了

**Comment by Ninian4155** [comment]
因为缺失x86和x86_64的 so库，无法在mumu模拟器上正常运行（可能会影响提审）。

**Comment by zombieyang** [comment]
v8和qjs已提供，nodejs剩余问题https://github.com/puerts/backend-nodejs/issues/6继续跟进
