### ISSUE TITLE
UMG控件RenderTransform.Translation读取两次就会报错。

### ISSUE THREAD

**Issue by youngzii** [Tencent/puerts#711]
## error log | 日志或报错信息
示例代码:
`
const TranslationData = this.m_BtnChooseServer.RenderTransform.Translation;

console.log(`-----------0000000, RenderTranslation:${TranslationData}`);
console.log(`-----------1111111, RenderTranslation:${TranslationData.X}`);
`
报错信息: 
PIE模式Play后，第一次执行结果正常，如下：
Puerts: (0x00000AF752CE4730) -----------0000000, RenderTranslation:[object Object]
Puerts: (0x00000AF752CE4730) -----------1111111, RenderTranslation:0

第二次（间隔一段时间后）执行同样的代码，报错，如下：
Puerts: (0x00000AF752CE4730) -----------0000000, RenderTranslation:undefined
Puerts: Error: (0x00000AF752CE4730) js callback exception 路径XXXXXX\wnd_login.js:139: TypeError: Cannot read property 'X'

## context | 编译/运行环境
UE5

## PS
1. 如果在读取Translation之前先调用一句‘this.m_BtnChooseServer.RenderTransform.Translation = new UE.Vector2D(5, 6);’，那么则重复执行测试代码不会有问题。
2. 测试发现多次读取this.m_BtnChooseServer.RenderTransform.Angle是没有这个问题的。
3. 如果用c++接口获取控件的RenderTranslation，则没有上述bug。
4. this.m_BtnChooseServer.RenderTransform.Translation = new UE.Vector2D(5,6)，这种操作并不会把数值同步到C++。

**Comment by chexiongsheng** [comment]
更详细的信息？比如RenderTransform的定义，BtnChooseServer是个UObject还是啥？

**Comment by youngzii** [comment]
BtnChooseServer是UButton控件， RenderTransform是UWidget的一个UProperty，参见Widget.h Line:290

**Comment by youngzii** [comment]
补充一点：
BtnChooseServer.RenderTransform.Angle这个float值是没有问题，多次访问也ok。
但是BtnChooseServer.RenderTransform.RenderTranslation这是个Vector2D，多次访问是有问题的。

**Comment by chexiongsheng** [comment]
补充个简单重现方法，demo那
~~~ts

let o = new UE.MainObject();

console.log(o.SomeData.Alignment.X);
console.log(o.SomeData.Alignment.X);

~~~
