### ISSUE TITLE
[Unreal]UE5中蓝图生成的类型不符合预期

### ISSUE THREAD

**Issue by morirain** [Tencent/puerts#712]
由于4.27同样的工程没有出现过此问题，估计就是UE5的改动

脚本中的类型是number
`TotalDuration: number`
插件生成的：
`VarType=(PinCategory="float",PinSubCategory=""`
![image](https://user-images.githubusercontent.com/10196181/160024761-1683f181-7571-44e2-b659-fb09c849f4b7.png)

预期的：
`VarType=(PinCategory="real",PinSubCategory="double"`
![image](https://user-images.githubusercontent.com/10196181/160024905-e9360bf4-ded3-4547-91c3-71a96312a9bb.png)

其他类似情况：
`PinName="DamageAmount",Direction="EGPD_Output",PinType.PinCategory="float",PinType.PinSubCategory=""`
![image](https://user-images.githubusercontent.com/10196181/160025231-e6f08766-3bc0-4881-b83d-4c13964741c6.png)

预期的：
`PinName="DamageAmount",Direction="EGPD_Output",PinType.PinCategory="real",PinType.PinSubCategory="double"`
![image](https://user-images.githubusercontent.com/10196181/160025382-9384b1d3-6758-463f-9cbc-4c40cad2c076.png)

**Comment by chexiongsheng** [comment]
简单坐下兼容就可以了把？判断到是UE5，发现PinCategory是float，就改为real，并且把PinSubCategory改为double？
