### ISSUE TITLE
【ue】打开编辑器触发编译的频率很高，等待时间长

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#718]
## detail | 详细描述
上次更新puerts后，打开编辑器触发编译的频率变得很高了，现在项目的体量让等待时间变得很长
而且ue的编辑器也容易奔溃，经常重开后，需要等待很长时间，有啥办法能使用者自行打开编辑器后，自行编译这个事？例如一个工具按钮，需要的就点编译

**Comment by chexiongsheng** [comment]
更新版本试试

**Comment by chexiongsheng** [comment]
先关闭，有问题再提
