### ISSUE TITLE
支持NS遇到的问题SnapshotBlob

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#734]
## detail | 详细描述
#elif PLATFORM_ANDROID_ARM
#include "Blob/Android/armv7a/NativesBlob.h"
#include "Blob/Android/armv7a/SnapshotBlob.h"
#elif PLATFORM_ANDROID_ARM64
#include "Blob/Android/arm64/NativesBlob.h"
#include "Blob/Android/arm64/SnapshotBlob.h"
#elif PLATFORM_SWITCH
#include "Blob/Android/arm64/NativesBlob.h"
#include "Blob/Android/arm64/SnapshotBlob.h"
#elif PLATFORM_MAC
#include "Blob/macOS/NativesBlob.h"
#include "Blob/macOS/SnapshotBlob.h"
#elif PLATFORM_IOS
#include "Blob/iOS/arm64/NativesBlob.h"
#include "Blob/iOS/arm64/SnapshotBlob.h"
#elif PLATFORM_LINUX
#include "Blob/Linux/NativesBlob.h"
#include "Blob/Linux/SnapshotBlob.h"
#endif

请问一下我在Switch平台直接用Android arm64位的可以吗？

**Comment by chexiongsheng** [comment]
是v8还是quickjs？
v8的话，必需用对应平台的。
quickjs版本用啥都可以，就一个空文件。

**Comment by liuzongan** [comment]
谢谢了，是quickjs
