### ISSUE TITLE
UE5提示 could not be compiled. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by gtd138** [Tencent/puerts#736]
## detail | 详细描述
按照步骤安装，打开工程，提示需要编译，点击确定后，就提示 XXXX could not be compiled. Try rebuilding from source manually. XXXX是项目名。工程是新建的，并且是蓝图工程。UE版本是5.0.0。

**Comment by chexiongsheng** [comment]
蓝图工程需要编译后的plugins
你可以clone demo: https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TsProj/QuickStart.ts
切换到UE5然后编译。然后再把Plugins下的内容拷贝到你蓝图工程。
