### ISSUE TITLE
[Unity] Puerts_V8_1.3.1 生成代码功能报错

### ISSUE THREAD

**Issue by liu3656** [Tencent/puerts#737]
## error log | 日志或报错信息
DllNotFoundException: puerts
Puerts.PuertsDLL.GetApiLevel () (at Assets/ThirdParty/Puerts/Runtime/Src/PuertsDLL.cs:95)
Puerts.JsEnv..ctor (Puerts.ILoader loader, System.Int32 debugPort, System.IntPtr externalRuntime, System.IntPtr externalContext) (at Assets/ThirdParty/Puerts/Runtime/Src/JsEnv.cs:80)
Puerts.JsEnv..ctor (Puerts.ILoader loader, System.Int32 debugPort) (at Assets/ThirdParty/Puerts/Runtime/Src/JsEnv.cs:68)
Puerts.Editor.Generator.Menu.GenerateWrapper (System.String saveTo, Puerts.ILoader loader) (at Assets/ThirdParty/Puerts/Editor/Src/Generator/Menu.cs:158)
Puerts.Editor.Generator.Menu.GenerateCode () (at Assets/ThirdParty/Puerts/Editor/Src/Generator/Menu.cs:32)
## context | 编译/运行环境
Unity 2020.3.12f1
## how to reproduce | 复现步骤
1. 把 Puerts V8 1.3.1 解压包的内容放进工程
2. 点击编辑器菜单 Puerts -> Generate Code
3. 报错发生

## more | 其他
另, NodeJs 版本没有这个问题.

**Comment by zombieyang** [comment]
meta文件的问题, 我设置成Runtime Only了, 你可以找到对应的puerts.dll然后把Editor勾上
我看看怎么优化
