### ISSUE TITLE
[unreal]在Window平台使用QuickJs问题(puerts_unreal_demo)

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#743]
## error log | 日志或报错信息
1、在WIndows上使用QuickJs运行PerfTest.ts会崩溃，如：
     let testobj:any = new UE.TGUnitTestCallee();
     testobj.sTArrayRet();
     应该都是Wrap扩展的问题
## context | 编译/运行环境
     VS2019 QuickJs  Window
## how to reproduce | 复现步骤
1.
2.
3.

**Comment by chexiongsheng** [comment]
QuickJs提供的是静态库，不能在JsEnv外用静态Wrap（静态库的v8也一样，原因相同），在编辑器下会崩。
看静态wrap的说明：https://github.com/Tencent/puerts/blob/master/doc/unreal/template_binding.md#%E6%B3%A8%E6%84%8F

**Comment by liuzongan** [comment]
有点奇怪了，我WIndow平台上不行PerfTest，但在Switch可以正常运行PertTest啊

**Comment by liuzongan** [comment]
这是什么原理啊，有些不理解。。。。。。

**Comment by chexiongsheng** [comment]
仔细看我回复啊，是编辑器下会崩

**Comment by chexiongsheng** [comment]
你打window包应该可以跑
