### ISSUE TITLE
Puerts性能问题

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#745]
## detail | 详细描述
1、没有写静态Binding的代码是不是都走的是反射方法？
2、你的文档中说有一个高效的方法，是写静态Wrap的方法吗？有没有自动生成代码的方法？

**Comment by zombieyang** [comment]
哪篇文档里提的”高效的方法“？

**Comment by chexiongsheng** [comment]
UE下基于模板的静态Binding比反射快不少。
但基于模板的静态Binding主要的使用场景是“第三方库”，以及“UE非反射API”

UE反射本身的性能就不错，最重要的不像C#那样产生GC。
所以实践中大多数puerts项目（包括一些lua方案），基本上都是用反射，想unreal.js更是只有反射。

而且跨语言调用也并不是“脚本系统”的瓶颈，而“脚本系统”往往也不是游戏的性能瓶颈，担心这个有点过虑了。后期如果发现某个地方有反射拖累性能，可以静态Binding进行优化。

关于脚本性能，可以看看我这篇文章的观点：https://zhuanlan.zhihu.com/p/488347126

**Comment by liuzongan** [comment]
谢谢了，我知道ILRuntime是可以生成代码的方式进行优化，同时反射与生成Binding的方法都是存在的，如果能做到极致的话，应该可以考试一下啊。

**Comment by liuzongan** [comment]
1m NoArgNoRet using 3534ms
1m RetInt using 4553ms
 1m IntArgIntRet using 5755ms
1m StrArgIntRet using 8515ms
 1m Vector Property Get using 8602ms
 1m Vector Property Set using 5129ms
 1m TArrayRefIntRet using 11860ms
 TArrayRefIntRet:1024
 1m ConstTArrayRefIntRet using 12105ms
 ConstTArrayRefIntRet:1024
 1m TArrayRet using 36634ms
1,100
 0
1m arr.Get using 5809ms
 ---------------------------------------------------------
1m sNoArgNoRet using 3483ms
 1m sRetInt using 4448ms
1m sIntArgIntRet using 5786ms
1m sStrArgIntRet using 7592ms
1m Vector Property sGet using 11247ms
1m Vector Property sSet using 7918ms
1m sTArrayRefIntRet using 11155ms
 sTArrayRefIntRet:1024
1m sConstTArrayRefIntRet using 12279ms
sConstTArrayRefIntRet:1024
1m sTArrayRet using 33493ms
1,100
0
1m sarr.Get using 5711ms
这个是我在NS上跑的数据，1000000次，有静态Wrap是高效一点，有点还是负优化了（Vector 操作）。。。

**Comment by chexiongsheng** [comment]
倒不是负优化，而是有些针对反射的优化，静态难做到。

**Comment by chexiongsheng** [comment]
> 谢谢了，我知道ILRuntime是可以生成代码的方式进行优化，同时反射与生成Binding的方法都是存在的，如果能做到极致的话，应该可以考试一下啊。

说起ILRuntime，我那文章里头本来想提下的。“虚拟机性能”比“跨语言”重要的典型就是这。早年它的虚拟机性能出奇差（很久没关注了，据说有优化，不知道实际数据），但测试中用它的“跨域”对比lua的“跨语言”来说明自己性能更好（它本来就没跨语言，公用gc，天然就该比真正的跨语言要快），“虚拟机”这块轻飘飘的说“计算性能”慢。我所知道的一个项目，一个挂机游戏战斗部分用IL跑都卡。

**Comment by chexiongsheng** [comment]
你用v8对比更明显。quickjs可能它本身的脚本性能，以及适配成v8的api的开销都占大头了。

**Comment by chexiongsheng** [comment]
v8在window，静态相比反射，有些有5倍的差距

**Comment by liuzongan** [comment]
> > 谢谢了，我知道ILRuntime是可以生成代码的方式进行优化，同时反射与生成Binding的方法都是存在的，如果能做到极致的话，应该可以考试一下啊。
> 
> 说起ILRuntime，我那文章里头本来想提下的。“虚拟机性能”比“跨语言”重要的典型案例就想说它。早年它的虚拟机性能出奇差（很久没关注了，据说有优化，不知道实际数据），但测试中用它的“跨域”对比lua的“跨语言”来说明自己性能更好（它本来就没跨语言，共用gc，天然就该比真正的跨语言要快），“虚拟机”这块轻飘飘的说“计算性能”慢。我所知道的一个项目，一个挂机游戏战斗部分用IL跑都卡。

我用了这么长的时间，还没有想到是共用GC
