### ISSUE TITLE
[Unreal] 想请问一下为何只提供了通过动态委托从C++调用ts的方法，为什么不提供直接调用方式

### ISSUE THREAD

**Issue by lzj1989712** [Tencent/puerts#749]
## detail | 详细描述
之前测试过UnLua的直接调用Lua函数和通过委托调用，以及puerts的通过委托调用ts，性能差异还是比较明显的，所以想问一下为什么puerts没有提供直接调用ts函数的方案，因为消息处理这块通过委托处理开销还是比较大的

![image](https://user-images.githubusercontent.com/5946974/162690108-c485d85a-0427-44dc-bb0c-ccfe820c60aa.png)

**Comment by chexiongsheng** [comment]
试试std::function或者FJsObject 
https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/Plugins/Puerts/Source/JsEnv/Private/TestBinding/AdvanceTestClass.cpp#L22
