### ISSUE TITLE
[unreal]值拷贝UStruct GC优化

### ISSUE THREAD

**Issue by chexiongsheng** [Tencent/puerts#752]
## detail | 详细描述
某项目反馈程序运行中有规律卡顿。
经定位，是其游戏的大量临时UStruct的GC导致的，此类对象大多是FVector之类对象的运算过程中产生，有1200+次回收。

进一步定位，主要耗时是在FJsEnvImpl::UnBindStruct，耗时30ms（StructCache有10w左右，红黑树erase）。

目前的采取的临时解决方式：std::map换成TMap，下降到10ms（TMap优化得也不是十分多，和10w有关？我测试1k数据红黑树erase只要1ms），每帧跑一次MinorGarbageCollection可以削平性能峰值，MinorGarbageCollection的开销高配PC上为0.7ms, 在手机上大概为1.3ms。

**Comment by chexiongsheng** [comment]
值拷贝UStruct放在map其实只是为了找个地方存放v8::UniquePersistent，这个对象v8用来存放用户的释放回调。
尝试了一个方案，把v8::UniquePersistent放在和UStruct同一块内存，位于（ustruct首地址+AlignedSize(SizeOfUstruct, 8)）。
静态绑定改为不直接new，而是用placement new。

用该方案1000个对象一次性MinorGarbageCollection，开销在0.5ms左右。

**Comment by chexiongsheng** [comment]
在8以上版本的v8，ArrayBuffer新增了BackingStore相关支持，这套api能保证用户自定义的回收函数在ArrayBuffer释放时能被调用。

期间也碰到了坑：编辑器下我们用的是dll版本的v8，而BackingStore相关api用了unique_ptr作为返回以及参数，由于v8 dll编译用的stl版本和ue的stl版本不一致，window下会崩溃。

目前v8 8版本以下，以及quickjs（没实现相关api），以及编辑器下如果使用dll，都沿用原来的实现。并新增一个强制编辑器下切换成静态库的选项。

**Comment by chexiongsheng** [comment]
优化后，1000个对象调用MinorGarbageCollection会快很多。而且观察到BackingStore的释放时机有可能延后到下一次MinorGarbageCollection。这是两次调用的结果。
[2022.04.13-07.14.23:027][957]LogTemp: Warning: ---------0.373900-----------
[2022.04.13-07.14.23:027][957]LogTemp: Warning: ==========0.462300===========
如果在释放那增加打印，会看到第一次只会释放少量（其中一次测试时15个），第二次释放掉其它的。

**Comment by chexiongsheng** [comment]
dll + unique_ptr的问题，后续通过封装纯C API来规避。

**Comment by chexiongsheng** [comment]
BackingStore的优化，在原来发现性能问题的项目已经验证能解决卡顿问题。

**Comment by BlurryLight** [comment]
同样的问题也存在于 `CppObjectMapper.h`。
使用静态绑定创建大量的struct，在gc的时候会走到`FCppObjectMapper::UnBindCppObject`然后走到std::map的erase。
可能需要替换成TMap或者std::unordered_map

https://github.com/Tencent/puerts/blob/c74faf14c0b728a988079321ec2fd4b43bf67205/unreal/Puerts/Source/JsEnv/Private/CppObjectMapper.h#L46
