### ISSUE TITLE
Package Warning

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#755]
## detail | 详细描述
When Packaging：
LogClass: Warning: ObjectProperty FPEGraphPinType::PinSubCategoryObject is not initialized properly. Module:PuertsEditor File:Public/PEBlueprintAsset.h

**Comment by morirain** [comment]
不是这个问题导致的打包错误吧？修复的话，给FPEGraphPinType加一个空白的构造函数就可以了

**Comment by chexiongsheng** [comment]
> 不是这个问题导致的打包错误吧？修复的话，给FPEGraphPinType加一个空白的构造函数就可以了

这种可以提交个PR过来
