### ISSUE TITLE
[Unity] 2021下生成UnityEngine.Screen报错

### ISSUE THREAD

**Issue by lsx1994** [Tencent/puerts#758]
Unity版本：2021.3.0f1c1
问题描述：升级前可以正常运行，升级后报错。

# 1.自动生成代码错误
log：
`Assets\Gen\UnityEngine_Screen_Wrap.cs(198,78): error CS1615: Argument 1 may not be passed with the 'ref' keyword`
code:
`var result = UnityEngine.Screen.MoveMainWindowTo(ref Arg0, Arg1);`
这个问题手动删除ref可解决。

# 2.加载init.mjs失败
log:
<pre>Exception: puerts/init.mjs:1: Error: resolve module puerts/init.mjs error: Object reference not set to an instance of an object
Error: resolve module puerts/init.mjs error: Object reference not set to an instance of an object
    at puerts/init.mjs:1:7
Puerts.JsEnv.ExecuteModule (System.String filename) (at Assets/Puerts/Runtime/Src/JsEnv.cs:256)
Puerts.JsEnv..ctor (Puerts.ILoader loader, System.Int32 debugPort, System.IntPtr externalRuntime, System.IntPtr externalContext) (at Assets/Puerts/Runtime/Src/JsEnv.cs:166)
Puerts.JsEnv..ctor (Puerts.ILoader loader, System.Int32 debugPort) (at Assets/Puerts/Runtime/Src/JsEnv.cs:68)
PuertsMgr.Init () (at Assets/Scripts/Engine/Puerts/PuertsMgr.cs:15)
GameLanch.Start () (at Assets/Scripts/GameLanch.cs:26)
</pre>

code：
<pre>
public void Init() {
        loader = new Loader(Path.Combine(Application.streamingAssetsPath,"JavaScript"));
        jsEnv = new JsEnv(loader);        // 实例化 js 虚拟机 
#if UNITY_EDITOR
        jsEnv.WaitDebuggerAsync(); // 启用调试
#endif
    }
</pre>

**Comment by zombieyang** [comment]
问题1，测试了在1.2.x也有，不是1.3.2导致的。

问题2，如果DefaultLoader没问题，你自己写的Loader有问题，那还是先从你自己Loader里的逻辑开始排查

**Comment by lsx1994** [comment]
> 

问题1确认是升级Unity版本引起的。
问题2我自己再查查看，我测试了一下最新的demo用这个Unity版本没问题

**Comment by zombieyang** [comment]
问题1我这边查一下

**Comment by lsx1994** [comment]
问题2 我自己写的Loader把基类改成DefaultLoader就可以了。
