### ISSUE TITLE
QuickJS的Window运行我们项目问题

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#759]
## error log | 日志或报错信息
    static T toCpp(v8::Local<v8::Context> context, const v8::Local<v8::Value>& value)
    {
        T* ptr = ::puerts::DataTransfer::GetPointerFast<T>(value.As<v8::Object>()); //这一行崩溃
        return ptr ? *ptr : T{};
    }

以下是堆栈：
>   UE4Editor-Common.dll!puerts::converter::Converter<FLocFormatArgumentValue,void>::toCpp(v8::Local<v8::Context> context, const v8::Local<v8::Value> & value) Line 259 C++
    UE4Editor-Common.dll!puerts::internal::FuncCallHelper<std::pair<FLocText,std::tuple<FLocText const &,FLocFormatArgumentValue const &,FLocFormatArgumentValue const &>>,0>::call<FLocText (__cdecl*)(FLocText const &,FLocFormatArgumentValue const &,FLocFormatArgumentValue const &),0,1,2>(FLocText(*)(const FLocText &, const FLocFormatArgumentValue &, const FLocFormatArgumentValue &) & func, const v8::FunctionCallbackInfo<v8::Value> & info, std::integer_sequence<unsigned __int64,0,1,2> __formal) Line 367 C++
    UE4Editor-Common.dll!puerts::FuncCallWrapper<FLocText (__cdecl*)(FLocText const &,FLocFormatArgumentValue const &,FLocFormatArgumentValue const &),&FLocText::FormatOrderedTwo>::call(const v8::FunctionCallbackInfo<v8::Value> & info) Line 462    C++
    [External Code] 
    UE4Editor-JsEnv.dll!puerts::FFunctionTranslator::CallJs(v8::Isolate * Isolate, v8::Local<v8::Context> & Context, v8::Local<v8::Function> JsFunction, v8::Local<v8::Value> This, UObject * ContextObject, FFrame & Stack, void * Z_Param__Result) Line 456   C++
    UE4Editor-JsEnv.dll!puerts::FJsEnvImpl::InvokeTsMethod(UObject * ContextObject, UFunction * Function, FFrame & Stack, void * Z_Param__Result) Line 1976 C++
    UE4Editor-JsEnv.dll!UTypeScriptGeneratedClass::execCallJS(UObject * Context, FFrame & Stack, void * const Z_Param__Result) Line 27  C++
    UE4Editor-CoreUObject.dll!UFunction::Invoke(UObject * Obj, FFrame & Stack, void * const Z_Param__Result) Line 5588  C++
    UE4Editor-CoreUObject.dll!UObject::ProcessEvent(UFunction * Function, void * Parms) Line 1992   C++
    UE4Editor-Engine.dll!AActor::ProcessEvent(UFunction * Function, void * Parameters) Line 864 C++
    UE4Editor-Engine.dll!AActor::BeginPlay() Line 3577  C++
    UE4Editor-Engine.dll!APlayerController::BeginPlay() Line 1444   C++
    UE4Editor-Common.dll!ACommonPlayerController::BeginPlay() Line 46   C++
    UE4Editor-DreamEditor.dll!ADEPlayerController::BeginPlay() Line 14  C++
    UE4Editor-Engine.dll!AActor::DispatchBeginPlay(bool bFromLevelStreaming) Line 3517  C++
    UE4Editor-Engine.dll!AWorldSettings::NotifyBeginPlay() Line 247 C++
    UE4Editor-Engine.dll!AGameStateBase::HandleBeginPlay() Line 205 C++
    UE4Editor-Engine.dll!UWorld::BeginPlay() Line 4349  C++
    UE4Editor-Engine.dll!UEngine::LoadMap(FWorldContext & WorldContext, FURL URL, UPendingNetGame * Pending, FString & Error) Line 13133    C++
    UE4Editor-Engine.dll!UEngine::Browse(FWorldContext & WorldContext, FURL URL, FString & Error) Line 12338    C++
    UE4Editor-Engine.dll!UEngine::TickWorldTravel(FWorldContext & Context, float DeltaSeconds) Line 12536   C++
    UE4Editor-UnrealEd.dll!UEditorEngine::Tick(float DeltaSeconds, bool bIdleMode) Line 1692    C++
    UE4Editor-UnrealEd.dll!UUnrealEdEngine::Tick(float DeltaSeconds, bool bIdleMode) Line 426   C++
    UE4Editor.exe!FEngineLoop::Tick() Line 4836 C++

## how to reproduce | 复现步骤
1.
2.
3.

**Comment by chexiongsheng** [comment]
你的静态wrap声明写在哪里？Quickjs只能放在在JsEnv模块。

**Comment by liuzongan** [comment]
好的，谢谢了，找到了

**Comment by liuzongan** [comment]
有什么方法不放到JsEnv模块中呢？是什么原因导致的啊？

**Comment by chexiongsheng** [comment]
> 有什么方法不放到JsEnv模块中呢？是什么原因导致的啊？

把整个quickjs backend编译成dll就可以不放JsEnv模块。

你们游戏只做ns平台？为啥window都用quickjs呢？即使运行时最终采用quickjs，开发期也最好用v8，有更好的调试支持。

**Comment by liuzongan** [comment]
上PC与NS，只是提前测试一下代码有没有什么问题

**Comment by chexiongsheng** [comment]
ns的v8编译还没搞定么？

**Comment by chexiongsheng** [comment]
还不如努力下搞定v8编译呢。或者你共享下你是怎么搞定ns的quickjs的，包括ns编译环境的搭建，quickjs的编译等等。我可以试试。

**Comment by liuzongan** [comment]
那太好了，我给你搭建环境啊

**Comment by liuzongan** [comment]
我可以添加一下你的QQ吗？

**Comment by liuzongan** [comment]
我已经直接编译window 平台的v8
