### ISSUE TITLE
[Unreal] Error：No object initializer found during construction.

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#760]
## error log | 日志或报错信息
No object initializer found during construction.
## context | 编译/运行环境
UE5.0，Puerts1.0，vs2022
## how to reproduce | 复现步骤
1.enable Async Loading Thread Enabled
2.Create a class extends from Actor
3.Create SubObject in Constructor().
4.Spawn this class in level blueprint.
5. Package pc project , show this error.

**Comment by morirain** [comment]
目前`AsyncLoadingThreadEnabled`不能打开，可以先关掉

**Comment by ljporljp** [comment]
有支持计划吗

**Comment by ljporljp** [comment]
> 目前`AsyncLoadingThreadEnabled`不能打开，可以先关掉

有支持计划吗

**Comment by chexiongsheng** [comment]
AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。

至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。

**Comment by ljporljp** [comment]
> AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。
> 
> 至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。

关掉这个开关是好的。报错堆栈是在TsConstruct

**Comment by ljporljp** [comment]
I resolve this by
`            if (!IsCDO) {
                __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr));
            }`
at line 1808

**Comment by ljporljp** [comment]
> AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。
> 
> 至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。

I resolve this by
if (!IsCDO) { __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr)); }
at line 1808

**Comment by chexiongsheng** [comment]
> > AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。
> > 至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。
> 
> I resolve this by if (!IsCDO) { __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr)); } at line 1808

equivalent to disable the constructor. puerts will not work  as expected.

**Comment by ljporljp** [comment]
> > > AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。
> > > 至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。
> > 
> > 
> > I resolve this by if (!IsCDO) { __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr)); } at line 1808
> 
> equivalent to disable the constructor. puerts will not work as expected.

But everything is ok in my project...... the another method to solve this is that checking “!IsCDO” in my every ts Constructor.

**Comment by chexiongsheng** [comment]
no constructor called, so no CreateDefaultSubobject called, so no "No object initializer found during construction".

**Comment by chexiongsheng** [comment]
"No object initializer found during construction" mean calling CreateDefaultSubobject at runtime:
https://forums.unrealengine.com/t/when-is-valid-time-to-create-subobjects-components/367184

**Comment by chexiongsheng** [comment]
i think it cause by the delay calling of constructor, when AsyncLoadingThreadEnabled is true

**Comment by ljporljp** [comment]
> 

no. CreateDefaultSubobject realy called! the func in my code become ok.

**Comment by chexiongsheng** [comment]
> > > AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。
> > > 至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。
> > 
> > 
> > I resolve this by if (!IsCDO) { __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr)); } at line 1808
> 
> equivalent to disable the constructor. puerts will not work as expected.

just disable the constructor of CDO, so no CreateDefaultSubobject call on CDO, but may not cause problom if your program not depend on these.

**Comment by ljporljp** [comment]
I don't get where and why someone would use constructor in ts cdo

**Comment by chexiongsheng** [comment]
> > > > AsyncLoadingThreadEnabled倒不是不能打开。只是不能在异步线程里头调用js而已，js本来就不适用于多线程访问。所以没啥支持不支持好说的。
> > > > 至于你提的这问题，这报错是UE的报错，建议找相关信息看看原因。
> > > 
> > > 
> > > I resolve this by if (!IsCDO) { __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr)); } at line 1808
> > 
> > 
> > equivalent to disable the constructor. puerts will not work as expected.
> 
> But everything is ok in my project...... the another method to solve this is that checking “!IsCDO” in my every ts Constructor.

https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L1712

Comment out these two lines of code to disable delay calling of constructor :
~~~cpp
        {
            //FScopeLock Lock(&PendingConstructLock);
            //PendingConstructObjects.AddUnique(Object);
~~~

**Comment by chexiongsheng** [comment]
//disable all constructor of cdo
if (!IsCDO) { __USE(Iter->second.Constructor.Get(Isolate)->Call(Context, JSObject, 0, nullptr)); } 

//just disable constructor of cdo while asyn loading.
//FScopeLock Lock(&PendingConstructLock);
 //PendingConstructObjects.AddUnique(Object);

**Comment by ljporljp** [comment]
gotcha

**Comment by chexiongsheng** [comment]
> I don't get where and why someone would use constructor in ts cdo

useful in editor extension.

**Comment by ljporljp** [comment]
any ideas to solve the two situation.

**Comment by chexiongsheng** [comment]
Comment out these [two lines of code](https://github.com/Tencent/puerts/blob/02a26ffaf551fa0a5077fecd50d561c316e63cac/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L1718)，It just disable constructor of cdo while asyn loading.
//FScopeLock Lock(&PendingConstructLock);
//PendingConstructObjects.AddUnique(Object);

Is it worked?

**Comment by ljporljp** [comment]
Waiting....just compile my engine.....

**Comment by ljporljp** [comment]
> Comment out these [two lines of code](https://github.com/Tencent/puerts/blob/02a26ffaf551fa0a5077fecd50d561c316e63cac/unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp#L1718)，It just disable constructor of cdo while asyn loading. //FScopeLock Lock(&PendingConstructLock); //PendingConstructObjects.AddUnique(Object);
> 
> Is it worked?

It worked as well.

**Comment by chexiongsheng** [comment]
最新加入了多线程的支持
把ThreadSafe改为true，应该就可以支持AsyncLoadingThreadEnabled了
https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/JsEnv.Build.cs#L29
