### ISSUE TITLE
[unreal]最新版本使用FBox2d传值的方法（ts 传++)

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#763]
## error log | 日志或报错信息
从ts传到C++会丢失值（box2d.Min）的问题
C++:
void UMainObject::SetBox2d(const FBox2D& Box2D) const
{
        UE_LOG(LogTemp,Display,TEXT("FillTiles:%lf,%lf %lf %lf"),Box2D.Min.X,Box2D.Min.Y,Box2D.Max.X,Box2D.Max.Y);
}

TS:
let box = new UE.Box2D();
box.Max.X = 100;
box.Max.Y = 102;
box.Min.X = 1100;
box.Min.Y = 102;
obj.SetBox2d(box);

## how to reproduce | 复现步骤
1.
2.
3.

**Comment by chexiongsheng** [comment]
这个优化（ https://github.com/Tencent/puerts/commit/0c64722f961bb5ec241aa2808d9872db66ccf91f ）引入的问题，cache除首字段之外的字段。但静态的没处理好。先把所有静态都禁用cache吧。

**Comment by liuzongan** [comment]
怎么把所有的静态都禁用“先把所有静态都禁用cache吧”？
