### ISSUE TITLE
[Unity] UnityEngine.Vector2.op_Implicit is not a function

### ISSUE THREAD

**Issue by lsx1994** [Tencent/puerts#767]
问题描述： 旧版本运行正常，升级Unity后报错。

Unity版本 2021.3.0f1c1

#log 
<pre>
Exception: E:/LsxGithub/skygame-U3D/Assets/StreamingAssets/JavaScript/GameLanch.js:3: TypeError: _csharp.UnityEngine.Vector2.op_Implicit is not a function

TypeError: _csharp.UnityEngine.Vector2.op_Implicit is not a function
    at E:/LsxGithub/skygame-U3D/Assets/StreamingAssets/JavaScript/GameLanch.js:3:37
    at executeModule (puerts/modular.mjs:41:5)
    at require (puerts/modular.mjs:90:13)
    at chunk:1:1
Puerts.JsEnv.Eval (System.String chunk, System.String chunkName) (at Assets/Puerts/Runtime/Src/JsEnv.cs:278)
PuertsMgr.Begin () (at Assets/Scripts/Engine/Puerts/PuertsMgr.cs:30)
GameLanch.Start () (at Assets/Scripts/GameLanch.cs:33)

</pre>

#testcode 
<pre>
import { UnityEngine } from "csharp";
let a = UnityEngine.Vector2.op_Implicit(new UnityEngine.Vector3(0,0,0))
</pre>

**Comment by zombieyang** [comment]
op_Implicit也是全版本不允许使用的
https://github.com/Tencent/puerts/blob/master/unity/Assets/Puerts/Editor/Src/Generator/Wrapper.cs#L181

**Comment by lsx1994** [comment]
> op_Implicit也是全版本不允许使用的 https://github.com/Tencent/puerts/blob/master/unity/Assets/Puerts/Editor/Src/Generator/Wrapper.cs#L181

好的， 我看index.d.ts里面还有这个api以为可以正常使用

**Comment by zombieyang** [comment]
我更正下，只是全版本不允许生成。
看上去旧版是可以调用的。
