### ISSUE TITLE
[Unity]Version '1.3.2f' is invalid. Expected a 'SemVer' compatible value. 

### ISSUE THREAD

**Issue by duanrui71** [Tencent/puerts#768]
Version '1.3.2f' is invalid. Expected a 'SemVer' compatible value. [NotFound]. 
使用git模式的包，更新的时候会出这个错
![1650130033(1)](https://user-images.githubusercontent.com/20023122/163685267-e9c4f94c-7b64-4d3a-965e-1a59f5df97a2.jpg)
。

**Comment by zombieyang** [comment]
我修改一下
Unity本身的版本号各种加f，但UPM却又不允许我们用f，无力吐槽

**Comment by zombieyang** [comment]
30f0fbc24a6ba5f2f4e7b03f4a56b2f4a6381240
