### ISSUE TITLE
[Unreal] 静态绑定如何导出委托类型

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#770]

**Comment by chexiongsheng** [comment]
只要你写出native到js的转换器。任意类型都支持。

比如最简单的整数的Converter.：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Public/V8Converter.hpp#L187

复杂一点的，和delegate类似的std::function的Converter：https://github.com/Tencent/puerts/blob/2cad5805aabcf2f1c5198aaff6b9533b6dd37825/unreal/Puerts/Source/JsEnv/Public/JsObject.h#L211

**Comment by ljporljp** [comment]
通过基于模板的静态绑定导出一些引擎组件的非反射带代理事件参数的函数有点问题，而通过继承UExtensionMethods，则正常。我不太清楚应该用什么声明Delegate类型。UsingCppType能通过编译，但是导出声明不是原来的$Delegate类型。。。。。

**Comment by ljporljp** [comment]
我怎样以一种不侵入你代码的方式去扩展这个转换器？

**Comment by ljporljp** [comment]
继承UExtensionMethods没有静态绑定方便，毕竟繁琐，但更灵活，可以用来做一些api的封装，静态绑定更符合我们快速用来导出接口，看了下你那个解析反射信息生成Delegate类型的写法，感觉是一种基于顺序的暴力转换枚举，不太清楚这个转换器如何实现。。。

**Comment by ljporljp** [comment]
还有静态绑定导出的参数名也没有字面意义了，p0，p1这种，不过这个影响较小。

**Comment by chexiongsheng** [comment]
> 我怎样以一种不侵入你代码的方式去扩展这个转换器？

你另外写个文件都可以的。比如UE一些类型的扩展我写在这个文件里头：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp

只是用UsingCppType，只是把Delegate作为指针传入，并不能映射到函数。

**Comment by ljporljp** [comment]
是不是可以通过 FJsEnvImpl::AddToDelegate这个来做转换？

**Comment by ljporljp** [comment]
要命，这个是私有的。。。。

**Comment by ljporljp** [comment]
> > 我怎样以一种不侵入你代码的方式去扩展这个转换器？
> 
> 你另外写个文件都可以的。比如UE一些类型的扩展我写在这个文件里头：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp
> 
> 只是用UsingCppType，只是把Delegate作为指针传入，并不能映射到函数。

这个类型怎么从v8转成cpp的Delegate？

**Comment by ljporljp** [comment]
问下，我看有个基本pesapi,这个是用来做什么的

**Comment by ljporljp** [comment]
what's #lizard forgives？🙂

**Comment by chexiongsheng** [comment]
where are you come from? 🙂

**Comment by ljporljp** [comment]
哈哈，看到这个把我逗笑了=。=

**Comment by chexiongsheng** [comment]
为啥半中半英的？

**Comment by ljporljp** [comment]
一般情况下，在同一个issue下我保持一种语言，刚才那个没忍住，不好意思。还有大佬能支持下ue代理类型的静态绑定么。。。

**Comment by ljporljp** [comment]
这样子用起来就比较完整了，我也在尝试，不过。。。进度有点缓慢。想能够达到和反射类似的效果。

**Comment by ljporljp** [comment]
如果你能够支持的话就很nice了，用起来就顺畅多了。

**Comment by ljporljp** [comment]
@chexiongsheng  是不是可以用FDelegateWrapper来做转换？不知道我理解的是否正确？

**Comment by ljporljp** [comment]
template <>
struct Converter< FOnTimelineFloat >
{
    static v8::Local<v8::Value> toScript(v8::Local<v8::Context> context, FOnTimelineFloat value)
    {
        return v8::Undefined(context->GetIsolate());
    }

    static FOnTimelineFloat toCpp(v8::Local<v8::Context> context, const v8::Local<v8::Value>& value)
    {
        FOnTimelineFloat OnTimelineFloat;
        return OnTimelineFloat;
    }

    static bool accept(v8::Local<v8::Context> context, const v8::Local<v8::Value>& value)
    {
        return value->IsFunction();
    }
};

}    // namespace converter

template <>
struct ScriptTypeName<FOnTimelineFloat>
{
    static constexpr const char* value = "$Delegate<(Output: number) => void>";
};


@chexiongsheng 我已经从形式上ok了，但是这个转换器咋写。。。。大佬求助。。。。
还有，静态绑定之后，好像不支持函数参数默认值了。
从这样：
AddInterpFloat(FloatCurve: $Nullable<UE.CurveFloat>, InterpFunc: $Delegate<(Output: number) => void>, PropertyName?: string /* = "None" */, TrackName?: string /* = "None" */) : void;
变成：
AddInterpFloat(p0: $Nullable<CurveFloat>, p1: $Delegate<(Output: number) => void>, p2: string, p3: string) : void;
（缺了最后两个参数的默认值）
这个有没有什么好的思路？

**Comment by ljporljp** [comment]
等一个回复，thanks！

**Comment by chexiongsheng** [comment]
最开始那个就是有效回复啊。
你搞不定不代表那不可行啊。

ps，为啥不能临时用“扩展函数”处理呢？并不影响你写代码啊？即使后面搞定了，不就换换声明的事情么？又不会影响到使用方？？为啥纠结那么久？

**Comment by ljporljp** [comment]
什么叫我搞不定不代表那不可行？你能搞得定为啥不能直接支持呢？我这不是在请教下写法么，能不能友好点？

**Comment by ljporljp** [comment]
如果社区氛围是这样的，那我关了吧。
