### ISSUE TITLE
[Unreal]第三方工具中的 AdvancedAssetsTool 枚举生成头文件报错

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#773]
## error log | 日志或报错信息
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,30): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,36): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,43): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,50): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,57): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,65): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,73): An enum member cannot have a numeric name.
Error        Puerts               (0x00000949BFE94610)   Error D:/Develop/LL/client/Plugins/Puerts/Typing/ue/ue.d.ts (44838,81): An enum member cannot have a numeric name.

![image](https://user-images.githubusercontent.com/5946974/164385374-b29d6dfa-2024-4b25-a468-03abfda8b0b7.png)

![image](https://user-images.githubusercontent.com/5946974/164385413-1a11e5df-17a3-41b7-93a6-fe412684e75e.png)

![image](https://user-images.githubusercontent.com/5946974/164385745-233b95b1-cf27-4ea9-8503-ef2b287c761e.png)

## context | 编译/运行环境
UE5+Release-5.0  Windows 
## how to reproduce | 复现步骤
1. Content\Editor 中放入AdvancedAssetsTool
2.在编辑器中生成头文件

## more | 其他
原因是第三方工具 AdvancedAssetsTool  中定义的枚举字段是数字，但是ts的枚举不能有数值名

**Comment by chexiongsheng** [comment]
你这第三方工具啥水平？
枚举本来不就是为了避免硬编码数字而搞的东西？直接字段名就用数字？

**Comment by lzj1989712** [comment]
主要是蓝图里定义的枚举没办法赋值，而这个工具直接把枚举名字强转数字使用了。。

**Comment by lzj10** [comment]
![image](https://user-images.githubusercontent.com/5946974/164968287-57e745e2-d2ce-4ace-ae1c-e759f666d8ed.png)
先强行过滤掉这个工具的生成，暂时解决 后续看看需不需要弄一个生成头文件过滤
