### ISSUE TITLE
[Unity] 安卓真机TS调用c#报错  TypeError: task.GetAwaiter(...).OnCompleted is not a function 

### ISSUE THREAD

**Issue by daodaozhangnianxi** [Tencent/puerts#778]
## error log | 日志或报错信息
![1](https://user-images.githubusercontent.com/32058714/164420832-75b90dcb-c434-460c-8bff-2a14f658e900.png)
![2](https://user-images.githubusercontent.com/32058714/164420842-82a839c2-aeeb-4cc8-80b8-9eb29e7b4fd2.png)

## context | 编译/运行环境
Unity 2019.4.21f1c1 (64-bit)  谷歌 pixel3 安卓10 操作系统
## how to reproduce | 复现步骤
1. 在ts里去调用 c#  异步方法
2.
3.

## more | 其他
        public static async Task LoadFairyGUIPackage(string address, string packageName)
        {
            var pkgAsset = await Addressables.LoadAssetAsync<TextAsset>(address).Task;

            UIPackage.AddPackage(
                pkgAsset.bytes,
                packageName,
                async (string name, string extension, Type type, PackageItem ite) =>
                {
                    Log.Debug(LogGroups.Engine, $"{name}, {extension}, {type.ToString()}, {ite.ToString()}");

                    if (type == typeof(Texture))
                    {
                        Texture t = await Addressables.LoadAssetAsync<Texture>(name + extension).Task;
                        ite.owner.SetItemAsset(ite, t, DestroyMethod.Custom);

                    }
                });
            Addressables.Release(pkgAsset);
        }
调用的Promise 
```
function taskToPromise(task) {
    return new Promise((resolve, reject) => {
        task.GetAwaiter().OnCompleted(() => {
            let t = task;
            task = undefined;
            if (t.IsFaulted) {
                if (t.Exception) {
                    if (t.Exception.InnerException) {
                        reject(t.Exception.InnerException.Message);
                    } else {
                        reject(t.Exception.Message);
                    }
                } else {
                    reject("unknow exception!");
                }
            } else {
                resolve(t.Result);
            }
        });
    });
}
```

**Comment by zombieyang** [comment]
有试过生成`System.Runtime.CompilerServices.TaskAwaiter`或者尝试其他防裁剪的手段吗

**Comment by daodaozhangnianxi** [comment]
生成过也没有用 还是报错

**Comment by zombieyang** [comment]
#793 同样的问题

@daodaozhangnianxi  为什么把这个关掉了？
