### ISSUE TITLE
[Unity] build instruction

### ISSUE THREAD

**Issue by profelis** [Tencent/puerts#779]
## detail | 详细描述

HI! Can you provide more information about build dependencies, used libraries, versions?
I still don't understand how to get <platform>/SnapshotBlob.h files too.

Thanks!

**Comment by zombieyang** [comment]
If you just want to use PuerTS in your project, you can follow the [install guide](https://github.com/Tencent/puerts/blob/master/doc/unity/install.md) or download the [distribution](https://github.com/Tencent/puerts/releases)

If you really want to build PuerTS yourself. I will translate [this wiki](https://github.com/Tencent/puerts/wiki/%5BUnity%5D-Plugin%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97) for you tonight.

**Comment by chexiongsheng** [comment]
release for unreal plugin including the v8 lib: https://github.com/Tencent/puerts/releases/tag/Unreal_v1.0.0, 
v8 lib for ue4.25 or upper here: https://github.com/puerts/backend-v8/releases/tag/V8_8.4.371.19_0323
v8 lib for ue4.24 or blow here: https://github.com/puerts/backend-v8/releases/tag/v8_for_ue424_or_below

**Comment by profelis** [comment]
Thanks!

**Comment by profelis** [comment]
I already found all required backend repositories and successfully compiled everything I need. V8 crashes on my m1 cpu, but it's another question. Thanks again.

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts/releases/tag/tempm1

i've uploaded a distribution for m1 that works in @chexiongsheng 's macbook.

Or you can compile puerts with backend v8_9.6, which can find in respository v8-backend's 9.6 branch. But it is not completely tested.

**Comment by profelis** [comment]
Oh thank you! I appreciate it. 
Your version works perfect on my laptop as well as my locally compiled quickjs library. In result I have 2 working libs and it's enough for me for future weeks )
