### ISSUE TITLE
新版本生成的typing文件有很多 Interface 'XXX' cannot simultaneously extend types 'Component' and '$Extension<Transform, typeof ShortcutExtensions>'.报错

### ISSUE THREAD

**Issue by wchrt** [Tencent/puerts#78]
比如DOTween相关的代码生成绑定后, 报了很多这样的的错误:
Interface 'Transform' cannot simultaneously extend types 'Component' and '$Extension<Transform, typeof ShortcutExtensions>'.
  Named property 'DOAspect' of types 'Component' and '$Extension<Transform, typeof ShortcutExtensions>' are not identical.

![image](https://user-images.githubusercontent.com/20762359/97128631-d2cb0680-1777-11eb-8e83-d29bb3af0f56.png)
![image](https://user-images.githubusercontent.com/20762359/97128650-dbbbd800-1777-11eb-8f9a-6acb19f4a70e.png)

**Comment by wchrt** [comment]
生成DOTween这种直接声明文件时, $Extension不仅扩展了基类, 还扩展了每个子类, 导致冲突

**Comment by chexiongsheng** [comment]
DOTween是哪个版本呢？
unity是哪个版本呢？

**Comment by wchrt** [comment]
Unity2019.4.5 DOTween 1.0

**Comment by jihuayu** [comment]
有没有独立的可复现版本。
我这边自己写了个这样的类没问题。
```C#
public class A { }
public class B : A { }
public static class C
{
    public static void pp(this A b) { }
    
    public static void pp1(this B b) { }
    
    public static void pp2(this string b) { }
}
```

**Comment by chexiongsheng** [comment]
我可以复现

**Comment by jihuayu** [comment]
感觉像是$Extension函数中
```ts
type $Extension<T1, T2> = {
    [P in keyof T2] : T2[P] extends (obj:T1//** 要严格相等 **//, ...args: infer P) => infer R ? (...args: P) => R : never;
}
```

**Comment by wchrt** [comment]
> 感觉像是 $Extension 函数中
> 
> ```ts
> type $Extension<T1, T2> = {
>     [P in keyof T2] : T2[P] extends (obj:T1//** 要严格相等 **//, ...args: infer P) => infer R ? (...args: P) => R : never;
> }
> ```
> 
> 原因是 ts 参数类型是双向协变的，导致 T1 的子类兼容 T1。

T1确实没严格匹配上, 导致所有方法都被扩展到了不同类型里

**Comment by jihuayu** [comment]
还有一个问题，ts 判断类型相等靠的是判断类型里所有的 key 的类型是否相等。
所以，那一堆空类就全是相等的。

**Comment by jihuayu** [comment]
```ts
type $Extension<T1, T2> = {
    [K in keyof T2]: Equals<ArgumentTypes<T2[K]>[0], T1> extends true ? (T2[K] extends (obj: T1, ...args: infer P) => infer R ? (...args: P) => R : never) : never;
}
type ArgumentTypes<F> = F extends (...args: infer A) => any ? A : never;
type Equals<X, Y> =
    (<T>() => T extends X ? 1 : 2) extends (<T>() => T extends Y ? 1 : 2) ? true : false;
```
这样应该可以解决。
不过要把 #79 这个先修了。
