### ISSUE TITLE
[unreal]在Switch平台上Copy值的时候崩溃

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#780]
![image](https://user-images.githubusercontent.com/575589/164458032-793c1dd7-03ec-4029-9e12-a3777feadba8.png)
![image](https://user-images.githubusercontent.com/575589/164458075-e71dc1a4-2bea-46fe-a1ad-49d8147cfb4e.png)
麻烦再帮忙看一下啊

**Comment by chexiongsheng** [comment]
应该是你的数据或者说参数有问题。

**Comment by chexiongsheng** [comment]
举个例子，返回HitResult，然后你持有了HitResult.Location，不持有HitResult，HitResult被gc了。HitResult.Location就是野指针。
解决办法就是new XXX()值拷贝一次。
最近刚好有个项目有类似的问题。

**Comment by liuzongan** [comment]
早上定位了一下代码位置：
![image](https://user-images.githubusercontent.com/575589/164590818-d8762c64-0edf-47d5-aff3-23c4142ec3af.png)
![image](https://user-images.githubusercontent.com/575589/164590869-2320e922-94dc-4422-80fa-9acf42595bf8.png)
![image](https://user-images.githubusercontent.com/575589/164590907-28c77d0f-3522-410b-b736-1f58e7991bb8.png)

 LEventManager.emit(DEEventDefines.LEVEL_EDITOR_ADD_WORLD_WIDGET, worldWidgetInfo); 发事件的这一行崩溃，接收代码如下：
![image](https://user-images.githubusercontent.com/575589/164591097-57793187-45e9-44a6-8398-eb375b8b369d.png)
![image](https://user-images.githubusercontent.com/575589/164591177-5d70f2bf-3c15-4138-8c6b-78eef71b01d7.png)
最终传给DEWorldWidgetsPanel的AddWidgetInfo方法，崩溃

**Comment by liuzongan** [comment]
不知道 应该怎么修改

**Comment by liuzongan** [comment]
哦对了，PC平台没有问题，就是在Switch有问题

**Comment by chexiongsheng** [comment]
PC是v8吧？

**Comment by liuzongan** [comment]
pc平台是quickjs

**Comment by chexiongsheng** [comment]
看上去不是我说的问题。
崩溃的地方其实很简单，只是把js那传来的数据（指向的是new出来的结构），往一个栈上拷贝而已。你看看是不是数据源释放了，或者拷贝的目的地未初始化也有可能导致问题，因为不是简单的内存拷贝，而是调用结构体的拷贝构造函数。
你的AddWidgetInfo接口的C++声明是怎样的？

**Comment by liuzongan** [comment]
代码不熟悉，所以找的位置不够细，又仔细看了一下：
![image](https://user-images.githubusercontent.com/575589/164614662-88e724b8-dc64-4b1e-9fda-b670592493f3.png)
AddWidgetInfo中调用UserWidget->AddToPanel()
![image](https://user-images.githubusercontent.com/575589/164614755-07cb94df-8086-42c8-a362-f1ae9430741f.png)
这里发事件，在TS中接收了这个事件
![image](https://user-images.githubusercontent.com/575589/164615213-46546656-73da-481e-90e7-9365467fd264.png)
![image](https://user-images.githubusercontent.com/575589/164615318-9fe5952a-f604-45e0-b2c7-4c52dd0ca0fa.png)

**Comment by liuzongan** [comment]
![image](https://user-images.githubusercontent.com/575589/164615477-0789a04c-49fc-4905-9b78-04459e489a89.png)
![image](https://user-images.githubusercontent.com/575589/164615528-b6171945-42fa-4454-bf07-1ff8e4d0d5c1.png)
是不是const FWorldWidgetInfo& 引用的问题啊

**Comment by chexiongsheng** [comment]
> 代码不熟悉，所以找的位置不够细，又仔细看了一下： ![image](https://user-images.githubusercontent.com/575589/164614662-88e724b8-dc64-4b1e-9fda-b670592493f3.png) AddWidgetInfo中调用UserWidget->AddToPanel() ![image](https://user-images.githubusercontent.com/575589/164614755-07cb94df-8086-42c8-a362-f1ae9430741f.png) 这里发事件，在TS中接收了这个事件 ![image](https://user-images.githubusercontent.com/575589/164615213-46546656-73da-481e-90e7-9365467fd264.png) ![image](https://user-images.githubusercontent.com/575589/164615318-9fe5952a-f604-45e0-b2c7-4c52dd0ca0fa.png)

这不就有个外层节点释放的情况么？

**Comment by chexiongsheng** [comment]
这个返回的外层节点的定义是怎样的？

**Comment by liuzongan** [comment]
![image](https://user-images.githubusercontent.com/575589/164616184-2a1bf749-bb05-4d10-8b63-4643ac468c2e.png)
是不是应该把这个引用去了

**Comment by chexiongsheng** [comment]
> > ![image](https://user-images.githubusercontent.com/575589/164615213-46546656-73da-481e-90e7-9365467fd264.png)
> 
> 这不就有个外层节点释放的情况么？

GetWorldWidgetInfo()这可能有问题。

**Comment by chexiongsheng** [comment]
GetWorldWidgetInfo的C++定义是怎样的？

**Comment by liuzongan** [comment]
![image](https://user-images.githubusercontent.com/575589/164616695-7e2fbcf5-90e3-47de-8cf3-9f42dfdcfbb5.png)
![image](https://user-images.githubusercontent.com/575589/164616817-4b4b5f69-40ba-4bcf-83de-ac0ef2061bab.png)
![image](https://user-images.githubusercontent.com/575589/164617073-738c99c6-8c50-4fe7-828e-5a1503231263.png)

TS new CLass 用引用的方式存在C++有没有问题啊？

**Comment by chexiongsheng** [comment]
应该就是GetWorldWidgetInfo这行代码的问题。
你改为
let info = this.Instanc().GetWorldWidgetInfo();
...SetTextBlockText(info.LocTextBlock)
试试？

ps，别截图吧？抄个变量名都难

**Comment by liuzongan** [comment]
哦对了，FLocText是用静态定义的
![image](https://user-images.githubusercontent.com/575589/164618604-a51f4201-409b-47f7-8622-12fa00cd7f70.png)
有没有关系

**Comment by chexiongsheng** [comment]
没关系

**Comment by chexiongsheng** [comment]
发FWorldWidgetInfo和FLocText的定义看看就知道了

**Comment by chexiongsheng** [comment]
如果LocTextBlock不是指针，而是成员，那么quickjs你那写法下必crash，但为啥你window没事？是没跑到这里？

**Comment by liuzongan** [comment]
let ofb = this.Instance.GetWorldWidgetInfo();
        this.Instance.TextBlockName.SetTextBlockLocText(ofb.LocTextBlock);

**Comment by liuzongan** [comment]
这样写就没有问题

**Comment by chexiongsheng** [comment]
我可以改改puerts，支持你之前的写法。

**Comment by liuzongan** [comment]
OK.谢谢了

**Comment by chexiongsheng** [comment]
> 我可以改改puerts，支持你之前的写法。

试试更新到最新版本的quickjs

**Comment by chexiongsheng** [comment]
开启这个功能试试：https://github.com/Tencent/puerts/issues/792
