### ISSUE TITLE
[unreal]关于QuickJS在Window上的$Ref<TArray<Actor>>使用问题

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#781]
## detail | 详细描述
麻烦帮忙看一下， TypeError: cannot read property 'Num' of undefined
![image](https://user-images.githubusercontent.com/575589/164648508-aa888cfe-d68b-403f-8347-1e0170f3703c.png)

![image](https://user-images.githubusercontent.com/575589/164648401-cc19c4c3-fd7f-4e60-ac31-b35ddf7ee178.png)

**Comment by chexiongsheng** [comment]
和quickjs没啥关系吧？成员你定义TArray就可以了，不支持$Ref

**Comment by liuzongan** [comment]
他们之前在v8下就是这样写的，我只是切换到quickjs，OK

**Comment by liuzongan** [comment]
这种估计是项目中的骚操作了
