### ISSUE TITLE
[Unity] 生成的Index中，delegate里没有Invoke方法

### ISSUE THREAD

**Issue by Ninian4155** [Tencent/puerts#785]
## detail | 详细描述
生成的Index中，delegate里没有Invoke方法，导致调用Invoke时必须加上ts-ignore。

**Comment by zombieyang** [comment]
我看现有代码，思路应该是期望delegate能直接以函数的方式执行，因此就没导出Invoke方法。

有没有一个例子能说明必须要用Invoke，而不是直接以函数方式执行？
