### ISSUE TITLE
[unreal]关于在Switch上对象出现object flags are invalid or either Class or Outer is misaligned

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#789]
## detail | 详细描述
![image](https://user-images.githubusercontent.com/575589/164973480-fae800e9-0fa2-4a37-b39d-16a11e1c0ac3.png)
感觉是像被回收了似的，
![image](https://user-images.githubusercontent.com/575589/164973583-77ce1039-fb7c-4818-b5d2-cb23ec01c04c.png)
PC：没有问题
下面是Array定义：
![image](https://user-images.githubusercontent.com/575589/164973671-22fb8c63-93af-4d0d-84a9-c6459e0f8b6a.png)

**Comment by liuzongan** [comment]
这个问题应该是https://github.com/Tencent/puerts/issues/782 这个问题引起的

**Comment by liuzongan** [comment]
PC v8上可以模拟出这种问题
![image](https://user-images.githubusercontent.com/575589/164975863-af734ffe-5656-46e5-9dd1-47f9363a15a9.png)
这样写：
![image](https://user-images.githubusercontent.com/575589/164975884-c9f56d58-f8e5-47b2-bcc5-bc89f4a4ee8b.png)

**Comment by chexiongsheng** [comment]
no-blueprint没在ts初始化不就是undefined么？

**Comment by chexiongsheng** [comment]
你这代码贴了个寂寞。。关键在于这变量怎么初始化，怎么访问。

**Comment by liuzongan** [comment]
![image](https://user-images.githubusercontent.com/575589/165008515-fd8d4f63-f8d8-4bf1-a3c6-2d9d6ea8bd99.png)
这个是代码初始化，容易被GC了，我们项目组的人员说必要用使用蓝图引用的TMap与TArrary才能保证不被GC（我觉得有点局限性），想知道这种情况下怎么不被GC了

**Comment by liuzongan** [comment]
![image](https://user-images.githubusercontent.com/575589/165008774-2f242e6e-9921-43b7-88ed-4fc7f7ec3b90.png)
又没有出现这种日志在PC V8：object flags are invalid or either Class or Outer is misaligned

**Comment by chexiongsheng** [comment]
如果持有的类没被GC。TMap和TArrary不会被GC。但TMap是js持有的话，TMap里头的内容是可能会被GC的

**Comment by chexiongsheng** [comment]
跟你在C++中，非UProperty里头，用一个TMap持有UObject是一个道理，都会被GC

**Comment by chexiongsheng** [comment]
问题的关键不在于是不是使用蓝图引用，而是在于是否通过UProperty告诉UE GC引用关系了。

**Comment by liuzongan** [comment]
OK，明白了
