### ISSUE TITLE
[Unity] Scripting backend  从Mono改为 IL2CPP 安卓真机上报错

### ISSUE THREAD

**Issue by daodaozhangnianxi** [Tencent/puerts#793]
## er
![1](https://user-images.githubusercontent.com/32058714/165502968-2c916fdc-2a93-44ba-b6ce-5fe0dbfb1e22.png)
![2](https://user-images.githubusercontent.com/32058714/165502980-5b39a8e1-a738-427d-8e18-34b31c651d61.png)
![3](https://user-images.githubusercontent.com/32058714/165502983-08e44b46-4059-42eb-8b92-786e15c9661d.png)
ror log | 日志或报错信息

## context | 编译/运行环境
   mono 是正常的 
  参考了 Android 使用 il2cpp 编译，启动时崩溃 不生效还是有问题

**Comment by chexiongsheng** [comment]
剪裁导致的。
加到生产列表或者在link.xml中配置

**Comment by daodaozhangnianxi** [comment]
![1](https://user-images.githubusercontent.com/32058714/165711487-7289ca6f-402b-42a5-ac47-cddf1ebb2cfd.png)
![2](https://user-images.githubusercontent.com/32058714/165711507-d06752e8-8f89-4f52-adc6-6f515aa38044.png)
还是一样报错

**Comment by zhihesoft** [comment]
In short, after appreciation of all the answers and comments, my realization about using GetAwaiter() is: don't do it.

If you need it, this is most likely an indication that your asynchronous design is in badly need of refactoring.

[origin](https://stackoverflow.com/questions/30362621/can-a-call-to-task-getawaiter-oncompleted-fail-because-of-garbage-collection)

**Comment by zombieyang** [comment]
```
using System;
using UnityEngine;
using UnityEngine.UI;
using Puerts;
using System.Threading.Tasks;

namespace PuertsTest
{
    public class JsCallCs : MonoBehaviour
    {
        JsEnv jsEnv;

        public static Task MakeATask() 
        {
            long now = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            var task = new Task<int>(()=> {
                while (true) {
                    if (DateTimeOffset.Now.ToUnixTimeMilliseconds() - now > 3000) {
                        break;
                    }
                }
                return 30;
            });

            task.Start();
            return task;
        }
        public static Task theTask;

        void Start()
        {
            theTask = MakeATask();
            jsEnv = new JsEnv();
            jsEnv.Eval(@"
                const CS = require('csharp');
                CS.PuertsTest.JsCallCs.theTask.GetAwaiter().OnCompleted(()=> {
                    console.log('js done')
                });
            ");
            
            theTask.GetAwaiter().OnCompleted(()=> {
                UnityEngine.Debug.Log("cs done");
            });
        }

        void OnDestroy()
        {
            jsEnv.Dispose();
        }
    }
}

```

测试了如上代码，在安卓il2cpp下没有报错。
需要更多的线索

**Comment by zombieyang** [comment]
![image](https://user-images.githubusercontent.com/5595819/167614658-a75ab429-c465-40aa-9973-0b22de27bc7d.png)
另外群上有热心群众提供了此方法，据 @Justin-sky 测试可用。
