### ISSUE TITLE
ue4.27  ts无法生成蓝图

### ISSUE THREAD

**Issue by weyenrooney** [Tencent/puerts#798]
## how to reproduce | 复现步骤
1.新建一个4.27 c++ 第三人称项目，添加2个最简单的继承  UE.Actor的类
class TS_Actor extends UE.Actor {
    @edit_on_instance()
    ABill: boolean=false;
    @edit_on_instance()
    BTest4: boolean;   
    test1():void {
        console.log("ts test4 ");
    }

}

export default TS_Actor;

2.c++调试模式下，在代码编辑器里修改ts代码，然后在编辑器中点ts生成蓝图的按钮
3.运行游戏，点ts生成蓝图的按钮。在运行的过程中修改ts代码，点生成蓝图
2，3步骤中的几个动作来回随机操作，要不了多久，新增加的ts类无论怎么操作都不会生成对应的蓝图了

从早上弄到下午，各种文档中的细节都试了一遍，楞是不知道怎么生成蓝图了。但是新建的一个工程又能生成蓝图

**Comment by chexiongsheng** [comment]
看UE日志有什么报错没

**Comment by jackfong66** [comment]
没有按照步骤安装的话 会出现。  还有如果代码不是方式工程同一层级也不行
我昨天遇到过
