### ISSUE TITLE
[unreal] 如何在代理蓝图里调用动画蓝图中的自定义事件

### ISSUE THREAD

**Issue by shadow0162** [Tencent/puerts#803]
请问如果在Animation Blueprint的Event Graph中创建了Custom Event。那么如何在TS的代理蓝图中触发这个自定义事件呢？进一步而言，参数怎么传递？

这个需求可能有点奇怪，需要的话，可以补充细节。先谢谢了

**Comment by shadow0162** [comment]
补充一下，如果在C++的话，可以用BlueprintImplementableEvent，BlueprintNativeEvent或者CallFunctionByNameWithArguments来实现

**Comment by chexiongsheng** [comment]
Custom Event最后不是也是生成蓝图函数么？就普通蓝图函数那样调用就可以了
