### ISSUE TITLE
[UE5.0.0]ts类型校验错误

### ISSUE THREAD

**Issue by FishOrBear** [Tencent/puerts#808]
下面的代码ts不会报错,不知道是否有办法检测到这个错误.
```typescript
import * as UE from 'ue';
let arr: UE.TArray<UE.Vector3f>;
arr.Add(new UE.Vector());
```

**Comment by chexiongsheng** [comment]
ts的类型校验是接口兼容就能赋值，如果Vector3f和Vector字段和方法都一样 ，就可以赋值。

**Comment by FishOrBear** [comment]
但是这样的代码是错误的, arr.Add后 这些值是坏的.

**Comment by FishOrBear** [comment]
![image](https://user-images.githubusercontent.com/19372111/168246416-83440ebe-1fb0-4814-9341-690ebd4f89d4.png)

**Comment by FishOrBear** [comment]
建议在生成.d.ts时,加入独一无二的信息,避免这种错误,例如:
```typescript
class A
{
    x: number;

    private __ISA__: boolean;
}

class B
{
    x: number;

    private __ISB__: boolean;
}

let arr: A[] = [];

arr.push(new B);
```


![image](https://user-images.githubusercontent.com/19372111/168247200-d4cfa343-edc6-4490-9dfa-2613290ddc7f.png)

**Comment by chexiongsheng** [comment]
之前有想过加个特殊字段，不过加这东西会让人比较奇怪，所以没加。

**Comment by FishOrBear** [comment]
为了避免错误我觉得还是有必要加一下,不会影响实际功能,只影响类型校验
