### ISSUE TITLE
[UE5.0.0] 应用退出时程序崩溃

### ISSUE THREAD

**Issue by FishOrBear** [Tencent/puerts#809]
ts代码
```typescript
class MyActor extends UE.Actor
{
    p: UE.Vector2D;
    Constructor()
    {
        this.p = new UE.Vector2D(1, 2); //移除掉这行就不会崩溃了
    }
}
let cls = makeUClass(MyActor);
```

还原步骤:
打包
执行程序
关闭窗体后
![image](https://user-images.githubusercontent.com/19372111/168202169-3175764b-0c1e-4a47-9f39-3f9933597e60.png)

**Comment by FishOrBear** [comment]
解决了,看起来新版本的不再需要在结束的时候调用下面的代码,否则出现这个错误
```
	for (auto& Script : Scripts)
		Script.Value.Reset();
	Scripts.Reset();

	if (GEngine)
	{
		GEngine->ForceGarbageCollection(true);
		GEngine->ConditionalCollectGarbage();
	}
```

**Comment by chexiongsheng** [comment]
> 解决了,看起来新版本的不再需要在结束的时候调用下面的代码,否则出现这个错误
> 
> ```
> 	for (auto& Script : Scripts)
> 		Script.Value.Reset();
> 	Scripts.Reset();
> 
> 	if (GEngine)
> 	{
> 		GEngine->ForceGarbageCollection(true);
> 		GEngine->ConditionalCollectGarbage();
> 	}
> ```

 为啥之前要加这代码呢？

**Comment by FishOrBear** [comment]
应该也是为了解决窗体关闭时弹出错误警告.

**Comment by chexiongsheng** [comment]
Scripts是啥？
ForceGarbageCollection看上去应该加上也不会导致崩溃。

**Comment by FishOrBear** [comment]
TMap<uint32, TSharedPtr<puerts::FJsEnv>> Scripts;

我现在在调试为什么程序启动后会崩溃的问题,不知道和这个有没有关联

**Comment by FishOrBear** [comment]
![image](https://user-images.githubusercontent.com/19372111/168233613-5ed03c29-9608-4322-a1c3-21e07cddbc4c.png)

奇怪了 不知道为什么会崩溃

**Comment by FishOrBear** [comment]
环境是nodejs

**Comment by FishOrBear** [comment]
猜测可能和https://github.com/Tencent/puerts/issues/780 类似

**Comment by FishOrBear** [comment]
> > 解决了,看起来新版本的不再需要在结束的时候调用下面的代码,否则出现这个错误
> > ```
> > 	for (auto& Script : Scripts)
> > 		Script.Value.Reset();
> > 	Scripts.Reset();
> > 
> > 	if (GEngine)
> > 	{
> > 		GEngine->ForceGarbageCollection(true);
> > 		GEngine->ConditionalCollectGarbage();
> > 	}
> > ```
> 
> 为啥之前要加这代码呢？

应该在编辑器环境时,防止资源没有回收,切换地图时出问题加入的这个代码

**Comment by chexiongsheng** [comment]
你的WITH_BACKING_STORE_AUTO_FREE为true么

**Comment by chexiongsheng** [comment]
编辑器下应该不会用到backing store，你是编辑器下崩溃还是打包后崩溃呢？

**Comment by FishOrBear** [comment]
打包后崩溃  我没有设置过WITH_BACKING_STORE_AUTO_FREE  我应该设置它吗?

**Comment by chexiongsheng** [comment]
那我知道原因了

**Comment by FishOrBear** [comment]
怎么办,在线等

**Comment by FishOrBear** [comment]
看起来解决了
