### ISSUE TITLE
[Unity] invoke any generic method by some util function like `puerts.$generic`

### ISSUE THREAD

**Issue by zombieyang** [Tencent/puerts#819]
## detail | 详细描述
如XLua做的一样
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%94%AF%E6%8C%81%E6%B3%9B%E5%9E%8B%E6%96%B9%E6%B3%95%E7%9A%84%E8%B0%83%E7%94%A8%E4%B9%88

**Comment by chexiongsheng** [comment]
xlua的实现：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/StaticLuaCallbacks.cs#L1146
