### ISSUE TITLE
[UE] ts继承TableRowBase的时候 增加一个属性 ue客户端崩溃

### ISSUE THREAD

**Issue by kong21690** [Tencent/puerts#822]
ue版本：4.27

**复现步骤：** 
新建ts文件 ，继承UE.TableRowBase  任意薪资一个属性
**例子：**
class TS_WeaponData extends UE.TableRowBase {
    WeaponID: number;
}
ue4 客户端就会崩溃

**Log：**
LoginId:3ba2b4844988c250e03a57888706f777
EpicAccountId:f6c37292b52e431c9603aa4263a45cf3

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000000001b8

UE4Editor_UnrealEd
UE4Editor_PuertsEditor!UPEBlueprintAsset::AddMemberVariable() [D:\ue_project\polygonFps\Plugins\Puerts\Source\PuertsEditor\Private\PEBlueprintAsset.cpp:896]
UE4Editor_PuertsEditor!UPEBlueprintAsset::AddMemberVariableWithMetaData() [D:\ue_project\polygonFps\Plugins\Puerts\Source\PuertsEditor\Private\PEBlueprintAsset.cpp:989]
UE4Editor_PuertsEditor!UPEBlueprintAsset::execAddMemberVariableWithMetaData() [D:\ue_project\polygonFps\Plugins\Puerts\Intermediate\Build\Win64\UE4Editor\Inc\PuertsEditor\PEBlueprintAsset.gen.cpp:296]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_JsEnv!puerts::FFunctionTranslator::Call() [D:\ue_project\polygonFps\Plugins\Puerts\Source\JsEnv\Private\FunctionTranslator.cpp:271]
UE4Editor_JsEnv!puerts::FFunctionTranslator::Call() [D:\ue_project\polygonFps\Plugins\Puerts\Source\JsEnv\Private\FunctionTranslator.c

**Comment by chexiongsheng** [comment]
目前并不支持继承UStruct。
不过进入生成逻辑并崩溃时不对的，我加个判断。

**Comment by chexiongsheng** [comment]
之前那个修改会导致Vector参数用不了，再更新下
