### ISSUE TITLE
[unreal]在ts中访问不到DataTable数据

### ISSUE THREAD

**Issue by bichengming** [Tencent/puerts#836]
## detail | 详细描述
DataTable的结构是用蓝图结构体定义的，在ts中读取不到这个DataTable的数据，代码如下
![image](https://user-images.githubusercontent.com/1991439/170488482-9a0cfead-ee1a-4ac1-b177-e5633e995af9.png)

不清楚是不是引用参数的写法不对？简单debug了一下，execGetDataTableRowFromName函数中Stack.MostRecentProperty为空

**Comment by chexiongsheng** [comment]
GetDataTableRowFromName不就普通函数么？
访问不到表现为什么？报错，还是数据不符合预期？

**Comment by lzj10** [comment]
> GetDataTableRowFromName不就普通函数么？ 访问不到表现为什么？报错，还是数据不符合预期？

这个不是普通方法 是一个特殊的函数 ，蓝图调用过来 Code是存在的 ts调用过来Code为空 所以报错了 原因是UFunction中的Script是空的
![image](https://user-images.githubusercontent.com/5946974/179968517-10c4bf2e-07fa-4324-bbd5-26c314ceae63.png)
![image](https://user-images.githubusercontent.com/5946974/179968554-17e2720c-9c8e-49aa-9190-fc50ba3b6ec7.png)
![image](https://user-images.githubusercontent.com/5946974/179968821-15f366dd-a2b3-4bea-bba6-b04de048dfe5.png)
