### ISSUE TITLE
[Unity] macOS + Unity 2021.3.3f1c1 环境下创建JsEnv运行崩溃

### ISSUE THREAD

**Issue by benloong** [Tencent/puerts#841]
## error log | 日志或报错信息
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Unity [7297]
Path:                  /Applications/Unity/*/Unity.app/Contents/MacOS/Unity
Identifier:            com.unity3d.UnityEditor5.x
Version:               Unity version 2021.3.3f1c1 (2021.3.3f1c1)
Code Type:             X86-64 (Native)
Parent Process:        Unity Hub [823]
Responsible:           Unity Hub [823]
User ID:               501

Date/Time:             2022-05-31 10:40:30.0166 +0800
OS Version:            macOS 12.3 (21E230)
Report Version:        12
Bridge OS Version:     6.4 (19P4242)
Anonymous UUID:        D12A3FE4-5CE2-3A2B-FBC5-C4CE6069EA10

Time Awake Since Boot: 3400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  tid_103  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000e8
Exception Codes:       0x0000000000000001, 0x00000000000000e8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   Unity [7297]

VM Region Info: 0xe8 is not in any region.  Bytes before following region: 4478598936
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10af20000-10edb8000    [ 62.6M] r-x/r-x SM=COW  ...s/MacOS/Unity

Thread 0 Crashed:: tid_103 Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80a82bb9e __kill + 10
1   libmonobdwgc-2.0.dylib        	       0x179105bc0 mono_chain_signal + 79
2   libmonobdwgc-2.0.dylib        	       0x179029070 mono_sigsegv_signal_handler_debug + 704
3   libsystem_platform.dylib      	    0x7ff80a877dfd _sigtramp + 29
4   ???                           	               0x0 ???
5   puerts.bundle                 	       0x1c4d885bf asio::detail::reactive_socket_service_base::do_open(asio::detail::reactive_socket_service_base::base_implementation_type&, int, int, int, std::__1::error_code&) + 111
6   puerts.bundle                 	       0x1c4d88260 websocketpp::transport::asio::endpoint<websocketpp::config::asio::transport_config>::listen(asio::ip::basic_endpoint<asio::ip::tcp> const&, std::__1::error_code&) + 144
7   puerts.bundle                 	       0x1c4d7ff99 puerts::V8InspectorClientImpl::V8InspectorClientImpl(int, v8::Local<v8::Context>) + 1305
8   puerts.bundle                 	       0x1c4d81e3b puerts::CreateV8Inspector(int, void*) + 43
9   puerts.bundle                 	       0x1c4d76b0c puerts::JSEngine::CreateInspector(int) + 108
10  ???                           	       0x1b3325e22 ???
11  ???                           	       0x1999ba4fb ???
12  ???                           	       0x1999b94da ???
13  ???                           	       0x1999b89db ???
14  libmonobdwgc-2.0.dylib        	       0x17902bf3c mono_jit_runtime_invoke + 1587
15  libmonobdwgc-2.0.dylib        	       0x1791e1467 do_runtime_invoke + 80
16  libmonobdwgc-2.0.dylib        	       0x1791e13a4 mono_runtime_invoke + 94
17  Unity                         	       0x10bbbd9b7 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) + 71
18  Unity                         	       0x10bbb8946 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 166
19  Unity                         	       0x10bbb8816 ScriptingInvocation::InvokeChecked(ScriptingExceptionPtr*) + 54
20  Unity                         	       0x10bc45c44 SerializableManagedRef::CallMethod(Object&, ScriptingMethodPtr) + 116
21  Unity                         	       0x10bb606f0 MonoBehaviour::CallAwake() + 336
22  Unity                         	       0x10bb61037 MonoBehaviour::AddToManager() + 359
23  Unity                         	       0x10b7d2aba SetupScriptForIManagedObjectHost(Object*, ScriptingClassPtr, MonoScript*) + 218
24  Unity                         	       0x10b7d2318 AddComponentUnchecked(GameObject&, Unity::Type const*, ScriptingClassPtr, MonoScript*, core::basic_string<char, core::StringStorageDefault<char> >*, AwakeFromLoadQueue*) + 632
25  Unity                         	       0x10b7d43d2 AddComponent(GameObject&, Unity::Type const*, ScriptingClassPtr, core::basic_string<char, core::StringStorageDefault<char> >*, AwakeFromLoadQueue*, char const*, dynamic_array<Unity::Component*, 0ul>*) + 770
26  Unity                         	       0x10baa1cfe MonoAddComponentWithType(GameObject&, ScriptingSystemTypeObjectPtr) + 254
27  Unity                         	       0x10af2fc1b GameObject_CUSTOM_Internal_AddComponentWithType(ScriptingBackendNativeObjectPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*) + 219
28  ???                           	       0x1990e56e4 ???
29  libmonobdwgc-2.0.dylib        	       0x17902bf3c mono_jit_runtime_invoke + 1587
30  libmonobdwgc-2.0.dylib        	       0x1791e1467 do_runtime_invoke + 80
31  libmonobdwgc-2.0.dylib        	       0x1791e13a4 mono_runtime_invoke + 94
32  Unity                         	       0x10bbbd9b7 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) + 71
33  Unity                         	       0x10bbb8946 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 166
34  Unity                         	       0x10bbb8816 ScriptingInvocation::InvokeChecked(ScriptingExceptionPtr*) + 54
35  Unity                         	       0x10bc45c44 SerializableManagedRef::CallMethod(Object&, ScriptingMethodPtr) + 116
36  Unity                         	       0x10bb606f0 MonoBehaviour::CallAwake() + 336
37  Unity                         	       0x10bb61037 MonoBehaviour::AddToManager() + 359
38  Unity                         	       0x10bc85f18 AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool) + 440
39  Unity                         	       0x10bc85c36 AwakeFromLoadQueue::PersistentManagerAwakeFromLoad(int, AwakeFromLoadMode, bool) + 294
40  Unity                         	       0x10b84277c LoadSceneOperation::CompleteAwakeSequence() + 716
41  Unity                         	       0x10b841e27 LoadSceneOperation::CompletePreloadManagerLoadSceneEditor() + 663
42  Unity                         	       0x10b8411a1 LoadSceneOperation::IntegrateMainThread() + 241
43  Unity                         	       0x10b84444d PreloadManager::UpdatePreloadingSingleStep(PreloadManager::UpdatePreloadingFlags, int) + 269
44  Unity                         	       0x10b845061 PreloadManager::WaitForAllAsyncOperationsToComplete() + 193
45  Unity                         	       0x10c8b27dd EditorSceneManager::RestoreSceneBackups(std::__1::vector<EditorSceneBackup, stl_allocator<EditorSceneBackup, (MemLabelIdentifier)124, 16> >&, EditorSceneManager::PlayModeChange) + 1565
46  Unity                         	       0x10cb8dc52 PlayerLoopController::EnterPlayMode() + 594
47  Unity                         	       0x10cb85317 PlayerLoopController::SetIsPlaying(bool) + 679
48  Unity                         	       0x10cb833f3 Application::TickTimer() + 5123
49  Unity                         	       0x10dac132f -[EditorApplication TickTimer] + 559
50  Foundation                    	    0x7ff80b7bd281 __NSFireTimer + 67
51  CoreFoundation                	    0x7ff80a941899 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
52  CoreFoundation                	    0x7ff80a941388 __CFRunLoopDoTimer + 923
53  CoreFoundation                	    0x7ff80a940ef8 __CFRunLoopDoTimers + 307
54  CoreFoundation                	    0x7ff80a927646 __CFRunLoopRun + 2010
55  CoreFoundation                	    0x7ff80a9267ac CFRunLoopRunSpecific + 562
56  HIToolbox                     	    0x7ff8135adce6 RunCurrentEventLoopInMode + 292
57  HIToolbox                     	    0x7ff8135ad913 ReceiveNextEventCommon + 283
58  HIToolbox                     	    0x7ff8135ad7e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
59  AppKit                        	    0x7ff80d34d5cd _DPSNextEvent + 927
60  AppKit                        	    0x7ff80d34bc8a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
61  AppKit                        	    0x7ff80d33e339 -[NSApplication run] + 586
62  AppKit                        	    0x7ff80d3122b7 NSApplicationMain + 817
63  Unity                         	       0x10dabe445 EditorMain(int, char const**) + 949
64  Unity                         	       0x10dabe769 main + 9
65  dyld                          	       0x1196a151e start + 462
## context | 编译/运行环境
macOS Monterey （2.2 GHz 六核Intel Core i7） + Unity 2021.3.3f1c1 
puerts 1.3.3
## how to reproduce | 复现步骤
1. 新建空工程，导入puerts插件。
2. 代码中创建JsEnv `new JsEnv(new DefaultLoader(), 9999); `

## more | 其他
Unity 2021.3.2f1c1 不会崩溃

**Comment by zgz682000** [comment]
我也遇到这个问题了，应该是PuertsDLL.CreateInspector导致的，暂时先把debugPort设置成-1了

**Comment by benloong** [comment]
2021.3.4 版本的崩溃栈信息
```
Obtained 62 stack frames.
#0  0x000001cfcb3557 in asio::detail::kqueue_reactor::allocate_descriptor_state()
#1  0x000001cfcb329f in asio::detail::reactive_socket_service_base::do_open(asio::detail::reactive_socket_service_base::base_implementation_type&, int, int, int, std::__1::error_code&)
#2  0x000001cfcb2f40 in websocketpp::transport::asio::endpoint<websocketpp::config::asio::transport_config>::listen(asio::ip::basic_endpoint<asio::ip::tcp> const&, std::__1::error_code&)
#3  0x000001cfcaac79 in puerts::V8InspectorClientImpl::V8InspectorClientImpl(int, v8::Local<v8::Context>)
#4  0x000001cfcacb1b in puerts::CreateV8Inspector(int, void*)
#5  0x000001cfca0821 in puerts::JSEngine::CreateInspector(int)
#6  0x0000019766dc92 in  (wrapper managed-to-native) Puerts.PuertsDLL:CreateInspector (intptr,int) [{0x7ff5ed5c08f8} + 0xe2]  (0x19766dbb0 0x19766dd7b) [0x174bc2a80 - Unity Child Domain]
#7  0x00000197143b2b in  Puerts.JsEnv:.ctor (Puerts.ILoader,int) [{0x7ff5f11d1280} + 0x9b] [/Users/wangbenlong/workspace/project002/client/Assets/Puerts/Runtime/Src/JsEnv.cs :: 68u] (0x197143a90 0x197143b7c) [0x174bc2a80 - Unity Child Domain]
#8  0x0000019766cc6a in  System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<TStateMachine_REF> (TStateMachine_REF&) [{0x60000bc51920} + 0x1ea]  (0x19766ca80 0x19766cd59) [0x174bc2a80 - Unity Child Domain]
#9  0x0000019766c0ab in  ScriptManager:Awake () [{0x7ff5f14df120} + 0x21b]  (0x19766be90 0x19766c0f3) [0x174bc2a80 - Unity Child Domain]
#10 0x0000017b6ebd9c in mono_jit_runtime_invoke
#11 0x0000017b8a13bb in do_runtime_invoke
#12 0x0000017b8a12f8 in mono_runtime_invoke
#13 0x0000010d5eab17 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
#14 0x0000010d5e5aa6 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
#15 0x0000010d5e5976 in ScriptingInvocation::InvokeChecked(ScriptingExceptionPtr*)
#16 0x0000010d672da4 in SerializableManagedRef::CallMethod(Object&, ScriptingMethodPtr)
#17 0x0000010d58d840 in MonoBehaviour::CallAwake()
#18 0x0000010d58e18e in MonoBehaviour::AddToManager()
#19 0x0000010d1feb1a in SetupScriptForIManagedObjectHost(Object*, ScriptingClassPtr, MonoScript*)
#20 0x0000010d1fe378 in AddComponentUnchecked(GameObject&, Unity::Type const*, ScriptingClassPtr, MonoScript*, core::basic_string<char, core::StringStorageDefault<char> >*, AwakeFromLoadQueue*)
#21 0x0000010d200432 in AddComponent(GameObject&, Unity::Type const*, ScriptingClassPtr, core::basic_string<char, core::StringStorageDefault<char> >*, AwakeFromLoadQueue*, char const*, dynamic_array<Unity::Component*, 0ul>*)
#22 0x0000010d4cedce in MonoAddComponentWithType(GameObject&, ScriptingSystemTypeObjectPtr)
#23 0x0000010c95b61b in GameObject_CUSTOM_Internal_AddComponentWithType(ScriptingBackendNativeObjectPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
#24 0x000001972d0644 in  (wrapper managed-to-native) UnityEngine.GameObject:Internal_AddComponentWithType (UnityEngine.GameObject,System.Type) [{0x7ff5f6131258} + 0x104]  (0x1972d0540 0x1972d0745) [0x174bc2a80 - Unity Child Domain]
#25 0x0000017b6ebd9c in mono_jit_runtime_invoke
#26 0x0000017b8a13bb in do_runtime_invoke
#27 0x0000017b8a12f8 in mono_runtime_invoke
#28 0x0000010d5eab17 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
#29 0x0000010d5e5aa6 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
#30 0x0000010d5e5976 in ScriptingInvocation::InvokeChecked(ScriptingExceptionPtr*)
#31 0x0000010d672da4 in SerializableManagedRef::CallMethod(Object&, ScriptingMethodPtr)
#32 0x0000010d58d840 in MonoBehaviour::CallAwake()
#33 0x0000010d58e18e in MonoBehaviour::AddToManager()
#34 0x0000010d6b3078 in AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool)
#35 0x0000010d6b2d96 in AwakeFromLoadQueue::PersistentManagerAwakeFromLoad(int, AwakeFromLoadMode, bool)
#36 0x0000010d26e7fc in LoadSceneOperation::CompleteAwakeSequence()
#37 0x0000010d26dea7 in LoadSceneOperation::CompletePreloadManagerLoadSceneEditor()
#38 0x0000010d26d221 in LoadSceneOperation::IntegrateMainThread()
#39 0x0000010d2704cd in PreloadManager::UpdatePreloadingSingleStep(PreloadManager::UpdatePreloadingFlags, int)
#40 0x0000010d2710e1 in PreloadManager::WaitForAllAsyncOperationsToComplete()
#41 0x0000010e2e1b7d in EditorSceneManager::RestoreSceneBackups(std::__1::vector<EditorSceneBackup, stl_allocator<EditorSceneBackup, (MemLabelIdentifier)124, 16> >&, EditorSceneManager::PlayModeChange)
#42 0x0000010e5bce52 in PlayerLoopController::EnterPlayMode()
#43 0x0000010e5b4517 in PlayerLoopController::SetIsPlaying(bool)
#44 0x0000010e5b25f3 in Application::TickTimer()
#45 0x0000010f4f2cef in -[EditorApplication TickTimer]
#46 0x007ff80b7bd281 in __NSFireTimer
#47 0x007ff80a941899 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
#48 0x007ff80a941388 in __CFRunLoopDoTimer
#49 0x007ff80a940ef8 in __CFRunLoopDoTimers
#50 0x007ff80a927646 in __CFRunLoopRun
#51 0x007ff80a9267ac in CFRunLoopRunSpecific
#52 0x007ff8135adce6 in RunCurrentEventLoopInMode
#53 0x007ff8135ad913 in ReceiveNextEventCommon
#54 0x007ff8135ad7e5 in _BlockUntilNextEventMatchingListInModeWithFilter
#55 0x007ff80d34d5cd in _DPSNextEvent
#56 0x007ff80d34bc8a in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
#57 0x007ff80d33e339 in -[NSApplication run]
#58 0x007ff80d3122b7 in NSApplicationMain
#59 0x0000010f4efe05 in EditorMain(int, char const**)
#60 0x0000010f4f0129 in main
#61 0x000001203c051e in (Unknown)
```

**Comment by bydreamxxx** [comment]
2021.3.5也崩溃，只能先把DebugPort去掉了

**Comment by zgz682000** [comment]
@zombieyang 大佬可否出一个1.2.x libversion=15 的release
