### ISSUE TITLE
[UE] index.d.ts文件中的declare重复

### ISSUE THREAD

**Issue by zeuong** [Tencent/puerts#847]
![image](https://user-images.githubusercontent.com/66762695/171580260-82bdccc2-a6e8-4941-8a28-2dab5e023f75.png)

请问有遇到这种问题么

**Comment by chexiongsheng** [comment]
你引入的库也声明了一个，你注释掉其中一个就可以了

**Comment by zeuong** [comment]
车神，因为两者实现不一样，我这边是把index这边的require改成了querts_require，应该没问题吧

**Comment by chexiongsheng** [comment]
改名跟删没区别
