### ISSUE TITLE
[Unity] 导出"UnityEngine.InputSystem"命名空间后生成的index.d.ts报错

### ISSUE THREAD

**Issue by luuuuyang** [Tencent/puerts#857]
## detail | 详细描述
Unity 2020.3.34f1c2
Input System 1.3.0

**Comment by zombieyang** [comment]
两个原因：
1. 扩展函数以及delegate类型如果带了指针参数，目前没被过滤掉，是bug。
2. enum如果带有扩展函数，要用namespace，不能用interface进行dts merge。


另外下次请把详细描述写得详细些，至少说明是什么类生成出问题，InputSystem不涉及敏感代码可以直接截图。

**Comment by luuuuyang** [comment]
感谢，第一次提issue不周到的地方还请见谅
