### ISSUE TITLE
[unreal]  请问能不能和unlua一样一个蓝图对应一个ts？

### ISSUE THREAD

**Issue by jackfong66** [Tencent/puerts#859]
假设UMG蓝图A中  嵌套调用了其他UMG蓝图B。  并且 A的逻辑用ts编写。  B的逻辑也希望用ts编写。 这个如何实现？

**Comment by chexiongsheng** [comment]
不太明白你说啥。从标题到内容。
什么叫“和unlua一样一个蓝图对应一个ts”？如果你说的是unlua的所谓“override”功能，这功能puerts类似的功能叫mixin。
如果是puerts的继承ts类功能，unlua并没对应的东西，而且这功能本来就只能一个ts生成一个蓝图。

你内容描述的东西，没看出puerts哪里限制了你要实现的东西，还是你没表达清楚？

**Comment by jackfong66** [comment]
> 

谢谢，可能是我没表达清楚 或者没有研究明白mixin能不能实现。

我之前使用继承引擎的方式没有达到效果。我的使用方法如下

TS：  BP_CustomButton extends UE.Button   -> 这样会在/Game/Blueprints/TypeScript下生成一个BP_CustomButton蓝图。
我尝试将这个蓝图拖到一个UserWidget里，发现不行。
我准备试试mixin看看是否可以实现。
