### ISSUE TITLE
是否计划支援iOS armv7？

### ISSUE THREAD

**Issue by h3902340** [Tencent/puerts#86]
如题，是否计划支援iOS armv7？我们游戏支援iOS armv7，但是puerts没有支援iOS armv7

**Comment by chexiongsheng** [comment]
armv7的设备只有iphone5c及以下。
ios11已经禁用armv7应用。
新版本的xcode已经编译不了armv7。
你还提审armv7干嘛呢？

**Comment by h3902340** [comment]
我们iOS最低版号是设在10.0，所以还有支援小部分armv7用户。希望puerts能支持armv7

**Comment by chexiongsheng** [comment]
台湾的国语和大陆的国语区别那么大么。。
ios11是完全禁用armv7，意味着你只提交armv7，ios11以上用不了。
ios10是同时支持armv7和arm64，两者都能跑的情况下优先跑arm64。
你只提交arm64，影响只是不支持iphone5及以下的设备。但那种设备应该千分之一都不到。

**Comment by chexiongsheng** [comment]
苹果的ios版本情况：https://developer.apple.com/support/app-store/
