### ISSUE TITLE
关于Chrome DevTools 接入V8调试性能分析问题

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#861]
## detail | 详细描述
性能录制时，提示错误：Performance trace recording not  supported  for this type of target的，不知道在哪里设置？怎么解决呢？
![image](https://user-images.githubusercontent.com/575589/173065993-0b58618f-8e00-4f99-8cc6-3f7802cca0e6.png)

**Comment by zombieyang** [comment]
看性能用javascript profile，别用performance
我只知道英文叫这两个
