### ISSUE TITLE
在清理动态多路委托的时候没生效

### ISSUE THREAD

**Issue by 276455058** [Tencent/puerts#864]
## detail | 详细描述
![Q)RY9LMROOOXIK)5(`7Y CI](https://user-images.githubusercontent.com/42234865/173344678-1ebdf187-6004-426d-84fb-d3d669229f97.png)
如图，直接返回了
调用代码是
![G GG 2}GHI6DL~$G~172QN0](https://user-images.githubusercontent.com/42234865/173344745-a0169b73-b0ff-437c-898c-5cfb1576ee74.png)
一直无法生效。onClick是一个动态多路委托
![IR2OOR425547B7I1G M)0IY](https://user-images.githubusercontent.com/42234865/173344804-1b1df595-23b1-4905-a5ec-958acba3d5fa.png)

**Comment by chexiongsheng** [comment]
你代码错了吧？
不同的bind，返回的函数不一样。
如果需要bind，你得把Add的时候bind的返回保存下来，后面Remove

**Comment by 276455058** [comment]
可以了，谢谢指点
