### ISSUE TITLE
[ureal]请问游戏逻辑的主循环应该怎么添加

### ISSUE THREAD

**Issue by 276455058** [Tencent/puerts#866]
## detail | 详细描述
游戏的主循环是不是应该注册到FSlateApplication::Get().OnPostTick()这个回调上面，然后由JsEnv回调到Ts里面执行啊？

**Comment by 276455058** [comment]
还是用说用TSGameInstance里面的TimerManager去调用到Ts执行呢？

**Comment by chexiongsheng** [comment]
issues用来反馈puerts的bug（至少你感觉是bug）。
你问的属于你游戏本身如何设计的问题。应该自行把握和探索。每个项目自有其特殊性，别人也给不了什么意见。

**Comment by 276455058** [comment]
> 好的，懂了，多谢
