### ISSUE TITLE
[Unity]fork工程然后加入自己代码，变为private的时候，使用github workflows action编译会报错

### ISSUE THREAD

**Issue by quaerere** [Tencent/puerts#874]
Run dawidd6/action-download-artifact@v2
==> Artifact name: qjs_v8_bin
==> Local path: unity/native_src/
==> Workflow name: build_quickjs.yml
==> Repository: quaerere/puerts
==> Workflow conclusion: success
Error: Resource not accessible by integration

fork工程然后加入自己代码，变为private的时候，使用github workflows action编译会报错，能不能编译unity plugins的时候，依赖v8 库直接http去请求一个url，不要自己编译了，也没搞懂为什么会有这种权限问题

**Comment by chexiongsheng** [comment]
应该直接wget一个url去获取库
