### ISSUE TITLE
【BUG】生成代码，c#返回到js字符串如果为null，则会崩溃

### ISSUE THREAD

**Issue by ctxdegithub** [Tencent/puerts#88]
系统：Mac
版本：Tag:v1.0.6,Plugin_Version:7
```ts
var result = obj.Error;
// 如果result == null，ReturnString就会崩溃
Puerts.PuertsDLL.ReturnString(isolate, info, result);
```
![image](https://user-images.githubusercontent.com/8472028/99037481-ba078100-25be-11eb-8323-2f45e5542ebd.png)

**Comment by ctxdegithub** [comment]
修改生成模板：string: 'Puerts.PuertsDLL.ReturnString(isolate, info, result ?? "")',
或者该原生代码判断处理（感觉这样更高效一些）

**Comment by chexiongsheng** [comment]
不能这么改，这语法低版本unity用不了
而且也没改全
