### ISSUE TITLE
[Unity] 静态变量在Ts赋值，断点定位跑到c# get方法

### ISSUE THREAD

**Issue by Persiechan** [Tencent/puerts#881]
## error log | 
![E3}HS 6%BJ) )3P)%`C_1F8](https://user-images.githubusercontent.com/30543982/175508551-192e4b91-772a-4090-bd83-55dc788c0285.png)

## context |
静态变量UnityEngine.Screen.sleepTimeout的 get set方法已经在c#端注册
![I_Y03_K0RB} D8@9MXX3~JW](https://user-images.githubusercontent.com/30543982/175508852-8baa226b-5e25-420b-b024-d9a4b9530cc0.png)
![}_`48}BFW2R9Y8) LFG$6_W](https://user-images.githubusercontent.com/30543982/175508871-b024e920-03b4-443c-8401-73922e375eb4.png)

## how to reproduce | 复现步骤
1.Ts端调用
![)A2_W(~%%6T3@7%6P%0C4 A](https://user-images.githubusercontent.com/30543982/175509377-d194d671-caa5-41d8-91c3-08c45eae053d.png)
2.控制台打印
![JO2OI5LS7J(M5Q}F970J2MP](https://user-images.githubusercontent.com/30543982/175509549-c948fde8-4953-4c89-8c75-64874732b648.png)

**Comment by Persiechan** [comment]
补充一下：16版本是可以的，17版本不行

**Comment by zombieyang** [comment]
用demo项目测试了一下2017.1.0f3，并没有复现该问题。是否是替换文件的时候替换少了？
2017版本可能是有一个.mjs文件替换成.mjs.txt的过程

**Comment by Persiechan** [comment]
谢谢，确实是替换文件少了
