### ISSUE TITLE
[ue]在Window平台使用quickjs的问题

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#886]
好长时间没有跑window平台的quickjs了，发现了一个崩溃，V8下是没有问题的
![image](https://user-images.githubusercontent.com/575589/176425785-ffde83c9-ed36-486d-b8d8-36526e459b52.png)

![image](https://user-images.githubusercontent.com/575589/176425721-c85d01aa-6e9f-4e2b-9a0e-8ec8de44c73d.png)

![image](https://user-images.githubusercontent.com/575589/176425581-a941a46d-a4fd-4945-b058-22668bdd1d61.png)
不知道跟什么有关系 ？麻烦看一下

**Comment by chexiongsheng** [comment]
上次不是说过了么？
quickjs实现v8的过程中用了静态变量（V8自己也有）。所以编辑器下静态绑定只能在JsEnv模块内进行。

**Comment by liuzongan** [comment]
怎么判断是静态绑定的问题啊?车神，下次就不用麻烦您了

**Comment by liuzongan** [comment]
谢谢了，车神，找到规则了，谢谢了
