### ISSUE TITLE
[UE]Switch平台一些奇怪的bug

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#889]
日志错误很常见TypeError: cannot read property 'Add' of undefined，但是不好解决：
![image](https://user-images.githubusercontent.com/575589/176845224-420963c0-143c-416a-a9a8-5b7269a3525f.png)
这个tiles不是空的，是有值的
![image](https://user-images.githubusercontent.com/575589/176845655-6c4661a0-b775-4ff3-9b11-63c454cde189.png)

GuideMarkInfo 这个是C++的定义
![image](https://user-images.githubusercontent.com/575589/176845862-9e2149f3-8fd0-4b81-89fa-239024ff1087.png)
构造器中初始化了
![image](https://user-images.githubusercontent.com/575589/176846012-972e6c4f-2b93-494b-b7ba-e16b1e884f98.png)

UGuideMapInfo：也是C++定义
![image](https://user-images.githubusercontent.com/575589/176846151-3fca5ebe-c101-4bab-ad91-244baeffa752.png)

使用这个Tiles属性就有问题，window编辑器（quickjs）下是没有这个问题的，在Switch平台是有问题的

麻烦帮忙分析 一下了

**Comment by chexiongsheng** [comment]
faq就有啊

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/blob/master/doc/unreal/faq.md#%E6%89%93%E5%8C%85%E5%90%8E%E8%BF%90%E8%A1%8C%E6%97%B6%E6%8A%A5%E4%B8%80%E4%BA%9B%E5%AD%97%E6%AE%B5%E6%89%BE%E4%B8%8D%E5%88%B0

**Comment by liuzongan** [comment]
问题是Window 版本打包后V8是没有这个问题的啊，只有Switch平台有一些这种问题啊

**Comment by liuzongan** [comment]
但是我只要重新修改一个名字就没有问题了，在Switch平台下会有这么多这样的问题

**Comment by liuzongan** [comment]
![image](https://user-images.githubusercontent.com/575589/177072251-33687ac3-9cb6-46a0-bddc-96a7ff11e837.png)
这句话怎么理解？怎么创建个大写的字段呢？
我们的window出包与mac平台出包都没有这个问题啊，Switch平台怎么就有这样的问题呢
