### ISSUE TITLE
process.memoryUsage() 方法可以用来查看 V8 引擎的内存使用量, 请问PuerTS中如何拿到内存信息？

### ISSUE THREAD

**Issue by jinqi166** [Tencent/puerts#89]
process.memoryUsage() 方法可以用来查看 V8 引擎的内存使用量, 请问PuerTS中如何拿到内存信息？

**Comment by jinqi166** [comment]
感觉因该把 v8的getHeapStatistics暴露出来会好点，有些时候可能需要统计局部代码块的内存开销

**Comment by chexiongsheng** [comment]
直接用chrome dev tool连过去就可以看，有可视化图表不香么？
