### ISSUE TITLE
[UE] 更新到UE_V1.0.1后，枚举蓝图报错问题

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#890]
## detail | 详细描述

1. 枚举蓝图文件

![image](https://user-images.githubusercontent.com/18215765/176998110-12f4cace-c765-46ab-a1e0-310b09f85a08.png)

![image](https://user-images.githubusercontent.com/18215765/176998103-afe5250f-5026-4c99-9604-4da487c3f70f.png)

2. 导出.d.ts
会有字符串类型？！
![image](https://user-images.githubusercontent.com/18215765/176998145-66c7ac52-75b0-4b3f-81e3-34b6d8febc3a.png)

3.代码中使用
![image](https://user-images.githubusercontent.com/18215765/176998182-f4e7f84b-0b8f-46b3-ba1f-c6753d500524.png)

4. 报错
![image](https://user-images.githubusercontent.com/18215765/176998196-0e764582-d1b2-477d-b20d-f3636f3987e1.png)

**Comment by zhang357622852** [comment]
枚举名称中存在空格的话，导出的时候就是会变成字符串类型

**Comment by zhang357622852** [comment]
目前测试到的是：因为我在IDeclarationGenerator加上了不生成命名空间的宏
![image](https://user-images.githubusercontent.com/18215765/176999889-2f1367c0-5923-4a7b-8904-242ef7d8cef2.png)

才会出现这个报错(puerts_ue_demo工程下测试的结果)

**Comment by chexiongsheng** [comment]
你有一年没更新了吧？

字符串那个是合法ts语法。

其次不能通过UE.XX访问蓝图枚举（任意蓝图）是很久很久之前就已经这样的。名字并不能唯一定位一个蓝图，很久很久前能通过UE.XX访问蓝图是一个错误，你工程能跑只是恰好符合你要求的蓝图在内存而已。

**Comment by zhang357622852** [comment]
嗯嗯，我取消这个宏声明了，修改了项目所有蓝图访问，就可以了
![](https://user-images.githubusercontent.com/18215765/176999889-2f1367c0-5923-4a7b-8904-242ef7d8cef2.png)
