### ISSUE TITLE
[UE] Switch平台打包后确实报一些字段找不到的疑问

### ISSUE THREAD

**Issue by liuzongan** [Tencent/puerts#892]
## detail | 详细描述
![image](https://user-images.githubusercontent.com/575589/177091904-bc4c64c1-d7f1-40f6-a8fc-e2165553cea8.png)
目前在我们项目Switch平台中发现确实像FAQ的描述的一样，但是Window打包后就没有这个问题，有没有办法在Windows上复现这种问题？不能在Switch进行测试这种问题呢？如果有更好的方案请指教一下？有没有比较好的方法解决这种问题啊？

描述一下项目中的另一个类似问题
找不到Tiles成员
生成代码是大写的Tiles
![image](https://user-images.githubusercontent.com/575589/177093024-ba0cc057-fa1a-46db-9bf3-172ebd6e3bc6.png)

但通过打印日志在Switch上是小写的：

![image](https://user-images.githubusercontent.com/575589/177093103-6d044091-669a-402f-a8f7-5e00c77a4a70.png)
 
Window上是大写的：
![image](https://user-images.githubusercontent.com/575589/177093166-c55b512b-6727-4b95-bc96-b1007d839bf6.png)

**Comment by chexiongsheng** [comment]
window你用的是v8吧？v8有用v8特有的机制规避了这个问题。你window用quickjs打包应该能复现

**Comment by liuzongan** [comment]
window是用的v8，是什么机制啊，可以quickjs上实现吗？
