### ISSUE TITLE
[UE] 继承一个普通的ts类 ，如果符合继承引擎类的扫描格式，也会尝试生成蓝图 然后报错

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#893]
## error log | 日志或报错信息
![image](https://user-images.githubusercontent.com/5946974/177128766-c4a4aa49-c2cd-4238-a1ea-9b4eb817ec52.png)
![image](https://user-images.githubusercontent.com/5946974/177128765-e5e77c7d-ebae-4c32-99ae-ddfde25e3cb8.png)

## context | 编译/运行环境
UE5.0
## how to reproduce | 复现步骤
1. 继承一个普通的ts类
2. 其他符合继承引擎类的2、3需求
![image](https://user-images.githubusercontent.com/5946974/177129304-81368f95-7043-4e38-af8d-c2677f675871.png)

puerts会尝试生成蓝图 然后报错，因为普通ts类没有GetClass方法

## more | 其他
尝试修复 ，暂时确定有没有其他问题
![image](https://user-images.githubusercontent.com/5946974/177131772-80ee126f-c791-4b40-95e0-dc166caba84e.png)

**Comment by chexiongsheng** [comment]
你可以提交个PR过来
