### ISSUE TITLE
[UE] ts继承UE类实现的行为树Task，UE 行为树无法扫描到，无法使用

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#896]
## detail | 详细描述
原因是UE行为树扫描task扫的是Blueprint，而puerts生成的蓝图除了Actor外BlueprintClassType 都被设置成 UTypeScriptBlueprint，所以UE的行为树无法发现 ts实现的Task。所以想请教几个问题

1. 为什么这么设计UTypeScriptBlueprint相对于UBlueprint有什么特殊处理的地方
2. 把UBTNode 和Actor一样设置成UBlueprint是否可行

![image](https://user-images.githubusercontent.com/5946974/177490669-0c2f3146-c5b5-4878-a58e-a6c4dd56755e.png)
![image](https://user-images.githubusercontent.com/5946974/177491012-4653c372-eded-4d4a-8449-33811c58d13e.png)

**Comment by Wangxiangyao-717** [comment]
根据我的理解，使用UTypeScriptBlueprint是为了在后面进行FKismetEditorUtilities::CompileBlueprint编译时，可以调用puerts内的FTypeScriptCompilerContext中的SpawnNewClass，因为除了Actor之外的蓝图类FKismetEditorUtilities::CreateBlueprint传入的BlueprintGeneratedClass，如果调用默认的FKismetCompilerContext，会导致他最终生成的是UBlueprintGeneratedClass而不是UTypeScriptGeneratedClass，就导致之后的脚本无法代理，如果其他什么都不改，出现的结果应该是UPEBlueprintAsset::Save中Cast<UTypeScriptGeneratedClass>(GeneratedClass)会为空，进而编译失败。
我的一个临时的办法是自己继承一个FKismetCompilerContext，然后重载他的SpawnNewClass，在里面进行判断，然后执行NewObject<UTypeScriptGeneratedClass>(Blueprint->GetOutermost(), FName(*NewClassName), RF_Public | RF_Transactional);同时使用FKismetCompilerContext::RegisterCompilerForBP注册UBlueprint::StaticClass()走你继承的FKismetCompilerContext的那个类

**Comment by lzj10** [comment]
> 根据我的理解，使用UTypeScriptBlueprint是为了在后面进行FKismetEditorUtilities::CompileBlueprint编译时，可以调用puerts内的FTypeScriptCompilerContext中的SpawnNewClass，因为除了Actor之外的蓝图类FKismetEditorUtilities::CreateBlueprint传入的BlueprintGeneratedClass，如果调用默认的FKismetCompilerContext，会导致他最终生成的是UBlueprintGeneratedClass而不是UTypeScriptGeneratedClass，就导致之后的脚本无法代理，如果其他什么都不改，出现的结果应该是UPEBlueprintAsset::Save中Cast(GeneratedClass)会为空，进而编译失败。 我的一个临时的办法是自己继承一个FKismetCompilerContext，然后重载他的SpawnNewClass，在里面进行判断，然后执行NewObject(Blueprint->GetOutermost(), FName(*NewClassName), RF_Public | RF_Transactional);同时使用FKismetCompilerContext::RegisterCompilerForBP注册UBlueprint::StaticClass()走你继承的FKismetCompilerContext的那个类

感谢 这个我大概看懂了  但是为什么继承Actor不需要 UTypeScriptBlueprint ，这个有点不太理解，理论上讲继承Actor也是需要蓝图的

**Comment by Wangxiangyao-717** [comment]
> > 根据我的理解，使用UTypeScriptBlueprint是为了在后面进行FKismetEditorUtilities::CompileBlueprint编译时，可以调用puerts内的FTypeScriptCompilerContext中的SpawnNewClass，因为除了Actor之外的蓝图类FKismetEditorUtilities::CreateBlueprint传入的BlueprintGeneratedClass，如果调用默认的FKismetCompilerContext，会导致他最终生成的是UBlueprintGeneratedClass而不是UTypeScriptGeneratedClass，就导致之后的脚本无法代理，如果其他什么都不改，出现的结果应该是UPEBlueprintAsset::Save中Cast(GeneratedClass)会为空，进而编译失败。 我的一个临时的办法是自己继承一个FKismetCompilerContext，然后重载他的SpawnNewClass，在里面进行判断，然后执行NewObject(Blueprint->GetOutermost(), FName(*NewClassName), RF_Public | RF_Transactional);同时使用FKismetCompilerContext::RegisterCompilerForBP注册UBlueprint::StaticClass()走你继承的FKismetCompilerContext的那个类
> 
> 感谢 这个我大概看懂了 但是为什么继承Actor不需要 UTypeScriptBlueprint ，这个有点不太理解，理论上讲继承Actor也是需要蓝图的

![image](https://user-images.githubusercontent.com/73415998/178892069-765e21bd-5809-47cb-a2dd-10ffa0580079.png)

**Comment by lzj10** [comment]
![image](https://user-images.githubusercontent.com/5946974/178913104-de6348c0-3352-4556-8295-872a5c292b95.png)
无论是否是Actor  BlueprintGeneratedClass 都是 UTypeScriptGeneratedClass ，但是只有Actor的BlueprintClass 是UBlueprint 而其他类型是UTypeScriptBlueprint，并且只有再PIE模式下才有效 这才是我疑惑的点
![image](https://user-images.githubusercontent.com/5946974/178913549-7cbe1a7b-f263-4f5b-963e-acd9fc4996ec.png)

**Comment by Wangxiangyao-717** [comment]
> 你看UE源码CreateBlueprint中，大部分的蓝图的生成类设置都是通过其中的FBlueprintCompilationManager::CompileSynchronously进行，通过CreateBlueprint设置的BlueprintGeneratedClass都是没有作用的，
![image](https://user-images.githubusercontent.com/73415998/178915668-c371bbc3-faa4-4b09-ba21-3f388abc9cf7.png)
![image](https://user-images.githubusercontent.com/73415998/178915706-964f373d-2432-40d7-97ec-9dcc47d39121.png)
所以如果不设置为UTypeScriptBlueprint，就走不了自己写的给他设置蓝图生成类的地方
不过我现在也遇到了打包之后还是找不到的问题，我目前是gameplaycue打包后应该是没有被加载

**Comment by lzj10** [comment]
所以我好奇的是为啥Actor可以不需要这么处理，是因为UE对Actor有特殊处理么，我没找到UE特殊处理Actor的地方

**Comment by Wangxiangyao-717** [comment]
> 所以我好奇的是为啥Actor可以不需要这么处理，是因为UE对Actor有特殊处理么，我没找到UE特殊处理Actor的地方
FKismetEditorUtilities::CreateBlueprint中的FBlueprintEditorUtils::SupportsConstructionScript，actor会为真，然后设置生成类，
![image](https://user-images.githubusercontent.com/73415998/178917276-b66ba374-25f2-4422-bfeb-feb17b3902db.png)

**Comment by lzj10** [comment]
感谢 主要是没看到这里 我去看看解决方案

**Comment by dawnarc** [comment]
@lzj10 哥们，最后你是怎么解决的，是按上面说的这种方式吗？

> 我的一个临时的办法是自己继承一个FKismetCompilerContext，然后重载他的SpawnNewClass，在里面进行判断，然后执行NewObject(Blueprint->GetOutermost(), FName(*NewClassName), RF_Public | RF_Transactional);同时使用FKismetCompilerContext::RegisterCompilerForBP注册UBlueprint::StaticClass()走你继承的FKismetCompilerContext的那个类

如果是这么改的，可否提个PR，方便大家使用，感谢！

**Comment by Wangxiangyao-717** [comment]
> @lzj10 哥们，最后你是怎么解决的，是按上面说的这种方式吗？
> 
> > 我的一个临时的办法是自己继承一个FKismetCompilerContext，然后重载他的SpawnNewClass，在里面进行判断，然后执行NewObject(Blueprint->GetOutermost(), FName(*NewClassName), RF_Public | RF_Transactional);同时使用FKismetCompilerContext::RegisterCompilerForBP注册UBlueprint::StaticClass()走你继承的FKismetCompilerContext的那个类
> 
> 如果是这么改的，可否提个PR，方便大家使用，感谢！

bro，应该是你说的方式改的，不过原来改的代码不在我手中了，现在加班加闷了，哥们可以这样改一下，><

**Comment by dawnarc** [comment]
@Wangxiangyao-717 好滴好滴，明白鸟，感谢回复 :two_hearts:

**Comment by How-invin** [comment]
![Image](https://github.com/user-attachments/assets/bdb16f7a-d549-4683-9088-7f6ea561d14e) 尝试在引擎代码里面绿皮一下是可行的
