### ISSUE TITLE
[unity] C#回调中使用递归和 super 导致崩溃

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#90]
下面整理组能够重现的demo

C# 中导出 game.Unit 类 Unit.cs 如下
```c#
namespace game {
	public class Unit {
		
		public delegate void KilledCallback(Unit attacker);
		
		public string name;
		public float HP = 100;
		public bool Alive => HP > 0;

		public event KilledCallback OnKilled;
		
		// 执行攻击，返回是否致死
		public bool Damage(Unit attacker, float amount) {
			HP -= amount;
			if (!Alive) {
				if (OnKilled != null) OnKilled(attacker);
			}
			return this.Alive != null;
		}
	}
}
```

TS 中使用该类如下，编译执行Unity将会崩溃
```ts
import { game } from "csharp";
let allUnits: GameUnit[] = [];

class GameUnit extends game.Unit {
	private _killedCallback: game.Unit.KilledCallback;

	constructor(readonly name: string) {
		super();
		// this._killedCallback = (attacker: game.Unit) => this.onKilled(attacker);
		this._killedCallback = this.onKilled.bind(this);
		this.add_OnKilled(this._killedCallback);
	}

	protected onKilled(attacker: game.Unit) {
		console.log(`${attacker.name} 杀死了 ${this.name}`);
	}
}

class BombUnit extends GameUnit {
	protected onKilled(attacker: game.Unit) {
		console.log(`${this.name} 执行爆炸操作`);
		for (const u of allUnits) {
			if (!u.Alive || u == this) continue;
			u.Damage(this, u.HP);
		}
		super.onKilled(attacker); // 注释这行就没事儿，但基类的逻辑无法复用
	}
}

export function startGame() {
	let bombs = [
		new BombUnit('托马斯'),
		new BombUnit('高登'),
		new BombUnit('艾米丽'),
	];
	bombs.forEach( b => allUnits.push(b) );
	let tms = bombs[0];
	// 托马斯玩火自焚, 伤及队友，还把 Unity 搞崩溃了！
	tms.Damage(tms, tms.HP);
}
```

**Comment by Geequlim** [comment]
Unity编辑的崩溃日志如下
<details>
========== OUTPUTTING STACK TRACE ==================

0x000002416A393A5B (Mono JIT Code) (wrapper managed-to-native) Puerts.PuertsDLL:ReturnBoolean (intptr,intptr,bool)
0x000002416A3938EB (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\NativeValueApiGeneric.cs:269] Puerts.SetValueToResultImpl:SetBoolean (intptr,intptr,bool) 
0x000002416A393791 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\DataTranslate.cs:464] Puerts.GeneralSetterManager:BooleanTranslator (intptr,Puerts.ISetValueToJs,intptr,object) 
0x000002416A392576 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\MethodReflection.cs:272] Puerts.OverloadReflectionWrap:Invoke (Puerts.CallInfo) 
0x000002416A390BC3 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\MethodReflection.cs:350] Puerts.MethodReflectionWrap:Invoke (intptr,intptr,intptr,int) 
0x000002416A3850E5 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\JsEnv.cs:188] Puerts.JsEnv:InvokeCallback (intptr,int,intptr,intptr,int) 
0x000002416A384C8B (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\StaticCallbacks.cs:21] Puerts.StaticCallbacks:JsEnvCallbackWrap (intptr,intptr,intptr,int,long) 
0x000002416A36DD73 (Mono JIT Code) (wrapper native-to-managed) Puerts.StaticCallbacks:JsEnvCallbackWrap (intptr,intptr,intptr,int,long)
0x00007FFE6780B1EF (puerts) SetLogCallback
0x00007FFE67A4504F (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67A445DE (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67A448D7 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67A44723 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67BFEE5D (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B97902 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B955BE (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B951AC (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67881E08 (puerts) std::enable_shared_from_this<v8_inspector::V8Inspector::Counters>::weak_from_this
0x00007FFE678815EF (puerts) std::enable_shared_from_this<v8_inspector::V8Inspector::Counters>::weak_from_this
0x00007FFE6785AEE7 (puerts) std::enable_shared_from_this<v8_inspector::V8Inspector::Counters>::weak_from_this
0x00007FFE67811C92 (puerts) SetLogCallback
0x00007FFE67805B23 (puerts) InvokeJSFunction
0x000002416A3A5635 (Mono JIT Code) (wrapper managed-to-native) Puerts.PuertsDLL:InvokeJSFunction (intptr,bool)
0x000002416A3A4E1B (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\GenericDelegate.cs:321] Puerts.GenericDelegate:Action<T1_REF> (T1_REF) 
0x000002416A3AA6A2 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Scripts\game\Unit.cs:16] game.Unit:Damage (game.Unit,single) 
0x000002416A3AA96F (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool__this___object_single (object,intptr,intptr,intptr)
0x00007FFE690DD690 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFE69062912 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2921] do_runtime_invoke 
0x00007FFE6906BB42 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:3073] mono_runtime_invoke_checked 
0x00007FFE6906C2D9 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:5264] mono_runtime_try_invoke_array 
0x00007FFE6906BAD6 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:5142] mono_runtime_invoke_array_checked 
0x00007FFE69010384 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\icall.c:3358] ves_icall_InternalInvoke 
0x00000241458581A6 (Mono JIT Code) (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
0x0000024145856BAB (Mono JIT Code) System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
0x000002414585686F (Mono JIT Code) System.Reflection.MethodBase:Invoke (object,object[])
0x000002416A3924CB (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\MethodReflection.cs:270] Puerts.OverloadReflectionWrap:Invoke (Puerts.CallInfo) 
0x000002416A390BC3 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\MethodReflection.cs:350] Puerts.MethodReflectionWrap:Invoke (intptr,intptr,intptr,int) 
0x000002416A3850E5 (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\JsEnv.cs:188] Puerts.JsEnv:InvokeCallback (intptr,int,intptr,intptr,int) 
0x000002416A384C8B (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\StaticCallbacks.cs:21] Puerts.StaticCallbacks:JsEnvCallbackWrap (intptr,intptr,intptr,int,long) 
0x000002416A36DD73 (Mono JIT Code) (wrapper native-to-managed) Puerts.StaticCallbacks:JsEnvCallbackWrap (intptr,intptr,intptr,int,long)
0x00007FFE6780B1EF (puerts) SetLogCallback
0x00007FFE67A4504F (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67A445DE (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67A448D7 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67A44723 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67BFEE5D (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B97902 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B97902 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B97902 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B936EA (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67C7C2A3 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B97902 (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B955BE (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67B951AC (puerts) CrashForExceptionInNonABICompliantCodeRange
0x00007FFE67881E08 (puerts) std::enable_shared_from_this<v8_inspector::V8Inspector::Counters>::weak_from_this
0x00007FFE678815EF (puerts) std::enable_shared_from_this<v8_inspector::V8Inspector::Counters>::weak_from_this
0x00007FFE6785AEE7 (puerts) std::enable_shared_from_this<v8_inspector::V8Inspector::Counters>::weak_from_this
0x00007FFE67811C92 (puerts) SetLogCallback
0x00007FFE67805B23 (puerts) InvokeJSFunction
0x000002416A3A5635 (Mono JIT Code) (wrapper managed-to-native) Puerts.PuertsDLL:InvokeJSFunction (intptr,bool)
0x000002416A3A4E1B (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Libraries\Puerts\Src\GenericDelegate.cs:321] Puerts.GenericDelegate:Action<T1_REF> (T1_REF) 
0x000002416A35996C (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Scripts\tiny\core\JavaScript.cs:37] tiny.JavaScriptLauncher:StartJavaScript () 
0x000002416A35928B (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Scripts\main.cs:9] tiny.main:StartJavaScript () 
0x000002416A0C806F (Mono JIT Code) [D:\dev\puerts-starter-kit\puerts-starter-kit\Assets\Scripts\main.cs:24] tiny.main:Update () 
0x00000241B4174D68 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFE690DD690 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFE69062912 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2921] do_runtime_invoke 
0x00007FFE6906B96F (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2968] mono_runtime_invoke 
LocalFileCache size was not reduced below threshold at path: C:/Users/Geequlim/AppData/LocalLow/Unity/Caches/GiCache. ( 11267420687 / 10737418240) 
0x00007FF68EDDAB2E (Unity) scripting_method_invoke
0x00007FF68EDD486D (Unity) ScriptingInvocation::Invoke
0x00007FF68ED9E4A5 (Unity) MonoBehaviour::CallMethodIfAvailable
0x00007FF68ED9E5B6 (Unity) MonoBehaviour::CallUpdateMethod
0x00007FF68E4361F8 (Unity) BaseBehaviourManager::CommonUpdate<BehaviourManager>
0x00007FF68E43F374 (Unity) BehaviourManager::Update
0x00007FF68E879183 (Unity) `InitPlayerLoopCallbacks'::`2'::UpdateScriptRunBehaviourUpdateRegistrator::Forward
0x00007FF68E8620F8 (Unity) ExecutePlayerLoop
0x00007FF68E8621CD (Unity) ExecutePlayerLoop
0x00007FF68E8676BC (Unity) PlayerLoop
0x00007FF68CBFE75C (Unity) PlayerLoopController::UpdateScene
0x00007FF68CBFC6F8 (Unity) Application::TickTimer
0x00007FF68D56E1C0 (Unity) MainMessageLoop
0x00007FF68D578398 (Unity) WinMain
0x00007FF690586542 (Unity) __scrt_common_main_seh
0x00007FFEC90A7C24 (KERNEL32) BaseThreadInitThunk
0x00007FFECB04D4D1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
</details>

**Comment by Geequlim** [comment]
感觉调用 super.onKilled 时栈里的东西都有问题，里面什么都不写就是OK的，我访问全局的 console.log 或者 this的属性都会崩溃
```ts
	protected onKilled(attacker: game.Unit) {
		// console.log('Hello'); // 崩溃
		// this.name; // 崩溃
		// 1 + 1; // 没问题
	}
```

**Comment by layerpsr** [comment]
经过Debug, 执行流程大致如下:
托马斯(0)  .onKilled();
高登(1)    .onKilled();
艾米丽(2)  .onKilled();
艾米丽(2)  .super.onKilled();
高登(1)    .super.onKilled();
托马斯(0)  crash...
高登(1)和艾米丽(2)是可以正常执行结束, 高登(1)执行结束后应返回托马斯(0)的okKilled的循环体, 而此时发生了crash

**Comment by layerpsr** [comment]
> 经过Debug, 执行流程大致如下:
> 托马斯(0) .onKilled();
> 高登(1) .onKilled();
> 艾米丽(2) .onKilled();
> 艾米丽(2) .super.onKilled();
> 高登(1) .super.onKilled();
> 托马斯(0) crash...
> 高登(1)和艾米丽(2)是可以正常执行结束, 高登(1)执行结束后应返回托马斯(0)的okKilled的循环体, 而此时发生了crash

我的猜测, 这里是C#和js相互调用的递归方法, 在返回递归入口(最开始的位置)时发生了crash

**Comment by layerpsr** [comment]
这里是C#和js相互调用的递归方法, 我猜测应该是在返回递归入口(最开始的位置)时发生了crash
