### ISSUE TITLE
[Unity] 1.4.0 预览版，导出工程xcode编译错误

### ISSUE THREAD

**Issue by stnaw** [Tencent/puerts#908]
## error log | 日志或报错信息 

导出工程xcode编译错误

`Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >& std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__assign_no_alias<false>(char const*, unsigned long)

Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >& std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__assign_no_alias<true>(char const*, unsigned long)

Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__assign_external(char const*)

Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__erase_external_with_move(unsigned long, unsigned long)

Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init_copy_ctor_external(char const*, unsigned long)`

## context | 环境

unity 2021.3.6 lts   
puerts 1.4.0  各个预览版本
iOS

## how to reproduce | 复现步骤
直接导出iOS工程

**Comment by zombieyang** [comment]
正在排查
如果是因为m1不得不用1.4.0，可以在build IOS的时候降级回1.3.x，目前都是兼容的

**Comment by zombieyang** [comment]
暂时将安卓、ios的v8版本都降级了以规避该问题。preview.5版本已带上
