### ISSUE TITLE
TS类中使用了fs模块之后ts类损坏

### ISSUE THREAD

**Issue by fonlylovey** [Tencent/puerts#910]
TS类中import了fs模块

然后在类成员函数中使用任意fs模块的函数以后，会导致该类损坏，哪怕这个成员函数没有被调用 。

复现步骤
1.在c++类中通过TS类的UClass创建TS类对象
2.TS类从UObject继承，在类中使用任意fs模块

**Comment by chexiongsheng** [comment]
有fs模块么？
没有的话，你这现象不就正常的么？

**Comment by Evilom** [comment]
好像是没有fs模块，装了fs-extra也是用不了

**Comment by chexiongsheng** [comment]
fs是nodejs的扩展。不是js的标准库

**Comment by VegetableWithChicken** [comment]
> 

只能使用原生支持的TS模块对吧
