### ISSUE TITLE
[Unity] @DllImport ("__Internal")

### ISSUE THREAD

**Issue by wbb21230** [Tencent/puerts#916]
[DllImport("__Internal")]
    private extern static void FunctionName();
这种有没对应typescript写法

**Comment by throw-out** [comment]
typescript调用宿主平台的方法, 你这里因为是`private`所在没有在typescript d.ts中生成声明

**Comment by wbb21230** [comment]
> typescript调用宿主平台的方法, 你这里因为是`private`所在没有在typescript d.ts中生成声明

我是说直接用typescript写，要怎么写

**Comment by zombieyang** [comment]
没明白你的需求，是要在ts里直接导入dll里的方法？
另外请在标题里标注是UE还是Unity
