### ISSUE TITLE
[[UE] ue5装relaease包无法打开

### ISSUE THREAD

**Issue by Evilom** [Tencent/puerts#924]
![image](https://user-images.githubusercontent.com/33251918/180008242-87d89bec-255f-4c2a-b2cb-d7a1506b0947.png)

![image](https://user-images.githubusercontent.com/33251918/180008325-90370371-f375-49fe-915e-59f71433e6a7.png)

**Comment by chexiongsheng** [comment]
要编译

**Comment by Evilom** [comment]
照着faq里用ide编译打开了，但是还是无法正常使用
![image](https://user-images.githubusercontent.com/33251918/180258669-5055d9fd-f903-4050-85a6-99422dd74ded.png)
