### ISSUE TITLE
[UE] I found a bug 调用TMap.Num() 有时候会进入断言 TScriptArray 的ArrayNum 不合法

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#927]
## error log | 日志或报错信息

![image](https://user-images.githubusercontent.com/5946974/180170980-380a78bf-dd2e-4c16-8098-630b952ae8d3.png)

调用堆栈
![image](https://user-images.githubusercontent.com/5946974/180171283-c3d63c4f-17e4-40da-98b4-feb985c627d1.png)

## context | 编译/运行环境
UE5.0

## how to reproduce | 复现步骤
暂时不确定

## more | 其他
猜测与返回值是TMap引用类型有关，顺便发现了ue.d.ts生成的方法签名对于返回容器引用与预期不太一样
定义了Test函数，函数参数引用有$Ref,返回值没有
![image](https://user-images.githubusercontent.com/5946974/180171814-2d2e46e1-8898-4a45-8953-161586e988ff.png)
![image](https://user-images.githubusercontent.com/5946974/180171933-6504040b-88fb-467d-9f2e-52bb0cdaa418.png)

**Comment by chexiongsheng** [comment]
你那个Test感觉就有问题吧？那个函数的c++实现是怎样的？

**Comment by lzj10** [comment]
Test只是为了测试头文件生成的 没有实现，猜测是这个方法有问题 
![image](https://user-images.githubusercontent.com/5946974/180173819-07c53648-ff62-48e0-bf64-31580ffe9dff.png)
![image](https://user-images.githubusercontent.com/5946974/180173859-8cbaf3af-f375-4653-bbab-803c1516d92c.png)

**Comment by chexiongsheng** [comment]
> Test只是为了测试头文件生成的 没有实现，猜测是这个方法有问题，但是不是毕现，感觉是ArrayNum没有初始化 不合法 什么值都有可能。 ![image](https://user-images.githubusercontent.com/5946974/180173819-07c53648-ff62-48e0-bf64-31580ffe9dff.png) ![image](https://user-images.githubusercontent.com/5946974/180173859-8cbaf3af-f375-4653-bbab-803c1516d92c.png) ![image](https://user-images.githubusercontent.com/5946974/180174085-bf1afe1f-3900-4960-925c-1c157729c75c.png) ![image](https://user-images.githubusercontent.com/5946974/180174103-25b7c42a-ad2d-4c4f-be12-87ec1f17e369.png)

你这代码应该也是有问题的，你的CharactorMapWithType插入元素时，有可能会rehash，里面的元素会无效。
你那个Test目测也是类似的问题。

**Comment by chexiongsheng** [comment]
这么写代码只是导致断言算幸运了。

**Comment by lzj10** [comment]
暂时为了安全先不允许返回由Map管理内存的引用了，后续有机会在仔细查一下
