### ISSUE TITLE
[UE] 新增c++扩展接口，有时ue.d.ts没有正确导出接口

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#929]
## detail | 详细描述
c++扩展接口
![image](https://user-images.githubusercontent.com/18215765/180387647-7dd9fc60-03e5-4713-b813-c4a93cdb7f3d.png)
编译项目，点击ue.d.ts后没有正确导出这个接口

删除了目录，Binaries，DerivedDataCache，Intermediate，Saved后，从新项目编译c++，再次点击ue.d.ts后，有导出接口
![image](https://user-images.githubusercontent.com/18215765/180388122-d8e1435a-6e63-4a70-9539-a5209ceea708.png)

UE版本: 4.26.2
Vs2022

**Comment by zhang357622852** [comment]
UE Puerts 1.0.1

**Comment by chexiongsheng** [comment]
有什么接口是根据“UE”的反射api的返回来。
所以你这问题得去UE那提。
看你的描述应该是UBT编译的问题。

**Comment by zhang357622852** [comment]
嗯嗯，好
