### ISSUE TITLE
[Unity] 导出泛型类，在ios真机下报错

### ISSUE THREAD

**Issue by cty41** [Tencent/puerts#931]
## error log | 日志或报错信息
il2cpp does not support marshaling delegates that point to generic methods、
[crash 截图](https://s3.bmp.ovh/imgs/2022/07/25/1de9bf81f7bc8c9e.jpg)
## context | 编译/运行环境
Unity_v1.3.6,ApiLevel:16
ios真机 il2cpp
## how to reproduce | 复现步骤
1.添加导出
PuertsConfig.cs
static IEnumerable<Type> Bindings
    {
        get
        {
            return new List<Type>()
            {
                typeof(TSEnvManager),
                typeof(SimpleSingletonProvider<TSEnvManager>),
            }
        }
    }
    [Binding]
    static IEnumerable<Type> DynamicBindings
    //...
2.生成cs wrap类 
+SimpleSingletonProvider_1_T__Wrap.cs
using System;
using Puerts;

namespace PuertsStaticWrap
{
    public static class SimpleSingletonProvider_1_T__Wrap<T>
    {

        [Puerts.MonoPInvokeCallback(typeof(Puerts.V8ConstructorCallback))]
        private static IntPtr Constructor(IntPtr isolate, IntPtr info, int paramLen, long data)
        {
            try
            {

    
            } catch (Exception e) {
                Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
            }
            return IntPtr.Zero;
        }
    
        [Puerts.MonoPInvokeCallback(typeof(Puerts.V8FunctionCallback))]
        private static void M_OnDestory(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
        {
            try
            {
                var obj = Puerts.Utils.GetSelf((int)data, self) as SimpleSingletonProvider<T>;
        
                {
            
                    {
                
                        obj.OnDestory();
                
                        
                        
                        
                    }
                
                }
            
            }
            catch (Exception e)
            {
                Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
            }
        }
        
        [Puerts.MonoPInvokeCallback(typeof(Puerts.V8FunctionCallback))]
        private static void F_CreateInstance(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
        {
            try
            {
                
        
                {
            
                    {
                
                        SimpleSingletonProvider<T>.CreateInstance();
                
                        
                        
                        
                    }
                
                }
            
            }
            catch (Exception e)
            {
                Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
            }
        }
        
        [Puerts.MonoPInvokeCallback(typeof(Puerts.V8FunctionCallback))]
        private static void G_Instance(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
        {
            try
            {
                
                var result = SimpleSingletonProvider<T>.Instance;
                Puerts.ResultHelper.Set((int)data, isolate, info, result);
            }
            catch (Exception e)
            {
                Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
            }
        }
            
        [Puerts.MonoPInvokeCallback(typeof(Puerts.V8FunctionCallback))]
        private static void G_HasInstance(IntPtr isolate, IntPtr info, IntPtr self, int paramLen, long data)
        {
            try
            {
                
                var result = SimpleSingletonProvider<T>.HasInstance;
                Puerts.StaticTranslate<bool>.Set((int)data, isolate, Puerts.NativeValueApi.SetValueToResult, info, result);
            }
            catch (Exception e)
            {
                Puerts.PuertsDLL.ThrowException(isolate, "c# exception:" + e.Message + ",stack:" + e.StackTrace);
            }
        }
                
        public static Puerts.TypeRegisterInfo GetRegisterInfo()
        {
            return new Puerts.TypeRegisterInfo()
            {
                BlittableCopy = false,
                Constructor = Constructor,
                Methods = new System.Collections.Generic.Dictionary<Puerts.MethodKey, Puerts.V8FunctionCallback>()
                {   
                    { new Puerts.MethodKey { Name = "OnDestory", IsStatic = false}, M_OnDestory },
                    { new Puerts.MethodKey { Name = "CreateInstance", IsStatic = true}, F_CreateInstance }
                },
                Properties = new System.Collections.Generic.Dictionary<string, Puerts.PropertyRegisterInfo>()
                {
                    
                    {"Instance", new Puerts.PropertyRegisterInfo(){ IsStatic = true, Getter = G_Instance, Setter = null} },

                    {"HasInstance", new Puerts.PropertyRegisterInfo(){ IsStatic = true, Getter = G_HasInstance, Setter = null} }
                },
                LazyMembers = new System.Collections.Generic.List<Puerts.LazyMemberRegisterInfo>()
                {   
                }
            };
        }
    
    }
}

## more | 其他
推测原因是导出的是泛型类，il2cpp无法处理？还是说我的导出写法有问题

**Comment by zombieyang** [comment]
unity版本是？

**Comment by zombieyang** [comment]
如果是unity2018，可以参见#918

**Comment by cty41** [comment]
嗯 也是2018.4.36。感谢，我看看
