### ISSUE TITLE
[Unity] 1.3.6版本生成脚本报错

### ISSUE THREAD

**Issue by junweili199** [Tencent/puerts#938]
## error log | 日志或报错信息
![_}S{ZCC_6O$KZ1$J_LD V3Y](https://user-images.githubusercontent.com/77668713/181472319-e1741e88-7101-4493-893d-6612b7b43be1.png)
![RZTBTC}`D$XV1`VFKS@~}F2](https://user-images.githubusercontent.com/77668713/181472342-812a8cc5-4a13-4a34-96d9-739a8b4760ae.png)

## context | 编译/运行环境
unity
## how to reproduce | 复现步骤
1.使用1.3.6版本
2.build

**Comment by zombieyang** [comment]
fixed in 0e1822378e1dcc6f8592382ca8a1d2ff9f411411
