### ISSUE TITLE
[UE]打开 WITHOUT_BP_NAMESPACE 后， 蓝图枚举无法使用

### ISSUE THREAD

**Issue by operatorkai** [Tencent/puerts#940]
![企业微信截图_16590105638436](https://user-images.githubusercontent.com/3296962/181726011-05452959-1a86-4332-b1d1-aaa4060219dd.png)

开启namespace时，没有问题
关闭namespace时，找不到信息
UE4.27

DeclarationGenerator.Build.cs中修改的宏：
PublicDefinitions.Add("WITHOUT_BP_NAMESPACE");

**Comment by operatorkai** [comment]
重新导出了
一个枚举蓝图TTTT放到/Content/下

有namespace时，ts中这样调用：
let ev = UE.Game.TTTT.TTTT.value;
没有问题

关闭namespace后，重新导出一下，ts里这样调用
let ev = UE.TTTT.value
运行就会报错了

**Comment by chexiongsheng** [comment]
必须报错啊

WITHOUT_BP_NAMESPACE你打开来干嘛呢？WITHOUT_BP_NAMESPACE是有的项目升级后，有太多地方要改了，给他们临时兼容用的。

通过UE.XX.YY访问蓝图是”基于”“名字空间特性“开发的新特性。WITHOUT_BP_NAMESPACE是关闭了”名字空间特性“的选项，不是让你能够选择偷懒不输入名字空间的选型。

UE蓝图加载策略是按需加载，没有名字空间信息，光凭蓝图名字怎么加载蓝图？怎么知道蓝图在哪里？

**Comment by operatorkai** [comment]
哦哈哈 以为关闭namespace是一个完整的特性

**Comment by operatorkai** [comment]
您上面说的 临时兼容用途，是说 项目升级后，最终还是应该把namespace加回来是吗

**Comment by mysticfarer** [comment]
> 您上面说的 临时兼容用途，是说 项目升级后，最终还是应该把namespace加回来是吗

是的，后续使用不能打开这个宏开关；我升级兼容性后也把这个宏开关给关闭掉了（我这边升级的适配不算复杂）
