### ISSUE TITLE
[UE] UE5.0.2 下载demo后，把puerts放到plugins下无法启动

### ISSUE THREAD

**Issue by ladyishenlong** [Tencent/puerts#943]
## detail | 详细描述
the following modules are missing or built with a different engine version
jsEnv
DeclarationGenerator
Puerts
PuertsEditor

**Comment by chexiongsheng** [comment]
源码，要编译。demo readme有说明

**Comment by ladyishenlong** [comment]
https://github.com/chexiongsheng/puerts_fps_demo
我就是按照这个做的
执行了node enable_puerts_module.js tsconfig也生成了，然后打开就报上面的错

**Comment by ladyishenlong** [comment]
我自己搭建项目也试过，也会有这样的错。其他的unlua 或者 unreal.js则是很顺利地跑起来了

**Comment by chexiongsheng** [comment]
你用这个deme也不会报那个错：https://github.com/chexiongsheng/puerts_unreal_demo
unlua 或者 unreal.js提供的都是C++项目。puerts_unreal_demo也是。
而puerts_fps_demo是纯蓝图项目，需要自行编译Plugins。
