### ISSUE TITLE
[UE] 生成ue.d.ts时 报错内存访问异常

### ISSUE THREAD

**Issue by cc-Gao** [Tencent/puerts#945]
## Detail | 细节描述
我在学习puerts时，使用他人demo仓库时，使用editor生成ue.d.ts时，发生内存访问异常
![image](https://user-images.githubusercontent.com/49053992/182275544-4b61cf80-65e4-408c-8d3a-3a3fe5d9ce0d.png)
报错如上图
是此处VariableInfo 被误写作 PropertyInfo 了么？
代码位置：`unreal/Puerts/Source/DeclarationGenerator/Private/TemplateBindingGenerator.cpp`
## context | 编译/运行环境
ue版本：4.27.2
使用的demo仓库：https://github.com/chexiongsheng/puerts_unreal_demo
IDE：Microsoft Visual Studio Professional 2019 版本 16.11.17

**Comment by chexiongsheng** [comment]
是有问题

**Comment by chexiongsheng** [comment]
你可以提个PR过来
