### ISSUE TITLE
[Unity] suggestion 创建了一个http服务 打包好以后无效

### ISSUE THREAD

**Issue by Jike0628** [Tencent/puerts#948]
Unity 创建了一个http服务 打包好以后无效

**Comment by zombieyang** [comment]
用的是Node.js plugin吗？
打包到什么平台？

**Comment by Jike0628** [comment]
window11 其他有效果 就http服务没效果

**Comment by Jike0628** [comment]
编辑器中有效果

**Comment by zombieyang** [comment]
手机端现版本暂不支持node.js API

**Comment by Jike0628** [comment]
pc window11

**Comment by zombieyang** [comment]
目前nodejs默认只有editor平台可用。

你可以改一下Editor/Plugins/x86_64的meta，让它能在standalone的情况下作用，同时删除掉Runtime/Plugins里的那个plugin

**Comment by Jike0628** [comment]
1.4 版本的无效 1.3.7测试有效

**Comment by zombieyang** [comment]
现已支持手机平台Node.js
