### ISSUE TITLE
错误: 泛型方法Method<T>() where T: Delegate生成代码时报错

### ISSUE THREAD

**Issue by layerpsr** [Tencent/puerts#95]
泛型方法Method<T>() where T: Delegate, 参数T继承自Delegate时, 图示红框处报空异常
![Snipaste_2020-11-20_11-07-30](https://user-images.githubusercontent.com/45587825/99753128-a5783b00-2b20-11eb-9aaf-10e6fde26ceb.png)

**Comment by chexiongsheng** [comment]
你修复这问题的PR呢？

**Comment by layerpsr** [comment]
请你在下次更新的时候修复一下吧!
因为这种泛型参数并不是实际类型, 所以我的思路是判断type.IsGenericParameter
![Snipaste_2020-11-20_17-43-13](https://user-images.githubusercontent.com/45587825/99785262-e6d80d00-2b57-11eb-899c-bd40f71c7730.png)
