### ISSUE TITLE
[UE] suggestion unreal的 SourceMap有什么参考怎么使用吗

### ISSUE THREAD

**Issue by justinlm** [Tencent/puerts#953]
## detail | 详细描述
您好，我们也有在 UE 项目当中使用 Puerts 的计划，请问你们是怎么解决调试堆栈问题的呢？

我们遇到的问题是，调试堆栈，包括行号等都是 JS 的，而不是 TS 的，所以调试起来会不太方便。

 https://github.com/Tencent/puerts/issues/172 提到 Unity 可以自己写一个脚本，利用 SourceMap 将调试堆栈重定向至 C# 的控制台，我们尝试在 UE 上参考这种做法。不知道您的项目是不是也是用类似的方法，还是有其他做法呢？

**Comment by chexiongsheng** [comment]
你先看明白https://github.com/Tencent/puerts/issues/172是怎么解决的。
简单来说，source-map-support直接就支持了。
但问题是source-map-support需要读取SourceMap文件，调用的是nodejs的api。
所以你提供用到的几个api即可。

**Comment by justinlm** [comment]
确实，按照 #172 的方式在unreal也提供一下类似的实现就可以了
