### ISSUE TITLE
[UE] Linux-arm64 运行时，v8启动报错 

### ISSUE THREAD

**Issue by tiansen-hub** [Tencent/puerts#955]
## error log | 日志或报错信息
[2022.08.17-08.15.51:850][  0]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to access memory at address 0x0000000000000000

[2022.08.17-08.15.51:850][  0]LogCore: Fatal error!

0x000000000a2894d8 MyProjectServer!v8::internal::(anonymous namespace)::GetPageTableInitializer()()
0x000000000a28948c MyProjectServer!v8::internal::GetPlatformPageAllocator()()
0x000000000a0278e0 MyProjectServer!v8::internal::IsolateAllocator::IsolateAllocator(v8::internal::IsolateAllocationMode)()
0x0000000009e170cc MyProjectServer!v8::internal::Isolate::New(v8::internal::IsolateAllocationMode)()
0x0000000009d51f14 MyProjectServer!v8::Isolate::New(v8::Isolate::CreateParams const&)()
0x0000000009c2a8d0 MyProjectServer!puerts::FJsEnvImpl::FJsEnvImpl(std::__1::shared_ptr<puerts::IJSModuleLoader>, std::__1::shared_ptr<puerts::ILogger>, int, void*, void*) [D:/Arm64Package/MyProject/Plugins/Typescript/PuertsUnreal/Source/JsEnv/Private/JsEnvImpl.cpp:332]
0x0000000009c2a32c MyProjectServer!puerts::FJsEnvImpl::FJsEnvImpl(FString const&) [D:/Arm64Package/MyProject/Plugins/Typescript/PuertsUnreal/Source/JsEnv/Private/JsEnvImpl.cpp:112]
0x0000000009c299c8 MyProjectServer!puerts::FJsEnv::FJsEnv(FString const&) [D:/Arm64Package/MyProject/Plugins/Typescript/PuertsUnreal/Source/JsEnv/Private/JsEnv.cpp:16]
0x0000000002f08870 MyProjectServer!FKTSLaunchHelper::Start(FString const&, FString const&) [D:/Arm64Package/MyProject/Plugins/Typescript/KTSFramework/Source/KTSFramework/Private/KTSLaunchHelper.cpp:25]
0x0000000002f08718 MyProjectServer!UKTSFramework::OnStartGame(UKGameInstance*) [D:/Arm64Package/MyProject/Plugins/Typescript/KTSFramework/Source/KTSFramework/Private/KTSFramework.cpp:38]
0x0000000002ee0720 MyProjectServer!UKGameInstance::FImplement::StartGame() [D:/Arm64Package/MyProject/Plugins/KFramework/Source/KFramework/Private/KGameInstance.cpp:73]
0x0000000002eb3894 MyProjectServer!FEngineLoop::Init() [D:/IronDesert/UnrealEngine/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:4302]
0x0000000002ebde30 MyProjectServer!GuardedMain(char16_t const*) [D:/IronDesert/UnrealEngine/Engine/Source/./Runtime/Launch/Private/Launch.cpp:163]
0x0000000009af0b8c MyProjectServer!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [D:/IronDesert/UnrealEngine/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
0x0000ffffb9202e10 libc.so.6!__libc_start_main(+0xe7)
0x0000000002eb244c MyProjectServer!_start()

[2022.08.17-08.15.51:853][  0]LogExit: Executing StaticShutdownAfterError
## context | 编译/运行环境
Linux    arm64
## how to reproduce | 复现步骤
1. 基于 Linux arm64平台，构建该平台 ds 包
2. 将ds包跑在 Linux arm64的云服务器上报错

**Comment by tiansen-hub** [comment]
![03aZrcX8nU](https://user-images.githubusercontent.com/57481995/185072470-126d664c-0023-4d9c-ad71-4fdf4d0cde41.jpg)

**Comment by chexiongsheng** [comment]
看上去不太可能。
GetPageTableInitializer是这定义的
~~~c++
DEFINE_LAZY_LEAKY_OBJECT_GETTER(PageAllocatorInitializer,
                                GetPageTableInitializer)
~~~
DEFINE_LAZY_LEAKY_OBJECT_GETTER是这么定义的
~~~c++
template <typename T>
class LeakyObject {
 public:
  template <typename... Args>
  explicit LeakyObject(Args&&... args) {
    new (&storage_) T(std::forward<Args>(args)...);
  }

  T* get() { return reinterpret_cast<T*>(&storage_); }

 private:
  typename std::aligned_storage<sizeof(T), alignof(T)>::type storage_;

  DISALLOW_COPY_AND_ASSIGN(LeakyObject);
};

// Define a function which returns a pointer to a lazily initialized and never
// destructed object of type T.
#define DEFINE_LAZY_LEAKY_OBJECT_GETTER(T, FunctionName, ...) \
  T* FunctionName() {                                         \
    static ::v8::base::LeakyObject<T> object{__VA_ARGS__};    \
    return object.get();                                      \
  }
~~~

没看出哪里有空指针的可能。

**Comment by tiansen-hub** [comment]
那这大概是啥问题，能看出来不老大，我这下 v8 的源码呢，下载了好长时间了，执行fetch v8总是报错，能大概分析下是啥问题吗

**Comment by tiansen-hub** [comment]
@chexiongsheng 老大，那这大概是啥问题，我这正在下 v8 的源码，下载了好长时间了，执行fetch v8总是报错，上面我的这个崩溃问题能分析下是啥原因吗

**Comment by chexiongsheng** [comment]
相关代码我已经贴完整了，简单来说就是看代码不可能出现那样的崩溃。
你是直接打包你们项目？你试试只用最简单的，比如puerts提供的demo来试试看：https://github.com/chexiongsheng/puerts_unreal_demo

**Comment by tiansen-hub** [comment]
@chexiongsheng 嗯，我正在编译demo，然后试试，另外老大我看浩哥正在升级v8到9.4，另外 M1 的 arm64 也开始支持了，我想LinuxArm64 能不能也顺便支持下，我这也同时调试看看

**Comment by tiansen-hub** [comment]
> 相关代码我已经贴完整了，简单来说就是看代码不可能出现那样的崩溃。 你是直接打包你们项目？你试试只用最简单的，比如puerts提供的demo来试试看：https://github.com/chexiongsheng/puerts_unreal_demo

demo我跑了下，也是crash，我把日志打了个包，老大看下，另外我修改的demo的地方我提了个PR老大你看下我改的地方对不对，看完之后把那个PR关了就行
[crashinfo-puerts_unreal_demo.zip](https://github.com/Tencent/puerts/files/9379899/crashinfo-puerts_unreal_demo.zip)

**Comment by chexiongsheng** [comment]
你可以拿9.4的试试：https://github.com/puerts/backend-v8/actions/runs/2902113479
不过这次编译mac都失败了，上个commit mac都可以的，不过不影响，你可以下载Artifacts，拿linux arm的试试看。

**Comment by chexiongsheng** [comment]
这是包含了linux arm64的9.4版本v8：https://github.com/puerts/backend-v8/releases/tag/V8_9.4.146.24_0825

**Comment by tiansen-hub** [comment]
车老大，上次那个在linux arm64 上跑puerts的崩溃问题还是存在，想问下现在官方有没有计划支持下arm64的正式版本

**Comment by chexiongsheng** [comment]
没有环境。
我建议试试在你的linux arm64上编译下v8。有可能是编译环境和运行环境不一致导致的。
用这个脚本
https://github.com/puerts/backend-v8/blob/master/linux_arm64.sh
需要解决下脚本在非github action环境下的一些问题。
有可能需要科学上网。

**Comment by chexiongsheng** [comment]
这有个官方的指引：https://v8.dev/docs/compile-arm64

**Comment by chexiongsheng** [comment]
可以试试这个项目：https://github.com/bnoordhuis/v8-cmake
我在虚拟机上的arm64 linux可以编译通过。

要注意几点：
1、master编译不过，用这个commit（刚好是arm64编译的支持）：https://github.com/bnoordhuis/v8-cmake/commit/8dfb23f20c466f290d454c4cd63ef93baa49765c
2、得手动把 `set(is-arm64 0)`改为`set(is-arm64 1)`，它那判断不生效
3、python3.10会编译不过，我换3.9可以；

**Comment by qui-kwe** [comment]
@tiansen-hub 你这边用https://github.com/bnoordhuis/v8-cmake完成编译了吗？puerts在linux arm64上跑通了吗？
