### ISSUE TITLE
[UE] 运行时delegate触发时，崩溃。

### ISSUE THREAD

**Issue by dmydb** [Tencent/puerts#960]
## detail | 详细描述

D/UE4     : [2022.08.22-11.55.50:578][923]LogOutputDevice: Warning: 
D/UE4     : 
D/UE4     : Script Stack (2 frames):
D/UE4     : BP_PlayerController_Simulates_M9_C.ExecuteUbergraph_BP_PlayerController_Simulates_M9
D/UE4     : BP_PlayerController_Simulates_M9_C.ReceiveTick
D/UE4     : 
D/UE4     : Assertion failed: ArrayIndex < ArrayDim [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Public\UObject/UnrealType.h] [Line: 367] 
D/UE4     : 
D/UE4     : [2022.08.22-11.55.51:026][923]Assertion failed: ArrayIndex < ArrayDim [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Public\UObject/UnrealType.h] [Line: 367] 
D/UE4     : 
D/UE4     : [2022.08.22-11.55.51:026][923]LogAndroid: Error: === Critical error: ===
D/UE4     : [2022.08.22-11.55.51:026][923]LogAndroid: Error: 
D/UE4     : [2022.08.22-11.55.51:026][923]LogAndroid: Error: Assertion failed: ArrayIndex < ArrayDim [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Public\UObject/UnrealType.h] [Line: 367] 
D/UE4     : [2022.08.22-11.55.51:026][923]LogAndroid: Error: 
D/UE4     : [2022.08.22-11.55.51:026][923]LogAndroid: Error: [Callstack] 0x0000007BA4411994 libUE4.so(0x0000000008F8F994)!FDebug::CheckVerifyFailedImpl(char const*, char const*, int, char16_t const*, ...)  []
D/UE4     : [2022.08.22-11.55.51:026][923]LogAndroid: Error: [Callstack] 0x0000007BA35C4818 libUE4.so(0x0000000008142818)!puerts::FFunctionTranslator::CallJs(v8::Isolate*, v8::Local<v8::Context>&, v8::Local<v8::Function>, v8::Local<v8::Value>, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA3617DE4 libUE4.so(0x0000000008195DE4)!puerts::FJsEnvImpl::InvokeDelegateCallback(UDynamicDelegateProxy*, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA35482BC libUE4.so(0x00000000080C62BC)!UDynamicDelegateProxy::ProcessEvent(UFunction*, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA310CD28 libUE4.so(0x0000000007C8AD28)!void TScriptDelegate<FWeakObjectPtr>::ProcessDelegate<UObject>(void*) const  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA310CB18 libUE4.so(0x0000000007C8AB18)!void TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>(void*) const  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A5C2E0 libUE4.so(0x00000000095DA2E0)!FCallDelegateHelper::CallMulticastDelegate(FFrame&)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A4F590 libUE4.so(0x00000000095CD590)!ProcessLocalScriptFunction(UObject*, FFrame&, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A4EF48 libUE4.so(0x00000000095CCF48)!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*))  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A50424 libUE4.so(0x00000000095CE424)!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A4F590 libUE4.so(0x00000000095CD590)!ProcessLocalScriptFunction(UObject*, FFrame&, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A4F294 libUE4.so(0x00000000095CD294)!UObject::ProcessInternal(UObject*, FFrame&, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA487CAE4 libUE4.so(0x00000000093FAAE4)!UFunction::Invoke(UObject*, FFrame&, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA4A54C70 libUE4.so(0x00000000095D2C70)!UObject::ProcessEvent(UFunction*, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA736FF94 libUE4.so(0x000000000BEEDF94)!AActor::ProcessEvent(UFunction*, void*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA847B578 libUE4.so(0x000000000CFF9578)!AActor::ReceiveTick(float)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA7371118 libUE4.so(0x000000000BEEF118)!AActor::Tick(float)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA7ED9DEC libUE4.so(0x000000000CA57DEC)!APlayerController::TickActor(float, ELevelTick, FActorTickFunction&)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA736CB5C libUE4.so(0x000000000BEEAB5C)!FActorTickFunction::ExecuteTick(float, ELevelTick, ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA82BD58C libUE4.so(0x000000000CE3B58C)!FTickFunctionTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA82BCF4C libUE4.so(0x000000000CE3AF4C)!TGraphTask<FTickFunctionTask>::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA41EA3F4 libUE4.so(0x0000000008D683F4)!FNamedTaskThread::ProcessTasksNamedThread(int, bool)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA41E8C90 libUE4.so(0x0000000008D66C90)!FNamedTaskThread::ProcessTasksUntilQuit(int)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA41E6484 libUE4.so(0x0000000008D64484)!FTaskGraphImplementation::WaitUntilTasksComplete(TArray<TRefCountPtr<FGraphEvent>, TInlineAllocator<4u, TSizedDefaultAllocator<32> > > const&, ENamedThreads::Type)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA82B6034 libUE4.so(0x000000000CE34034)!FTickTaskSequencer::ReleaseTickGroup(ETickingGroup, bool)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA82B12FC libUE4.so(0x000000000CE2F2FC)!FTickTaskManager::RunTickGroup(ETickingGroup, bool)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA7AEA258 libUE4.so(0x000000000C668258)!UWorld::Tick(ELevelTick, float)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA79176DC libUE4.so(0x000000000C4956DC)!UGameEngine::Tick(float, bool)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA3079048 libUE4.so(0x0000000007BF7048)!FEngineLoop::Tick()  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA306F118 libUE4.so(0x0000000007BED118)!AndroidMain(android_app*)  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA307FC9C libUE4.so(0x0000000007BFDC9C)!android_main()  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007BA30AC738 libUE4.so(0x0000000007C2A738)![Unknown]()  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007CCEFADB14 libc.so(0x00000000000EFB14)![Unknown]()  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: [Callstack] 0x0000007CCEF4A35C libc.so(0x000000000008C35C)![Unknown]()  []
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: 
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: 
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: 
D/UE4     : [2022.08.22-11.55.51:027][923]LogAndroid: Error: 
D/UE4     : [2022.08.22-11.55.51:038][923]LogExit: Executing StaticShutdownAfterError
D/UE4     : [2022.08.22-11.55.51:042][923]LogAndroid: FAndroidMisc::RequestExit(1)

## 运行环境
只有在手机端会崩溃。
![image](https://user-images.githubusercontent.com/36908144/186174116-870f6738-c1bc-412f-aa57-32c3101b1425.png)
这么修改就可以好了不崩溃了。
请问是怎么造成的？业务侧代码应该怎么修改可以避免.

**Comment by chexiongsheng** [comment]
崩溃的地方
~~~c++
FORCEINLINE void* ContainerVoidPtrToValuePtrInternal(void* ContainerPtr, int32 ArrayIndex) const
	{
		check(ArrayIndex < ArrayDim);
		check(ContainerPtr);

		if (0)
		{
			// in the future, these checks will be tested if the property is NOT relative to a UClass
			check(!GetOwner<UClass>()); // Check we are _not_ calling this on a direct child property of a UClass, you should pass in a UObject* in that case
		}

		return (uint8*)ContainerPtr + Offset_Internal + ElementSize * ArrayIndex;
	}
~~~
ArrayIndex传的是0，正常来说UFunction的参数Property，至少为1，怀疑FFunctionTranslator缓存的Property过时导致的。你加的那两句其实是根据SignatureFunction重新创建FFunctionTranslator，如果不崩了证明确实FFunctionTranslator缓存的Property过时了。
但问题是SignatureFunction是用WeakObjectPtr引用着，WeakObjectPtr是有效的，所以大概率SignatureFunction并没有被释放然后重新分配。
结合如上两点，比较怀疑是对该Delegate绑定后，Delegate的SignatureFunction里的内容发生了变化。

**Comment by chexiongsheng** [comment]
或者是FFunctionTranslator被非法修改了。

**Comment by chexiongsheng** [comment]
在 https://github.com/Tencent/puerts/pull/975 处理了
