### ISSUE TITLE
[[UE] 通过事件从TS端向蓝图传递TArray<自定义蓝图结构体>会导致崩溃

### ISSUE THREAD

**Issue by kefengwei** [Tencent/puerts#962]
## error log | 日志或报错信息
![image](https://user-images.githubusercontent.com/4326865/186918338-772a2fa8-33d9-487e-bb76-cecc8320adf3.png)

## context | 编译/运行环境
从github拉取的最新版本
## how to reproduce | 复现步骤
1.在蓝图声明一个自定义结构体 `MyStructure`,只要其中包含Int类型或Float类型,且不是属性的第一位.如图:
![image](https://user-images.githubusercontent.com/4326865/186919189-c3febca9-b57b-4958-840c-3882a59e6add.png)

2. 在蓝图中声明一个Custom Event, 其参数是 `TArray<MyStructure>`
![image](https://user-images.githubusercontent.com/4326865/186919696-8059f0ce-82f9-4271-a585-08f6c34be0b0.png)

3. 在TS端构建Array, 并且添加1个以上的元素传入Custom Event调用.
![image](https://user-images.githubusercontent.com/4326865/186920070-c3289f84-9d91-4194-8f37-2627f56f16f6.png)
4. 崩溃

## more | 其他

经排查, `FScriptArrayWrapper` 在处理 `<蓝图结构体>`类型的`Add`时,通过 `Inner->Property->GetSize()`所获取的长度不是Struct的真实长度.
![image](https://user-images.githubusercontent.com/4326865/186921387-7b39b1be-8abb-4682-9937-c1fd42d28b2e.png)

**Comment by chexiongsheng** [comment]
Property->GetSize()返回的数字没把字节对齐计算进去。
而我用结构体的TArray测试，至少默认情况下有考虑字节对齐。

**Comment by kefengwei** [comment]
![image](https://user-images.githubusercontent.com/4326865/187158247-0fe8f197-0c38-4e40-868c-d49822edf010.png)
这个结构体对齐后的Size应该是24,而`Property->GetSize()`获取到的是20.

**Comment by chexiongsheng** [comment]
更新试试

**Comment by kefengwei** [comment]
已测试,能正常工作了.感谢!
