### ISSUE TITLE
[Unity] 如何支持dotween的DOTween.To的getter和setter接口到ts层

### ISSUE THREAD

**Issue by cty41** [Tencent/puerts#970]
## detail | 详细描述
dotween的to函数：
`
public static TweenerCore<float, float, FloatOptions> To(DOGetter<float> getter, DOSetter<float> setter, float endValue, float duration);
public delegate T DOGetter<out T>();
public delegate void DOSetter<in T>(T pNewValue);
`
faq说有写：参数含ref，out的修饰，目前尚未支持，解决办法：填写issues来提需求
但没搜到相关的issues。
有什么办法可以对这类的的delegate 进行支持么？感谢
目前版本是：unity 2018.4.36f， puerts版本是 1.3.6

**Comment by zombieyang** [comment]
FAQ那段说的是C#调用ts的情况，你这是ts调用C#

泛型函数是可以调用的，参见$genericMethod方法（从test里找一下例子），但它同样也受ILCPP的AOT限制。因此目前最佳实践还是写一个adaptor函数给ts用
