### ISSUE TITLE
[document] case collection | 案例收集 - WebGL

### ISSUE THREAD

**Issue by zombieyang** [Tencent/puerts#980]
## detail | 详细描述
I provided WebGL runtime some time ago,( see https://github.com/zombieyang/puerts_unity_webgl_demo for details). Now is easy to publish the game or app to a web page.

Because PuerTS is based on JS, web games/apps are easier to communicate with Unity after the above step of conversion. 
Puer documentation needs the community to contribute relevant examples to demonstrate the potential of this new capability.

**Comment by zombieyang** [comment]
https://gitee.com/puerts/puerts/issues/I5PX87
本Issue中文描述在gitee上且开启了悬赏（尝试一下）

**Comment by Hill1942** [comment]
案例名：活动回放系统

在腾讯游戏中，我们使用Puerts开发了一些营销活动；通常，每一个营销活动一般只会在线1-2周的时间，而随着日积月累，会有很多这样的营销活动，但这些活动下线后就不能以可交互的形式再查看了。

对此，我们的运营希望有一个统一的地方能方便地展示出过往的所有营销活动。基于该诉求，我们借助Puerts On WebGL的能力，把我们的营销活动做了WebGL平台的assetbundle打包，直接运行在了浏览器中，并且这些活动可直接交互，和游戏内体验基本一致。下面是效果示意图：

Case name: Active Playback System

In Tencent Games, we use Puerts to develop some in-game events. Usually, each event is generally only online for 1-2 weeks and as time goes on there will be many events. However, we cannot viewed these events in an interactive form when they go offline .

Our operation hopes to have a place to easily view all these past in-game events. Based on this demand, we package our in-game events to assetbundle in webgl platform and leverage the capabilities of Puerts On WebGL, these events can run directly in the browser. And not only that, we can directly interact with these events which is basically the same as the in-game experience. See the following

<img width="1490" alt="WeChatWorkScreenshot_510ed39d-d84a-4aac-be33-dada3f37ef0a" src="https://user-images.githubusercontent.com/3347541/192134584-264fc372-2fe6-424c-9cb5-c40feeca0143.png">
