### ISSUE TITLE
[UE] puerts::object添加对Iosolate的生命周期跟踪

### ISSUE THREAD

**Issue by chexiongsheng** [Tencent/puerts#982]
## detail | 详细描述
目前puerts::object（含std::function这种依赖puerts::object的对象），其销毁时机必须在其关联对象的虚拟机销毁前。
可以添加Iosolate的生命周期跟踪，去除这个约束。

**Comment by lzj10** [comment]
这个可以  之前由于在PIE模式下和其他模式下 继承引擎的虚拟机销毁的时机不一致 所以保存的std::function 清理的时候崩溃还查了好久
