### ISSUE TITLE
[UE] suggestion 打包Android报错，node_modules/@types/node/assert.d.ts (12,72): '{' or ';' expected.

### ISSUE THREAD

**Issue by justinlm** [Tencent/puerts#985]
## detail | 详细描述

打包Android的时候，会报下面的错位，有大佬知道是什么问题吗
``` ts
UATHelper: Packaging (Android (ASTC)): Puerts: Error: (0x00000A2ED77C4830)   Error E:/Projects/Client/node_modules/@types/node/assert.d.ts (12,72): '{' or ';' expected.
```

**Comment by chexiongsheng** [comment]
你用的是nodejs版本的puerts么？不是就不用安装nodejs的@type。
如果是nodejs版本的puerts，可以在这里升级下ts版本：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/PuertsEditor/package.json

**Comment by justinlm** [comment]
好的，谢谢大佬，确实是 ts版本的问题，升级完就好了
