### ISSUE TITLE
[UE] 关于Mixin和继承引擎的Ts类不会调用js原生的构造函数 的疑问

### ISSUE THREAD

**Issue by lzj10** [Tencent/puerts#987]
通过Mixin和继承引擎类创建的tsClass不会调用到原生的constructor，导致ts类的属性默认值以及通过箭头方式定义的成员函数无法被初始化。而通过通常方式定义的函数，在回调时必须通过闭包才能访问this指针。但是如果委托参数过多书写起来很麻烦，需要在某些条件下需要对委托进行解绑还需要实现对闭包函数进行存储。所以想问下有没有什么简单的解决方案。

由于OnActorHitFunNew函数不是通过箭头定义，所以如果需要在回调中使用this指针 需要通过闭包，并且参数需要手动传递
![image](https://user-images.githubusercontent.com/5946974/190361308-a290f23a-917d-4ffa-85a1-ffc08166cc0c.png)

能看到箭头函数是在constructor中实例化的
![image](https://user-images.githubusercontent.com/5946974/190359365-1a0137d4-1934-4966-8dbd-df2ef0a4972d.png)

**Comment by chexiongsheng** [comment]
Mixin是对被扩展类的增强，它本身的构造函数是无意义的，如果你之前用过C#，可以类比extension methods。
