### ISSUE TITLE
[Unity] 多维数组比如 int[,] 是不是会被生成为 int[] ?

### ISSUE THREAD

**Issue by Joycraft** [Tencent/puerts#99]
我这里, Unity 的 C# 里面

`public int[,] mapData { get; set; }`

结果生成的时候变成了

`obj.mapData = argHelper.Get<int[]>(false);`

实际上应该是

`obj.mapData = argHelper.Get<int[,]>(false);`

所有这种 xxx[,] 类型的参数都变成了xxx[ ], 不过不大确实是否原版是这样的

**Comment by Joycraft** [comment]
在 `Editor/Generator.cs` 里面的 `static void FillEnumInfo(DataTypeInfo info, Type type)` 方法里面加上
```
if(type.IsArray && type.GetArrayRank() > 1) {
   info.TypeName = info.TypeName.Replace("[]","[" + new String(',',type.GetArrayRank()-1)) + "]";
}
```
可以临时修复下 C# 报错的问题, 但是不清楚 Typescript 那边如何处理这种类型或者其他的影响.

**Comment by chexiongsheng** [comment]
ts也是一样，可以通过Array的接口对其操作
