### ISSUE TITLE
[UE] demo 无法触发热更

### ISSUE THREAD

**Issue by scutDavid** [Tencent/puerts#994]
## detail | 详细描述
下载Demo https://github.com/chexiongsheng/puerts_unreal_demo 学习时，发现热更不起效， 引擎版本4.26， 是需要开启哪些宏吗
![image](https://user-images.githubusercontent.com/30872025/190643330-f0ded174-72dd-4a06-9f60-06be4b782f64.png)

**Comment by scutDavid** [comment]
断点查看确实有跑到 hot_relaod.js发送新脚本的逻辑，但就是不生效，比如更改在actor 的 tick里打印的日志。
![image](https://user-images.githubusercontent.com/30872025/190941629-8eba9789-c641-4678-90c8-cfd0077fd03a.png)

**Comment by chexiongsheng** [comment]
你断点的是另外一个虚拟机。
[puerts_unreal_demo](https://github.com/chexiongsheng/puerts_unreal_demo)里的例子是用户创建的虚拟机，这个例子没启用热更。

**Comment by scutDavid** [comment]
那么用户创建的虚拟机 得怎样才能启用热更呢

**Comment by chexiongsheng** [comment]
用SourceFileWatcher，使用参考这：https://github.com/puerts/EasyEditorPlugin/blob/master/Source/EasyEditorPlugin/Private/EasyEditorPlugin.cpp#L255

**Comment by scutDavid** [comment]
get， 感谢大佬！
