### ISSUE TITLE
[UE] 关于1.0.2的require使用问题

### ISSUE THREAD

**Issue by zhang357622852** [Tencent/puerts#995]
## detail | 详细描述
由1.0.1更新到1.0.2这个require无法使用了？
![image](https://user-images.githubusercontent.com/18215765/190862663-c9cfb463-80bb-49ac-a1d7-1727ad92a3c3.png)

原来的require声明在
![image](https://user-images.githubusercontent.com/18215765/190862694-9fc0c3c9-8986-4ce8-b719-15d3ac98ca95.png)
在1.0.2中移除了

在1.0.2中，我要如何继续使用require?

**Comment by zhang357622852** [comment]
目前我的先把删除的require给补上去，项目跑起来也没啥问题？不知道有啥隐患嘛？或是对后续更新插件不便？
![image](https://user-images.githubusercontent.com/18215765/190864223-0e46794e-a957-476d-b244-37f3e16f2259.png)

**Comment by chexiongsheng** [comment]
现在支持nodejs了。
这个定义会和nodejs的冲突，而且一般来说用不上，就去掉了。有需要自己加下即可。
